In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.metrics import mean_squared_error

import mlflow

mlflow.set_tracking_uri("sqlite:///mlflow.db")

mlflow.set_experiment("nyc-taxi-experiment")

MlflowException: Detected out-of-date database schema (found version 97727af70f4d, but expected bd07f7e963c5). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.

In [ ]:
import pickle

In [2]:
! pip freeze | grep scikit-learn

scikit-learn==1.1.1

In [2]:
#!pip install pyarrow

In [23]:
# data = pd.read_parquet("data/yellow_tripdata_2022-01.parquet")
data = pd.read_parquet("https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2021-01.parquet")
data.shape

(76518, 20)

### Q1 Read the data for January. How many columns are there?

In [24]:
print(f"The data has {data.shape[1]} columns")

The data has 20 columns

In [25]:
# val = pd.read_parquet("data/yellow_tripdata_2022-02.parquet")
val = pd.read_parquet("https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2021-02.parquet")
val.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2021-02-01 00:34:03,2021-02-01 00:51:58,N,1.0,130,205,5.0,3.66,14.0,0.5,0.5,10.00,0.0,None,0.3,25.30,1.0,1.0,0.00
1,2,2021-02-01 00:04:00,2021-02-01 00:10:30,N,1.0,152,244,1.0,1.10,6.5,0.5,0.5,0.00,0.0,None,0.3,7.80,2.0,1.0,0.00
2,2,2021-02-01 00:18:51,2021-02-01 00:34:06,N,1.0,152,48,1.0,4.93,16.5,0.5,0.5,0.00,0.0,None,0.3,20.55,2.0,1.0,2.75
3,2,2021-02-01 00:53:27,2021-02-01 01:11:41,N,1.0,152,241,1.0,6.70,21.0,0.5,0.5,0.00,0.0,None,0.3,22.30,2.0,1.0,0.00
4,2,2021-02-01 00:57:46,2021-02-01 01:06:44,N,1.0,75,42,1.0,1.89,8.5,0.5,0.5,2.45,0.0,None,0.3,12.25,1.0,1.0,0.00

In [26]:
data.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2021-01-01 00:15:56,2021-01-01 00:19:52,N,1.0,43,151,1.0,1.01,5.5,0.5,0.5,0.00,0.0,None,0.3,6.80,2.0,1.0,0.00
1,2,2021-01-01 00:25:59,2021-01-01 00:34:44,N,1.0,166,239,1.0,2.53,10.0,0.5,0.5,2.81,0.0,None,0.3,16.86,1.0,1.0,2.75
2,2,2021-01-01 00:45:57,2021-01-01 00:51:55,N,1.0,41,42,1.0,1.12,6.0,0.5,0.5,1.00,0.0,None,0.3,8.30,1.0,1.0,0.00
3,2,2020-12-31 23:57:51,2021-01-01 00:04:56,N,1.0,168,75,1.0,1.99,8.0,0.5,0.5,0.00,0.0,None,0.3,9.30,2.0,1.0,0.00
4,2,2021-01-01 00:16:36,2021-01-01 00:16:40,N,2.0,265,265,3.0,0.00,-52.0,0.0,-0.5,0.00,0.0,None,-0.3,-52.80,3.0,1.0,0.00

In [27]:
data.columns

Index(['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime',
       'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID',
       'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'ehail_fee', 'improvement_surcharge',
       'total_amount', 'payment_type', 'trip_type', 'congestion_surcharge'],
      dtype='object')

In [28]:
def extract_trip_time(df):
    df['duration'] = df.lpep_dropoff_datetime - df.lpep_pickup_datetime
    df['duration'] = df['duration'].apply(lambda x: x.total_seconds() / 60 ) # Time in minutes
    return df

### Q2 What's the standard deviation of the trips duration in January?

In [29]:
new_dat = extract_trip_time(data)
ans = new_dat['duration'].std()
print(f"The standard deviation of the trip duration is {ans:.2f}")

The standard deviation of the trip duration is 59.34

In [30]:
def remove_outlier(df):
    df = df[(df['duration'] >= 1) & (df['duration'] <= 60)]
    return df

### Q3 What fraction of the records left after you dropped the outliers?

In [31]:
data_without_outlier = remove_outlier(new_dat)
df_num_rows = new_dat.shape[0]
df_less_outlier_num_rows = data_without_outlier.shape[0]
percentage_left = (df_less_outlier_num_rows/df_num_rows)*100
print(f"The fraction of the records left after I dropped the outliers is {percentage_left:.2f}")

The fraction of the records left after I dropped the outliers is 96.59

In [32]:
category_columns = ['PULocationID', 'DOLocationID']

In [33]:
train_data = remove_outlier(extract_trip_time(data))
test_data = remove_outlier(extract_trip_time(val))

In [34]:
train_dicts = train_data[category_columns].fillna(-1).astype('int').astype('str').to_dict(orient="records")
val_dicts = test_data[category_columns].fillna(-1).astype('int').astype('str').to_dict(orient="records")

In [35]:
dv = DictVectorizer()
X_train = dv.fit_transform(train_dicts)
X_val = dv.transform(val_dicts)

In [36]:
X_train.shape, X_val.shape

((73908, 506), (61921, 506))

### Q4 What's the dimensionality of this matrix (number of columns)?

In [37]:
print(f"The dimensionality of this matrix is {X_train.shape[1]}")

The dimensionality of this matrix is 506

In [38]:

y_train = train_data["duration"].values
y_val = test_data["duration"].values

In [39]:
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_train)

### Q5 What's the RMSE on train?

In [40]:
err = mean_squared_error(y_pred, y_train, squared=False)
err
print(f"The RMSE of on the train data is {err:.2f} ")

The RMSE of on the train data is 9.78

### Q6 What's the RMSE on validation?

In [41]:
y_pred_1 = lr.predict(X_val)
err_1= mean_squared_error(y_pred_1, y_val, squared=False)
err_1
print(f"The RMSE on the validation data is {err_1:.2f}")

The RMSE on the validation data is 10.47

In [43]:
with open('models/lin_reg.bin', 'wb') as f_out:
    pickle.dump((dv, lr), f_out)

In [46]:
with mlflow.start_run():
    mlflow.set_tag("developer", "muhammed")
    mlflow.log_param("train_data", "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2021-01.parquet")
    mlflow.log_param("val_data", "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2021-02.parquet")
    alpha = 0.01
    mlflow.log_param("alpha", alpha)
    las = Lasso(alpha)
    las.fit(X_train, y_train)
    y_pred = las.predict(X_train)

    err = mean_squared_error(y_pred, y_train, squared=False)
    print(f"The RMSE of on the train data is {err:.2f} ")
    mlflow.log_metric("rmse", err)

The RMSE of on the train data is 10.18

In [51]:
import xgboost as xgb

from hyperopt import fmin, tpe, hp, STATUS_OK, Trials
from hyperopt.pyll import scope

In [52]:
train = xgb.DMatrix(X_train, label=y_train)
valid = xgb.DMatrix(X_val, label=y_val)

In [53]:
def objective(params):
    with mlflow.start_run():
        mlflow.set_tag("model", "xgboost")
        mlflow.log_params(params)
        booster = xgb.train(
            params=params,
            dtrain=train,
            num_boost_round=1000,
            evals=[(valid, 'validation')],
            early_stopping_rounds=50
        )
        y_pred = booster.predict(valid)
        rmse = mean_squared_error(y_val, y_pred, squared=False)
        mlflow.log_metric("rmse", rmse)

    return {'loss': rmse, 'status': STATUS_OK}

In [54]:
search_space = {
    'max_depth': scope.int(hp.quniform('max_depth', 4, 100, 1)),
    'learning_rate': hp.loguniform('learning_rate', -3, 0),
    'reg_alpha': hp.loguniform('reg_alpha', -5, -1),
    'reg_lambda': hp.loguniform('reg_lambda', -6, -1),
    'min_child_weight': hp.loguniform('min_child_weight', -1, 3),
    'objective': 'reg:linear',
    'seed': 42
}

best_result = fmin(
    fn=objective,
    space=search_space,
    algo=tpe.suggest,
    max_evals=50,
    trials=Trials()
)

  0%|          | 0/50 [00:00<?, ?trial/s, best loss=?]

[11:49:56] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[0]	validation-rmse:19.70712
[1]	validation-rmse:18.39572
[2]	validation-rmse:17.23537
[3]	validation-rmse:16.20204
[4]	validation-rmse:15.30215
[5]	validation-rmse:14.49933
[6]	validation-rmse:13.80024
[7]	validation-rmse:13.18260
[8]	validation-rmse:12.65225
[9]	validation-rmse:12.20105
[10]	validation-rmse:11.77810
[11]	validation-rmse:11.43326
[12]	validation-rmse:11.09537
[13]	validation-rmse:10.79229
[14]	validation-rmse:10.57349
[15]	validation-rmse:10.36342
[16]	validation-rmse:10.18472
[17]	validation-rmse:10.03871
[18]	validation-rmse:9.85522
[19]	validation-rmse:9.74746
[20]	validation-rmse:9.64505
[21]	validation-rmse:9.51625
[22]	validation-rmse:9.43821
[23]	validation-rmse:9.36574
[24]	validation-rmse:9.26500
[25]	validation-rmse:9.14101
[26]	validation-rmse:9.08446
[27]	validation-rmse:9.00450
[28]	validation-rmse:8.96382
[29]	validation-rmse:8.91100
[30]	validation-rmse:8.87275
[31]	validation-rmse:8.83146
[32]	validation-rmse:8.80528
[33]	validation-rmse:8.77707
[34]	validation-rmse:8.74965
[35]	validation-rmse:8.69550
[36]	validation-rmse:8.66984
[37]	validation-rmse:8.62973
[38]	validation-rmse:8.59004
[39]	validation-rmse:8.55143
[40]	validation-rmse:8.52313
[41]	validation-rmse:8.49617
[42]	validation-rmse:8.46795
[43]	validation-rmse:8.42170
[44]	validation-rmse:8.40706
[45]	validation-rmse:8.38878
[46]	validation-rmse:8.37069
[47]	validation-rmse:8.33983
[48]	validation-rmse:8.32355
[49]	validation-rmse:8.29118
[50]	validation-rmse:8.27770
[51]	validation-rmse:8.26025
[52]	validation-rmse:8.23161
[53]	validation-rmse:8.21397
[54]	validation-rmse:8.19227
[55]	validation-rmse:8.18309
[56]	validation-rmse:8.16982
[57]	validation-rmse:8.13814
[58]	validation-rmse:8.10982
[59]	validation-rmse:8.10063
[60]	validation-rmse:8.09047
[61]	validation-rmse:8.08115
[62]	validation-rmse:8.06152
[63]	validation-rmse:8.03696
[64]	validation-rmse:8.01891
[65]	validation-rmse:8.00554
[66]	validation-rmse:7.99933
[67]	validation-rmse:7.97457
[68]	validation-rmse:7.96285
[69]	validation-rmse:7.94530
[70]	validation-rmse:7.94095
[71]	validation-rmse:7.93103
[72]	validation-rmse:7.90564
[73]	validation-rmse:7.89353
[74]	validation-rmse:7.86141
[75]	validation-rmse:7.85714
[76]	validation-rmse:7.84513
[77]	validation-rmse:7.83436
[78]	validation-rmse:7.82542
[79]	validation-rmse:7.81518
[80]	validation-rmse:7.80532
[81]	validation-rmse:7.79567
[82]	validation-rmse:7.79075
[83]	validation-rmse:7.78295
[84]	validation-rmse:7.77264
[85]	validation-rmse:7.76937
[86]	validation-rmse:7.76062
[87]	validation-rmse:7.74784
[88]	validation-rmse:7.72245
[89]	validation-rmse:7.71618
[90]	validation-rmse:7.70824
[91]	validation-rmse:7.70060
[92]	validation-rmse:7.69191
[93]	validation-rmse:7.68717
[94]	validation-rmse:7.68225
[95]	validation-rmse:7.67338
[96]	validation-rmse:7.66633
[97]	validation-rmse:7.66139
[98]	validation-rmse:7.65668
[99]	validation-rmse:7.65160
[100]	validation-rmse:7.64433
[101]	validation-rmse:7.63912
[102]	validation-rmse:7.63683
[103]	validation-rmse:7.63422
[104]	validation-rmse:7.62334
[105]	validation-rmse:7.61408
[106]	validation-rmse:7.60997
[107]	validation-rmse:7.59999
[108]	validation-rmse:7.59838
[109]	validation-rmse:7.59268
[110]	validation-rmse:7.58923
[111]	validation-rmse:7.58553
[112]	validation-rmse:7.57231
[113]	validation-rmse:7.56855
[114]	validation-rmse:7.56630
[115]	validation-rmse:7.56224
[116]	validation-rmse:7.55318
[117]	validation-rmse:7.54869
[118]	validation-rmse:7.54653
[119]	validation-rmse:7.54432
[120]	validation-rmse:7.53175
[121]	validation-rmse:7.52665
[122]	validation-rmse:7.52423
[123]	validation-rmse:7.52156
[124]	validation-rmse:7.51323
[125]	validation-rmse:7.51066
[126]	validation-rmse:7.50823
[127]	validation-rmse:7.50576
[128]	validation-rmse:7.50460
[129]	validation-rmse:7.50085
[130]	validation-rmse:7.49958
[131]	validation-rmse:7.49570
[132]	validation-rmse:7.49397
[133]	validation-rmse:7.49234
[134]	validation-rmse:7.49029
[135]	validation-rmse:7.48965
[136]	validation-rmse:7.48591
[137]	validation-rmse:7.48291
[138]	validation-rmse:7.48195
[139]	validation-rmse:7.47847
[140]	validation-rmse:7.47700
[141]	validation-rmse:7.47451
[142]	validation-rmse:7.47404
[143]	validation-rmse:7.47237
[144]	validation-rmse:7.46877
[145]	validation-rmse:7.46716
[146]	validation-rmse:7.46478
[147]	validation-rmse:7.46425
[148]	validation-rmse:7.46123
[149]	validation-rmse:7.46016
[150]	validation-rmse:7.45864
[151]	validation-rmse:7.45520
[152]	validation-rmse:7.45082
[153]	validation-rmse:7.44884
[154]	validation-rmse:7.44680
[155]	validation-rmse:7.44605
[156]	validation-rmse:7.44513
[157]	validation-rmse:7.44458
[158]	validation-rmse:7.44107
[159]	validation-rmse:7.44006
[160]	validation-rmse:7.43984
[161]	validation-rmse:7.43932
[162]	validation-rmse:7.43799
[163]	validation-rmse:7.43527
[164]	validation-rmse:7.43350
[165]	validation-rmse:7.43276
[166]	validation-rmse:7.43232
[167]	validation-rmse:7.43198
[168]	validation-rmse:7.43182
[169]	validation-rmse:7.43120
[170]	validation-rmse:7.43036
[171]	validation-rmse:7.42788
[172]	validation-rmse:7.42582
[173]	validation-rmse:7.42323
[174]	validation-rmse:7.42230
[175]	validation-rmse:7.42202
[176]	validation-rmse:7.42138
[177]	validation-rmse:7.42019
[178]	validation-rmse:7.41678
[179]	validation-rmse:7.41631
[180]	validation-rmse:7.41572
[181]	validation-rmse:7.41577
[182]	validation-rmse:7.41371
[183]	validation-rmse:7.41271
[184]	validation-rmse:7.41284
[185]	validation-rmse:7.40908
[186]	validation-rmse:7.40883
[187]	validation-rmse:7.40844
[188]	validation-rmse:7.40853
[189]	validation-rmse:7.40779
[190]	validation-rmse:7.40764
[191]	validation-rmse:7.40783
[192]	validation-rmse:7.40685
[193]	validation-rmse:7.40603
[194]	validation-rmse:7.40546
[195]	validation-rmse:7.40540
[196]	validation-rmse:7.40559
[197]	validation-rmse:7.40464
[198]	validation-rmse:7.40448
[199]	validation-rmse:7.40122
[200]	validation-rmse:7.40117
[201]	validation-rmse:7.40005
[202]	validation-rmse:7.39881
[203]	validation-rmse:7.39883
[204]	validation-rmse:7.39789
[205]	validation-rmse:7.39750
[206]	validation-rmse:7.39708
[207]	validation-rmse:7.39672
[208]	validation-rmse:7.39676
[209]	validation-rmse:7.39674
[210]	validation-rmse:7.39674
[211]	validation-rmse:7.39687
[212]	validation-rmse:7.39680
[213]	validation-rmse:7.39678
[214]	validation-rmse:7.39629
[215]	validation-rmse:7.39620
[216]	validation-rmse:7.39597
[217]	validation-rmse:7.39537
[218]	validation-rmse:7.39406
[219]	validation-rmse:7.39392
[220]	validation-rmse:7.39364
[221]	validation-rmse:7.39314
[222]	validation-rmse:7.39346
[223]	validation-rmse:7.39289
[224]	validation-rmse:7.39289
[225]	validation-rmse:7.39228
[226]	validation-rmse:7.39207
[227]	validation-rmse:7.39183
[228]	validation-rmse:7.39150
[229]	validation-rmse:7.39109
[230]	validation-rmse:7.39106
[231]	validation-rmse:7.39058
[232]	validation-rmse:7.39042
[233]	validation-rmse:7.39009
[234]	validation-rmse:7.39007
[235]	validation-rmse:7.38977
[236]	validation-rmse:7.39014
[237]	validation-rmse:7.38985
[238]	validation-rmse:7.38805
[239]	validation-rmse:7.38775
[240]	validation-rmse:7.38746
[241]	validation-rmse:7.38668
[242]	validation-rmse:7.38669
[243]	validation-rmse:7.38673
[244]	validation-rmse:7.38668
[245]	validation-rmse:7.38667
[246]	validation-rmse:7.38659
[247]	validation-rmse:7.38614
[248]	validation-rmse:7.38560
[249]	validation-rmse:7.38409
[250]	validation-rmse:7.38364
[251]	validation-rmse:7.38301
[252]	validation-rmse:7.38236
[253]	validation-rmse:7.38266
[254]	validation-rmse:7.38260
[255]	validation-rmse:7.38257
[256]	validation-rmse:7.38254
[257]	validation-rmse:7.38256
[258]	validation-rmse:7.38249
[259]	validation-rmse:7.38239
[260]	validation-rmse:7.38238
[261]	validation-rmse:7.38085
[262]	validation-rmse:7.38040
[263]	validation-rmse:7.38022
[264]	validation-rmse:7.37947
[265]	validation-rmse:7.37924
[266]	validation-rmse:7.37898
[267]	validation-rmse:7.37895
[268]	validation-rmse:7.37836
[269]	validation-rmse:7.37813
[270]	validation-rmse:7.37706
[271]	validation-rmse:7.37681
[272]	validation-rmse:7.37661
[273]	validation-rmse:7.37580
[274]	validation-rmse:7.37527
[275]	validation-rmse:7.37464
[276]	validation-rmse:7.37472
[277]	validation-rmse:7.37401
[278]	validation-rmse:7.37351
[279]	validation-rmse:7.37310
[280]	validation-rmse:7.37303
[281]	validation-rmse:7.37291
[282]	validation-rmse:7.37274
[283]	validation-rmse:7.37280
[284]	validation-rmse:7.37255
[285]	validation-rmse:7.37176
[286]	validation-rmse:7.37152
[287]	validation-rmse:7.37164
[288]	validation-rmse:7.37177
[289]	validation-rmse:7.37124
[290]	validation-rmse:7.37078
[291]	validation-rmse:7.37089
[292]	validation-rmse:7.37113
[293]	validation-rmse:7.37079
[294]	validation-rmse:7.37051
[295]	validation-rmse:7.37011
[296]	validation-rmse:7.37032
[297]	validation-rmse:7.37001
[298]	validation-rmse:7.37002
[299]	validation-rmse:7.36975
[300]	validation-rmse:7.37011
[301]	validation-rmse:7.37015
[302]	validation-rmse:7.37013
[303]	validation-rmse:7.37011
[304]	validation-rmse:7.37023
[305]	validation-rmse:7.36967
[306]	validation-rmse:7.36917
[307]	validation-rmse:7.36913
[308]	validation-rmse:7.36907
[309]	validation-rmse:7.36830
[310]	validation-rmse:7.36814
[311]	validation-rmse:7.36770
[312]	validation-rmse:7.36749
[313]	validation-rmse:7.36740
[314]	validation-rmse:7.36703
[315]	validation-rmse:7.36728
[316]	validation-rmse:7.36669
[317]	validation-rmse:7.36673
[318]	validation-rmse:7.36648
[319]	validation-rmse:7.36647
[320]	validation-rmse:7.36642
[321]	validation-rmse:7.36583
[322]	validation-rmse:7.36583
[323]	validation-rmse:7.36586
[324]	validation-rmse:7.36596
[325]	validation-rmse:7.36569
[326]	validation-rmse:7.36507
[327]	validation-rmse:7.36470
[328]	validation-rmse:7.36501
[329]	validation-rmse:7.36483
[330]	validation-rmse:7.36491
[331]	validation-rmse:7.36469
[332]	validation-rmse:7.36483
[333]	validation-rmse:7.36481
[334]	validation-rmse:7.36470
[335]	validation-rmse:7.36434
[336]	validation-rmse:7.36430
[337]	validation-rmse:7.36398
[338]	validation-rmse:7.36429
[339]	validation-rmse:7.36427
[340]	validation-rmse:7.36389
[341]	validation-rmse:7.36320
[342]	validation-rmse:7.36311
[343]	validation-rmse:7.36297
[344]	validation-rmse:7.36284
[345]	validation-rmse:7.36239
[346]	validation-rmse:7.36230
[347]	validation-rmse:7.36212
[348]	validation-rmse:7.36219
[349]	validation-rmse:7.36219
[350]	validation-rmse:7.36204
[351]	validation-rmse:7.36170
[352]	validation-rmse:7.36173
[353]	validation-rmse:7.36153
[354]	validation-rmse:7.36129
[355]	validation-rmse:7.36086
[356]	validation-rmse:7.36048
[357]	validation-rmse:7.36078
[358]	validation-rmse:7.36070
[359]	validation-rmse:7.36039
[360]	validation-rmse:7.36005
[361]	validation-rmse:7.36025
[362]	validation-rmse:7.36010
[363]	validation-rmse:7.36007
[364]	validation-rmse:7.35998
[365]	validation-rmse:7.35999
[366]	validation-rmse:7.35996
[367]	validation-rmse:7.36001
[368]	validation-rmse:7.35993
[369]	validation-rmse:7.35995
[370]	validation-rmse:7.35990
[371]	validation-rmse:7.35963
[372]	validation-rmse:7.35937
[373]	validation-rmse:7.35915
[374]	validation-rmse:7.35892
[375]	validation-rmse:7.35857
[376]	validation-rmse:7.35835
[377]	validation-rmse:7.35831
[378]	validation-rmse:7.35841
[379]	validation-rmse:7.35821
[380]	validation-rmse:7.35783
[381]	validation-rmse:7.35768
[382]	validation-rmse:7.35763
[383]	validation-rmse:7.35749
[384]	validation-rmse:7.35760
[385]	validation-rmse:7.35723
[386]	validation-rmse:7.35712
[387]	validation-rmse:7.35710
[388]	validation-rmse:7.35701
[389]	validation-rmse:7.35689
[390]	validation-rmse:7.35681
[391]	validation-rmse:7.35669
[392]	validation-rmse:7.35653
[393]	validation-rmse:7.35664
[394]	validation-rmse:7.35628
[395]	validation-rmse:7.35633
[396]	validation-rmse:7.35640
[397]	validation-rmse:7.35598
[398]	validation-rmse:7.35589
[399]	validation-rmse:7.35581
[400]	validation-rmse:7.35563
[401]	validation-rmse:7.35559
[402]	validation-rmse:7.35523
[403]	validation-rmse:7.35487
[404]	validation-rmse:7.35440
[405]	validation-rmse:7.35439
[406]	validation-rmse:7.35397
[407]	validation-rmse:7.35366
[408]	validation-rmse:7.35388
[409]	validation-rmse:7.35376
[410]	validation-rmse:7.35344
[411]	validation-rmse:7.35328
[412]	validation-rmse:7.35297
[413]	validation-rmse:7.35262
[414]	validation-rmse:7.35253
[415]	validation-rmse:7.35252
[416]	validation-rmse:7.35242
[417]	validation-rmse:7.35198
[418]	validation-rmse:7.35194
[419]	validation-rmse:7.35209
[420]	validation-rmse:7.35199
[421]	validation-rmse:7.35163
[422]	validation-rmse:7.35139
[423]	validation-rmse:7.35144
[424]	validation-rmse:7.35129
[425]	validation-rmse:7.35106
[426]	validation-rmse:7.35126
[427]	validation-rmse:7.35134
[428]	validation-rmse:7.35130
[429]	validation-rmse:7.35120
[430]	validation-rmse:7.35129
[431]	validation-rmse:7.35092
[432]	validation-rmse:7.35101
[433]	validation-rmse:7.35092
[434]	validation-rmse:7.35068
[435]	validation-rmse:7.35052
[436]	validation-rmse:7.35028
[437]	validation-rmse:7.35029
[438]	validation-rmse:7.35049
[439]	validation-rmse:7.35034
[440]	validation-rmse:7.35025
[441]	validation-rmse:7.35031
[442]	validation-rmse:7.35036
[443]	validation-rmse:7.35024
[444]	validation-rmse:7.34979
[445]	validation-rmse:7.34960
[446]	validation-rmse:7.34932
[447]	validation-rmse:7.34898
[448]	validation-rmse:7.34885
[449]	validation-rmse:7.34874
[450]	validation-rmse:7.34867
[451]	validation-rmse:7.34832
[452]	validation-rmse:7.34799
[453]	validation-rmse:7.34808
[454]	validation-rmse:7.34822
[455]	validation-rmse:7.34810
[456]	validation-rmse:7.34808
[457]	validation-rmse:7.34806
[458]	validation-rmse:7.34795
[459]	validation-rmse:7.34787
[460]	validation-rmse:7.34781
[461]	validation-rmse:7.34763
[462]	validation-rmse:7.34754
[463]	validation-rmse:7.34719
[464]	validation-rmse:7.34717
[465]	validation-rmse:7.34708
[466]	validation-rmse:7.34713
[467]	validation-rmse:7.34718
[468]	validation-rmse:7.34689
[469]	validation-rmse:7.34683
[470]	validation-rmse:7.34663
[471]	validation-rmse:7.34666
[472]	validation-rmse:7.34626
[473]	validation-rmse:7.34635
[474]	validation-rmse:7.34641
[475]	validation-rmse:7.34649
[476]	validation-rmse:7.34650
[477]	validation-rmse:7.34626
[478]	validation-rmse:7.34593
[479]	validation-rmse:7.34600
[480]	validation-rmse:7.34600
[481]	validation-rmse:7.34588
[482]	validation-rmse:7.34572
[483]	validation-rmse:7.34549
[484]	validation-rmse:7.34554
[485]	validation-rmse:7.34549
[486]	validation-rmse:7.34556
[487]	validation-rmse:7.34537
[488]	validation-rmse:7.34543
[489]	validation-rmse:7.34530
[490]	validation-rmse:7.34538
[491]	validation-rmse:7.34527
[492]	validation-rmse:7.34521
[493]	validation-rmse:7.34499
[494]	validation-rmse:7.34496
[495]	validation-rmse:7.34480
[496]	validation-rmse:7.34447
[497]	validation-rmse:7.34438
[498]	validation-rmse:7.34434
[499]	validation-rmse:7.34421
[500]	validation-rmse:7.34417
[501]	validation-rmse:7.34391
[502]	validation-rmse:7.34387
[503]	validation-rmse:7.34398
[504]	validation-rmse:7.34394
[505]	validation-rmse:7.34396
[506]	validation-rmse:7.34378
[507]	validation-rmse:7.34355
[508]	validation-rmse:7.34331
[509]	validation-rmse:7.34329
[510]	validation-rmse:7.34327
[511]	validation-rmse:7.34335
[512]	validation-rmse:7.34315
[513]	validation-rmse:7.34277
[514]	validation-rmse:7.34274
[515]	validation-rmse:7.34285
[516]	validation-rmse:7.34284
[517]	validation-rmse:7.34290
[518]	validation-rmse:7.34278
[519]	validation-rmse:7.34256
[520]	validation-rmse:7.34272
[521]	validation-rmse:7.34248
[522]	validation-rmse:7.34218
[523]	validation-rmse:7.34190
[524]	validation-rmse:7.34184
[525]	validation-rmse:7.34180
[526]	validation-rmse:7.34151
[527]	validation-rmse:7.34126
[528]	validation-rmse:7.34105
[529]	validation-rmse:7.34111
[530]	validation-rmse:7.34111
[531]	validation-rmse:7.34115
[532]	validation-rmse:7.34117
[533]	validation-rmse:7.34120
[534]	validation-rmse:7.34102
[535]	validation-rmse:7.34079
[536]	validation-rmse:7.34098
[537]	validation-rmse:7.34085
[538]	validation-rmse:7.34083
[539]	validation-rmse:7.34056
[540]	validation-rmse:7.34053
[541]	validation-rmse:7.34039
[542]	validation-rmse:7.34056
[543]	validation-rmse:7.34041
[544]	validation-rmse:7.34050
[545]	validation-rmse:7.34021
[546]	validation-rmse:7.34031
[547]	validation-rmse:7.34000
[548]	validation-rmse:7.33997
[549]	validation-rmse:7.33981
[550]	validation-rmse:7.33952
[551]	validation-rmse:7.33952
[552]	validation-rmse:7.33937
[553]	validation-rmse:7.33931
[554]	validation-rmse:7.33903
[555]	validation-rmse:7.33882
[556]	validation-rmse:7.33850
[557]	validation-rmse:7.33831
[558]	validation-rmse:7.33838
[559]	validation-rmse:7.33839
[560]	validation-rmse:7.33830
[561]	validation-rmse:7.33810
[562]	validation-rmse:7.33793
[563]	validation-rmse:7.33773
[564]	validation-rmse:7.33741
[565]	validation-rmse:7.33735
[566]	validation-rmse:7.33730
[567]	validation-rmse:7.33734
[568]	validation-rmse:7.33712
[569]	validation-rmse:7.33687
[570]	validation-rmse:7.33666
[571]	validation-rmse:7.33668
[572]	validation-rmse:7.33686
[573]	validation-rmse:7.33658
[574]	validation-rmse:7.33634
[575]	validation-rmse:7.33649
[576]	validation-rmse:7.33623
[577]	validation-rmse:7.33624
[578]	validation-rmse:7.33604
[579]	validation-rmse:7.33602
[580]	validation-rmse:7.33599
[581]	validation-rmse:7.33594
[582]	validation-rmse:7.33603
[583]	validation-rmse:7.33595
[584]	validation-rmse:7.33598
[585]	validation-rmse:7.33590
[586]	validation-rmse:7.33558
[587]	validation-rmse:7.33545
[588]	validation-rmse:7.33533
[589]	validation-rmse:7.33543
[590]	validation-rmse:7.33528
[591]	validation-rmse:7.33487
[592]	validation-rmse:7.33493
[593]	validation-rmse:7.33469
[594]	validation-rmse:7.33464
[595]	validation-rmse:7.33452
[596]	validation-rmse:7.33451
[597]	validation-rmse:7.33437
[598]	validation-rmse:7.33422
[599]	validation-rmse:7.33415
[600]	validation-rmse:7.33398
[601]	validation-rmse:7.33377
[602]	validation-rmse:7.33377
[603]	validation-rmse:7.33390
[604]	validation-rmse:7.33378
[605]	validation-rmse:7.33392
[606]	validation-rmse:7.33392
[607]	validation-rmse:7.33399
[608]	validation-rmse:7.33395
[609]	validation-rmse:7.33399
[610]	validation-rmse:7.33378
[611]	validation-rmse:7.33335
[612]	validation-rmse:7.33321
[613]	validation-rmse:7.33340
[614]	validation-rmse:7.33327
[615]	validation-rmse:7.33305
[616]	validation-rmse:7.33282
[617]	validation-rmse:7.33261
[618]	validation-rmse:7.33261
[619]	validation-rmse:7.33244
[620]	validation-rmse:7.33235
[621]	validation-rmse:7.33252
[622]	validation-rmse:7.33260
[623]	validation-rmse:7.33260
[624]	validation-rmse:7.33252
[625]	validation-rmse:7.33246
[626]	validation-rmse:7.33228
[627]	validation-rmse:7.33189
[628]	validation-rmse:7.33175
[629]	validation-rmse:7.33180
[630]	validation-rmse:7.33192
[631]	validation-rmse:7.33186
[632]	validation-rmse:7.33131
[633]	validation-rmse:7.33129
[634]	validation-rmse:7.33125
[635]	validation-rmse:7.33106
[636]	validation-rmse:7.33091
[637]	validation-rmse:7.33084
[638]	validation-rmse:7.33065
[639]	validation-rmse:7.33070
[640]	validation-rmse:7.33054
[641]	validation-rmse:7.33055
[642]	validation-rmse:7.33037
[643]	validation-rmse:7.33033
[644]	validation-rmse:7.33050
[645]	validation-rmse:7.33023
[646]	validation-rmse:7.33017
[647]	validation-rmse:7.33004
[648]	validation-rmse:7.32981
[649]	validation-rmse:7.32965
[650]	validation-rmse:7.32953
[651]	validation-rmse:7.32941
[652]	validation-rmse:7.32936
[653]	validation-rmse:7.32931
[654]	validation-rmse:7.32928
[655]	validation-rmse:7.32931
[656]	validation-rmse:7.32923
[657]	validation-rmse:7.32902
[658]	validation-rmse:7.32897
[659]	validation-rmse:7.32908
[660]	validation-rmse:7.32895
[661]	validation-rmse:7.32896
[662]	validation-rmse:7.32877
[663]	validation-rmse:7.32834
[664]	validation-rmse:7.32841
[665]	validation-rmse:7.32828
[666]	validation-rmse:7.32832
[667]	validation-rmse:7.32838
[668]	validation-rmse:7.32822

[11:56:22] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:10.23188
[2]	validation-rmse:9.53056
[3]	validation-rmse:9.24265
[4]	validation-rmse:9.06931
[5]	validation-rmse:8.98247
[6]	validation-rmse:8.92512
[7]	validation-rmse:8.67630
[8]	validation-rmse:8.61384
[9]	validation-rmse:8.57605
[10]	validation-rmse:8.54069
[11]	validation-rmse:8.49741
[12]	validation-rmse:8.46264
[13]	validation-rmse:8.43905
[14]	validation-rmse:8.41399
[15]	validation-rmse:8.40906
[16]	validation-rmse:8.38513
[17]	validation-rmse:8.37239
[18]	validation-rmse:8.35906
[19]	validation-rmse:8.35372
[20]	validation-rmse:8.34054
[21]	validation-rmse:8.33155
[22]	validation-rmse:8.31879
[23]	validation-rmse:8.30010
[24]	validation-rmse:8.28318
[25]	validation-rmse:8.27011
[26]	validation-rmse:8.25176
[27]	validation-rmse:8.22796
[28]	validation-rmse:8.21917
[29]	validation-rmse:8.21229
[30]	validation-rmse:8.20058
[31]	validation-rmse:8.19260
[32]	validation-rmse:8.18456
[33]	validation-rmse:8.17619
[34]	validation-rmse:8.16893
[35]	validation-rmse:8.16180
[36]	validation-rmse:8.15426
[37]	validation-rmse:8.14861
[38]	validation-rmse:8.14626
[39]	validation-rmse:8.13891
[40]	validation-rmse:8.13396
[41]	validation-rmse:8.12968
[42]	validation-rmse:8.12528
[43]	validation-rmse:8.12230
[44]	validation-rmse:8.11975
[45]	validation-rmse:8.11430
[46]	validation-rmse:8.10697
[47]	validation-rmse:8.10159
[48]	validation-rmse:8.09755
[49]	validation-rmse:8.08914
[50]	validation-rmse:8.08532
[51]	validation-rmse:8.08260
[52]	validation-rmse:8.07963
[53]	validation-rmse:8.07310
[54]	validation-rmse:8.07123
[55]	validation-rmse:8.06788
[56]	validation-rmse:8.06368
[57]	validation-rmse:8.06042
[58]	validation-rmse:8.05655
[59]	validation-rmse:8.05399
[60]	validation-rmse:8.04998
[61]	validation-rmse:8.04675
[62]	validation-rmse:8.03973
[63]	validation-rmse:8.03752
[64]	validation-rmse:8.03169
[65]	validation-rmse:8.03120
[66]	validation-rmse:8.02766
[67]	validation-rmse:8.02654
[68]	validation-rmse:8.01824
[69]	validation-rmse:8.01358
[70]	validation-rmse:8.01009
[71]	validation-rmse:8.00620
[72]	validation-rmse:8.00426
[73]	validation-rmse:8.00311
[74]	validation-rmse:8.00119
[75]	validation-rmse:7.99970
[76]	validation-rmse:7.99794
[77]	validation-rmse:7.99606
[78]	validation-rmse:7.99486
[79]	validation-rmse:7.99467
[80]	validation-rmse:7.98990
[81]	validation-rmse:7.98622
[82]	validation-rmse:7.98248
[83]	validation-rmse:7.97903
[84]	validation-rmse:7.97078
[85]	validation-rmse:7.96800
[86]	validation-rmse:7.96130
[87]	validation-rmse:7.95999
[88]	validation-rmse:7.95460
[89]	validation-rmse:7.95124
[90]	validation-rmse:7.94812
[91]	validation-rmse:7.94223
[92]	validation-rmse:7.93903
[93]	validation-rmse:7.93141
[94]	validation-rmse:7.92796
[95]	validation-rmse:7.92229
[96]	validation-rmse:7.92192
[97]	validation-rmse:7.91806
[98]	validation-rmse:7.91598
[99]	validation-rmse:7.90978
[100]	validation-rmse:7.90617
[101]	validation-rmse:7.90671
[102]	validation-rmse:7.90107
[103]	validation-rmse:7.89728
[104]	validation-rmse:7.89370
[105]	validation-rmse:7.89155
[106]	validation-rmse:7.89135
[107]	validation-rmse:7.88871
[108]	validation-rmse:7.88748
[109]	validation-rmse:7.88638
[110]	validation-rmse:7.88492
[111]	validation-rmse:7.88151
[112]	validation-rmse:7.88040
[113]	validation-rmse:7.87537
[114]	validation-rmse:7.87413
[115]	validation-rmse:7.87107
[116]	validation-rmse:7.86823
[117]	validation-rmse:7.86738
[118]	validation-rmse:7.86458
[119]	validation-rmse:7.86054
[120]	validation-rmse:7.85838
[121]	validation-rmse:7.85631
[122]	validation-rmse:7.85096
[123]	validation-rmse:7.84526
[124]	validation-rmse:7.84131
[125]	validation-rmse:7.83543
[126]	validation-rmse:7.83109
[127]	validation-rmse:7.82588
[128]	validation-rmse:7.82518
[129]	validation-rmse:7.82016
[130]	validation-rmse:7.81752
[131]	validation-rmse:7.81674
[132]	validation-rmse:7.81458
[133]	validation-rmse:7.81244
[134]	validation-rmse:7.81212
[135]	validation-rmse:7.80593
[136]	validation-rmse:7.80033
[137]	validation-rmse:7.79352
[138]	validation-rmse:7.79039
[139]	validation-rmse:7.78863
[140]	validation-rmse:7.78464
[141]	validation-rmse:7.78439
[142]	validation-rmse:7.78144
[143]	validation-rmse:7.78110
[144]	validation-rmse:7.77817
[145]	validation-rmse:7.77634
[146]	validation-rmse:7.77372
[147]	validation-rmse:7.77335
[148]	validation-rmse:7.76945
[149]	validation-rmse:7.76769
[150]	validation-rmse:7.76634
[151]	validation-rmse:7.76474
[152]	validation-rmse:7.76237
[153]	validation-rmse:7.76208
[154]	validation-rmse:7.75991
[155]	validation-rmse:7.75854
[156]	validation-rmse:7.75635
[157]	validation-rmse:7.75346
[158]	validation-rmse:7.75101
[159]	validation-rmse:7.74777
[160]	validation-rmse:7.74468
[161]	validation-rmse:7.74073
[162]	validation-rmse:7.73989
[163]	validation-rmse:7.73909
[164]	validation-rmse:7.73734
[165]	validation-rmse:7.73773
[166]	validation-rmse:7.73450
[167]	validation-rmse:7.72997
[168]	validation-rmse:7.72902
[169]	validation-rmse:7.72794
[170]	validation-rmse:7.72528
[171]	validation-rmse:7.72126
[172]	validation-rmse:7.72036
[173]	validation-rmse:7.71900
[174]	validation-rmse:7.71517
[175]	validation-rmse:7.71277
[176]	validation-rmse:7.71257
[177]	validation-rmse:7.70960
[178]	validation-rmse:7.70865
[179]	validation-rmse:7.70774
[180]	validation-rmse:7.70389
[181]	validation-rmse:7.70403
[182]	validation-rmse:7.70214
[183]	validation-rmse:7.70062
[184]	validation-rmse:7.69638
[185]	validation-rmse:7.69313
[186]	validation-rmse:7.69233
[187]	validation-rmse:7.68917
[188]	validation-rmse:7.68809
[189]	validation-rmse:7.68681
[190]	validation-rmse:7.68439
[191]	validation-rmse:7.68319
[192]	validation-rmse:7.68133
[193]	validation-rmse:7.67943
[194]	validation-rmse:7.67663
[195]	validation-rmse:7.67683
[196]	validation-rmse:7.67557
[197]	validation-rmse:7.67326
[198]	validation-rmse:7.67058
[199]	validation-rmse:7.66789
[200]	validation-rmse:7.66818
[201]	validation-rmse:7.66661
[202]	validation-rmse:7.66635
[203]	validation-rmse:7.66509
[204]	validation-rmse:7.66483
[205]	validation-rmse:7.66233
[206]	validation-rmse:7.66309
[207]	validation-rmse:7.66236
[208]	validation-rmse:7.66080
[209]	validation-rmse:7.66040
[210]	validation-rmse:7.65737
[211]	validation-rmse:7.65404
[212]	validation-rmse:7.65436
[213]	validation-rmse:7.65377
[214]	validation-rmse:7.65304
[215]	validation-rmse:7.65177
[216]	validation-rmse:7.64997
[217]	validation-rmse:7.64967
[218]	validation-rmse:7.64773
[219]	validation-rmse:7.64719
[220]	validation-rmse:7.64440
[221]	validation-rmse:7.64259
[222]	validation-rmse:7.63997
[223]	validation-rmse:7.63927
[224]	validation-rmse:7.63682
[225]	validation-rmse:7.63744
[226]	validation-rmse:7.63783
[227]	validation-rmse:7.63692
[228]	validation-rmse:7.63512
[229]	validation-rmse:7.63499
[230]	validation-rmse:7.63167
[231]	validation-rmse:7.62973
[232]	validation-rmse:7.62659
[233]	validation-rmse:7.62196
[234]	validation-rmse:7.62061
[235]	validation-rmse:7.61478
[236]	validation-rmse:7.61431
[237]	validation-rmse:7.61340
[238]	validation-rmse:7.61232
[239]	validation-rmse:7.61037
[240]	validation-rmse:7.61054
[241]	validation-rmse:7.60972
[242]	validation-rmse:7.60699
[243]	validation-rmse:7.60550
[244]	validation-rmse:7.60707
[245]	validation-rmse:7.60417
[246]	validation-rmse:7.60287
[247]	validation-rmse:7.60302
[248]	validation-rmse:7.60036
[249]	validation-rmse:7.60038
[250]	validation-rmse:7.60005
[251]	validation-rmse:7.59724
[252]	validation-rmse:7.59334
[253]	validation-rmse:7.59220
[254]	validation-rmse:7.59085
[255]	validation-rmse:7.58930
[256]	validation-rmse:7.58902
[257]	validation-rmse:7.58891
[258]	validation-rmse:7.58653
[259]	validation-rmse:7.58421
[260]	validation-rmse:7.58391
[261]	validation-rmse:7.58201
[262]	validation-rmse:7.57895
[263]	validation-rmse:7.58021
[264]	validation-rmse:7.57902
[265]	validation-rmse:7.57840
[266]	validation-rmse:7.57770
[267]	validation-rmse:7.57683
[268]	validation-rmse:7.57547
[269]	validation-rmse:7.57473
[270]	validation-rmse:7.57383
[271]	validation-rmse:7.57248
[272]	validation-rmse:7.57087
[273]	validation-rmse:7.57002
[274]	validation-rmse:7.56991
[275]	validation-rmse:7.56843
[276]	validation-rmse:7.56820
[277]	validation-rmse:7.56787
[278]	validation-rmse:7.56458
[279]	validation-rmse:7.56421
[280]	validation-rmse:7.56240
[281]	validation-rmse:7.56144
[282]	validation-rmse:7.56143
[283]	validation-rmse:7.56151
[284]	validation-rmse:7.56025
[285]	validation-rmse:7.55832
[286]	validation-rmse:7.55761
[287]	validation-rmse:7.55645
[288]	validation-rmse:7.55592
[289]	validation-rmse:7.55658
[290]	validation-rmse:7.55449
[291]	validation-rmse:7.55265
[292]	validation-rmse:7.55198
[293]	validation-rmse:7.55340
[294]	validation-rmse:7.55176
[295]	validation-rmse:7.55076
[296]	validation-rmse:7.54933
[297]	validation-rmse:7.54915
[298]	validation-rmse:7.54864
[299]	validation-rmse:7.54770
[300]	validation-rmse:7.54477
[301]	validation-rmse:7.54541
[302]	validation-rmse:7.54578
[303]	validation-rmse:7.54558
[304]	validation-rmse:7.54117
[305]	validation-rmse:7.54034
[306]	validation-rmse:7.53863
[307]	validation-rmse:7.53747
[308]	validation-rmse:7.53541
[309]	validation-rmse:7.53531
[310]	validation-rmse:7.53420
[311]	validation-rmse:7.53392
[312]	validation-rmse:7.53420
[313]	validation-rmse:7.53407
[314]	validation-rmse:7.53206
[315]	validation-rmse:7.53166
[316]	validation-rmse:7.53100
[317]	validation-rmse:7.53057
[318]	validation-rmse:7.52956
[319]	validation-rmse:7.52764
[320]	validation-rmse:7.52661
[321]	validation-rmse:7.52476
[322]	validation-rmse:7.52463
[323]	validation-rmse:7.52447
[324]	validation-rmse:7.52268
[325]	validation-rmse:7.52070
[326]	validation-rmse:7.51893
[327]	validation-rmse:7.51765
[328]	validation-rmse:7.51591
[329]	validation-rmse:7.51589
[330]	validation-rmse:7.51581
[331]	validation-rmse:7.51274
[332]	validation-rmse:7.51297
[333]	validation-rmse:7.51184
[334]	validation-rmse:7.51150
[335]	validation-rmse:7.51127
[336]	validation-rmse:7.51014
[337]	validation-rmse:7.51088
[338]	validation-rmse:7.50937
[339]	validation-rmse:7.50949
[340]	validation-rmse:7.50711
[341]	validation-rmse:7.50735
[342]	validation-rmse:7.50850
[343]	validation-rmse:7.50706
[344]	validation-rmse:7.50683
[345]	validation-rmse:7.50684
[346]	validation-rmse:7.50647
[347]	validation-rmse:7.50442
[348]	validation-rmse:7.50393
[349]	validation-rmse:7.50277
[350]	validation-rmse:7.50282
[351]	validation-rmse:7.50187
[352]	validation-rmse:7.49807
[353]	validation-rmse:7.49808
[354]	validation-rmse:7.49668
[355]	validation-rmse:7.49649
[356]	validation-rmse:7.49516
[357]	validation-rmse:7.49350
[358]	validation-rmse:7.49119
[359]	validation-rmse:7.49103
[360]	validation-rmse:7.48937
[361]	validation-rmse:7.48835
[362]	validation-rmse:7.48818
[363]	validation-rmse:7.48747
[364]	validation-rmse:7.48692
[365]	validation-rmse:7.48482
[366]	validation-rmse:7.48324
[367]	validation-rmse:7.48366
[368]	validation-rmse:7.48234
[369]	validation-rmse:7.48254
[370]	validation-rmse:7.48116
[371]	validation-rmse:7.48064
[372]	validation-rmse:7.47776
[373]	validation-rmse:7.47823
[374]	validation-rmse:7.47649
[375]	validation-rmse:7.47488
[376]	validation-rmse:7.47462
[377]	validation-rmse:7.47497
[378]	validation-rmse:7.47387
[379]	validation-rmse:7.47304
[380]	validation-rmse:7.47224
[381]	validation-rmse:7.47146
[382]	validation-rmse:7.47099
[383]	validation-rmse:7.47080
[384]	validation-rmse:7.47022
[385]	validation-rmse:7.46904
[386]	validation-rmse:7.46981
[387]	validation-rmse:7.47022
[388]	validation-rmse:7.46684
[389]	validation-rmse:7.46750
[390]	validation-rmse:7.46473
[391]	validation-rmse:7.46350
[392]	validation-rmse:7.46202
[393]	validation-rmse:7.46225
[394]	validation-rmse:7.45977
[395]	validation-rmse:7.45722
[396]	validation-rmse:7.45565
[397]	validation-rmse:7.45483
[398]	validation-rmse:7.45455
[399]	validation-rmse:7.45362
[400]	validation-rmse:7.45410
[401]	validation-rmse:7.45308
[402]	validation-rmse:7.45340
[403]	validation-rmse:7.45069
[404]	validation-rmse:7.45030
[405]	validation-rmse:7.44932
[406]	validation-rmse:7.44943
[407]	validation-rmse:7.44916
[408]	validation-rmse:7.44952
[409]	validation-rmse:7.44925
[410]	validation-rmse:7.44900
[411]	validation-rmse:7.44702
[412]	validation-rmse:7.44608
[413]	validation-rmse:7.44525
[414]	validation-rmse:7.44327
[415]	validation-rmse:7.44267
[416]	validation-rmse:7.44208
[417]	validation-rmse:7.44163
[418]	validation-rmse:7.44148
[419]	validation-rmse:7.44113
[420]	validation-rmse:7.44103
[421]	validation-rmse:7.43942
[422]	validation-rmse:7.43933
[423]	validation-rmse:7.43767
[424]	validation-rmse:7.43679
[425]	validation-rmse:7.43628
[426]	validation-rmse:7.43674
[427]	validation-rmse:7.43526
[428]	validation-rmse:7.43703
[429]	validation-rmse:7.43590
[430]	validation-rmse:7.43467
[431]	validation-rmse:7.43409
[432]	validation-rmse:7.43449
[433]	validation-rmse:7.43247
[434]	validation-rmse:7.43133
[435]	validation-rmse:7.42964
[436]	validation-rmse:7.42924
[437]	validation-rmse:7.42898
[438]	validation-rmse:7.42886
[439]	validation-rmse:7.42756
[440]	validation-rmse:7.42646
[441]	validation-rmse:7.42430
[442]	validation-rmse:7.42372
[443]	validation-rmse:7.42251
[444]	validation-rmse:7.42266
[445]	validation-rmse:7.42202
[446]	validation-rmse:7.42100
[447]	validation-rmse:7.42176
[448]	validation-rmse:7.42073
[449]	validation-rmse:7.41953
[450]	validation-rmse:7.41983
[451]	validation-rmse:7.41847
[452]	validation-rmse:7.41768
[453]	validation-rmse:7.41532
[454]	validation-rmse:7.41516
[455]	validation-rmse:7.41432
[456]	validation-rmse:7.41335
[457]	validation-rmse:7.41352
[458]	validation-rmse:7.41313
[459]	validation-rmse:7.41316
[460]	validation-rmse:7.41315
[461]	validation-rmse:7.41291
[462]	validation-rmse:7.41227
[463]	validation-rmse:7.41082
[464]	validation-rmse:7.41014
[465]	validation-rmse:7.40808
[466]	validation-rmse:7.40854
[467]	validation-rmse:7.40728
[468]	validation-rmse:7.40772
[469]	validation-rmse:7.40795
[470]	validation-rmse:7.40459
[471]	validation-rmse:7.40303
[472]	validation-rmse:7.40208
[473]	validation-rmse:7.40098
[474]	validation-rmse:7.40121
[475]	validation-rmse:7.39760
[476]	validation-rmse:7.39853
[477]	validation-rmse:7.39816
[478]	validation-rmse:7.39874
[479]	validation-rmse:7.39803
[480]	validation-rmse:7.39746
[481]	validation-rmse:7.39528
[482]	validation-rmse:7.39505
[483]	validation-rmse:7.39490
[484]	validation-rmse:7.39451
[485]	validation-rmse:7.39311
[486]	validation-rmse:7.39361
[487]	validation-rmse:7.39319
[488]	validation-rmse:7.39270
[489]	validation-rmse:7.39186
[490]	validation-rmse:7.39115
[491]	validation-rmse:7.39174
[492]	validation-rmse:7.39108
[493]	validation-rmse:7.39055
[494]	validation-rmse:7.38945
[495]	validation-rmse:7.38909
[496]	validation-rmse:7.38916
[497]	validation-rmse:7.38977
[498]	validation-rmse:7.38896
[499]	validation-rmse:7.38971
[500]	validation-rmse:7.38896
[501]	validation-rmse:7.38855
[502]	validation-rmse:7.38840
[503]	validation-rmse:7.38617
[504]	validation-rmse:7.38589
[505]	validation-rmse:7.38632
[506]	validation-rmse:7.38511
[507]	validation-rmse:7.38474
[508]	validation-rmse:7.38447
[509]	validation-rmse:7.38404
[510]	validation-rmse:7.38386
[511]	validation-rmse:7.38294
[512]	validation-rmse:7.38282
[513]	validation-rmse:7.38331
[514]	validation-rmse:7.38281
[515]	validation-rmse:7.38168
[516]	validation-rmse:7.38097
[517]	validation-rmse:7.38114
[518]	validation-rmse:7.38020
[519]	validation-rmse:7.38019
[520]	validation-rmse:7.37978
[521]	validation-rmse:7.37896
[522]	validation-rmse:7.37770
[523]	validation-rmse:7.37687
[524]	validation-rmse:7.37713
[525]	validation-rmse:7.37557
[526]	validation-rmse:7.37621
[527]	validation-rmse:7.37503
[528]	validation-rmse:7.37384
[529]	validation-rmse:7.37390
[530]	validation-rmse:7.37321
[531]	validation-rmse:7.37285
[532]	validation-rmse:7.37240
[533]	validation-rmse:7.37334
[534]	validation-rmse:7.37200
[535]	validation-rmse:7.37098
[536]	validation-rmse:7.36958
[537]	validation-rmse:7.36768
[538]	validation-rmse:7.36849
[539]	validation-rmse:7.36693
[540]	validation-rmse:7.36549
[541]	validation-rmse:7.36457
[542]	validation-rmse:7.36389
[543]	validation-rmse:7.36340
[544]	validation-rmse:7.36235
[545]	validation-rmse:7.36160
[546]	validation-rmse:7.36100
[547]	validation-rmse:7.36062
[548]	validation-rmse:7.35922
[549]	validation-rmse:7.35990
[550]	validation-rmse:7.35933
[551]	validation-rmse:7.35828
[552]	validation-rmse:7.35660
[553]	validation-rmse:7.35734
[554]	validation-rmse:7.35688
[555]	validation-rmse:7.35605
[556]	validation-rmse:7.35699
[557]	validation-rmse:7.35656
[558]	validation-rmse:7.35661
[559]	validation-rmse:7.35650
[560]	validation-rmse:7.35541
[561]	validation-rmse:7.35455
[562]	validation-rmse:7.35166
[563]	validation-rmse:7.35004
[564]	validation-rmse:7.35082
[565]	validation-rmse:7.35019
[566]	validation-rmse:7.34828
[567]	validation-rmse:7.34898
[568]	validation-rmse:7.34974
[569]	validation-rmse:7.34951
[570]	validation-rmse:7.34871
[571]	validation-rmse:7.34902
[572]	validation-rmse:7.34797
[573]	validation-rmse:7.34695
[574]	validation-rmse:7.34579
[575]	validation-rmse:7.34584
[576]	validation-rmse:7.34643
[577]	validation-rmse:7.34603
[578]	validation-rmse:7.34608
[579]	validation-rmse:7.34502
[580]	validation-rmse:7.34403
[581]	validation-rmse:7.34418
[582]	validation-rmse:7.34344
[583]	validation-rmse:7.34337
[584]	validation-rmse:7.34242
[585]	validation-rmse:7.34352
[586]	validation-rmse:7.34334
[587]	validation-rmse:7.34264
[588]	validation-rmse:7.34205
[589]	validation-rmse:7.34043
[590]	validation-rmse:7.34082
[591]	validation-rmse:7.34018
[592]	validation-rmse:7.34054
[593]	validation-rmse:7.34157
[594]	validation-rmse:7.34097
[595]	validation-rmse:7.33999
[596]	validation-rmse:7.33949
[597]	validation-rmse:7.33916
[598]	validation-rmse:7.33828
[599]	validation-rmse:7.33822
[600]	validation-rmse:7.33812
[601]	validation-rmse:7.33814
[602]	validation-rmse:7.33763
[603]	validation-rmse:7.33738
[604]	validation-rmse:7.33705
[605]	validation-rmse:7.33669
[606]	validation-rmse:7.33586
[607]	validation-rmse:7.33522
[608]	validation-rmse:7.33511
[609]	validation-rmse:7.33508
[610]	validation-rmse:7.33436
[611]	validation-rmse:7.33479
[612]	validation-rmse:7.33535
[613]	validation-rmse:7.33387
[614]	validation-rmse:7.33324
[615]	validation-rmse:7.33285
[616]	validation-rmse:7.33284
[617]	validation-rmse:7.33261
[618]	validation-rmse:7.33212
[619]	validation-rmse:7.33280
[620]	validation-rmse:7.33145
[621]	validation-rmse:7.33001
[622]	validation-rmse:7.33028
[623]	validation-rmse:7.32939
[624]	validation-rmse:7.32986
[625]	validation-rmse:7.32970
[626]	validation-rmse:7.32900
[627]	validation-rmse:7.32832
[628]	validation-rmse:7.32900
[629]	validation-rmse:7.32803
[630]	validation-rmse:7.32816
[631]	validation-rmse:7.32860
[632]	validation-rmse:7.32799
[633]	validation-rmse:7.32810
[634]	validation-rmse:7.32779
[635]	validation-rmse:7.32786
[636]	validation-rmse:7.32670
[637]	validation-rmse:7.32684
[638]	validation-rmse:7.32547
[639]	validation-rmse:7.32499
[640]	validation-rmse:7.32484
[641]	validation-rmse:7.32335
[642]	validation-rmse:7.32413
[643]	validation-rmse:7.32418
[644]	validation-rmse:7.32335
[645]	validation-rmse:7.32304
[646]	validation-rmse:7.32176
[647]	validation-rmse:7.32210
[648]	validation-rmse:7.32233
[649]	validation-rmse:7.32172
[650]	validation-rmse:7.32164
[651]	validation-rmse:7.32080
[652]	validation-rmse:7.32033
[653]	validation-rmse:7.31985
[654]	validation-rmse:7.32047
[655]	validation-rmse:7.32004
[656]	validation-rmse:7.31989
[657]	validation-rmse:7.31977
[658]	validation-rmse:7.31958
[659]	validation-rmse:7.31903
[660]	validation-rmse:7.31888
[661]	validation-rmse:7.31809
[662]	validation-rmse:7.31723
[663]	validation-rmse:7.31665
[664]	validation-rmse:7.31630
[665]	validation-rmse:7.31575
[666]	validation-rmse:7.31530
[667]	validation-rmse:7.31483
[668]	validation-rmse:7.31320
[669]	validation-rmse:7.31272
[670]	validation-rmse:7.31264

[12:01:24] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[2]	validation-rmse:9.52916
[3]	validation-rmse:9.36225
[4]	validation-rmse:9.19154
[5]	validation-rmse:8.99880
[6]	validation-rmse:8.91550
[7]	validation-rmse:8.81673
[8]	validation-rmse:8.69866
[9]	validation-rmse:8.55168
[10]	validation-rmse:8.48182
[11]	validation-rmse:8.40920
[12]	validation-rmse:8.33473
[13]	validation-rmse:8.27978
[14]	validation-rmse:8.23289
[15]	validation-rmse:8.15541
[16]	validation-rmse:8.08969
[17]	validation-rmse:8.04630
[18]	validation-rmse:8.02588
[19]	validation-rmse:7.97002
[20]	validation-rmse:7.94950
[21]	validation-rmse:7.93097
[22]	validation-rmse:7.91550
[23]	validation-rmse:7.89596
[24]	validation-rmse:7.87358
[25]	validation-rmse:7.85307
[26]	validation-rmse:7.83424
[27]	validation-rmse:7.81536
[28]	validation-rmse:7.80292
[29]	validation-rmse:7.78449
[30]	validation-rmse:7.77222
[31]	validation-rmse:7.76054
[32]	validation-rmse:7.75609
[33]	validation-rmse:7.75158
[34]	validation-rmse:7.74947
[35]	validation-rmse:7.74630
[36]	validation-rmse:7.74429
[37]	validation-rmse:7.74146
[38]	validation-rmse:7.74055
[39]	validation-rmse:7.73626
[40]	validation-rmse:7.73562
[41]	validation-rmse:7.73543
[42]	validation-rmse:7.73477
[43]	validation-rmse:7.73437
[44]	validation-rmse:7.73142
[45]	validation-rmse:7.72955
[46]	validation-rmse:7.72860
[47]	validation-rmse:7.72854
[48]	validation-rmse:7.72958
[49]	validation-rmse:7.73110
[50]	validation-rmse:7.73362
[51]	validation-rmse:7.73323
[52]	validation-rmse:7.73265
[53]	validation-rmse:7.73280
[54]	validation-rmse:7.73217
[55]	validation-rmse:7.73200
[56]	validation-rmse:7.73236
[57]	validation-rmse:7.73297
[58]	validation-rmse:7.73183
[59]	validation-rmse:7.73164
[60]	validation-rmse:7.73221
[61]	validation-rmse:7.73299
[62]	validation-rmse:7.73362
[63]	validation-rmse:7.73437
[64]	validation-rmse:7.73446
[65]	validation-rmse:7.73446
[66]	validation-rmse:7.73448
[67]	validation-rmse:7.73384
[68]	validation-rmse:7.73406
[69]	validation-rmse:7.73420
[70]	validation-rmse:7.73410
[71]	validation-rmse:7.73399
[72]	validation-rmse:7.73433
[73]	validation-rmse:7.73454
[74]	validation-rmse:7.73475
[75]	validation-rmse:7.73470
[76]	validation-rmse:7.73482
[77]	validation-rmse:7.73460
[78]	validation-rmse:7.73493
[79]	validation-rmse:7.73504
[80]	validation-rmse:7.73548
[81]	validation-rmse:7.73550
[82]	validation-rmse:7.73581
[83]	validation-rmse:7.73598
[84]	validation-rmse:7.73606
[85]	validation-rmse:7.73607
[86]	validation-rmse:7.73624
[87]	validation-rmse:7.73631
[88]	validation-rmse:7.73649
[89]	validation-rmse:7.73655
[90]	validation-rmse:7.73650
[91]	validation-rmse:7.73653
[92]	validation-rmse:7.73650
[93]	validation-rmse:7.73656
[94]	validation-rmse:7.73660
[95]	validation-rmse:7.73674
[96]	validation-rmse:7.73671
[0]	validation-rmse:11.47638
  6%|▌         | 3/50 [11:37<2:26:36, 187.16s/trial, best loss: 7.2272270245905395]

[12:01:33] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:9.53563
[2]	validation-rmse:9.03021
[3]	validation-rmse:8.62257
[4]	validation-rmse:8.36647
[5]	validation-rmse:8.29294
[6]	validation-rmse:8.17255
[7]	validation-rmse:8.12643
[8]	validation-rmse:8.05292
[9]	validation-rmse:8.00236
[10]	validation-rmse:7.97473
[11]	validation-rmse:7.93802
[12]	validation-rmse:7.93031
[13]	validation-rmse:7.92472
[14]	validation-rmse:7.91985
[15]	validation-rmse:7.91110
[16]	validation-rmse:7.89717
[17]	validation-rmse:7.89217
[18]	validation-rmse:7.88395
[19]	validation-rmse:7.87635
[20]	validation-rmse:7.87275
[21]	validation-rmse:7.86691
[22]	validation-rmse:7.86376
[23]	validation-rmse:7.86223
[24]	validation-rmse:7.85941
[25]	validation-rmse:7.84972
[26]	validation-rmse:7.84931
[27]	validation-rmse:7.84488
[28]	validation-rmse:7.83941
[29]	validation-rmse:7.83457
[30]	validation-rmse:7.82933
[31]	validation-rmse:7.82789
[32]	validation-rmse:7.82357
[33]	validation-rmse:7.81936
[34]	validation-rmse:7.81735
[35]	validation-rmse:7.80884
[36]	validation-rmse:7.80437
[37]	validation-rmse:7.80251
[38]	validation-rmse:7.79609
[39]	validation-rmse:7.79433
[40]	validation-rmse:7.78583
[41]	validation-rmse:7.78221
[42]	validation-rmse:7.77864
[43]	validation-rmse:7.77594
[44]	validation-rmse:7.77449
[45]	validation-rmse:7.76429
[46]	validation-rmse:7.76124
[47]	validation-rmse:7.75678
[48]	validation-rmse:7.75095
[49]	validation-rmse:7.75137
[50]	validation-rmse:7.74896
[51]	validation-rmse:7.74775
[52]	validation-rmse:7.74671
[53]	validation-rmse:7.74435
[54]	validation-rmse:7.73503
[55]	validation-rmse:7.73195
[56]	validation-rmse:7.73184
[57]	validation-rmse:7.72852
[58]	validation-rmse:7.72446
[59]	validation-rmse:7.72397
[60]	validation-rmse:7.72497
[61]	validation-rmse:7.72251
[62]	validation-rmse:7.72044
[63]	validation-rmse:7.71640
[64]	validation-rmse:7.71407
[65]	validation-rmse:7.71260
[66]	validation-rmse:7.71078
[67]	validation-rmse:7.70664
[68]	validation-rmse:7.70555
[69]	validation-rmse:7.70399
[70]	validation-rmse:7.70200
[71]	validation-rmse:7.70018
[72]	validation-rmse:7.69672
[73]	validation-rmse:7.69306
[74]	validation-rmse:7.69019
[75]	validation-rmse:7.69030
[76]	validation-rmse:7.69131
[77]	validation-rmse:7.69063
[78]	validation-rmse:7.68839
[79]	validation-rmse:7.68883
[80]	validation-rmse:7.68869
[81]	validation-rmse:7.68545
[82]	validation-rmse:7.68312
[83]	validation-rmse:7.68157
[84]	validation-rmse:7.68016
[85]	validation-rmse:7.67807
[86]	validation-rmse:7.67562
[87]	validation-rmse:7.67335
[88]	validation-rmse:7.67184
[89]	validation-rmse:7.67025
[90]	validation-rmse:7.66845
[91]	validation-rmse:7.66907
[92]	validation-rmse:7.66609
[93]	validation-rmse:7.66429
[94]	validation-rmse:7.66357
[95]	validation-rmse:7.66251
[96]	validation-rmse:7.66179
[97]	validation-rmse:7.66048
[98]	validation-rmse:7.65817
[99]	validation-rmse:7.65828
[100]	validation-rmse:7.65419
[101]	validation-rmse:7.65292
[102]	validation-rmse:7.64908
[103]	validation-rmse:7.64816
[104]	validation-rmse:7.64523
[105]	validation-rmse:7.64650
[106]	validation-rmse:7.64488
[107]	validation-rmse:7.64419
[108]	validation-rmse:7.64011
[109]	validation-rmse:7.64067
[110]	validation-rmse:7.63540
[111]	validation-rmse:7.63379
[112]	validation-rmse:7.63408
[113]	validation-rmse:7.63408
[114]	validation-rmse:7.62927
[115]	validation-rmse:7.62866
[116]	validation-rmse:7.62435
[117]	validation-rmse:7.62545
[118]	validation-rmse:7.62613
[119]	validation-rmse:7.62322
[120]	validation-rmse:7.62102
[121]	validation-rmse:7.61749
[122]	validation-rmse:7.61626
[123]	validation-rmse:7.61502
[124]	validation-rmse:7.61425
[125]	validation-rmse:7.61155
[126]	validation-rmse:7.61045
[127]	validation-rmse:7.61000
[128]	validation-rmse:7.60861
[129]	validation-rmse:7.60592
[130]	validation-rmse:7.60432
[131]	validation-rmse:7.60349
[132]	validation-rmse:7.60297
[133]	validation-rmse:7.60089
[134]	validation-rmse:7.59957
[135]	validation-rmse:7.59636
[136]	validation-rmse:7.59526
[137]	validation-rmse:7.59407
[138]	validation-rmse:7.59328
[139]	validation-rmse:7.59114
[140]	validation-rmse:7.59080
[141]	validation-rmse:7.58875
[142]	validation-rmse:7.58661
[143]	validation-rmse:7.58877
[144]	validation-rmse:7.58712
[145]	validation-rmse:7.58495
[146]	validation-rmse:7.58285
[147]	validation-rmse:7.58210
[148]	validation-rmse:7.58092
[149]	validation-rmse:7.58209
[150]	validation-rmse:7.58088
[151]	validation-rmse:7.57893
[152]	validation-rmse:7.57950
[153]	validation-rmse:7.57897
[154]	validation-rmse:7.57355
[155]	validation-rmse:7.57174
[156]	validation-rmse:7.57343
[157]	validation-rmse:7.57178
[158]	validation-rmse:7.57062
[159]	validation-rmse:7.56658
[160]	validation-rmse:7.56694
[161]	validation-rmse:7.56548
[162]	validation-rmse:7.56485
[163]	validation-rmse:7.56291
[164]	validation-rmse:7.56095
[165]	validation-rmse:7.56017
[166]	validation-rmse:7.55905
[167]	validation-rmse:7.55662
[168]	validation-rmse:7.55462
[169]	validation-rmse:7.55394
[170]	validation-rmse:7.55104
[171]	validation-rmse:7.55047
[172]	validation-rmse:7.54883
[173]	validation-rmse:7.54624
[174]	validation-rmse:7.54430
[175]	validation-rmse:7.54321
[176]	validation-rmse:7.54357
[177]	validation-rmse:7.54271
[178]	validation-rmse:7.54316
[179]	validation-rmse:7.54154
[180]	validation-rmse:7.53902
[181]	validation-rmse:7.53693
[182]	validation-rmse:7.53419
[183]	validation-rmse:7.53295
[184]	validation-rmse:7.53200
[185]	validation-rmse:7.53038
[186]	validation-rmse:7.53060
[187]	validation-rmse:7.52935
[188]	validation-rmse:7.52881
[189]	validation-rmse:7.52872
[190]	validation-rmse:7.52868
[191]	validation-rmse:7.52683
[192]	validation-rmse:7.52431
[193]	validation-rmse:7.52484
[194]	validation-rmse:7.52513
[195]	validation-rmse:7.52268
[196]	validation-rmse:7.52104
[197]	validation-rmse:7.52012
[198]	validation-rmse:7.51852
[199]	validation-rmse:7.51634
[200]	validation-rmse:7.51533
[201]	validation-rmse:7.51380
[202]	validation-rmse:7.51214
[203]	validation-rmse:7.51229
[204]	validation-rmse:7.51201
[205]	validation-rmse:7.50995
[206]	validation-rmse:7.50934
[207]	validation-rmse:7.50886
[208]	validation-rmse:7.50790
[209]	validation-rmse:7.50740
[210]	validation-rmse:7.50594
[211]	validation-rmse:7.50403
[212]	validation-rmse:7.50281
[213]	validation-rmse:7.50058
[214]	validation-rmse:7.49765
[215]	validation-rmse:7.49815
[216]	validation-rmse:7.49588
[217]	validation-rmse:7.49356
[218]	validation-rmse:7.49458
[219]	validation-rmse:7.49153
[220]	validation-rmse:7.49008
[221]	validation-rmse:7.49024
[222]	validation-rmse:7.48795
[223]	validation-rmse:7.48713
[224]	validation-rmse:7.48685
[225]	validation-rmse:7.48382
[226]	validation-rmse:7.48330
[227]	validation-rmse:7.48429
[228]	validation-rmse:7.48357
[229]	validation-rmse:7.48295
[230]	validation-rmse:7.48365
[231]	validation-rmse:7.48228
[232]	validation-rmse:7.48003
[233]	validation-rmse:7.48003
[234]	validation-rmse:7.47799
[235]	validation-rmse:7.47525
[236]	validation-rmse:7.47556
[237]	validation-rmse:7.47542
[238]	validation-rmse:7.47427
[239]	validation-rmse:7.47290
[240]	validation-rmse:7.47224
[241]	validation-rmse:7.47298
[242]	validation-rmse:7.47218
[243]	validation-rmse:7.47065
[244]	validation-rmse:7.46802
[245]	validation-rmse:7.46665
[246]	validation-rmse:7.46534
[247]	validation-rmse:7.46483
[248]	validation-rmse:7.46574
[249]	validation-rmse:7.46353
[250]	validation-rmse:7.46162
[251]	validation-rmse:7.46104
[252]	validation-rmse:7.46009
[253]	validation-rmse:7.46039
[254]	validation-rmse:7.45912
[255]	validation-rmse:7.45870
[256]	validation-rmse:7.45807
[257]	validation-rmse:7.45486
[258]	validation-rmse:7.45429
[259]	validation-rmse:7.45635
[260]	validation-rmse:7.45518
[261]	validation-rmse:7.45483
[262]	validation-rmse:7.45444
[263]	validation-rmse:7.45389
[264]	validation-rmse:7.45358
[265]	validation-rmse:7.45288
[266]	validation-rmse:7.45219
[267]	validation-rmse:7.45231
[268]	validation-rmse:7.45134
[269]	validation-rmse:7.45065
[270]	validation-rmse:7.45124
[271]	validation-rmse:7.45035
[272]	validation-rmse:7.45029
[273]	validation-rmse:7.45033
[274]	validation-rmse:7.44746
[275]	validation-rmse:7.44625
[276]	validation-rmse:7.44621
[277]	validation-rmse:7.44412
[278]	validation-rmse:7.44437
[279]	validation-rmse:7.44433
[280]	validation-rmse:7.44478
[281]	validation-rmse:7.44326
[282]	validation-rmse:7.44271
[283]	validation-rmse:7.44180
[284]	validation-rmse:7.43995
[285]	validation-rmse:7.43844
[286]	validation-rmse:7.43822
[287]	validation-rmse:7.43809
[288]	validation-rmse:7.43646
[289]	validation-rmse:7.43726
[290]	validation-rmse:7.43464
[291]	validation-rmse:7.43464
[292]	validation-rmse:7.43383
[293]	validation-rmse:7.43407
[294]	validation-rmse:7.43291
[295]	validation-rmse:7.43175
[296]	validation-rmse:7.43100
[297]	validation-rmse:7.43157
[298]	validation-rmse:7.42958
[299]	validation-rmse:7.42785
[300]	validation-rmse:7.42785
[301]	validation-rmse:7.42779
[302]	validation-rmse:7.42738
[303]	validation-rmse:7.42786
[304]	validation-rmse:7.42690
[305]	validation-rmse:7.42682
[306]	validation-rmse:7.42400
[307]	validation-rmse:7.42476
[308]	validation-rmse:7.42311
[309]	validation-rmse:7.42242
[310]	validation-rmse:7.42186
[311]	validation-rmse:7.42141
[312]	validation-rmse:7.42093
[313]	validation-rmse:7.42114
[314]	validation-rmse:7.42005
[315]	validation-rmse:7.41943
[316]	validation-rmse:7.41791
[317]	validation-rmse:7.41806
[318]	validation-rmse:7.41633
[319]	validation-rmse:7.41561
[320]	validation-rmse:7.41429
[321]	validation-rmse:7.41429
[322]	validation-rmse:7.41352
[323]	validation-rmse:7.41176
[324]	validation-rmse:7.41159
[325]	validation-rmse:7.41170
[326]	validation-rmse:7.41047
[327]	validation-rmse:7.40982
[328]	validation-rmse:7.40823
[329]	validation-rmse:7.40709
[330]	validation-rmse:7.40771
[331]	validation-rmse:7.40673
[332]	validation-rmse:7.40618
[333]	validation-rmse:7.40496
[334]	validation-rmse:7.40339
[335]	validation-rmse:7.40453
[336]	validation-rmse:7.40439
[337]	validation-rmse:7.40288
[338]	validation-rmse:7.40185
[339]	validation-rmse:7.40243
[340]	validation-rmse:7.40229
[341]	validation-rmse:7.40150
[342]	validation-rmse:7.40018
[343]	validation-rmse:7.39916
[344]	validation-rmse:7.39821
[345]	validation-rmse:7.39776
[346]	validation-rmse:7.39508
[347]	validation-rmse:7.39560
[348]	validation-rmse:7.39331
[349]	validation-rmse:7.39386
[350]	validation-rmse:7.39240
[351]	validation-rmse:7.39243
[352]	validation-rmse:7.39247
[353]	validation-rmse:7.39155
[354]	validation-rmse:7.39112
[355]	validation-rmse:7.39039
[356]	validation-rmse:7.38911
[357]	validation-rmse:7.38779
[358]	validation-rmse:7.38651
[359]	validation-rmse:7.38804
[360]	validation-rmse:7.38728
[361]	validation-rmse:7.38536
[362]	validation-rmse:7.38616
[363]	validation-rmse:7.38457
[364]	validation-rmse:7.38308
[365]	validation-rmse:7.38267
[366]	validation-rmse:7.38107
[367]	validation-rmse:7.38203
[368]	validation-rmse:7.38298
[369]	validation-rmse:7.38219
[370]	validation-rmse:7.38172
[371]	validation-rmse:7.38105
[372]	validation-rmse:7.38143
[373]	validation-rmse:7.37914
[374]	validation-rmse:7.37922
[375]	validation-rmse:7.37642
[376]	validation-rmse:7.37714
[377]	validation-rmse:7.37655
[378]	validation-rmse:7.37615
[379]	validation-rmse:7.37586
[380]	validation-rmse:7.37542
[381]	validation-rmse:7.37471
[382]	validation-rmse:7.37483
[383]	validation-rmse:7.37542
[384]	validation-rmse:7.37411
[385]	validation-rmse:7.37295
[386]	validation-rmse:7.37323
[387]	validation-rmse:7.37242
[388]	validation-rmse:7.37146
[389]	validation-rmse:7.37029
[390]	validation-rmse:7.36933
[391]	validation-rmse:7.36888
[392]	validation-rmse:7.36659
[393]	validation-rmse:7.36679
[394]	validation-rmse:7.36602
[395]	validation-rmse:7.36608
[396]	validation-rmse:7.36534
[397]	validation-rmse:7.36542
[398]	validation-rmse:7.36643
[399]	validation-rmse:7.36530
[400]	validation-rmse:7.36474
[401]	validation-rmse:7.36316
[402]	validation-rmse:7.36412
[403]	validation-rmse:7.36414
[404]	validation-rmse:7.36406
[405]	validation-rmse:7.36350
[406]	validation-rmse:7.36082
[407]	validation-rmse:7.36065
[408]	validation-rmse:7.35934
[409]	validation-rmse:7.36073
[410]	validation-rmse:7.35975
[411]	validation-rmse:7.35890
[412]	validation-rmse:7.35666
[413]	validation-rmse:7.35655
[414]	validation-rmse:7.35494
[415]	validation-rmse:7.35284
[416]	validation-rmse:7.35351
[417]	validation-rmse:7.35407
[418]	validation-rmse:7.35336
[419]	validation-rmse:7.35251
[420]	validation-rmse:7.35267
[421]	validation-rmse:7.35208
[422]	validation-rmse:7.35098
[423]	validation-rmse:7.35030
[424]	validation-rmse:7.35149
[425]	validation-rmse:7.35063
[426]	validation-rmse:7.34910
[427]	validation-rmse:7.34817
[428]	validation-rmse:7.34744
[429]	validation-rmse:7.34682
[430]	validation-rmse:7.34623
[431]	validation-rmse:7.34528
[432]	validation-rmse:7.34541
[433]	validation-rmse:7.34580
[434]	validation-rmse:7.34541
[435]	validation-rmse:7.34429
[436]	validation-rmse:7.34358
[437]	validation-rmse:7.34344
[438]	validation-rmse:7.34325
[439]	validation-rmse:7.34237
[440]	validation-rmse:7.34109
[441]	validation-rmse:7.34058
[442]	validation-rmse:7.33931
[443]	validation-rmse:7.33889
[444]	validation-rmse:7.34006
[445]	validation-rmse:7.34107
[446]	validation-rmse:7.34024
[447]	validation-rmse:7.34041
[448]	validation-rmse:7.34033
[449]	validation-rmse:7.34003
[450]	validation-rmse:7.33986
[451]	validation-rmse:7.33806
[452]	validation-rmse:7.33798
[453]	validation-rmse:7.33590
[454]	validation-rmse:7.33531
[455]	validation-rmse:7.33653
[456]	validation-rmse:7.33617
[457]	validation-rmse:7.33604
[458]	validation-rmse:7.33552
[459]	validation-rmse:7.33466
[460]	validation-rmse:7.33510
[461]	validation-rmse:7.33475
[462]	validation-rmse:7.33351
[463]	validation-rmse:7.33279
[464]	validation-rmse:7.33160
[465]	validation-rmse:7.33205
[466]	validation-rmse:7.33061
[467]	validation-rmse:7.33123
[468]	validation-rmse:7.32948
[469]	validation-rmse:7.32900
[470]	validation-rmse:7.32825
[471]	validation-rmse:7.32691
[472]	validation-rmse:7.32679
[473]	validation-rmse:7.32612
[474]	validation-rmse:7.32586
[475]	validation-rmse:7.32393
[476]	validation-rmse:7.32417
[477]	validation-rmse:7.32345
[478]	validation-rmse:7.32369
[479]	validation-rmse:7.32386
[480]	validation-rmse:7.32254
[481]	validation-rmse:7.32209
[482]	validation-rmse:7.32186
[483]	validation-rmse:7.32214
[484]	validation-rmse:7.32122
[485]	validation-rmse:7.32097
[486]	validation-rmse:7.32095
[487]	validation-rmse:7.32085
[488]	validation-rmse:7.32115
[489]	validation-rmse:7.32068
[490]	validation-rmse:7.31994
[491]	validation-rmse:7.31771
[492]	validation-rmse:7.31852
[493]	validation-rmse:7.31715
[494]	validation-rmse:7.31745
[495]	validation-rmse:7.31747
[496]	validation-rmse:7.31698
[497]	validation-rmse:7.31558
[498]	validation-rmse:7.31619
[499]	validation-rmse:7.31680
[500]	validation-rmse:7.31654
[501]	validation-rmse:7.31509
[502]	validation-rmse:7.31535
[503]	validation-rmse:7.31470
[504]	validation-rmse:7.31566
[505]	validation-rmse:7.31436
[506]	validation-rmse:7.31454
[507]	validation-rmse:7.31332
[508]	validation-rmse:7.31298
[509]	validation-rmse:7.31315
[510]	validation-rmse:7.31228
[511]	validation-rmse:7.31210
[512]	validation-rmse:7.31112
[513]	validation-rmse:7.30927
[514]	validation-rmse:7.30756
[515]	validation-rmse:7.30741
[516]	validation-rmse:7.30661
[517]	validation-rmse:7.30606
[518]	validation-rmse:7.30660
[519]	validation-rmse:7.30746
[520]	validation-rmse:7.30654
[521]	validation-rmse:7.30531
[522]	validation-rmse:7.30484
[523]	validation-rmse:7.30361
[524]	validation-rmse:7.30417
[525]	validation-rmse:7.30313
[526]	validation-rmse:7.30437
[527]	validation-rmse:7.30449
[528]	validation-rmse:7.30356
[529]	validation-rmse:7.30206
[530]	validation-rmse:7.30246
[531]	validation-rmse:7.30067
[532]	validation-rmse:7.29993
[533]	validation-rmse:7.29948
[534]	validation-rmse:7.29828
[535]	validation-rmse:7.29857
[536]	validation-rmse:7.29727
[537]	validation-rmse:7.29807
[538]	validation-rmse:7.29852
[539]	validation-rmse:7.29785
[540]	validation-rmse:7.29718
[541]	validation-rmse:7.29773
[542]	validation-rmse:7.29721
[543]	validation-rmse:7.29798
[544]	validation-rmse:7.29769
[545]	validation-rmse:7.29649
[546]	validation-rmse:7.29630
[547]	validation-rmse:7.29556
[548]	validation-rmse:7.29582
[549]	validation-rmse:7.29529
[550]	validation-rmse:7.29570
[551]	validation-rmse:7.29539
[552]	validation-rmse:7.29422
[553]	validation-rmse:7.29362
[554]	validation-rmse:7.29274
[555]	validation-rmse:7.29348
[556]	validation-rmse:7.29336
[557]	validation-rmse:7.29312
[558]	validation-rmse:7.29283
[559]	validation-rmse:7.29184
[560]	validation-rmse:7.29195
[561]	validation-rmse:7.29233
[562]	validation-rmse:7.29057
[563]	validation-rmse:7.28988
[564]	validation-rmse:7.28875
[565]	validation-rmse:7.28833
[566]	validation-rmse:7.28789
[567]	validation-rmse:7.28769
[568]	validation-rmse:7.28737
[569]	validation-rmse:7.28706
[570]	validation-rmse:7.28728
[571]	validation-rmse:7.28689
[572]	validation-rmse:7.28657
[573]	validation-rmse:7.28598
[574]	validation-rmse:7.28474
[575]	validation-rmse:7.28540
[576]	validation-rmse:7.28407
[577]	validation-rmse:7.28446
[578]	validation-rmse:7.28421
[579]	validation-rmse:7.28464
[580]	validation-rmse:7.28451
[581]	validation-rmse:7.28386
[582]	validation-rmse:7.28280
[583]	validation-rmse:7.28442
[584]	validation-rmse:7.28270
[585]	validation-rmse:7.28340
[586]	validation-rmse:7.28306
[587]	validation-rmse:7.28173
[588]	validation-rmse:7.28137
[589]	validation-rmse:7.28067
[590]	validation-rmse:7.28053
[591]	validation-rmse:7.28026
[592]	validation-rmse:7.27993
[593]	validation-rmse:7.27804
[594]	validation-rmse:7.27755
[595]	validation-rmse:7.27712
[596]	validation-rmse:7.27762
[597]	validation-rmse:7.27813
[598]	validation-rmse:7.27829
[599]	validation-rmse:7.27693
[600]	validation-rmse:7.27656
[601]	validation-rmse:7.27554
[602]	validation-rmse:7.27540
[603]	validation-rmse:7.27281
[604]	validation-rmse:7.27411
[605]	validation-rmse:7.27420
[606]	validation-rmse:7.27299
[607]	validation-rmse:7.27314
[608]	validation-rmse:7.27257
[609]	validation-rmse:7.27231
[610]	validation-rmse:7.27221
[611]	validation-rmse:7.27144
[612]	validation-rmse:7.27089
[613]	validation-rmse:7.27052
[614]	validation-rmse:7.26858
[615]	validation-rmse:7.26962
[616]	validation-rmse:7.26996
[617]	validation-rmse:7.27059
[618]	validation-rmse:7.27048
[619]	validation-rmse:7.26896
[620]	validation-rmse:7.26931
[621]	validation-rmse:7.26896
[622]	validation-rmse:7.26781
[623]	validation-rmse:7.26783
[624]	validation-rmse:7.26671
[625]	validation-rmse:7.26794
[626]	validation-rmse:7.26686
[627]	validation-rmse:7.26757
[628]	validation-rmse:7.26720
[629]	validation-rmse:7.26748
[630]	validation-rmse:7.26769
[631]	validation-rmse:7.26697
[632]	validation-rmse:7.26638
[633]	validation-rmse:7.26636
[634]	validation-rmse:7.26598
[635]	validation-rmse:7.26648
[636]	validation-rmse:7.26545
[637]	validation-rmse:7.26518
[638]	validation-rmse:7.26335
[639]	validation-rmse:7.26345
[640]	validation-rmse:7.26269
[641]	validation-rmse:7.26396
[642]	validation-rmse:7.26386
[643]	validation-rmse:7.26298
[644]	validation-rmse:7.26321
[645]	validation-rmse:7.26348
[646]	validation-rmse:7.26291
[647]	validation-rmse:7.26381
[648]	validation-rmse:7.26329
[649]	validation-rmse:7.26290
[650]	validation-rmse:7.26192
[651]	validation-rmse:7.26166
[652]	validation-rmse:7.26236
[653]	validation-rmse:7.25939
[654]	validation-rmse:7.25915
[655]	validation-rmse:7.25881
[656]	validation-rmse:7.25804
[657]	validation-rmse:7.25781
[658]	validation-rmse:7.25781
[659]	validation-rmse:7.25591
[660]	validation-rmse:7.25574
[661]	validation-rmse:7.25731
[662]	validation-rmse:7.25739
[663]	validation-rmse:7.25697
[664]	validation-rmse:7.25713
[665]	validation-rmse:7.25577
[666]	validation-rmse:7.25498
[667]	validation-rmse:7.25583
[668]	validation-rmse:7.25524
[669]	validation-rmse:7.25551
[670]	validation-rmse:7.25585

[12:05:55] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:9.26599
[2]	validation-rmse:8.61382
[3]	validation-rmse:8.29556
[4]	validation-rmse:8.02085
[5]	validation-rmse:7.96243
[6]	validation-rmse:7.93085
[7]	validation-rmse:7.88850
[8]	validation-rmse:7.86878
[9]	validation-rmse:7.84755
[10]	validation-rmse:7.83076
[11]	validation-rmse:7.81739
[12]	validation-rmse:7.81097
[13]	validation-rmse:7.79354
[14]	validation-rmse:7.77880
[15]	validation-rmse:7.77259
[16]	validation-rmse:7.75264
[17]	validation-rmse:7.74206
[18]	validation-rmse:7.73126
[19]	validation-rmse:7.72133
[20]	validation-rmse:7.71199
[21]	validation-rmse:7.70711
[22]	validation-rmse:7.70212
[23]	validation-rmse:7.69313
[24]	validation-rmse:7.69174
[25]	validation-rmse:7.68769
[26]	validation-rmse:7.68256
[27]	validation-rmse:7.67949
[28]	validation-rmse:7.67139
[29]	validation-rmse:7.66731
[30]	validation-rmse:7.65835
[31]	validation-rmse:7.65499
[32]	validation-rmse:7.64975
[33]	validation-rmse:7.64976
[34]	validation-rmse:7.64318
[35]	validation-rmse:7.64213
[36]	validation-rmse:7.63701
[37]	validation-rmse:7.63488
[38]	validation-rmse:7.62833
[39]	validation-rmse:7.62594
[40]	validation-rmse:7.62089
[41]	validation-rmse:7.61950
[42]	validation-rmse:7.61708
[43]	validation-rmse:7.61230
[44]	validation-rmse:7.61134
[45]	validation-rmse:7.60649
[46]	validation-rmse:7.60532
[47]	validation-rmse:7.59999
[48]	validation-rmse:7.59696
[49]	validation-rmse:7.59377
[50]	validation-rmse:7.58928
[51]	validation-rmse:7.58494
[52]	validation-rmse:7.58333
[53]	validation-rmse:7.58155
[54]	validation-rmse:7.57946
[55]	validation-rmse:7.57416
[56]	validation-rmse:7.57004
[57]	validation-rmse:7.56982
[58]	validation-rmse:7.56585
[59]	validation-rmse:7.56232
[60]	validation-rmse:7.56072
[61]	validation-rmse:7.55783
[62]	validation-rmse:7.55411
[63]	validation-rmse:7.54868
[64]	validation-rmse:7.54476
[65]	validation-rmse:7.54110
[66]	validation-rmse:7.53938
[67]	validation-rmse:7.53600
[68]	validation-rmse:7.53377
[69]	validation-rmse:7.52861
[70]	validation-rmse:7.52714
[71]	validation-rmse:7.52706
[72]	validation-rmse:7.52329
[73]	validation-rmse:7.51970
[74]	validation-rmse:7.51499
[75]	validation-rmse:7.51254
[76]	validation-rmse:7.50675
[77]	validation-rmse:7.50536
[78]	validation-rmse:7.50043
[79]	validation-rmse:7.50036
[80]	validation-rmse:7.49654
[81]	validation-rmse:7.49763
[82]	validation-rmse:7.49608
[83]	validation-rmse:7.49325
[84]	validation-rmse:7.48946
[85]	validation-rmse:7.48870
[86]	validation-rmse:7.48420
[87]	validation-rmse:7.48338
[88]	validation-rmse:7.47885
[89]	validation-rmse:7.47613
[90]	validation-rmse:7.47404
[91]	validation-rmse:7.47462
[92]	validation-rmse:7.47023
[93]	validation-rmse:7.46789
[94]	validation-rmse:7.46365
[95]	validation-rmse:7.46166
[96]	validation-rmse:7.45990
[97]	validation-rmse:7.46012
[98]	validation-rmse:7.45754
[99]	validation-rmse:7.45260
[100]	validation-rmse:7.45008
[101]	validation-rmse:7.44981
[102]	validation-rmse:7.44975
[103]	validation-rmse:7.44784
[104]	validation-rmse:7.44556
[105]	validation-rmse:7.44353
[106]	validation-rmse:7.44155
[107]	validation-rmse:7.44027
[108]	validation-rmse:7.43927
[109]	validation-rmse:7.43817
[110]	validation-rmse:7.43621
[111]	validation-rmse:7.43403
[112]	validation-rmse:7.43481
[113]	validation-rmse:7.43415
[114]	validation-rmse:7.43216
[115]	validation-rmse:7.43052
[116]	validation-rmse:7.42687
[117]	validation-rmse:7.42673
[118]	validation-rmse:7.42416
[119]	validation-rmse:7.41968
[120]	validation-rmse:7.41823
[121]	validation-rmse:7.41673
[122]	validation-rmse:7.41315
[123]	validation-rmse:7.41084
[124]	validation-rmse:7.40920
[125]	validation-rmse:7.40833
[126]	validation-rmse:7.40823
[127]	validation-rmse:7.40488
[128]	validation-rmse:7.40448
[129]	validation-rmse:7.40099
[130]	validation-rmse:7.39934
[131]	validation-rmse:7.39493
[132]	validation-rmse:7.39163
[133]	validation-rmse:7.38925
[134]	validation-rmse:7.39004
[135]	validation-rmse:7.38934
[136]	validation-rmse:7.38582
[137]	validation-rmse:7.38681
[138]	validation-rmse:7.38469
[139]	validation-rmse:7.38265
[140]	validation-rmse:7.38287
[141]	validation-rmse:7.37923
[142]	validation-rmse:7.37771
[143]	validation-rmse:7.37495
[144]	validation-rmse:7.37197
[145]	validation-rmse:7.37060
[146]	validation-rmse:7.36894
[147]	validation-rmse:7.36994
[148]	validation-rmse:7.36980
[149]	validation-rmse:7.36655
[150]	validation-rmse:7.36287
[151]	validation-rmse:7.36260
[152]	validation-rmse:7.36243
[153]	validation-rmse:7.36125
[154]	validation-rmse:7.35954
[155]	validation-rmse:7.35750
[156]	validation-rmse:7.35509
[157]	validation-rmse:7.35288
[158]	validation-rmse:7.35157
[159]	validation-rmse:7.34812
[160]	validation-rmse:7.34440
[161]	validation-rmse:7.34367
[162]	validation-rmse:7.34092
[163]	validation-rmse:7.34198
[164]	validation-rmse:7.34018
[165]	validation-rmse:7.34004
[166]	validation-rmse:7.33874
[167]	validation-rmse:7.33659
[168]	validation-rmse:7.33413
[169]	validation-rmse:7.33351
[170]	validation-rmse:7.33347
[171]	validation-rmse:7.33116
[172]	validation-rmse:7.32988
[173]	validation-rmse:7.32834
[174]	validation-rmse:7.32578
[175]	validation-rmse:7.32407
[176]	validation-rmse:7.32498
[177]	validation-rmse:7.32355
[178]	validation-rmse:7.32155
[179]	validation-rmse:7.32097
[180]	validation-rmse:7.31992
[181]	validation-rmse:7.31980
[182]	validation-rmse:7.31782
[183]	validation-rmse:7.31673
[184]	validation-rmse:7.31712
[185]	validation-rmse:7.31554
[186]	validation-rmse:7.31513
[187]	validation-rmse:7.31347
[188]	validation-rmse:7.31148
[189]	validation-rmse:7.31121
[190]	validation-rmse:7.30862
[191]	validation-rmse:7.30684
[192]	validation-rmse:7.30733
[193]	validation-rmse:7.30747
[194]	validation-rmse:7.30508
[195]	validation-rmse:7.30425
[196]	validation-rmse:7.30221
[197]	validation-rmse:7.30105
[198]	validation-rmse:7.30102
[199]	validation-rmse:7.29949
[200]	validation-rmse:7.29739
[201]	validation-rmse:7.29566
[202]	validation-rmse:7.29470
[203]	validation-rmse:7.29377
[204]	validation-rmse:7.29269
[205]	validation-rmse:7.29261
[206]	validation-rmse:7.29148
[207]	validation-rmse:7.28861
[208]	validation-rmse:7.28903
[209]	validation-rmse:7.28761
[210]	validation-rmse:7.28602
[211]	validation-rmse:7.28478
[212]	validation-rmse:7.28360
[213]	validation-rmse:7.28208
[214]	validation-rmse:7.28164
[215]	validation-rmse:7.28060
[216]	validation-rmse:7.27529
[217]	validation-rmse:7.27325
[218]	validation-rmse:7.27292
[219]	validation-rmse:7.27337
[220]	validation-rmse:7.27156
[221]	validation-rmse:7.26997
[222]	validation-rmse:7.26818
[223]	validation-rmse:7.26985
[224]	validation-rmse:7.26894
[225]	validation-rmse:7.26613
[226]	validation-rmse:7.26633
[227]	validation-rmse:7.26432
[228]	validation-rmse:7.26367
[229]	validation-rmse:7.26308
[230]	validation-rmse:7.26420
[231]	validation-rmse:7.26229
[232]	validation-rmse:7.26113
[233]	validation-rmse:7.26136
[234]	validation-rmse:7.25905
[235]	validation-rmse:7.25843
[236]	validation-rmse:7.25659
[237]	validation-rmse:7.25593
[238]	validation-rmse:7.25317
[239]	validation-rmse:7.25331
[240]	validation-rmse:7.25466
[241]	validation-rmse:7.25328
[242]	validation-rmse:7.25167
[243]	validation-rmse:7.24900
[244]	validation-rmse:7.24850
[245]	validation-rmse:7.24973
[246]	validation-rmse:7.24892
[247]	validation-rmse:7.24650
[248]	validation-rmse:7.24548
[249]	validation-rmse:7.24384
[250]	validation-rmse:7.24353
[251]	validation-rmse:7.24239
[252]	validation-rmse:7.24250
[253]	validation-rmse:7.24280
[254]	validation-rmse:7.24045
[255]	validation-rmse:7.23989
[256]	validation-rmse:7.23907
[257]	validation-rmse:7.23838
[258]	validation-rmse:7.23659
[259]	validation-rmse:7.23663
[260]	validation-rmse:7.23499
[261]	validation-rmse:7.23413
[262]	validation-rmse:7.23417
[263]	validation-rmse:7.23294
[264]	validation-rmse:7.23147
[265]	validation-rmse:7.23086
[266]	validation-rmse:7.23027
[267]	validation-rmse:7.22909
[268]	validation-rmse:7.22905
[269]	validation-rmse:7.22829
[270]	validation-rmse:7.22646
[271]	validation-rmse:7.22714
[272]	validation-rmse:7.22614
[273]	validation-rmse:7.22481
[274]	validation-rmse:7.22209
[275]	validation-rmse:7.22102
[276]	validation-rmse:7.22318
[277]	validation-rmse:7.22369
[278]	validation-rmse:7.22211
[279]	validation-rmse:7.22196
[280]	validation-rmse:7.22089
[281]	validation-rmse:7.21906
[282]	validation-rmse:7.21954
[283]	validation-rmse:7.21861
[284]	validation-rmse:7.21927
[285]	validation-rmse:7.21993
[286]	validation-rmse:7.21800
[287]	validation-rmse:7.21815
[288]	validation-rmse:7.21651
[289]	validation-rmse:7.21680
[290]	validation-rmse:7.21764
[291]	validation-rmse:7.21624
[292]	validation-rmse:7.21419
[293]	validation-rmse:7.21471
[294]	validation-rmse:7.21259
[295]	validation-rmse:7.21142
[296]	validation-rmse:7.21301
[297]	validation-rmse:7.21142
[298]	validation-rmse:7.21155
[299]	validation-rmse:7.20908
[300]	validation-rmse:7.20903
[301]	validation-rmse:7.20903
[302]	validation-rmse:7.20864
[303]	validation-rmse:7.20840
[304]	validation-rmse:7.20740
[305]	validation-rmse:7.20556
[306]	validation-rmse:7.20768
[307]	validation-rmse:7.20717
[308]	validation-rmse:7.20700
[309]	validation-rmse:7.20613
[310]	validation-rmse:7.20646
[311]	validation-rmse:7.20533
[312]	validation-rmse:7.20483
[313]	validation-rmse:7.20411
[314]	validation-rmse:7.20500
[315]	validation-rmse:7.20522
[316]	validation-rmse:7.20501
[317]	validation-rmse:7.20511
[318]	validation-rmse:7.20454
[319]	validation-rmse:7.20411
[320]	validation-rmse:7.20370
[321]	validation-rmse:7.20387
[322]	validation-rmse:7.20404
[323]	validation-rmse:7.20372
[324]	validation-rmse:7.20274
[325]	validation-rmse:7.20159
[326]	validation-rmse:7.20334
[327]	validation-rmse:7.20360
[328]	validation-rmse:7.20399
[329]	validation-rmse:7.20329
[330]	validation-rmse:7.20336
[331]	validation-rmse:7.20089
[332]	validation-rmse:7.20097
[333]	validation-rmse:7.20021
[334]	validation-rmse:7.20025
[335]	validation-rmse:7.19913
[336]	validation-rmse:7.19953
[337]	validation-rmse:7.19955
[338]	validation-rmse:7.19974
[339]	validation-rmse:7.19892
[340]	validation-rmse:7.19766
[341]	validation-rmse:7.19754
[342]	validation-rmse:7.19584
[343]	validation-rmse:7.19438
[344]	validation-rmse:7.19487
[345]	validation-rmse:7.19507
[346]	validation-rmse:7.19432
[347]	validation-rmse:7.19508
[348]	validation-rmse:7.19363
[349]	validation-rmse:7.19276
[350]	validation-rmse:7.19301
[351]	validation-rmse:7.19176
[352]	validation-rmse:7.19196
[353]	validation-rmse:7.19139
[354]	validation-rmse:7.19120
[355]	validation-rmse:7.19033
[356]	validation-rmse:7.18957
[357]	validation-rmse:7.18885
[358]	validation-rmse:7.18817
[359]	validation-rmse:7.18586
[360]	validation-rmse:7.18750
[361]	validation-rmse:7.18765
[362]	validation-rmse:7.18832
[363]	validation-rmse:7.18675
[364]	validation-rmse:7.18585
[365]	validation-rmse:7.18738
[366]	validation-rmse:7.18630
[367]	validation-rmse:7.18625
[368]	validation-rmse:7.18658
[369]	validation-rmse:7.18726
[370]	validation-rmse:7.18592
[371]	validation-rmse:7.18525
[372]	validation-rmse:7.18401
[373]	validation-rmse:7.18416
[374]	validation-rmse:7.18320
[375]	validation-rmse:7.18317
[376]	validation-rmse:7.18252
[377]	validation-rmse:7.18188
[378]	validation-rmse:7.18290
[379]	validation-rmse:7.18315
[380]	validation-rmse:7.18303
[381]	validation-rmse:7.18311
[382]	validation-rmse:7.18314
[383]	validation-rmse:7.18138
[384]	validation-rmse:7.18066
[385]	validation-rmse:7.17942
[386]	validation-rmse:7.17915
[387]	validation-rmse:7.18009
[388]	validation-rmse:7.17925
[389]	validation-rmse:7.17892
[390]	validation-rmse:7.17890
[391]	validation-rmse:7.17875
[392]	validation-rmse:7.17912
[393]	validation-rmse:7.17829
[394]	validation-rmse:7.17819
[395]	validation-rmse:7.17783
[396]	validation-rmse:7.17740
[397]	validation-rmse:7.17592
[398]	validation-rmse:7.17560
[399]	validation-rmse:7.17552
[400]	validation-rmse:7.17562
[401]	validation-rmse:7.17449
[402]	validation-rmse:7.17532
[403]	validation-rmse:7.17498
[404]	validation-rmse:7.17422
[405]	validation-rmse:7.17254
[406]	validation-rmse:7.17276
[407]	validation-rmse:7.17190
[408]	validation-rmse:7.17232
[409]	validation-rmse:7.17303
[410]	validation-rmse:7.17277
[411]	validation-rmse:7.17316
[412]	validation-rmse:7.17251
[413]	validation-rmse:7.17292
[414]	validation-rmse:7.17153
[415]	validation-rmse:7.17089
[416]	validation-rmse:7.17211
[417]	validation-rmse:7.17174
[418]	validation-rmse:7.17013
[419]	validation-rmse:7.16847
[420]	validation-rmse:7.16878
[421]	validation-rmse:7.16889
[422]	validation-rmse:7.16771
[423]	validation-rmse:7.16744
[424]	validation-rmse:7.16738
[425]	validation-rmse:7.16681
[426]	validation-rmse:7.16809
[427]	validation-rmse:7.16722
[428]	validation-rmse:7.16606
[429]	validation-rmse:7.16477
[430]	validation-rmse:7.16623
[431]	validation-rmse:7.16658
[432]	validation-rmse:7.16596
[433]	validation-rmse:7.16538
[434]	validation-rmse:7.16401
[435]	validation-rmse:7.16462
[436]	validation-rmse:7.16392
[437]	validation-rmse:7.16380
[438]	validation-rmse:7.16366
[439]	validation-rmse:7.16217
[440]	validation-rmse:7.16193
[441]	validation-rmse:7.16190
[442]	validation-rmse:7.16225
[443]	validation-rmse:7.16257
[444]	validation-rmse:7.16268
[445]	validation-rmse:7.16129
[446]	validation-rmse:7.16161
[447]	validation-rmse:7.16067
[448]	validation-rmse:7.16066
[449]	validation-rmse:7.16081
[450]	validation-rmse:7.16013
[451]	validation-rmse:7.16027
[452]	validation-rmse:7.16016
[453]	validation-rmse:7.16104
[454]	validation-rmse:7.16069
[455]	validation-rmse:7.15977
[456]	validation-rmse:7.16037
[457]	validation-rmse:7.15972
[458]	validation-rmse:7.15907
[459]	validation-rmse:7.15948
[460]	validation-rmse:7.15908
[461]	validation-rmse:7.15856
[462]	validation-rmse:7.15878
[463]	validation-rmse:7.15818
[464]	validation-rmse:7.15754
[465]	validation-rmse:7.15718
[466]	validation-rmse:7.15763
[467]	validation-rmse:7.15832
[468]	validation-rmse:7.15771
[469]	validation-rmse:7.15706
[470]	validation-rmse:7.15758
[471]	validation-rmse:7.15773
[472]	validation-rmse:7.15682
[473]	validation-rmse:7.15695
[474]	validation-rmse:7.15748
[475]	validation-rmse:7.15568
[476]	validation-rmse:7.15581
[477]	validation-rmse:7.15542
[478]	validation-rmse:7.15456
[479]	validation-rmse:7.15452
[480]	validation-rmse:7.15446
[481]	validation-rmse:7.15519
[482]	validation-rmse:7.15603
[483]	validation-rmse:7.15564
[484]	validation-rmse:7.15635
[485]	validation-rmse:7.15501
[486]	validation-rmse:7.15491
[487]	validation-rmse:7.15375
[488]	validation-rmse:7.15338
[489]	validation-rmse:7.15393
[490]	validation-rmse:7.15377
[491]	validation-rmse:7.15414
[492]	validation-rmse:7.15384
[493]	validation-rmse:7.15426
[494]	validation-rmse:7.15397
[495]	validation-rmse:7.15296
[496]	validation-rmse:7.15165
[497]	validation-rmse:7.15179
[498]	validation-rmse:7.15094
[499]	validation-rmse:7.15183
[500]	validation-rmse:7.15300
[501]	validation-rmse:7.15309
[502]	validation-rmse:7.15349
[503]	validation-rmse:7.15349
[504]	validation-rmse:7.15281
[505]	validation-rmse:7.15237
[506]	validation-rmse:7.15271
[507]	validation-rmse:7.15222
[508]	validation-rmse:7.15166
[509]	validation-rmse:7.15157
[510]	validation-rmse:7.15047
[511]	validation-rmse:7.15069
[512]	validation-rmse:7.15001
[513]	validation-rmse:7.15038
[514]	validation-rmse:7.15060
[515]	validation-rmse:7.15125
[516]	validation-rmse:7.15192
[517]	validation-rmse:7.15135
[518]	validation-rmse:7.15162
[519]	validation-rmse:7.15119
[520]	validation-rmse:7.14981
[521]	validation-rmse:7.14910
[522]	validation-rmse:7.15034
[523]	validation-rmse:7.14984
[524]	validation-rmse:7.14958
[525]	validation-rmse:7.15058
[526]	validation-rmse:7.15100
[527]	validation-rmse:7.15054
[528]	validation-rmse:7.14965
[529]	validation-rmse:7.14977
[530]	validation-rmse:7.15030
[531]	validation-rmse:7.15008
[532]	validation-rmse:7.14939
[533]	validation-rmse:7.14932
[534]	validation-rmse:7.14908
[535]	validation-rmse:7.14946
[536]	validation-rmse:7.14882
[537]	validation-rmse:7.14916
[538]	validation-rmse:7.14792
[539]	validation-rmse:7.14921
[540]	validation-rmse:7.14927
[541]	validation-rmse:7.14966
[542]	validation-rmse:7.14897
[543]	validation-rmse:7.14993
[544]	validation-rmse:7.14903
[545]	validation-rmse:7.14878
[546]	validation-rmse:7.14955
[547]	validation-rmse:7.14988
[548]	validation-rmse:7.15022
[549]	validation-rmse:7.14902
[550]	validation-rmse:7.14906
[551]	validation-rmse:7.14994
[552]	validation-rmse:7.14984
[553]	validation-rmse:7.14935
[554]	validation-rmse:7.15002
[555]	validation-rmse:7.15013
[556]	validation-rmse:7.14974
[557]	validation-rmse:7.14961
[558]	validation-rmse:7.14946
[559]	validation-rmse:7.14956
[560]	validation-rmse:7.14939
[561]	validation-rmse:7.14996
[562]	validation-rmse:7.14911
[563]	validation-rmse:7.14944
[564]	validation-rmse:7.15052
[565]	validation-rmse:7.15057
[566]	validation-rmse:7.15044
[567]	validation-rmse:7.15112
[568]	validation-rmse:7.15064
[569]	validation-rmse:7.14979
[570]	validation-rmse:7.14902
[571]	validation-rmse:7.14834
[572]	validation-rmse:7.14801
[573]	validation-rmse:7.14710
[574]	validation-rmse:7.14732
[575]	validation-rmse:7.14703
[576]	validation-rmse:7.14739
[577]	validation-rmse:7.14793
[578]	validation-rmse:7.14853
[579]	validation-rmse:7.14850
[580]	validation-rmse:7.14854
[581]	validation-rmse:7.14882
[582]	validation-rmse:7.14808
[583]	validation-rmse:7.14879
[584]	validation-rmse:7.14988
[585]	validation-rmse:7.14911
[586]	validation-rmse:7.14959
[587]	validation-rmse:7.14826
[588]	validation-rmse:7.14904
[589]	validation-rmse:7.14954
[590]	validation-rmse:7.15007
[591]	validation-rmse:7.15013
[592]	validation-rmse:7.14922
[593]	validation-rmse:7.14945
[594]	validation-rmse:7.14931
[595]	validation-rmse:7.14954
[596]	validation-rmse:7.14931
[597]	validation-rmse:7.14870
[598]	validation-rmse:7.14952
[599]	validation-rmse:7.14906
[600]	validation-rmse:7.14810
[601]	validation-rmse:7.14929
[602]	validation-rmse:7.14853
[603]	validation-rmse:7.14869
[604]	validation-rmse:7.14748
[605]	validation-rmse:7.14803
[606]	validation-rmse:7.14860
[607]	validation-rmse:7.14890
[608]	validation-rmse:7.14789
[609]	validation-rmse:7.14810
[610]	validation-rmse:7.14785
[611]	validation-rmse:7.14725
[612]	validation-rmse:7.14727
[613]	validation-rmse:7.14779
[614]	validation-rmse:7.14657
[615]	validation-rmse:7.14655
[616]	validation-rmse:7.14702
[617]	validation-rmse:7.14734
[618]	validation-rmse:7.14740
[619]	validation-rmse:7.14689
[620]	validation-rmse:7.14684
[621]	validation-rmse:7.14707
[622]	validation-rmse:7.14692
[623]	validation-rmse:7.14671
[624]	validation-rmse:7.14702
[625]	validation-rmse:7.14671
[626]	validation-rmse:7.14742
[627]	validation-rmse:7.14804
[628]	validation-rmse:7.14699
[629]	validation-rmse:7.14682
[630]	validation-rmse:7.14696
[631]	validation-rmse:7.14648
[632]	validation-rmse:7.14681
[633]	validation-rmse:7.14689
[634]	validation-rmse:7.14619
[635]	validation-rmse:7.14594
[636]	validation-rmse:7.14580
[637]	validation-rmse:7.14648
[638]	validation-rmse:7.14592
[639]	validation-rmse:7.14556
[640]	validation-rmse:7.14676
[641]	validation-rmse:7.14750
[642]	validation-rmse:7.14735
[643]	validation-rmse:7.14702
[644]	validation-rmse:7.14719
[645]	validation-rmse:7.14759
[646]	validation-rmse:7.14787
[647]	validation-rmse:7.14720
[648]	validation-rmse:7.14736
[649]	validation-rmse:7.14710
[650]	validation-rmse:7.14760
[651]	validation-rmse:7.14686
[652]	validation-rmse:7.14653
[653]	validation-rmse:7.14676
[654]	validation-rmse:7.14733
[655]	validation-rmse:7.14714
[656]	validation-rmse:7.14717
[657]	validation-rmse:7.14712
[658]	validation-rmse:7.14753
[659]	validation-rmse:7.14712
[660]	validation-rmse:7.14710
[661]	validation-rmse:7.14828
[662]	validation-rmse:7.14835
[663]	validation-rmse:7.14807
[664]	validation-rmse:7.14845
[665]	validation-rmse:7.14812
[666]	validation-rmse:7.14839
[667]	validation-rmse:7.14869
[668]	validation-rmse:7.14812
[669]	validation-rmse:7.14800
[670]	validation-rmse:7.14800

[12:11:06] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[0]	validation-rmse:10.03455
[1]	validation-rmse:9.49721
[2]	validation-rmse:9.21921
[3]	validation-rmse:8.85488
[4]	validation-rmse:8.73957
[5]	validation-rmse:8.58983
[6]	validation-rmse:8.37534
[7]	validation-rmse:8.13872
[8]	validation-rmse:8.05810
[9]	validation-rmse:7.98549
[10]	validation-rmse:7.94695
[11]	validation-rmse:7.90129
[12]	validation-rmse:7.87161
[13]	validation-rmse:7.82884
[14]	validation-rmse:7.80514
[15]	validation-rmse:7.78264
[16]	validation-rmse:7.76788
[17]	validation-rmse:7.75871
[18]	validation-rmse:7.74938
[19]	validation-rmse:7.74643
[20]	validation-rmse:7.74388
[21]	validation-rmse:7.74398
[22]	validation-rmse:7.74343
[23]	validation-rmse:7.74361
[24]	validation-rmse:7.74377
[25]	validation-rmse:7.74341
[26]	validation-rmse:7.74457
[27]	validation-rmse:7.74479
[28]	validation-rmse:7.74486
[29]	validation-rmse:7.74562
[30]	validation-rmse:7.74545
[31]	validation-rmse:7.74571
[32]	validation-rmse:7.74598
[33]	validation-rmse:7.74643
[34]	validation-rmse:7.74691
[35]	validation-rmse:7.74639
[36]	validation-rmse:7.74678
[37]	validation-rmse:7.74667
[38]	validation-rmse:7.74618
[39]	validation-rmse:7.74645
[40]	validation-rmse:7.74614
[41]	validation-rmse:7.74629
[42]	validation-rmse:7.74649
[43]	validation-rmse:7.74673
[44]	validation-rmse:7.74660
[45]	validation-rmse:7.74669
[46]	validation-rmse:7.74672
[47]	validation-rmse:7.74601
[48]	validation-rmse:7.74618
[49]	validation-rmse:7.74578
[50]	validation-rmse:7.74605
[51]	validation-rmse:7.74597
[52]	validation-rmse:7.74608
[53]	validation-rmse:7.74597
[54]	validation-rmse:7.74602
[55]	validation-rmse:7.74591
[56]	validation-rmse:7.74577
[57]	validation-rmse:7.74548
[58]	validation-rmse:7.74550
[59]	validation-rmse:7.74526
[60]	validation-rmse:7.74516
[61]	validation-rmse:7.74481
[62]	validation-rmse:7.74467
[63]	validation-rmse:7.74463
[64]	validation-rmse:7.74460
[65]	validation-rmse:7.74458
[66]	validation-rmse:7.74463
[67]	validation-rmse:7.74447
[68]	validation-rmse:7.74439
[69]	validation-rmse:7.74443
[70]	validation-rmse:7.74424
[71]	validation-rmse:7.74442
[72]	validation-rmse:7.74368
[73]	validation-rmse:7.74435
[74]	validation-rmse:7.74387
[75]	validation-rmse:7.74384
 12%|█▏        | 6/50 [21:48<2:10:49, 178.40s/trial, best loss: 7.14819276917268]

[12:11:44] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[0]	validation-rmse:19.26708
[1]	validation-rmse:17.61653
[2]	validation-rmse:16.16733
[3]	validation-rmse:14.93394
[4]	validation-rmse:13.91707
[5]	validation-rmse:12.99603
[6]	validation-rmse:12.24182
[7]	validation-rmse:11.64585
[8]	validation-rmse:11.09709
[9]	validation-rmse:10.67093
[10]	validation-rmse:10.30683
[11]	validation-rmse:9.97176
[12]	validation-rmse:9.72044
[13]	validation-rmse:9.44709
[14]	validation-rmse:9.26805
[15]	validation-rmse:9.08341
[16]	validation-rmse:8.94318
[17]	validation-rmse:8.83781
[18]	validation-rmse:8.74260
[19]	validation-rmse:8.62287
[20]	validation-rmse:8.54013
[21]	validation-rmse:8.47781
[22]	validation-rmse:8.40603
[23]	validation-rmse:8.31821
[24]	validation-rmse:8.26915
[25]	validation-rmse:8.20683
[26]	validation-rmse:8.17187
[27]	validation-rmse:8.13303
[28]	validation-rmse:8.09654
[29]	validation-rmse:8.04389
[30]	validation-rmse:8.02057
[31]	validation-rmse:7.99800
[32]	validation-rmse:7.95980
[33]	validation-rmse:7.93747
[34]	validation-rmse:7.92101
[35]	validation-rmse:7.89552
[36]	validation-rmse:7.87924
[37]	validation-rmse:7.86716
[38]	validation-rmse:7.84721
[39]	validation-rmse:7.83736
[40]	validation-rmse:7.82240
[41]	validation-rmse:7.80638
[42]	validation-rmse:7.79525
[43]	validation-rmse:7.78404
[44]	validation-rmse:7.76792
[45]	validation-rmse:7.74719
[46]	validation-rmse:7.73298
[47]	validation-rmse:7.71702
[48]	validation-rmse:7.71059
[49]	validation-rmse:7.69131
[50]	validation-rmse:7.68560
[51]	validation-rmse:7.67932
[52]	validation-rmse:7.67540
[53]	validation-rmse:7.67177
[54]	validation-rmse:7.66760
[55]	validation-rmse:7.65943
[56]	validation-rmse:7.65091
[57]	validation-rmse:7.64594
[58]	validation-rmse:7.64194
[59]	validation-rmse:7.63646
[60]	validation-rmse:7.62948
[61]	validation-rmse:7.62699
[62]	validation-rmse:7.62457
[63]	validation-rmse:7.61705
[64]	validation-rmse:7.61456
[65]	validation-rmse:7.61260
[66]	validation-rmse:7.61059
[67]	validation-rmse:7.60810
[68]	validation-rmse:7.60683
[69]	validation-rmse:7.60221
[70]	validation-rmse:7.59753
[71]	validation-rmse:7.59203
[72]	validation-rmse:7.59005
[73]	validation-rmse:7.58867
[74]	validation-rmse:7.58501
[75]	validation-rmse:7.58320
[76]	validation-rmse:7.58040
[77]	validation-rmse:7.57857
[78]	validation-rmse:7.57665
[79]	validation-rmse:7.57487
[80]	validation-rmse:7.57375
[81]	validation-rmse:7.57296
[82]	validation-rmse:7.57234
[83]	validation-rmse:7.57046
[84]	validation-rmse:7.56894
[85]	validation-rmse:7.56779
[86]	validation-rmse:7.56706
[87]	validation-rmse:7.56559
[88]	validation-rmse:7.56459
[89]	validation-rmse:7.56337
[90]	validation-rmse:7.56263
[91]	validation-rmse:7.56046
[92]	validation-rmse:7.55842
[93]	validation-rmse:7.55796
[94]	validation-rmse:7.55690
[95]	validation-rmse:7.55600
[96]	validation-rmse:7.55574
[97]	validation-rmse:7.55389
[98]	validation-rmse:7.55289
[99]	validation-rmse:7.55151
[100]	validation-rmse:7.55032
[101]	validation-rmse:7.54947
[102]	validation-rmse:7.54882
[103]	validation-rmse:7.54763
[104]	validation-rmse:7.54606
[105]	validation-rmse:7.54550
[106]	validation-rmse:7.54506
[107]	validation-rmse:7.54404
[108]	validation-rmse:7.54311
[109]	validation-rmse:7.54264
[110]	validation-rmse:7.54214
[111]	validation-rmse:7.54133
[112]	validation-rmse:7.54033
[113]	validation-rmse:7.53904
[114]	validation-rmse:7.53819
[115]	validation-rmse:7.53712
[116]	validation-rmse:7.53655
[117]	validation-rmse:7.53563
[118]	validation-rmse:7.53487
[119]	validation-rmse:7.53419
[120]	validation-rmse:7.53382
[121]	validation-rmse:7.53225
[122]	validation-rmse:7.53110
[123]	validation-rmse:7.53050
[124]	validation-rmse:7.52963
[125]	validation-rmse:7.52856
[126]	validation-rmse:7.52816
[127]	validation-rmse:7.52723
[128]	validation-rmse:7.52646
[129]	validation-rmse:7.52581
[130]	validation-rmse:7.52503
[131]	validation-rmse:7.52383
[132]	validation-rmse:7.52291
[133]	validation-rmse:7.52224
[134]	validation-rmse:7.52157
[135]	validation-rmse:7.52107
[136]	validation-rmse:7.52006
[137]	validation-rmse:7.51898
[138]	validation-rmse:7.51872
[139]	validation-rmse:7.51789
[140]	validation-rmse:7.51607
[141]	validation-rmse:7.51504
[142]	validation-rmse:7.51415
[143]	validation-rmse:7.51400
[144]	validation-rmse:7.51315
[145]	validation-rmse:7.51185
[146]	validation-rmse:7.51117
[147]	validation-rmse:7.51044
[148]	validation-rmse:7.50945
[149]	validation-rmse:7.50905
[150]	validation-rmse:7.50799
[151]	validation-rmse:7.50721
[152]	validation-rmse:7.50637
[153]	validation-rmse:7.50601
[154]	validation-rmse:7.50541
[155]	validation-rmse:7.50395
[156]	validation-rmse:7.50336
[157]	validation-rmse:7.50239
[158]	validation-rmse:7.50163
[159]	validation-rmse:7.50136
[160]	validation-rmse:7.50104
[161]	validation-rmse:7.50026
[162]	validation-rmse:7.49934
[163]	validation-rmse:7.49857
[164]	validation-rmse:7.49792
[165]	validation-rmse:7.49716
[166]	validation-rmse:7.49676
[167]	validation-rmse:7.49607
[168]	validation-rmse:7.49531
[169]	validation-rmse:7.49477
[170]	validation-rmse:7.49425
[171]	validation-rmse:7.49375
[172]	validation-rmse:7.49261
[173]	validation-rmse:7.49185
[174]	validation-rmse:7.49087
[175]	validation-rmse:7.48964
[176]	validation-rmse:7.48924
[177]	validation-rmse:7.48879
[178]	validation-rmse:7.48784
[179]	validation-rmse:7.48759
[180]	validation-rmse:7.48724
[181]	validation-rmse:7.48676
[182]	validation-rmse:7.48584
[183]	validation-rmse:7.48521
[184]	validation-rmse:7.48487
[185]	validation-rmse:7.48438
[186]	validation-rmse:7.48380
[187]	validation-rmse:7.48354
[188]	validation-rmse:7.48281
[189]	validation-rmse:7.48132
[190]	validation-rmse:7.48071
[191]	validation-rmse:7.48040
[192]	validation-rmse:7.47951
[193]	validation-rmse:7.47858
[194]	validation-rmse:7.47852
[195]	validation-rmse:7.47828
[196]	validation-rmse:7.47752
[197]	validation-rmse:7.47697
[198]	validation-rmse:7.47630
[199]	validation-rmse:7.47561
[200]	validation-rmse:7.47531
[201]	validation-rmse:7.47486
[202]	validation-rmse:7.47392
[203]	validation-rmse:7.47322
[204]	validation-rmse:7.47279
[205]	validation-rmse:7.47193
[206]	validation-rmse:7.47168
[207]	validation-rmse:7.47126
[208]	validation-rmse:7.47144
[209]	validation-rmse:7.47088
[210]	validation-rmse:7.47034
[211]	validation-rmse:7.46879
[212]	validation-rmse:7.46863
[213]	validation-rmse:7.46818
[214]	validation-rmse:7.46765
[215]	validation-rmse:7.46693
[216]	validation-rmse:7.46626
[217]	validation-rmse:7.46601
[218]	validation-rmse:7.46570
[219]	validation-rmse:7.46541
[220]	validation-rmse:7.46508
[221]	validation-rmse:7.46462
[222]	validation-rmse:7.46425
[223]	validation-rmse:7.46398
[224]	validation-rmse:7.46373
[225]	validation-rmse:7.46354
[226]	validation-rmse:7.46288
[227]	validation-rmse:7.46193
[228]	validation-rmse:7.46163
[229]	validation-rmse:7.46137
[230]	validation-rmse:7.46080
[231]	validation-rmse:7.45996
[232]	validation-rmse:7.45919
[233]	validation-rmse:7.45865
[234]	validation-rmse:7.45778
[235]	validation-rmse:7.45686
[236]	validation-rmse:7.45606
[237]	validation-rmse:7.45533
[238]	validation-rmse:7.45497
[239]	validation-rmse:7.45413
[240]	validation-rmse:7.45354
[241]	validation-rmse:7.45283
[242]	validation-rmse:7.45241
[243]	validation-rmse:7.45192
[244]	validation-rmse:7.45140
[245]	validation-rmse:7.45096
[246]	validation-rmse:7.45010
[247]	validation-rmse:7.44951
[248]	validation-rmse:7.44930
[249]	validation-rmse:7.44891
[250]	validation-rmse:7.44829
[251]	validation-rmse:7.44781
[252]	validation-rmse:7.44764
[253]	validation-rmse:7.44696
[254]	validation-rmse:7.44676
[255]	validation-rmse:7.44648
[256]	validation-rmse:7.44552
[257]	validation-rmse:7.44459
[258]	validation-rmse:7.44414
[259]	validation-rmse:7.44356
[260]	validation-rmse:7.44332
[261]	validation-rmse:7.44337
[262]	validation-rmse:7.44295
[263]	validation-rmse:7.44286
[264]	validation-rmse:7.44242
[265]	validation-rmse:7.44145
[266]	validation-rmse:7.44121
[267]	validation-rmse:7.44094
[268]	validation-rmse:7.43984
[269]	validation-rmse:7.43987
[270]	validation-rmse:7.43864
[271]	validation-rmse:7.43860
[272]	validation-rmse:7.43808
[273]	validation-rmse:7.43785
[274]	validation-rmse:7.43772
[275]	validation-rmse:7.43708
[276]	validation-rmse:7.43649
[277]	validation-rmse:7.43652
[278]	validation-rmse:7.43614
[279]	validation-rmse:7.43580
[280]	validation-rmse:7.43539
[281]	validation-rmse:7.43492
[282]	validation-rmse:7.43382
[283]	validation-rmse:7.43363
[284]	validation-rmse:7.43334
[285]	validation-rmse:7.43335
[286]	validation-rmse:7.43279
[287]	validation-rmse:7.43230
[288]	validation-rmse:7.43206
[289]	validation-rmse:7.43162
[290]	validation-rmse:7.43117
[291]	validation-rmse:7.43060
[292]	validation-rmse:7.43024
[293]	validation-rmse:7.42992
[294]	validation-rmse:7.43002
[295]	validation-rmse:7.42957
[296]	validation-rmse:7.42956
[297]	validation-rmse:7.42918
[298]	validation-rmse:7.42866
[299]	validation-rmse:7.42847
[300]	validation-rmse:7.42802
[301]	validation-rmse:7.42763
[302]	validation-rmse:7.42688
[303]	validation-rmse:7.42656
[304]	validation-rmse:7.42640
[305]	validation-rmse:7.42625
[306]	validation-rmse:7.42543
[307]	validation-rmse:7.42522
[308]	validation-rmse:7.42496
[309]	validation-rmse:7.42456
[310]	validation-rmse:7.42391
[311]	validation-rmse:7.42316
[312]	validation-rmse:7.42256
[313]	validation-rmse:7.42235
[314]	validation-rmse:7.42202
[315]	validation-rmse:7.42175
[316]	validation-rmse:7.42107
[317]	validation-rmse:7.42055
[318]	validation-rmse:7.42036
[319]	validation-rmse:7.41949
[320]	validation-rmse:7.41875
[321]	validation-rmse:7.41859
[322]	validation-rmse:7.41810
[323]	validation-rmse:7.41786
[324]	validation-rmse:7.41761
[325]	validation-rmse:7.41701
[326]	validation-rmse:7.41614
[327]	validation-rmse:7.41596
[328]	validation-rmse:7.41551
[329]	validation-rmse:7.41507
[330]	validation-rmse:7.41483
[331]	validation-rmse:7.41455
[332]	validation-rmse:7.41432
[333]	validation-rmse:7.41397
[334]	validation-rmse:7.41400
[335]	validation-rmse:7.41362
[336]	validation-rmse:7.41340
[337]	validation-rmse:7.41320
[338]	validation-rmse:7.41295
[339]	validation-rmse:7.41252
[340]	validation-rmse:7.41192
[341]	validation-rmse:7.41158
[342]	validation-rmse:7.41111
[343]	validation-rmse:7.41086
[344]	validation-rmse:7.41029
[345]	validation-rmse:7.40977
[346]	validation-rmse:7.40931
[347]	validation-rmse:7.40886
[348]	validation-rmse:7.40885
[349]	validation-rmse:7.40896
[350]	validation-rmse:7.40818
[351]	validation-rmse:7.40746
[352]	validation-rmse:7.40666
[353]	validation-rmse:7.40621
[354]	validation-rmse:7.40589
[355]	validation-rmse:7.40592
[356]	validation-rmse:7.40531
[357]	validation-rmse:7.40503
[358]	validation-rmse:7.40459
[359]	validation-rmse:7.40397
[360]	validation-rmse:7.40372
[361]	validation-rmse:7.40287
[362]	validation-rmse:7.40195
[363]	validation-rmse:7.40183
[364]	validation-rmse:7.40091
[365]	validation-rmse:7.40062
[366]	validation-rmse:7.40044
[367]	validation-rmse:7.40034
[368]	validation-rmse:7.39980
[369]	validation-rmse:7.39971
[370]	validation-rmse:7.39957
[371]	validation-rmse:7.39908
[372]	validation-rmse:7.39870
[373]	validation-rmse:7.39798
[374]	validation-rmse:7.39791
[375]	validation-rmse:7.39777
[376]	validation-rmse:7.39781
[377]	validation-rmse:7.39773
[378]	validation-rmse:7.39719
[379]	validation-rmse:7.39701
[380]	validation-rmse:7.39720
[381]	validation-rmse:7.39671
[382]	validation-rmse:7.39661
[383]	validation-rmse:7.39655
[384]	validation-rmse:7.39616
[385]	validation-rmse:7.39552
[386]	validation-rmse:7.39531
[387]	validation-rmse:7.39510
[388]	validation-rmse:7.39404
[389]	validation-rmse:7.39382
[390]	validation-rmse:7.39366
[391]	validation-rmse:7.39312
[392]	validation-rmse:7.39283
[393]	validation-rmse:7.39283
[394]	validation-rmse:7.39266
[395]	validation-rmse:7.39212
[396]	validation-rmse:7.39182
[397]	validation-rmse:7.39198
[398]	validation-rmse:7.39174
[399]	validation-rmse:7.39152
[400]	validation-rmse:7.39112
[401]	validation-rmse:7.39101
[402]	validation-rmse:7.39047
[403]	validation-rmse:7.39015
[404]	validation-rmse:7.38937
[405]	validation-rmse:7.38892
[406]	validation-rmse:7.38834
[407]	validation-rmse:7.38799
[408]	validation-rmse:7.38734
[409]	validation-rmse:7.38700
[410]	validation-rmse:7.38651
[411]	validation-rmse:7.38652
[412]	validation-rmse:7.38570
[413]	validation-rmse:7.38530
[414]	validation-rmse:7.38524
[415]	validation-rmse:7.38500
[416]	validation-rmse:7.38483
[417]	validation-rmse:7.38448
[418]	validation-rmse:7.38449
[419]	validation-rmse:7.38439
[420]	validation-rmse:7.38418
[421]	validation-rmse:7.38412
[422]	validation-rmse:7.38376
[423]	validation-rmse:7.38389
[424]	validation-rmse:7.38375
[425]	validation-rmse:7.38329
[426]	validation-rmse:7.38278
[427]	validation-rmse:7.38166
[428]	validation-rmse:7.38169
[429]	validation-rmse:7.38126
[430]	validation-rmse:7.38097
[431]	validation-rmse:7.38060
[432]	validation-rmse:7.38021
[433]	validation-rmse:7.37971
[434]	validation-rmse:7.37937
[435]	validation-rmse:7.37875
[436]	validation-rmse:7.37884
[437]	validation-rmse:7.37906
[438]	validation-rmse:7.37880
[439]	validation-rmse:7.37855
[440]	validation-rmse:7.37796
[441]	validation-rmse:7.37816
[442]	validation-rmse:7.37773
[443]	validation-rmse:7.37736
[444]	validation-rmse:7.37669
[445]	validation-rmse:7.37665
[446]	validation-rmse:7.37645
[447]	validation-rmse:7.37619
[448]	validation-rmse:7.37599
[449]	validation-rmse:7.37571
[450]	validation-rmse:7.37527
[451]	validation-rmse:7.37487
[452]	validation-rmse:7.37473
[453]	validation-rmse:7.37423
[454]	validation-rmse:7.37404
[455]	validation-rmse:7.37371
[456]	validation-rmse:7.37354
[457]	validation-rmse:7.37317
[458]	validation-rmse:7.37318
[459]	validation-rmse:7.37279
[460]	validation-rmse:7.37271
[461]	validation-rmse:7.37250
[462]	validation-rmse:7.37195
[463]	validation-rmse:7.37186
[464]	validation-rmse:7.37160
[465]	validation-rmse:7.37135
[466]	validation-rmse:7.37007
[467]	validation-rmse:7.36959
[468]	validation-rmse:7.36913
[469]	validation-rmse:7.36878
[470]	validation-rmse:7.36852
[471]	validation-rmse:7.36810
[472]	validation-rmse:7.36778
[473]	validation-rmse:7.36766
[474]	validation-rmse:7.36719
[475]	validation-rmse:7.36685
[476]	validation-rmse:7.36641
[477]	validation-rmse:7.36610
[478]	validation-rmse:7.36577
[479]	validation-rmse:7.36522
[480]	validation-rmse:7.36507
[481]	validation-rmse:7.36474
[482]	validation-rmse:7.36447
[483]	validation-rmse:7.36388
[484]	validation-rmse:7.36363
[485]	validation-rmse:7.36342
[486]	validation-rmse:7.36321
[487]	validation-rmse:7.36341
[488]	validation-rmse:7.36344
[489]	validation-rmse:7.36324
[490]	validation-rmse:7.36320
[491]	validation-rmse:7.36273
[492]	validation-rmse:7.36279
[493]	validation-rmse:7.36229
[494]	validation-rmse:7.36195
[495]	validation-rmse:7.36171
[496]	validation-rmse:7.36129
[497]	validation-rmse:7.36075
[498]	validation-rmse:7.36046
[499]	validation-rmse:7.36023
[500]	validation-rmse:7.36027
[501]	validation-rmse:7.35984
[502]	validation-rmse:7.35958
[503]	validation-rmse:7.35919
[504]	validation-rmse:7.35899
[505]	validation-rmse:7.35885
[506]	validation-rmse:7.35846
[507]	validation-rmse:7.35830
[508]	validation-rmse:7.35815
[509]	validation-rmse:7.35765
[510]	validation-rmse:7.35750
[511]	validation-rmse:7.35722
[512]	validation-rmse:7.35716
[513]	validation-rmse:7.35713
[514]	validation-rmse:7.35713
[515]	validation-rmse:7.35670
[516]	validation-rmse:7.35643
[517]	validation-rmse:7.35628
[518]	validation-rmse:7.35600
[519]	validation-rmse:7.35569
[520]	validation-rmse:7.35526
[521]	validation-rmse:7.35507
[522]	validation-rmse:7.35492
[523]	validation-rmse:7.35479
[524]	validation-rmse:7.35442
[525]	validation-rmse:7.35405
[526]	validation-rmse:7.35355
[527]	validation-rmse:7.35355
[528]	validation-rmse:7.35309
[529]	validation-rmse:7.35290
[530]	validation-rmse:7.35273
[531]	validation-rmse:7.35224
[532]	validation-rmse:7.35206
[533]	validation-rmse:7.35196
[534]	validation-rmse:7.35129
[535]	validation-rmse:7.35102
[536]	validation-rmse:7.35084
[537]	validation-rmse:7.35042
[538]	validation-rmse:7.35017
[539]	validation-rmse:7.35030
[540]	validation-rmse:7.34962
[541]	validation-rmse:7.34976
[542]	validation-rmse:7.34933
[543]	validation-rmse:7.34936
[544]	validation-rmse:7.34908
[545]	validation-rmse:7.34858
[546]	validation-rmse:7.34859
[547]	validation-rmse:7.34867
[548]	validation-rmse:7.34811
[549]	validation-rmse:7.34785
[550]	validation-rmse:7.34760
[551]	validation-rmse:7.34736
[552]	validation-rmse:7.34706
[553]	validation-rmse:7.34648
[554]	validation-rmse:7.34653
[555]	validation-rmse:7.34603
[556]	validation-rmse:7.34597
[557]	validation-rmse:7.34590
[558]	validation-rmse:7.34537
[559]	validation-rmse:7.34540
[560]	validation-rmse:7.34537
[561]	validation-rmse:7.34553
[562]	validation-rmse:7.34546
[563]	validation-rmse:7.34503
[564]	validation-rmse:7.34483
[565]	validation-rmse:7.34446
[566]	validation-rmse:7.34434
[567]	validation-rmse:7.34347
[568]	validation-rmse:7.34323
[569]	validation-rmse:7.34273
[570]	validation-rmse:7.34260
[571]	validation-rmse:7.34234
[572]	validation-rmse:7.34211
[573]	validation-rmse:7.34172
[574]	validation-rmse:7.34150
[575]	validation-rmse:7.34141
[576]	validation-rmse:7.34103
[577]	validation-rmse:7.34042
[578]	validation-rmse:7.34010
[579]	validation-rmse:7.33951
[580]	validation-rmse:7.33962
[581]	validation-rmse:7.33936
[582]	validation-rmse:7.33929
[583]	validation-rmse:7.33874
[584]	validation-rmse:7.33876
[585]	validation-rmse:7.33823
[586]	validation-rmse:7.33772
[587]	validation-rmse:7.33760
[588]	validation-rmse:7.33743
[589]	validation-rmse:7.33688
[590]	validation-rmse:7.33644
[591]	validation-rmse:7.33609
[592]	validation-rmse:7.33575
[593]	validation-rmse:7.33567
[594]	validation-rmse:7.33577
[595]	validation-rmse:7.33576
[596]	validation-rmse:7.33533
[597]	validation-rmse:7.33491
[598]	validation-rmse:7.33496
[599]	validation-rmse:7.33496
[600]	validation-rmse:7.33509
[601]	validation-rmse:7.33478
[602]	validation-rmse:7.33422
[603]	validation-rmse:7.33387
[604]	validation-rmse:7.33358
[605]	validation-rmse:7.33345
[606]	validation-rmse:7.33299
[607]	validation-rmse:7.33287
[608]	validation-rmse:7.33248
[609]	validation-rmse:7.33248
[610]	validation-rmse:7.33230
[611]	validation-rmse:7.33192
[612]	validation-rmse:7.33176
[613]	validation-rmse:7.33153
[614]	validation-rmse:7.33129
[615]	validation-rmse:7.33090
[616]	validation-rmse:7.33069
[617]	validation-rmse:7.33029
[618]	validation-rmse:7.33024
[619]	validation-rmse:7.33019
[620]	validation-rmse:7.32999
[621]	validation-rmse:7.32984
[622]	validation-rmse:7.32928
[623]	validation-rmse:7.32891
[624]	validation-rmse:7.32858
[625]	validation-rmse:7.32856
[626]	validation-rmse:7.32829
[627]	validation-rmse:7.32783
[628]	validation-rmse:7.32768
[629]	validation-rmse:7.32758
[630]	validation-rmse:7.32722
[631]	validation-rmse:7.32696
[632]	validation-rmse:7.32674
[633]	validation-rmse:7.32686
[634]	validation-rmse:7.32632
[635]	validation-rmse:7.32602
[636]	validation-rmse:7.32582
[637]	validation-rmse:7.32609
[638]	validation-rmse:7.32588
[639]	validation-rmse:7.32557
[640]	validation-rmse:7.32521
[641]	validation-rmse:7.32479
[642]	validation-rmse:7.32495
[643]	validation-rmse:7.32473
[644]	validation-rmse:7.32423
[645]	validation-rmse:7.32381
[646]	validation-rmse:7.32353
[647]	validation-rmse:7.32318
[648]	validation-rmse:7.32283
[649]	validation-rmse:7.32259
[650]	validation-rmse:7.32255
[651]	validation-rmse:7.32226
[652]	validation-rmse:7.32201
[653]	validation-rmse:7.32156
[654]	validation-rmse:7.32153
[655]	validation-rmse:7.32087
[656]	validation-rmse:7.32097
[657]	validation-rmse:7.32038
[658]	validation-rmse:7.32026
[659]	validation-rmse:7.31979
[660]	validation-rmse:7.31954
[661]	validation-rmse:7.31909
[662]	validation-rmse:7.31907
[663]	validation-rmse:7.31892
[664]	validation-rmse:7.31804
[665]	validation-rmse:7.31752
[666]	validation-rmse:7.31712
[667]	validation-rmse:7.31695
[668]	validation-rmse:7.31648

[12:17:59] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[0]	validation-rmse:19.02429
[1]	validation-rmse:17.29315
[2]	validation-rmse:15.92351
[3]	validation-rmse:14.84334
[4]	validation-rmse:14.01069
[5]	validation-rmse:13.35033
[6]	validation-rmse:12.85514
[7]	validation-rmse:12.46532
[8]	validation-rmse:12.15175
[9]	validation-rmse:11.91596
[10]	validation-rmse:11.72990
[11]	validation-rmse:11.58053
[12]	validation-rmse:11.46729
[13]	validation-rmse:11.36548
[14]	validation-rmse:11.28507
[15]	validation-rmse:11.22042
[16]	validation-rmse:11.16270
[17]	validation-rmse:11.11619
[18]	validation-rmse:11.07085
[19]	validation-rmse:11.01989
[20]	validation-rmse:10.98718
[21]	validation-rmse:10.95674
[22]	validation-rmse:10.92565
[23]	validation-rmse:10.90184
[24]	validation-rmse:10.88248
[25]	validation-rmse:10.85757
[26]	validation-rmse:10.84061
[27]	validation-rmse:10.81835
[28]	validation-rmse:10.80196
[29]	validation-rmse:10.78707
[30]	validation-rmse:10.76903
[31]	validation-rmse:10.75237
[32]	validation-rmse:10.71844
[33]	validation-rmse:10.70364
[34]	validation-rmse:10.68951
[35]	validation-rmse:10.67470
[36]	validation-rmse:10.65952
[37]	validation-rmse:10.64567
[38]	validation-rmse:10.61413
[39]	validation-rmse:10.59382
[40]	validation-rmse:10.58351
[41]	validation-rmse:10.57439
[42]	validation-rmse:10.56123
[43]	validation-rmse:10.55155
[44]	validation-rmse:10.54001
[45]	validation-rmse:10.53230
[46]	validation-rmse:10.52183
[47]	validation-rmse:10.51488
[48]	validation-rmse:10.50191
[49]	validation-rmse:10.48599
[50]	validation-rmse:10.47983
[51]	validation-rmse:10.47221
[52]	validation-rmse:10.45593
[53]	validation-rmse:10.43747
[54]	validation-rmse:10.42676
[55]	validation-rmse:10.42008
[56]	validation-rmse:10.40754
[57]	validation-rmse:10.40206
[58]	validation-rmse:10.39206
[59]	validation-rmse:10.38628
[60]	validation-rmse:10.37132
[61]	validation-rmse:10.36097
[62]	validation-rmse:10.33732
[63]	validation-rmse:10.33213
[64]	validation-rmse:10.32647
[65]	validation-rmse:10.31511
[66]	validation-rmse:10.30458
[67]	validation-rmse:10.29456
[68]	validation-rmse:10.28726
[69]	validation-rmse:10.27650
[70]	validation-rmse:10.27205
[71]	validation-rmse:10.26336
[72]	validation-rmse:10.25837
[73]	validation-rmse:10.25312
[74]	validation-rmse:10.24769
[75]	validation-rmse:10.24266
[76]	validation-rmse:10.23797
[77]	validation-rmse:10.23320
[78]	validation-rmse:10.22291
[79]	validation-rmse:10.20787
[80]	validation-rmse:10.19316
[81]	validation-rmse:10.18770
[82]	validation-rmse:10.18192
[83]	validation-rmse:10.17679
[84]	validation-rmse:10.16431
[85]	validation-rmse:10.15908
[86]	validation-rmse:10.15407
[87]	validation-rmse:10.14584
[88]	validation-rmse:10.14154
[89]	validation-rmse:10.12618
[90]	validation-rmse:10.12105
[91]	validation-rmse:10.11662
[92]	validation-rmse:10.11028
[93]	validation-rmse:10.10678
[94]	validation-rmse:10.10163
[95]	validation-rmse:10.09742
[96]	validation-rmse:10.09406
[97]	validation-rmse:10.08392
[98]	validation-rmse:10.08068
[99]	validation-rmse:10.07377
[100]	validation-rmse:10.06956
[101]	validation-rmse:10.06559
[102]	validation-rmse:10.06166
[103]	validation-rmse:10.05883
[104]	validation-rmse:10.05037
[105]	validation-rmse:10.04584
[106]	validation-rmse:10.04181
[107]	validation-rmse:10.03880
[108]	validation-rmse:10.03430
[109]	validation-rmse:10.02084
[110]	validation-rmse:10.01647
[111]	validation-rmse:10.00359
[112]	validation-rmse:10.00112
[113]	validation-rmse:9.98903
[114]	validation-rmse:9.98453
[115]	validation-rmse:9.98132
[116]	validation-rmse:9.97868
[117]	validation-rmse:9.97682
[118]	validation-rmse:9.97377
[119]	validation-rmse:9.96806
[120]	validation-rmse:9.96469
[121]	validation-rmse:9.96286
[122]	validation-rmse:9.95827
[123]	validation-rmse:9.95381
[124]	validation-rmse:9.94911
[125]	validation-rmse:9.94650
[126]	validation-rmse:9.94294
[127]	validation-rmse:9.94150
[128]	validation-rmse:9.93280
[129]	validation-rmse:9.92757
[130]	validation-rmse:9.91545
[131]	validation-rmse:9.91275
[132]	validation-rmse:9.90821
[133]	validation-rmse:9.90541
[134]	validation-rmse:9.90082
[135]	validation-rmse:9.89754
[136]	validation-rmse:9.89204
[137]	validation-rmse:9.88986
[138]	validation-rmse:9.88074
[139]	validation-rmse:9.87131
[140]	validation-rmse:9.86253
[141]	validation-rmse:9.85664
[142]	validation-rmse:9.85505
[143]	validation-rmse:9.85323
[144]	validation-rmse:9.85109
[145]	validation-rmse:9.84446
[146]	validation-rmse:9.83917
[147]	validation-rmse:9.83649
[148]	validation-rmse:9.82385
[149]	validation-rmse:9.82274
[150]	validation-rmse:9.82010
[151]	validation-rmse:9.81747
[152]	validation-rmse:9.81546
[153]	validation-rmse:9.81112
[154]	validation-rmse:9.80802
[155]	validation-rmse:9.80568
[156]	validation-rmse:9.80377
[157]	validation-rmse:9.80277
[158]	validation-rmse:9.79619
[159]	validation-rmse:9.78965
[160]	validation-rmse:9.78782
[161]	validation-rmse:9.78383
[162]	validation-rmse:9.78306
[163]	validation-rmse:9.77911
[164]	validation-rmse:9.77742
[165]	validation-rmse:9.76888
[166]	validation-rmse:9.76351
[167]	validation-rmse:9.76114
[168]	validation-rmse:9.75863
[169]	validation-rmse:9.75503
[170]	validation-rmse:9.75232
[171]	validation-rmse:9.74762
[172]	validation-rmse:9.74648
[173]	validation-rmse:9.74445
[174]	validation-rmse:9.74173
[175]	validation-rmse:9.73291
[176]	validation-rmse:9.72712
[177]	validation-rmse:9.72547
[178]	validation-rmse:9.72186
[179]	validation-rmse:9.72055
[180]	validation-rmse:9.71562
[181]	validation-rmse:9.71259
[182]	validation-rmse:9.70886
[183]	validation-rmse:9.70811
[184]	validation-rmse:9.70456
[185]	validation-rmse:9.70306
[186]	validation-rmse:9.70084
[187]	validation-rmse:9.69904
[188]	validation-rmse:9.69788
[189]	validation-rmse:9.69651
[190]	validation-rmse:9.69369
[191]	validation-rmse:9.69240
[192]	validation-rmse:9.68657
[193]	validation-rmse:9.67816
[194]	validation-rmse:9.67224
[195]	validation-rmse:9.66908
[196]	validation-rmse:9.66774
[197]	validation-rmse:9.66541
[198]	validation-rmse:9.66340
[199]	validation-rmse:9.66208
[200]	validation-rmse:9.66049
[201]	validation-rmse:9.64564
[202]	validation-rmse:9.64442
[203]	validation-rmse:9.63836
[204]	validation-rmse:9.63435
[205]	validation-rmse:9.63088
[206]	validation-rmse:9.62801
[207]	validation-rmse:9.62480
[208]	validation-rmse:9.62322
[209]	validation-rmse:9.62223
[210]	validation-rmse:9.61627
[211]	validation-rmse:9.61451
[212]	validation-rmse:9.61258
[213]	validation-rmse:9.61166
[214]	validation-rmse:9.60878
[215]	validation-rmse:9.60790
[216]	validation-rmse:9.60402
[217]	validation-rmse:9.59707
[218]	validation-rmse:9.59328
[219]	validation-rmse:9.59006
[220]	validation-rmse:9.58850
[221]	validation-rmse:9.58701
[222]	validation-rmse:9.58689
[223]	validation-rmse:9.58603
[224]	validation-rmse:9.58175
[225]	validation-rmse:9.57412
[226]	validation-rmse:9.56519
[227]	validation-rmse:9.56360
[228]	validation-rmse:9.56150
[229]	validation-rmse:9.55995
[230]	validation-rmse:9.55779
[231]	validation-rmse:9.55359
[232]	validation-rmse:9.55289
[233]	validation-rmse:9.55110
[234]	validation-rmse:9.54919
[235]	validation-rmse:9.53874
[236]	validation-rmse:9.53675
[237]	validation-rmse:9.53536
[238]	validation-rmse:9.53415
[239]	validation-rmse:9.52934
[240]	validation-rmse:9.52838
[241]	validation-rmse:9.52624
[242]	validation-rmse:9.52466
[243]	validation-rmse:9.52063
[244]	validation-rmse:9.51997
[245]	validation-rmse:9.51604
[246]	validation-rmse:9.51099
[247]	validation-rmse:9.50983
[248]	validation-rmse:9.50901
[249]	validation-rmse:9.50389
[250]	validation-rmse:9.50205
[251]	validation-rmse:9.50093
[252]	validation-rmse:9.49962
[253]	validation-rmse:9.49470
[254]	validation-rmse:9.49414
[255]	validation-rmse:9.49194
[256]	validation-rmse:9.48993
[257]	validation-rmse:9.48909
[258]	validation-rmse:9.48651
[259]	validation-rmse:9.48494
[260]	validation-rmse:9.47635
[261]	validation-rmse:9.46259
[262]	validation-rmse:9.46117
[263]	validation-rmse:9.45753
[264]	validation-rmse:9.45727
[265]	validation-rmse:9.45593
[266]	validation-rmse:9.45482
[267]	validation-rmse:9.45416
[268]	validation-rmse:9.45294
[269]	validation-rmse:9.45259
[270]	validation-rmse:9.45034
[271]	validation-rmse:9.44907
[272]	validation-rmse:9.44719
[273]	validation-rmse:9.44448
[274]	validation-rmse:9.44041
[275]	validation-rmse:9.43905
[276]	validation-rmse:9.43705
[277]	validation-rmse:9.43617
[278]	validation-rmse:9.42940
[279]	validation-rmse:9.42749
[280]	validation-rmse:9.42591
[281]	validation-rmse:9.42332
[282]	validation-rmse:9.42073
[283]	validation-rmse:9.41927
[284]	validation-rmse:9.41841
[285]	validation-rmse:9.41402
[286]	validation-rmse:9.40901
[287]	validation-rmse:9.40869
[288]	validation-rmse:9.40691
[289]	validation-rmse:9.40651
[290]	validation-rmse:9.40483
[291]	validation-rmse:9.40446
[292]	validation-rmse:9.39936
[293]	validation-rmse:9.39808
[294]	validation-rmse:9.39450
[295]	validation-rmse:9.38732
[296]	validation-rmse:9.38369
[297]	validation-rmse:9.37762
[298]	validation-rmse:9.37540
[299]	validation-rmse:9.37448
[300]	validation-rmse:9.37309
[301]	validation-rmse:9.37180
[302]	validation-rmse:9.36870
[303]	validation-rmse:9.36857
[304]	validation-rmse:9.36613
[305]	validation-rmse:9.36201
[306]	validation-rmse:9.36168
[307]	validation-rmse:9.36066
[308]	validation-rmse:9.36011
[309]	validation-rmse:9.35981
[310]	validation-rmse:9.35874
[311]	validation-rmse:9.35839
[312]	validation-rmse:9.35684
[313]	validation-rmse:9.35618
[314]	validation-rmse:9.35448
[315]	validation-rmse:9.34738
[316]	validation-rmse:9.34683
[317]	validation-rmse:9.34618
[318]	validation-rmse:9.34569
[319]	validation-rmse:9.34250
[320]	validation-rmse:9.34188
[321]	validation-rmse:9.33901
[322]	validation-rmse:9.33725
[323]	validation-rmse:9.33340
[324]	validation-rmse:9.33291
[325]	validation-rmse:9.33085
[326]	validation-rmse:9.33039
[327]	validation-rmse:9.32724
[328]	validation-rmse:9.32689
[329]	validation-rmse:9.32502
[330]	validation-rmse:9.32335
[331]	validation-rmse:9.32213
[332]	validation-rmse:9.31921
[333]	validation-rmse:9.31831
[334]	validation-rmse:9.31731
[335]	validation-rmse:9.31407
[336]	validation-rmse:9.31246
[337]	validation-rmse:9.30766
[338]	validation-rmse:9.30617
[339]	validation-rmse:9.30556
[340]	validation-rmse:9.30370
[341]	validation-rmse:9.30178
[342]	validation-rmse:9.30104
[343]	validation-rmse:9.30009
[344]	validation-rmse:9.29897
[345]	validation-rmse:9.29781
[346]	validation-rmse:9.29589
[347]	validation-rmse:9.29312
[348]	validation-rmse:9.29270
[349]	validation-rmse:9.29116
[350]	validation-rmse:9.29064
[351]	validation-rmse:9.29025
[352]	validation-rmse:9.28905
[353]	validation-rmse:9.28836
[354]	validation-rmse:9.28760
[355]	validation-rmse:9.28720
[356]	validation-rmse:9.28657
[357]	validation-rmse:9.28577
[358]	validation-rmse:9.28435
[359]	validation-rmse:9.28196
[360]	validation-rmse:9.28076
[361]	validation-rmse:9.27814
[362]	validation-rmse:9.27808
[363]	validation-rmse:9.27742
[364]	validation-rmse:9.27534
[365]	validation-rmse:9.27446
[366]	validation-rmse:9.27345
[367]	validation-rmse:9.27218
[368]	validation-rmse:9.27197
[369]	validation-rmse:9.27079
[370]	validation-rmse:9.26959
[371]	validation-rmse:9.26438
[372]	validation-rmse:9.26278
[373]	validation-rmse:9.26085
[374]	validation-rmse:9.25392
[375]	validation-rmse:9.25116
[376]	validation-rmse:9.24810
[377]	validation-rmse:9.24483
[378]	validation-rmse:9.23030
[379]	validation-rmse:9.22685
[380]	validation-rmse:9.22302
[381]	validation-rmse:9.22198
[382]	validation-rmse:9.22152
[383]	validation-rmse:9.21666
[384]	validation-rmse:9.21412
[385]	validation-rmse:9.21195
[386]	validation-rmse:9.21159
[387]	validation-rmse:9.20783
[388]	validation-rmse:9.20624
[389]	validation-rmse:9.20590
[390]	validation-rmse:9.20564
[391]	validation-rmse:9.20523
[392]	validation-rmse:9.20436
[393]	validation-rmse:9.20391
[394]	validation-rmse:9.20344
[395]	validation-rmse:9.20270
[396]	validation-rmse:9.20216
[397]	validation-rmse:9.20170
[398]	validation-rmse:9.20145
[399]	validation-rmse:9.20018
[400]	validation-rmse:9.19422
[401]	validation-rmse:9.19101
[402]	validation-rmse:9.18995
[403]	validation-rmse:9.18981
[404]	validation-rmse:9.18810
[405]	validation-rmse:9.18674
[406]	validation-rmse:9.18122
[407]	validation-rmse:9.18021
[408]	validation-rmse:9.17986
[409]	validation-rmse:9.17969
[410]	validation-rmse:9.17511
[411]	validation-rmse:9.17285
[412]	validation-rmse:9.17223
[413]	validation-rmse:9.17104
[414]	validation-rmse:9.17078
[415]	validation-rmse:9.17020
[416]	validation-rmse:9.16783
[417]	validation-rmse:9.16758
[418]	validation-rmse:9.16525
[419]	validation-rmse:9.16336
[420]	validation-rmse:9.16144
[421]	validation-rmse:9.16156
[422]	validation-rmse:9.15949
[423]	validation-rmse:9.15118
[424]	validation-rmse:9.14923
[425]	validation-rmse:9.14364
[426]	validation-rmse:9.14024
[427]	validation-rmse:9.13972
[428]	validation-rmse:9.13922
[429]	validation-rmse:9.13830
[430]	validation-rmse:9.13727
[431]	validation-rmse:9.13411
[432]	validation-rmse:9.13291
[433]	validation-rmse:9.13279
[434]	validation-rmse:9.13211
[435]	validation-rmse:9.13121
[436]	validation-rmse:9.12902
[437]	validation-rmse:9.12859
[438]	validation-rmse:9.12608
[439]	validation-rmse:9.12449
[440]	validation-rmse:9.12409
[441]	validation-rmse:9.12377
[442]	validation-rmse:9.12249
[443]	validation-rmse:9.12197
[444]	validation-rmse:9.12153
[445]	validation-rmse:9.12051
[446]	validation-rmse:9.11982
[447]	validation-rmse:9.11709
[448]	validation-rmse:9.11645
[449]	validation-rmse:9.11645
[450]	validation-rmse:9.11400
[451]	validation-rmse:9.11230
[452]	validation-rmse:9.11207
[453]	validation-rmse:9.10760
[454]	validation-rmse:9.10129
[455]	validation-rmse:9.09596
[456]	validation-rmse:9.09356
[457]	validation-rmse:9.09129
[458]	validation-rmse:9.09059
[459]	validation-rmse:9.09004
[460]	validation-rmse:9.08813
[461]	validation-rmse:9.08617
[462]	validation-rmse:9.08474
[463]	validation-rmse:9.08454
[464]	validation-rmse:9.08438
[465]	validation-rmse:9.08431
[466]	validation-rmse:9.08328
[467]	validation-rmse:9.08251
[468]	validation-rmse:9.08118
[469]	validation-rmse:9.07985
[470]	validation-rmse:9.07548
[471]	validation-rmse:9.07397
[472]	validation-rmse:9.07342
[473]	validation-rmse:9.07305
[474]	validation-rmse:9.07099
[475]	validation-rmse:9.06921
[476]	validation-rmse:9.06934
[477]	validation-rmse:9.06923
[478]	validation-rmse:9.06727
[479]	validation-rmse:9.06685
[480]	validation-rmse:9.06605
[481]	validation-rmse:9.06507
[482]	validation-rmse:9.06203
[483]	validation-rmse:9.05631
[484]	validation-rmse:9.05384
[485]	validation-rmse:9.05226
[486]	validation-rmse:9.05057
[487]	validation-rmse:9.05012
[488]	validation-rmse:9.04853
[489]	validation-rmse:9.04563
[490]	validation-rmse:9.04173
[491]	validation-rmse:9.03899
[492]	validation-rmse:9.03876
[493]	validation-rmse:9.03876
[494]	validation-rmse:9.03863
[495]	validation-rmse:9.03679
[496]	validation-rmse:9.03583
[497]	validation-rmse:9.03550
[498]	validation-rmse:9.03442
[499]	validation-rmse:9.03379
[500]	validation-rmse:9.03194
[501]	validation-rmse:9.03165
[502]	validation-rmse:9.02976
[503]	validation-rmse:9.02912
[504]	validation-rmse:9.02856
[505]	validation-rmse:9.02835
[506]	validation-rmse:9.02829
[507]	validation-rmse:9.02793
[508]	validation-rmse:9.02740
[509]	validation-rmse:9.02526
[510]	validation-rmse:9.02485
[511]	validation-rmse:9.02164
[512]	validation-rmse:9.02086
[513]	validation-rmse:9.02018
[514]	validation-rmse:9.01954
[515]	validation-rmse:9.01541
[516]	validation-rmse:9.01497
[517]	validation-rmse:9.01160
[518]	validation-rmse:9.01067
[519]	validation-rmse:9.00970
[520]	validation-rmse:9.00964
[521]	validation-rmse:9.00892
[522]	validation-rmse:9.00857
[523]	validation-rmse:9.00741
[524]	validation-rmse:9.00695
[525]	validation-rmse:9.00549
[526]	validation-rmse:9.00396
[527]	validation-rmse:9.00353
[528]	validation-rmse:9.00077
[529]	validation-rmse:8.99942
[530]	validation-rmse:8.99458
[531]	validation-rmse:8.99433
[532]	validation-rmse:8.99371
[533]	validation-rmse:8.99340
[534]	validation-rmse:8.98785
[535]	validation-rmse:8.98713
[536]	validation-rmse:8.98711
[537]	validation-rmse:8.98729
[538]	validation-rmse:8.98710
[539]	validation-rmse:8.98696
[540]	validation-rmse:8.98530
[541]	validation-rmse:8.98212
[542]	validation-rmse:8.98129
[543]	validation-rmse:8.98132
[544]	validation-rmse:8.98043
[545]	validation-rmse:8.97787
[546]	validation-rmse:8.97577
[547]	validation-rmse:8.97520
[548]	validation-rmse:8.97433
[549]	validation-rmse:8.97440
[550]	validation-rmse:8.97394
[551]	validation-rmse:8.96835
[552]	validation-rmse:8.96173
[553]	validation-rmse:8.96121
[554]	validation-rmse:8.96077
[555]	validation-rmse:8.96052
[556]	validation-rmse:8.96020
[557]	validation-rmse:8.95737
[558]	validation-rmse:8.95696
[559]	validation-rmse:8.95559
[560]	validation-rmse:8.95538
[561]	validation-rmse:8.95325
[562]	validation-rmse:8.95293
[563]	validation-rmse:8.95284
[564]	validation-rmse:8.95231
[565]	validation-rmse:8.94954
[566]	validation-rmse:8.94852
[567]	validation-rmse:8.94823
[568]	validation-rmse:8.94814
[569]	validation-rmse:8.94676
[570]	validation-rmse:8.94682
[571]	validation-rmse:8.94669
[572]	validation-rmse:8.94605
[573]	validation-rmse:8.94570
[574]	validation-rmse:8.94447
[575]	validation-rmse:8.94346
[576]	validation-rmse:8.94303
[577]	validation-rmse:8.94185
[578]	validation-rmse:8.93952
[579]	validation-rmse:8.93946
[580]	validation-rmse:8.93893
[581]	validation-rmse:8.93777
[582]	validation-rmse:8.93723
[583]	validation-rmse:8.93697
[584]	validation-rmse:8.93666
[585]	validation-rmse:8.93570
[586]	validation-rmse:8.93549
[587]	validation-rmse:8.93561
[588]	validation-rmse:8.93519
[589]	validation-rmse:8.93425
[590]	validation-rmse:8.93335
[591]	validation-rmse:8.93331
[592]	validation-rmse:8.93343
[593]	validation-rmse:8.93183
[594]	validation-rmse:8.93143
[595]	validation-rmse:8.93121
[596]	validation-rmse:8.93119
[597]	validation-rmse:8.93006
[598]	validation-rmse:8.92941
[599]	validation-rmse:8.92920
[600]	validation-rmse:8.92913
[601]	validation-rmse:8.92859
[602]	validation-rmse:8.92681
[603]	validation-rmse:8.92657
[604]	validation-rmse:8.92503
[605]	validation-rmse:8.92394
[606]	validation-rmse:8.92397
[607]	validation-rmse:8.92131
[608]	validation-rmse:8.91855
[609]	validation-rmse:8.91539
[610]	validation-rmse:8.91333
[611]	validation-rmse:8.90651
[612]	validation-rmse:8.90525
[613]	validation-rmse:8.90340
[614]	validation-rmse:8.90313
[615]	validation-rmse:8.90210
[616]	validation-rmse:8.90060
[617]	validation-rmse:8.89963
[618]	validation-rmse:8.89936
[619]	validation-rmse:8.89894
[620]	validation-rmse:8.89892
[621]	validation-rmse:8.89890
[622]	validation-rmse:8.89881
[623]	validation-rmse:8.89873
[624]	validation-rmse:8.89808
[625]	validation-rmse:8.89793
[626]	validation-rmse:8.89696
[627]	validation-rmse:8.89585
[628]	validation-rmse:8.89581
[629]	validation-rmse:8.89398
[630]	validation-rmse:8.89399
[631]	validation-rmse:8.89356
[632]	validation-rmse:8.89299
[633]	validation-rmse:8.89248
[634]	validation-rmse:8.89236
[635]	validation-rmse:8.89058
[636]	validation-rmse:8.88915
[637]	validation-rmse:8.88905
[638]	validation-rmse:8.88799
[639]	validation-rmse:8.88795
[640]	validation-rmse:8.88763
[641]	validation-rmse:8.88657
[642]	validation-rmse:8.88494
[643]	validation-rmse:8.88221
[644]	validation-rmse:8.88091
[645]	validation-rmse:8.88050
[646]	validation-rmse:8.87821
[647]	validation-rmse:8.87681
[648]	validation-rmse:8.87661
[649]	validation-rmse:8.87605
[650]	validation-rmse:8.87535
[651]	validation-rmse:8.87487
[652]	validation-rmse:8.87356
[653]	validation-rmse:8.87316
[654]	validation-rmse:8.87306
[655]	validation-rmse:8.87297
[656]	validation-rmse:8.87181
[657]	validation-rmse:8.87048
[658]	validation-rmse:8.86960
[659]	validation-rmse:8.86959
[660]	validation-rmse:8.86942
[661]	validation-rmse:8.86790
[662]	validation-rmse:8.86773
[663]	validation-rmse:8.86710
[664]	validation-rmse:8.86221
[665]	validation-rmse:8.86095

[12:19:26] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:17.94401
[2]	validation-rmse:16.62823
[3]	validation-rmse:15.47788
[4]	validation-rmse:14.47074
[5]	validation-rmse:13.64756
[6]	validation-rmse:12.90793
[7]	validation-rmse:12.29004
[8]	validation-rmse:11.75433
[9]	validation-rmse:11.31768
[10]	validation-rmse:10.92692
[11]	validation-rmse:10.60485
[12]	validation-rmse:10.34845
[13]	validation-rmse:10.06016
[14]	validation-rmse:9.87097
[15]	validation-rmse:9.66714
[16]	validation-rmse:9.46035
[17]	validation-rmse:9.34737
[18]	validation-rmse:9.23542
[19]	validation-rmse:9.10172
[20]	validation-rmse:8.98492
[21]	validation-rmse:8.91412
[22]	validation-rmse:8.82775
[23]	validation-rmse:8.77715
[24]	validation-rmse:8.69148
[25]	validation-rmse:8.62969
[26]	validation-rmse:8.55454
[27]	validation-rmse:8.51688
[28]	validation-rmse:8.48599
[29]	validation-rmse:8.45822
[30]	validation-rmse:8.41773
[31]	validation-rmse:8.38347
[32]	validation-rmse:8.35316
[33]	validation-rmse:8.31851
[34]	validation-rmse:8.29828
[35]	validation-rmse:8.26934
[36]	validation-rmse:8.25198
[37]	validation-rmse:8.23152
[38]	validation-rmse:8.20317
[39]	validation-rmse:8.17949
[40]	validation-rmse:8.16450
[41]	validation-rmse:8.14797
[42]	validation-rmse:8.13472
[43]	validation-rmse:8.12545
[44]	validation-rmse:8.09512
[45]	validation-rmse:8.08082
[46]	validation-rmse:8.05932
[47]	validation-rmse:8.04343
[48]	validation-rmse:8.01840
[49]	validation-rmse:8.00331
[50]	validation-rmse:7.99196
[51]	validation-rmse:7.98313
[52]	validation-rmse:7.97127
[53]	validation-rmse:7.96055
[54]	validation-rmse:7.95242
[55]	validation-rmse:7.94374
[56]	validation-rmse:7.92573
[57]	validation-rmse:7.92011
[58]	validation-rmse:7.91334
[59]	validation-rmse:7.90963
[60]	validation-rmse:7.90211
[61]	validation-rmse:7.88939
[62]	validation-rmse:7.87378
[63]	validation-rmse:7.86821
[64]	validation-rmse:7.86533
[65]	validation-rmse:7.85787
[66]	validation-rmse:7.85278
[67]	validation-rmse:7.84810
[68]	validation-rmse:7.84563
[69]	validation-rmse:7.83901
[70]	validation-rmse:7.82961
[71]	validation-rmse:7.82529
[72]	validation-rmse:7.82301
[73]	validation-rmse:7.81948
[74]	validation-rmse:7.81551
[75]	validation-rmse:7.81180
[76]	validation-rmse:7.80874
[77]	validation-rmse:7.80578
[78]	validation-rmse:7.80325
[79]	validation-rmse:7.79892
[80]	validation-rmse:7.79289
[81]	validation-rmse:7.79054
[82]	validation-rmse:7.78849
[83]	validation-rmse:7.78579
[84]	validation-rmse:7.77993
[85]	validation-rmse:7.77786
[86]	validation-rmse:7.77537
[87]	validation-rmse:7.77194
[88]	validation-rmse:7.76935
[89]	validation-rmse:7.76753
[90]	validation-rmse:7.76394
[91]	validation-rmse:7.76066
[92]	validation-rmse:7.75888
[93]	validation-rmse:7.75374
[94]	validation-rmse:7.75230
[95]	validation-rmse:7.74810
[96]	validation-rmse:7.74711
[97]	validation-rmse:7.74583
[98]	validation-rmse:7.74470
[99]	validation-rmse:7.74220
[100]	validation-rmse:7.74108
[101]	validation-rmse:7.73967
[102]	validation-rmse:7.73786
[103]	validation-rmse:7.73648
[104]	validation-rmse:7.73562
[105]	validation-rmse:7.73356
[106]	validation-rmse:7.73266
[107]	validation-rmse:7.73103
[108]	validation-rmse:7.72985
[109]	validation-rmse:7.72892
[110]	validation-rmse:7.72772
[111]	validation-rmse:7.72693
[112]	validation-rmse:7.72573
[113]	validation-rmse:7.72445
[114]	validation-rmse:7.72364
[115]	validation-rmse:7.72295
[116]	validation-rmse:7.72132
[117]	validation-rmse:7.72110
[118]	validation-rmse:7.71982
[119]	validation-rmse:7.71884
[120]	validation-rmse:7.71780
[121]	validation-rmse:7.71700
[122]	validation-rmse:7.71527
[123]	validation-rmse:7.71409
[124]	validation-rmse:7.71249
[125]	validation-rmse:7.71154
[126]	validation-rmse:7.70976
[127]	validation-rmse:7.70845
[128]	validation-rmse:7.70764
[129]	validation-rmse:7.70658
[130]	validation-rmse:7.70572
[131]	validation-rmse:7.70392
[132]	validation-rmse:7.70290
[133]	validation-rmse:7.70152
[134]	validation-rmse:7.70051
[135]	validation-rmse:7.69989
[136]	validation-rmse:7.69901
[137]	validation-rmse:7.69825
[138]	validation-rmse:7.69769
[139]	validation-rmse:7.69695
[140]	validation-rmse:7.69617
[141]	validation-rmse:7.69489
[142]	validation-rmse:7.69422
[143]	validation-rmse:7.69394
[144]	validation-rmse:7.69273
[145]	validation-rmse:7.69140
[146]	validation-rmse:7.68980
[147]	validation-rmse:7.68856
[148]	validation-rmse:7.68812
[149]	validation-rmse:7.68737
[150]	validation-rmse:7.68696
[151]	validation-rmse:7.68615
[152]	validation-rmse:7.68510
[153]	validation-rmse:7.68435
[154]	validation-rmse:7.68356
[155]	validation-rmse:7.68314
[156]	validation-rmse:7.68290
[157]	validation-rmse:7.68206
[158]	validation-rmse:7.68156
[159]	validation-rmse:7.67957
[160]	validation-rmse:7.67889
[161]	validation-rmse:7.67800
[162]	validation-rmse:7.67712
[163]	validation-rmse:7.67662
[164]	validation-rmse:7.67614
[165]	validation-rmse:7.67565
[166]	validation-rmse:7.67468
[167]	validation-rmse:7.67392
[168]	validation-rmse:7.67327
[169]	validation-rmse:7.67266
[170]	validation-rmse:7.67187
[171]	validation-rmse:7.67125
[172]	validation-rmse:7.67024
[173]	validation-rmse:7.66872
[174]	validation-rmse:7.66782
[175]	validation-rmse:7.66723
[176]	validation-rmse:7.66698
[177]	validation-rmse:7.66667
[178]	validation-rmse:7.66570
[179]	validation-rmse:7.66536
[180]	validation-rmse:7.66380
[181]	validation-rmse:7.66311
[182]	validation-rmse:7.66267
[183]	validation-rmse:7.66217
[184]	validation-rmse:7.66114
[185]	validation-rmse:7.66016
[186]	validation-rmse:7.65937
[187]	validation-rmse:7.65872
[188]	validation-rmse:7.65792
[189]	validation-rmse:7.65740
[190]	validation-rmse:7.65637
[191]	validation-rmse:7.65609
[192]	validation-rmse:7.65539
[193]	validation-rmse:7.65458
[194]	validation-rmse:7.65453
[195]	validation-rmse:7.65413
[196]	validation-rmse:7.65360
[197]	validation-rmse:7.65223
[198]	validation-rmse:7.65150
[199]	validation-rmse:7.65018
[200]	validation-rmse:7.64919
[201]	validation-rmse:7.64821
[202]	validation-rmse:7.64716
[203]	validation-rmse:7.64675
[204]	validation-rmse:7.64638
[205]	validation-rmse:7.64511
[206]	validation-rmse:7.64422
[207]	validation-rmse:7.64353
[208]	validation-rmse:7.64301
[209]	validation-rmse:7.64169
[210]	validation-rmse:7.64101
[211]	validation-rmse:7.63974
[212]	validation-rmse:7.63930
[213]	validation-rmse:7.63907
[214]	validation-rmse:7.63740
[215]	validation-rmse:7.63667
[216]	validation-rmse:7.63562
[217]	validation-rmse:7.63489
[218]	validation-rmse:7.63415
[219]	validation-rmse:7.63323
[220]	validation-rmse:7.63260
[221]	validation-rmse:7.63206
[222]	validation-rmse:7.63163
[223]	validation-rmse:7.63084
[224]	validation-rmse:7.63048
[225]	validation-rmse:7.62954
[226]	validation-rmse:7.62867
[227]	validation-rmse:7.62783
[228]	validation-rmse:7.62708
[229]	validation-rmse:7.62650
[230]	validation-rmse:7.62565
[231]	validation-rmse:7.62508
[232]	validation-rmse:7.62472
[233]	validation-rmse:7.62378
[234]	validation-rmse:7.62346
[235]	validation-rmse:7.62269
[236]	validation-rmse:7.62216
[237]	validation-rmse:7.62166
[238]	validation-rmse:7.62129
[239]	validation-rmse:7.62069
[240]	validation-rmse:7.61965
[241]	validation-rmse:7.61922
[242]	validation-rmse:7.61828
[243]	validation-rmse:7.61736
[244]	validation-rmse:7.61643
[245]	validation-rmse:7.61580
[246]	validation-rmse:7.61542
[247]	validation-rmse:7.61449
[248]	validation-rmse:7.61407
[249]	validation-rmse:7.61343
[250]	validation-rmse:7.61295
[251]	validation-rmse:7.61252
[252]	validation-rmse:7.61181
[253]	validation-rmse:7.61114
[254]	validation-rmse:7.61077
[255]	validation-rmse:7.61002
[256]	validation-rmse:7.60927
[257]	validation-rmse:7.60839
[258]	validation-rmse:7.60754
[259]	validation-rmse:7.60664
[260]	validation-rmse:7.60572
[261]	validation-rmse:7.60530
[262]	validation-rmse:7.60419
[263]	validation-rmse:7.60370
[264]	validation-rmse:7.60314
[265]	validation-rmse:7.60239
[266]	validation-rmse:7.60209
[267]	validation-rmse:7.60080
[268]	validation-rmse:7.60052
[269]	validation-rmse:7.59964
[270]	validation-rmse:7.59943
[271]	validation-rmse:7.59899
[272]	validation-rmse:7.59834
[273]	validation-rmse:7.59769
[274]	validation-rmse:7.59739
[275]	validation-rmse:7.59686
[276]	validation-rmse:7.59632
[277]	validation-rmse:7.59582
[278]	validation-rmse:7.59489
[279]	validation-rmse:7.59456
[280]	validation-rmse:7.59421
[281]	validation-rmse:7.59396
[282]	validation-rmse:7.59302
[283]	validation-rmse:7.59260
[284]	validation-rmse:7.59205
[285]	validation-rmse:7.59131
[286]	validation-rmse:7.59099
[287]	validation-rmse:7.59011
[288]	validation-rmse:7.58953
[289]	validation-rmse:7.58887
[290]	validation-rmse:7.58836
[291]	validation-rmse:7.58766
[292]	validation-rmse:7.58691
[293]	validation-rmse:7.58660
[294]	validation-rmse:7.58590
[295]	validation-rmse:7.58549
[296]	validation-rmse:7.58521
[297]	validation-rmse:7.58474
[298]	validation-rmse:7.58404
[299]	validation-rmse:7.58342
[300]	validation-rmse:7.58329
[301]	validation-rmse:7.58281
[302]	validation-rmse:7.58266
[303]	validation-rmse:7.58198
[304]	validation-rmse:7.58154
[305]	validation-rmse:7.58066
[306]	validation-rmse:7.58021
[307]	validation-rmse:7.57998
[308]	validation-rmse:7.57963
[309]	validation-rmse:7.57894
[310]	validation-rmse:7.57804
[311]	validation-rmse:7.57747
[312]	validation-rmse:7.57725
[313]	validation-rmse:7.57647
[314]	validation-rmse:7.57567
[315]	validation-rmse:7.57546
[316]	validation-rmse:7.57497
[317]	validation-rmse:7.57468
[318]	validation-rmse:7.57427
[319]	validation-rmse:7.57397
[320]	validation-rmse:7.57325
[321]	validation-rmse:7.57314
[322]	validation-rmse:7.57257
[323]	validation-rmse:7.57213
[324]	validation-rmse:7.57140
[325]	validation-rmse:7.57115
[326]	validation-rmse:7.57027
[327]	validation-rmse:7.56979
[328]	validation-rmse:7.56901
[329]	validation-rmse:7.56880
[330]	validation-rmse:7.56867
[331]	validation-rmse:7.56835
[332]	validation-rmse:7.56814
[333]	validation-rmse:7.56752
[334]	validation-rmse:7.56715
[335]	validation-rmse:7.56633
[336]	validation-rmse:7.56593
[337]	validation-rmse:7.56503
[338]	validation-rmse:7.56440
[339]	validation-rmse:7.56365
[340]	validation-rmse:7.56277
[341]	validation-rmse:7.56261
[342]	validation-rmse:7.56195
[343]	validation-rmse:7.56171
[344]	validation-rmse:7.56166
[345]	validation-rmse:7.56074
[346]	validation-rmse:7.56040
[347]	validation-rmse:7.56018
[348]	validation-rmse:7.55925
[349]	validation-rmse:7.55867
[350]	validation-rmse:7.55836
[351]	validation-rmse:7.55763
[352]	validation-rmse:7.55681
[353]	validation-rmse:7.55631
[354]	validation-rmse:7.55550
[355]	validation-rmse:7.55501
[356]	validation-rmse:7.55471
[357]	validation-rmse:7.55439
[358]	validation-rmse:7.55406
[359]	validation-rmse:7.55340
[360]	validation-rmse:7.55319
[361]	validation-rmse:7.55224
[362]	validation-rmse:7.55205
[363]	validation-rmse:7.55053
[364]	validation-rmse:7.55028
[365]	validation-rmse:7.54998
[366]	validation-rmse:7.54985
[367]	validation-rmse:7.54937
[368]	validation-rmse:7.54946
[369]	validation-rmse:7.54945
[370]	validation-rmse:7.54896
[371]	validation-rmse:7.54865
[372]	validation-rmse:7.54809
[373]	validation-rmse:7.54756
[374]	validation-rmse:7.54734
[375]	validation-rmse:7.54617
[376]	validation-rmse:7.54570
[377]	validation-rmse:7.54525
[378]	validation-rmse:7.54509
[379]	validation-rmse:7.54473
[380]	validation-rmse:7.54422
[381]	validation-rmse:7.54401
[382]	validation-rmse:7.54375
[383]	validation-rmse:7.54310
[384]	validation-rmse:7.54272
[385]	validation-rmse:7.54206
[386]	validation-rmse:7.54137
[387]	validation-rmse:7.54103
[388]	validation-rmse:7.54077
[389]	validation-rmse:7.54066
[390]	validation-rmse:7.54054
[391]	validation-rmse:7.54032
[392]	validation-rmse:7.53983
[393]	validation-rmse:7.53978
[394]	validation-rmse:7.53913
[395]	validation-rmse:7.53885
[396]	validation-rmse:7.53794
[397]	validation-rmse:7.53763
[398]	validation-rmse:7.53698
[399]	validation-rmse:7.53668
[400]	validation-rmse:7.53653
[401]	validation-rmse:7.53630
[402]	validation-rmse:7.53617
[403]	validation-rmse:7.53622
[404]	validation-rmse:7.53555
[405]	validation-rmse:7.53517
[406]	validation-rmse:7.53497
[407]	validation-rmse:7.53462
[408]	validation-rmse:7.53402
[409]	validation-rmse:7.53276
[410]	validation-rmse:7.53259
[411]	validation-rmse:7.53241
[412]	validation-rmse:7.53201
[413]	validation-rmse:7.53168
[414]	validation-rmse:7.53078
[415]	validation-rmse:7.53025
[416]	validation-rmse:7.53002
[417]	validation-rmse:7.52972
[418]	validation-rmse:7.52965
[419]	validation-rmse:7.52898
[420]	validation-rmse:7.52885
[421]	validation-rmse:7.52861
[422]	validation-rmse:7.52829
[423]	validation-rmse:7.52780
[424]	validation-rmse:7.52709
[425]	validation-rmse:7.52652
[426]	validation-rmse:7.52592
[427]	validation-rmse:7.52546
[428]	validation-rmse:7.52512
[429]	validation-rmse:7.52495
[430]	validation-rmse:7.52437
[431]	validation-rmse:7.52433
[432]	validation-rmse:7.52371
[433]	validation-rmse:7.52302
[434]	validation-rmse:7.52254
[435]	validation-rmse:7.52182
[436]	validation-rmse:7.52131
[437]	validation-rmse:7.52119
[438]	validation-rmse:7.52093
[439]	validation-rmse:7.51997
[440]	validation-rmse:7.51955
[441]	validation-rmse:7.51901
[442]	validation-rmse:7.51878
[443]	validation-rmse:7.51878
[444]	validation-rmse:7.51855
[445]	validation-rmse:7.51790
[446]	validation-rmse:7.51731
[447]	validation-rmse:7.51669
[448]	validation-rmse:7.51634
[449]	validation-rmse:7.51593
[450]	validation-rmse:7.51545
[451]	validation-rmse:7.51474
[452]	validation-rmse:7.51431
[453]	validation-rmse:7.51343
[454]	validation-rmse:7.51270
[455]	validation-rmse:7.51237
[456]	validation-rmse:7.51203
[457]	validation-rmse:7.51176
[458]	validation-rmse:7.51125
[459]	validation-rmse:7.51104
[460]	validation-rmse:7.51049
[461]	validation-rmse:7.50982
[462]	validation-rmse:7.50941
[463]	validation-rmse:7.50890
[464]	validation-rmse:7.50846
[465]	validation-rmse:7.50779
[466]	validation-rmse:7.50704
[467]	validation-rmse:7.50699
[468]	validation-rmse:7.50598
[469]	validation-rmse:7.50492
[470]	validation-rmse:7.50439
[471]	validation-rmse:7.50380
[472]	validation-rmse:7.50360
[473]	validation-rmse:7.50310
[474]	validation-rmse:7.50277
[475]	validation-rmse:7.50236
[476]	validation-rmse:7.50193
[477]	validation-rmse:7.50147
[478]	validation-rmse:7.50117
[479]	validation-rmse:7.50082
[480]	validation-rmse:7.50055
[481]	validation-rmse:7.50004
[482]	validation-rmse:7.49955
[483]	validation-rmse:7.49911
[484]	validation-rmse:7.49877
[485]	validation-rmse:7.49841
[486]	validation-rmse:7.49791
[487]	validation-rmse:7.49716
[488]	validation-rmse:7.49673
[489]	validation-rmse:7.49659
[490]	validation-rmse:7.49606
[491]	validation-rmse:7.49522
[492]	validation-rmse:7.49502
[493]	validation-rmse:7.49461
[494]	validation-rmse:7.49462
[495]	validation-rmse:7.49410
[496]	validation-rmse:7.49357
[497]	validation-rmse:7.49296
[498]	validation-rmse:7.49231
[499]	validation-rmse:7.49220
[500]	validation-rmse:7.49196
[501]	validation-rmse:7.49171
[502]	validation-rmse:7.49152
[503]	validation-rmse:7.49040
[504]	validation-rmse:7.48983
[505]	validation-rmse:7.48949
[506]	validation-rmse:7.48921
[507]	validation-rmse:7.48904
[508]	validation-rmse:7.48880
[509]	validation-rmse:7.48841
[510]	validation-rmse:7.48835
[511]	validation-rmse:7.48804
[512]	validation-rmse:7.48755
[513]	validation-rmse:7.48726
[514]	validation-rmse:7.48683
[515]	validation-rmse:7.48634
[516]	validation-rmse:7.48618
[517]	validation-rmse:7.48570
[518]	validation-rmse:7.48520
[519]	validation-rmse:7.48506
[520]	validation-rmse:7.48483
[521]	validation-rmse:7.48455
[522]	validation-rmse:7.48446
[523]	validation-rmse:7.48413
[524]	validation-rmse:7.48399
[525]	validation-rmse:7.48366
[526]	validation-rmse:7.48345
[527]	validation-rmse:7.48314
[528]	validation-rmse:7.48256
[529]	validation-rmse:7.48220
[530]	validation-rmse:7.48199
[531]	validation-rmse:7.48212
[532]	validation-rmse:7.48180
[533]	validation-rmse:7.48145
[534]	validation-rmse:7.48099
[535]	validation-rmse:7.48021
[536]	validation-rmse:7.47910
[537]	validation-rmse:7.47846
[538]	validation-rmse:7.47801
[539]	validation-rmse:7.47745
[540]	validation-rmse:7.47713
[541]	validation-rmse:7.47670
[542]	validation-rmse:7.47623
[543]	validation-rmse:7.47580
[544]	validation-rmse:7.47537
[545]	validation-rmse:7.47532
[546]	validation-rmse:7.47515
[547]	validation-rmse:7.47485
[548]	validation-rmse:7.47463
[549]	validation-rmse:7.47450
[550]	validation-rmse:7.47435
[551]	validation-rmse:7.47404
[552]	validation-rmse:7.47377
[553]	validation-rmse:7.47359
[554]	validation-rmse:7.47284
[555]	validation-rmse:7.47223
[556]	validation-rmse:7.47191
[557]	validation-rmse:7.47202
[558]	validation-rmse:7.47174
[559]	validation-rmse:7.47086
[560]	validation-rmse:7.47062
[561]	validation-rmse:7.47032
[562]	validation-rmse:7.46986
[563]	validation-rmse:7.46975
[564]	validation-rmse:7.46969
[565]	validation-rmse:7.46932
[566]	validation-rmse:7.46937
[567]	validation-rmse:7.46930
[568]	validation-rmse:7.46893
[569]	validation-rmse:7.46858
[570]	validation-rmse:7.46817
[571]	validation-rmse:7.46801
[572]	validation-rmse:7.46800
[573]	validation-rmse:7.46780
[574]	validation-rmse:7.46726
[575]	validation-rmse:7.46713
[576]	validation-rmse:7.46708
[577]	validation-rmse:7.46696
[578]	validation-rmse:7.46640
[579]	validation-rmse:7.46582
[580]	validation-rmse:7.46528
[581]	validation-rmse:7.46531
[582]	validation-rmse:7.46493
[583]	validation-rmse:7.46441
[584]	validation-rmse:7.46433
[585]	validation-rmse:7.46394
[586]	validation-rmse:7.46381
[587]	validation-rmse:7.46310
[588]	validation-rmse:7.46296
[589]	validation-rmse:7.46264
[590]	validation-rmse:7.46233
[591]	validation-rmse:7.46192
[592]	validation-rmse:7.46158
[593]	validation-rmse:7.46105
[594]	validation-rmse:7.46101
[595]	validation-rmse:7.46093
[596]	validation-rmse:7.46028
[597]	validation-rmse:7.45990
[598]	validation-rmse:7.45961
[599]	validation-rmse:7.45957
[600]	validation-rmse:7.45939
[601]	validation-rmse:7.45908
[602]	validation-rmse:7.45886
[603]	validation-rmse:7.45850
[604]	validation-rmse:7.45795
[605]	validation-rmse:7.45782
[606]	validation-rmse:7.45748
[607]	validation-rmse:7.45716
[608]	validation-rmse:7.45641
[609]	validation-rmse:7.45596
[610]	validation-rmse:7.45554
[611]	validation-rmse:7.45536
[612]	validation-rmse:7.45536
[613]	validation-rmse:7.45496
[614]	validation-rmse:7.45483
[615]	validation-rmse:7.45417
[616]	validation-rmse:7.45383
[617]	validation-rmse:7.45377
[618]	validation-rmse:7.45349
[619]	validation-rmse:7.45338
[620]	validation-rmse:7.45299
[621]	validation-rmse:7.45265
[622]	validation-rmse:7.45229
[623]	validation-rmse:7.45205
[624]	validation-rmse:7.45174
[625]	validation-rmse:7.45154
[626]	validation-rmse:7.45100
[627]	validation-rmse:7.45080
[628]	validation-rmse:7.45072
[629]	validation-rmse:7.45073
[630]	validation-rmse:7.45040
[631]	validation-rmse:7.45028
[632]	validation-rmse:7.44995
[633]	validation-rmse:7.44961
[634]	validation-rmse:7.44951
[635]	validation-rmse:7.44925
[636]	validation-rmse:7.44883
[637]	validation-rmse:7.44849
[638]	validation-rmse:7.44824
[639]	validation-rmse:7.44746
[640]	validation-rmse:7.44754
[641]	validation-rmse:7.44708
[642]	validation-rmse:7.44691
[643]	validation-rmse:7.44646
[644]	validation-rmse:7.44616
[645]	validation-rmse:7.44557
[646]	validation-rmse:7.44520
[647]	validation-rmse:7.44480
[648]	validation-rmse:7.44431
[649]	validation-rmse:7.44394
[650]	validation-rmse:7.44372
[651]	validation-rmse:7.44360
[652]	validation-rmse:7.44287
[653]	validation-rmse:7.44237
[654]	validation-rmse:7.44200
[655]	validation-rmse:7.44177
[656]	validation-rmse:7.44123
[657]	validation-rmse:7.44077
[658]	validation-rmse:7.44031
[659]	validation-rmse:7.44025
[660]	validation-rmse:7.43980
[661]	validation-rmse:7.43905
[662]	validation-rmse:7.43882
[663]	validation-rmse:7.43812
[664]	validation-rmse:7.43760
[665]	validation-rmse:7.43743
[666]	validation-rmse:7.43706
[667]	validation-rmse:7.43650
[668]	validation-rmse:7.43623
[669]	validation-rmse:7.43575

[12:25:12] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:14.87415
[2]	validation-rmse:12.94915
[3]	validation-rmse:11.63705
[4]	validation-rmse:10.69650
[5]	validation-rmse:9.98838
[6]	validation-rmse:9.58181
[7]	validation-rmse:9.26398
[8]	validation-rmse:8.95124
[9]	validation-rmse:8.76609
[10]	validation-rmse:8.53712
[11]	validation-rmse:8.41606
[12]	validation-rmse:8.31065
[13]	validation-rmse:8.23590
[14]	validation-rmse:8.15944
[15]	validation-rmse:8.08746
[16]	validation-rmse:8.02562
[17]	validation-rmse:7.98077
[18]	validation-rmse:7.91922
[19]	validation-rmse:7.90067
[20]	validation-rmse:7.88462
[21]	validation-rmse:7.83833
[22]	validation-rmse:7.79822
[23]	validation-rmse:7.77267
[24]	validation-rmse:7.75379
[25]	validation-rmse:7.74136
[26]	validation-rmse:7.72042
[27]	validation-rmse:7.69726
[28]	validation-rmse:7.67384
[29]	validation-rmse:7.65895
[30]	validation-rmse:7.65035
[31]	validation-rmse:7.64510
[32]	validation-rmse:7.63454
[33]	validation-rmse:7.62225
[34]	validation-rmse:7.60748
[35]	validation-rmse:7.60709
[36]	validation-rmse:7.60090
[37]	validation-rmse:7.59941
[38]	validation-rmse:7.59284
[39]	validation-rmse:7.58741
[40]	validation-rmse:7.58622
[41]	validation-rmse:7.58341
[42]	validation-rmse:7.58124
[43]	validation-rmse:7.57480
[44]	validation-rmse:7.57497
[45]	validation-rmse:7.57556
[46]	validation-rmse:7.57358
[47]	validation-rmse:7.56998
[48]	validation-rmse:7.56823
[49]	validation-rmse:7.56776
[50]	validation-rmse:7.56663
[51]	validation-rmse:7.56395
[52]	validation-rmse:7.56242
[53]	validation-rmse:7.56116
[54]	validation-rmse:7.56056
[55]	validation-rmse:7.56010
[56]	validation-rmse:7.56023
[57]	validation-rmse:7.55920
[58]	validation-rmse:7.55874
[59]	validation-rmse:7.55901
[60]	validation-rmse:7.55718
[61]	validation-rmse:7.55710
[62]	validation-rmse:7.55737
[63]	validation-rmse:7.55661
[64]	validation-rmse:7.55570
[65]	validation-rmse:7.55554
[66]	validation-rmse:7.55313
[67]	validation-rmse:7.55320
[68]	validation-rmse:7.55295
[69]	validation-rmse:7.55266
[70]	validation-rmse:7.55228
[71]	validation-rmse:7.55188
[72]	validation-rmse:7.55196
[73]	validation-rmse:7.55169
[74]	validation-rmse:7.55185
[75]	validation-rmse:7.55157
[76]	validation-rmse:7.55119
[77]	validation-rmse:7.55049
[78]	validation-rmse:7.55012
[79]	validation-rmse:7.55001
[80]	validation-rmse:7.55004
[81]	validation-rmse:7.55003
[82]	validation-rmse:7.55000
[83]	validation-rmse:7.54961
[84]	validation-rmse:7.54942
[85]	validation-rmse:7.54883
[86]	validation-rmse:7.54833
[87]	validation-rmse:7.54826
[88]	validation-rmse:7.54836
[89]	validation-rmse:7.54814
[90]	validation-rmse:7.54793
[91]	validation-rmse:7.54744
[92]	validation-rmse:7.54695
[93]	validation-rmse:7.54646
[94]	validation-rmse:7.54639
[95]	validation-rmse:7.54610
[96]	validation-rmse:7.54566
[97]	validation-rmse:7.54525
[98]	validation-rmse:7.54489
[99]	validation-rmse:7.54495
[100]	validation-rmse:7.54460
[101]	validation-rmse:7.54447
[102]	validation-rmse:7.54397
[103]	validation-rmse:7.54345
[104]	validation-rmse:7.54317
[105]	validation-rmse:7.54253
[106]	validation-rmse:7.54259
[107]	validation-rmse:7.54241
[108]	validation-rmse:7.54228
[109]	validation-rmse:7.54219
[110]	validation-rmse:7.54217
[111]	validation-rmse:7.54233
[112]	validation-rmse:7.54223
[113]	validation-rmse:7.54232
[114]	validation-rmse:7.54188
[115]	validation-rmse:7.54186
[116]	validation-rmse:7.54182
[117]	validation-rmse:7.54174
[118]	validation-rmse:7.54167
[119]	validation-rmse:7.54164
[120]	validation-rmse:7.54159
[121]	validation-rmse:7.54132
[122]	validation-rmse:7.54120
[123]	validation-rmse:7.54109
[124]	validation-rmse:7.54111
[125]	validation-rmse:7.54080
[126]	validation-rmse:7.54058
[127]	validation-rmse:7.54031
[128]	validation-rmse:7.54028
[129]	validation-rmse:7.54022
[130]	validation-rmse:7.54029
[131]	validation-rmse:7.54020
[132]	validation-rmse:7.54015
[133]	validation-rmse:7.54008
[134]	validation-rmse:7.54007
[135]	validation-rmse:7.53999
[136]	validation-rmse:7.53995
[137]	validation-rmse:7.53991
[138]	validation-rmse:7.53984
[139]	validation-rmse:7.53975
[140]	validation-rmse:7.53971
[141]	validation-rmse:7.53968
[142]	validation-rmse:7.53970
[143]	validation-rmse:7.53969
[144]	validation-rmse:7.53954
[145]	validation-rmse:7.53953
[146]	validation-rmse:7.53942
[147]	validation-rmse:7.53943
[148]	validation-rmse:7.53942
[149]	validation-rmse:7.53933
[150]	validation-rmse:7.53922
[151]	validation-rmse:7.53917
[152]	validation-rmse:7.53916
[153]	validation-rmse:7.53915
[154]	validation-rmse:7.53907
[155]	validation-rmse:7.53903
[156]	validation-rmse:7.53899
[157]	validation-rmse:7.53899
[158]	validation-rmse:7.53902
[159]	validation-rmse:7.53900
[160]	validation-rmse:7.53897
[161]	validation-rmse:7.53897
[162]	validation-rmse:7.53893
[163]	validation-rmse:7.53889
[164]	validation-rmse:7.53877
[165]	validation-rmse:7.53879
[166]	validation-rmse:7.53876
[167]	validation-rmse:7.53875
[168]	validation-rmse:7.53873
[169]	validation-rmse:7.53868
[170]	validation-rmse:7.53864
[171]	validation-rmse:7.53864
[172]	validation-rmse:7.53858
[173]	validation-rmse:7.53856
[174]	validation-rmse:7.53853
[175]	validation-rmse:7.53851
[176]	validation-rmse:7.53851
[177]	validation-rmse:7.53849
[178]	validation-rmse:7.53846
[179]	validation-rmse:7.53848
[180]	validation-rmse:7.53842
[181]	validation-rmse:7.53839
[182]	validation-rmse:7.53837
[183]	validation-rmse:7.53833
[184]	validation-rmse:7.53831
[185]	validation-rmse:7.53828
[186]	validation-rmse:7.53828
[187]	validation-rmse:7.53826
[188]	validation-rmse:7.53825
[189]	validation-rmse:7.53825
[190]	validation-rmse:7.53827
[191]	validation-rmse:7.53824
[192]	validation-rmse:7.53818
[193]	validation-rmse:7.53817
[194]	validation-rmse:7.53816
[195]	validation-rmse:7.53813
[196]	validation-rmse:7.53811
[197]	validation-rmse:7.53810
[198]	validation-rmse:7.53809
[199]	validation-rmse:7.53809
[200]	validation-rmse:7.53807
[201]	validation-rmse:7.53806
[202]	validation-rmse:7.53803
[203]	validation-rmse:7.53802
[204]	validation-rmse:7.53802
[205]	validation-rmse:7.53799
[206]	validation-rmse:7.53798
[207]	validation-rmse:7.53797
[208]	validation-rmse:7.53795
[209]	validation-rmse:7.53794
[210]	validation-rmse:7.53795
[211]	validation-rmse:7.53794
[212]	validation-rmse:7.53794
[213]	validation-rmse:7.53792
[214]	validation-rmse:7.53792
[215]	validation-rmse:7.53792
[216]	validation-rmse:7.53789
[217]	validation-rmse:7.53790
[218]	validation-rmse:7.53789
[219]	validation-rmse:7.53788
[220]	validation-rmse:7.53788
[221]	validation-rmse:7.53787
[222]	validation-rmse:7.53787
[223]	validation-rmse:7.53786
[224]	validation-rmse:7.53786
[225]	validation-rmse:7.53784
[226]	validation-rmse:7.53784
[227]	validation-rmse:7.53783
[228]	validation-rmse:7.53781
[229]	validation-rmse:7.53779
[230]	validation-rmse:7.53777
[231]	validation-rmse:7.53778
[232]	validation-rmse:7.53778
[233]	validation-rmse:7.53777
[234]	validation-rmse:7.53772
[235]	validation-rmse:7.53771
[236]	validation-rmse:7.53770
[237]	validation-rmse:7.53768
[238]	validation-rmse:7.53769
[239]	validation-rmse:7.53768
[240]	validation-rmse:7.53767
[241]	validation-rmse:7.53766
[242]	validation-rmse:7.53765
[243]	validation-rmse:7.53764
[244]	validation-rmse:7.53765
[245]	validation-rmse:7.53765
[246]	validation-rmse:7.53765
[247]	validation-rmse:7.53764
[248]	validation-rmse:7.53763
[249]	validation-rmse:7.53763
[250]	validation-rmse:7.53763
[251]	validation-rmse:7.53764
[252]	validation-rmse:7.53764
[253]	validation-rmse:7.53764
[254]	validation-rmse:7.53761
[255]	validation-rmse:7.53761
[256]	validation-rmse:7.53760
[257]	validation-rmse:7.53759
[258]	validation-rmse:7.53759
[259]	validation-rmse:7.53759
[260]	validation-rmse:7.53760
[261]	validation-rmse:7.53759
[262]	validation-rmse:7.53759
[263]	validation-rmse:7.53760
[264]	validation-rmse:7.53759
[265]	validation-rmse:7.53760
[266]	validation-rmse:7.53758
[267]	validation-rmse:7.53758
[268]	validation-rmse:7.53757
[269]	validation-rmse:7.53755
[270]	validation-rmse:7.53754
[271]	validation-rmse:7.53755
[272]	validation-rmse:7.53753
[273]	validation-rmse:7.53753
[274]	validation-rmse:7.53752
[275]	validation-rmse:7.53752
[276]	validation-rmse:7.53753
[277]	validation-rmse:7.53751
[278]	validation-rmse:7.53751
[279]	validation-rmse:7.53751
[280]	validation-rmse:7.53749
[281]	validation-rmse:7.53749
[282]	validation-rmse:7.53749
[283]	validation-rmse:7.53749
[284]	validation-rmse:7.53748
[285]	validation-rmse:7.53747
[286]	validation-rmse:7.53746
[287]	validation-rmse:7.53748
[288]	validation-rmse:7.53749
[289]	validation-rmse:7.53749
[290]	validation-rmse:7.53749
[291]	validation-rmse:7.53749
[292]	validation-rmse:7.53749
[293]	validation-rmse:7.53747
[294]	validation-rmse:7.53746
[295]	validation-rmse:7.53746
[296]	validation-rmse:7.53745
[297]	validation-rmse:7.53745
[298]	validation-rmse:7.53744
[299]	validation-rmse:7.53744
[300]	validation-rmse:7.53744
[301]	validation-rmse:7.53744
[302]	validation-rmse:7.53743
[303]	validation-rmse:7.53745
[304]	validation-rmse:7.53744
[305]	validation-rmse:7.53743
[306]	validation-rmse:7.53743
[307]	validation-rmse:7.53741
[308]	validation-rmse:7.53741
[309]	validation-rmse:7.53741
[310]	validation-rmse:7.53743
[311]	validation-rmse:7.53742
[312]	validation-rmse:7.53742
[313]	validation-rmse:7.53742
[314]	validation-rmse:7.53742
[315]	validation-rmse:7.53742
[316]	validation-rmse:7.53742
[317]	validation-rmse:7.53741
[318]	validation-rmse:7.53741
[319]	validation-rmse:7.53741
[320]	validation-rmse:7.53740
[321]	validation-rmse:7.53741
[322]	validation-rmse:7.53741
[323]	validation-rmse:7.53741
[324]	validation-rmse:7.53741
[325]	validation-rmse:7.53741
[326]	validation-rmse:7.53740
[327]	validation-rmse:7.53740
[328]	validation-rmse:7.53740
[329]	validation-rmse:7.53739
[330]	validation-rmse:7.53738
[331]	validation-rmse:7.53738
[332]	validation-rmse:7.53738
[333]	validation-rmse:7.53738
[334]	validation-rmse:7.53738
[335]	validation-rmse:7.53738
[336]	validation-rmse:7.53738
[337]	validation-rmse:7.53737
[338]	validation-rmse:7.53737
[339]	validation-rmse:7.53737
[340]	validation-rmse:7.53736
[341]	validation-rmse:7.53737
[342]	validation-rmse:7.53736
[343]	validation-rmse:7.53736
[344]	validation-rmse:7.53736
[345]	validation-rmse:7.53736
[346]	validation-rmse:7.53735
[347]	validation-rmse:7.53735
[348]	validation-rmse:7.53736
[349]	validation-rmse:7.53736
[350]	validation-rmse:7.53736
[351]	validation-rmse:7.53736
[352]	validation-rmse:7.53736
[353]	validation-rmse:7.53735
[354]	validation-rmse:7.53735
[355]	validation-rmse:7.53736
[356]	validation-rmse:7.53735
[357]	validation-rmse:7.53736
[358]	validation-rmse:7.53736
[359]	validation-rmse:7.53735
[360]	validation-rmse:7.53736
[361]	validation-rmse:7.53737
[362]	validation-rmse:7.53737
[363]	validation-rmse:7.53737
[364]	validation-rmse:7.53736
[365]	validation-rmse:7.53737
[366]	validation-rmse:7.53737
[367]	validation-rmse:7.53736
[368]	validation-rmse:7.53737
[369]	validation-rmse:7.53737
[370]	validation-rmse:7.53737
[371]	validation-rmse:7.53736
[372]	validation-rmse:7.53735
[373]	validation-rmse:7.53735
[374]	validation-rmse:7.53735
[375]	validation-rmse:7.53735
[376]	validation-rmse:7.53735
[377]	validation-rmse:7.53734
[378]	validation-rmse:7.53733
[379]	validation-rmse:7.53734
[380]	validation-rmse:7.53734
[381]	validation-rmse:7.53733
[382]	validation-rmse:7.53733
[383]	validation-rmse:7.53735
[384]	validation-rmse:7.53734
[385]	validation-rmse:7.53734
[386]	validation-rmse:7.53734
[387]	validation-rmse:7.53735
[388]	validation-rmse:7.53734
[389]	validation-rmse:7.53735
[390]	validation-rmse:7.53735
[391]	validation-rmse:7.53736
[392]	validation-rmse:7.53735
[393]	validation-rmse:7.53736
[394]	validation-rmse:7.53736
[395]	validation-rmse:7.53736
[396]	validation-rmse:7.53735
[397]	validation-rmse:7.53735
[398]	validation-rmse:7.53735
[399]	validation-rmse:7.53735
[400]	validation-rmse:7.53735
[401]	validation-rmse:7.53735
[402]	validation-rmse:7.53736
[403]	validation-rmse:7.53737
[404]	validation-rmse:7.53738
[405]	validation-rmse:7.53737
[406]	validation-rmse:7.53739
[407]	validation-rmse:7.53739
[408]	validation-rmse:7.53738
[409]	validation-rmse:7.53739
[410]	validation-rmse:7.53740
[411]	validation-rmse:7.53755
[412]	validation-rmse:7.53762
[413]	validation-rmse:7.53766
[414]	validation-rmse:7.53771
[415]	validation-rmse:7.53775
[416]	validation-rmse:7.53779
[417]	validation-rmse:7.53778
[418]	validation-rmse:7.53778
[419]	validation-rmse:7.53778
[420]	validation-rmse:7.53778
[421]	validation-rmse:7.53778
[422]	validation-rmse:7.53778
[423]	validation-rmse:7.53778
[424]	validation-rmse:7.53778
[425]	validation-rmse:7.53778
[426]	validation-rmse:7.53778
[427]	validation-rmse:7.53778
[428]	validation-rmse:7.53778
[429]	validation-rmse:7.53778
[430]	validation-rmse:7.53778
[431]	validation-rmse:7.53778
[432]	validation-rmse:7.53778
[0]	validation-rmse:19.26071
 20%|██        | 10/50 [37:46<2:21:53, 212.84s/trial, best loss: 7.14819276917268]

[12:27:42] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:17.62319
[2]	validation-rmse:16.21507
[3]	validation-rmse:15.03937
[4]	validation-rmse:14.07084
[5]	validation-rmse:13.25175
[6]	validation-rmse:12.56863
[7]	validation-rmse:11.99866
[8]	validation-rmse:11.54601
[9]	validation-rmse:11.15609
[10]	validation-rmse:10.85090
[11]	validation-rmse:10.58658
[12]	validation-rmse:10.38194
[13]	validation-rmse:10.16324
[14]	validation-rmse:10.01676
[15]	validation-rmse:9.89064
[16]	validation-rmse:9.78908
[17]	validation-rmse:9.69620
[18]	validation-rmse:9.62348
[19]	validation-rmse:9.52040
[20]	validation-rmse:9.43995
[21]	validation-rmse:9.39163
[22]	validation-rmse:9.34738
[23]	validation-rmse:9.31630
[24]	validation-rmse:9.28286
[25]	validation-rmse:9.23315
[26]	validation-rmse:9.20739
[27]	validation-rmse:9.18282
[28]	validation-rmse:9.15890
[29]	validation-rmse:9.12451
[30]	validation-rmse:9.10940
[31]	validation-rmse:9.09354
[32]	validation-rmse:9.07744
[33]	validation-rmse:9.06216
[34]	validation-rmse:9.04561
[35]	validation-rmse:9.03214
[36]	validation-rmse:9.01175
[37]	validation-rmse:9.00113
[38]	validation-rmse:8.99192
[39]	validation-rmse:8.98316
[40]	validation-rmse:8.97403
[41]	validation-rmse:8.96656
[42]	validation-rmse:8.95706
[43]	validation-rmse:8.95003
[44]	validation-rmse:8.94126
[45]	validation-rmse:8.93015
[46]	validation-rmse:8.92213
[47]	validation-rmse:8.91195
[48]	validation-rmse:8.89797
[49]	validation-rmse:8.89069
[50]	validation-rmse:8.87681
[51]	validation-rmse:8.86456
[52]	validation-rmse:8.85030
[53]	validation-rmse:8.83975
[54]	validation-rmse:8.83010
[55]	validation-rmse:8.81886
[56]	validation-rmse:8.80873
[57]	validation-rmse:8.80047
[58]	validation-rmse:8.79130
[59]	validation-rmse:8.78376
[60]	validation-rmse:8.77322
[61]	validation-rmse:8.76440
[62]	validation-rmse:8.75792
[63]	validation-rmse:8.74934
[64]	validation-rmse:8.73911
[65]	validation-rmse:8.73205
[66]	validation-rmse:8.72350
[67]	validation-rmse:8.71465
[68]	validation-rmse:8.70442
[69]	validation-rmse:8.69714
[70]	validation-rmse:8.68914
[71]	validation-rmse:8.68137
[72]	validation-rmse:8.67317
[73]	validation-rmse:8.66567
[74]	validation-rmse:8.65836
[75]	validation-rmse:8.65183
[76]	validation-rmse:8.64204
[77]	validation-rmse:8.63562
[78]	validation-rmse:8.62773
[79]	validation-rmse:8.62197
[80]	validation-rmse:8.61562
[81]	validation-rmse:8.60979
[82]	validation-rmse:8.60227
[83]	validation-rmse:8.59592
[84]	validation-rmse:8.58742
[85]	validation-rmse:8.58131
[86]	validation-rmse:8.57495
[87]	validation-rmse:8.56817
[88]	validation-rmse:8.56019
[89]	validation-rmse:8.55343
[90]	validation-rmse:8.54728
[91]	validation-rmse:8.54210
[92]	validation-rmse:8.53602
[93]	validation-rmse:8.53124
[94]	validation-rmse:8.52586
[95]	validation-rmse:8.52050
[96]	validation-rmse:8.51487
[97]	validation-rmse:8.50716
[98]	validation-rmse:8.50246
[99]	validation-rmse:8.49632
[100]	validation-rmse:8.49090
[101]	validation-rmse:8.48458
[102]	validation-rmse:8.47714
[103]	validation-rmse:8.47061
[104]	validation-rmse:8.46396
[105]	validation-rmse:8.46007
[106]	validation-rmse:8.45531
[107]	validation-rmse:8.45157
[108]	validation-rmse:8.44747
[109]	validation-rmse:8.44281
[110]	validation-rmse:8.43883
[111]	validation-rmse:8.43514
[112]	validation-rmse:8.42968
[113]	validation-rmse:8.42632
[114]	validation-rmse:8.42270
[115]	validation-rmse:8.42002
[116]	validation-rmse:8.41574
[117]	validation-rmse:8.41021
[118]	validation-rmse:8.40403
[119]	validation-rmse:8.39880
[120]	validation-rmse:8.39492
[121]	validation-rmse:8.39063
[122]	validation-rmse:8.38723
[123]	validation-rmse:8.38274
[124]	validation-rmse:8.37985
[125]	validation-rmse:8.37562
[126]	validation-rmse:8.37129
[127]	validation-rmse:8.36834
[128]	validation-rmse:8.36434
[129]	validation-rmse:8.36001
[130]	validation-rmse:8.35630
[131]	validation-rmse:8.35326
[132]	validation-rmse:8.35059
[133]	validation-rmse:8.34570
[134]	validation-rmse:8.34081
[135]	validation-rmse:8.33852
[136]	validation-rmse:8.33575
[137]	validation-rmse:8.33254
[138]	validation-rmse:8.32431
[139]	validation-rmse:8.32092
[140]	validation-rmse:8.31747
[141]	validation-rmse:8.31423
[142]	validation-rmse:8.31141
[143]	validation-rmse:8.30849
[144]	validation-rmse:8.30486
[145]	validation-rmse:8.30257
[146]	validation-rmse:8.29959
[147]	validation-rmse:8.29733
[148]	validation-rmse:8.29162
[149]	validation-rmse:8.28888
[150]	validation-rmse:8.28587
[151]	validation-rmse:8.28104
[152]	validation-rmse:8.27681
[153]	validation-rmse:8.27176
[154]	validation-rmse:8.26745
[155]	validation-rmse:8.26383
[156]	validation-rmse:8.26001
[157]	validation-rmse:8.25632
[158]	validation-rmse:8.25298
[159]	validation-rmse:8.24891
[160]	validation-rmse:8.24548
[161]	validation-rmse:8.24180
[162]	validation-rmse:8.23810
[163]	validation-rmse:8.23529
[164]	validation-rmse:8.23144
[165]	validation-rmse:8.22915
[166]	validation-rmse:8.22657
[167]	validation-rmse:8.22338
[168]	validation-rmse:8.22010
[169]	validation-rmse:8.21695
[170]	validation-rmse:8.21451
[171]	validation-rmse:8.21226
[172]	validation-rmse:8.20889
[173]	validation-rmse:8.20639
[174]	validation-rmse:8.20386
[175]	validation-rmse:8.20046
[176]	validation-rmse:8.19780
[177]	validation-rmse:8.19530
[178]	validation-rmse:8.19076
[179]	validation-rmse:8.18877
[180]	validation-rmse:8.18622
[181]	validation-rmse:8.18313
[182]	validation-rmse:8.17970
[183]	validation-rmse:8.17669
[184]	validation-rmse:8.17354
[185]	validation-rmse:8.17064
[186]	validation-rmse:8.16754
[187]	validation-rmse:8.16454
[188]	validation-rmse:8.16208
[189]	validation-rmse:8.15906
[190]	validation-rmse:8.15700
[191]	validation-rmse:8.15344
[192]	validation-rmse:8.15027
[193]	validation-rmse:8.14731
[194]	validation-rmse:8.14414
[195]	validation-rmse:8.14180
[196]	validation-rmse:8.13901
[197]	validation-rmse:8.13623
[198]	validation-rmse:8.13258
[199]	validation-rmse:8.13016
[200]	validation-rmse:8.12776
[201]	validation-rmse:8.12525
[202]	validation-rmse:8.12248
[203]	validation-rmse:8.11972
[204]	validation-rmse:8.11649
[205]	validation-rmse:8.11400
[206]	validation-rmse:8.11115
[207]	validation-rmse:8.10841
[208]	validation-rmse:8.10608
[209]	validation-rmse:8.10253
[210]	validation-rmse:8.10022
[211]	validation-rmse:8.09804
[212]	validation-rmse:8.09571
[213]	validation-rmse:8.09349
[214]	validation-rmse:8.09158
[215]	validation-rmse:8.08914
[216]	validation-rmse:8.08769
[217]	validation-rmse:8.08515
[218]	validation-rmse:8.08287
[219]	validation-rmse:8.08150
[220]	validation-rmse:8.07985
[221]	validation-rmse:8.07797
[222]	validation-rmse:8.07580
[223]	validation-rmse:8.07392
[224]	validation-rmse:8.07305
[225]	validation-rmse:8.07152
[226]	validation-rmse:8.06932
[227]	validation-rmse:8.06550
[228]	validation-rmse:8.06285
[229]	validation-rmse:8.06167
[230]	validation-rmse:8.05849
[231]	validation-rmse:8.05703
[232]	validation-rmse:8.05428
[233]	validation-rmse:8.05040
[234]	validation-rmse:8.04871
[235]	validation-rmse:8.04694
[236]	validation-rmse:8.04495
[237]	validation-rmse:8.04158
[238]	validation-rmse:8.03965
[239]	validation-rmse:8.03752
[240]	validation-rmse:8.03548
[241]	validation-rmse:8.03138
[242]	validation-rmse:8.02977
[243]	validation-rmse:8.02777
[244]	validation-rmse:8.02585
[245]	validation-rmse:8.02351
[246]	validation-rmse:8.02043
[247]	validation-rmse:8.01901
[248]	validation-rmse:8.01613
[249]	validation-rmse:8.01362
[250]	validation-rmse:8.01013
[251]	validation-rmse:8.00794
[252]	validation-rmse:8.00601
[253]	validation-rmse:8.00357
[254]	validation-rmse:8.00142
[255]	validation-rmse:7.99878
[256]	validation-rmse:7.99710
[257]	validation-rmse:7.99403
[258]	validation-rmse:7.99125
[259]	validation-rmse:7.98934
[260]	validation-rmse:7.98660
[261]	validation-rmse:7.98485
[262]	validation-rmse:7.98189
[263]	validation-rmse:7.97795
[264]	validation-rmse:7.97421
[265]	validation-rmse:7.97020
[266]	validation-rmse:7.96733
[267]	validation-rmse:7.96498
[268]	validation-rmse:7.96249
[269]	validation-rmse:7.95769
[270]	validation-rmse:7.95461
[271]	validation-rmse:7.95014
[272]	validation-rmse:7.94647
[273]	validation-rmse:7.94338
[274]	validation-rmse:7.93970
[275]	validation-rmse:7.93467
[276]	validation-rmse:7.93145
[277]	validation-rmse:7.92826
[278]	validation-rmse:7.92511
[279]	validation-rmse:7.92105
[280]	validation-rmse:7.91674
[281]	validation-rmse:7.91380
[282]	validation-rmse:7.91051
[283]	validation-rmse:7.90656
[284]	validation-rmse:7.90339
[285]	validation-rmse:7.90050
[286]	validation-rmse:7.89760
[287]	validation-rmse:7.89363
[288]	validation-rmse:7.89023
[289]	validation-rmse:7.88719
[290]	validation-rmse:7.88539
[291]	validation-rmse:7.88355
[292]	validation-rmse:7.88131
[293]	validation-rmse:7.87855
[294]	validation-rmse:7.87593
[295]	validation-rmse:7.87397
[296]	validation-rmse:7.87148
[297]	validation-rmse:7.86807
[298]	validation-rmse:7.86559
[299]	validation-rmse:7.86353
[300]	validation-rmse:7.86131
[301]	validation-rmse:7.85892
[302]	validation-rmse:7.85502
[303]	validation-rmse:7.85314
[304]	validation-rmse:7.85044
[305]	validation-rmse:7.84797
[306]	validation-rmse:7.84598
[307]	validation-rmse:7.84414
[308]	validation-rmse:7.84191
[309]	validation-rmse:7.83973
[310]	validation-rmse:7.83796
[311]	validation-rmse:7.83583
[312]	validation-rmse:7.83370
[313]	validation-rmse:7.83161
[314]	validation-rmse:7.83042
[315]	validation-rmse:7.82874
[316]	validation-rmse:7.82705
[317]	validation-rmse:7.82447
[318]	validation-rmse:7.82200
[319]	validation-rmse:7.82043
[320]	validation-rmse:7.81877
[321]	validation-rmse:7.81714
[322]	validation-rmse:7.81452
[323]	validation-rmse:7.81221
[324]	validation-rmse:7.81036
[325]	validation-rmse:7.80857
[326]	validation-rmse:7.80634
[327]	validation-rmse:7.80424
[328]	validation-rmse:7.80215
[329]	validation-rmse:7.80042
[330]	validation-rmse:7.79922
[331]	validation-rmse:7.79768
[332]	validation-rmse:7.79575
[333]	validation-rmse:7.79373
[334]	validation-rmse:7.79244
[335]	validation-rmse:7.79051
[336]	validation-rmse:7.78878
[337]	validation-rmse:7.78742
[338]	validation-rmse:7.78550
[339]	validation-rmse:7.78461
[340]	validation-rmse:7.78329
[341]	validation-rmse:7.78207
[342]	validation-rmse:7.78090
[343]	validation-rmse:7.77953
[344]	validation-rmse:7.77863
[345]	validation-rmse:7.77685
[346]	validation-rmse:7.77535
[347]	validation-rmse:7.77436
[348]	validation-rmse:7.77340
[349]	validation-rmse:7.77112
[350]	validation-rmse:7.76921
[351]	validation-rmse:7.76781
[352]	validation-rmse:7.76639
[353]	validation-rmse:7.76507
[354]	validation-rmse:7.76400
[355]	validation-rmse:7.76305
[356]	validation-rmse:7.76119
[357]	validation-rmse:7.76020
[358]	validation-rmse:7.75878
[359]	validation-rmse:7.75686
[360]	validation-rmse:7.75538
[361]	validation-rmse:7.75469
[362]	validation-rmse:7.75364
[363]	validation-rmse:7.75218
[364]	validation-rmse:7.74940
[365]	validation-rmse:7.74881
[366]	validation-rmse:7.74717
[367]	validation-rmse:7.74433
[368]	validation-rmse:7.74303
[369]	validation-rmse:7.74153
[370]	validation-rmse:7.74009
[371]	validation-rmse:7.73925
[372]	validation-rmse:7.73809
[373]	validation-rmse:7.73751
[374]	validation-rmse:7.73636
[375]	validation-rmse:7.73480
[376]	validation-rmse:7.73341
[377]	validation-rmse:7.73240
[378]	validation-rmse:7.73152
[379]	validation-rmse:7.72976
[380]	validation-rmse:7.72793
[381]	validation-rmse:7.72672
[382]	validation-rmse:7.72330
[383]	validation-rmse:7.72240
[384]	validation-rmse:7.72083
[385]	validation-rmse:7.71971
[386]	validation-rmse:7.71817
[387]	validation-rmse:7.71715
[388]	validation-rmse:7.71592
[389]	validation-rmse:7.71473
[390]	validation-rmse:7.71435
[391]	validation-rmse:7.71267
[392]	validation-rmse:7.71137
[393]	validation-rmse:7.71100
[394]	validation-rmse:7.71015
[395]	validation-rmse:7.70952
[396]	validation-rmse:7.70844
[397]	validation-rmse:7.70653
[398]	validation-rmse:7.70558
[399]	validation-rmse:7.70377
[400]	validation-rmse:7.70310
[401]	validation-rmse:7.70046
[402]	validation-rmse:7.69998
[403]	validation-rmse:7.69887
[404]	validation-rmse:7.69496
[405]	validation-rmse:7.69326
[406]	validation-rmse:7.69256
[407]	validation-rmse:7.69201
[408]	validation-rmse:7.69134
[409]	validation-rmse:7.69021
[410]	validation-rmse:7.68837
[411]	validation-rmse:7.68676
[412]	validation-rmse:7.68518
[413]	validation-rmse:7.68449
[414]	validation-rmse:7.68160
[415]	validation-rmse:7.68076
[416]	validation-rmse:7.67735
[417]	validation-rmse:7.67694
[418]	validation-rmse:7.67567
[419]	validation-rmse:7.67433
[420]	validation-rmse:7.67228
[421]	validation-rmse:7.67018
[422]	validation-rmse:7.66731
[423]	validation-rmse:7.66505
[424]	validation-rmse:7.66353
[425]	validation-rmse:7.66206
[426]	validation-rmse:7.65793
[427]	validation-rmse:7.65619
[428]	validation-rmse:7.65242
[429]	validation-rmse:7.65132
[430]	validation-rmse:7.64882
[431]	validation-rmse:7.64744
[432]	validation-rmse:7.64608
[433]	validation-rmse:7.64434
[434]	validation-rmse:7.64297
[435]	validation-rmse:7.64096
[436]	validation-rmse:7.63887
[437]	validation-rmse:7.63721
[438]	validation-rmse:7.63512
[439]	validation-rmse:7.63322
[440]	validation-rmse:7.62997
[441]	validation-rmse:7.62807
[442]	validation-rmse:7.62672
[443]	validation-rmse:7.62373
[444]	validation-rmse:7.62139
[445]	validation-rmse:7.61930
[446]	validation-rmse:7.61674
[447]	validation-rmse:7.61436
[448]	validation-rmse:7.61208
[449]	validation-rmse:7.60945
[450]	validation-rmse:7.60680
[451]	validation-rmse:7.60511
[452]	validation-rmse:7.60312
[453]	validation-rmse:7.60015
[454]	validation-rmse:7.59779
[455]	validation-rmse:7.59428
[456]	validation-rmse:7.59264
[457]	validation-rmse:7.59083
[458]	validation-rmse:7.58744
[459]	validation-rmse:7.58584
[460]	validation-rmse:7.58267
[461]	validation-rmse:7.58094
[462]	validation-rmse:7.57884
[463]	validation-rmse:7.57762
[464]	validation-rmse:7.57620
[465]	validation-rmse:7.57319
[466]	validation-rmse:7.57174
[467]	validation-rmse:7.57049
[468]	validation-rmse:7.56717
[469]	validation-rmse:7.56609
[470]	validation-rmse:7.56398
[471]	validation-rmse:7.56298
[472]	validation-rmse:7.56169
[473]	validation-rmse:7.55925
[474]	validation-rmse:7.55719
[475]	validation-rmse:7.55637
[476]	validation-rmse:7.55488
[477]	validation-rmse:7.55218
[478]	validation-rmse:7.55093
[479]	validation-rmse:7.54983
[480]	validation-rmse:7.54896
[481]	validation-rmse:7.54733
[482]	validation-rmse:7.54623
[483]	validation-rmse:7.54479
[484]	validation-rmse:7.54436
[485]	validation-rmse:7.54276
[486]	validation-rmse:7.54228
[487]	validation-rmse:7.54168
[488]	validation-rmse:7.54056
[489]	validation-rmse:7.53923
[490]	validation-rmse:7.53821
[491]	validation-rmse:7.53680
[492]	validation-rmse:7.53560
[493]	validation-rmse:7.53473
[494]	validation-rmse:7.53233
[495]	validation-rmse:7.53180
[496]	validation-rmse:7.53123
[497]	validation-rmse:7.52967
[498]	validation-rmse:7.52886
[499]	validation-rmse:7.52844
[500]	validation-rmse:7.52823
[501]	validation-rmse:7.52670
[502]	validation-rmse:7.52609
[503]	validation-rmse:7.52527
[504]	validation-rmse:7.52437
[505]	validation-rmse:7.52345
[506]	validation-rmse:7.52230
[507]	validation-rmse:7.52155
[508]	validation-rmse:7.52023
[509]	validation-rmse:7.51934
[510]	validation-rmse:7.51838
[511]	validation-rmse:7.51773
[512]	validation-rmse:7.51610
[513]	validation-rmse:7.51518
[514]	validation-rmse:7.51427
[515]	validation-rmse:7.51307
[516]	validation-rmse:7.51104
[517]	validation-rmse:7.50881
[518]	validation-rmse:7.50748
[519]	validation-rmse:7.50675
[520]	validation-rmse:7.50529
[521]	validation-rmse:7.50358
[522]	validation-rmse:7.50299
[523]	validation-rmse:7.50159
[524]	validation-rmse:7.50103
[525]	validation-rmse:7.50085
[526]	validation-rmse:7.49992
[527]	validation-rmse:7.49932
[528]	validation-rmse:7.49898
[529]	validation-rmse:7.49863
[530]	validation-rmse:7.49731
[531]	validation-rmse:7.49583
[532]	validation-rmse:7.49518
[533]	validation-rmse:7.49433
[534]	validation-rmse:7.49269
[535]	validation-rmse:7.49211
[536]	validation-rmse:7.49181
[537]	validation-rmse:7.49142
[538]	validation-rmse:7.49146
[539]	validation-rmse:7.48992
[540]	validation-rmse:7.48952
[541]	validation-rmse:7.48877
[542]	validation-rmse:7.48749
[543]	validation-rmse:7.48714
[544]	validation-rmse:7.48578
[545]	validation-rmse:7.48554
[546]	validation-rmse:7.48403
[547]	validation-rmse:7.48330
[548]	validation-rmse:7.48288
[549]	validation-rmse:7.48243
[550]	validation-rmse:7.48162
[551]	validation-rmse:7.48057
[552]	validation-rmse:7.48017
[553]	validation-rmse:7.47931
[554]	validation-rmse:7.47835
[555]	validation-rmse:7.47733
[556]	validation-rmse:7.47668
[557]	validation-rmse:7.47537
[558]	validation-rmse:7.47507
[559]	validation-rmse:7.47454
[560]	validation-rmse:7.47415
[561]	validation-rmse:7.47313
[562]	validation-rmse:7.47204
[563]	validation-rmse:7.47201
[564]	validation-rmse:7.47072
[565]	validation-rmse:7.47031
[566]	validation-rmse:7.46991
[567]	validation-rmse:7.46965
[568]	validation-rmse:7.46830
[569]	validation-rmse:7.46821
[570]	validation-rmse:7.46737
[571]	validation-rmse:7.46661
[572]	validation-rmse:7.46609
[573]	validation-rmse:7.46557
[574]	validation-rmse:7.46531
[575]	validation-rmse:7.46435
[576]	validation-rmse:7.46376
[577]	validation-rmse:7.46337
[578]	validation-rmse:7.46316
[579]	validation-rmse:7.46222
[580]	validation-rmse:7.46122
[581]	validation-rmse:7.46066
[582]	validation-rmse:7.45979
[583]	validation-rmse:7.45968
[584]	validation-rmse:7.45888
[585]	validation-rmse:7.45839
[586]	validation-rmse:7.45772
[587]	validation-rmse:7.45737
[588]	validation-rmse:7.45632
[589]	validation-rmse:7.45508
[590]	validation-rmse:7.45425
[591]	validation-rmse:7.45375
[592]	validation-rmse:7.45320
[593]	validation-rmse:7.45293
[594]	validation-rmse:7.45258
[595]	validation-rmse:7.45162
[596]	validation-rmse:7.45020
[597]	validation-rmse:7.44979
[598]	validation-rmse:7.44864
[599]	validation-rmse:7.44800
[600]	validation-rmse:7.44654
[601]	validation-rmse:7.44574
[602]	validation-rmse:7.44465
[603]	validation-rmse:7.44388
[604]	validation-rmse:7.44249
[605]	validation-rmse:7.44138
[606]	validation-rmse:7.44000
[607]	validation-rmse:7.43914
[608]	validation-rmse:7.43903
[609]	validation-rmse:7.43763
[610]	validation-rmse:7.43732
[611]	validation-rmse:7.43692
[612]	validation-rmse:7.43623
[613]	validation-rmse:7.43536
[614]	validation-rmse:7.43474
[615]	validation-rmse:7.43375
[616]	validation-rmse:7.43354
[617]	validation-rmse:7.43229
[618]	validation-rmse:7.43133
[619]	validation-rmse:7.43012
[620]	validation-rmse:7.42943
[621]	validation-rmse:7.42909
[622]	validation-rmse:7.42835
[623]	validation-rmse:7.42735
[624]	validation-rmse:7.42708
[625]	validation-rmse:7.42638
[626]	validation-rmse:7.42567
[627]	validation-rmse:7.42494
[628]	validation-rmse:7.42452
[629]	validation-rmse:7.42379
[630]	validation-rmse:7.42329
[631]	validation-rmse:7.42244
[632]	validation-rmse:7.42125
[633]	validation-rmse:7.42017
[634]	validation-rmse:7.41954
[635]	validation-rmse:7.41857
[636]	validation-rmse:7.41809
[637]	validation-rmse:7.41793
[638]	validation-rmse:7.41698
[639]	validation-rmse:7.41666
[640]	validation-rmse:7.41610
[641]	validation-rmse:7.41558
[642]	validation-rmse:7.41521
[643]	validation-rmse:7.41503
[644]	validation-rmse:7.41406
[645]	validation-rmse:7.41378
[646]	validation-rmse:7.41315
[647]	validation-rmse:7.41261
[648]	validation-rmse:7.41210
[649]	validation-rmse:7.41146
[650]	validation-rmse:7.41128
[651]	validation-rmse:7.41099
[652]	validation-rmse:7.41037
[653]	validation-rmse:7.41011
[654]	validation-rmse:7.41004
[655]	validation-rmse:7.40926
[656]	validation-rmse:7.40892
[657]	validation-rmse:7.40859
[658]	validation-rmse:7.40834
[659]	validation-rmse:7.40802
[660]	validation-rmse:7.40768
[661]	validation-rmse:7.40695
[662]	validation-rmse:7.40683
[663]	validation-rmse:7.40639
[664]	validation-rmse:7.40592
[665]	validation-rmse:7.40511
[666]	validation-rmse:7.40484
[667]	validation-rmse:7.40389
[668]	validation-rmse:7.40366
[669]	validation-rmse:7.40310

[12:32:54] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:17.33640
[2]	validation-rmse:15.89126
[3]	validation-rmse:14.72863
[4]	validation-rmse:13.74771
[5]	validation-rmse:12.95694
[6]	validation-rmse:12.34673
[7]	validation-rmse:11.79879
[8]	validation-rmse:11.34431
[9]	validation-rmse:11.02497
[10]	validation-rmse:10.76080
[11]	validation-rmse:10.55670
[12]	validation-rmse:10.32695
[13]	validation-rmse:10.18448
[14]	validation-rmse:10.02717
[15]	validation-rmse:9.90283
[16]	validation-rmse:9.82618
[17]	validation-rmse:9.75936
[18]	validation-rmse:9.64801
[19]	validation-rmse:9.58378
[20]	validation-rmse:9.53282
[21]	validation-rmse:9.49411
[22]	validation-rmse:9.43928
[23]	validation-rmse:9.38721
[24]	validation-rmse:9.36373
[25]	validation-rmse:9.30771
[26]	validation-rmse:9.26003
[27]	validation-rmse:9.21909
[28]	validation-rmse:9.18661
[29]	validation-rmse:9.15598
[30]	validation-rmse:9.13503
[31]	validation-rmse:9.09657
[32]	validation-rmse:9.05258
[33]	validation-rmse:9.03714
[34]	validation-rmse:9.00944
[35]	validation-rmse:8.96621
[36]	validation-rmse:8.94860
[37]	validation-rmse:8.92934
[38]	validation-rmse:8.90978
[39]	validation-rmse:8.88732
[40]	validation-rmse:8.83904
[41]	validation-rmse:8.82521
[42]	validation-rmse:8.81235
[43]	validation-rmse:8.77856
[44]	validation-rmse:8.76762
[45]	validation-rmse:8.74919
[46]	validation-rmse:8.73495
[47]	validation-rmse:8.69480
[48]	validation-rmse:8.68364
[49]	validation-rmse:8.64705
[50]	validation-rmse:8.62874
[51]	validation-rmse:8.61017
[52]	validation-rmse:8.59784
[53]	validation-rmse:8.58602
[54]	validation-rmse:8.57356
[55]	validation-rmse:8.55462
[56]	validation-rmse:8.54698
[57]	validation-rmse:8.53870
[58]	validation-rmse:8.51352
[59]	validation-rmse:8.49517
[60]	validation-rmse:8.48439
[61]	validation-rmse:8.46585
[62]	validation-rmse:8.44783
[63]	validation-rmse:8.44015
[64]	validation-rmse:8.42603
[65]	validation-rmse:8.40850
[66]	validation-rmse:8.39634
[67]	validation-rmse:8.39264
[68]	validation-rmse:8.36676
[69]	validation-rmse:8.35595
[70]	validation-rmse:8.35096
[71]	validation-rmse:8.33845
[72]	validation-rmse:8.32279
[73]	validation-rmse:8.28243
[74]	validation-rmse:8.26950
[75]	validation-rmse:8.25801
[76]	validation-rmse:8.24009
[77]	validation-rmse:8.22901
[78]	validation-rmse:8.22264
[79]	validation-rmse:8.20751
[80]	validation-rmse:8.20330
[81]	validation-rmse:8.19514
[82]	validation-rmse:8.17715
[83]	validation-rmse:8.13782
[84]	validation-rmse:8.12759
[85]	validation-rmse:8.12498
[86]	validation-rmse:8.10784
[87]	validation-rmse:8.09546
[88]	validation-rmse:8.09096
[89]	validation-rmse:8.08912
[90]	validation-rmse:8.07943
[91]	validation-rmse:8.07128
[92]	validation-rmse:8.06556
[93]	validation-rmse:8.06302
[94]	validation-rmse:8.05789
[95]	validation-rmse:8.04773
[96]	validation-rmse:8.03179
[97]	validation-rmse:8.02832
[98]	validation-rmse:8.02194
[99]	validation-rmse:8.01629
[100]	validation-rmse:8.01195
[101]	validation-rmse:7.99591
[102]	validation-rmse:7.99196
[103]	validation-rmse:7.99073
[104]	validation-rmse:7.98061
[105]	validation-rmse:7.96976
[106]	validation-rmse:7.95992
[107]	validation-rmse:7.95335
[108]	validation-rmse:7.94932
[109]	validation-rmse:7.94175
[110]	validation-rmse:7.93870
[111]	validation-rmse:7.92506
[112]	validation-rmse:7.92263
[113]	validation-rmse:7.89847
[114]	validation-rmse:7.89129
[115]	validation-rmse:7.88597
[116]	validation-rmse:7.88178
[117]	validation-rmse:7.87558
[118]	validation-rmse:7.87238
[119]	validation-rmse:7.86782
[120]	validation-rmse:7.86317
[121]	validation-rmse:7.86116
[122]	validation-rmse:7.85623
[123]	validation-rmse:7.84645
[124]	validation-rmse:7.83789
[125]	validation-rmse:7.83308
[126]	validation-rmse:7.82347
[127]	validation-rmse:7.81291
[128]	validation-rmse:7.81096
[129]	validation-rmse:7.80881
[130]	validation-rmse:7.80587
[131]	validation-rmse:7.79827
[132]	validation-rmse:7.78997
[133]	validation-rmse:7.78609
[134]	validation-rmse:7.78332
[135]	validation-rmse:7.77974
[136]	validation-rmse:7.77902
[137]	validation-rmse:7.77649
[138]	validation-rmse:7.77221
[139]	validation-rmse:7.76982
[140]	validation-rmse:7.76462
[141]	validation-rmse:7.76303
[142]	validation-rmse:7.76214
[143]	validation-rmse:7.76043
[144]	validation-rmse:7.75728
[145]	validation-rmse:7.75126
[146]	validation-rmse:7.74398
[147]	validation-rmse:7.74144
[148]	validation-rmse:7.73372
[149]	validation-rmse:7.72747
[150]	validation-rmse:7.72382
[151]	validation-rmse:7.72114
[152]	validation-rmse:7.71994
[153]	validation-rmse:7.71802
[154]	validation-rmse:7.71644
[155]	validation-rmse:7.71248
[156]	validation-rmse:7.70978
[157]	validation-rmse:7.70655
[158]	validation-rmse:7.70115
[159]	validation-rmse:7.69844
[160]	validation-rmse:7.69658
[161]	validation-rmse:7.69616
[162]	validation-rmse:7.69497
[163]	validation-rmse:7.69363
[164]	validation-rmse:7.69320
[165]	validation-rmse:7.69094
[166]	validation-rmse:7.68830
[167]	validation-rmse:7.68596
[168]	validation-rmse:7.68409
[169]	validation-rmse:7.68116
[170]	validation-rmse:7.67646
[171]	validation-rmse:7.67306
[172]	validation-rmse:7.67113
[173]	validation-rmse:7.67044
[174]	validation-rmse:7.66797
[175]	validation-rmse:7.66691
[176]	validation-rmse:7.66568
[177]	validation-rmse:7.66436
[178]	validation-rmse:7.66391
[179]	validation-rmse:7.66309
[180]	validation-rmse:7.65438
[181]	validation-rmse:7.65267
[182]	validation-rmse:7.65041
[183]	validation-rmse:7.64656
[184]	validation-rmse:7.64150
[185]	validation-rmse:7.64003
[186]	validation-rmse:7.63638
[187]	validation-rmse:7.63459
[188]	validation-rmse:7.63303
[189]	validation-rmse:7.63184
[190]	validation-rmse:7.63065
[191]	validation-rmse:7.62950
[192]	validation-rmse:7.62949
[193]	validation-rmse:7.62874
[194]	validation-rmse:7.62694
[195]	validation-rmse:7.62490
[196]	validation-rmse:7.62345
[197]	validation-rmse:7.62254
[198]	validation-rmse:7.61989
[199]	validation-rmse:7.61718
[200]	validation-rmse:7.61315
[201]	validation-rmse:7.61254
[202]	validation-rmse:7.61076
[203]	validation-rmse:7.60903
[204]	validation-rmse:7.60836
[205]	validation-rmse:7.60772
[206]	validation-rmse:7.60679
[207]	validation-rmse:7.60401
[208]	validation-rmse:7.60362
[209]	validation-rmse:7.60242
[210]	validation-rmse:7.59948
[211]	validation-rmse:7.59835
[212]	validation-rmse:7.59649
[213]	validation-rmse:7.59534
[214]	validation-rmse:7.59461
[215]	validation-rmse:7.59377
[216]	validation-rmse:7.59116
[217]	validation-rmse:7.59049
[218]	validation-rmse:7.58990
[219]	validation-rmse:7.58940
[220]	validation-rmse:7.58868
[221]	validation-rmse:7.58818
[222]	validation-rmse:7.58787
[223]	validation-rmse:7.58750
[224]	validation-rmse:7.58637
[225]	validation-rmse:7.58523
[226]	validation-rmse:7.58005
[227]	validation-rmse:7.57785
[228]	validation-rmse:7.57577
[229]	validation-rmse:7.57416
[230]	validation-rmse:7.57327
[231]	validation-rmse:7.57178
[232]	validation-rmse:7.57185
[233]	validation-rmse:7.57081
[234]	validation-rmse:7.56971
[235]	validation-rmse:7.56969
[236]	validation-rmse:7.56892
[237]	validation-rmse:7.56394
[238]	validation-rmse:7.56281
[239]	validation-rmse:7.56251
[240]	validation-rmse:7.56214
[241]	validation-rmse:7.56129
[242]	validation-rmse:7.56114
[243]	validation-rmse:7.56038
[244]	validation-rmse:7.55881
[245]	validation-rmse:7.55808
[246]	validation-rmse:7.55719
[247]	validation-rmse:7.55346
[248]	validation-rmse:7.55166
[249]	validation-rmse:7.55092
[250]	validation-rmse:7.55044
[251]	validation-rmse:7.54995
[252]	validation-rmse:7.54983
[253]	validation-rmse:7.54928
[254]	validation-rmse:7.54834
[255]	validation-rmse:7.54446
[256]	validation-rmse:7.54369
[257]	validation-rmse:7.54145
[258]	validation-rmse:7.54060
[259]	validation-rmse:7.54066
[260]	validation-rmse:7.54009
[261]	validation-rmse:7.53991
[262]	validation-rmse:7.53961
[263]	validation-rmse:7.53918
[264]	validation-rmse:7.53850
[265]	validation-rmse:7.53871
[266]	validation-rmse:7.53844
[267]	validation-rmse:7.53868
[268]	validation-rmse:7.53854
[269]	validation-rmse:7.53838
[270]	validation-rmse:7.53791
[271]	validation-rmse:7.53651
[272]	validation-rmse:7.53646
[273]	validation-rmse:7.53428
[274]	validation-rmse:7.53368
[275]	validation-rmse:7.53328
[276]	validation-rmse:7.53250
[277]	validation-rmse:7.53229
[278]	validation-rmse:7.53195
[279]	validation-rmse:7.53060
[280]	validation-rmse:7.52995
[281]	validation-rmse:7.52970
[282]	validation-rmse:7.52966
[283]	validation-rmse:7.52934
[284]	validation-rmse:7.52938
[285]	validation-rmse:7.52921
[286]	validation-rmse:7.52870
[287]	validation-rmse:7.52812
[288]	validation-rmse:7.52735
[289]	validation-rmse:7.52562
[290]	validation-rmse:7.52465
[291]	validation-rmse:7.52430
[292]	validation-rmse:7.52326
[293]	validation-rmse:7.52277
[294]	validation-rmse:7.52177
[295]	validation-rmse:7.52140
[296]	validation-rmse:7.52141
[297]	validation-rmse:7.52089
[298]	validation-rmse:7.52021
[299]	validation-rmse:7.51943
[300]	validation-rmse:7.51920
[301]	validation-rmse:7.51752
[302]	validation-rmse:7.51724
[303]	validation-rmse:7.51659
[304]	validation-rmse:7.51635
[305]	validation-rmse:7.51633
[306]	validation-rmse:7.51587
[307]	validation-rmse:7.51579
[308]	validation-rmse:7.51508
[309]	validation-rmse:7.51446
[310]	validation-rmse:7.51419
[311]	validation-rmse:7.51426
[312]	validation-rmse:7.51350
[313]	validation-rmse:7.51320
[314]	validation-rmse:7.51244
[315]	validation-rmse:7.51231
[316]	validation-rmse:7.51216
[317]	validation-rmse:7.51169
[318]	validation-rmse:7.51163
[319]	validation-rmse:7.51079
[320]	validation-rmse:7.51003
[321]	validation-rmse:7.50997
[322]	validation-rmse:7.50968
[323]	validation-rmse:7.50842
[324]	validation-rmse:7.50816
[325]	validation-rmse:7.50818
[326]	validation-rmse:7.50800
[327]	validation-rmse:7.50785
[328]	validation-rmse:7.50734
[329]	validation-rmse:7.50678
[330]	validation-rmse:7.50585
[331]	validation-rmse:7.50571
[332]	validation-rmse:7.50477
[333]	validation-rmse:7.50438
[334]	validation-rmse:7.50409
[335]	validation-rmse:7.50279
[336]	validation-rmse:7.50290
[337]	validation-rmse:7.50291
[338]	validation-rmse:7.50239
[339]	validation-rmse:7.50130
[340]	validation-rmse:7.50058
[341]	validation-rmse:7.50053
[342]	validation-rmse:7.49983
[343]	validation-rmse:7.49963
[344]	validation-rmse:7.49944
[345]	validation-rmse:7.49911
[346]	validation-rmse:7.49845
[347]	validation-rmse:7.49789
[348]	validation-rmse:7.49758
[349]	validation-rmse:7.49753
[350]	validation-rmse:7.49711
[351]	validation-rmse:7.49697
[352]	validation-rmse:7.49612
[353]	validation-rmse:7.49552
[354]	validation-rmse:7.49473
[355]	validation-rmse:7.49462
[356]	validation-rmse:7.49438
[357]	validation-rmse:7.49393
[358]	validation-rmse:7.49360
[359]	validation-rmse:7.49322
[360]	validation-rmse:7.49280
[361]	validation-rmse:7.49271
[362]	validation-rmse:7.49269
[363]	validation-rmse:7.49283
[364]	validation-rmse:7.49259
[365]	validation-rmse:7.49252
[366]	validation-rmse:7.49167
[367]	validation-rmse:7.49131
[368]	validation-rmse:7.49129
[369]	validation-rmse:7.49104
[370]	validation-rmse:7.49020
[371]	validation-rmse:7.49011
[372]	validation-rmse:7.48991
[373]	validation-rmse:7.49000
[374]	validation-rmse:7.48997
[375]	validation-rmse:7.48985
[376]	validation-rmse:7.48968
[377]	validation-rmse:7.48932
[378]	validation-rmse:7.48915
[379]	validation-rmse:7.48908
[380]	validation-rmse:7.48873
[381]	validation-rmse:7.48790
[382]	validation-rmse:7.48783
[383]	validation-rmse:7.48695
[384]	validation-rmse:7.48588
[385]	validation-rmse:7.48574
[386]	validation-rmse:7.48575
[387]	validation-rmse:7.48559
[388]	validation-rmse:7.48561
[389]	validation-rmse:7.48554
[390]	validation-rmse:7.48503
[391]	validation-rmse:7.48408
[392]	validation-rmse:7.48405
[393]	validation-rmse:7.48347
[394]	validation-rmse:7.48351
[395]	validation-rmse:7.48287
[396]	validation-rmse:7.48296
[397]	validation-rmse:7.48280
[398]	validation-rmse:7.48243
[399]	validation-rmse:7.48230
[400]	validation-rmse:7.48186
[401]	validation-rmse:7.48140
[402]	validation-rmse:7.48086
[403]	validation-rmse:7.48051
[404]	validation-rmse:7.48039
[405]	validation-rmse:7.48031
[406]	validation-rmse:7.48020
[407]	validation-rmse:7.47968
[408]	validation-rmse:7.47979
[409]	validation-rmse:7.47909
[410]	validation-rmse:7.47899
[411]	validation-rmse:7.47889
[412]	validation-rmse:7.47880
[413]	validation-rmse:7.47884
[414]	validation-rmse:7.47844
[415]	validation-rmse:7.47818
[416]	validation-rmse:7.47800
[417]	validation-rmse:7.47803
[418]	validation-rmse:7.47793
[419]	validation-rmse:7.47776
[420]	validation-rmse:7.47744
[421]	validation-rmse:7.47741
[422]	validation-rmse:7.47719
[423]	validation-rmse:7.47703
[424]	validation-rmse:7.47672
[425]	validation-rmse:7.47642
[426]	validation-rmse:7.47580
[427]	validation-rmse:7.47499
[428]	validation-rmse:7.47492
[429]	validation-rmse:7.47452
[430]	validation-rmse:7.47400
[431]	validation-rmse:7.47363
[432]	validation-rmse:7.47383
[433]	validation-rmse:7.47391
[434]	validation-rmse:7.47381
[435]	validation-rmse:7.47388
[436]	validation-rmse:7.47378
[437]	validation-rmse:7.47394
[438]	validation-rmse:7.47377
[439]	validation-rmse:7.47350
[440]	validation-rmse:7.47335
[441]	validation-rmse:7.47303
[442]	validation-rmse:7.47302
[443]	validation-rmse:7.47200
[444]	validation-rmse:7.47184
[445]	validation-rmse:7.47163
[446]	validation-rmse:7.47110
[447]	validation-rmse:7.47083
[448]	validation-rmse:7.47035
[449]	validation-rmse:7.47038
[450]	validation-rmse:7.47043
[451]	validation-rmse:7.47065
[452]	validation-rmse:7.47053
[453]	validation-rmse:7.47046
[454]	validation-rmse:7.47027
[455]	validation-rmse:7.46937
[456]	validation-rmse:7.46948
[457]	validation-rmse:7.46912
[458]	validation-rmse:7.46889
[459]	validation-rmse:7.46845
[460]	validation-rmse:7.46836
[461]	validation-rmse:7.46816
[462]	validation-rmse:7.46789
[463]	validation-rmse:7.46790
[464]	validation-rmse:7.46684
[465]	validation-rmse:7.46621
[466]	validation-rmse:7.46607
[467]	validation-rmse:7.46514
[468]	validation-rmse:7.46507
[469]	validation-rmse:7.46499
[470]	validation-rmse:7.46484
[471]	validation-rmse:7.46418
[472]	validation-rmse:7.46418
[473]	validation-rmse:7.46407
[474]	validation-rmse:7.46383
[475]	validation-rmse:7.46387
[476]	validation-rmse:7.46358
[477]	validation-rmse:7.46342
[478]	validation-rmse:7.46315
[479]	validation-rmse:7.46321
[480]	validation-rmse:7.46313
[481]	validation-rmse:7.46299
[482]	validation-rmse:7.46309
[483]	validation-rmse:7.46303
[484]	validation-rmse:7.46275
[485]	validation-rmse:7.46243
[486]	validation-rmse:7.46228
[487]	validation-rmse:7.46224
[488]	validation-rmse:7.46199
[489]	validation-rmse:7.46175
[490]	validation-rmse:7.46174
[491]	validation-rmse:7.46188
[492]	validation-rmse:7.46165
[493]	validation-rmse:7.46149
[494]	validation-rmse:7.46092
[495]	validation-rmse:7.46099
[496]	validation-rmse:7.46080
[497]	validation-rmse:7.46075
[498]	validation-rmse:7.46035
[499]	validation-rmse:7.46036
[500]	validation-rmse:7.46030
[501]	validation-rmse:7.45993
[502]	validation-rmse:7.45941
[503]	validation-rmse:7.45907
[504]	validation-rmse:7.45893
[505]	validation-rmse:7.45894
[506]	validation-rmse:7.45883
[507]	validation-rmse:7.45876
[508]	validation-rmse:7.45857
[509]	validation-rmse:7.45860
[510]	validation-rmse:7.45836
[511]	validation-rmse:7.45808
[512]	validation-rmse:7.45821
[513]	validation-rmse:7.45773
[514]	validation-rmse:7.45760
[515]	validation-rmse:7.45750
[516]	validation-rmse:7.45707
[517]	validation-rmse:7.45682
[518]	validation-rmse:7.45694
[519]	validation-rmse:7.45635
[520]	validation-rmse:7.45624
[521]	validation-rmse:7.45615
[522]	validation-rmse:7.45573
[523]	validation-rmse:7.45527
[524]	validation-rmse:7.45509
[525]	validation-rmse:7.45509
[526]	validation-rmse:7.45452
[527]	validation-rmse:7.45453
[528]	validation-rmse:7.45470
[529]	validation-rmse:7.45442
[530]	validation-rmse:7.45402
[531]	validation-rmse:7.45373
[532]	validation-rmse:7.45360
[533]	validation-rmse:7.45386
[534]	validation-rmse:7.45346
[535]	validation-rmse:7.45310
[536]	validation-rmse:7.45312
[537]	validation-rmse:7.45291
[538]	validation-rmse:7.45280
[539]	validation-rmse:7.45280
[540]	validation-rmse:7.45269
[541]	validation-rmse:7.45255
[542]	validation-rmse:7.45245
[543]	validation-rmse:7.45201
[544]	validation-rmse:7.45154
[545]	validation-rmse:7.45158
[546]	validation-rmse:7.45119
[547]	validation-rmse:7.45093
[548]	validation-rmse:7.45061
[549]	validation-rmse:7.45024
[550]	validation-rmse:7.45036
[551]	validation-rmse:7.45023
[552]	validation-rmse:7.44986
[553]	validation-rmse:7.44929
[554]	validation-rmse:7.44911
[555]	validation-rmse:7.44921
[556]	validation-rmse:7.44862
[557]	validation-rmse:7.44830
[558]	validation-rmse:7.44811
[559]	validation-rmse:7.44830
[560]	validation-rmse:7.44829
[561]	validation-rmse:7.44804
[562]	validation-rmse:7.44802
[563]	validation-rmse:7.44776
[564]	validation-rmse:7.44679
[565]	validation-rmse:7.44687
[566]	validation-rmse:7.44681
[567]	validation-rmse:7.44665
[568]	validation-rmse:7.44640
[569]	validation-rmse:7.44649
[570]	validation-rmse:7.44657
[571]	validation-rmse:7.44647
[572]	validation-rmse:7.44622
[573]	validation-rmse:7.44606
[574]	validation-rmse:7.44577
[575]	validation-rmse:7.44567
[576]	validation-rmse:7.44565
[577]	validation-rmse:7.44556
[578]	validation-rmse:7.44544
[579]	validation-rmse:7.44528
[580]	validation-rmse:7.44499
[581]	validation-rmse:7.44449
[582]	validation-rmse:7.44434
[583]	validation-rmse:7.44450
[584]	validation-rmse:7.44442
[585]	validation-rmse:7.44429
[586]	validation-rmse:7.44426
[587]	validation-rmse:7.44390
[588]	validation-rmse:7.44395
[589]	validation-rmse:7.44402
[590]	validation-rmse:7.44402
[591]	validation-rmse:7.44395
[592]	validation-rmse:7.44362
[593]	validation-rmse:7.44248
[594]	validation-rmse:7.44232
[595]	validation-rmse:7.44183
[596]	validation-rmse:7.44172
[597]	validation-rmse:7.44162
[598]	validation-rmse:7.44158
[599]	validation-rmse:7.44139
[600]	validation-rmse:7.44137
[601]	validation-rmse:7.44146
[602]	validation-rmse:7.44158
[603]	validation-rmse:7.44122
[604]	validation-rmse:7.44115
[605]	validation-rmse:7.44111
[606]	validation-rmse:7.44099
[607]	validation-rmse:7.44079
[608]	validation-rmse:7.44087
[609]	validation-rmse:7.44092
[610]	validation-rmse:7.44034
[611]	validation-rmse:7.43990
[612]	validation-rmse:7.43964
[613]	validation-rmse:7.43978
[614]	validation-rmse:7.43955
[615]	validation-rmse:7.43940
[616]	validation-rmse:7.43953
[617]	validation-rmse:7.43954
[618]	validation-rmse:7.43943
[619]	validation-rmse:7.43922
[620]	validation-rmse:7.43900
[621]	validation-rmse:7.43893
[622]	validation-rmse:7.43859
[623]	validation-rmse:7.43849
[624]	validation-rmse:7.43821
[625]	validation-rmse:7.43833
[626]	validation-rmse:7.43846
[627]	validation-rmse:7.43842
[628]	validation-rmse:7.43853
[629]	validation-rmse:7.43835
[630]	validation-rmse:7.43852
[631]	validation-rmse:7.43843
[632]	validation-rmse:7.43795
[633]	validation-rmse:7.43787
[634]	validation-rmse:7.43771
[635]	validation-rmse:7.43766
[636]	validation-rmse:7.43753
[637]	validation-rmse:7.43755
[638]	validation-rmse:7.43708
[639]	validation-rmse:7.43694
[640]	validation-rmse:7.43640
[641]	validation-rmse:7.43625
[642]	validation-rmse:7.43634
[643]	validation-rmse:7.43625
[644]	validation-rmse:7.43564
[645]	validation-rmse:7.43577
[646]	validation-rmse:7.43563
[647]	validation-rmse:7.43530
[648]	validation-rmse:7.43529
[649]	validation-rmse:7.43508
[650]	validation-rmse:7.43505
[651]	validation-rmse:7.43475
[652]	validation-rmse:7.43447
[653]	validation-rmse:7.43439
[654]	validation-rmse:7.43429
[655]	validation-rmse:7.43395
[656]	validation-rmse:7.43370
[657]	validation-rmse:7.43342
[658]	validation-rmse:7.43335
[659]	validation-rmse:7.43333
[660]	validation-rmse:7.43323
[661]	validation-rmse:7.43280
[662]	validation-rmse:7.43261
[663]	validation-rmse:7.43252
[664]	validation-rmse:7.43254
[665]	validation-rmse:7.43258
[666]	validation-rmse:7.43229
[667]	validation-rmse:7.43214
[668]	validation-rmse:7.43215
[669]	validation-rmse:7.43193

[12:35:26] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[2]	validation-rmse:16.39342
[3]	validation-rmse:15.29325
[4]	validation-rmse:14.37316
[5]	validation-rmse:13.63164
[6]	validation-rmse:13.01453
[7]	validation-rmse:12.50068
[8]	validation-rmse:12.09145
[9]	validation-rmse:11.76516
[10]	validation-rmse:11.47433
[11]	validation-rmse:11.23127
[12]	validation-rmse:11.05328
[13]	validation-rmse:10.89393
[14]	validation-rmse:10.76671
[15]	validation-rmse:10.64021
[16]	validation-rmse:10.55694
[17]	validation-rmse:10.47232
[18]	validation-rmse:10.40586
[19]	validation-rmse:10.32039
[20]	validation-rmse:10.27115
[21]	validation-rmse:10.22789
[22]	validation-rmse:10.19210
[23]	validation-rmse:10.15591
[24]	validation-rmse:10.12024
[25]	validation-rmse:10.09672
[26]	validation-rmse:10.05686
[27]	validation-rmse:10.02465
[28]	validation-rmse:10.00842
[29]	validation-rmse:9.97645
[30]	validation-rmse:9.94605
[31]	validation-rmse:9.91297
[32]	validation-rmse:9.89489
[33]	validation-rmse:9.88437
[34]	validation-rmse:9.85642
[35]	validation-rmse:9.84517
[36]	validation-rmse:9.82363
[37]	validation-rmse:9.77535
[38]	validation-rmse:9.75597
[39]	validation-rmse:9.74662
[40]	validation-rmse:9.72287
[41]	validation-rmse:9.71393
[42]	validation-rmse:9.68905
[43]	validation-rmse:9.67936
[44]	validation-rmse:9.65831
[45]	validation-rmse:9.63345
[46]	validation-rmse:9.61645
[47]	validation-rmse:9.60289
[48]	validation-rmse:9.59406
[49]	validation-rmse:9.58381
[50]	validation-rmse:9.57587
[51]	validation-rmse:9.54746
[52]	validation-rmse:9.53896
[53]	validation-rmse:9.53320
[54]	validation-rmse:9.52417
[55]	validation-rmse:9.51843
[56]	validation-rmse:9.50399
[57]	validation-rmse:9.49214
[58]	validation-rmse:9.48614
[59]	validation-rmse:9.48050
[60]	validation-rmse:9.46202
[61]	validation-rmse:9.44911
[62]	validation-rmse:9.43457
[63]	validation-rmse:9.41788
[64]	validation-rmse:9.39086
[65]	validation-rmse:9.38556
[66]	validation-rmse:9.37439
[67]	validation-rmse:9.36626
[68]	validation-rmse:9.35778
[69]	validation-rmse:9.35475
[70]	validation-rmse:9.34909
[71]	validation-rmse:9.33682
[72]	validation-rmse:9.33243
[73]	validation-rmse:9.32621
[74]	validation-rmse:9.32022
[75]	validation-rmse:9.31318
[76]	validation-rmse:9.30596
[77]	validation-rmse:9.29915
[78]	validation-rmse:9.29042
[79]	validation-rmse:9.28361
[80]	validation-rmse:9.27228
[81]	validation-rmse:9.26509
[82]	validation-rmse:9.25709
[83]	validation-rmse:9.25255
[84]	validation-rmse:9.23837
[85]	validation-rmse:9.22830
[86]	validation-rmse:9.21452
[87]	validation-rmse:9.20443
[88]	validation-rmse:9.19579
[89]	validation-rmse:9.18939
[90]	validation-rmse:9.17847
[91]	validation-rmse:9.17550
[92]	validation-rmse:9.16994
[93]	validation-rmse:9.15699
[94]	validation-rmse:9.15022
[95]	validation-rmse:9.14767
[96]	validation-rmse:9.14048
[97]	validation-rmse:9.13697
[98]	validation-rmse:9.13394
[99]	validation-rmse:9.12554
[100]	validation-rmse:9.10078
[101]	validation-rmse:9.09665
[102]	validation-rmse:9.09276
[103]	validation-rmse:9.08856
[104]	validation-rmse:9.05659
[105]	validation-rmse:9.05310
[106]	validation-rmse:9.04946
[107]	validation-rmse:9.03922
[108]	validation-rmse:9.03442
[109]	validation-rmse:9.02899
[110]	validation-rmse:9.02813
[111]	validation-rmse:9.02650
[112]	validation-rmse:9.01955
[113]	validation-rmse:9.01238
[114]	validation-rmse:9.00791
[115]	validation-rmse:9.00166
[116]	validation-rmse:8.99473
[117]	validation-rmse:8.99024
[118]	validation-rmse:8.97887
[119]	validation-rmse:8.97329
[120]	validation-rmse:8.96799
[121]	validation-rmse:8.96653
[122]	validation-rmse:8.96263
[123]	validation-rmse:8.95922
[124]	validation-rmse:8.95489
[125]	validation-rmse:8.95236
[126]	validation-rmse:8.94912
[127]	validation-rmse:8.94401
[128]	validation-rmse:8.93712
[129]	validation-rmse:8.92065
[130]	validation-rmse:8.91477
[131]	validation-rmse:8.91228
[132]	validation-rmse:8.90741
[133]	validation-rmse:8.90487
[134]	validation-rmse:8.89997
[135]	validation-rmse:8.89107
[136]	validation-rmse:8.88660
[137]	validation-rmse:8.88495
[138]	validation-rmse:8.87855
[139]	validation-rmse:8.87682
[140]	validation-rmse:8.87439
[141]	validation-rmse:8.87208
[142]	validation-rmse:8.87043
[143]	validation-rmse:8.86896
[144]	validation-rmse:8.86678
[145]	validation-rmse:8.85971
[146]	validation-rmse:8.85272
[147]	validation-rmse:8.82968
[148]	validation-rmse:8.82548
[149]	validation-rmse:8.82293
[150]	validation-rmse:8.81102
[151]	validation-rmse:8.80658
[152]	validation-rmse:8.80500
[153]	validation-rmse:8.80315
[154]	validation-rmse:8.79973
[155]	validation-rmse:8.79846
[156]	validation-rmse:8.79216
[157]	validation-rmse:8.79039
[158]	validation-rmse:8.78937
[159]	validation-rmse:8.78750
[160]	validation-rmse:8.77099
[161]	validation-rmse:8.76241
[162]	validation-rmse:8.75852
[163]	validation-rmse:8.75601
[164]	validation-rmse:8.75341
[165]	validation-rmse:8.75019
[166]	validation-rmse:8.74613
[167]	validation-rmse:8.72904
[168]	validation-rmse:8.72789
[169]	validation-rmse:8.72630
[170]	validation-rmse:8.71685
[171]	validation-rmse:8.70794
[172]	validation-rmse:8.70601
[173]	validation-rmse:8.70207
[174]	validation-rmse:8.70106
[175]	validation-rmse:8.69752
[176]	validation-rmse:8.69343
[177]	validation-rmse:8.69318
[178]	validation-rmse:8.69198
[179]	validation-rmse:8.68508
[180]	validation-rmse:8.68439
[181]	validation-rmse:8.67840
[182]	validation-rmse:8.67417
[183]	validation-rmse:8.67362
[184]	validation-rmse:8.66570
[185]	validation-rmse:8.66383
[186]	validation-rmse:8.65968
[187]	validation-rmse:8.65526
[188]	validation-rmse:8.65384
[189]	validation-rmse:8.65234
[190]	validation-rmse:8.65109
[191]	validation-rmse:8.64832
[192]	validation-rmse:8.64553
[193]	validation-rmse:8.64414
[194]	validation-rmse:8.64335
[195]	validation-rmse:8.64001
[196]	validation-rmse:8.63904
[197]	validation-rmse:8.63812
[198]	validation-rmse:8.63362
[199]	validation-rmse:8.63147
[200]	validation-rmse:8.63027
[201]	validation-rmse:8.62449
[202]	validation-rmse:8.62214
[203]	validation-rmse:8.61942
[204]	validation-rmse:8.60774
[205]	validation-rmse:8.60620
[206]	validation-rmse:8.60619
[207]	validation-rmse:8.60439
[208]	validation-rmse:8.60151
[209]	validation-rmse:8.59826
[210]	validation-rmse:8.59658
[211]	validation-rmse:8.59468
[212]	validation-rmse:8.59433
[213]	validation-rmse:8.59270
[214]	validation-rmse:8.59162
[215]	validation-rmse:8.59036
[216]	validation-rmse:8.58883
[217]	validation-rmse:8.58697
[218]	validation-rmse:8.58459
[219]	validation-rmse:8.58384
[220]	validation-rmse:8.58177
[221]	validation-rmse:8.58012
[222]	validation-rmse:8.57704
[223]	validation-rmse:8.57598
[224]	validation-rmse:8.57214
[225]	validation-rmse:8.57030
[226]	validation-rmse:8.56874
[227]	validation-rmse:8.56578
[228]	validation-rmse:8.56015
[229]	validation-rmse:8.54838
[230]	validation-rmse:8.53608
[231]	validation-rmse:8.53208
[232]	validation-rmse:8.52600
[233]	validation-rmse:8.52160
[234]	validation-rmse:8.51872
[235]	validation-rmse:8.51072
[236]	validation-rmse:8.50074
[237]	validation-rmse:8.49928
[238]	validation-rmse:8.49470
[239]	validation-rmse:8.49247
[240]	validation-rmse:8.48970
[241]	validation-rmse:8.48856
[242]	validation-rmse:8.48777
[243]	validation-rmse:8.47964
[244]	validation-rmse:8.47916
[245]	validation-rmse:8.47629
[246]	validation-rmse:8.47376
[247]	validation-rmse:8.47313
[248]	validation-rmse:8.47266
[249]	validation-rmse:8.47206
[250]	validation-rmse:8.47183
[251]	validation-rmse:8.47156
[252]	validation-rmse:8.47019
[253]	validation-rmse:8.46836
[254]	validation-rmse:8.46785
[255]	validation-rmse:8.46720
[256]	validation-rmse:8.46684
[257]	validation-rmse:8.46675
[258]	validation-rmse:8.46530
[259]	validation-rmse:8.46485
[260]	validation-rmse:8.46443
[261]	validation-rmse:8.46139
[262]	validation-rmse:8.46101
[263]	validation-rmse:8.46079
[264]	validation-rmse:8.46066
[265]	validation-rmse:8.46031
[266]	validation-rmse:8.45944
[267]	validation-rmse:8.45697
[268]	validation-rmse:8.45664
[269]	validation-rmse:8.45573
[270]	validation-rmse:8.45383
[271]	validation-rmse:8.45344
[272]	validation-rmse:8.45315
[273]	validation-rmse:8.45239
[274]	validation-rmse:8.45219
[275]	validation-rmse:8.45138
[276]	validation-rmse:8.45053
[277]	validation-rmse:8.44701
[278]	validation-rmse:8.44321
[279]	validation-rmse:8.44289
[280]	validation-rmse:8.44220
[281]	validation-rmse:8.44127
[282]	validation-rmse:8.44020
[283]	validation-rmse:8.43938
[284]	validation-rmse:8.43858
[285]	validation-rmse:8.43757
[286]	validation-rmse:8.43683
[287]	validation-rmse:8.43656
[288]	validation-rmse:8.43506
[289]	validation-rmse:8.43272
[290]	validation-rmse:8.43235
[291]	validation-rmse:8.42946
[292]	validation-rmse:8.42875
[293]	validation-rmse:8.42867
[294]	validation-rmse:8.42802
[295]	validation-rmse:8.42783
[296]	validation-rmse:8.42570
[297]	validation-rmse:8.42432
[298]	validation-rmse:8.42181
[299]	validation-rmse:8.42136
[300]	validation-rmse:8.41661
[301]	validation-rmse:8.41630
[302]	validation-rmse:8.41532
[303]	validation-rmse:8.41466
[304]	validation-rmse:8.41354
[305]	validation-rmse:8.41130
[306]	validation-rmse:8.40794
[307]	validation-rmse:8.40381
[308]	validation-rmse:8.40291
[309]	validation-rmse:8.39785
[310]	validation-rmse:8.39638
[311]	validation-rmse:8.39528
[312]	validation-rmse:8.39401
[313]	validation-rmse:8.39368
[314]	validation-rmse:8.39042
[315]	validation-rmse:8.38951
[316]	validation-rmse:8.38715
[317]	validation-rmse:8.38482
[318]	validation-rmse:8.38301
[319]	validation-rmse:8.38132
[320]	validation-rmse:8.38080
[321]	validation-rmse:8.38040
[322]	validation-rmse:8.37822
[323]	validation-rmse:8.37689
[324]	validation-rmse:8.37695
[325]	validation-rmse:8.37588
[326]	validation-rmse:8.37562
[327]	validation-rmse:8.37424
[328]	validation-rmse:8.37399
[329]	validation-rmse:8.37380
[330]	validation-rmse:8.37330
[331]	validation-rmse:8.37273
[332]	validation-rmse:8.37249
[333]	validation-rmse:8.37156
[334]	validation-rmse:8.37101
[335]	validation-rmse:8.36923
[336]	validation-rmse:8.36842
[337]	validation-rmse:8.36746
[338]	validation-rmse:8.36714
[339]	validation-rmse:8.36685
[340]	validation-rmse:8.36660
[341]	validation-rmse:8.36527
[342]	validation-rmse:8.36425
[343]	validation-rmse:8.36332
[344]	validation-rmse:8.36266
[345]	validation-rmse:8.36247
[346]	validation-rmse:8.36158
[347]	validation-rmse:8.36124
[348]	validation-rmse:8.36060
[349]	validation-rmse:8.36018
[350]	validation-rmse:8.35950
[351]	validation-rmse:8.35878
[352]	validation-rmse:8.35842
[353]	validation-rmse:8.35757
[354]	validation-rmse:8.35706
[355]	validation-rmse:8.35647
[356]	validation-rmse:8.35499
[357]	validation-rmse:8.35455
[358]	validation-rmse:8.35369
[359]	validation-rmse:8.35262
[360]	validation-rmse:8.35221
[361]	validation-rmse:8.35155
[362]	validation-rmse:8.35121
[363]	validation-rmse:8.35068
[364]	validation-rmse:8.35013
[365]	validation-rmse:8.34947
[366]	validation-rmse:8.34880
[367]	validation-rmse:8.34837
[368]	validation-rmse:8.34802
[369]	validation-rmse:8.34715
[370]	validation-rmse:8.34628
[371]	validation-rmse:8.34520
[372]	validation-rmse:8.34492
[373]	validation-rmse:8.34414
[374]	validation-rmse:8.34367
[375]	validation-rmse:8.34330
[376]	validation-rmse:8.34250
[377]	validation-rmse:8.34195
[378]	validation-rmse:8.34117
[379]	validation-rmse:8.34064
[380]	validation-rmse:8.33973
[381]	validation-rmse:8.33891
[382]	validation-rmse:8.33848
[383]	validation-rmse:8.33808
[384]	validation-rmse:8.33768
[385]	validation-rmse:8.33728
[386]	validation-rmse:8.33601
[387]	validation-rmse:8.33556
[388]	validation-rmse:8.33514
[389]	validation-rmse:8.33466
[390]	validation-rmse:8.33440
[391]	validation-rmse:8.33376
[392]	validation-rmse:8.33319
[393]	validation-rmse:8.33247
[394]	validation-rmse:8.33221
[395]	validation-rmse:8.33145
[396]	validation-rmse:8.33111
[397]	validation-rmse:8.33050
[398]	validation-rmse:8.33011
[399]	validation-rmse:8.32921
[400]	validation-rmse:8.32845
[401]	validation-rmse:8.32820
[402]	validation-rmse:8.32747
[403]	validation-rmse:8.32688
[404]	validation-rmse:8.32525
[405]	validation-rmse:8.32428
[406]	validation-rmse:8.32309
[407]	validation-rmse:8.32244
[408]	validation-rmse:8.32153
[409]	validation-rmse:8.32100
[410]	validation-rmse:8.32045
[411]	validation-rmse:8.31969
[412]	validation-rmse:8.31940
[413]	validation-rmse:8.31859
[414]	validation-rmse:8.31820
[415]	validation-rmse:8.31766
[416]	validation-rmse:8.31749
[417]	validation-rmse:8.31685
[418]	validation-rmse:8.31624
[419]	validation-rmse:8.31562
[420]	validation-rmse:8.31477
[421]	validation-rmse:8.31453
[422]	validation-rmse:8.31383
[423]	validation-rmse:8.31357
[424]	validation-rmse:8.31326
[425]	validation-rmse:8.31256
[426]	validation-rmse:8.31225
[427]	validation-rmse:8.31189
[428]	validation-rmse:8.31171
[429]	validation-rmse:8.31102
[430]	validation-rmse:8.31060
[431]	validation-rmse:8.31000
[432]	validation-rmse:8.30971
[433]	validation-rmse:8.30931
[434]	validation-rmse:8.30910
[435]	validation-rmse:8.30862
[436]	validation-rmse:8.30796
[437]	validation-rmse:8.30768
[438]	validation-rmse:8.30709
[439]	validation-rmse:8.30627
[440]	validation-rmse:8.30578
[441]	validation-rmse:8.30544
[442]	validation-rmse:8.30482
[443]	validation-rmse:8.30415
[444]	validation-rmse:8.30360
[445]	validation-rmse:8.30343
[446]	validation-rmse:8.30300
[447]	validation-rmse:8.30244
[448]	validation-rmse:8.30206
[449]	validation-rmse:8.30156
[450]	validation-rmse:8.30148
[451]	validation-rmse:8.30108
[452]	validation-rmse:8.29923
[453]	validation-rmse:8.29869
[454]	validation-rmse:8.29743
[455]	validation-rmse:8.29675
[456]	validation-rmse:8.29662
[457]	validation-rmse:8.29603
[458]	validation-rmse:8.29577
[459]	validation-rmse:8.29520
[460]	validation-rmse:8.29459
[461]	validation-rmse:8.29302
[462]	validation-rmse:8.29165
[463]	validation-rmse:8.29105
[464]	validation-rmse:8.29034
[465]	validation-rmse:8.29017
[466]	validation-rmse:8.28944
[467]	validation-rmse:8.28940
[468]	validation-rmse:8.28898
[469]	validation-rmse:8.28876
[470]	validation-rmse:8.28831
[471]	validation-rmse:8.28819
[472]	validation-rmse:8.28725
[473]	validation-rmse:8.28718
[474]	validation-rmse:8.28659
[475]	validation-rmse:8.28632
[476]	validation-rmse:8.28557
[477]	validation-rmse:8.28492
[478]	validation-rmse:8.28416
[479]	validation-rmse:8.28428
[480]	validation-rmse:8.28359
[481]	validation-rmse:8.28308
[482]	validation-rmse:8.28239
[483]	validation-rmse:8.28193
[484]	validation-rmse:8.28154
[485]	validation-rmse:8.28097
[486]	validation-rmse:8.28036
[487]	validation-rmse:8.27972
[488]	validation-rmse:8.27926
[489]	validation-rmse:8.27896
[490]	validation-rmse:8.27843
[491]	validation-rmse:8.27799
[492]	validation-rmse:8.27760
[493]	validation-rmse:8.27740
[494]	validation-rmse:8.27709
[495]	validation-rmse:8.27695
[496]	validation-rmse:8.27667
[497]	validation-rmse:8.27535
[498]	validation-rmse:8.27484
[499]	validation-rmse:8.27455
[500]	validation-rmse:8.27405
[501]	validation-rmse:8.27367
[502]	validation-rmse:8.27325
[503]	validation-rmse:8.27255
[504]	validation-rmse:8.27244
[505]	validation-rmse:8.27216
[506]	validation-rmse:8.27153
[507]	validation-rmse:8.27155
[508]	validation-rmse:8.27123
[509]	validation-rmse:8.27074
[510]	validation-rmse:8.26993
[511]	validation-rmse:8.26948
[512]	validation-rmse:8.26933
[513]	validation-rmse:8.26879
[514]	validation-rmse:8.26805
[515]	validation-rmse:8.26793
[516]	validation-rmse:8.26740
[517]	validation-rmse:8.26719
[518]	validation-rmse:8.26678
[519]	validation-rmse:8.26629
[520]	validation-rmse:8.26576
[521]	validation-rmse:8.26580
[522]	validation-rmse:8.26529
[523]	validation-rmse:8.26504
[524]	validation-rmse:8.26446
[525]	validation-rmse:8.26389
[526]	validation-rmse:8.26364
[527]	validation-rmse:8.26287
[528]	validation-rmse:8.26239
[529]	validation-rmse:8.26213
[530]	validation-rmse:8.26191
[531]	validation-rmse:8.26165
[532]	validation-rmse:8.26083
[533]	validation-rmse:8.26049
[534]	validation-rmse:8.25936
[535]	validation-rmse:8.25904
[536]	validation-rmse:8.25899
[537]	validation-rmse:8.25863
[538]	validation-rmse:8.25850
[539]	validation-rmse:8.25828
[540]	validation-rmse:8.25811
[541]	validation-rmse:8.25773
[542]	validation-rmse:8.25604
[543]	validation-rmse:8.25570
[544]	validation-rmse:8.25571
[545]	validation-rmse:8.25553
[546]	validation-rmse:8.25533
[547]	validation-rmse:8.25500
[548]	validation-rmse:8.25465
[549]	validation-rmse:8.25407
[550]	validation-rmse:8.25397
[551]	validation-rmse:8.25377
[552]	validation-rmse:8.25307
[553]	validation-rmse:8.25292
[554]	validation-rmse:8.25129
[555]	validation-rmse:8.25057
[556]	validation-rmse:8.25068
[557]	validation-rmse:8.25049
[558]	validation-rmse:8.25002
[559]	validation-rmse:8.24969
[560]	validation-rmse:8.24934
[561]	validation-rmse:8.24929
[562]	validation-rmse:8.24907
[563]	validation-rmse:8.24877
[564]	validation-rmse:8.24858
[565]	validation-rmse:8.24843
[566]	validation-rmse:8.24762
[567]	validation-rmse:8.24742
[568]	validation-rmse:8.24722
[569]	validation-rmse:8.24714
[570]	validation-rmse:8.24605
[571]	validation-rmse:8.24569
[572]	validation-rmse:8.24538
[573]	validation-rmse:8.24471
[574]	validation-rmse:8.24432
[575]	validation-rmse:8.24405
[576]	validation-rmse:8.24355
[577]	validation-rmse:8.24305
[578]	validation-rmse:8.24191
[579]	validation-rmse:8.24157
[580]	validation-rmse:8.24133
[581]	validation-rmse:8.24046
[582]	validation-rmse:8.24020
[583]	validation-rmse:8.23975
[584]	validation-rmse:8.23972
[585]	validation-rmse:8.23933
[586]	validation-rmse:8.23927
[587]	validation-rmse:8.23887
[588]	validation-rmse:8.23817
[589]	validation-rmse:8.23774
[590]	validation-rmse:8.23716
[591]	validation-rmse:8.23678
[592]	validation-rmse:8.23621
[593]	validation-rmse:8.23597
[594]	validation-rmse:8.23545
[595]	validation-rmse:8.23494
[596]	validation-rmse:8.23477
[597]	validation-rmse:8.23442
[598]	validation-rmse:8.23423
[599]	validation-rmse:8.23389
[600]	validation-rmse:8.23378
[601]	validation-rmse:8.23290
[602]	validation-rmse:8.23276
[603]	validation-rmse:8.23210
[604]	validation-rmse:8.23178
[605]	validation-rmse:8.23165
[606]	validation-rmse:8.23155
[607]	validation-rmse:8.23149
[608]	validation-rmse:8.23064
[609]	validation-rmse:8.23055
[610]	validation-rmse:8.23027
[611]	validation-rmse:8.22993
[612]	validation-rmse:8.22922
[613]	validation-rmse:8.22923
[614]	validation-rmse:8.22846
[615]	validation-rmse:8.22835
[616]	validation-rmse:8.22775
[617]	validation-rmse:8.22747
[618]	validation-rmse:8.22723
[619]	validation-rmse:8.22657
[620]	validation-rmse:8.22602
[621]	validation-rmse:8.22596
[622]	validation-rmse:8.22564
[623]	validation-rmse:8.22552
[624]	validation-rmse:8.22483
[625]	validation-rmse:8.22472
[626]	validation-rmse:8.22427
[627]	validation-rmse:8.22422
[628]	validation-rmse:8.22414
[629]	validation-rmse:8.22377
[630]	validation-rmse:8.22345
[631]	validation-rmse:8.22334
[632]	validation-rmse:8.22287
[633]	validation-rmse:8.22242
[634]	validation-rmse:8.22200
[635]	validation-rmse:8.22184
[636]	validation-rmse:8.22157
[637]	validation-rmse:8.22121
[638]	validation-rmse:8.22097
[639]	validation-rmse:8.22067
[640]	validation-rmse:8.22022
[641]	validation-rmse:8.22015
[642]	validation-rmse:8.22006
[643]	validation-rmse:8.21988
[644]	validation-rmse:8.21936
[645]	validation-rmse:8.21898
[646]	validation-rmse:8.21874
[647]	validation-rmse:8.21843
[648]	validation-rmse:8.21816
[649]	validation-rmse:8.21776
[650]	validation-rmse:8.21765
[651]	validation-rmse:8.21723
[652]	validation-rmse:8.21682
[653]	validation-rmse:8.21651
[654]	validation-rmse:8.21622
[655]	validation-rmse:8.21579
[656]	validation-rmse:8.21551
[657]	validation-rmse:8.21537
[658]	validation-rmse:8.21500
[659]	validation-rmse:8.21434
[660]	validation-rmse:8.21432
[661]	validation-rmse:8.21404
[662]	validation-rmse:8.21385
[663]	validation-rmse:8.21378
[664]	validation-rmse:8.21352
[665]	validation-rmse:8.21333
[666]	validation-rmse:8.21298
[667]	validation-rmse:8.21294
[668]	validation-rmse:8.21277
[669]	validation-rmse:8.21244
[670]	validation-rmse:8.21206

[12:37:15] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[2]	validation-rmse:18.53495
[3]	validation-rmse:17.78822
[4]	validation-rmse:17.10527
[5]	validation-rmse:16.47583
[6]	validation-rmse:15.89814
[7]	validation-rmse:15.37955
[8]	validation-rmse:14.89429
[9]	validation-rmse:14.45713
[10]	validation-rmse:14.06043
[11]	validation-rmse:13.69937
[12]	validation-rmse:13.35335
[13]	validation-rmse:13.05940
[14]	validation-rmse:12.77304
[15]	validation-rmse:12.51582
[16]	validation-rmse:12.29464
[17]	validation-rmse:12.08440
[18]	validation-rmse:11.88588
[19]	validation-rmse:11.72291
[20]	validation-rmse:11.57257
[21]	validation-rmse:11.42848
[22]	validation-rmse:11.30478
[23]	validation-rmse:11.17634
[24]	validation-rmse:11.07604
[25]	validation-rmse:10.95858
[26]	validation-rmse:10.86688
[27]	validation-rmse:10.78853
[28]	validation-rmse:10.71811
[29]	validation-rmse:10.64717
[30]	validation-rmse:10.59064
[31]	validation-rmse:10.51773
[32]	validation-rmse:10.46209
[33]	validation-rmse:10.41197
[34]	validation-rmse:10.37261
[35]	validation-rmse:10.32756
[36]	validation-rmse:10.28434
[37]	validation-rmse:10.23470
[38]	validation-rmse:10.20507
[39]	validation-rmse:10.17456
[40]	validation-rmse:10.14039
[41]	validation-rmse:10.11467
[42]	validation-rmse:10.09013
[43]	validation-rmse:10.06062
[44]	validation-rmse:10.02592
[45]	validation-rmse:10.00546
[46]	validation-rmse:9.98640
[47]	validation-rmse:9.95494
[48]	validation-rmse:9.93987
[49]	validation-rmse:9.91342
[50]	validation-rmse:9.89637
[51]	validation-rmse:9.88080
[52]	validation-rmse:9.86448
[53]	validation-rmse:9.84093
[54]	validation-rmse:9.82925
[55]	validation-rmse:9.81474
[56]	validation-rmse:9.79666
[57]	validation-rmse:9.77811
[58]	validation-rmse:9.76247
[59]	validation-rmse:9.75359
[60]	validation-rmse:9.73251
[61]	validation-rmse:9.70517
[62]	validation-rmse:9.69547
[63]	validation-rmse:9.67908
[64]	validation-rmse:9.66925
[65]	validation-rmse:9.65716
[66]	validation-rmse:9.64422
[67]	validation-rmse:9.63064
[68]	validation-rmse:9.62225
[69]	validation-rmse:9.60727
[70]	validation-rmse:9.58564
[71]	validation-rmse:9.57870
[72]	validation-rmse:9.57333
[73]	validation-rmse:9.56054
[74]	validation-rmse:9.54735
[75]	validation-rmse:9.53841
[76]	validation-rmse:9.51786
[77]	validation-rmse:9.50948
[78]	validation-rmse:9.50418
[79]	validation-rmse:9.49859
[80]	validation-rmse:9.48365
[81]	validation-rmse:9.47164
[82]	validation-rmse:9.46834
[83]	validation-rmse:9.45294
[84]	validation-rmse:9.44240
[85]	validation-rmse:9.43709
[86]	validation-rmse:9.41779
[87]	validation-rmse:9.41358
[88]	validation-rmse:9.40920
[89]	validation-rmse:9.39802
[90]	validation-rmse:9.38768
[91]	validation-rmse:9.36853
[92]	validation-rmse:9.36399
[93]	validation-rmse:9.35530
[94]	validation-rmse:9.34710
[95]	validation-rmse:9.33564
[96]	validation-rmse:9.33144
[97]	validation-rmse:9.31890
[98]	validation-rmse:9.31517
[99]	validation-rmse:9.30596
[100]	validation-rmse:9.29038
[101]	validation-rmse:9.28562
[102]	validation-rmse:9.27939
[103]	validation-rmse:9.26416
[104]	validation-rmse:9.26037
[105]	validation-rmse:9.25426
[106]	validation-rmse:9.24369
[107]	validation-rmse:9.22591
[108]	validation-rmse:9.21837
[109]	validation-rmse:9.21527
[110]	validation-rmse:9.20986
[111]	validation-rmse:9.20347
[112]	validation-rmse:9.19621
[113]	validation-rmse:9.19115
[114]	validation-rmse:9.18672
[115]	validation-rmse:9.17219
[116]	validation-rmse:9.16421
[117]	validation-rmse:9.15580
[118]	validation-rmse:9.15249
[119]	validation-rmse:9.13399
[120]	validation-rmse:9.13018
[121]	validation-rmse:9.11962
[122]	validation-rmse:9.11237
[123]	validation-rmse:9.10099
[124]	validation-rmse:9.09312
[125]	validation-rmse:9.09065
[126]	validation-rmse:9.08310
[127]	validation-rmse:9.07221
[128]	validation-rmse:9.06409
[129]	validation-rmse:9.06052
[130]	validation-rmse:9.05469
[131]	validation-rmse:9.05161
[132]	validation-rmse:9.04212
[133]	validation-rmse:9.02868
[134]	validation-rmse:9.02694
[135]	validation-rmse:9.02006
[136]	validation-rmse:9.01346
[137]	validation-rmse:9.00954
[138]	validation-rmse:9.00653
[139]	validation-rmse:8.99699
[140]	validation-rmse:8.99536
[141]	validation-rmse:8.99207
[142]	validation-rmse:8.98935
[143]	validation-rmse:8.98186
[144]	validation-rmse:8.97661
[145]	validation-rmse:8.96739
[146]	validation-rmse:8.96212
[147]	validation-rmse:8.95549
[148]	validation-rmse:8.95166
[149]	validation-rmse:8.94582
[150]	validation-rmse:8.94326
[151]	validation-rmse:8.93425
[152]	validation-rmse:8.93153
[153]	validation-rmse:8.92842
[154]	validation-rmse:8.91773
[155]	validation-rmse:8.91066
[156]	validation-rmse:8.90901
[157]	validation-rmse:8.90685
[158]	validation-rmse:8.88951
[159]	validation-rmse:8.88087
[160]	validation-rmse:8.86863
[161]	validation-rmse:8.86517
[162]	validation-rmse:8.86179
[163]	validation-rmse:8.85874
[164]	validation-rmse:8.85480
[165]	validation-rmse:8.84640
[166]	validation-rmse:8.84425
[167]	validation-rmse:8.84310
[168]	validation-rmse:8.83724
[169]	validation-rmse:8.82885
[170]	validation-rmse:8.82328
[171]	validation-rmse:8.82028
[172]	validation-rmse:8.81212
[173]	validation-rmse:8.80898
[174]	validation-rmse:8.80254
[175]	validation-rmse:8.79803
[176]	validation-rmse:8.78744
[177]	validation-rmse:8.78456
[178]	validation-rmse:8.78050
[179]	validation-rmse:8.77637
[180]	validation-rmse:8.76916
[181]	validation-rmse:8.76537
[182]	validation-rmse:8.76377
[183]	validation-rmse:8.75459
[184]	validation-rmse:8.75213
[185]	validation-rmse:8.75103
[186]	validation-rmse:8.74319
[187]	validation-rmse:8.74049
[188]	validation-rmse:8.73766
[189]	validation-rmse:8.73483
[190]	validation-rmse:8.73105
[191]	validation-rmse:8.72448
[192]	validation-rmse:8.72143
[193]	validation-rmse:8.72001
[194]	validation-rmse:8.71491
[195]	validation-rmse:8.71243
[196]	validation-rmse:8.71059
[197]	validation-rmse:8.69997
[198]	validation-rmse:8.69296
[199]	validation-rmse:8.68302
[200]	validation-rmse:8.68086
[201]	validation-rmse:8.67863
[202]	validation-rmse:8.67495
[203]	validation-rmse:8.66943
[204]	validation-rmse:8.66844
[205]	validation-rmse:8.66398
[206]	validation-rmse:8.65461
[207]	validation-rmse:8.64960
[208]	validation-rmse:8.64545
[209]	validation-rmse:8.64385
[210]	validation-rmse:8.64108
[211]	validation-rmse:8.63815
[212]	validation-rmse:8.63419
[213]	validation-rmse:8.63254
[214]	validation-rmse:8.62547
[215]	validation-rmse:8.62101
[216]	validation-rmse:8.61845
[217]	validation-rmse:8.61351
[218]	validation-rmse:8.60261
[219]	validation-rmse:8.60133
[220]	validation-rmse:8.59958
[221]	validation-rmse:8.59834
[222]	validation-rmse:8.59512
[223]	validation-rmse:8.58730
[224]	validation-rmse:8.58323
[225]	validation-rmse:8.58129
[226]	validation-rmse:8.57756
[227]	validation-rmse:8.57302
[228]	validation-rmse:8.56977
[229]	validation-rmse:8.56803
[230]	validation-rmse:8.56456
[231]	validation-rmse:8.56335
[232]	validation-rmse:8.56217
[233]	validation-rmse:8.55955
[234]	validation-rmse:8.55197
[235]	validation-rmse:8.54222
[236]	validation-rmse:8.54014
[237]	validation-rmse:8.53180
[238]	validation-rmse:8.52821
[239]	validation-rmse:8.52740
[240]	validation-rmse:8.52413
[241]	validation-rmse:8.51509
[242]	validation-rmse:8.51447
[243]	validation-rmse:8.50865
[244]	validation-rmse:8.50591
[245]	validation-rmse:8.50460
[246]	validation-rmse:8.50069
[247]	validation-rmse:8.49102
[248]	validation-rmse:8.48846
[249]	validation-rmse:8.48447
[250]	validation-rmse:8.48073
[251]	validation-rmse:8.47453
[252]	validation-rmse:8.46937
[253]	validation-rmse:8.46393
[254]	validation-rmse:8.46151
[255]	validation-rmse:8.45602
[256]	validation-rmse:8.45375
[257]	validation-rmse:8.45189
[258]	validation-rmse:8.44872
[259]	validation-rmse:8.44705
[260]	validation-rmse:8.44475
[261]	validation-rmse:8.44355
[262]	validation-rmse:8.43452
[263]	validation-rmse:8.43112
[264]	validation-rmse:8.43045
[265]	validation-rmse:8.42897
[266]	validation-rmse:8.42752
[267]	validation-rmse:8.42502
[268]	validation-rmse:8.42425
[269]	validation-rmse:8.42328
[270]	validation-rmse:8.41997
[271]	validation-rmse:8.41832
[272]	validation-rmse:8.41100
[273]	validation-rmse:8.40921
[274]	validation-rmse:8.40536
[275]	validation-rmse:8.40309
[276]	validation-rmse:8.40137
[277]	validation-rmse:8.39641
[278]	validation-rmse:8.39170
[279]	validation-rmse:8.39082
[280]	validation-rmse:8.38882
[281]	validation-rmse:8.38730
[282]	validation-rmse:8.38433
[283]	validation-rmse:8.37879
[284]	validation-rmse:8.37566
[285]	validation-rmse:8.37495
[286]	validation-rmse:8.36979
[287]	validation-rmse:8.36601
[288]	validation-rmse:8.36511
[289]	validation-rmse:8.36433
[290]	validation-rmse:8.35819
[291]	validation-rmse:8.35516
[292]	validation-rmse:8.34931
[293]	validation-rmse:8.34634
[294]	validation-rmse:8.34386
[295]	validation-rmse:8.34155
[296]	validation-rmse:8.34069
[297]	validation-rmse:8.33943
[298]	validation-rmse:8.33813
[299]	validation-rmse:8.33666
[300]	validation-rmse:8.33510
[301]	validation-rmse:8.32950
[302]	validation-rmse:8.32534
[303]	validation-rmse:8.32376
[304]	validation-rmse:8.31929
[305]	validation-rmse:8.31853
[306]	validation-rmse:8.31438
[307]	validation-rmse:8.31204
[308]	validation-rmse:8.31054
[309]	validation-rmse:8.30565
[310]	validation-rmse:8.30458
[311]	validation-rmse:8.30188
[312]	validation-rmse:8.29532
[313]	validation-rmse:8.29231
[314]	validation-rmse:8.28973
[315]	validation-rmse:8.28819
[316]	validation-rmse:8.28553
[317]	validation-rmse:8.28232
[318]	validation-rmse:8.27558
[319]	validation-rmse:8.27300
[320]	validation-rmse:8.27051
[321]	validation-rmse:8.26761
[322]	validation-rmse:8.26324
[323]	validation-rmse:8.26260
[324]	validation-rmse:8.26107
[325]	validation-rmse:8.25930
[326]	validation-rmse:8.25827
[327]	validation-rmse:8.25773
[328]	validation-rmse:8.25709
[329]	validation-rmse:8.25498
[330]	validation-rmse:8.25370
[331]	validation-rmse:8.25218
[332]	validation-rmse:8.24947
[333]	validation-rmse:8.24649
[334]	validation-rmse:8.24586
[335]	validation-rmse:8.24515
[336]	validation-rmse:8.24335
[337]	validation-rmse:8.24191
[338]	validation-rmse:8.23948
[339]	validation-rmse:8.23866
[340]	validation-rmse:8.23632
[341]	validation-rmse:8.23383
[342]	validation-rmse:8.23213
[343]	validation-rmse:8.22961
[344]	validation-rmse:8.22814
[345]	validation-rmse:8.22657
[346]	validation-rmse:8.22486
[347]	validation-rmse:8.22368
[348]	validation-rmse:8.22190
[349]	validation-rmse:8.22134
[350]	validation-rmse:8.22053
[351]	validation-rmse:8.21917
[352]	validation-rmse:8.21705
[353]	validation-rmse:8.21549
[354]	validation-rmse:8.20968
[355]	validation-rmse:8.20350
[356]	validation-rmse:8.20173
[357]	validation-rmse:8.20125
[358]	validation-rmse:8.19957
[359]	validation-rmse:8.19735
[360]	validation-rmse:8.19645
[361]	validation-rmse:8.19405
[362]	validation-rmse:8.19008
[363]	validation-rmse:8.18742
[364]	validation-rmse:8.18517
[365]	validation-rmse:8.18344
[366]	validation-rmse:8.18276
[367]	validation-rmse:8.18110
[368]	validation-rmse:8.18019
[369]	validation-rmse:8.17726
[370]	validation-rmse:8.17388
[371]	validation-rmse:8.17273
[372]	validation-rmse:8.17113
[373]	validation-rmse:8.17025
[374]	validation-rmse:8.16901
[375]	validation-rmse:8.16558
[376]	validation-rmse:8.16363
[377]	validation-rmse:8.16205
[378]	validation-rmse:8.16051
[379]	validation-rmse:8.15994
[380]	validation-rmse:8.15837
[381]	validation-rmse:8.15766
[382]	validation-rmse:8.15499
[383]	validation-rmse:8.15356
[384]	validation-rmse:8.15186
[385]	validation-rmse:8.14872
[386]	validation-rmse:8.14517
[387]	validation-rmse:8.14412
[388]	validation-rmse:8.14089
[389]	validation-rmse:8.13678
[390]	validation-rmse:8.13450
[391]	validation-rmse:8.13417
[392]	validation-rmse:8.13349
[393]	validation-rmse:8.13323
[394]	validation-rmse:8.13204
[395]	validation-rmse:8.13095
[396]	validation-rmse:8.12850
[397]	validation-rmse:8.12257
[398]	validation-rmse:8.12167
[399]	validation-rmse:8.12085
[400]	validation-rmse:8.11983
[401]	validation-rmse:8.11782
[402]	validation-rmse:8.11306
[403]	validation-rmse:8.11113
[404]	validation-rmse:8.10830
[405]	validation-rmse:8.10652
[406]	validation-rmse:8.10537
[407]	validation-rmse:8.10248
[408]	validation-rmse:8.09913
[409]	validation-rmse:8.09759
[410]	validation-rmse:8.09705
[411]	validation-rmse:8.09606
[412]	validation-rmse:8.09470
[413]	validation-rmse:8.09342
[414]	validation-rmse:8.08626
[415]	validation-rmse:8.08572
[416]	validation-rmse:8.08301
[417]	validation-rmse:8.08200
[418]	validation-rmse:8.07984
[419]	validation-rmse:8.07914
[420]	validation-rmse:8.07858
[421]	validation-rmse:8.07545
[422]	validation-rmse:8.07458
[423]	validation-rmse:8.07346
[424]	validation-rmse:8.07286
[425]	validation-rmse:8.07129
[426]	validation-rmse:8.06833
[427]	validation-rmse:8.06578
[428]	validation-rmse:8.06417
[429]	validation-rmse:8.06305
[430]	validation-rmse:8.06096
[431]	validation-rmse:8.06012
[432]	validation-rmse:8.05737
[433]	validation-rmse:8.05514
[434]	validation-rmse:8.05375
[435]	validation-rmse:8.05140
[436]	validation-rmse:8.04742
[437]	validation-rmse:8.04270
[438]	validation-rmse:8.04069
[439]	validation-rmse:8.03926
[440]	validation-rmse:8.03698
[441]	validation-rmse:8.03399
[442]	validation-rmse:8.03367
[443]	validation-rmse:8.03094
[444]	validation-rmse:8.03015
[445]	validation-rmse:8.02850
[446]	validation-rmse:8.02734
[447]	validation-rmse:8.02683
[448]	validation-rmse:8.02542
[449]	validation-rmse:8.02358
[450]	validation-rmse:8.02033
[451]	validation-rmse:8.01707
[452]	validation-rmse:8.01480
[453]	validation-rmse:8.01140
[454]	validation-rmse:8.01057
[455]	validation-rmse:8.00892
[456]	validation-rmse:8.00693
[457]	validation-rmse:8.00562
[458]	validation-rmse:8.00452
[459]	validation-rmse:8.00240
[460]	validation-rmse:8.00130
[461]	validation-rmse:7.99949
[462]	validation-rmse:7.99852
[463]	validation-rmse:7.99733
[464]	validation-rmse:7.99636
[465]	validation-rmse:7.99496
[466]	validation-rmse:7.99446
[467]	validation-rmse:7.99300
[468]	validation-rmse:7.99063
[469]	validation-rmse:7.98971
[470]	validation-rmse:7.98782
[471]	validation-rmse:7.98715
[472]	validation-rmse:7.98451
[473]	validation-rmse:7.98360
[474]	validation-rmse:7.98243
[475]	validation-rmse:7.98131
[476]	validation-rmse:7.97783
[477]	validation-rmse:7.97716
[478]	validation-rmse:7.97619
[479]	validation-rmse:7.97515
[480]	validation-rmse:7.97042
[481]	validation-rmse:7.96839
[482]	validation-rmse:7.96738
[483]	validation-rmse:7.96474
[484]	validation-rmse:7.96251
[485]	validation-rmse:7.96149
[486]	validation-rmse:7.96043
[487]	validation-rmse:7.95960
[488]	validation-rmse:7.95751
[489]	validation-rmse:7.95669
[490]	validation-rmse:7.95563
[491]	validation-rmse:7.95305
[492]	validation-rmse:7.95189
[493]	validation-rmse:7.95172
[494]	validation-rmse:7.95018
[495]	validation-rmse:7.94771
[496]	validation-rmse:7.94744
[497]	validation-rmse:7.94512
[498]	validation-rmse:7.94411
[499]	validation-rmse:7.94325
[500]	validation-rmse:7.94180
[501]	validation-rmse:7.94102
[502]	validation-rmse:7.94003
[503]	validation-rmse:7.93701
[504]	validation-rmse:7.93547
[505]	validation-rmse:7.93376
[506]	validation-rmse:7.93275
[507]	validation-rmse:7.93199
[508]	validation-rmse:7.93174
[509]	validation-rmse:7.93105
[510]	validation-rmse:7.92946
[511]	validation-rmse:7.92883
[512]	validation-rmse:7.92813
[513]	validation-rmse:7.92640
[514]	validation-rmse:7.92506
[515]	validation-rmse:7.92428
[516]	validation-rmse:7.92311
[517]	validation-rmse:7.92229
[518]	validation-rmse:7.92214
[519]	validation-rmse:7.92097
[520]	validation-rmse:7.92005
[521]	validation-rmse:7.91735
[522]	validation-rmse:7.91585
[523]	validation-rmse:7.91509
[524]	validation-rmse:7.91410
[525]	validation-rmse:7.91388
[526]	validation-rmse:7.91233
[527]	validation-rmse:7.91005
[528]	validation-rmse:7.90899
[529]	validation-rmse:7.90870
[530]	validation-rmse:7.90620
[531]	validation-rmse:7.90489
[532]	validation-rmse:7.90436
[533]	validation-rmse:7.90366
[534]	validation-rmse:7.90077
[535]	validation-rmse:7.90025
[536]	validation-rmse:7.89798
[537]	validation-rmse:7.89741
[538]	validation-rmse:7.89555
[539]	validation-rmse:7.89553
[540]	validation-rmse:7.89366
[541]	validation-rmse:7.89327
[542]	validation-rmse:7.89156
[543]	validation-rmse:7.88690
[544]	validation-rmse:7.88228
[545]	validation-rmse:7.87997
[546]	validation-rmse:7.87922
[547]	validation-rmse:7.87780
[548]	validation-rmse:7.87608
[549]	validation-rmse:7.87527
[550]	validation-rmse:7.87512
[551]	validation-rmse:7.87316
[552]	validation-rmse:7.87042
[553]	validation-rmse:7.86979
[554]	validation-rmse:7.86818
[555]	validation-rmse:7.86778
[556]	validation-rmse:7.86483
[557]	validation-rmse:7.86460
[558]	validation-rmse:7.86396
[559]	validation-rmse:7.86220
[560]	validation-rmse:7.86136
[561]	validation-rmse:7.86110
[562]	validation-rmse:7.86066
[563]	validation-rmse:7.86009
[564]	validation-rmse:7.85951
[565]	validation-rmse:7.85864
[566]	validation-rmse:7.85785
[567]	validation-rmse:7.85686
[568]	validation-rmse:7.85662
[569]	validation-rmse:7.85646
[570]	validation-rmse:7.85564
[571]	validation-rmse:7.85510
[572]	validation-rmse:7.85391
[573]	validation-rmse:7.85367
[574]	validation-rmse:7.85323
[575]	validation-rmse:7.85304
[576]	validation-rmse:7.85220
[577]	validation-rmse:7.85158
[578]	validation-rmse:7.85107
[579]	validation-rmse:7.85017
[580]	validation-rmse:7.84863
[581]	validation-rmse:7.84687
[582]	validation-rmse:7.84615
[583]	validation-rmse:7.84499
[584]	validation-rmse:7.84359
[585]	validation-rmse:7.84308
[586]	validation-rmse:7.84265
[587]	validation-rmse:7.84191
[588]	validation-rmse:7.84005
[589]	validation-rmse:7.83922
[590]	validation-rmse:7.83847
[591]	validation-rmse:7.83771
[592]	validation-rmse:7.83727
[593]	validation-rmse:7.83672
[594]	validation-rmse:7.83523
[595]	validation-rmse:7.83428
[596]	validation-rmse:7.83269
[597]	validation-rmse:7.83232
[598]	validation-rmse:7.83067
[599]	validation-rmse:7.82965
[600]	validation-rmse:7.82868
[601]	validation-rmse:7.82792
[602]	validation-rmse:7.82785
[603]	validation-rmse:7.82761
[604]	validation-rmse:7.82740
[605]	validation-rmse:7.82655
[606]	validation-rmse:7.82601
[607]	validation-rmse:7.82505
[608]	validation-rmse:7.82467
[609]	validation-rmse:7.82384
[610]	validation-rmse:7.82317
[611]	validation-rmse:7.82278
[612]	validation-rmse:7.82209
[613]	validation-rmse:7.82177
[614]	validation-rmse:7.82125
[615]	validation-rmse:7.82032
[616]	validation-rmse:7.81887
[617]	validation-rmse:7.81863
[618]	validation-rmse:7.81714
[619]	validation-rmse:7.81528
[620]	validation-rmse:7.81414
[621]	validation-rmse:7.81343
[622]	validation-rmse:7.81255
[623]	validation-rmse:7.81229
[624]	validation-rmse:7.81097
[625]	validation-rmse:7.81060
[626]	validation-rmse:7.80934
[627]	validation-rmse:7.80886
[628]	validation-rmse:7.80777
[629]	validation-rmse:7.80720
[630]	validation-rmse:7.80667
[631]	validation-rmse:7.80590
[632]	validation-rmse:7.80506
[633]	validation-rmse:7.80463
[634]	validation-rmse:7.80390
[635]	validation-rmse:7.80352
[636]	validation-rmse:7.80325
[637]	validation-rmse:7.80310
[638]	validation-rmse:7.80184
[639]	validation-rmse:7.80107
[640]	validation-rmse:7.80057
[641]	validation-rmse:7.80018
[642]	validation-rmse:7.80004
[643]	validation-rmse:7.79965
[644]	validation-rmse:7.79920
[645]	validation-rmse:7.79882
[646]	validation-rmse:7.79823
[647]	validation-rmse:7.79709
[648]	validation-rmse:7.79636
[649]	validation-rmse:7.79544
[650]	validation-rmse:7.79525
[651]	validation-rmse:7.79338
[652]	validation-rmse:7.79259
[653]	validation-rmse:7.79227
[654]	validation-rmse:7.79153
[655]	validation-rmse:7.79109
[656]	validation-rmse:7.78990
[657]	validation-rmse:7.78978
[658]	validation-rmse:7.78968
[659]	validation-rmse:7.78948
[660]	validation-rmse:7.78842
[661]	validation-rmse:7.78702
[662]	validation-rmse:7.78656
[663]	validation-rmse:7.78659
[664]	validation-rmse:7.78638
[665]	validation-rmse:7.78563
[666]	validation-rmse:7.78548
[667]	validation-rmse:7.78521
[668]	validation-rmse:7.78500
[669]	validation-rmse:7.78452

[12:39:21] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:19.49697
[2]	validation-rmse:18.73394
[3]	validation-rmse:18.02523
[4]	validation-rmse:17.35710
[5]	validation-rmse:16.73098
[6]	validation-rmse:16.16127
[7]	validation-rmse:15.63078
[8]	validation-rmse:15.12562
[9]	validation-rmse:14.66070
[10]	validation-rmse:14.23027
[11]	validation-rmse:13.84310
[12]	validation-rmse:13.47536
[13]	validation-rmse:13.14476
[14]	validation-rmse:12.83569
[15]	validation-rmse:12.54239
[16]	validation-rmse:12.27464
[17]	validation-rmse:12.02117
[18]	validation-rmse:11.80251
[19]	validation-rmse:11.58652
[20]	validation-rmse:11.38665
[21]	validation-rmse:11.21495
[22]	validation-rmse:11.05539
[23]	validation-rmse:10.89531
[24]	validation-rmse:10.75351
[25]	validation-rmse:10.63310
[26]	validation-rmse:10.52200
[27]	validation-rmse:10.41034
[28]	validation-rmse:10.31714
[29]	validation-rmse:10.21951
[30]	validation-rmse:10.12451
[31]	validation-rmse:10.01958
[32]	validation-rmse:9.92369
[33]	validation-rmse:9.86075
[34]	validation-rmse:9.79539
[35]	validation-rmse:9.73851
[36]	validation-rmse:9.68527
[37]	validation-rmse:9.61345
[38]	validation-rmse:9.57307
[39]	validation-rmse:9.51453
[40]	validation-rmse:9.46415
[41]	validation-rmse:9.42646
[42]	validation-rmse:9.39606
[43]	validation-rmse:9.36416
[44]	validation-rmse:9.33682
[45]	validation-rmse:9.28775
[46]	validation-rmse:9.24322
[47]	validation-rmse:9.21163
[48]	validation-rmse:9.18322
[49]	validation-rmse:9.15612
[50]	validation-rmse:9.13310
[51]	validation-rmse:9.11113
[52]	validation-rmse:9.09285
[53]	validation-rmse:9.07343
[54]	validation-rmse:9.05251
[55]	validation-rmse:9.02398
[56]	validation-rmse:9.00608
[57]	validation-rmse:8.98808
[58]	validation-rmse:8.97455
[59]	validation-rmse:8.96222
[60]	validation-rmse:8.94570
[61]	validation-rmse:8.93009
[62]	validation-rmse:8.91857
[63]	validation-rmse:8.89419
[64]	validation-rmse:8.88395
[65]	validation-rmse:8.86495
[66]	validation-rmse:8.85351
[67]	validation-rmse:8.84043
[68]	validation-rmse:8.83194
[69]	validation-rmse:8.81960
[70]	validation-rmse:8.81179
[71]	validation-rmse:8.80296
[72]	validation-rmse:8.78541
[73]	validation-rmse:8.77498
[74]	validation-rmse:8.75917
[75]	validation-rmse:8.75318
[76]	validation-rmse:8.74611
[77]	validation-rmse:8.73965
[78]	validation-rmse:8.72537
[79]	validation-rmse:8.71950
[80]	validation-rmse:8.71387
[81]	validation-rmse:8.70941
[82]	validation-rmse:8.69772
[83]	validation-rmse:8.68639
[84]	validation-rmse:8.67798
[85]	validation-rmse:8.66953
[86]	validation-rmse:8.66197
[87]	validation-rmse:8.65459
[88]	validation-rmse:8.64630
[89]	validation-rmse:8.64180
[90]	validation-rmse:8.63697
[91]	validation-rmse:8.62912
[92]	validation-rmse:8.62218
[93]	validation-rmse:8.61830
[94]	validation-rmse:8.61317
[95]	validation-rmse:8.60708
[96]	validation-rmse:8.60240
[97]	validation-rmse:8.59635
[98]	validation-rmse:8.58598
[99]	validation-rmse:8.57964
[100]	validation-rmse:8.57401
[101]	validation-rmse:8.56841
[102]	validation-rmse:8.56517
[103]	validation-rmse:8.56029
[104]	validation-rmse:8.55507
[105]	validation-rmse:8.55210
[106]	validation-rmse:8.54864
[107]	validation-rmse:8.54624
[108]	validation-rmse:8.54201
[109]	validation-rmse:8.53741
[110]	validation-rmse:8.53390
[111]	validation-rmse:8.53002
[112]	validation-rmse:8.52542
[113]	validation-rmse:8.51648
[114]	validation-rmse:8.51383
[115]	validation-rmse:8.51184
[116]	validation-rmse:8.50922
[117]	validation-rmse:8.50655
[118]	validation-rmse:8.50390
[119]	validation-rmse:8.50237
[120]	validation-rmse:8.49668
[121]	validation-rmse:8.49353
[122]	validation-rmse:8.49138
[123]	validation-rmse:8.48695
[124]	validation-rmse:8.48371
[125]	validation-rmse:8.47750
[126]	validation-rmse:8.47478
[127]	validation-rmse:8.47000
[128]	validation-rmse:8.46814
[129]	validation-rmse:8.46501
[130]	validation-rmse:8.46036
[131]	validation-rmse:8.45792
[132]	validation-rmse:8.45502
[133]	validation-rmse:8.45300
[134]	validation-rmse:8.44969
[135]	validation-rmse:8.44820
[136]	validation-rmse:8.44652
[137]	validation-rmse:8.44405
[138]	validation-rmse:8.44084
[139]	validation-rmse:8.43666
[140]	validation-rmse:8.43298
[141]	validation-rmse:8.43148
[142]	validation-rmse:8.43005
[143]	validation-rmse:8.42722
[144]	validation-rmse:8.42617
[145]	validation-rmse:8.42358
[146]	validation-rmse:8.42178
[147]	validation-rmse:8.42080
[148]	validation-rmse:8.41571
[149]	validation-rmse:8.41431
[150]	validation-rmse:8.41229
[151]	validation-rmse:8.40879
[152]	validation-rmse:8.40508
[153]	validation-rmse:8.40160
[154]	validation-rmse:8.39847
[155]	validation-rmse:8.39531
[156]	validation-rmse:8.39257
[157]	validation-rmse:8.38885
[158]	validation-rmse:8.38540
[159]	validation-rmse:8.38269
[160]	validation-rmse:8.37890
[161]	validation-rmse:8.37610
[162]	validation-rmse:8.37364
[163]	validation-rmse:8.37116
[164]	validation-rmse:8.36982
[165]	validation-rmse:8.36715
[166]	validation-rmse:8.36482
[167]	validation-rmse:8.36340
[168]	validation-rmse:8.36083
[169]	validation-rmse:8.35824
[170]	validation-rmse:8.35629
[171]	validation-rmse:8.35399
[172]	validation-rmse:8.35225
[173]	validation-rmse:8.35030
[174]	validation-rmse:8.34761
[175]	validation-rmse:8.34571
[176]	validation-rmse:8.34353
[177]	validation-rmse:8.34143
[178]	validation-rmse:8.34020
[179]	validation-rmse:8.33737
[180]	validation-rmse:8.33548
[181]	validation-rmse:8.33417
[182]	validation-rmse:8.33119
[183]	validation-rmse:8.32891
[184]	validation-rmse:8.32725
[185]	validation-rmse:8.32523
[186]	validation-rmse:8.32304
[187]	validation-rmse:8.32154
[188]	validation-rmse:8.31933
[189]	validation-rmse:8.31765
[190]	validation-rmse:8.31603
[191]	validation-rmse:8.31421
[192]	validation-rmse:8.31288
[193]	validation-rmse:8.31040
[194]	validation-rmse:8.30847
[195]	validation-rmse:8.30703
[196]	validation-rmse:8.30528
[197]	validation-rmse:8.30399
[198]	validation-rmse:8.30185
[199]	validation-rmse:8.30023
[200]	validation-rmse:8.29869
[201]	validation-rmse:8.29697
[202]	validation-rmse:8.29516
[203]	validation-rmse:8.29336
[204]	validation-rmse:8.29144
[205]	validation-rmse:8.28965
[206]	validation-rmse:8.28751
[207]	validation-rmse:8.28634
[208]	validation-rmse:8.28480
[209]	validation-rmse:8.28307
[210]	validation-rmse:8.28215
[211]	validation-rmse:8.28012
[212]	validation-rmse:8.27838
[213]	validation-rmse:8.27713
[214]	validation-rmse:8.27511
[215]	validation-rmse:8.27420
[216]	validation-rmse:8.27219
[217]	validation-rmse:8.27056
[218]	validation-rmse:8.26893
[219]	validation-rmse:8.26718
[220]	validation-rmse:8.26583
[221]	validation-rmse:8.26427
[222]	validation-rmse:8.26262
[223]	validation-rmse:8.26096
[224]	validation-rmse:8.25980
[225]	validation-rmse:8.25790
[226]	validation-rmse:8.25651
[227]	validation-rmse:8.25551
[228]	validation-rmse:8.25350
[229]	validation-rmse:8.25183
[230]	validation-rmse:8.25003
[231]	validation-rmse:8.24868
[232]	validation-rmse:8.24699
[233]	validation-rmse:8.24595
[234]	validation-rmse:8.24431
[235]	validation-rmse:8.24309
[236]	validation-rmse:8.24183
[237]	validation-rmse:8.24047
[238]	validation-rmse:8.23857
[239]	validation-rmse:8.23720
[240]	validation-rmse:8.23530
[241]	validation-rmse:8.23410
[242]	validation-rmse:8.23286
[243]	validation-rmse:8.23132
[244]	validation-rmse:8.22998
[245]	validation-rmse:8.22819
[246]	validation-rmse:8.22671
[247]	validation-rmse:8.22527
[248]	validation-rmse:8.22363
[249]	validation-rmse:8.22220
[250]	validation-rmse:8.22112
[251]	validation-rmse:8.21922
[252]	validation-rmse:8.21792
[253]	validation-rmse:8.21740
[254]	validation-rmse:8.21618
[255]	validation-rmse:8.21504
[256]	validation-rmse:8.21334
[257]	validation-rmse:8.21182
[258]	validation-rmse:8.21066
[259]	validation-rmse:8.20919
[260]	validation-rmse:8.20798
[261]	validation-rmse:8.20662
[262]	validation-rmse:8.20505
[263]	validation-rmse:8.20357
[264]	validation-rmse:8.20190
[265]	validation-rmse:8.20052
[266]	validation-rmse:8.19934
[267]	validation-rmse:8.19803
[268]	validation-rmse:8.19675
[269]	validation-rmse:8.19489
[270]	validation-rmse:8.19374
[271]	validation-rmse:8.19248
[272]	validation-rmse:8.19115
[273]	validation-rmse:8.18980
[274]	validation-rmse:8.18811
[275]	validation-rmse:8.18695
[276]	validation-rmse:8.18542
[277]	validation-rmse:8.18382
[278]	validation-rmse:8.18217
[279]	validation-rmse:8.18069
[280]	validation-rmse:8.17928
[281]	validation-rmse:8.17788
[282]	validation-rmse:8.17670
[283]	validation-rmse:8.17485
[284]	validation-rmse:8.17344
[285]	validation-rmse:8.17217
[286]	validation-rmse:8.17092
[287]	validation-rmse:8.17001
[288]	validation-rmse:8.16841
[289]	validation-rmse:8.16712
[290]	validation-rmse:8.16592
[291]	validation-rmse:8.16435
[292]	validation-rmse:8.16291
[293]	validation-rmse:8.16145
[294]	validation-rmse:8.16033
[295]	validation-rmse:8.15900
[296]	validation-rmse:8.15783
[297]	validation-rmse:8.15671
[298]	validation-rmse:8.15563
[299]	validation-rmse:8.15445
[300]	validation-rmse:8.15301
[301]	validation-rmse:8.15184
[302]	validation-rmse:8.15093
[303]	validation-rmse:8.14939
[304]	validation-rmse:8.14841
[305]	validation-rmse:8.14703
[306]	validation-rmse:8.14580
[307]	validation-rmse:8.14457
[308]	validation-rmse:8.14291
[309]	validation-rmse:8.14171
[310]	validation-rmse:8.13998
[311]	validation-rmse:8.13897
[312]	validation-rmse:8.13777
[313]	validation-rmse:8.13649
[314]	validation-rmse:8.13545
[315]	validation-rmse:8.13375
[316]	validation-rmse:8.13277
[317]	validation-rmse:8.13187
[318]	validation-rmse:8.13050
[319]	validation-rmse:8.12915
[320]	validation-rmse:8.12780
[321]	validation-rmse:8.12639
[322]	validation-rmse:8.12505
[323]	validation-rmse:8.12379
[324]	validation-rmse:8.12278
[325]	validation-rmse:8.12152
[326]	validation-rmse:8.11980
[327]	validation-rmse:8.11843
[328]	validation-rmse:8.11731
[329]	validation-rmse:8.11608
[330]	validation-rmse:8.11495
[331]	validation-rmse:8.11381
[332]	validation-rmse:8.11254
[333]	validation-rmse:8.11145
[334]	validation-rmse:8.11039
[335]	validation-rmse:8.10896
[336]	validation-rmse:8.10780
[337]	validation-rmse:8.10673
[338]	validation-rmse:8.10523
[339]	validation-rmse:8.10414
[340]	validation-rmse:8.10307
[341]	validation-rmse:8.10200
[342]	validation-rmse:8.10104
[343]	validation-rmse:8.09935
[344]	validation-rmse:8.09832
[345]	validation-rmse:8.09714
[346]	validation-rmse:8.09621
[347]	validation-rmse:8.09512
[348]	validation-rmse:8.09394
[349]	validation-rmse:8.09281
[350]	validation-rmse:8.09160
[351]	validation-rmse:8.09068
[352]	validation-rmse:8.08977
[353]	validation-rmse:8.08866
[354]	validation-rmse:8.08711
[355]	validation-rmse:8.08614
[356]	validation-rmse:8.08515
[357]	validation-rmse:8.08401
[358]	validation-rmse:8.08321
[359]	validation-rmse:8.08238
[360]	validation-rmse:8.08144
[361]	validation-rmse:8.08038
[362]	validation-rmse:8.07950
[363]	validation-rmse:8.07854
[364]	validation-rmse:8.07725
[365]	validation-rmse:8.07635
[366]	validation-rmse:8.07522
[367]	validation-rmse:8.07442
[368]	validation-rmse:8.07340
[369]	validation-rmse:8.07272
[370]	validation-rmse:8.07189
[371]	validation-rmse:8.07084
[372]	validation-rmse:8.06999
[373]	validation-rmse:8.06900
[374]	validation-rmse:8.06806
[375]	validation-rmse:8.06707
[376]	validation-rmse:8.06649
[377]	validation-rmse:8.06536
[378]	validation-rmse:8.06472
[379]	validation-rmse:8.06378
[380]	validation-rmse:8.06277
[381]	validation-rmse:8.06209
[382]	validation-rmse:8.06153
[383]	validation-rmse:8.06074
[384]	validation-rmse:8.05965
[385]	validation-rmse:8.05858
[386]	validation-rmse:8.05789
[387]	validation-rmse:8.05696
[388]	validation-rmse:8.05607
[389]	validation-rmse:8.05519
[390]	validation-rmse:8.05423
[391]	validation-rmse:8.05340
[392]	validation-rmse:8.05257
[393]	validation-rmse:8.05189
[394]	validation-rmse:8.05110
[395]	validation-rmse:8.05013
[396]	validation-rmse:8.04834
[397]	validation-rmse:8.04748
[398]	validation-rmse:8.04679
[399]	validation-rmse:8.04607
[400]	validation-rmse:8.04494
[401]	validation-rmse:8.04443
[402]	validation-rmse:8.04369
[403]	validation-rmse:8.04265
[404]	validation-rmse:8.04142
[405]	validation-rmse:8.04081
[406]	validation-rmse:8.04047
[407]	validation-rmse:8.03988
[408]	validation-rmse:8.03913
[409]	validation-rmse:8.03834
[410]	validation-rmse:8.03642
[411]	validation-rmse:8.03526
[412]	validation-rmse:8.03447
[413]	validation-rmse:8.03301
[414]	validation-rmse:8.03191
[415]	validation-rmse:8.03120
[416]	validation-rmse:8.02836
[417]	validation-rmse:8.02752
[418]	validation-rmse:8.02608
[419]	validation-rmse:8.02540
[420]	validation-rmse:8.02477
[421]	validation-rmse:8.02409
[422]	validation-rmse:8.02349
[423]	validation-rmse:8.02288
[424]	validation-rmse:8.02184
[425]	validation-rmse:8.02105
[426]	validation-rmse:8.02034
[427]	validation-rmse:8.01993
[428]	validation-rmse:8.01918
[429]	validation-rmse:8.01869
[430]	validation-rmse:8.01812
[431]	validation-rmse:8.01627
[432]	validation-rmse:8.01485
[433]	validation-rmse:8.01398
[434]	validation-rmse:8.01315
[435]	validation-rmse:8.01263
[436]	validation-rmse:8.01093
[437]	validation-rmse:8.01052
[438]	validation-rmse:8.01002
[439]	validation-rmse:8.00934
[440]	validation-rmse:8.00842
[441]	validation-rmse:8.00772
[442]	validation-rmse:8.00688
[443]	validation-rmse:8.00562
[444]	validation-rmse:8.00399
[445]	validation-rmse:8.00347
[446]	validation-rmse:8.00253
[447]	validation-rmse:8.00104
[448]	validation-rmse:8.00006
[449]	validation-rmse:7.99911
[450]	validation-rmse:7.99857
[451]	validation-rmse:7.99790
[452]	validation-rmse:7.99660
[453]	validation-rmse:7.99603
[454]	validation-rmse:7.99456
[455]	validation-rmse:7.99403
[456]	validation-rmse:7.99283
[457]	validation-rmse:7.99225
[458]	validation-rmse:7.99177
[459]	validation-rmse:7.99144
[460]	validation-rmse:7.99041
[461]	validation-rmse:7.98971
[462]	validation-rmse:7.98914
[463]	validation-rmse:7.98824
[464]	validation-rmse:7.98672
[465]	validation-rmse:7.98606
[466]	validation-rmse:7.98535
[467]	validation-rmse:7.98433
[468]	validation-rmse:7.98361
[469]	validation-rmse:7.98295
[470]	validation-rmse:7.98218
[471]	validation-rmse:7.98122
[472]	validation-rmse:7.98013
[473]	validation-rmse:7.97927
[474]	validation-rmse:7.97830
[475]	validation-rmse:7.97736
[476]	validation-rmse:7.97670
[477]	validation-rmse:7.97619
[478]	validation-rmse:7.97522
[479]	validation-rmse:7.97415
[480]	validation-rmse:7.97321
[481]	validation-rmse:7.97234
[482]	validation-rmse:7.97143
[483]	validation-rmse:7.97043
[484]	validation-rmse:7.96941
[485]	validation-rmse:7.96846
[486]	validation-rmse:7.96778
[487]	validation-rmse:7.96733
[488]	validation-rmse:7.96672
[489]	validation-rmse:7.96597
[490]	validation-rmse:7.96521
[491]	validation-rmse:7.96448
[492]	validation-rmse:7.96384
[493]	validation-rmse:7.96313
[494]	validation-rmse:7.96218
[495]	validation-rmse:7.96152
[496]	validation-rmse:7.96105
[497]	validation-rmse:7.96028
[498]	validation-rmse:7.95927
[499]	validation-rmse:7.95850
[500]	validation-rmse:7.95794
[501]	validation-rmse:7.95748
[502]	validation-rmse:7.95675
[503]	validation-rmse:7.95602
[504]	validation-rmse:7.95514
[505]	validation-rmse:7.95463
[506]	validation-rmse:7.95405
[507]	validation-rmse:7.95344
[508]	validation-rmse:7.95234
[509]	validation-rmse:7.95197
[510]	validation-rmse:7.95104
[511]	validation-rmse:7.95019
[512]	validation-rmse:7.94943
[513]	validation-rmse:7.94837
[514]	validation-rmse:7.94758
[515]	validation-rmse:7.94696
[516]	validation-rmse:7.94657
[517]	validation-rmse:7.94582
[518]	validation-rmse:7.94522
[519]	validation-rmse:7.94438
[520]	validation-rmse:7.94372
[521]	validation-rmse:7.94281
[522]	validation-rmse:7.94206
[523]	validation-rmse:7.94150
[524]	validation-rmse:7.94084
[525]	validation-rmse:7.93978
[526]	validation-rmse:7.93915
[527]	validation-rmse:7.93859
[528]	validation-rmse:7.93791
[529]	validation-rmse:7.93706
[530]	validation-rmse:7.93652
[531]	validation-rmse:7.93587
[532]	validation-rmse:7.93532
[533]	validation-rmse:7.93448
[534]	validation-rmse:7.93379
[535]	validation-rmse:7.93314
[536]	validation-rmse:7.93255
[537]	validation-rmse:7.93166
[538]	validation-rmse:7.93112
[539]	validation-rmse:7.93065
[540]	validation-rmse:7.93001
[541]	validation-rmse:7.92954
[542]	validation-rmse:7.92913
[543]	validation-rmse:7.92875
[544]	validation-rmse:7.92827
[545]	validation-rmse:7.92768
[546]	validation-rmse:7.92693
[547]	validation-rmse:7.92641
[548]	validation-rmse:7.92596
[549]	validation-rmse:7.92535
[550]	validation-rmse:7.92491
[551]	validation-rmse:7.92422
[552]	validation-rmse:7.92373
[553]	validation-rmse:7.92339
[554]	validation-rmse:7.92262
[555]	validation-rmse:7.92189
[556]	validation-rmse:7.92137
[557]	validation-rmse:7.92106
[558]	validation-rmse:7.92040
[559]	validation-rmse:7.91997
[560]	validation-rmse:7.91939
[561]	validation-rmse:7.91890
[562]	validation-rmse:7.91829
[563]	validation-rmse:7.91792
[564]	validation-rmse:7.91751
[565]	validation-rmse:7.91715
[566]	validation-rmse:7.91670
[567]	validation-rmse:7.91617
[568]	validation-rmse:7.91557
[569]	validation-rmse:7.91513
[570]	validation-rmse:7.91450
[571]	validation-rmse:7.91379
[572]	validation-rmse:7.91337
[573]	validation-rmse:7.91297
[574]	validation-rmse:7.91244
[575]	validation-rmse:7.91222
[576]	validation-rmse:7.91154
[577]	validation-rmse:7.91121
[578]	validation-rmse:7.91073
[579]	validation-rmse:7.91044
[580]	validation-rmse:7.90976
[581]	validation-rmse:7.90942
[582]	validation-rmse:7.90897
[583]	validation-rmse:7.90852
[584]	validation-rmse:7.90827
[585]	validation-rmse:7.90779
[586]	validation-rmse:7.90730
[587]	validation-rmse:7.90651
[588]	validation-rmse:7.90600
[589]	validation-rmse:7.90539
[590]	validation-rmse:7.90462
[591]	validation-rmse:7.90394
[592]	validation-rmse:7.90336
[593]	validation-rmse:7.90296
[594]	validation-rmse:7.90263
[595]	validation-rmse:7.90219
[596]	validation-rmse:7.90152
[597]	validation-rmse:7.90105
[598]	validation-rmse:7.90070
[599]	validation-rmse:7.90030
[600]	validation-rmse:7.89996
[601]	validation-rmse:7.89986
[602]	validation-rmse:7.89927
[603]	validation-rmse:7.89859
[604]	validation-rmse:7.89833
[605]	validation-rmse:7.89799
[606]	validation-rmse:7.89763
[607]	validation-rmse:7.89723
[608]	validation-rmse:7.89677
[609]	validation-rmse:7.89630
[610]	validation-rmse:7.89553
[611]	validation-rmse:7.89506
[612]	validation-rmse:7.89434
[613]	validation-rmse:7.89382
[614]	validation-rmse:7.89330
[615]	validation-rmse:7.89284
[616]	validation-rmse:7.89268
[617]	validation-rmse:7.89228
[618]	validation-rmse:7.89203
[619]	validation-rmse:7.89175
[620]	validation-rmse:7.89147
[621]	validation-rmse:7.89110
[622]	validation-rmse:7.89060
[623]	validation-rmse:7.89032
[624]	validation-rmse:7.89006
[625]	validation-rmse:7.88968
[626]	validation-rmse:7.88899
[627]	validation-rmse:7.88857
[628]	validation-rmse:7.88817
[629]	validation-rmse:7.88773
[630]	validation-rmse:7.88715
[631]	validation-rmse:7.88692
[632]	validation-rmse:7.88667
[633]	validation-rmse:7.88611
[634]	validation-rmse:7.88555
[635]	validation-rmse:7.88511
[636]	validation-rmse:7.88465
[637]	validation-rmse:7.88410
[638]	validation-rmse:7.88358
[639]	validation-rmse:7.88329
[640]	validation-rmse:7.88300
[641]	validation-rmse:7.88271
[642]	validation-rmse:7.88226
[643]	validation-rmse:7.88168
[644]	validation-rmse:7.88128
[645]	validation-rmse:7.88080
[646]	validation-rmse:7.88031
[647]	validation-rmse:7.87989
[648]	validation-rmse:7.87942
[649]	validation-rmse:7.87904
[650]	validation-rmse:7.87861
[651]	validation-rmse:7.87841
[652]	validation-rmse:7.87792
[653]	validation-rmse:7.87743
[654]	validation-rmse:7.87676
[655]	validation-rmse:7.87639
[656]	validation-rmse:7.87580
[657]	validation-rmse:7.87546
[658]	validation-rmse:7.87487
[659]	validation-rmse:7.87446
[660]	validation-rmse:7.87423
[661]	validation-rmse:7.87397
[662]	validation-rmse:7.87359
[663]	validation-rmse:7.87312
[664]	validation-rmse:7.87237
[665]	validation-rmse:7.87219
[666]	validation-rmse:7.87179
[667]	validation-rmse:7.87131
[668]	validation-rmse:7.87061
[669]	validation-rmse:7.87032

[12:43:55] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:15.89167
[2]	validation-rmse:14.18209
[3]	validation-rmse:12.87772
[4]	validation-rmse:11.94065
[5]	validation-rmse:11.28048
[6]	validation-rmse:10.75429
[7]	validation-rmse:10.39331
[8]	validation-rmse:10.13571
[9]	validation-rmse:9.82530
[10]	validation-rmse:9.67467
[11]	validation-rmse:9.55129
[12]	validation-rmse:9.44586
[13]	validation-rmse:9.33131
[14]	validation-rmse:9.21795
[15]	validation-rmse:9.16584
[16]	validation-rmse:9.08437
[17]	validation-rmse:9.02638
[18]	validation-rmse:8.97230
[19]	validation-rmse:8.85891
[20]	validation-rmse:8.81149
[21]	validation-rmse:8.78538
[22]	validation-rmse:8.76024
[23]	validation-rmse:8.69483
[24]	validation-rmse:8.66770
[25]	validation-rmse:8.63086
[26]	validation-rmse:8.55711
[27]	validation-rmse:8.51713
[28]	validation-rmse:8.48064
[29]	validation-rmse:8.46151
[30]	validation-rmse:8.42263
[31]	validation-rmse:8.39496
[32]	validation-rmse:8.36111
[33]	validation-rmse:8.34468
[34]	validation-rmse:8.31036
[35]	validation-rmse:8.29220
[36]	validation-rmse:8.26894
[37]	validation-rmse:8.22959
[38]	validation-rmse:8.21132
[39]	validation-rmse:8.16690
[40]	validation-rmse:8.16110
[41]	validation-rmse:8.14136
[42]	validation-rmse:8.11949
[43]	validation-rmse:8.10017
[44]	validation-rmse:8.08161
[45]	validation-rmse:8.06797
[46]	validation-rmse:8.04994
[47]	validation-rmse:8.02415
[48]	validation-rmse:8.00900
[49]	validation-rmse:7.99118
[50]	validation-rmse:7.97957
[51]	validation-rmse:7.97016
[52]	validation-rmse:7.96292
[53]	validation-rmse:7.94748
[54]	validation-rmse:7.92944
[55]	validation-rmse:7.91207
[56]	validation-rmse:7.86126
[57]	validation-rmse:7.84474
[58]	validation-rmse:7.82559
[59]	validation-rmse:7.81388
[60]	validation-rmse:7.80750
[61]	validation-rmse:7.80398
[62]	validation-rmse:7.78836
[63]	validation-rmse:7.78351
[64]	validation-rmse:7.76907
[65]	validation-rmse:7.76316
[66]	validation-rmse:7.74975
[67]	validation-rmse:7.74363
[68]	validation-rmse:7.74049
[69]	validation-rmse:7.73712
[70]	validation-rmse:7.73523
[71]	validation-rmse:7.72029
[72]	validation-rmse:7.71256
[73]	validation-rmse:7.70420
[74]	validation-rmse:7.69746
[75]	validation-rmse:7.69316
[76]	validation-rmse:7.68458
[77]	validation-rmse:7.67069
[78]	validation-rmse:7.66281
[79]	validation-rmse:7.65897
[80]	validation-rmse:7.65261
[81]	validation-rmse:7.64959
[82]	validation-rmse:7.64288
[83]	validation-rmse:7.63858
[84]	validation-rmse:7.63404
[85]	validation-rmse:7.63081
[86]	validation-rmse:7.60470
[87]	validation-rmse:7.60309
[88]	validation-rmse:7.59733
[89]	validation-rmse:7.59590
[90]	validation-rmse:7.59197
[91]	validation-rmse:7.58769
[92]	validation-rmse:7.58114
[93]	validation-rmse:7.57863
[94]	validation-rmse:7.57640
[95]	validation-rmse:7.57237
[96]	validation-rmse:7.57055
[97]	validation-rmse:7.56058
[98]	validation-rmse:7.55971
[99]	validation-rmse:7.55881
[100]	validation-rmse:7.54937
[101]	validation-rmse:7.54636
[102]	validation-rmse:7.53726
[103]	validation-rmse:7.53460
[104]	validation-rmse:7.53224
[105]	validation-rmse:7.52677
[106]	validation-rmse:7.52449
[107]	validation-rmse:7.52053
[108]	validation-rmse:7.52035
[109]	validation-rmse:7.51812
[110]	validation-rmse:7.51560
[111]	validation-rmse:7.50955
[112]	validation-rmse:7.50740
[113]	validation-rmse:7.50680
[114]	validation-rmse:7.50645
[115]	validation-rmse:7.50600
[116]	validation-rmse:7.50575
[117]	validation-rmse:7.50453
[118]	validation-rmse:7.50391
[119]	validation-rmse:7.49939
[120]	validation-rmse:7.49827
[121]	validation-rmse:7.49709
[122]	validation-rmse:7.49571
[123]	validation-rmse:7.48804
[124]	validation-rmse:7.48763
[125]	validation-rmse:7.48676
[126]	validation-rmse:7.48604
[127]	validation-rmse:7.48617
[128]	validation-rmse:7.48568
[129]	validation-rmse:7.48389
[130]	validation-rmse:7.48131
[131]	validation-rmse:7.48118
[132]	validation-rmse:7.48004
[133]	validation-rmse:7.47851
[134]	validation-rmse:7.47791
[135]	validation-rmse:7.47373
[136]	validation-rmse:7.47370
[137]	validation-rmse:7.47294
[138]	validation-rmse:7.47293
[139]	validation-rmse:7.47334
[140]	validation-rmse:7.47175
[141]	validation-rmse:7.47137
[142]	validation-rmse:7.47022
[143]	validation-rmse:7.46838
[144]	validation-rmse:7.46856
[145]	validation-rmse:7.46686
[146]	validation-rmse:7.46602
[147]	validation-rmse:7.46473
[148]	validation-rmse:7.46380
[149]	validation-rmse:7.46326
[150]	validation-rmse:7.46093
[151]	validation-rmse:7.45924
[152]	validation-rmse:7.45921
[153]	validation-rmse:7.45763
[154]	validation-rmse:7.45743
[155]	validation-rmse:7.45623
[156]	validation-rmse:7.45589
[157]	validation-rmse:7.45547
[158]	validation-rmse:7.45529
[159]	validation-rmse:7.45504
[160]	validation-rmse:7.45509
[161]	validation-rmse:7.45429
[162]	validation-rmse:7.45412
[163]	validation-rmse:7.45361
[164]	validation-rmse:7.45268
[165]	validation-rmse:7.45188
[166]	validation-rmse:7.45113
[167]	validation-rmse:7.45091
[168]	validation-rmse:7.45063
[169]	validation-rmse:7.45055
[170]	validation-rmse:7.45046
[171]	validation-rmse:7.45019
[172]	validation-rmse:7.44955
[173]	validation-rmse:7.44956
[174]	validation-rmse:7.44909
[175]	validation-rmse:7.44727
[176]	validation-rmse:7.44723
[177]	validation-rmse:7.44671
[178]	validation-rmse:7.44592
[179]	validation-rmse:7.44532
[180]	validation-rmse:7.44529
[181]	validation-rmse:7.44474
[182]	validation-rmse:7.44405
[183]	validation-rmse:7.44338
[184]	validation-rmse:7.44225
[185]	validation-rmse:7.44172
[186]	validation-rmse:7.44181
[187]	validation-rmse:7.44166
[188]	validation-rmse:7.44058
[189]	validation-rmse:7.44013
[190]	validation-rmse:7.44008
[191]	validation-rmse:7.44003
[192]	validation-rmse:7.43955
[193]	validation-rmse:7.43827
[194]	validation-rmse:7.43798
[195]	validation-rmse:7.43757
[196]	validation-rmse:7.43769
[197]	validation-rmse:7.43772
[198]	validation-rmse:7.43741
[199]	validation-rmse:7.43685
[200]	validation-rmse:7.43663
[201]	validation-rmse:7.43593
[202]	validation-rmse:7.43521
[203]	validation-rmse:7.43482
[204]	validation-rmse:7.43495
[205]	validation-rmse:7.43415
[206]	validation-rmse:7.43321
[207]	validation-rmse:7.43231
[208]	validation-rmse:7.43243
[209]	validation-rmse:7.43181
[210]	validation-rmse:7.43095
[211]	validation-rmse:7.43062
[212]	validation-rmse:7.43098
[213]	validation-rmse:7.43086
[214]	validation-rmse:7.43086
[215]	validation-rmse:7.43083
[216]	validation-rmse:7.43090
[217]	validation-rmse:7.43102
[218]	validation-rmse:7.43096
[219]	validation-rmse:7.43094
[220]	validation-rmse:7.43050
[221]	validation-rmse:7.42933
[222]	validation-rmse:7.42879
[223]	validation-rmse:7.42752
[224]	validation-rmse:7.42718
[225]	validation-rmse:7.42710
[226]	validation-rmse:7.42753
[227]	validation-rmse:7.42771
[228]	validation-rmse:7.42758
[229]	validation-rmse:7.42674
[230]	validation-rmse:7.42658
[231]	validation-rmse:7.42635
[232]	validation-rmse:7.42622
[233]	validation-rmse:7.42556
[234]	validation-rmse:7.42525
[235]	validation-rmse:7.42464
[236]	validation-rmse:7.42443
[237]	validation-rmse:7.42521
[238]	validation-rmse:7.42515
[239]	validation-rmse:7.42440
[240]	validation-rmse:7.42405
[241]	validation-rmse:7.42403
[242]	validation-rmse:7.42417
[243]	validation-rmse:7.42380
[244]	validation-rmse:7.42355
[245]	validation-rmse:7.42329
[246]	validation-rmse:7.42324
[247]	validation-rmse:7.42254
[248]	validation-rmse:7.42251
[249]	validation-rmse:7.42240
[250]	validation-rmse:7.42268
[251]	validation-rmse:7.42261
[252]	validation-rmse:7.42210
[253]	validation-rmse:7.42158
[254]	validation-rmse:7.42094
[255]	validation-rmse:7.42073
[256]	validation-rmse:7.42092
[257]	validation-rmse:7.42061
[258]	validation-rmse:7.41952
[259]	validation-rmse:7.41920
[260]	validation-rmse:7.41901
[261]	validation-rmse:7.41880
[262]	validation-rmse:7.41844
[263]	validation-rmse:7.41857
[264]	validation-rmse:7.41860
[265]	validation-rmse:7.41875
[266]	validation-rmse:7.41798
[267]	validation-rmse:7.41847
[268]	validation-rmse:7.41834
[269]	validation-rmse:7.41885
[270]	validation-rmse:7.41824
[271]	validation-rmse:7.41790
[272]	validation-rmse:7.41781
[273]	validation-rmse:7.41679
[274]	validation-rmse:7.41666
[275]	validation-rmse:7.41628
[276]	validation-rmse:7.41593
[277]	validation-rmse:7.41529
[278]	validation-rmse:7.41480
[279]	validation-rmse:7.41418
[280]	validation-rmse:7.41429
[281]	validation-rmse:7.41346
[282]	validation-rmse:7.41278
[283]	validation-rmse:7.41208
[284]	validation-rmse:7.41209
[285]	validation-rmse:7.41181
[286]	validation-rmse:7.41169
[287]	validation-rmse:7.41108
[288]	validation-rmse:7.41060
[289]	validation-rmse:7.41036
[290]	validation-rmse:7.41050
[291]	validation-rmse:7.41034
[292]	validation-rmse:7.40988
[293]	validation-rmse:7.40978
[294]	validation-rmse:7.40935
[295]	validation-rmse:7.40890
[296]	validation-rmse:7.40845
[297]	validation-rmse:7.40814
[298]	validation-rmse:7.40786
[299]	validation-rmse:7.40772
[300]	validation-rmse:7.40750
[301]	validation-rmse:7.40731
[302]	validation-rmse:7.40709
[303]	validation-rmse:7.40716
[304]	validation-rmse:7.40693
[305]	validation-rmse:7.40646
[306]	validation-rmse:7.40602
[307]	validation-rmse:7.40597
[308]	validation-rmse:7.40554
[309]	validation-rmse:7.40554
[310]	validation-rmse:7.40544
[311]	validation-rmse:7.40545
[312]	validation-rmse:7.40531
[313]	validation-rmse:7.40508
[314]	validation-rmse:7.40482
[315]	validation-rmse:7.40504
[316]	validation-rmse:7.40501
[317]	validation-rmse:7.40467
[318]	validation-rmse:7.40417
[319]	validation-rmse:7.40385
[320]	validation-rmse:7.40346
[321]	validation-rmse:7.40294
[322]	validation-rmse:7.40272
[323]	validation-rmse:7.40250
[324]	validation-rmse:7.40240
[325]	validation-rmse:7.40195
[326]	validation-rmse:7.40162
[327]	validation-rmse:7.40109
[328]	validation-rmse:7.40144
[329]	validation-rmse:7.40101
[330]	validation-rmse:7.40090
[331]	validation-rmse:7.40037
[332]	validation-rmse:7.39983
[333]	validation-rmse:7.39968
[334]	validation-rmse:7.39961
[335]	validation-rmse:7.39982
[336]	validation-rmse:7.39953
[337]	validation-rmse:7.39971
[338]	validation-rmse:7.39953
[339]	validation-rmse:7.39966
[340]	validation-rmse:7.39912
[341]	validation-rmse:7.39854
[342]	validation-rmse:7.39821
[343]	validation-rmse:7.39777
[344]	validation-rmse:7.39781
[345]	validation-rmse:7.39725
[346]	validation-rmse:7.39731
[347]	validation-rmse:7.39721
[348]	validation-rmse:7.39750
[349]	validation-rmse:7.39729
[350]	validation-rmse:7.39724
[351]	validation-rmse:7.39673
[352]	validation-rmse:7.39599
[353]	validation-rmse:7.39605
[354]	validation-rmse:7.39599
[355]	validation-rmse:7.39602
[356]	validation-rmse:7.39576
[357]	validation-rmse:7.39539
[358]	validation-rmse:7.39499
[359]	validation-rmse:7.39493
[360]	validation-rmse:7.39467
[361]	validation-rmse:7.39427
[362]	validation-rmse:7.39411
[363]	validation-rmse:7.39400
[364]	validation-rmse:7.39395
[365]	validation-rmse:7.39392
[366]	validation-rmse:7.39395
[367]	validation-rmse:7.39335
[368]	validation-rmse:7.39333
[369]	validation-rmse:7.39360
[370]	validation-rmse:7.39299
[371]	validation-rmse:7.39297
[372]	validation-rmse:7.39290
[373]	validation-rmse:7.39284
[374]	validation-rmse:7.39255
[375]	validation-rmse:7.39254
[376]	validation-rmse:7.39216
[377]	validation-rmse:7.39186
[378]	validation-rmse:7.39190
[379]	validation-rmse:7.39203
[380]	validation-rmse:7.39166
[381]	validation-rmse:7.39155
[382]	validation-rmse:7.39131
[383]	validation-rmse:7.39129
[384]	validation-rmse:7.39144
[385]	validation-rmse:7.39138
[386]	validation-rmse:7.39137
[387]	validation-rmse:7.39146
[388]	validation-rmse:7.39106
[389]	validation-rmse:7.39113
[390]	validation-rmse:7.39096
[391]	validation-rmse:7.39050
[392]	validation-rmse:7.39045
[393]	validation-rmse:7.39043
[394]	validation-rmse:7.38970
[395]	validation-rmse:7.38947
[396]	validation-rmse:7.38942
[397]	validation-rmse:7.38938
[398]	validation-rmse:7.38968
[399]	validation-rmse:7.38977
[400]	validation-rmse:7.38950
[401]	validation-rmse:7.38913
[402]	validation-rmse:7.38885
[403]	validation-rmse:7.38829
[404]	validation-rmse:7.38787
[405]	validation-rmse:7.38794
[406]	validation-rmse:7.38799
[407]	validation-rmse:7.38747
[408]	validation-rmse:7.38738
[409]	validation-rmse:7.38714
[410]	validation-rmse:7.38682
[411]	validation-rmse:7.38676
[412]	validation-rmse:7.38693
[413]	validation-rmse:7.38661
[414]	validation-rmse:7.38672
[415]	validation-rmse:7.38682
[416]	validation-rmse:7.38694
[417]	validation-rmse:7.38627
[418]	validation-rmse:7.38633
[419]	validation-rmse:7.38598
[420]	validation-rmse:7.38577
[421]	validation-rmse:7.38545
[422]	validation-rmse:7.38511
[423]	validation-rmse:7.38477
[424]	validation-rmse:7.38419
[425]	validation-rmse:7.38423
[426]	validation-rmse:7.38402
[427]	validation-rmse:7.38398
[428]	validation-rmse:7.38400
[429]	validation-rmse:7.38396
[430]	validation-rmse:7.38371
[431]	validation-rmse:7.38375
[432]	validation-rmse:7.38353
[433]	validation-rmse:7.38330
[434]	validation-rmse:7.38341
[435]	validation-rmse:7.38338
[436]	validation-rmse:7.38300
[437]	validation-rmse:7.38235
[438]	validation-rmse:7.38231
[439]	validation-rmse:7.38248
[440]	validation-rmse:7.38247
[441]	validation-rmse:7.38287
[442]	validation-rmse:7.38285
[443]	validation-rmse:7.38266
[444]	validation-rmse:7.38224
[445]	validation-rmse:7.38214
[446]	validation-rmse:7.38234
[447]	validation-rmse:7.38228
[448]	validation-rmse:7.38207
[449]	validation-rmse:7.38243
[450]	validation-rmse:7.38242
[451]	validation-rmse:7.38233
[452]	validation-rmse:7.38225
[453]	validation-rmse:7.38137
[454]	validation-rmse:7.38139
[455]	validation-rmse:7.38095
[456]	validation-rmse:7.38088
[457]	validation-rmse:7.38070
[458]	validation-rmse:7.38057
[459]	validation-rmse:7.38027
[460]	validation-rmse:7.38017
[461]	validation-rmse:7.37991
[462]	validation-rmse:7.37970
[463]	validation-rmse:7.37963
[464]	validation-rmse:7.37949
[465]	validation-rmse:7.37919
[466]	validation-rmse:7.37904
[467]	validation-rmse:7.37911
[468]	validation-rmse:7.37885
[469]	validation-rmse:7.37855
[470]	validation-rmse:7.37794
[471]	validation-rmse:7.37781
[472]	validation-rmse:7.37776
[473]	validation-rmse:7.37743
[474]	validation-rmse:7.37733
[475]	validation-rmse:7.37728
[476]	validation-rmse:7.37725
[477]	validation-rmse:7.37685
[478]	validation-rmse:7.37656
[479]	validation-rmse:7.37680
[480]	validation-rmse:7.37700
[481]	validation-rmse:7.37664
[482]	validation-rmse:7.37645
[483]	validation-rmse:7.37644
[484]	validation-rmse:7.37590
[485]	validation-rmse:7.37592
[486]	validation-rmse:7.37554
[487]	validation-rmse:7.37575
[488]	validation-rmse:7.37607
[489]	validation-rmse:7.37596
[490]	validation-rmse:7.37570
[491]	validation-rmse:7.37551
[492]	validation-rmse:7.37530
[493]	validation-rmse:7.37512
[494]	validation-rmse:7.37519
[495]	validation-rmse:7.37520
[496]	validation-rmse:7.37490
[497]	validation-rmse:7.37492
[498]	validation-rmse:7.37495
[499]	validation-rmse:7.37467
[500]	validation-rmse:7.37433
[501]	validation-rmse:7.37429
[502]	validation-rmse:7.37393
[503]	validation-rmse:7.37377
[504]	validation-rmse:7.37333
[505]	validation-rmse:7.37335
[506]	validation-rmse:7.37310
[507]	validation-rmse:7.37283
[508]	validation-rmse:7.37268
[509]	validation-rmse:7.37271
[510]	validation-rmse:7.37243
[511]	validation-rmse:7.37255
[512]	validation-rmse:7.37230
[513]	validation-rmse:7.37197
[514]	validation-rmse:7.37196
[515]	validation-rmse:7.37214
[516]	validation-rmse:7.37209
[517]	validation-rmse:7.37210
[518]	validation-rmse:7.37202
[519]	validation-rmse:7.37187
[520]	validation-rmse:7.37135
[521]	validation-rmse:7.37167
[522]	validation-rmse:7.37140
[523]	validation-rmse:7.37113
[524]	validation-rmse:7.37041
[525]	validation-rmse:7.37016
[526]	validation-rmse:7.36991
[527]	validation-rmse:7.36994
[528]	validation-rmse:7.36984
[529]	validation-rmse:7.36988
[530]	validation-rmse:7.36971
[531]	validation-rmse:7.36999
[532]	validation-rmse:7.36979
[533]	validation-rmse:7.36960
[534]	validation-rmse:7.36914
[535]	validation-rmse:7.36883
[536]	validation-rmse:7.36894
[537]	validation-rmse:7.36882
[538]	validation-rmse:7.36848
[539]	validation-rmse:7.36835
[540]	validation-rmse:7.36797
[541]	validation-rmse:7.36792
[542]	validation-rmse:7.36775
[543]	validation-rmse:7.36783
[544]	validation-rmse:7.36782
[545]	validation-rmse:7.36753
[546]	validation-rmse:7.36730
[547]	validation-rmse:7.36682
[548]	validation-rmse:7.36696
[549]	validation-rmse:7.36670
[550]	validation-rmse:7.36647
[551]	validation-rmse:7.36649
[552]	validation-rmse:7.36617
[553]	validation-rmse:7.36620
[554]	validation-rmse:7.36598
[555]	validation-rmse:7.36561
[556]	validation-rmse:7.36516
[557]	validation-rmse:7.36534
[558]	validation-rmse:7.36533
[559]	validation-rmse:7.36512
[560]	validation-rmse:7.36544
[561]	validation-rmse:7.36569
[562]	validation-rmse:7.36517
[563]	validation-rmse:7.36498
[564]	validation-rmse:7.36508
[565]	validation-rmse:7.36507
[566]	validation-rmse:7.36477
[567]	validation-rmse:7.36484
[568]	validation-rmse:7.36488
[569]	validation-rmse:7.36452
[570]	validation-rmse:7.36428
[571]	validation-rmse:7.36434
[572]	validation-rmse:7.36438
[573]	validation-rmse:7.36422
[574]	validation-rmse:7.36400
[575]	validation-rmse:7.36407
[576]	validation-rmse:7.36397
[577]	validation-rmse:7.36363
[578]	validation-rmse:7.36336
[579]	validation-rmse:7.36335
[580]	validation-rmse:7.36319
[581]	validation-rmse:7.36308
[582]	validation-rmse:7.36324
[583]	validation-rmse:7.36314
[584]	validation-rmse:7.36293
[585]	validation-rmse:7.36230
[586]	validation-rmse:7.36236
[587]	validation-rmse:7.36217
[588]	validation-rmse:7.36173
[589]	validation-rmse:7.36167
[590]	validation-rmse:7.36159
[591]	validation-rmse:7.36144
[592]	validation-rmse:7.36109
[593]	validation-rmse:7.36118
[594]	validation-rmse:7.36110
[595]	validation-rmse:7.36077
[596]	validation-rmse:7.36075
[597]	validation-rmse:7.36039
[598]	validation-rmse:7.36027
[599]	validation-rmse:7.36026
[600]	validation-rmse:7.35980
[601]	validation-rmse:7.35934
[602]	validation-rmse:7.35947
[603]	validation-rmse:7.35938
[604]	validation-rmse:7.35911
[605]	validation-rmse:7.35898
[606]	validation-rmse:7.35919
[607]	validation-rmse:7.35898
[608]	validation-rmse:7.35911
[609]	validation-rmse:7.35892
[610]	validation-rmse:7.35902
[611]	validation-rmse:7.35848
[612]	validation-rmse:7.35829
[613]	validation-rmse:7.35832
[614]	validation-rmse:7.35856
[615]	validation-rmse:7.35804
[616]	validation-rmse:7.35845
[617]	validation-rmse:7.35816
[618]	validation-rmse:7.35822
[619]	validation-rmse:7.35800
[620]	validation-rmse:7.35764
[621]	validation-rmse:7.35763
[622]	validation-rmse:7.35750
[623]	validation-rmse:7.35746
[624]	validation-rmse:7.35737
[625]	validation-rmse:7.35771
[626]	validation-rmse:7.35769
[627]	validation-rmse:7.35752
[628]	validation-rmse:7.35743
[629]	validation-rmse:7.35759
[630]	validation-rmse:7.35785
[631]	validation-rmse:7.35773
[632]	validation-rmse:7.35760
[633]	validation-rmse:7.35747
[634]	validation-rmse:7.35699
[635]	validation-rmse:7.35703
[636]	validation-rmse:7.35691
[637]	validation-rmse:7.35634
[638]	validation-rmse:7.35584
[639]	validation-rmse:7.35571
[640]	validation-rmse:7.35582
[641]	validation-rmse:7.35558
[642]	validation-rmse:7.35533
[643]	validation-rmse:7.35530
[644]	validation-rmse:7.35531
[645]	validation-rmse:7.35521
[646]	validation-rmse:7.35549
[647]	validation-rmse:7.35567
[648]	validation-rmse:7.35511
[649]	validation-rmse:7.35459
[650]	validation-rmse:7.35464
[651]	validation-rmse:7.35455
[652]	validation-rmse:7.35438
[653]	validation-rmse:7.35397
[654]	validation-rmse:7.35404
[655]	validation-rmse:7.35368
[656]	validation-rmse:7.35329
[657]	validation-rmse:7.35279
[658]	validation-rmse:7.35283
[659]	validation-rmse:7.35233
[660]	validation-rmse:7.35237
[661]	validation-rmse:7.35261
[662]	validation-rmse:7.35225
[663]	validation-rmse:7.35192
[664]	validation-rmse:7.35195
[665]	validation-rmse:7.35236
[666]	validation-rmse:7.35196
[667]	validation-rmse:7.35181
[668]	validation-rmse:7.35186
[669]	validation-rmse:7.35207
[670]	validation-rmse:7.35190

[12:46:34] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:8.83640
[2]	validation-rmse:8.54008
[3]	validation-rmse:8.41718
[4]	validation-rmse:8.32073
[5]	validation-rmse:8.26928
[6]	validation-rmse:8.24806
[7]	validation-rmse:8.22659
[8]	validation-rmse:8.20558
[9]	validation-rmse:8.19768
[10]	validation-rmse:8.17838
[11]	validation-rmse:8.17292
[12]	validation-rmse:8.15254
[13]	validation-rmse:8.13137
[14]	validation-rmse:8.10837
[15]	validation-rmse:8.10177
[16]	validation-rmse:8.08680
[17]	validation-rmse:8.06899
[18]	validation-rmse:8.06199
[19]	validation-rmse:8.04747
[20]	validation-rmse:8.03698
[21]	validation-rmse:8.02188
[22]	validation-rmse:8.00922
[23]	validation-rmse:7.99778
[24]	validation-rmse:7.98031
[25]	validation-rmse:7.96174
[26]	validation-rmse:7.95767
[27]	validation-rmse:7.95010
[28]	validation-rmse:7.93945
[29]	validation-rmse:7.93212
[30]	validation-rmse:7.93048
[31]	validation-rmse:7.92288
[32]	validation-rmse:7.91825
[33]	validation-rmse:7.91467
[34]	validation-rmse:7.90792
[35]	validation-rmse:7.89966
[36]	validation-rmse:7.89181
[37]	validation-rmse:7.88708
[38]	validation-rmse:7.87994
[39]	validation-rmse:7.87036
[40]	validation-rmse:7.86275
[41]	validation-rmse:7.86048
[42]	validation-rmse:7.85653
[43]	validation-rmse:7.85091
[44]	validation-rmse:7.84701
[45]	validation-rmse:7.84028
[46]	validation-rmse:7.83359
[47]	validation-rmse:7.82906
[48]	validation-rmse:7.81976
[49]	validation-rmse:7.81479
[50]	validation-rmse:7.80983
[51]	validation-rmse:7.80339
[52]	validation-rmse:7.80503
[53]	validation-rmse:7.79196
[54]	validation-rmse:7.79132
[55]	validation-rmse:7.78893
[56]	validation-rmse:7.78599
[57]	validation-rmse:7.77653
[58]	validation-rmse:7.77418
[59]	validation-rmse:7.76181
[60]	validation-rmse:7.76110
[61]	validation-rmse:7.75318
[62]	validation-rmse:7.75001
[63]	validation-rmse:7.74581
[64]	validation-rmse:7.73719
[65]	validation-rmse:7.73376
[66]	validation-rmse:7.72740
[67]	validation-rmse:7.72774
[68]	validation-rmse:7.72286
[69]	validation-rmse:7.71187
[70]	validation-rmse:7.70865
[71]	validation-rmse:7.70532
[72]	validation-rmse:7.70049
[73]	validation-rmse:7.69423
[74]	validation-rmse:7.68791
[75]	validation-rmse:7.68742
[76]	validation-rmse:7.67794
[77]	validation-rmse:7.67282
[78]	validation-rmse:7.66934
[79]	validation-rmse:7.66411
[80]	validation-rmse:7.65898
[81]	validation-rmse:7.65835
[82]	validation-rmse:7.65742
[83]	validation-rmse:7.65012
[84]	validation-rmse:7.64318
[85]	validation-rmse:7.63784
[86]	validation-rmse:7.63622
[87]	validation-rmse:7.63672
[88]	validation-rmse:7.62922
[89]	validation-rmse:7.62322
[90]	validation-rmse:7.62210
[91]	validation-rmse:7.62136
[92]	validation-rmse:7.61759
[93]	validation-rmse:7.61469
[94]	validation-rmse:7.61474
[95]	validation-rmse:7.60863
[96]	validation-rmse:7.60843
[97]	validation-rmse:7.60181
[98]	validation-rmse:7.60084
[99]	validation-rmse:7.59793
[100]	validation-rmse:7.59677
[101]	validation-rmse:7.59230
[102]	validation-rmse:7.59014
[103]	validation-rmse:7.59002
[104]	validation-rmse:7.58421
[105]	validation-rmse:7.58032
[106]	validation-rmse:7.57935
[107]	validation-rmse:7.58043
[108]	validation-rmse:7.57843
[109]	validation-rmse:7.57495
[110]	validation-rmse:7.57030
[111]	validation-rmse:7.56656
[112]	validation-rmse:7.56494
[113]	validation-rmse:7.56202
[114]	validation-rmse:7.55790
[115]	validation-rmse:7.55623
[116]	validation-rmse:7.55649
[117]	validation-rmse:7.55703
[118]	validation-rmse:7.55240
[119]	validation-rmse:7.55040
[120]	validation-rmse:7.54423
[121]	validation-rmse:7.53951
[122]	validation-rmse:7.53750
[123]	validation-rmse:7.53609
[124]	validation-rmse:7.53128
[125]	validation-rmse:7.52842
[126]	validation-rmse:7.52802
[127]	validation-rmse:7.52764
[128]	validation-rmse:7.52343
[129]	validation-rmse:7.52132
[130]	validation-rmse:7.52092
[131]	validation-rmse:7.51730
[132]	validation-rmse:7.51552
[133]	validation-rmse:7.51139
[134]	validation-rmse:7.50975
[135]	validation-rmse:7.50962
[136]	validation-rmse:7.50821
[137]	validation-rmse:7.50541
[138]	validation-rmse:7.50078
[139]	validation-rmse:7.49857
[140]	validation-rmse:7.49863
[141]	validation-rmse:7.49508
[142]	validation-rmse:7.48932
[143]	validation-rmse:7.48586
[144]	validation-rmse:7.48026
[145]	validation-rmse:7.47468
[146]	validation-rmse:7.46943
[147]	validation-rmse:7.46740
[148]	validation-rmse:7.46503
[149]	validation-rmse:7.46374
[150]	validation-rmse:7.46172
[151]	validation-rmse:7.46288
[152]	validation-rmse:7.46216
[153]	validation-rmse:7.46059
[154]	validation-rmse:7.45925
[155]	validation-rmse:7.45736
[156]	validation-rmse:7.45599
[157]	validation-rmse:7.45323
[158]	validation-rmse:7.45007
[159]	validation-rmse:7.44894
[160]	validation-rmse:7.44720
[161]	validation-rmse:7.44730
[162]	validation-rmse:7.44637
[163]	validation-rmse:7.44546
[164]	validation-rmse:7.44239
[165]	validation-rmse:7.44151
[166]	validation-rmse:7.44316
[167]	validation-rmse:7.44027
[168]	validation-rmse:7.43770
[169]	validation-rmse:7.43798
[170]	validation-rmse:7.43316
[171]	validation-rmse:7.43108
[172]	validation-rmse:7.42821
[173]	validation-rmse:7.42792
[174]	validation-rmse:7.42776
[175]	validation-rmse:7.42799
[176]	validation-rmse:7.42596
[177]	validation-rmse:7.42447
[178]	validation-rmse:7.42484
[179]	validation-rmse:7.42451
[180]	validation-rmse:7.42117
[181]	validation-rmse:7.41979
[182]	validation-rmse:7.41625
[183]	validation-rmse:7.41360
[184]	validation-rmse:7.41106
[185]	validation-rmse:7.41135
[186]	validation-rmse:7.41349
[187]	validation-rmse:7.41013
[188]	validation-rmse:7.40832
[189]	validation-rmse:7.40906
[190]	validation-rmse:7.40736
[191]	validation-rmse:7.40718
[192]	validation-rmse:7.40448
[193]	validation-rmse:7.40199
[194]	validation-rmse:7.40152
[195]	validation-rmse:7.39838
[196]	validation-rmse:7.39870
[197]	validation-rmse:7.39611
[198]	validation-rmse:7.39516
[199]	validation-rmse:7.39615
[200]	validation-rmse:7.39360
[201]	validation-rmse:7.39153
[202]	validation-rmse:7.39085
[203]	validation-rmse:7.38913
[204]	validation-rmse:7.38626
[205]	validation-rmse:7.38620
[206]	validation-rmse:7.38307
[207]	validation-rmse:7.38219
[208]	validation-rmse:7.37876
[209]	validation-rmse:7.37987
[210]	validation-rmse:7.38046
[211]	validation-rmse:7.38080
[212]	validation-rmse:7.37930
[213]	validation-rmse:7.37755
[214]	validation-rmse:7.37723
[215]	validation-rmse:7.37510
[216]	validation-rmse:7.37214
[217]	validation-rmse:7.36999
[218]	validation-rmse:7.36753
[219]	validation-rmse:7.36881
[220]	validation-rmse:7.36647
[221]	validation-rmse:7.36608
[222]	validation-rmse:7.36601
[223]	validation-rmse:7.36544
[224]	validation-rmse:7.36419
[225]	validation-rmse:7.36426
[226]	validation-rmse:7.36305
[227]	validation-rmse:7.36165
[228]	validation-rmse:7.36092
[229]	validation-rmse:7.35907
[230]	validation-rmse:7.35785
[231]	validation-rmse:7.35754
[232]	validation-rmse:7.35575
[233]	validation-rmse:7.35528
[234]	validation-rmse:7.35319
[235]	validation-rmse:7.35308
[236]	validation-rmse:7.34899
[237]	validation-rmse:7.34763
[238]	validation-rmse:7.34781
[239]	validation-rmse:7.34656
[240]	validation-rmse:7.34675
[241]	validation-rmse:7.34475
[242]	validation-rmse:7.34554
[243]	validation-rmse:7.34000
[244]	validation-rmse:7.34192
[245]	validation-rmse:7.33861
[246]	validation-rmse:7.33756
[247]	validation-rmse:7.33527
[248]	validation-rmse:7.32855
[249]	validation-rmse:7.32740
[250]	validation-rmse:7.32351
[251]	validation-rmse:7.32103
[252]	validation-rmse:7.32169
[253]	validation-rmse:7.31870
[254]	validation-rmse:7.31908
[255]	validation-rmse:7.31970
[256]	validation-rmse:7.31668
[257]	validation-rmse:7.31811
[258]	validation-rmse:7.31592
[259]	validation-rmse:7.31740
[260]	validation-rmse:7.31791
[261]	validation-rmse:7.31556
[262]	validation-rmse:7.31535
[263]	validation-rmse:7.31545
[264]	validation-rmse:7.31270
[265]	validation-rmse:7.31190
[266]	validation-rmse:7.31080
[267]	validation-rmse:7.31081
[268]	validation-rmse:7.30776
[269]	validation-rmse:7.30867
[270]	validation-rmse:7.30727
[271]	validation-rmse:7.30651
[272]	validation-rmse:7.30368
[273]	validation-rmse:7.30183
[274]	validation-rmse:7.30279
[275]	validation-rmse:7.30242
[276]	validation-rmse:7.30553
[277]	validation-rmse:7.30193
[278]	validation-rmse:7.30007
[279]	validation-rmse:7.29950
[280]	validation-rmse:7.29999
[281]	validation-rmse:7.30087
[282]	validation-rmse:7.30086
[283]	validation-rmse:7.29961
[284]	validation-rmse:7.29739
[285]	validation-rmse:7.29846
[286]	validation-rmse:7.29602
[287]	validation-rmse:7.29548
[288]	validation-rmse:7.29378
[289]	validation-rmse:7.29210
[290]	validation-rmse:7.28900
[291]	validation-rmse:7.28950
[292]	validation-rmse:7.28809
[293]	validation-rmse:7.28803
[294]	validation-rmse:7.28550
[295]	validation-rmse:7.28348
[296]	validation-rmse:7.28342
[297]	validation-rmse:7.28275
[298]	validation-rmse:7.28131
[299]	validation-rmse:7.28114
[300]	validation-rmse:7.28016
[301]	validation-rmse:7.27830
[302]	validation-rmse:7.27824
[303]	validation-rmse:7.27820
[304]	validation-rmse:7.27902
[305]	validation-rmse:7.27794
[306]	validation-rmse:7.27710
[307]	validation-rmse:7.27701
[308]	validation-rmse:7.27511
[309]	validation-rmse:7.27303
[310]	validation-rmse:7.27412
[311]	validation-rmse:7.27311
[312]	validation-rmse:7.27408
[313]	validation-rmse:7.27385
[314]	validation-rmse:7.27367
[315]	validation-rmse:7.27429
[316]	validation-rmse:7.27389
[317]	validation-rmse:7.27433
[318]	validation-rmse:7.27265
[319]	validation-rmse:7.27023
[320]	validation-rmse:7.27072
[321]	validation-rmse:7.27057
[322]	validation-rmse:7.26979
[323]	validation-rmse:7.26263
[324]	validation-rmse:7.25989
[325]	validation-rmse:7.26189
[326]	validation-rmse:7.26155
[327]	validation-rmse:7.26268
[328]	validation-rmse:7.26113
[329]	validation-rmse:7.26094
[330]	validation-rmse:7.25917
[331]	validation-rmse:7.25967
[332]	validation-rmse:7.25822
[333]	validation-rmse:7.25845
[334]	validation-rmse:7.26004
[335]	validation-rmse:7.25826
[336]	validation-rmse:7.25542
[337]	validation-rmse:7.25571
[338]	validation-rmse:7.25713
[339]	validation-rmse:7.25468
[340]	validation-rmse:7.25581
[341]	validation-rmse:7.25188
[342]	validation-rmse:7.25227
[343]	validation-rmse:7.25225
[344]	validation-rmse:7.25288
[345]	validation-rmse:7.25200
[346]	validation-rmse:7.25186
[347]	validation-rmse:7.25238
[348]	validation-rmse:7.24965
[349]	validation-rmse:7.25010
[350]	validation-rmse:7.24887
[351]	validation-rmse:7.24740
[352]	validation-rmse:7.24858
[353]	validation-rmse:7.25045
[354]	validation-rmse:7.24868
[355]	validation-rmse:7.24731
[356]	validation-rmse:7.24780
[357]	validation-rmse:7.24782
[358]	validation-rmse:7.24713
[359]	validation-rmse:7.24635
[360]	validation-rmse:7.24545
[361]	validation-rmse:7.24489
[362]	validation-rmse:7.24172
[363]	validation-rmse:7.24332
[364]	validation-rmse:7.24264
[365]	validation-rmse:7.24183
[366]	validation-rmse:7.24144
[367]	validation-rmse:7.24111
[368]	validation-rmse:7.24017
[369]	validation-rmse:7.24030
[370]	validation-rmse:7.24088
[371]	validation-rmse:7.24030
[372]	validation-rmse:7.23975
[373]	validation-rmse:7.24137
[374]	validation-rmse:7.23962
[375]	validation-rmse:7.23942
[376]	validation-rmse:7.23868
[377]	validation-rmse:7.23831
[378]	validation-rmse:7.23850
[379]	validation-rmse:7.23820
[380]	validation-rmse:7.23781
[381]	validation-rmse:7.23624
[382]	validation-rmse:7.23553
[383]	validation-rmse:7.23552
[384]	validation-rmse:7.23511
[385]	validation-rmse:7.23528
[386]	validation-rmse:7.23428
[387]	validation-rmse:7.23600
[388]	validation-rmse:7.23371
[389]	validation-rmse:7.23305
[390]	validation-rmse:7.23291
[391]	validation-rmse:7.23317
[392]	validation-rmse:7.23352
[393]	validation-rmse:7.23241
[394]	validation-rmse:7.23259
[395]	validation-rmse:7.23157
[396]	validation-rmse:7.23147
[397]	validation-rmse:7.23085
[398]	validation-rmse:7.23075
[399]	validation-rmse:7.22956
[400]	validation-rmse:7.22888
[401]	validation-rmse:7.22784
[402]	validation-rmse:7.22856
[403]	validation-rmse:7.22886
[404]	validation-rmse:7.22841
[405]	validation-rmse:7.23042
[406]	validation-rmse:7.22822
[407]	validation-rmse:7.22912
[408]	validation-rmse:7.22834
[409]	validation-rmse:7.22799
[410]	validation-rmse:7.22567
[411]	validation-rmse:7.22661
[412]	validation-rmse:7.22721
[413]	validation-rmse:7.22667
[414]	validation-rmse:7.22561
[415]	validation-rmse:7.22500
[416]	validation-rmse:7.22592
[417]	validation-rmse:7.22481
[418]	validation-rmse:7.22482
[419]	validation-rmse:7.22397
[420]	validation-rmse:7.22456
[421]	validation-rmse:7.22348
[422]	validation-rmse:7.22314
[423]	validation-rmse:7.22190
[424]	validation-rmse:7.22158
[425]	validation-rmse:7.22155
[426]	validation-rmse:7.22153
[427]	validation-rmse:7.22228
[428]	validation-rmse:7.22233
[429]	validation-rmse:7.22199
[430]	validation-rmse:7.22192
[431]	validation-rmse:7.22020
[432]	validation-rmse:7.21960
[433]	validation-rmse:7.22030
[434]	validation-rmse:7.21969
[435]	validation-rmse:7.21906
[436]	validation-rmse:7.21960
[437]	validation-rmse:7.21838
[438]	validation-rmse:7.22033
[439]	validation-rmse:7.22017
[440]	validation-rmse:7.21887
[441]	validation-rmse:7.21837
[442]	validation-rmse:7.21762
[443]	validation-rmse:7.21604
[444]	validation-rmse:7.21541
[445]	validation-rmse:7.21699
[446]	validation-rmse:7.21618
[447]	validation-rmse:7.21764
[448]	validation-rmse:7.21597
[449]	validation-rmse:7.21587
[450]	validation-rmse:7.21663
[451]	validation-rmse:7.21642
[452]	validation-rmse:7.21559
[453]	validation-rmse:7.21652
[454]	validation-rmse:7.21657
[455]	validation-rmse:7.21624
[456]	validation-rmse:7.21602
[457]	validation-rmse:7.21541
[458]	validation-rmse:7.21453
[459]	validation-rmse:7.21436
[460]	validation-rmse:7.21456
[461]	validation-rmse:7.21452
[462]	validation-rmse:7.21574
[463]	validation-rmse:7.21592
[464]	validation-rmse:7.21459
[465]	validation-rmse:7.21440
[466]	validation-rmse:7.21360
[467]	validation-rmse:7.21445
[468]	validation-rmse:7.21274
[469]	validation-rmse:7.21285
[470]	validation-rmse:7.21331
[471]	validation-rmse:7.21259
[472]	validation-rmse:7.21300
[473]	validation-rmse:7.21181
[474]	validation-rmse:7.21158
[475]	validation-rmse:7.21207
[476]	validation-rmse:7.21085
[477]	validation-rmse:7.21066
[478]	validation-rmse:7.21177
[479]	validation-rmse:7.21174
[480]	validation-rmse:7.21180
[481]	validation-rmse:7.21184
[482]	validation-rmse:7.20957
[483]	validation-rmse:7.20863
[484]	validation-rmse:7.20904
[485]	validation-rmse:7.20992
[486]	validation-rmse:7.20983
[487]	validation-rmse:7.21001
[488]	validation-rmse:7.21049
[489]	validation-rmse:7.20942
[490]	validation-rmse:7.20829
[491]	validation-rmse:7.20744
[492]	validation-rmse:7.20878
[493]	validation-rmse:7.20723
[494]	validation-rmse:7.20785
[495]	validation-rmse:7.20846
[496]	validation-rmse:7.20807
[497]	validation-rmse:7.20764
[498]	validation-rmse:7.20773
[499]	validation-rmse:7.20655
[500]	validation-rmse:7.20686
[501]	validation-rmse:7.20616
[502]	validation-rmse:7.20567
[503]	validation-rmse:7.20533
[504]	validation-rmse:7.20555
[505]	validation-rmse:7.20541
[506]	validation-rmse:7.20575
[507]	validation-rmse:7.20444
[508]	validation-rmse:7.20396
[509]	validation-rmse:7.20421
[510]	validation-rmse:7.20487
[511]	validation-rmse:7.20422
[512]	validation-rmse:7.20345
[513]	validation-rmse:7.20218
[514]	validation-rmse:7.20330
[515]	validation-rmse:7.20364
[516]	validation-rmse:7.20318
[517]	validation-rmse:7.20231
[518]	validation-rmse:7.20366
[519]	validation-rmse:7.20367
[520]	validation-rmse:7.20162
[521]	validation-rmse:7.20148
[522]	validation-rmse:7.20221
[523]	validation-rmse:7.20298
[524]	validation-rmse:7.20339
[525]	validation-rmse:7.20202
[526]	validation-rmse:7.20193
[527]	validation-rmse:7.20076
[528]	validation-rmse:7.20182
[529]	validation-rmse:7.20326
[530]	validation-rmse:7.20222
[531]	validation-rmse:7.20170
[532]	validation-rmse:7.20133
[533]	validation-rmse:7.20013
[534]	validation-rmse:7.20071
[535]	validation-rmse:7.20088
[536]	validation-rmse:7.20027
[537]	validation-rmse:7.20098
[538]	validation-rmse:7.20115
[539]	validation-rmse:7.20104
[540]	validation-rmse:7.20006
[541]	validation-rmse:7.19963
[542]	validation-rmse:7.19913
[543]	validation-rmse:7.19929
[544]	validation-rmse:7.20015
[545]	validation-rmse:7.19951
[546]	validation-rmse:7.19947
[547]	validation-rmse:7.19817
[548]	validation-rmse:7.19831
[549]	validation-rmse:7.19866
[550]	validation-rmse:7.19788
[551]	validation-rmse:7.19877
[552]	validation-rmse:7.19941
[553]	validation-rmse:7.19866
[554]	validation-rmse:7.19927
[555]	validation-rmse:7.19876
[556]	validation-rmse:7.19847
[557]	validation-rmse:7.19938
[558]	validation-rmse:7.19862
[559]	validation-rmse:7.19878
[560]	validation-rmse:7.19842
[561]	validation-rmse:7.19760
[562]	validation-rmse:7.19751
[563]	validation-rmse:7.19786
[564]	validation-rmse:7.19730
[565]	validation-rmse:7.19809
[566]	validation-rmse:7.19782
[567]	validation-rmse:7.19835
[568]	validation-rmse:7.19749
[569]	validation-rmse:7.19813
[570]	validation-rmse:7.19772
[571]	validation-rmse:7.19742
[572]	validation-rmse:7.19695
[573]	validation-rmse:7.19684
[574]	validation-rmse:7.19656
[575]	validation-rmse:7.19583
[576]	validation-rmse:7.19533
[577]	validation-rmse:7.19452
[578]	validation-rmse:7.19443
[579]	validation-rmse:7.19442
[580]	validation-rmse:7.19447
[581]	validation-rmse:7.19480
[582]	validation-rmse:7.19427
[583]	validation-rmse:7.19462
[584]	validation-rmse:7.19437
[585]	validation-rmse:7.19448
[586]	validation-rmse:7.19377
[587]	validation-rmse:7.19418
[588]	validation-rmse:7.19334
[589]	validation-rmse:7.19325
[590]	validation-rmse:7.19343
[591]	validation-rmse:7.19340
[592]	validation-rmse:7.19248
[593]	validation-rmse:7.19263
[594]	validation-rmse:7.19299
[595]	validation-rmse:7.19290
[596]	validation-rmse:7.19328
[597]	validation-rmse:7.19261
[598]	validation-rmse:7.19361
[599]	validation-rmse:7.19280
[600]	validation-rmse:7.19337
[601]	validation-rmse:7.19327
[602]	validation-rmse:7.19330
[603]	validation-rmse:7.19326
[604]	validation-rmse:7.19323
[605]	validation-rmse:7.19388
[606]	validation-rmse:7.19307
[607]	validation-rmse:7.19345
[608]	validation-rmse:7.19365
[609]	validation-rmse:7.19215
[610]	validation-rmse:7.19201
[611]	validation-rmse:7.19219
[612]	validation-rmse:7.19177
[613]	validation-rmse:7.19189
[614]	validation-rmse:7.19142
[615]	validation-rmse:7.19200
[616]	validation-rmse:7.19168
[617]	validation-rmse:7.19212
[618]	validation-rmse:7.19068
[619]	validation-rmse:7.18997
[620]	validation-rmse:7.18974
[621]	validation-rmse:7.18961
[622]	validation-rmse:7.18969
[623]	validation-rmse:7.18945
[624]	validation-rmse:7.18970
[625]	validation-rmse:7.19097
[626]	validation-rmse:7.19153
[627]	validation-rmse:7.19130
[628]	validation-rmse:7.19123
[629]	validation-rmse:7.19119
[630]	validation-rmse:7.19129
[631]	validation-rmse:7.19198
[632]	validation-rmse:7.19093
[633]	validation-rmse:7.18989
[634]	validation-rmse:7.19096
[635]	validation-rmse:7.19089
[636]	validation-rmse:7.19061
[637]	validation-rmse:7.19001
[638]	validation-rmse:7.18980
[639]	validation-rmse:7.18947
[640]	validation-rmse:7.18941
[641]	validation-rmse:7.18890
[642]	validation-rmse:7.18948
[643]	validation-rmse:7.18738
[644]	validation-rmse:7.18756
[645]	validation-rmse:7.18825
[646]	validation-rmse:7.18815
[647]	validation-rmse:7.18826
[648]	validation-rmse:7.18798
[649]	validation-rmse:7.18836
[650]	validation-rmse:7.18744
[651]	validation-rmse:7.18839
[652]	validation-rmse:7.18803
[653]	validation-rmse:7.18837
[654]	validation-rmse:7.18752
[655]	validation-rmse:7.18757
[656]	validation-rmse:7.18791
[657]	validation-rmse:7.18883
[658]	validation-rmse:7.18837
[659]	validation-rmse:7.18800
[660]	validation-rmse:7.18789
[661]	validation-rmse:7.18796
[662]	validation-rmse:7.18666
[663]	validation-rmse:7.18744
[664]	validation-rmse:7.18745
[665]	validation-rmse:7.18683
[666]	validation-rmse:7.18769
[667]	validation-rmse:7.18759
[668]	validation-rmse:7.18861
[669]	validation-rmse:7.18732
[670]	validation-rmse:7.18690

[12:49:50] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:9.64540
[2]	validation-rmse:9.12003
[3]	validation-rmse:8.78858
[4]	validation-rmse:8.55257
[5]	validation-rmse:8.43851
[6]	validation-rmse:8.35201
[7]	validation-rmse:8.29855
[8]	validation-rmse:8.24041
[9]	validation-rmse:8.20673
[10]	validation-rmse:8.17523
[11]	validation-rmse:8.15366
[12]	validation-rmse:8.13232
[13]	validation-rmse:8.12037
[14]	validation-rmse:8.10850
[15]	validation-rmse:8.10437
[16]	validation-rmse:8.09095
[17]	validation-rmse:8.08013
[18]	validation-rmse:8.07546
[19]	validation-rmse:8.06674
[20]	validation-rmse:8.06177
[21]	validation-rmse:8.05773
[22]	validation-rmse:8.05061
[23]	validation-rmse:8.04363
[24]	validation-rmse:8.03352
[25]	validation-rmse:8.02237
[26]	validation-rmse:8.01296
[27]	validation-rmse:8.00502
[28]	validation-rmse:7.99601
[29]	validation-rmse:7.98949
[30]	validation-rmse:7.98184
[31]	validation-rmse:7.97679
[32]	validation-rmse:7.96546
[33]	validation-rmse:7.95833
[34]	validation-rmse:7.95238
[35]	validation-rmse:7.94611
[36]	validation-rmse:7.93973
[37]	validation-rmse:7.93407
[38]	validation-rmse:7.92886
[39]	validation-rmse:7.92009
[40]	validation-rmse:7.91357
[41]	validation-rmse:7.90697
[42]	validation-rmse:7.90298
[43]	validation-rmse:7.89746
[44]	validation-rmse:7.89243
[45]	validation-rmse:7.88835
[46]	validation-rmse:7.88626
[47]	validation-rmse:7.88258
[48]	validation-rmse:7.87919
[49]	validation-rmse:7.87325
[50]	validation-rmse:7.86998
[51]	validation-rmse:7.86722
[52]	validation-rmse:7.86721
[53]	validation-rmse:7.86171
[54]	validation-rmse:7.85869
[55]	validation-rmse:7.85384
[56]	validation-rmse:7.84870
[57]	validation-rmse:7.84533
[58]	validation-rmse:7.84198
[59]	validation-rmse:7.83801
[60]	validation-rmse:7.83334
[61]	validation-rmse:7.82888
[62]	validation-rmse:7.82647
[63]	validation-rmse:7.82019
[64]	validation-rmse:7.81910
[65]	validation-rmse:7.81895
[66]	validation-rmse:7.81399
[67]	validation-rmse:7.81117
[68]	validation-rmse:7.80973
[69]	validation-rmse:7.80705
[70]	validation-rmse:7.80474
[71]	validation-rmse:7.80172
[72]	validation-rmse:7.79784
[73]	validation-rmse:7.79452
[74]	validation-rmse:7.79267
[75]	validation-rmse:7.78670
[76]	validation-rmse:7.78465
[77]	validation-rmse:7.78263
[78]	validation-rmse:7.78208
[79]	validation-rmse:7.77598
[80]	validation-rmse:7.77618
[81]	validation-rmse:7.77530
[82]	validation-rmse:7.76989
[83]	validation-rmse:7.76652
[84]	validation-rmse:7.76596
[85]	validation-rmse:7.76104
[86]	validation-rmse:7.75667
[87]	validation-rmse:7.75737
[88]	validation-rmse:7.75780
[89]	validation-rmse:7.75522
[90]	validation-rmse:7.75403
[91]	validation-rmse:7.74951
[92]	validation-rmse:7.74811
[93]	validation-rmse:7.74839
[94]	validation-rmse:7.74662
[95]	validation-rmse:7.74482
[96]	validation-rmse:7.74482
[97]	validation-rmse:7.74200
[98]	validation-rmse:7.73952
[99]	validation-rmse:7.73820
[100]	validation-rmse:7.73729
[101]	validation-rmse:7.73213
[102]	validation-rmse:7.72849
[103]	validation-rmse:7.72594
[104]	validation-rmse:7.72133
[105]	validation-rmse:7.72181
[106]	validation-rmse:7.71969
[107]	validation-rmse:7.71733
[108]	validation-rmse:7.71861
[109]	validation-rmse:7.71484
[110]	validation-rmse:7.71578
[111]	validation-rmse:7.71448
[112]	validation-rmse:7.71112
[113]	validation-rmse:7.71119
[114]	validation-rmse:7.71183
[115]	validation-rmse:7.70953
[116]	validation-rmse:7.70991
[117]	validation-rmse:7.70697
[118]	validation-rmse:7.70510
[119]	validation-rmse:7.70293
[120]	validation-rmse:7.69904
[121]	validation-rmse:7.69830
[122]	validation-rmse:7.69368
[123]	validation-rmse:7.69038
[124]	validation-rmse:7.68597
[125]	validation-rmse:7.68392
[126]	validation-rmse:7.68324
[127]	validation-rmse:7.67973
[128]	validation-rmse:7.67487
[129]	validation-rmse:7.67355
[130]	validation-rmse:7.67116
[131]	validation-rmse:7.66895
[132]	validation-rmse:7.66579
[133]	validation-rmse:7.66508
[134]	validation-rmse:7.66171
[135]	validation-rmse:7.65295
[136]	validation-rmse:7.65359
[137]	validation-rmse:7.65217
[138]	validation-rmse:7.65115
[139]	validation-rmse:7.64770
[140]	validation-rmse:7.64734
[141]	validation-rmse:7.64440
[142]	validation-rmse:7.64508
[143]	validation-rmse:7.64365
[144]	validation-rmse:7.64471
[145]	validation-rmse:7.64258
[146]	validation-rmse:7.64221
[147]	validation-rmse:7.63984
[148]	validation-rmse:7.63569
[149]	validation-rmse:7.63517
[150]	validation-rmse:7.63614
[151]	validation-rmse:7.63611
[152]	validation-rmse:7.63463
[153]	validation-rmse:7.63072
[154]	validation-rmse:7.62985
[155]	validation-rmse:7.62611
[156]	validation-rmse:7.62381
[157]	validation-rmse:7.62016
[158]	validation-rmse:7.61996
[159]	validation-rmse:7.61543
[160]	validation-rmse:7.61319
[161]	validation-rmse:7.61173
[162]	validation-rmse:7.61177
[163]	validation-rmse:7.60981
[164]	validation-rmse:7.60703
[165]	validation-rmse:7.60418
[166]	validation-rmse:7.60295
[167]	validation-rmse:7.59830
[168]	validation-rmse:7.59624
[169]	validation-rmse:7.59639
[170]	validation-rmse:7.59605
[171]	validation-rmse:7.59388
[172]	validation-rmse:7.59249
[173]	validation-rmse:7.58986
[174]	validation-rmse:7.59141
[175]	validation-rmse:7.59127
[176]	validation-rmse:7.58880
[177]	validation-rmse:7.58836
[178]	validation-rmse:7.58613
[179]	validation-rmse:7.58500
[180]	validation-rmse:7.58261
[181]	validation-rmse:7.57934
[182]	validation-rmse:7.57941
[183]	validation-rmse:7.57686
[184]	validation-rmse:7.57444
[185]	validation-rmse:7.57594
[186]	validation-rmse:7.57415
[187]	validation-rmse:7.57346
[188]	validation-rmse:7.57260
[189]	validation-rmse:7.57060
[190]	validation-rmse:7.57061
[191]	validation-rmse:7.56586
[192]	validation-rmse:7.56719
[193]	validation-rmse:7.56800
[194]	validation-rmse:7.56625
[195]	validation-rmse:7.56475
[196]	validation-rmse:7.56274
[197]	validation-rmse:7.56162
[198]	validation-rmse:7.56203
[199]	validation-rmse:7.55899
[200]	validation-rmse:7.55813
[201]	validation-rmse:7.55854
[202]	validation-rmse:7.55720
[203]	validation-rmse:7.55415
[204]	validation-rmse:7.55123
[205]	validation-rmse:7.54767
[206]	validation-rmse:7.54527
[207]	validation-rmse:7.54442
[208]	validation-rmse:7.54382
[209]	validation-rmse:7.54347
[210]	validation-rmse:7.54196
[211]	validation-rmse:7.54101
[212]	validation-rmse:7.54105
[213]	validation-rmse:7.53881
[214]	validation-rmse:7.53835
[215]	validation-rmse:7.53556
[216]	validation-rmse:7.53361
[217]	validation-rmse:7.53450
[218]	validation-rmse:7.53345
[219]	validation-rmse:7.53278
[220]	validation-rmse:7.53080
[221]	validation-rmse:7.52843
[222]	validation-rmse:7.52852
[223]	validation-rmse:7.52666
[224]	validation-rmse:7.52655
[225]	validation-rmse:7.52575
[226]	validation-rmse:7.52462
[227]	validation-rmse:7.52455
[228]	validation-rmse:7.52335
[229]	validation-rmse:7.52265
[230]	validation-rmse:7.52018
[231]	validation-rmse:7.51970
[232]	validation-rmse:7.51804
[233]	validation-rmse:7.51836
[234]	validation-rmse:7.51512
[235]	validation-rmse:7.51268
[236]	validation-rmse:7.51122
[237]	validation-rmse:7.50955
[238]	validation-rmse:7.50892
[239]	validation-rmse:7.50792
[240]	validation-rmse:7.50622
[241]	validation-rmse:7.50338
[242]	validation-rmse:7.49996
[243]	validation-rmse:7.49952
[244]	validation-rmse:7.49658
[245]	validation-rmse:7.49492
[246]	validation-rmse:7.49407
[247]	validation-rmse:7.49363
[248]	validation-rmse:7.49209
[249]	validation-rmse:7.49038
[250]	validation-rmse:7.48752
[251]	validation-rmse:7.48653
[252]	validation-rmse:7.48543
[253]	validation-rmse:7.48670
[254]	validation-rmse:7.48659
[255]	validation-rmse:7.48607
[256]	validation-rmse:7.48364
[257]	validation-rmse:7.48203
[258]	validation-rmse:7.48123
[259]	validation-rmse:7.48065
[260]	validation-rmse:7.48118
[261]	validation-rmse:7.47970
[262]	validation-rmse:7.47577
[263]	validation-rmse:7.47322
[264]	validation-rmse:7.47385
[265]	validation-rmse:7.47380
[266]	validation-rmse:7.47315
[267]	validation-rmse:7.47183
[268]	validation-rmse:7.46994
[269]	validation-rmse:7.46943
[270]	validation-rmse:7.46906
[271]	validation-rmse:7.46773
[272]	validation-rmse:7.46753
[273]	validation-rmse:7.46665
[274]	validation-rmse:7.46617
[275]	validation-rmse:7.46445
[276]	validation-rmse:7.46338
[277]	validation-rmse:7.46293
[278]	validation-rmse:7.46190
[279]	validation-rmse:7.45973
[280]	validation-rmse:7.45538
[281]	validation-rmse:7.45583
[282]	validation-rmse:7.45333
[283]	validation-rmse:7.45179
[284]	validation-rmse:7.45163
[285]	validation-rmse:7.44935
[286]	validation-rmse:7.44881
[287]	validation-rmse:7.44956
[288]	validation-rmse:7.44756
[289]	validation-rmse:7.44540
[290]	validation-rmse:7.44652
[291]	validation-rmse:7.44404
[292]	validation-rmse:7.44302
[293]	validation-rmse:7.44338
[294]	validation-rmse:7.44256
[295]	validation-rmse:7.44078
[296]	validation-rmse:7.44002
[297]	validation-rmse:7.44050
[298]	validation-rmse:7.43910
[299]	validation-rmse:7.43953
[300]	validation-rmse:7.43772
[301]	validation-rmse:7.43776
[302]	validation-rmse:7.43625
[303]	validation-rmse:7.43599
[304]	validation-rmse:7.43580
[305]	validation-rmse:7.43554
[306]	validation-rmse:7.43356
[307]	validation-rmse:7.43425
[308]	validation-rmse:7.43421
[309]	validation-rmse:7.43321
[310]	validation-rmse:7.43298
[311]	validation-rmse:7.43216
[312]	validation-rmse:7.43083
[313]	validation-rmse:7.42979
[314]	validation-rmse:7.42721
[315]	validation-rmse:7.42704
[316]	validation-rmse:7.42646
[317]	validation-rmse:7.42447
[318]	validation-rmse:7.42405
[319]	validation-rmse:7.42377
[320]	validation-rmse:7.42309
[321]	validation-rmse:7.42273
[322]	validation-rmse:7.42295
[323]	validation-rmse:7.42243
[324]	validation-rmse:7.42278
[325]	validation-rmse:7.42063
[326]	validation-rmse:7.42102
[327]	validation-rmse:7.41931
[328]	validation-rmse:7.41959
[329]	validation-rmse:7.41907
[330]	validation-rmse:7.41614
[331]	validation-rmse:7.41534
[332]	validation-rmse:7.41313
[333]	validation-rmse:7.41293
[334]	validation-rmse:7.41366
[335]	validation-rmse:7.41085
[336]	validation-rmse:7.41066
[337]	validation-rmse:7.41049
[338]	validation-rmse:7.40945
[339]	validation-rmse:7.40890
[340]	validation-rmse:7.40800
[341]	validation-rmse:7.40776
[342]	validation-rmse:7.40670
[343]	validation-rmse:7.40637
[344]	validation-rmse:7.40570
[345]	validation-rmse:7.40550
[346]	validation-rmse:7.40460
[347]	validation-rmse:7.40433
[348]	validation-rmse:7.40313
[349]	validation-rmse:7.40319
[350]	validation-rmse:7.40258
[351]	validation-rmse:7.40079
[352]	validation-rmse:7.39982
[353]	validation-rmse:7.39874
[354]	validation-rmse:7.39828
[355]	validation-rmse:7.39932
[356]	validation-rmse:7.39908
[357]	validation-rmse:7.39837
[358]	validation-rmse:7.39851
[359]	validation-rmse:7.39743
[360]	validation-rmse:7.39801
[361]	validation-rmse:7.39705
[362]	validation-rmse:7.39643
[363]	validation-rmse:7.39468
[364]	validation-rmse:7.39392
[365]	validation-rmse:7.39332
[366]	validation-rmse:7.39303
[367]	validation-rmse:7.39076
[368]	validation-rmse:7.39095
[369]	validation-rmse:7.38931
[370]	validation-rmse:7.38955
[371]	validation-rmse:7.38914
[372]	validation-rmse:7.38820
[373]	validation-rmse:7.38711
[374]	validation-rmse:7.38701
[375]	validation-rmse:7.38684
[376]	validation-rmse:7.38567
[377]	validation-rmse:7.38527
[378]	validation-rmse:7.38453
[379]	validation-rmse:7.38365
[380]	validation-rmse:7.38315
[381]	validation-rmse:7.38323
[382]	validation-rmse:7.38380
[383]	validation-rmse:7.38290
[384]	validation-rmse:7.38080
[385]	validation-rmse:7.38066
[386]	validation-rmse:7.38096
[387]	validation-rmse:7.37914
[388]	validation-rmse:7.37862
[389]	validation-rmse:7.37956
[390]	validation-rmse:7.37821
[391]	validation-rmse:7.37740
[392]	validation-rmse:7.37699
[393]	validation-rmse:7.37639
[394]	validation-rmse:7.37544
[395]	validation-rmse:7.37396
[396]	validation-rmse:7.37172
[397]	validation-rmse:7.36915
[398]	validation-rmse:7.36778
[399]	validation-rmse:7.36845
[400]	validation-rmse:7.36856
[401]	validation-rmse:7.36725
[402]	validation-rmse:7.36599
[403]	validation-rmse:7.36623
[404]	validation-rmse:7.36485
[405]	validation-rmse:7.36317
[406]	validation-rmse:7.36372
[407]	validation-rmse:7.36266
[408]	validation-rmse:7.36175
[409]	validation-rmse:7.36157
[410]	validation-rmse:7.35998
[411]	validation-rmse:7.36031
[412]	validation-rmse:7.35859
[413]	validation-rmse:7.35782
[414]	validation-rmse:7.35806
[415]	validation-rmse:7.35863
[416]	validation-rmse:7.35909
[417]	validation-rmse:7.35513
[418]	validation-rmse:7.35486
[419]	validation-rmse:7.35468
[420]	validation-rmse:7.35340
[421]	validation-rmse:7.35293
[422]	validation-rmse:7.34975
[423]	validation-rmse:7.35065
[424]	validation-rmse:7.35137
[425]	validation-rmse:7.35047
[426]	validation-rmse:7.35113
[427]	validation-rmse:7.34909
[428]	validation-rmse:7.34807
[429]	validation-rmse:7.34731
[430]	validation-rmse:7.34718
[431]	validation-rmse:7.34735
[432]	validation-rmse:7.34580
[433]	validation-rmse:7.34528
[434]	validation-rmse:7.34608
[435]	validation-rmse:7.34557
[436]	validation-rmse:7.34468
[437]	validation-rmse:7.34460
[438]	validation-rmse:7.34425
[439]	validation-rmse:7.34256
[440]	validation-rmse:7.34091
[441]	validation-rmse:7.34026
[442]	validation-rmse:7.33959
[443]	validation-rmse:7.33907
[444]	validation-rmse:7.33953
[445]	validation-rmse:7.33949
[446]	validation-rmse:7.33982
[447]	validation-rmse:7.33944
[448]	validation-rmse:7.33867
[449]	validation-rmse:7.33799
[450]	validation-rmse:7.33834
[451]	validation-rmse:7.33716
[452]	validation-rmse:7.33767
[453]	validation-rmse:7.33801
[454]	validation-rmse:7.33650
[455]	validation-rmse:7.33566
[456]	validation-rmse:7.33510
[457]	validation-rmse:7.33541
[458]	validation-rmse:7.33583
[459]	validation-rmse:7.33481
[460]	validation-rmse:7.33442
[461]	validation-rmse:7.33466
[462]	validation-rmse:7.33300
[463]	validation-rmse:7.33200
[464]	validation-rmse:7.33173
[465]	validation-rmse:7.33125
[466]	validation-rmse:7.32947
[467]	validation-rmse:7.32976
[468]	validation-rmse:7.32937
[469]	validation-rmse:7.32906
[470]	validation-rmse:7.32837
[471]	validation-rmse:7.32779
[472]	validation-rmse:7.32783
[473]	validation-rmse:7.32819
[474]	validation-rmse:7.32812
[475]	validation-rmse:7.32764
[476]	validation-rmse:7.32718
[477]	validation-rmse:7.32672
[478]	validation-rmse:7.32701
[479]	validation-rmse:7.32656
[480]	validation-rmse:7.32596
[481]	validation-rmse:7.32568
[482]	validation-rmse:7.32442
[483]	validation-rmse:7.32376
[484]	validation-rmse:7.32393
[485]	validation-rmse:7.32347
[486]	validation-rmse:7.32375
[487]	validation-rmse:7.32343
[488]	validation-rmse:7.32228
[489]	validation-rmse:7.32229
[490]	validation-rmse:7.32228
[491]	validation-rmse:7.32074
[492]	validation-rmse:7.31988
[493]	validation-rmse:7.31900
[494]	validation-rmse:7.31967
[495]	validation-rmse:7.31915
[496]	validation-rmse:7.31863
[497]	validation-rmse:7.31875
[498]	validation-rmse:7.31819
[499]	validation-rmse:7.31780
[500]	validation-rmse:7.31720
[501]	validation-rmse:7.31819
[502]	validation-rmse:7.31770
[503]	validation-rmse:7.31657
[504]	validation-rmse:7.31545
[505]	validation-rmse:7.31548
[506]	validation-rmse:7.31632
[507]	validation-rmse:7.31689
[508]	validation-rmse:7.31633
[509]	validation-rmse:7.31620
[510]	validation-rmse:7.31661
[511]	validation-rmse:7.31470
[512]	validation-rmse:7.31388
[513]	validation-rmse:7.31370
[514]	validation-rmse:7.31314
[515]	validation-rmse:7.31307
[516]	validation-rmse:7.31147
[517]	validation-rmse:7.31036
[518]	validation-rmse:7.31115
[519]	validation-rmse:7.30896
[520]	validation-rmse:7.30902
[521]	validation-rmse:7.30927
[522]	validation-rmse:7.30885
[523]	validation-rmse:7.30726
[524]	validation-rmse:7.30689
[525]	validation-rmse:7.30593
[526]	validation-rmse:7.30525
[527]	validation-rmse:7.30469
[528]	validation-rmse:7.30377
[529]	validation-rmse:7.30363
[530]	validation-rmse:7.30522
[531]	validation-rmse:7.30524
[532]	validation-rmse:7.30450
[533]	validation-rmse:7.30439
[534]	validation-rmse:7.30335
[535]	validation-rmse:7.30316
[536]	validation-rmse:7.30283
[537]	validation-rmse:7.30282
[538]	validation-rmse:7.30197
[539]	validation-rmse:7.30073
[540]	validation-rmse:7.30091
[541]	validation-rmse:7.30121
[542]	validation-rmse:7.30134
[543]	validation-rmse:7.30065
[544]	validation-rmse:7.30075
[545]	validation-rmse:7.30053
[546]	validation-rmse:7.29981
[547]	validation-rmse:7.30058
[548]	validation-rmse:7.29929
[549]	validation-rmse:7.29774
[550]	validation-rmse:7.29758
[551]	validation-rmse:7.29684
[552]	validation-rmse:7.29661
[553]	validation-rmse:7.29633
[554]	validation-rmse:7.29568
[555]	validation-rmse:7.29504
[556]	validation-rmse:7.29202
[557]	validation-rmse:7.29124
[558]	validation-rmse:7.29165
[559]	validation-rmse:7.29298
[560]	validation-rmse:7.29282
[561]	validation-rmse:7.29228
[562]	validation-rmse:7.29192
[563]	validation-rmse:7.28998
[564]	validation-rmse:7.29035
[565]	validation-rmse:7.28975
[566]	validation-rmse:7.29008
[567]	validation-rmse:7.28915
[568]	validation-rmse:7.28911
[569]	validation-rmse:7.28953
[570]	validation-rmse:7.28830
[571]	validation-rmse:7.28843
[572]	validation-rmse:7.28870
[573]	validation-rmse:7.28815
[574]	validation-rmse:7.28814
[575]	validation-rmse:7.28759
[576]	validation-rmse:7.28750
[577]	validation-rmse:7.28695
[578]	validation-rmse:7.28411
[579]	validation-rmse:7.28438
[580]	validation-rmse:7.28416
[581]	validation-rmse:7.28393
[582]	validation-rmse:7.28401
[583]	validation-rmse:7.28396
[584]	validation-rmse:7.28349
[585]	validation-rmse:7.28285
[586]	validation-rmse:7.28260
[587]	validation-rmse:7.28170
[588]	validation-rmse:7.28062
[589]	validation-rmse:7.27960
[590]	validation-rmse:7.28042
[591]	validation-rmse:7.28045
[592]	validation-rmse:7.28032
[593]	validation-rmse:7.27937
[594]	validation-rmse:7.27946
[595]	validation-rmse:7.27881
[596]	validation-rmse:7.27865
[597]	validation-rmse:7.27743
[598]	validation-rmse:7.27793
[599]	validation-rmse:7.27806
[600]	validation-rmse:7.27670
[601]	validation-rmse:7.27637
[602]	validation-rmse:7.27682
[603]	validation-rmse:7.27610
[604]	validation-rmse:7.27619
[605]	validation-rmse:7.27465
[606]	validation-rmse:7.27438
[607]	validation-rmse:7.27469
[608]	validation-rmse:7.27539
[609]	validation-rmse:7.27444
[610]	validation-rmse:7.27515
[611]	validation-rmse:7.27469
[612]	validation-rmse:7.27337
[613]	validation-rmse:7.27353
[614]	validation-rmse:7.27369
[615]	validation-rmse:7.27384
[616]	validation-rmse:7.27296
[617]	validation-rmse:7.27166
[618]	validation-rmse:7.27077
[619]	validation-rmse:7.27050
[620]	validation-rmse:7.27092
[621]	validation-rmse:7.27086
[622]	validation-rmse:7.26977
[623]	validation-rmse:7.27031
[624]	validation-rmse:7.26982
[625]	validation-rmse:7.26796
[626]	validation-rmse:7.26618
[627]	validation-rmse:7.26650
[628]	validation-rmse:7.26480
[629]	validation-rmse:7.26528
[630]	validation-rmse:7.26426
[631]	validation-rmse:7.26407
[632]	validation-rmse:7.26403
[633]	validation-rmse:7.26481
[634]	validation-rmse:7.26370
[635]	validation-rmse:7.26266
[636]	validation-rmse:7.26240
[637]	validation-rmse:7.26235
[638]	validation-rmse:7.26259
[639]	validation-rmse:7.26158
[640]	validation-rmse:7.26098
[641]	validation-rmse:7.26069
[642]	validation-rmse:7.26056
[643]	validation-rmse:7.25915
[644]	validation-rmse:7.25731
[645]	validation-rmse:7.25637
[646]	validation-rmse:7.25640
[647]	validation-rmse:7.25620
[648]	validation-rmse:7.25469
[649]	validation-rmse:7.25571
[650]	validation-rmse:7.25639
[651]	validation-rmse:7.25537
[652]	validation-rmse:7.25543
[653]	validation-rmse:7.25523
[654]	validation-rmse:7.25381
[655]	validation-rmse:7.25308
[656]	validation-rmse:7.25336
[657]	validation-rmse:7.25306
[658]	validation-rmse:7.25292
[659]	validation-rmse:7.25364
[660]	validation-rmse:7.25375
[661]	validation-rmse:7.25336
[662]	validation-rmse:7.25393
[663]	validation-rmse:7.25258
[664]	validation-rmse:7.25154
[665]	validation-rmse:7.25227
[666]	validation-rmse:7.25236
[667]	validation-rmse:7.25169
[668]	validation-rmse:7.25096
[669]	validation-rmse:7.24967
[670]	validation-rmse:7.24968

[12:53:19] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[2]	validation-rmse:9.92205
[3]	validation-rmse:9.69049
[4]	validation-rmse:9.52826
[5]	validation-rmse:9.34130
[6]	validation-rmse:9.18981
[7]	validation-rmse:9.09224
[8]	validation-rmse:8.98598
[9]	validation-rmse:8.71046
[10]	validation-rmse:8.65885
[11]	validation-rmse:8.56322
[12]	validation-rmse:8.49945
[13]	validation-rmse:8.47070
[14]	validation-rmse:8.43387
[15]	validation-rmse:8.40229
[16]	validation-rmse:8.37843
[17]	validation-rmse:8.25120
[18]	validation-rmse:8.23011
[19]	validation-rmse:8.21917
[20]	validation-rmse:8.16236
[21]	validation-rmse:8.13122
[22]	validation-rmse:8.12170
[23]	validation-rmse:8.11340
[24]	validation-rmse:8.09011
[25]	validation-rmse:8.03558
[26]	validation-rmse:8.00636
[27]	validation-rmse:7.98927
[28]	validation-rmse:7.98272
[29]	validation-rmse:7.97759
[30]	validation-rmse:7.97288
[31]	validation-rmse:7.96932
[32]	validation-rmse:7.95770
[33]	validation-rmse:7.95325
[34]	validation-rmse:7.95200
[35]	validation-rmse:7.92774
[36]	validation-rmse:7.92321
[37]	validation-rmse:7.91016
[38]	validation-rmse:7.90674
[39]	validation-rmse:7.89573
[40]	validation-rmse:7.89214
[41]	validation-rmse:7.88962
[42]	validation-rmse:7.88559
[43]	validation-rmse:7.87620
[44]	validation-rmse:7.86899
[45]	validation-rmse:7.86842
[46]	validation-rmse:7.86641
[47]	validation-rmse:7.86588
[48]	validation-rmse:7.86257
[49]	validation-rmse:7.86137
[50]	validation-rmse:7.85935
[51]	validation-rmse:7.85730
[52]	validation-rmse:7.85599
[53]	validation-rmse:7.85060
[54]	validation-rmse:7.84868
[55]	validation-rmse:7.84845
[56]	validation-rmse:7.84329
[57]	validation-rmse:7.84164
[58]	validation-rmse:7.83835
[59]	validation-rmse:7.83794
[60]	validation-rmse:7.83085
[61]	validation-rmse:7.82973
[62]	validation-rmse:7.82915
[63]	validation-rmse:7.82737
[64]	validation-rmse:7.82593
[65]	validation-rmse:7.82408
[66]	validation-rmse:7.82235
[67]	validation-rmse:7.82134
[68]	validation-rmse:7.82175
[69]	validation-rmse:7.82128
[70]	validation-rmse:7.82150
[71]	validation-rmse:7.81731
[72]	validation-rmse:7.81724
[73]	validation-rmse:7.81510
[74]	validation-rmse:7.81433
[75]	validation-rmse:7.81436
[76]	validation-rmse:7.81204
[77]	validation-rmse:7.81134
[78]	validation-rmse:7.80884
[79]	validation-rmse:7.80873
[80]	validation-rmse:7.80831
[81]	validation-rmse:7.80727
[82]	validation-rmse:7.80511
[83]	validation-rmse:7.80395
[84]	validation-rmse:7.80094
[85]	validation-rmse:7.79959
[86]	validation-rmse:7.80046
[87]	validation-rmse:7.79972
[88]	validation-rmse:7.79781
[89]	validation-rmse:7.79631
[90]	validation-rmse:7.79601
[91]	validation-rmse:7.79488
[92]	validation-rmse:7.79318
[93]	validation-rmse:7.79221
[94]	validation-rmse:7.79091
[95]	validation-rmse:7.79126
[96]	validation-rmse:7.79086
[97]	validation-rmse:7.78217
[98]	validation-rmse:7.78055
[99]	validation-rmse:7.78066
[100]	validation-rmse:7.78158
[101]	validation-rmse:7.77747
[102]	validation-rmse:7.77841
[103]	validation-rmse:7.77796
[104]	validation-rmse:7.77620
[105]	validation-rmse:7.77472
[106]	validation-rmse:7.77403
[107]	validation-rmse:7.77412
[108]	validation-rmse:7.77168
[109]	validation-rmse:7.77003
[110]	validation-rmse:7.77098
[111]	validation-rmse:7.77023
[112]	validation-rmse:7.77047
[113]	validation-rmse:7.76940
[114]	validation-rmse:7.76973
[115]	validation-rmse:7.76869
[116]	validation-rmse:7.76363
[117]	validation-rmse:7.76378
[118]	validation-rmse:7.76234
[119]	validation-rmse:7.76357
[120]	validation-rmse:7.76160
[121]	validation-rmse:7.76053
[122]	validation-rmse:7.75909
[123]	validation-rmse:7.75606
[124]	validation-rmse:7.75655
[125]	validation-rmse:7.75590
[126]	validation-rmse:7.75613
[127]	validation-rmse:7.75584
[128]	validation-rmse:7.75570
[129]	validation-rmse:7.75291
[130]	validation-rmse:7.75180
[131]	validation-rmse:7.75137
[132]	validation-rmse:7.74981
[133]	validation-rmse:7.74831
[134]	validation-rmse:7.74719
[135]	validation-rmse:7.74788
[136]	validation-rmse:7.74784
[137]	validation-rmse:7.74747
[138]	validation-rmse:7.74566
[139]	validation-rmse:7.74482
[140]	validation-rmse:7.74427
[141]	validation-rmse:7.74393
[142]	validation-rmse:7.74372
[143]	validation-rmse:7.74309
[144]	validation-rmse:7.74285
[145]	validation-rmse:7.74324
[146]	validation-rmse:7.74145
[147]	validation-rmse:7.73921
[148]	validation-rmse:7.73873
[149]	validation-rmse:7.73826
[150]	validation-rmse:7.73877
[151]	validation-rmse:7.73830
[152]	validation-rmse:7.73933
[153]	validation-rmse:7.73735
[154]	validation-rmse:7.73739
[155]	validation-rmse:7.73812
[156]	validation-rmse:7.73753
[157]	validation-rmse:7.73531
[158]	validation-rmse:7.73526
[159]	validation-rmse:7.73433
[160]	validation-rmse:7.73281
[161]	validation-rmse:7.73149
[162]	validation-rmse:7.73039
[163]	validation-rmse:7.73090
[164]	validation-rmse:7.73003
[165]	validation-rmse:7.73038
[166]	validation-rmse:7.72819
[167]	validation-rmse:7.72591
[168]	validation-rmse:7.72398
[169]	validation-rmse:7.72276
[170]	validation-rmse:7.72169
[171]	validation-rmse:7.72207
[172]	validation-rmse:7.72178
[173]	validation-rmse:7.72185
[174]	validation-rmse:7.72070
[175]	validation-rmse:7.71649
[176]	validation-rmse:7.71542
[177]	validation-rmse:7.71516
[178]	validation-rmse:7.71452
[179]	validation-rmse:7.71385
[180]	validation-rmse:7.71406
[181]	validation-rmse:7.71505
[182]	validation-rmse:7.71259
[183]	validation-rmse:7.71222
[184]	validation-rmse:7.71211
[185]	validation-rmse:7.70983
[186]	validation-rmse:7.70794
[187]	validation-rmse:7.70919
[188]	validation-rmse:7.70879
[189]	validation-rmse:7.70928
[190]	validation-rmse:7.70849
[191]	validation-rmse:7.70845
[192]	validation-rmse:7.70830
[193]	validation-rmse:7.70778
[194]	validation-rmse:7.70822
[195]	validation-rmse:7.70757
[196]	validation-rmse:7.70864
[197]	validation-rmse:7.70678
[198]	validation-rmse:7.70686
[199]	validation-rmse:7.70757
[200]	validation-rmse:7.70673
[201]	validation-rmse:7.70676
[202]	validation-rmse:7.70616
[203]	validation-rmse:7.70505
[204]	validation-rmse:7.70465
[205]	validation-rmse:7.70334
[206]	validation-rmse:7.70217
[207]	validation-rmse:7.70266
[208]	validation-rmse:7.70167
[209]	validation-rmse:7.70092
[210]	validation-rmse:7.69964
[211]	validation-rmse:7.69975
[212]	validation-rmse:7.69862
[213]	validation-rmse:7.69924
[214]	validation-rmse:7.69889
[215]	validation-rmse:7.69859
[216]	validation-rmse:7.69853
[217]	validation-rmse:7.69779
[218]	validation-rmse:7.69646
[219]	validation-rmse:7.69554
[220]	validation-rmse:7.69604
[221]	validation-rmse:7.69622
[222]	validation-rmse:7.69164
[223]	validation-rmse:7.69105
[224]	validation-rmse:7.68994
[225]	validation-rmse:7.68991
[226]	validation-rmse:7.68955
[227]	validation-rmse:7.68917
[228]	validation-rmse:7.68924
[229]	validation-rmse:7.68939
[230]	validation-rmse:7.68821
[231]	validation-rmse:7.68716
[232]	validation-rmse:7.68612
[233]	validation-rmse:7.68771
[234]	validation-rmse:7.68731
[235]	validation-rmse:7.68714
[236]	validation-rmse:7.68671
[237]	validation-rmse:7.68568
[238]	validation-rmse:7.68453
[239]	validation-rmse:7.68433
[240]	validation-rmse:7.68428
[241]	validation-rmse:7.68395
[242]	validation-rmse:7.68407
[243]	validation-rmse:7.68498
[244]	validation-rmse:7.68436
[245]	validation-rmse:7.68358
[246]	validation-rmse:7.68259
[247]	validation-rmse:7.68067
[248]	validation-rmse:7.67901
[249]	validation-rmse:7.67898
[250]	validation-rmse:7.67626
[251]	validation-rmse:7.67553
[252]	validation-rmse:7.67338
[253]	validation-rmse:7.67284
[254]	validation-rmse:7.67259
[255]	validation-rmse:7.67279
[256]	validation-rmse:7.67199
[257]	validation-rmse:7.67165
[258]	validation-rmse:7.67195
[259]	validation-rmse:7.66931
[260]	validation-rmse:7.66898
[261]	validation-rmse:7.66911
[262]	validation-rmse:7.66910
[263]	validation-rmse:7.66753
[264]	validation-rmse:7.66780
[265]	validation-rmse:7.66733
[266]	validation-rmse:7.66702
[267]	validation-rmse:7.66696
[268]	validation-rmse:7.66604
[269]	validation-rmse:7.66652
[270]	validation-rmse:7.66735
[271]	validation-rmse:7.66804
[272]	validation-rmse:7.66687
[273]	validation-rmse:7.66528
[274]	validation-rmse:7.66431
[275]	validation-rmse:7.66362
[276]	validation-rmse:7.66339
[277]	validation-rmse:7.66286
[278]	validation-rmse:7.65477
[279]	validation-rmse:7.65521
[280]	validation-rmse:7.65547
[281]	validation-rmse:7.65570
[282]	validation-rmse:7.65428
[283]	validation-rmse:7.65317
[284]	validation-rmse:7.65152
[285]	validation-rmse:7.65152
[286]	validation-rmse:7.65024
[287]	validation-rmse:7.64968
[288]	validation-rmse:7.64854
[289]	validation-rmse:7.64853
[290]	validation-rmse:7.64890
[291]	validation-rmse:7.64884
[292]	validation-rmse:7.64915
[293]	validation-rmse:7.64821
[294]	validation-rmse:7.64717
[295]	validation-rmse:7.64712
[296]	validation-rmse:7.64691
[297]	validation-rmse:7.64660
[298]	validation-rmse:7.64627
[299]	validation-rmse:7.64602
[300]	validation-rmse:7.64559
[301]	validation-rmse:7.64466
[302]	validation-rmse:7.64512
[303]	validation-rmse:7.64487
[304]	validation-rmse:7.64184
[305]	validation-rmse:7.64182
[306]	validation-rmse:7.64086
[307]	validation-rmse:7.64078
[308]	validation-rmse:7.64077
[309]	validation-rmse:7.64042
[310]	validation-rmse:7.64018
[311]	validation-rmse:7.63985
[312]	validation-rmse:7.64001
[313]	validation-rmse:7.64064
[314]	validation-rmse:7.63844
[315]	validation-rmse:7.63887
[316]	validation-rmse:7.63845
[317]	validation-rmse:7.63827
[318]	validation-rmse:7.63821
[319]	validation-rmse:7.64000
[320]	validation-rmse:7.63979
[321]	validation-rmse:7.63811
[322]	validation-rmse:7.63872
[323]	validation-rmse:7.63771
[324]	validation-rmse:7.63768
[325]	validation-rmse:7.63810
[326]	validation-rmse:7.63756
[327]	validation-rmse:7.63647
[328]	validation-rmse:7.63573
[329]	validation-rmse:7.63503
[330]	validation-rmse:7.63340
[331]	validation-rmse:7.63300
[332]	validation-rmse:7.63229
[333]	validation-rmse:7.63112
[334]	validation-rmse:7.63101
[335]	validation-rmse:7.63146
[336]	validation-rmse:7.63113
[337]	validation-rmse:7.63043
[338]	validation-rmse:7.63129
[339]	validation-rmse:7.63104
[340]	validation-rmse:7.63011
[341]	validation-rmse:7.62953
[342]	validation-rmse:7.63027
[343]	validation-rmse:7.63027
[344]	validation-rmse:7.62947
[345]	validation-rmse:7.62888
[346]	validation-rmse:7.62775
[347]	validation-rmse:7.62692
[348]	validation-rmse:7.62753
[349]	validation-rmse:7.62638
[350]	validation-rmse:7.62649
[351]	validation-rmse:7.62625
[352]	validation-rmse:7.62497
[353]	validation-rmse:7.62486
[354]	validation-rmse:7.62402
[355]	validation-rmse:7.62295
[356]	validation-rmse:7.62224
[357]	validation-rmse:7.62263
[358]	validation-rmse:7.62254
[359]	validation-rmse:7.62351
[360]	validation-rmse:7.62275
[361]	validation-rmse:7.62299
[362]	validation-rmse:7.62306
[363]	validation-rmse:7.62286
[364]	validation-rmse:7.62293
[365]	validation-rmse:7.62285
[366]	validation-rmse:7.62185
[367]	validation-rmse:7.62217
[368]	validation-rmse:7.62200
[369]	validation-rmse:7.62081
[370]	validation-rmse:7.62074
[371]	validation-rmse:7.62039
[372]	validation-rmse:7.61970
[373]	validation-rmse:7.62041
[374]	validation-rmse:7.61945
[375]	validation-rmse:7.61952
[376]	validation-rmse:7.61908
[377]	validation-rmse:7.61888
[378]	validation-rmse:7.61831
[379]	validation-rmse:7.61879
[380]	validation-rmse:7.61726
[381]	validation-rmse:7.61697
[382]	validation-rmse:7.61562
[383]	validation-rmse:7.61533
[384]	validation-rmse:7.61347
[385]	validation-rmse:7.61322
[386]	validation-rmse:7.61243
[387]	validation-rmse:7.61255
[388]	validation-rmse:7.61235
[389]	validation-rmse:7.61206
[390]	validation-rmse:7.61153
[391]	validation-rmse:7.61016
[392]	validation-rmse:7.60872
[393]	validation-rmse:7.60894
[394]	validation-rmse:7.60793
[395]	validation-rmse:7.60762
[396]	validation-rmse:7.60574
[397]	validation-rmse:7.60623
[398]	validation-rmse:7.60606
[399]	validation-rmse:7.60672
[400]	validation-rmse:7.60701
[401]	validation-rmse:7.60609
[402]	validation-rmse:7.60462
[403]	validation-rmse:7.60379
[404]	validation-rmse:7.60444
[405]	validation-rmse:7.60409
[406]	validation-rmse:7.60347
[407]	validation-rmse:7.60324
[408]	validation-rmse:7.60288
[409]	validation-rmse:7.60224
[410]	validation-rmse:7.60263
[411]	validation-rmse:7.60102
[412]	validation-rmse:7.60152
[413]	validation-rmse:7.60097
[414]	validation-rmse:7.59946
[415]	validation-rmse:7.59967
[416]	validation-rmse:7.59936
[417]	validation-rmse:7.59856
[418]	validation-rmse:7.59887
[419]	validation-rmse:7.59801
[420]	validation-rmse:7.59832
[421]	validation-rmse:7.59907
[422]	validation-rmse:7.59882
[423]	validation-rmse:7.59816
[424]	validation-rmse:7.59767
[425]	validation-rmse:7.59774
[426]	validation-rmse:7.59759
[427]	validation-rmse:7.59722
[428]	validation-rmse:7.59739
[429]	validation-rmse:7.59729
[430]	validation-rmse:7.59692
[431]	validation-rmse:7.59638
[432]	validation-rmse:7.59516
[433]	validation-rmse:7.59531
[434]	validation-rmse:7.59433
[435]	validation-rmse:7.59443
[436]	validation-rmse:7.59470
[437]	validation-rmse:7.59383
[438]	validation-rmse:7.59424
[439]	validation-rmse:7.59317
[440]	validation-rmse:7.59333
[441]	validation-rmse:7.59222
[442]	validation-rmse:7.58878
[443]	validation-rmse:7.58906
[444]	validation-rmse:7.58827
[445]	validation-rmse:7.58826
[446]	validation-rmse:7.58759
[447]	validation-rmse:7.58772
[448]	validation-rmse:7.58712
[449]	validation-rmse:7.58668
[450]	validation-rmse:7.58557
[451]	validation-rmse:7.58660
[452]	validation-rmse:7.58535
[453]	validation-rmse:7.58533
[454]	validation-rmse:7.58405
[455]	validation-rmse:7.58393
[456]	validation-rmse:7.58342
[457]	validation-rmse:7.58263
[458]	validation-rmse:7.58257
[459]	validation-rmse:7.58162
[460]	validation-rmse:7.58178
[461]	validation-rmse:7.58238
[462]	validation-rmse:7.58169
[463]	validation-rmse:7.58087
[464]	validation-rmse:7.58044
[465]	validation-rmse:7.58050
[466]	validation-rmse:7.57961
[467]	validation-rmse:7.57964
[468]	validation-rmse:7.57850
[469]	validation-rmse:7.57786
[470]	validation-rmse:7.57727
[471]	validation-rmse:7.57809
[472]	validation-rmse:7.57785
[473]	validation-rmse:7.57693
[474]	validation-rmse:7.57693
[475]	validation-rmse:7.57701
[476]	validation-rmse:7.57770
[477]	validation-rmse:7.57773
[478]	validation-rmse:7.57767
[479]	validation-rmse:7.57629
[480]	validation-rmse:7.57578
[481]	validation-rmse:7.57490
[482]	validation-rmse:7.57504
[483]	validation-rmse:7.57456
[484]	validation-rmse:7.57491
[485]	validation-rmse:7.57452
[486]	validation-rmse:7.57502
[487]	validation-rmse:7.57479
[488]	validation-rmse:7.57500
[489]	validation-rmse:7.57376
[490]	validation-rmse:7.57330
[491]	validation-rmse:7.57409
[492]	validation-rmse:7.57440
[493]	validation-rmse:7.57269
[494]	validation-rmse:7.57232
[495]	validation-rmse:7.57107
[496]	validation-rmse:7.57086
[497]	validation-rmse:7.56972
[498]	validation-rmse:7.57006
[499]	validation-rmse:7.57048
[500]	validation-rmse:7.57043
[501]	validation-rmse:7.56947
[502]	validation-rmse:7.56961
[503]	validation-rmse:7.56718
[504]	validation-rmse:7.56583
[505]	validation-rmse:7.56576
[506]	validation-rmse:7.56588
[507]	validation-rmse:7.56517
[508]	validation-rmse:7.56550
[509]	validation-rmse:7.56650
[510]	validation-rmse:7.56600
[511]	validation-rmse:7.56517
[512]	validation-rmse:7.56475
[513]	validation-rmse:7.56436
[514]	validation-rmse:7.56482
[515]	validation-rmse:7.56407
[516]	validation-rmse:7.56498
[517]	validation-rmse:7.56328
[518]	validation-rmse:7.56329
[519]	validation-rmse:7.56205
[520]	validation-rmse:7.56215
[521]	validation-rmse:7.56263
[522]	validation-rmse:7.56263
[523]	validation-rmse:7.56271
[524]	validation-rmse:7.56235
[525]	validation-rmse:7.56163
[526]	validation-rmse:7.56114
[527]	validation-rmse:7.56003
[528]	validation-rmse:7.56059
[529]	validation-rmse:7.55995
[530]	validation-rmse:7.55876
[531]	validation-rmse:7.55819
[532]	validation-rmse:7.55786
[533]	validation-rmse:7.55722
[534]	validation-rmse:7.55676
[535]	validation-rmse:7.55746
[536]	validation-rmse:7.55711
[537]	validation-rmse:7.55687
[538]	validation-rmse:7.55700
[539]	validation-rmse:7.55702
[540]	validation-rmse:7.55659
[541]	validation-rmse:7.55668
[542]	validation-rmse:7.55520
[543]	validation-rmse:7.55544
[544]	validation-rmse:7.55468
[545]	validation-rmse:7.55434
[546]	validation-rmse:7.55315
[547]	validation-rmse:7.55259
[548]	validation-rmse:7.55218
[549]	validation-rmse:7.55212
[550]	validation-rmse:7.55245
[551]	validation-rmse:7.55150
[552]	validation-rmse:7.55163
[553]	validation-rmse:7.55062
[554]	validation-rmse:7.55086
[555]	validation-rmse:7.55059
[556]	validation-rmse:7.55054
[557]	validation-rmse:7.55100
[558]	validation-rmse:7.55058
[559]	validation-rmse:7.55120
[560]	validation-rmse:7.55052
[561]	validation-rmse:7.54956
[562]	validation-rmse:7.54861
[563]	validation-rmse:7.54952
[564]	validation-rmse:7.54892
[565]	validation-rmse:7.54851
[566]	validation-rmse:7.54818
[567]	validation-rmse:7.54715
[568]	validation-rmse:7.54691
[569]	validation-rmse:7.54696
[570]	validation-rmse:7.54764
[571]	validation-rmse:7.54735
[572]	validation-rmse:7.54641
[573]	validation-rmse:7.54581
[574]	validation-rmse:7.54551
[575]	validation-rmse:7.54490
[576]	validation-rmse:7.54482
[577]	validation-rmse:7.54500
[578]	validation-rmse:7.54478
[579]	validation-rmse:7.54431
[580]	validation-rmse:7.54422
[581]	validation-rmse:7.54375
[582]	validation-rmse:7.54354
[583]	validation-rmse:7.54340
[584]	validation-rmse:7.54380
[585]	validation-rmse:7.54283
[586]	validation-rmse:7.53957
[587]	validation-rmse:7.54024
[588]	validation-rmse:7.53985
[589]	validation-rmse:7.53951
[590]	validation-rmse:7.53999
[591]	validation-rmse:7.54050
[592]	validation-rmse:7.54033
[593]	validation-rmse:7.53917
[594]	validation-rmse:7.53871
[595]	validation-rmse:7.53877
[596]	validation-rmse:7.53825
[597]	validation-rmse:7.53863
[598]	validation-rmse:7.53864
[599]	validation-rmse:7.53845
[600]	validation-rmse:7.53827
[601]	validation-rmse:7.53780
[602]	validation-rmse:7.53654
[603]	validation-rmse:7.53633
[604]	validation-rmse:7.53645
[605]	validation-rmse:7.53685
[606]	validation-rmse:7.53714
[607]	validation-rmse:7.53618
[608]	validation-rmse:7.53629
[609]	validation-rmse:7.53591
[610]	validation-rmse:7.53563
[611]	validation-rmse:7.53501
[612]	validation-rmse:7.53450
[613]	validation-rmse:7.53485
[614]	validation-rmse:7.53427
[615]	validation-rmse:7.53443
[616]	validation-rmse:7.53430
[617]	validation-rmse:7.53405
[618]	validation-rmse:7.53247
[619]	validation-rmse:7.53200
[620]	validation-rmse:7.53079
[621]	validation-rmse:7.53087
[622]	validation-rmse:7.53086
[623]	validation-rmse:7.53012
[624]	validation-rmse:7.52875
[625]	validation-rmse:7.52888
[626]	validation-rmse:7.52937
[627]	validation-rmse:7.52960
[628]	validation-rmse:7.52940
[629]	validation-rmse:7.52965
[630]	validation-rmse:7.52894
[631]	validation-rmse:7.52818
[632]	validation-rmse:7.52822
[633]	validation-rmse:7.52785
[634]	validation-rmse:7.52779
[635]	validation-rmse:7.52679
[636]	validation-rmse:7.52636
[637]	validation-rmse:7.52714
[638]	validation-rmse:7.52689
[639]	validation-rmse:7.52641
[640]	validation-rmse:7.52594
[641]	validation-rmse:7.52666
[642]	validation-rmse:7.52519
[643]	validation-rmse:7.52481
[644]	validation-rmse:7.52494
[645]	validation-rmse:7.52570
[646]	validation-rmse:7.52452
[647]	validation-rmse:7.52381
[648]	validation-rmse:7.52335
[649]	validation-rmse:7.52349
[650]	validation-rmse:7.52282
[651]	validation-rmse:7.52335
[652]	validation-rmse:7.52324
[653]	validation-rmse:7.52309
[654]	validation-rmse:7.52226
[655]	validation-rmse:7.52203
[656]	validation-rmse:7.52129
[657]	validation-rmse:7.52187
[658]	validation-rmse:7.52208
[659]	validation-rmse:7.52205
[660]	validation-rmse:7.52189
[661]	validation-rmse:7.52123
[662]	validation-rmse:7.52079
[663]	validation-rmse:7.52013
[664]	validation-rmse:7.52086
[665]	validation-rmse:7.52086
[666]	validation-rmse:7.52070
[667]	validation-rmse:7.51992
[668]	validation-rmse:7.51782
[669]	validation-rmse:7.51775
[670]	validation-rmse:7.51728
[671]	validation-rmse:7.51692

[12:55:09] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[4]	validation-rmse:11.28890
[5]	validation-rmse:11.10834
[6]	validation-rmse:10.99511
[7]	validation-rmse:10.88654
[8]	validation-rmse:10.82304
[9]	validation-rmse:10.73814
[10]	validation-rmse:10.68873
[11]	validation-rmse:10.65661
[12]	validation-rmse:10.61107
[13]	validation-rmse:10.57925
[14]	validation-rmse:10.53434
[15]	validation-rmse:10.50848
[16]	validation-rmse:10.48318
[17]	validation-rmse:10.43521
[18]	validation-rmse:10.41775
[19]	validation-rmse:10.40243
[20]	validation-rmse:10.38587
[21]	validation-rmse:10.33976
[22]	validation-rmse:10.32307
[23]	validation-rmse:10.28996
[24]	validation-rmse:10.26991
[25]	validation-rmse:10.25709
[26]	validation-rmse:10.23458
[27]	validation-rmse:10.22379
[28]	validation-rmse:10.21122
[29]	validation-rmse:10.18419
[30]	validation-rmse:10.16780
[31]	validation-rmse:10.13988
[32]	validation-rmse:10.12720
[33]	validation-rmse:10.11077
[34]	validation-rmse:10.10276
[35]	validation-rmse:10.09495
[36]	validation-rmse:10.07206
[37]	validation-rmse:10.06619
[38]	validation-rmse:10.04717
[39]	validation-rmse:10.03543
[40]	validation-rmse:10.01779
[41]	validation-rmse:10.01293
[42]	validation-rmse:10.00121
[43]	validation-rmse:9.99361
[44]	validation-rmse:9.98881
[45]	validation-rmse:9.98268
[46]	validation-rmse:9.95890
[47]	validation-rmse:9.95119
[48]	validation-rmse:9.93492
[49]	validation-rmse:9.92853
[50]	validation-rmse:9.91747
[51]	validation-rmse:9.91445
[52]	validation-rmse:9.90439
[53]	validation-rmse:9.89961
[54]	validation-rmse:9.89167
[55]	validation-rmse:9.88256
[56]	validation-rmse:9.85223
[57]	validation-rmse:9.83945
[58]	validation-rmse:9.83347
[59]	validation-rmse:9.82943
[60]	validation-rmse:9.81092
[61]	validation-rmse:9.80415
[62]	validation-rmse:9.76925
[63]	validation-rmse:9.75590
[64]	validation-rmse:9.75174
[65]	validation-rmse:9.74876
[66]	validation-rmse:9.74187
[67]	validation-rmse:9.73905
[68]	validation-rmse:9.73221
[69]	validation-rmse:9.71018
[70]	validation-rmse:9.70383
[71]	validation-rmse:9.69914
[72]	validation-rmse:9.69356
[73]	validation-rmse:9.68662
[74]	validation-rmse:9.67980
[75]	validation-rmse:9.67661
[76]	validation-rmse:9.67054
[77]	validation-rmse:9.66873
[78]	validation-rmse:9.66730
[79]	validation-rmse:9.66513
[80]	validation-rmse:9.65819
[81]	validation-rmse:9.65231
[82]	validation-rmse:9.64250
[83]	validation-rmse:9.63770
[84]	validation-rmse:9.63384
[85]	validation-rmse:9.63006
[86]	validation-rmse:9.62405
[87]	validation-rmse:9.62166
[88]	validation-rmse:9.62062
[89]	validation-rmse:9.61656
[90]	validation-rmse:9.61468
[91]	validation-rmse:9.60812
[92]	validation-rmse:9.60114
[93]	validation-rmse:9.59028
[94]	validation-rmse:9.58242
[95]	validation-rmse:9.57695
[96]	validation-rmse:9.57407
[97]	validation-rmse:9.57248
[98]	validation-rmse:9.57151
[99]	validation-rmse:9.56423
[100]	validation-rmse:9.55961
[101]	validation-rmse:9.55679
[102]	validation-rmse:9.55347
[103]	validation-rmse:9.55014
[104]	validation-rmse:9.54231
[105]	validation-rmse:9.53888
[106]	validation-rmse:9.53688
[107]	validation-rmse:9.52642
[108]	validation-rmse:9.51804
[109]	validation-rmse:9.51448
[110]	validation-rmse:9.51219
[111]	validation-rmse:9.50922
[112]	validation-rmse:9.50231
[113]	validation-rmse:9.50051
[114]	validation-rmse:9.49990
[115]	validation-rmse:9.49867
[116]	validation-rmse:9.49660
[117]	validation-rmse:9.49539
[118]	validation-rmse:9.49182
[119]	validation-rmse:9.49037
[120]	validation-rmse:9.48708
[121]	validation-rmse:9.48626
[122]	validation-rmse:9.48562
[123]	validation-rmse:9.48481
[124]	validation-rmse:9.48355
[125]	validation-rmse:9.48263
[126]	validation-rmse:9.48225
[127]	validation-rmse:9.48120
[128]	validation-rmse:9.47817
[129]	validation-rmse:9.47709
[130]	validation-rmse:9.47474
[131]	validation-rmse:9.46738
[132]	validation-rmse:9.46396
[133]	validation-rmse:9.46185
[134]	validation-rmse:9.46095
[135]	validation-rmse:9.46028
[136]	validation-rmse:9.45885
[137]	validation-rmse:9.45819
[138]	validation-rmse:9.45702
[139]	validation-rmse:9.45656
[140]	validation-rmse:9.45196
[141]	validation-rmse:9.44976
[142]	validation-rmse:9.44838
[143]	validation-rmse:9.44754
[144]	validation-rmse:9.44615
[145]	validation-rmse:9.44591
[146]	validation-rmse:9.44498
[147]	validation-rmse:9.44345
[148]	validation-rmse:9.44301
[149]	validation-rmse:9.44264
[150]	validation-rmse:9.44174
[151]	validation-rmse:9.44014
[152]	validation-rmse:9.43557
[153]	validation-rmse:9.43508
[154]	validation-rmse:9.43477
[155]	validation-rmse:9.43322
[156]	validation-rmse:9.43282
[157]	validation-rmse:9.43232
[158]	validation-rmse:9.43154
[159]	validation-rmse:9.43088
[160]	validation-rmse:9.43033
[161]	validation-rmse:9.42960
[162]	validation-rmse:9.42947
[163]	validation-rmse:9.42860
[164]	validation-rmse:9.42872
[165]	validation-rmse:9.42776
[166]	validation-rmse:9.42569
[167]	validation-rmse:9.42350
[168]	validation-rmse:9.42316
[169]	validation-rmse:9.42272
[170]	validation-rmse:9.42236
[171]	validation-rmse:9.42098
[172]	validation-rmse:9.41880
[173]	validation-rmse:9.41186
[174]	validation-rmse:9.40806
[175]	validation-rmse:9.40578
[176]	validation-rmse:9.39124
[177]	validation-rmse:9.38981
[178]	validation-rmse:9.38547
[179]	validation-rmse:9.35465
[180]	validation-rmse:9.34574
[181]	validation-rmse:9.33251
[182]	validation-rmse:9.31982
[183]	validation-rmse:9.31550
[184]	validation-rmse:9.30711
[185]	validation-rmse:9.29935
[186]	validation-rmse:9.29828
[187]	validation-rmse:9.29208
[188]	validation-rmse:9.28709
[189]	validation-rmse:9.28674
[190]	validation-rmse:9.28317
[191]	validation-rmse:9.28016
[192]	validation-rmse:9.27793
[193]	validation-rmse:9.27224
[194]	validation-rmse:9.26957
[195]	validation-rmse:9.26921
[196]	validation-rmse:9.26087
[197]	validation-rmse:9.26002
[198]	validation-rmse:9.25581
[199]	validation-rmse:9.25012
[200]	validation-rmse:9.24884
[201]	validation-rmse:9.23787
[202]	validation-rmse:9.22488
[203]	validation-rmse:9.22419
[204]	validation-rmse:9.22194
[205]	validation-rmse:9.21870
[206]	validation-rmse:9.21681
[207]	validation-rmse:9.21573
[208]	validation-rmse:9.21356
[209]	validation-rmse:9.21074
[210]	validation-rmse:9.20274
[211]	validation-rmse:9.20166
[212]	validation-rmse:9.20034
[213]	validation-rmse:9.19739
[214]	validation-rmse:9.19616
[215]	validation-rmse:9.18905
[216]	validation-rmse:9.18407
[217]	validation-rmse:9.18266
[218]	validation-rmse:9.18151
[219]	validation-rmse:9.18027
[220]	validation-rmse:9.17810
[221]	validation-rmse:9.17736
[222]	validation-rmse:9.17495
[223]	validation-rmse:9.17413
[224]	validation-rmse:9.17084
[225]	validation-rmse:9.17054
[226]	validation-rmse:9.16988
[227]	validation-rmse:9.16952
[228]	validation-rmse:9.16903
[229]	validation-rmse:9.16859
[230]	validation-rmse:9.16773
[231]	validation-rmse:9.16622
[232]	validation-rmse:9.16586
[233]	validation-rmse:9.16459
[234]	validation-rmse:9.16427
[235]	validation-rmse:9.16388
[236]	validation-rmse:9.16305
[237]	validation-rmse:9.16268
[238]	validation-rmse:9.16218
[239]	validation-rmse:9.16184
[240]	validation-rmse:9.16120
[241]	validation-rmse:9.16040
[242]	validation-rmse:9.15983
[243]	validation-rmse:9.15836
[244]	validation-rmse:9.15763
[245]	validation-rmse:9.15638
[246]	validation-rmse:9.15572
[247]	validation-rmse:9.15535
[248]	validation-rmse:9.15487
[249]	validation-rmse:9.15384
[250]	validation-rmse:9.15267
[251]	validation-rmse:9.15175
[252]	validation-rmse:9.15158
[253]	validation-rmse:9.15058
[254]	validation-rmse:9.15013
[255]	validation-rmse:9.14866
[256]	validation-rmse:9.14829
[257]	validation-rmse:9.14752
[258]	validation-rmse:9.14685
[259]	validation-rmse:9.14612
[260]	validation-rmse:9.14487
[261]	validation-rmse:9.14454
[262]	validation-rmse:9.14398
[263]	validation-rmse:9.14356
[264]	validation-rmse:9.14305
[265]	validation-rmse:9.14250
[266]	validation-rmse:9.14291
[267]	validation-rmse:9.14241
[268]	validation-rmse:9.14177
[269]	validation-rmse:9.14054
[270]	validation-rmse:9.14020
[271]	validation-rmse:9.13984
[272]	validation-rmse:9.13939
[273]	validation-rmse:9.13920
[274]	validation-rmse:9.13932
[275]	validation-rmse:9.13926
[276]	validation-rmse:9.13935
[277]	validation-rmse:9.13958
[278]	validation-rmse:9.13962
[279]	validation-rmse:9.13884
[280]	validation-rmse:9.13814
[281]	validation-rmse:9.13672
[282]	validation-rmse:9.13651
[283]	validation-rmse:9.13588
[284]	validation-rmse:9.13563
[285]	validation-rmse:9.13508
[286]	validation-rmse:9.13471
[287]	validation-rmse:9.13353
[288]	validation-rmse:9.13375
[289]	validation-rmse:9.13218
[290]	validation-rmse:9.13076
[291]	validation-rmse:9.12796
[292]	validation-rmse:9.12588
[293]	validation-rmse:9.12532
[294]	validation-rmse:9.12383
[295]	validation-rmse:9.12265
[296]	validation-rmse:9.12182
[297]	validation-rmse:9.12126
[298]	validation-rmse:9.12052
[299]	validation-rmse:9.12000
[300]	validation-rmse:9.11938
[301]	validation-rmse:9.11932
[302]	validation-rmse:9.11860
[303]	validation-rmse:9.11840
[304]	validation-rmse:9.11687
[305]	validation-rmse:9.11587
[306]	validation-rmse:9.11423
[307]	validation-rmse:9.11275
[308]	validation-rmse:9.11012
[309]	validation-rmse:9.10885
[310]	validation-rmse:9.10703
[311]	validation-rmse:9.10634
[312]	validation-rmse:9.10477
[313]	validation-rmse:9.10354
[314]	validation-rmse:9.10101
[315]	validation-rmse:9.09858
[316]	validation-rmse:9.09759
[317]	validation-rmse:9.09690
[318]	validation-rmse:9.09520
[319]	validation-rmse:9.09441
[320]	validation-rmse:9.09233
[321]	validation-rmse:9.09135
[322]	validation-rmse:9.09024
[323]	validation-rmse:9.09020
[324]	validation-rmse:9.08860
[325]	validation-rmse:9.08849
[326]	validation-rmse:9.08759
[327]	validation-rmse:9.08713
[328]	validation-rmse:9.08496
[329]	validation-rmse:9.08410
[330]	validation-rmse:9.08151
[331]	validation-rmse:9.08091
[332]	validation-rmse:9.07973
[333]	validation-rmse:9.07864
[334]	validation-rmse:9.07761
[335]	validation-rmse:9.07686
[336]	validation-rmse:9.07532
[337]	validation-rmse:9.07485
[338]	validation-rmse:9.07375
[339]	validation-rmse:9.07297
[340]	validation-rmse:9.07129
[341]	validation-rmse:9.07164
[342]	validation-rmse:9.07056
[343]	validation-rmse:9.06984
[344]	validation-rmse:9.06894
[345]	validation-rmse:9.06800
[346]	validation-rmse:9.06743
[347]	validation-rmse:9.06679
[348]	validation-rmse:9.06605
[349]	validation-rmse:9.06616
[350]	validation-rmse:9.06515
[351]	validation-rmse:9.06530
[352]	validation-rmse:9.06445
[353]	validation-rmse:9.06412
[354]	validation-rmse:9.06297
[355]	validation-rmse:9.06286
[356]	validation-rmse:9.06241
[357]	validation-rmse:9.06212
[358]	validation-rmse:9.06129
[359]	validation-rmse:9.06068
[360]	validation-rmse:9.06029
[361]	validation-rmse:9.05970
[362]	validation-rmse:9.05914
[363]	validation-rmse:9.05859
[364]	validation-rmse:9.05794
[365]	validation-rmse:9.05684
[366]	validation-rmse:9.05394
[367]	validation-rmse:9.05343
[368]	validation-rmse:9.05219
[369]	validation-rmse:9.05200
[370]	validation-rmse:9.05089
[371]	validation-rmse:9.04463
[372]	validation-rmse:9.04427
[373]	validation-rmse:9.04333
[374]	validation-rmse:9.04273
[375]	validation-rmse:9.04203
[376]	validation-rmse:9.04118
[377]	validation-rmse:9.04048
[378]	validation-rmse:9.04048
[379]	validation-rmse:9.03984
[380]	validation-rmse:9.03946
[381]	validation-rmse:9.03867
[382]	validation-rmse:9.03825
[383]	validation-rmse:9.03800
[384]	validation-rmse:9.03735
[385]	validation-rmse:9.03669
[386]	validation-rmse:9.03582
[387]	validation-rmse:9.03491
[388]	validation-rmse:9.03428
[389]	validation-rmse:9.03452
[390]	validation-rmse:9.03407
[391]	validation-rmse:9.03392
[392]	validation-rmse:9.03369
[393]	validation-rmse:9.03284
[394]	validation-rmse:9.02968
[395]	validation-rmse:9.02901
[396]	validation-rmse:9.02900
[397]	validation-rmse:9.02802
[398]	validation-rmse:9.02764
[399]	validation-rmse:9.02705
[400]	validation-rmse:9.02563
[401]	validation-rmse:9.02513
[402]	validation-rmse:9.02448
[403]	validation-rmse:9.02410
[404]	validation-rmse:9.02333
[405]	validation-rmse:9.02277
[406]	validation-rmse:9.02219
[407]	validation-rmse:9.02123
[408]	validation-rmse:9.02019
[409]	validation-rmse:9.01975
[410]	validation-rmse:9.01814
[411]	validation-rmse:9.01682
[412]	validation-rmse:9.01646
[413]	validation-rmse:9.01551
[414]	validation-rmse:9.01539
[415]	validation-rmse:9.01439
[416]	validation-rmse:9.01422
[417]	validation-rmse:9.01457
[418]	validation-rmse:9.01418
[419]	validation-rmse:9.01314
[420]	validation-rmse:9.01257
[421]	validation-rmse:9.01182
[422]	validation-rmse:9.01141
[423]	validation-rmse:9.01074
[424]	validation-rmse:9.01037
[425]	validation-rmse:9.00870
[426]	validation-rmse:9.00814
[427]	validation-rmse:9.00750
[428]	validation-rmse:9.00698
[429]	validation-rmse:9.00677
[430]	validation-rmse:9.00662
[431]	validation-rmse:9.00624
[432]	validation-rmse:9.00516
[433]	validation-rmse:9.00511
[434]	validation-rmse:9.00433
[435]	validation-rmse:9.00386
[436]	validation-rmse:9.00315
[437]	validation-rmse:9.00275
[438]	validation-rmse:9.00218
[439]	validation-rmse:9.00191
[440]	validation-rmse:9.00088
[441]	validation-rmse:9.00008
[442]	validation-rmse:8.99990
[443]	validation-rmse:8.99897
[444]	validation-rmse:8.99888
[445]	validation-rmse:8.99801
[446]	validation-rmse:8.99816
[447]	validation-rmse:8.99726
[448]	validation-rmse:8.99718
[449]	validation-rmse:8.99684
[450]	validation-rmse:8.99685
[451]	validation-rmse:8.99626
[452]	validation-rmse:8.99606
[453]	validation-rmse:8.99432
[454]	validation-rmse:8.99430
[455]	validation-rmse:8.99318
[456]	validation-rmse:8.99333
[457]	validation-rmse:8.99303
[458]	validation-rmse:8.99308
[459]	validation-rmse:8.99238
[460]	validation-rmse:8.99252
[461]	validation-rmse:8.99133
[462]	validation-rmse:8.99097
[463]	validation-rmse:8.99063
[464]	validation-rmse:8.98973
[465]	validation-rmse:8.98949
[466]	validation-rmse:8.98871
[467]	validation-rmse:8.98903
[468]	validation-rmse:8.98832
[469]	validation-rmse:8.98800
[470]	validation-rmse:8.98724
[471]	validation-rmse:8.98646
[472]	validation-rmse:8.98614
[473]	validation-rmse:8.98566
[474]	validation-rmse:8.98545
[475]	validation-rmse:8.98493
[476]	validation-rmse:8.98487
[477]	validation-rmse:8.98343
[478]	validation-rmse:8.98338
[479]	validation-rmse:8.98304
[480]	validation-rmse:8.98279
[481]	validation-rmse:8.98228
[482]	validation-rmse:8.98201
[483]	validation-rmse:8.98200
[484]	validation-rmse:8.98158
[485]	validation-rmse:8.98147
[486]	validation-rmse:8.98067
[487]	validation-rmse:8.98047
[488]	validation-rmse:8.98020
[489]	validation-rmse:8.97941
[490]	validation-rmse:8.97916
[491]	validation-rmse:8.97849
[492]	validation-rmse:8.97810
[493]	validation-rmse:8.97835
[494]	validation-rmse:8.97797
[495]	validation-rmse:8.97780
[496]	validation-rmse:8.97736
[497]	validation-rmse:8.97722
[498]	validation-rmse:8.97680
[499]	validation-rmse:8.97660
[500]	validation-rmse:8.97668
[501]	validation-rmse:8.97622
[502]	validation-rmse:8.97542
[503]	validation-rmse:8.97466
[504]	validation-rmse:8.97369
[505]	validation-rmse:8.97297
[506]	validation-rmse:8.97255
[507]	validation-rmse:8.97202
[508]	validation-rmse:8.97154
[509]	validation-rmse:8.97115
[510]	validation-rmse:8.97119
[511]	validation-rmse:8.97066
[512]	validation-rmse:8.97082
[513]	validation-rmse:8.97053
[514]	validation-rmse:8.96915
[515]	validation-rmse:8.96815
[516]	validation-rmse:8.96801
[517]	validation-rmse:8.96760
[518]	validation-rmse:8.96731
[519]	validation-rmse:8.96561
[520]	validation-rmse:8.96528
[521]	validation-rmse:8.96473
[522]	validation-rmse:8.96367
[523]	validation-rmse:8.96367
[524]	validation-rmse:8.96370
[525]	validation-rmse:8.96337
[526]	validation-rmse:8.96332
[527]	validation-rmse:8.96282
[528]	validation-rmse:8.96215
[529]	validation-rmse:8.96041
[530]	validation-rmse:8.95959
[531]	validation-rmse:8.95774
[532]	validation-rmse:8.95591
[533]	validation-rmse:8.95522
[534]	validation-rmse:8.95423
[535]	validation-rmse:8.95343
[536]	validation-rmse:8.95176
[537]	validation-rmse:8.95064
[538]	validation-rmse:8.95038
[539]	validation-rmse:8.94914
[540]	validation-rmse:8.94893
[541]	validation-rmse:8.94883
[542]	validation-rmse:8.94874
[543]	validation-rmse:8.94867
[544]	validation-rmse:8.94796
[545]	validation-rmse:8.94744
[546]	validation-rmse:8.94705
[547]	validation-rmse:8.94664
[548]	validation-rmse:8.94631
[549]	validation-rmse:8.94596
[550]	validation-rmse:8.94575
[551]	validation-rmse:8.94562
[552]	validation-rmse:8.94520
[553]	validation-rmse:8.94492
[554]	validation-rmse:8.94499
[555]	validation-rmse:8.94434
[556]	validation-rmse:8.94446
[557]	validation-rmse:8.94422
[558]	validation-rmse:8.94356
[559]	validation-rmse:8.94331
[560]	validation-rmse:8.94230
[561]	validation-rmse:8.94185
[562]	validation-rmse:8.94145
[563]	validation-rmse:8.94152
[564]	validation-rmse:8.94140
[565]	validation-rmse:8.94076
[566]	validation-rmse:8.94050
[567]	validation-rmse:8.94040
[568]	validation-rmse:8.93960
[569]	validation-rmse:8.93938
[570]	validation-rmse:8.93842
[571]	validation-rmse:8.93840
[572]	validation-rmse:8.93758
[573]	validation-rmse:8.93743
[574]	validation-rmse:8.93618
[575]	validation-rmse:8.93494
[576]	validation-rmse:8.93430
[577]	validation-rmse:8.93336
[578]	validation-rmse:8.93245
[579]	validation-rmse:8.93245
[580]	validation-rmse:8.93168
[581]	validation-rmse:8.93130
[582]	validation-rmse:8.93056
[583]	validation-rmse:8.93006
[584]	validation-rmse:8.92946
[585]	validation-rmse:8.92923
[586]	validation-rmse:8.92898
[587]	validation-rmse:8.92926
[588]	validation-rmse:8.92860
[589]	validation-rmse:8.92858
[590]	validation-rmse:8.92813
[591]	validation-rmse:8.92758
[592]	validation-rmse:8.92473
[593]	validation-rmse:8.92370
[594]	validation-rmse:8.92188
[595]	validation-rmse:8.92066
[596]	validation-rmse:8.92025
[597]	validation-rmse:8.91922
[598]	validation-rmse:8.91858
[599]	validation-rmse:8.91833
[600]	validation-rmse:8.91792
[601]	validation-rmse:8.91633
[602]	validation-rmse:8.91531
[603]	validation-rmse:8.91528
[604]	validation-rmse:8.91526
[605]	validation-rmse:8.91497
[606]	validation-rmse:8.91501
[607]	validation-rmse:8.91386
[608]	validation-rmse:8.91336
[609]	validation-rmse:8.91285
[610]	validation-rmse:8.91231
[611]	validation-rmse:8.91153
[612]	validation-rmse:8.91122
[613]	validation-rmse:8.91066
[614]	validation-rmse:8.91019
[615]	validation-rmse:8.90909
[616]	validation-rmse:8.90911
[617]	validation-rmse:8.90874
[618]	validation-rmse:8.90813
[619]	validation-rmse:8.90753
[620]	validation-rmse:8.90742
[621]	validation-rmse:8.90647
[622]	validation-rmse:8.90609
[623]	validation-rmse:8.90553
[624]	validation-rmse:8.90507
[625]	validation-rmse:8.90456
[626]	validation-rmse:8.90424
[627]	validation-rmse:8.90363
[628]	validation-rmse:8.90337
[629]	validation-rmse:8.90298
[630]	validation-rmse:8.90231
[631]	validation-rmse:8.90125
[632]	validation-rmse:8.90029
[633]	validation-rmse:8.89919
[634]	validation-rmse:8.89889
[635]	validation-rmse:8.89881
[636]	validation-rmse:8.89855
[637]	validation-rmse:8.89857
[638]	validation-rmse:8.89798
[639]	validation-rmse:8.89812
[640]	validation-rmse:8.89745
[641]	validation-rmse:8.89517
[642]	validation-rmse:8.89491
[643]	validation-rmse:8.89443
[644]	validation-rmse:8.89404
[645]	validation-rmse:8.89360
[646]	validation-rmse:8.89360
[647]	validation-rmse:8.89323
[648]	validation-rmse:8.89294
[649]	validation-rmse:8.89314
[650]	validation-rmse:8.89285
[651]	validation-rmse:8.89304
[652]	validation-rmse:8.89252
[653]	validation-rmse:8.89291
[654]	validation-rmse:8.89168
[655]	validation-rmse:8.88978
[656]	validation-rmse:8.88816
[657]	validation-rmse:8.88777
[658]	validation-rmse:8.88730
[659]	validation-rmse:8.88656
[660]	validation-rmse:8.88661
[661]	validation-rmse:8.88289
[662]	validation-rmse:8.88177
[663]	validation-rmse:8.88102
[664]	validation-rmse:8.88007
[665]	validation-rmse:8.87989
[666]	validation-rmse:8.87859
[667]	validation-rmse:8.87727
[668]	validation-rmse:8.87669
[669]	validation-rmse:8.87640
[670]	validation-rmse:8.87533
[671]	validation-rmse:8.87419

[12:56:11] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:11.84435
[2]	validation-rmse:10.26093
[3]	validation-rmse:9.58425
[4]	validation-rmse:9.24817
[5]	validation-rmse:8.99132
[6]	validation-rmse:8.86712
[7]	validation-rmse:8.75524
[8]	validation-rmse:8.68393
[9]	validation-rmse:8.62860
[10]	validation-rmse:8.58177
[11]	validation-rmse:8.55327
[12]	validation-rmse:8.52883
[13]	validation-rmse:8.49628
[14]	validation-rmse:8.47332
[15]	validation-rmse:8.44950
[16]	validation-rmse:8.43100
[17]	validation-rmse:8.41324
[18]	validation-rmse:8.39401
[19]	validation-rmse:8.37227
[20]	validation-rmse:8.34813
[21]	validation-rmse:8.32249
[22]	validation-rmse:8.30142
[23]	validation-rmse:8.27909
[24]	validation-rmse:8.26060
[25]	validation-rmse:8.24819
[26]	validation-rmse:8.23070
[27]	validation-rmse:8.21212
[28]	validation-rmse:8.19361
[29]	validation-rmse:8.17877
[30]	validation-rmse:8.16469
[31]	validation-rmse:8.14766
[32]	validation-rmse:8.12986
[33]	validation-rmse:8.11431
[34]	validation-rmse:8.09743
[35]	validation-rmse:8.08179
[36]	validation-rmse:8.06866
[37]	validation-rmse:8.05696
[38]	validation-rmse:8.04340
[39]	validation-rmse:8.03696
[40]	validation-rmse:8.02553
[41]	validation-rmse:8.01919
[42]	validation-rmse:8.01646
[43]	validation-rmse:8.00820
[44]	validation-rmse:8.00033
[45]	validation-rmse:7.98583
[46]	validation-rmse:7.97724
[47]	validation-rmse:7.96596
[48]	validation-rmse:7.95717
[49]	validation-rmse:7.94832
[50]	validation-rmse:7.94228
[51]	validation-rmse:7.93442
[52]	validation-rmse:7.92728
[53]	validation-rmse:7.91904
[54]	validation-rmse:7.91474
[55]	validation-rmse:7.90895
[56]	validation-rmse:7.90231
[57]	validation-rmse:7.89105
[58]	validation-rmse:7.87905
[59]	validation-rmse:7.87218
[60]	validation-rmse:7.86513
[61]	validation-rmse:7.85861
[62]	validation-rmse:7.85375
[63]	validation-rmse:7.84699
[64]	validation-rmse:7.84172
[65]	validation-rmse:7.83309
[66]	validation-rmse:7.82470
[67]	validation-rmse:7.82103
[68]	validation-rmse:7.81592
[69]	validation-rmse:7.80977
[70]	validation-rmse:7.80136
[71]	validation-rmse:7.79238
[72]	validation-rmse:7.78813
[73]	validation-rmse:7.78152
[74]	validation-rmse:7.77700
[75]	validation-rmse:7.77429
[76]	validation-rmse:7.76460
[77]	validation-rmse:7.75593
[78]	validation-rmse:7.74828
[79]	validation-rmse:7.73252
[80]	validation-rmse:7.72302
[81]	validation-rmse:7.71401
[82]	validation-rmse:7.70687
[83]	validation-rmse:7.70138
[84]	validation-rmse:7.69369
[85]	validation-rmse:7.68595
[86]	validation-rmse:7.68027
[87]	validation-rmse:7.67732
[88]	validation-rmse:7.67316
[89]	validation-rmse:7.66875
[90]	validation-rmse:7.66453
[91]	validation-rmse:7.65899
[92]	validation-rmse:7.65440
[93]	validation-rmse:7.64805
[94]	validation-rmse:7.64514
[95]	validation-rmse:7.64140
[96]	validation-rmse:7.63793
[97]	validation-rmse:7.63508
[98]	validation-rmse:7.63150
[99]	validation-rmse:7.62849
[100]	validation-rmse:7.62395
[101]	validation-rmse:7.62201
[102]	validation-rmse:7.61426
[103]	validation-rmse:7.60665
[104]	validation-rmse:7.60506
[105]	validation-rmse:7.60190
[106]	validation-rmse:7.59798
[107]	validation-rmse:7.59476
[108]	validation-rmse:7.59386
[109]	validation-rmse:7.59171
[110]	validation-rmse:7.58391
[111]	validation-rmse:7.58050
[112]	validation-rmse:7.58045
[113]	validation-rmse:7.57789
[114]	validation-rmse:7.57579
[115]	validation-rmse:7.57237
[116]	validation-rmse:7.56932
[117]	validation-rmse:7.56769
[118]	validation-rmse:7.56485
[119]	validation-rmse:7.55988
[120]	validation-rmse:7.55818
[121]	validation-rmse:7.55591
[122]	validation-rmse:7.55312
[123]	validation-rmse:7.55008
[124]	validation-rmse:7.54092
[125]	validation-rmse:7.53806
[126]	validation-rmse:7.53301
[127]	validation-rmse:7.53077
[128]	validation-rmse:7.52846
[129]	validation-rmse:7.52367
[130]	validation-rmse:7.52126
[131]	validation-rmse:7.51843
[132]	validation-rmse:7.51293
[133]	validation-rmse:7.50907
[134]	validation-rmse:7.50308
[135]	validation-rmse:7.49941
[136]	validation-rmse:7.49456
[137]	validation-rmse:7.48751
[138]	validation-rmse:7.47843
[139]	validation-rmse:7.47191
[140]	validation-rmse:7.46707
[141]	validation-rmse:7.46458
[142]	validation-rmse:7.45860
[143]	validation-rmse:7.45295
[144]	validation-rmse:7.45003
[145]	validation-rmse:7.44747
[146]	validation-rmse:7.44230
[147]	validation-rmse:7.43754
[148]	validation-rmse:7.43212
[149]	validation-rmse:7.42709
[150]	validation-rmse:7.42487
[151]	validation-rmse:7.42220
[152]	validation-rmse:7.42044
[153]	validation-rmse:7.41885
[154]	validation-rmse:7.41191
[155]	validation-rmse:7.40358
[156]	validation-rmse:7.40401
[157]	validation-rmse:7.40406
[158]	validation-rmse:7.40247
[159]	validation-rmse:7.39991
[160]	validation-rmse:7.39833
[161]	validation-rmse:7.39654
[162]	validation-rmse:7.39542
[163]	validation-rmse:7.39331
[164]	validation-rmse:7.39232
[165]	validation-rmse:7.39016
[166]	validation-rmse:7.38882
[167]	validation-rmse:7.38642
[168]	validation-rmse:7.38427
[169]	validation-rmse:7.38305
[170]	validation-rmse:7.38010
[171]	validation-rmse:7.37837
[172]	validation-rmse:7.37738
[173]	validation-rmse:7.37645
[174]	validation-rmse:7.36693
[175]	validation-rmse:7.36795
[176]	validation-rmse:7.36743
[177]	validation-rmse:7.36598
[178]	validation-rmse:7.36347
[179]	validation-rmse:7.36177
[180]	validation-rmse:7.35846
[181]	validation-rmse:7.35776
[182]	validation-rmse:7.35433
[183]	validation-rmse:7.35394
[184]	validation-rmse:7.35117
[185]	validation-rmse:7.34965
[186]	validation-rmse:7.34780
[187]	validation-rmse:7.34359
[188]	validation-rmse:7.34341
[189]	validation-rmse:7.34225
[190]	validation-rmse:7.34097
[191]	validation-rmse:7.33914
[192]	validation-rmse:7.33764
[193]	validation-rmse:7.33549
[194]	validation-rmse:7.33307
[195]	validation-rmse:7.33349
[196]	validation-rmse:7.33245
[197]	validation-rmse:7.33058
[198]	validation-rmse:7.32995
[199]	validation-rmse:7.32803
[200]	validation-rmse:7.32671
[201]	validation-rmse:7.32539
[202]	validation-rmse:7.32481
[203]	validation-rmse:7.32394
[204]	validation-rmse:7.32348
[205]	validation-rmse:7.32206
[206]	validation-rmse:7.31977
[207]	validation-rmse:7.31913
[208]	validation-rmse:7.31619
[209]	validation-rmse:7.31352
[210]	validation-rmse:7.31371
[211]	validation-rmse:7.31263
[212]	validation-rmse:7.31078
[213]	validation-rmse:7.31034
[214]	validation-rmse:7.30913
[215]	validation-rmse:7.30412
[216]	validation-rmse:7.30240
[217]	validation-rmse:7.30146
[218]	validation-rmse:7.30126
[219]	validation-rmse:7.29915
[220]	validation-rmse:7.29973
[221]	validation-rmse:7.29749
[222]	validation-rmse:7.29753
[223]	validation-rmse:7.29638
[224]	validation-rmse:7.29537
[225]	validation-rmse:7.29482
[226]	validation-rmse:7.29449
[227]	validation-rmse:7.29343
[228]	validation-rmse:7.28951
[229]	validation-rmse:7.28867
[230]	validation-rmse:7.28685
[231]	validation-rmse:7.28645
[232]	validation-rmse:7.28605
[233]	validation-rmse:7.28536
[234]	validation-rmse:7.28394
[235]	validation-rmse:7.28269
[236]	validation-rmse:7.28146
[237]	validation-rmse:7.28042
[238]	validation-rmse:7.27898
[239]	validation-rmse:7.27833
[240]	validation-rmse:7.27659
[241]	validation-rmse:7.27519
[242]	validation-rmse:7.27551
[243]	validation-rmse:7.27486
[244]	validation-rmse:7.27397
[245]	validation-rmse:7.27363
[246]	validation-rmse:7.27107
[247]	validation-rmse:7.27027
[248]	validation-rmse:7.26941
[249]	validation-rmse:7.26573
[250]	validation-rmse:7.26525
[251]	validation-rmse:7.26345
[252]	validation-rmse:7.26326
[253]	validation-rmse:7.25884
[254]	validation-rmse:7.25644
[255]	validation-rmse:7.25489
[256]	validation-rmse:7.25537
[257]	validation-rmse:7.25452
[258]	validation-rmse:7.25261
[259]	validation-rmse:7.25237
[260]	validation-rmse:7.25106
[261]	validation-rmse:7.24916
[262]	validation-rmse:7.24851
[263]	validation-rmse:7.24757
[264]	validation-rmse:7.24570
[265]	validation-rmse:7.24339
[266]	validation-rmse:7.24398
[267]	validation-rmse:7.24408
[268]	validation-rmse:7.24378
[269]	validation-rmse:7.24317
[270]	validation-rmse:7.24113
[271]	validation-rmse:7.24121
[272]	validation-rmse:7.24035
[273]	validation-rmse:7.23898
[274]	validation-rmse:7.23803
[275]	validation-rmse:7.23814
[276]	validation-rmse:7.23742
[277]	validation-rmse:7.23658
[278]	validation-rmse:7.23565
[279]	validation-rmse:7.23385
[280]	validation-rmse:7.23428
[281]	validation-rmse:7.23372
[282]	validation-rmse:7.23238
[283]	validation-rmse:7.23170
[284]	validation-rmse:7.22968
[285]	validation-rmse:7.22894
[286]	validation-rmse:7.22942
[287]	validation-rmse:7.22842
[288]	validation-rmse:7.22741
[289]	validation-rmse:7.22579
[290]	validation-rmse:7.22375
[291]	validation-rmse:7.22349
[292]	validation-rmse:7.22204
[293]	validation-rmse:7.22174
[294]	validation-rmse:7.22194
[295]	validation-rmse:7.22105
[296]	validation-rmse:7.22037
[297]	validation-rmse:7.21956
[298]	validation-rmse:7.22035
[299]	validation-rmse:7.21970
[300]	validation-rmse:7.21770
[301]	validation-rmse:7.21611
[302]	validation-rmse:7.21600
[303]	validation-rmse:7.21529
[304]	validation-rmse:7.21499
[305]	validation-rmse:7.21423
[306]	validation-rmse:7.21396
[307]	validation-rmse:7.21326
[308]	validation-rmse:7.21277
[309]	validation-rmse:7.21169
[310]	validation-rmse:7.21174
[311]	validation-rmse:7.21117
[312]	validation-rmse:7.21010
[313]	validation-rmse:7.20999
[314]	validation-rmse:7.20950
[315]	validation-rmse:7.20810
[316]	validation-rmse:7.20745
[317]	validation-rmse:7.20608
[318]	validation-rmse:7.20446
[319]	validation-rmse:7.20301
[320]	validation-rmse:7.20220
[321]	validation-rmse:7.20132
[322]	validation-rmse:7.20126
[323]	validation-rmse:7.19972
[324]	validation-rmse:7.19866
[325]	validation-rmse:7.19855
[326]	validation-rmse:7.19841
[327]	validation-rmse:7.19652
[328]	validation-rmse:7.19554
[329]	validation-rmse:7.19432
[330]	validation-rmse:7.19318
[331]	validation-rmse:7.19254
[332]	validation-rmse:7.19130
[333]	validation-rmse:7.19128
[334]	validation-rmse:7.19107
[335]	validation-rmse:7.19016
[336]	validation-rmse:7.18880
[337]	validation-rmse:7.18825
[338]	validation-rmse:7.18804
[339]	validation-rmse:7.18723
[340]	validation-rmse:7.18676
[341]	validation-rmse:7.18579
[342]	validation-rmse:7.18430
[343]	validation-rmse:7.18324
[344]	validation-rmse:7.18290
[345]	validation-rmse:7.18267
[346]	validation-rmse:7.18197
[347]	validation-rmse:7.18212
[348]	validation-rmse:7.18175
[349]	validation-rmse:7.18115
[350]	validation-rmse:7.17945
[351]	validation-rmse:7.17976
[352]	validation-rmse:7.17981
[353]	validation-rmse:7.17855
[354]	validation-rmse:7.17734
[355]	validation-rmse:7.17585
[356]	validation-rmse:7.17456
[357]	validation-rmse:7.17394
[358]	validation-rmse:7.17283
[359]	validation-rmse:7.17227
[360]	validation-rmse:7.16948
[361]	validation-rmse:7.16896
[362]	validation-rmse:7.16778
[363]	validation-rmse:7.16710
[364]	validation-rmse:7.16767
[365]	validation-rmse:7.16765
[366]	validation-rmse:7.16711
[367]	validation-rmse:7.16693
[368]	validation-rmse:7.16667
[369]	validation-rmse:7.16543
[370]	validation-rmse:7.16457
[371]	validation-rmse:7.16440
[372]	validation-rmse:7.16350
[373]	validation-rmse:7.16129
[374]	validation-rmse:7.16061
[375]	validation-rmse:7.16073
[376]	validation-rmse:7.16047
[377]	validation-rmse:7.16062
[378]	validation-rmse:7.16036
[379]	validation-rmse:7.15781
[380]	validation-rmse:7.15801
[381]	validation-rmse:7.15770
[382]	validation-rmse:7.15688
[383]	validation-rmse:7.15666
[384]	validation-rmse:7.15675
[385]	validation-rmse:7.15610
[386]	validation-rmse:7.15605
[387]	validation-rmse:7.15446
[388]	validation-rmse:7.15133
[389]	validation-rmse:7.15133
[390]	validation-rmse:7.15201
[391]	validation-rmse:7.15161
[392]	validation-rmse:7.15163
[393]	validation-rmse:7.15130
[394]	validation-rmse:7.15190
[395]	validation-rmse:7.15180
[396]	validation-rmse:7.15215
[397]	validation-rmse:7.15035
[398]	validation-rmse:7.14919
[399]	validation-rmse:7.14781
[400]	validation-rmse:7.14768
[401]	validation-rmse:7.14616
[402]	validation-rmse:7.14526
[403]	validation-rmse:7.14490
[404]	validation-rmse:7.14461
[405]	validation-rmse:7.14408
[406]	validation-rmse:7.14468
[407]	validation-rmse:7.14443
[408]	validation-rmse:7.14283
[409]	validation-rmse:7.14274
[410]	validation-rmse:7.14192
[411]	validation-rmse:7.14154
[412]	validation-rmse:7.14133
[413]	validation-rmse:7.14172
[414]	validation-rmse:7.14058
[415]	validation-rmse:7.14028
[416]	validation-rmse:7.13947
[417]	validation-rmse:7.13912
[418]	validation-rmse:7.13842
[419]	validation-rmse:7.13882
[420]	validation-rmse:7.13788
[421]	validation-rmse:7.13744
[422]	validation-rmse:7.13723
[423]	validation-rmse:7.13637
[424]	validation-rmse:7.13576
[425]	validation-rmse:7.13519
[426]	validation-rmse:7.13462
[427]	validation-rmse:7.13377
[428]	validation-rmse:7.13287
[429]	validation-rmse:7.13197
[430]	validation-rmse:7.13154
[431]	validation-rmse:7.13096
[432]	validation-rmse:7.13112
[433]	validation-rmse:7.13084
[434]	validation-rmse:7.13117
[435]	validation-rmse:7.13081
[436]	validation-rmse:7.13078
[437]	validation-rmse:7.13041
[438]	validation-rmse:7.13081
[439]	validation-rmse:7.12982
[440]	validation-rmse:7.12953
[441]	validation-rmse:7.12956
[442]	validation-rmse:7.12937
[443]	validation-rmse:7.12905
[444]	validation-rmse:7.12898
[445]	validation-rmse:7.12883
[446]	validation-rmse:7.12810
[447]	validation-rmse:7.12834
[448]	validation-rmse:7.12785
[449]	validation-rmse:7.12780
[450]	validation-rmse:7.12743
[451]	validation-rmse:7.12720
[452]	validation-rmse:7.12733
[453]	validation-rmse:7.12723
[454]	validation-rmse:7.12622
[455]	validation-rmse:7.12466
[456]	validation-rmse:7.12441
[457]	validation-rmse:7.12412
[458]	validation-rmse:7.12398
[459]	validation-rmse:7.12354
[460]	validation-rmse:7.12267
[461]	validation-rmse:7.12316
[462]	validation-rmse:7.12244
[463]	validation-rmse:7.12280
[464]	validation-rmse:7.12214
[465]	validation-rmse:7.12165
[466]	validation-rmse:7.12189
[467]	validation-rmse:7.12132
[468]	validation-rmse:7.12086
[469]	validation-rmse:7.12064
[470]	validation-rmse:7.12015
[471]	validation-rmse:7.11991
[472]	validation-rmse:7.12009
[473]	validation-rmse:7.11842
[474]	validation-rmse:7.11876
[475]	validation-rmse:7.11803
[476]	validation-rmse:7.11812
[477]	validation-rmse:7.11781
[478]	validation-rmse:7.11475
[479]	validation-rmse:7.11457
[480]	validation-rmse:7.11409
[481]	validation-rmse:7.11361
[482]	validation-rmse:7.11287
[483]	validation-rmse:7.11206
[484]	validation-rmse:7.11201
[485]	validation-rmse:7.11256
[486]	validation-rmse:7.11204
[487]	validation-rmse:7.11187
[488]	validation-rmse:7.11112
[489]	validation-rmse:7.11120
[490]	validation-rmse:7.11050
[491]	validation-rmse:7.11012
[492]	validation-rmse:7.10947
[493]	validation-rmse:7.10890
[494]	validation-rmse:7.10886
[495]	validation-rmse:7.10511
[496]	validation-rmse:7.10513
[497]	validation-rmse:7.10517
[498]	validation-rmse:7.10460
[499]	validation-rmse:7.10416
[500]	validation-rmse:7.10378
[501]	validation-rmse:7.10345
[502]	validation-rmse:7.10339
[503]	validation-rmse:7.10425
[504]	validation-rmse:7.10354
[505]	validation-rmse:7.10293
[506]	validation-rmse:7.10249
[507]	validation-rmse:7.10250
[508]	validation-rmse:7.10132
[509]	validation-rmse:7.10048
[510]	validation-rmse:7.10056
[511]	validation-rmse:7.09973
[512]	validation-rmse:7.09966
[513]	validation-rmse:7.09912
[514]	validation-rmse:7.09921
[515]	validation-rmse:7.09988
[516]	validation-rmse:7.09958
[517]	validation-rmse:7.09985
[518]	validation-rmse:7.09967
[519]	validation-rmse:7.09665
[520]	validation-rmse:7.09600
[521]	validation-rmse:7.09527
[522]	validation-rmse:7.09555
[523]	validation-rmse:7.09605
[524]	validation-rmse:7.09485
[525]	validation-rmse:7.09435
[526]	validation-rmse:7.09384
[527]	validation-rmse:7.09446
[528]	validation-rmse:7.09416
[529]	validation-rmse:7.09396
[530]	validation-rmse:7.09344
[531]	validation-rmse:7.09324
[532]	validation-rmse:7.09312
[533]	validation-rmse:7.09280
[534]	validation-rmse:7.09220
[535]	validation-rmse:7.09265
[536]	validation-rmse:7.09308
[537]	validation-rmse:7.09307
[538]	validation-rmse:7.09297
[539]	validation-rmse:7.09281
[540]	validation-rmse:7.09169
[541]	validation-rmse:7.09169
[542]	validation-rmse:7.09176
[543]	validation-rmse:7.09144
[544]	validation-rmse:7.09083
[545]	validation-rmse:7.09095
[546]	validation-rmse:7.09100
[547]	validation-rmse:7.09016
[548]	validation-rmse:7.08941
[549]	validation-rmse:7.08906
[550]	validation-rmse:7.08861
[551]	validation-rmse:7.08864
[552]	validation-rmse:7.08895
[553]	validation-rmse:7.08865
[554]	validation-rmse:7.08841
[555]	validation-rmse:7.08850
[556]	validation-rmse:7.08818
[557]	validation-rmse:7.08763
[558]	validation-rmse:7.08796
[559]	validation-rmse:7.08779
[560]	validation-rmse:7.08726
[561]	validation-rmse:7.08698
[562]	validation-rmse:7.08698
[563]	validation-rmse:7.08722
[564]	validation-rmse:7.08666
[565]	validation-rmse:7.08661
[566]	validation-rmse:7.08563
[567]	validation-rmse:7.08575
[568]	validation-rmse:7.08614
[569]	validation-rmse:7.08597
[570]	validation-rmse:7.08522
[571]	validation-rmse:7.08479
[572]	validation-rmse:7.08554
[573]	validation-rmse:7.08511
[574]	validation-rmse:7.08504
[575]	validation-rmse:7.08508
[576]	validation-rmse:7.08576
[577]	validation-rmse:7.08482
[578]	validation-rmse:7.08416
[579]	validation-rmse:7.08390
[580]	validation-rmse:7.08381
[581]	validation-rmse:7.08386
[582]	validation-rmse:7.08376
[583]	validation-rmse:7.08341
[584]	validation-rmse:7.08330
[585]	validation-rmse:7.08345
[586]	validation-rmse:7.08207
[587]	validation-rmse:7.08270
[588]	validation-rmse:7.08302
[589]	validation-rmse:7.08304
[590]	validation-rmse:7.08288
[591]	validation-rmse:7.08233
[592]	validation-rmse:7.08251
[593]	validation-rmse:7.08195
[594]	validation-rmse:7.08143
[595]	validation-rmse:7.08103
[596]	validation-rmse:7.08068
[597]	validation-rmse:7.08084
[598]	validation-rmse:7.08067
[599]	validation-rmse:7.08095
[600]	validation-rmse:7.08096
[601]	validation-rmse:7.08030
[602]	validation-rmse:7.08033
[603]	validation-rmse:7.07963
[604]	validation-rmse:7.07821
[605]	validation-rmse:7.07818
[606]	validation-rmse:7.07833
[607]	validation-rmse:7.07823
[608]	validation-rmse:7.07844
[609]	validation-rmse:7.07825
[610]	validation-rmse:7.07818
[611]	validation-rmse:7.07770
[612]	validation-rmse:7.07742
[613]	validation-rmse:7.07707
[614]	validation-rmse:7.07692
[615]	validation-rmse:7.07676
[616]	validation-rmse:7.07683
[617]	validation-rmse:7.07676
[618]	validation-rmse:7.07623
[619]	validation-rmse:7.07674
[620]	validation-rmse:7.07685
[621]	validation-rmse:7.07656
[622]	validation-rmse:7.07639
[623]	validation-rmse:7.07633
[624]	validation-rmse:7.07638
[625]	validation-rmse:7.07562
[626]	validation-rmse:7.07447
[627]	validation-rmse:7.07435
[628]	validation-rmse:7.07483
[629]	validation-rmse:7.07562
[630]	validation-rmse:7.07543
[631]	validation-rmse:7.07533
[632]	validation-rmse:7.07522
[633]	validation-rmse:7.07446
[634]	validation-rmse:7.07416
[635]	validation-rmse:7.07344
[636]	validation-rmse:7.07333
[637]	validation-rmse:7.07301
[638]	validation-rmse:7.07228
[639]	validation-rmse:7.07178
[640]	validation-rmse:7.07184
[641]	validation-rmse:7.07264
[642]	validation-rmse:7.07242
[643]	validation-rmse:7.07200
[644]	validation-rmse:7.07217
[645]	validation-rmse:7.07203
[646]	validation-rmse:7.07183
[647]	validation-rmse:7.07121
[648]	validation-rmse:7.07112
[649]	validation-rmse:7.07086
[650]	validation-rmse:7.07103
[651]	validation-rmse:7.07087
[652]	validation-rmse:7.07052
[653]	validation-rmse:7.07085
[654]	validation-rmse:7.07072
[655]	validation-rmse:7.07061
[656]	validation-rmse:7.07071
[657]	validation-rmse:7.06972
[658]	validation-rmse:7.06951
[659]	validation-rmse:7.06934
[660]	validation-rmse:7.06875
[661]	validation-rmse:7.06871
[662]	validation-rmse:7.06818
[663]	validation-rmse:7.06818
[664]	validation-rmse:7.06793
[665]	validation-rmse:7.06797
[666]	validation-rmse:7.06833
[667]	validation-rmse:7.06853
[668]	validation-rmse:7.06835
[669]	validation-rmse:7.06843
[670]	validation-rmse:7.06783

[13:00:21] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:12.27452
[2]	validation-rmse:10.57238
[3]	validation-rmse:9.79831
[4]	validation-rmse:9.38903
[5]	validation-rmse:9.16663
[6]	validation-rmse:8.96869
[7]	validation-rmse:8.87565
[8]	validation-rmse:8.80233
[9]	validation-rmse:8.72455
[10]	validation-rmse:8.68875
[11]	validation-rmse:8.66202
[12]	validation-rmse:8.63235
[13]	validation-rmse:8.61342
[14]	validation-rmse:8.58767
[15]	validation-rmse:8.56398
[16]	validation-rmse:8.54387
[17]	validation-rmse:8.52240
[18]	validation-rmse:8.49651
[19]	validation-rmse:8.47055
[20]	validation-rmse:8.45264
[21]	validation-rmse:8.43036
[22]	validation-rmse:8.40533
[23]	validation-rmse:8.38562
[24]	validation-rmse:8.36674
[25]	validation-rmse:8.34980
[26]	validation-rmse:8.33085
[27]	validation-rmse:8.31443
[28]	validation-rmse:8.29151
[29]	validation-rmse:8.27718
[30]	validation-rmse:8.26493
[31]	validation-rmse:8.24891
[32]	validation-rmse:8.23375
[33]	validation-rmse:8.22102
[34]	validation-rmse:8.20663
[35]	validation-rmse:8.19582
[36]	validation-rmse:8.18155
[37]	validation-rmse:8.17219
[38]	validation-rmse:8.16242
[39]	validation-rmse:8.14993
[40]	validation-rmse:8.14088
[41]	validation-rmse:8.12649
[42]	validation-rmse:8.11567
[43]	validation-rmse:8.10279
[44]	validation-rmse:8.08932
[45]	validation-rmse:8.07677
[46]	validation-rmse:8.06767
[47]	validation-rmse:8.05714
[48]	validation-rmse:8.04749
[49]	validation-rmse:8.04000
[50]	validation-rmse:8.02979
[51]	validation-rmse:8.02157
[52]	validation-rmse:8.01362
[53]	validation-rmse:8.00875
[54]	validation-rmse:8.00011
[55]	validation-rmse:7.99401
[56]	validation-rmse:7.98679
[57]	validation-rmse:7.97532
[58]	validation-rmse:7.96956
[59]	validation-rmse:7.96110
[60]	validation-rmse:7.95666
[61]	validation-rmse:7.94982
[62]	validation-rmse:7.94112
[63]	validation-rmse:7.92344
[64]	validation-rmse:7.91557
[65]	validation-rmse:7.90710
[66]	validation-rmse:7.89877
[67]	validation-rmse:7.89153
[68]	validation-rmse:7.87944
[69]	validation-rmse:7.86843
[70]	validation-rmse:7.86049
[71]	validation-rmse:7.85422
[72]	validation-rmse:7.84696
[73]	validation-rmse:7.84269
[74]	validation-rmse:7.83526
[75]	validation-rmse:7.82995
[76]	validation-rmse:7.82426
[77]	validation-rmse:7.81511
[78]	validation-rmse:7.81063
[79]	validation-rmse:7.80101
[80]	validation-rmse:7.79608
[81]	validation-rmse:7.79043
[82]	validation-rmse:7.78558
[83]	validation-rmse:7.77922
[84]	validation-rmse:7.77446
[85]	validation-rmse:7.76706
[86]	validation-rmse:7.76286
[87]	validation-rmse:7.75207
[88]	validation-rmse:7.74588
[89]	validation-rmse:7.73388
[90]	validation-rmse:7.73170
[91]	validation-rmse:7.72690
[92]	validation-rmse:7.72215
[93]	validation-rmse:7.71966
[94]	validation-rmse:7.71231
[95]	validation-rmse:7.70728
[96]	validation-rmse:7.70324
[97]	validation-rmse:7.69562
[98]	validation-rmse:7.68953
[99]	validation-rmse:7.68402
[100]	validation-rmse:7.67562
[101]	validation-rmse:7.67175
[102]	validation-rmse:7.66511
[103]	validation-rmse:7.65471
[104]	validation-rmse:7.64474
[105]	validation-rmse:7.64011
[106]	validation-rmse:7.63342
[107]	validation-rmse:7.62743
[108]	validation-rmse:7.62330
[109]	validation-rmse:7.61448
[110]	validation-rmse:7.60894
[111]	validation-rmse:7.60314
[112]	validation-rmse:7.59588
[113]	validation-rmse:7.59066
[114]	validation-rmse:7.58495
[115]	validation-rmse:7.58022
[116]	validation-rmse:7.57339
[117]	validation-rmse:7.56637
[118]	validation-rmse:7.56285
[119]	validation-rmse:7.55724
[120]	validation-rmse:7.55456
[121]	validation-rmse:7.54752
[122]	validation-rmse:7.54568
[123]	validation-rmse:7.54198
[124]	validation-rmse:7.53979
[125]	validation-rmse:7.53663
[126]	validation-rmse:7.52108
[127]	validation-rmse:7.51751
[128]	validation-rmse:7.51596
[129]	validation-rmse:7.51525
[130]	validation-rmse:7.51122
[131]	validation-rmse:7.50820
[132]	validation-rmse:7.50625
[133]	validation-rmse:7.50353
[134]	validation-rmse:7.49900
[135]	validation-rmse:7.49701
[136]	validation-rmse:7.49336
[137]	validation-rmse:7.49184
[138]	validation-rmse:7.48953
[139]	validation-rmse:7.48643
[140]	validation-rmse:7.48457
[141]	validation-rmse:7.48049
[142]	validation-rmse:7.47790
[143]	validation-rmse:7.47711
[144]	validation-rmse:7.47461
[145]	validation-rmse:7.47105
[146]	validation-rmse:7.46657
[147]	validation-rmse:7.46458
[148]	validation-rmse:7.46117
[149]	validation-rmse:7.45659
[150]	validation-rmse:7.45498
[151]	validation-rmse:7.45239
[152]	validation-rmse:7.45135
[153]	validation-rmse:7.44663
[154]	validation-rmse:7.44471
[155]	validation-rmse:7.44221
[156]	validation-rmse:7.43910
[157]	validation-rmse:7.43654
[158]	validation-rmse:7.43475
[159]	validation-rmse:7.43431
[160]	validation-rmse:7.43225
[161]	validation-rmse:7.42914
[162]	validation-rmse:7.42807
[163]	validation-rmse:7.42569
[164]	validation-rmse:7.42355
[165]	validation-rmse:7.42378
[166]	validation-rmse:7.42253
[167]	validation-rmse:7.41617
[168]	validation-rmse:7.41385
[169]	validation-rmse:7.41217
[170]	validation-rmse:7.41062
[171]	validation-rmse:7.40532
[172]	validation-rmse:7.40359
[173]	validation-rmse:7.40178
[174]	validation-rmse:7.39949
[175]	validation-rmse:7.39651
[176]	validation-rmse:7.39571
[177]	validation-rmse:7.39405
[178]	validation-rmse:7.39294
[179]	validation-rmse:7.39108
[180]	validation-rmse:7.38792
[181]	validation-rmse:7.38594
[182]	validation-rmse:7.38488
[183]	validation-rmse:7.38314
[184]	validation-rmse:7.38106
[185]	validation-rmse:7.37918
[186]	validation-rmse:7.37976
[187]	validation-rmse:7.37717
[188]	validation-rmse:7.37569
[189]	validation-rmse:7.37414
[190]	validation-rmse:7.37270
[191]	validation-rmse:7.36996
[192]	validation-rmse:7.36856
[193]	validation-rmse:7.36741
[194]	validation-rmse:7.36499
[195]	validation-rmse:7.36342
[196]	validation-rmse:7.36198
[197]	validation-rmse:7.36123
[198]	validation-rmse:7.36099
[199]	validation-rmse:7.35874
[200]	validation-rmse:7.35651
[201]	validation-rmse:7.35514
[202]	validation-rmse:7.35382
[203]	validation-rmse:7.34700
[204]	validation-rmse:7.34573
[205]	validation-rmse:7.34385
[206]	validation-rmse:7.34071
[207]	validation-rmse:7.34059
[208]	validation-rmse:7.34108
[209]	validation-rmse:7.33981
[210]	validation-rmse:7.33530
[211]	validation-rmse:7.33395
[212]	validation-rmse:7.33034
[213]	validation-rmse:7.32854
[214]	validation-rmse:7.32674
[215]	validation-rmse:7.32553
[216]	validation-rmse:7.32375
[217]	validation-rmse:7.32262
[218]	validation-rmse:7.32083
[219]	validation-rmse:7.31749
[220]	validation-rmse:7.31416
[221]	validation-rmse:7.30911
[222]	validation-rmse:7.30591
[223]	validation-rmse:7.30427
[224]	validation-rmse:7.30121
[225]	validation-rmse:7.29920
[226]	validation-rmse:7.29408
[227]	validation-rmse:7.29332
[228]	validation-rmse:7.29000
[229]	validation-rmse:7.28900
[230]	validation-rmse:7.28734
[231]	validation-rmse:7.28521
[232]	validation-rmse:7.28243
[233]	validation-rmse:7.28242
[234]	validation-rmse:7.28102
[235]	validation-rmse:7.27999
[236]	validation-rmse:7.27826
[237]	validation-rmse:7.27730
[238]	validation-rmse:7.27607
[239]	validation-rmse:7.27555
[240]	validation-rmse:7.27536
[241]	validation-rmse:7.27262
[242]	validation-rmse:7.27213
[243]	validation-rmse:7.27097
[244]	validation-rmse:7.27103
[245]	validation-rmse:7.26859
[246]	validation-rmse:7.26867
[247]	validation-rmse:7.26688
[248]	validation-rmse:7.26559
[249]	validation-rmse:7.26348
[250]	validation-rmse:7.26333
[251]	validation-rmse:7.26310
[252]	validation-rmse:7.26230
[253]	validation-rmse:7.26110
[254]	validation-rmse:7.26084
[255]	validation-rmse:7.25947
[256]	validation-rmse:7.25884
[257]	validation-rmse:7.25804
[258]	validation-rmse:7.25760
[259]	validation-rmse:7.25700
[260]	validation-rmse:7.25683
[261]	validation-rmse:7.25557
[262]	validation-rmse:7.25422
[263]	validation-rmse:7.25349
[264]	validation-rmse:7.25358
[265]	validation-rmse:7.25257
[266]	validation-rmse:7.25287
[267]	validation-rmse:7.25269
[268]	validation-rmse:7.25185
[269]	validation-rmse:7.25091
[270]	validation-rmse:7.24923
[271]	validation-rmse:7.24840
[272]	validation-rmse:7.24845
[273]	validation-rmse:7.24624
[274]	validation-rmse:7.24265
[275]	validation-rmse:7.23986
[276]	validation-rmse:7.23961
[277]	validation-rmse:7.23658
[278]	validation-rmse:7.23553
[279]	validation-rmse:7.23440
[280]	validation-rmse:7.22927
[281]	validation-rmse:7.22790
[282]	validation-rmse:7.22624
[283]	validation-rmse:7.22410
[284]	validation-rmse:7.22322
[285]	validation-rmse:7.22037
[286]	validation-rmse:7.21917
[287]	validation-rmse:7.21904
[288]	validation-rmse:7.21763
[289]	validation-rmse:7.21653
[290]	validation-rmse:7.21391
[291]	validation-rmse:7.21343
[292]	validation-rmse:7.21209
[293]	validation-rmse:7.21061
[294]	validation-rmse:7.21044
[295]	validation-rmse:7.20940
[296]	validation-rmse:7.20894
[297]	validation-rmse:7.20782
[298]	validation-rmse:7.20747
[299]	validation-rmse:7.20625
[300]	validation-rmse:7.20582
[301]	validation-rmse:7.20535
[302]	validation-rmse:7.20419
[303]	validation-rmse:7.20370
[304]	validation-rmse:7.20258
[305]	validation-rmse:7.20048
[306]	validation-rmse:7.19830
[307]	validation-rmse:7.19791
[308]	validation-rmse:7.19717
[309]	validation-rmse:7.19580
[310]	validation-rmse:7.19458
[311]	validation-rmse:7.19454
[312]	validation-rmse:7.18945
[313]	validation-rmse:7.18985
[314]	validation-rmse:7.18836
[315]	validation-rmse:7.18814
[316]	validation-rmse:7.18472
[317]	validation-rmse:7.18409
[318]	validation-rmse:7.18251
[319]	validation-rmse:7.18107
[320]	validation-rmse:7.17975
[321]	validation-rmse:7.17930
[322]	validation-rmse:7.17907
[323]	validation-rmse:7.17969
[324]	validation-rmse:7.17728
[325]	validation-rmse:7.17574
[326]	validation-rmse:7.17532
[327]	validation-rmse:7.17497
[328]	validation-rmse:7.17237
[329]	validation-rmse:7.17187
[330]	validation-rmse:7.17139
[331]	validation-rmse:7.17096
[332]	validation-rmse:7.17002
[333]	validation-rmse:7.16870
[334]	validation-rmse:7.16829
[335]	validation-rmse:7.16730
[336]	validation-rmse:7.16678
[337]	validation-rmse:7.16696
[338]	validation-rmse:7.16640
[339]	validation-rmse:7.16558
[340]	validation-rmse:7.16494
[341]	validation-rmse:7.16520
[342]	validation-rmse:7.16407
[343]	validation-rmse:7.16338
[344]	validation-rmse:7.16321
[345]	validation-rmse:7.16195
[346]	validation-rmse:7.16168
[347]	validation-rmse:7.16158
[348]	validation-rmse:7.16031
[349]	validation-rmse:7.15964
[350]	validation-rmse:7.15885
[351]	validation-rmse:7.15705
[352]	validation-rmse:7.15693
[353]	validation-rmse:7.15504
[354]	validation-rmse:7.15477
[355]	validation-rmse:7.15486
[356]	validation-rmse:7.15414
[357]	validation-rmse:7.15406
[358]	validation-rmse:7.15422
[359]	validation-rmse:7.15437
[360]	validation-rmse:7.15395
[361]	validation-rmse:7.15394
[362]	validation-rmse:7.15340
[363]	validation-rmse:7.15358
[364]	validation-rmse:7.15232
[365]	validation-rmse:7.15195
[366]	validation-rmse:7.15194
[367]	validation-rmse:7.15100
[368]	validation-rmse:7.14959
[369]	validation-rmse:7.14895
[370]	validation-rmse:7.14815
[371]	validation-rmse:7.14775
[372]	validation-rmse:7.14713
[373]	validation-rmse:7.14702
[374]	validation-rmse:7.14616
[375]	validation-rmse:7.14591
[376]	validation-rmse:7.14492
[377]	validation-rmse:7.14414
[378]	validation-rmse:7.14337
[379]	validation-rmse:7.14335
[380]	validation-rmse:7.14321
[381]	validation-rmse:7.14267
[382]	validation-rmse:7.14312
[383]	validation-rmse:7.14334
[384]	validation-rmse:7.13868
[385]	validation-rmse:7.13775
[386]	validation-rmse:7.13734
[387]	validation-rmse:7.13710
[388]	validation-rmse:7.13705
[389]	validation-rmse:7.13679
[390]	validation-rmse:7.13578
[391]	validation-rmse:7.13612
[392]	validation-rmse:7.13532
[393]	validation-rmse:7.13630
[394]	validation-rmse:7.13495
[395]	validation-rmse:7.13504
[396]	validation-rmse:7.13396
[397]	validation-rmse:7.13341
[398]	validation-rmse:7.13359
[399]	validation-rmse:7.13288
[400]	validation-rmse:7.13305
[401]	validation-rmse:7.13267
[402]	validation-rmse:7.13172
[403]	validation-rmse:7.13123
[404]	validation-rmse:7.13022
[405]	validation-rmse:7.13028
[406]	validation-rmse:7.12916
[407]	validation-rmse:7.12886
[408]	validation-rmse:7.12907
[409]	validation-rmse:7.12923
[410]	validation-rmse:7.12855
[411]	validation-rmse:7.12685
[412]	validation-rmse:7.12683
[413]	validation-rmse:7.12306
[414]	validation-rmse:7.12264
[415]	validation-rmse:7.12269
[416]	validation-rmse:7.12269
[417]	validation-rmse:7.12169
[418]	validation-rmse:7.12152
[419]	validation-rmse:7.12190
[420]	validation-rmse:7.12086
[421]	validation-rmse:7.12000
[422]	validation-rmse:7.12030
[423]	validation-rmse:7.12043
[424]	validation-rmse:7.11977
[425]	validation-rmse:7.11950
[426]	validation-rmse:7.11927
[427]	validation-rmse:7.11875
[428]	validation-rmse:7.11887
[429]	validation-rmse:7.11782
[430]	validation-rmse:7.11652
[431]	validation-rmse:7.11696
[432]	validation-rmse:7.11697
[433]	validation-rmse:7.11608
[434]	validation-rmse:7.11524
[435]	validation-rmse:7.11588
[436]	validation-rmse:7.11515
[437]	validation-rmse:7.11530
[438]	validation-rmse:7.11488
[439]	validation-rmse:7.11596
[440]	validation-rmse:7.11518
[441]	validation-rmse:7.11113
[442]	validation-rmse:7.11024
[443]	validation-rmse:7.11019
[444]	validation-rmse:7.10913
[445]	validation-rmse:7.10912
[446]	validation-rmse:7.10919
[447]	validation-rmse:7.10875
[448]	validation-rmse:7.10829
[449]	validation-rmse:7.10893
[450]	validation-rmse:7.10885
[451]	validation-rmse:7.10814
[452]	validation-rmse:7.10801
[453]	validation-rmse:7.10788
[454]	validation-rmse:7.10760
[455]	validation-rmse:7.10689
[456]	validation-rmse:7.10646
[457]	validation-rmse:7.10541
[458]	validation-rmse:7.10286
[459]	validation-rmse:7.10124
[460]	validation-rmse:7.10051
[461]	validation-rmse:7.10019
[462]	validation-rmse:7.09989
[463]	validation-rmse:7.10020
[464]	validation-rmse:7.10039
[465]	validation-rmse:7.10028
[466]	validation-rmse:7.09958
[467]	validation-rmse:7.09854
[468]	validation-rmse:7.09868
[469]	validation-rmse:7.09810
[470]	validation-rmse:7.09741
[471]	validation-rmse:7.09726
[472]	validation-rmse:7.09684
[473]	validation-rmse:7.09639
[474]	validation-rmse:7.09626
[475]	validation-rmse:7.09633
[476]	validation-rmse:7.09546
[477]	validation-rmse:7.09557
[478]	validation-rmse:7.09580
[479]	validation-rmse:7.09523
[480]	validation-rmse:7.09466
[481]	validation-rmse:7.09488
[482]	validation-rmse:7.09436
[483]	validation-rmse:7.09475
[484]	validation-rmse:7.09508
[485]	validation-rmse:7.09397
[486]	validation-rmse:7.09412
[487]	validation-rmse:7.09370
[488]	validation-rmse:7.09311
[489]	validation-rmse:7.09262
[490]	validation-rmse:7.09211
[491]	validation-rmse:7.09228
[492]	validation-rmse:7.09255
[493]	validation-rmse:7.09165
[494]	validation-rmse:7.09176
[495]	validation-rmse:7.09137
[496]	validation-rmse:7.09011
[497]	validation-rmse:7.09013
[498]	validation-rmse:7.09005
[499]	validation-rmse:7.08951
[500]	validation-rmse:7.08994
[501]	validation-rmse:7.08971
[502]	validation-rmse:7.08969
[503]	validation-rmse:7.08930
[504]	validation-rmse:7.08964
[505]	validation-rmse:7.08966
[506]	validation-rmse:7.08766
[507]	validation-rmse:7.08731
[508]	validation-rmse:7.08646
[509]	validation-rmse:7.08561
[510]	validation-rmse:7.08579
[511]	validation-rmse:7.08539
[512]	validation-rmse:7.08505
[513]	validation-rmse:7.08524
[514]	validation-rmse:7.08425
[515]	validation-rmse:7.08218
[516]	validation-rmse:7.08294
[517]	validation-rmse:7.08326
[518]	validation-rmse:7.08261
[519]	validation-rmse:7.08233
[520]	validation-rmse:7.08237
[521]	validation-rmse:7.08182
[522]	validation-rmse:7.08180
[523]	validation-rmse:7.08134
[524]	validation-rmse:7.08174
[525]	validation-rmse:7.08211
[526]	validation-rmse:7.08125
[527]	validation-rmse:7.08165
[528]	validation-rmse:7.08063
[529]	validation-rmse:7.07997
[530]	validation-rmse:7.08023
[531]	validation-rmse:7.07945
[532]	validation-rmse:7.07892
[533]	validation-rmse:7.07826
[534]	validation-rmse:7.07760
[535]	validation-rmse:7.07742
[536]	validation-rmse:7.07729
[537]	validation-rmse:7.07744
[538]	validation-rmse:7.07739
[539]	validation-rmse:7.07635
[540]	validation-rmse:7.07677
[541]	validation-rmse:7.07632
[542]	validation-rmse:7.07640
[543]	validation-rmse:7.07641
[544]	validation-rmse:7.07649
[545]	validation-rmse:7.07632
[546]	validation-rmse:7.07657
[547]	validation-rmse:7.07642
[548]	validation-rmse:7.07596
[549]	validation-rmse:7.07518
[550]	validation-rmse:7.07537
[551]	validation-rmse:7.07555
[552]	validation-rmse:7.07484
[553]	validation-rmse:7.07468
[554]	validation-rmse:7.07535
[555]	validation-rmse:7.07476
[556]	validation-rmse:7.07470
[557]	validation-rmse:7.07489
[558]	validation-rmse:7.07428
[559]	validation-rmse:7.07339
[560]	validation-rmse:7.07341
[561]	validation-rmse:7.07307
[562]	validation-rmse:7.07242
[563]	validation-rmse:7.07171
[564]	validation-rmse:7.07156
[565]	validation-rmse:7.07087
[566]	validation-rmse:7.07078
[567]	validation-rmse:7.07107
[568]	validation-rmse:7.07108
[569]	validation-rmse:7.07170
[570]	validation-rmse:7.07068
[571]	validation-rmse:7.07025
[572]	validation-rmse:7.06976
[573]	validation-rmse:7.07032
[574]	validation-rmse:7.07021
[575]	validation-rmse:7.06989
[576]	validation-rmse:7.07034
[577]	validation-rmse:7.06998
[578]	validation-rmse:7.06922
[579]	validation-rmse:7.06886
[580]	validation-rmse:7.06953
[581]	validation-rmse:7.06897
[582]	validation-rmse:7.06753
[583]	validation-rmse:7.06694
[584]	validation-rmse:7.06535
[585]	validation-rmse:7.06562
[586]	validation-rmse:7.06546
[587]	validation-rmse:7.06494
[588]	validation-rmse:7.06484
[589]	validation-rmse:7.06491
[590]	validation-rmse:7.06507
[591]	validation-rmse:7.06491
[592]	validation-rmse:7.06391
[593]	validation-rmse:7.06421
[594]	validation-rmse:7.06453
[595]	validation-rmse:7.06387
[596]	validation-rmse:7.06346
[597]	validation-rmse:7.06370
[598]	validation-rmse:7.06353
[599]	validation-rmse:7.06269
[600]	validation-rmse:7.06309
[601]	validation-rmse:7.06359
[602]	validation-rmse:7.06300
[603]	validation-rmse:7.06267
[604]	validation-rmse:7.06245
[605]	validation-rmse:7.06157
[606]	validation-rmse:7.06240
[607]	validation-rmse:7.06220
[608]	validation-rmse:7.06207
[609]	validation-rmse:7.06223
[610]	validation-rmse:7.06154
[611]	validation-rmse:7.06157
[612]	validation-rmse:7.06190
[613]	validation-rmse:7.06180
[614]	validation-rmse:7.06185
[615]	validation-rmse:7.06151
[616]	validation-rmse:7.06087
[617]	validation-rmse:7.06064
[618]	validation-rmse:7.05959
[619]	validation-rmse:7.05877
[620]	validation-rmse:7.05873
[621]	validation-rmse:7.05811
[622]	validation-rmse:7.05836
[623]	validation-rmse:7.05815
[624]	validation-rmse:7.05797
[625]	validation-rmse:7.05827
[626]	validation-rmse:7.05850
[627]	validation-rmse:7.05890
[628]	validation-rmse:7.05817
[629]	validation-rmse:7.05745
[630]	validation-rmse:7.05676
[631]	validation-rmse:7.05690
[632]	validation-rmse:7.05556
[633]	validation-rmse:7.05444
[634]	validation-rmse:7.05495
[635]	validation-rmse:7.05470
[636]	validation-rmse:7.05516
[637]	validation-rmse:7.05512
[638]	validation-rmse:7.05383
[639]	validation-rmse:7.05435
[640]	validation-rmse:7.05418
[641]	validation-rmse:7.05388
[642]	validation-rmse:7.05372
[643]	validation-rmse:7.05369
[644]	validation-rmse:7.05382
[645]	validation-rmse:7.05387
[646]	validation-rmse:7.05374
[647]	validation-rmse:7.05354
[648]	validation-rmse:7.05338
[649]	validation-rmse:7.05342
[650]	validation-rmse:7.05367
[651]	validation-rmse:7.05361
[652]	validation-rmse:7.05352
[653]	validation-rmse:7.05347
[654]	validation-rmse:7.05329
[655]	validation-rmse:7.05300
[656]	validation-rmse:7.05307
[657]	validation-rmse:7.05287
[658]	validation-rmse:7.05103
[659]	validation-rmse:7.05032
[660]	validation-rmse:7.05089
[661]	validation-rmse:7.05116
[662]	validation-rmse:7.05082
[663]	validation-rmse:7.05100
[664]	validation-rmse:7.05085
[665]	validation-rmse:7.05080
[666]	validation-rmse:7.05015
[667]	validation-rmse:7.04998
[668]	validation-rmse:7.05009
[669]	validation-rmse:7.04981
[670]	validation-rmse:7.04939

[13:05:49] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:12.28684
[2]	validation-rmse:10.58320
[3]	validation-rmse:9.82832
[4]	validation-rmse:9.42097
[5]	validation-rmse:9.20981
[6]	validation-rmse:9.06428
[7]	validation-rmse:8.90733
[8]	validation-rmse:8.82301
[9]	validation-rmse:8.74844
[10]	validation-rmse:8.70008
[11]	validation-rmse:8.66355
[12]	validation-rmse:8.62836
[13]	validation-rmse:8.59906
[14]	validation-rmse:8.57839
[15]	validation-rmse:8.55356
[16]	validation-rmse:8.53620
[17]	validation-rmse:8.51653
[18]	validation-rmse:8.48915
[19]	validation-rmse:8.47438
[20]	validation-rmse:8.44939
[21]	validation-rmse:8.42727
[22]	validation-rmse:8.41028
[23]	validation-rmse:8.39154
[24]	validation-rmse:8.37232
[25]	validation-rmse:8.35111
[26]	validation-rmse:8.33623
[27]	validation-rmse:8.31784
[28]	validation-rmse:8.29838
[29]	validation-rmse:8.28163
[30]	validation-rmse:8.27097
[31]	validation-rmse:8.25115
[32]	validation-rmse:8.24241
[33]	validation-rmse:8.23286
[34]	validation-rmse:8.21842
[35]	validation-rmse:8.20699
[36]	validation-rmse:8.19655
[37]	validation-rmse:8.18600
[38]	validation-rmse:8.17438
[39]	validation-rmse:8.16011
[40]	validation-rmse:8.14988
[41]	validation-rmse:8.14173
[42]	validation-rmse:8.13299
[43]	validation-rmse:8.12529
[44]	validation-rmse:8.11895
[45]	validation-rmse:8.11217
[46]	validation-rmse:8.10500
[47]	validation-rmse:8.09403
[48]	validation-rmse:8.08799
[49]	validation-rmse:8.07559
[50]	validation-rmse:8.06687
[51]	validation-rmse:8.06016
[52]	validation-rmse:8.05093
[53]	validation-rmse:8.04447
[54]	validation-rmse:8.03584
[55]	validation-rmse:8.02978
[56]	validation-rmse:8.02232
[57]	validation-rmse:8.01554
[58]	validation-rmse:8.01010
[59]	validation-rmse:8.00326
[60]	validation-rmse:7.99629
[61]	validation-rmse:7.99106
[62]	validation-rmse:7.98465
[63]	validation-rmse:7.98162
[64]	validation-rmse:7.97665
[65]	validation-rmse:7.97052
[66]	validation-rmse:7.96630
[67]	validation-rmse:7.95495
[68]	validation-rmse:7.94845
[69]	validation-rmse:7.94420
[70]	validation-rmse:7.93441
[71]	validation-rmse:7.92905
[72]	validation-rmse:7.92497
[73]	validation-rmse:7.91977
[74]	validation-rmse:7.90916
[75]	validation-rmse:7.90146
[76]	validation-rmse:7.88970
[77]	validation-rmse:7.88049
[78]	validation-rmse:7.87316
[79]	validation-rmse:7.86577
[80]	validation-rmse:7.86371
[81]	validation-rmse:7.85443
[82]	validation-rmse:7.84559
[83]	validation-rmse:7.84117
[84]	validation-rmse:7.82946
[85]	validation-rmse:7.82527
[86]	validation-rmse:7.82129
[87]	validation-rmse:7.81741
[88]	validation-rmse:7.81234
[89]	validation-rmse:7.80858
[90]	validation-rmse:7.80437
[91]	validation-rmse:7.79859
[92]	validation-rmse:7.79215
[93]	validation-rmse:7.78158
[94]	validation-rmse:7.77751
[95]	validation-rmse:7.77406
[96]	validation-rmse:7.76945
[97]	validation-rmse:7.76123
[98]	validation-rmse:7.75582
[99]	validation-rmse:7.75299
[100]	validation-rmse:7.74068
[101]	validation-rmse:7.72968
[102]	validation-rmse:7.72636
[103]	validation-rmse:7.71374
[104]	validation-rmse:7.70506
[105]	validation-rmse:7.70245
[106]	validation-rmse:7.69643
[107]	validation-rmse:7.68889
[108]	validation-rmse:7.68353
[109]	validation-rmse:7.67506
[110]	validation-rmse:7.66704
[111]	validation-rmse:7.66009
[112]	validation-rmse:7.65206
[113]	validation-rmse:7.64660
[114]	validation-rmse:7.63996
[115]	validation-rmse:7.63539
[116]	validation-rmse:7.63156
[117]	validation-rmse:7.62944
[118]	validation-rmse:7.62734
[119]	validation-rmse:7.62465
[120]	validation-rmse:7.62099
[121]	validation-rmse:7.61900
[122]	validation-rmse:7.61665
[123]	validation-rmse:7.61520
[124]	validation-rmse:7.61314
[125]	validation-rmse:7.61176
[126]	validation-rmse:7.60975
[127]	validation-rmse:7.60450
[128]	validation-rmse:7.59699
[129]	validation-rmse:7.59507
[130]	validation-rmse:7.59450
[131]	validation-rmse:7.59063
[132]	validation-rmse:7.58732
[133]	validation-rmse:7.58708
[134]	validation-rmse:7.58608
[135]	validation-rmse:7.58240
[136]	validation-rmse:7.58041
[137]	validation-rmse:7.57814
[138]	validation-rmse:7.57650
[139]	validation-rmse:7.57502
[140]	validation-rmse:7.57209
[141]	validation-rmse:7.57036
[142]	validation-rmse:7.56940
[143]	validation-rmse:7.56658
[144]	validation-rmse:7.56555
[145]	validation-rmse:7.56468
[146]	validation-rmse:7.56040
[147]	validation-rmse:7.55788
[148]	validation-rmse:7.55682
[149]	validation-rmse:7.55472
[150]	validation-rmse:7.55312
[151]	validation-rmse:7.55056
[152]	validation-rmse:7.54858
[153]	validation-rmse:7.54004
[154]	validation-rmse:7.53418
[155]	validation-rmse:7.53196
[156]	validation-rmse:7.53017
[157]	validation-rmse:7.52912
[158]	validation-rmse:7.52889
[159]	validation-rmse:7.52605
[160]	validation-rmse:7.52515
[161]	validation-rmse:7.51921
[162]	validation-rmse:7.51802
[163]	validation-rmse:7.51298
[164]	validation-rmse:7.51166
[165]	validation-rmse:7.50891
[166]	validation-rmse:7.50624
[167]	validation-rmse:7.50525
[168]	validation-rmse:7.50277
[169]	validation-rmse:7.50225
[170]	validation-rmse:7.50176
[171]	validation-rmse:7.49814
[172]	validation-rmse:7.49750
[173]	validation-rmse:7.49485
[174]	validation-rmse:7.49268
[175]	validation-rmse:7.49211
[176]	validation-rmse:7.48937
[177]	validation-rmse:7.48661
[178]	validation-rmse:7.48557
[179]	validation-rmse:7.48399
[180]	validation-rmse:7.47812
[181]	validation-rmse:7.47681
[182]	validation-rmse:7.47509
[183]	validation-rmse:7.47309
[184]	validation-rmse:7.47218
[185]	validation-rmse:7.47046
[186]	validation-rmse:7.46831
[187]	validation-rmse:7.46518
[188]	validation-rmse:7.45889
[189]	validation-rmse:7.45604
[190]	validation-rmse:7.45392
[191]	validation-rmse:7.45202
[192]	validation-rmse:7.45153
[193]	validation-rmse:7.45045
[194]	validation-rmse:7.44881
[195]	validation-rmse:7.44852
[196]	validation-rmse:7.44425
[197]	validation-rmse:7.44346
[198]	validation-rmse:7.43992
[199]	validation-rmse:7.43865
[200]	validation-rmse:7.43729
[201]	validation-rmse:7.43490
[202]	validation-rmse:7.42932
[203]	validation-rmse:7.42741
[204]	validation-rmse:7.42521
[205]	validation-rmse:7.42370
[206]	validation-rmse:7.42289
[207]	validation-rmse:7.42186
[208]	validation-rmse:7.41904
[209]	validation-rmse:7.41928
[210]	validation-rmse:7.42013
[211]	validation-rmse:7.41864
[212]	validation-rmse:7.41646
[213]	validation-rmse:7.41516
[214]	validation-rmse:7.41277
[215]	validation-rmse:7.41104
[216]	validation-rmse:7.40906
[217]	validation-rmse:7.40690
[218]	validation-rmse:7.40571
[219]	validation-rmse:7.40298
[220]	validation-rmse:7.40134
[221]	validation-rmse:7.39978
[222]	validation-rmse:7.39878
[223]	validation-rmse:7.39842
[224]	validation-rmse:7.39722
[225]	validation-rmse:7.39606
[226]	validation-rmse:7.39343
[227]	validation-rmse:7.39104
[228]	validation-rmse:7.38795
[229]	validation-rmse:7.38745
[230]	validation-rmse:7.38580
[231]	validation-rmse:7.38514
[232]	validation-rmse:7.38321
[233]	validation-rmse:7.38297
[234]	validation-rmse:7.38214
[235]	validation-rmse:7.37999
[236]	validation-rmse:7.37824
[237]	validation-rmse:7.37691
[238]	validation-rmse:7.37646
[239]	validation-rmse:7.37116
[240]	validation-rmse:7.37181
[241]	validation-rmse:7.37148
[242]	validation-rmse:7.37025
[243]	validation-rmse:7.36974
[244]	validation-rmse:7.36938
[245]	validation-rmse:7.36651
[246]	validation-rmse:7.36425
[247]	validation-rmse:7.36285
[248]	validation-rmse:7.36160
[249]	validation-rmse:7.36029
[250]	validation-rmse:7.35936
[251]	validation-rmse:7.35887
[252]	validation-rmse:7.35829
[253]	validation-rmse:7.35875
[254]	validation-rmse:7.35076
[255]	validation-rmse:7.35007
[256]	validation-rmse:7.35009
[257]	validation-rmse:7.34967
[258]	validation-rmse:7.34788
[259]	validation-rmse:7.34847
[260]	validation-rmse:7.34776
[261]	validation-rmse:7.34677
[262]	validation-rmse:7.34594
[263]	validation-rmse:7.34432
[264]	validation-rmse:7.34270
[265]	validation-rmse:7.34242
[266]	validation-rmse:7.34086
[267]	validation-rmse:7.34057
[268]	validation-rmse:7.33880
[269]	validation-rmse:7.33839
[270]	validation-rmse:7.33673
[271]	validation-rmse:7.33615
[272]	validation-rmse:7.33491
[273]	validation-rmse:7.33045
[274]	validation-rmse:7.32938
[275]	validation-rmse:7.32653
[276]	validation-rmse:7.32593
[277]	validation-rmse:7.32457
[278]	validation-rmse:7.32393
[279]	validation-rmse:7.32169
[280]	validation-rmse:7.32110
[281]	validation-rmse:7.32121
[282]	validation-rmse:7.32081
[283]	validation-rmse:7.31976
[284]	validation-rmse:7.31984
[285]	validation-rmse:7.31873
[286]	validation-rmse:7.31810
[287]	validation-rmse:7.31764
[288]	validation-rmse:7.31579
[289]	validation-rmse:7.31437
[290]	validation-rmse:7.31407
[291]	validation-rmse:7.31357
[292]	validation-rmse:7.30554
[293]	validation-rmse:7.30500
[294]	validation-rmse:7.30467
[295]	validation-rmse:7.30428
[296]	validation-rmse:7.30080
[297]	validation-rmse:7.29758
[298]	validation-rmse:7.29472
[299]	validation-rmse:7.29263
[300]	validation-rmse:7.29173
[301]	validation-rmse:7.28648
[302]	validation-rmse:7.28313
[303]	validation-rmse:7.28052
[304]	validation-rmse:7.27946
[305]	validation-rmse:7.27825
[306]	validation-rmse:7.27365
[307]	validation-rmse:7.27130
[308]	validation-rmse:7.26811
[309]	validation-rmse:7.26703
[310]	validation-rmse:7.26302
[311]	validation-rmse:7.25839
[312]	validation-rmse:7.25623
[313]	validation-rmse:7.25390
[314]	validation-rmse:7.25107
[315]	validation-rmse:7.25016
[316]	validation-rmse:7.24635
[317]	validation-rmse:7.24299
[318]	validation-rmse:7.24246
[319]	validation-rmse:7.24226
[320]	validation-rmse:7.24192
[321]	validation-rmse:7.24122
[322]	validation-rmse:7.24001
[323]	validation-rmse:7.23781
[324]	validation-rmse:7.23804
[325]	validation-rmse:7.23716
[326]	validation-rmse:7.23608
[327]	validation-rmse:7.23396
[328]	validation-rmse:7.23513
[329]	validation-rmse:7.23423
[330]	validation-rmse:7.23382
[331]	validation-rmse:7.23257
[332]	validation-rmse:7.22953
[333]	validation-rmse:7.22980
[334]	validation-rmse:7.22577
[335]	validation-rmse:7.22576
[336]	validation-rmse:7.22511
[337]	validation-rmse:7.22356
[338]	validation-rmse:7.22322
[339]	validation-rmse:7.22320
[340]	validation-rmse:7.22044
[341]	validation-rmse:7.22035
[342]	validation-rmse:7.22015
[343]	validation-rmse:7.21946
[344]	validation-rmse:7.21794
[345]	validation-rmse:7.21693
[346]	validation-rmse:7.21770
[347]	validation-rmse:7.21506
[348]	validation-rmse:7.21440
[349]	validation-rmse:7.21237
[350]	validation-rmse:7.21164
[351]	validation-rmse:7.21170
[352]	validation-rmse:7.21097
[353]	validation-rmse:7.21080
[354]	validation-rmse:7.20960
[355]	validation-rmse:7.20880
[356]	validation-rmse:7.20781
[357]	validation-rmse:7.20724
[358]	validation-rmse:7.20680
[359]	validation-rmse:7.20643
[360]	validation-rmse:7.20588
[361]	validation-rmse:7.20441
[362]	validation-rmse:7.20385
[363]	validation-rmse:7.20381
[364]	validation-rmse:7.20207
[365]	validation-rmse:7.20176
[366]	validation-rmse:7.20083
[367]	validation-rmse:7.20081
[368]	validation-rmse:7.20024
[369]	validation-rmse:7.19963
[370]	validation-rmse:7.19898
[371]	validation-rmse:7.19886
[372]	validation-rmse:7.19798
[373]	validation-rmse:7.19823
[374]	validation-rmse:7.19800
[375]	validation-rmse:7.19650
[376]	validation-rmse:7.19631
[377]	validation-rmse:7.19609
[378]	validation-rmse:7.19592
[379]	validation-rmse:7.19532
[380]	validation-rmse:7.19443
[381]	validation-rmse:7.19528
[382]	validation-rmse:7.19363
[383]	validation-rmse:7.19331
[384]	validation-rmse:7.19325
[385]	validation-rmse:7.19359
[386]	validation-rmse:7.19345
[387]	validation-rmse:7.19191
[388]	validation-rmse:7.18666
[389]	validation-rmse:7.18424
[390]	validation-rmse:7.18413
[391]	validation-rmse:7.18372
[392]	validation-rmse:7.18298
[393]	validation-rmse:7.18222
[394]	validation-rmse:7.18195
[395]	validation-rmse:7.18146
[396]	validation-rmse:7.18134
[397]	validation-rmse:7.18101
[398]	validation-rmse:7.18111
[399]	validation-rmse:7.18171
[400]	validation-rmse:7.18169
[401]	validation-rmse:7.18241
[402]	validation-rmse:7.18170
[403]	validation-rmse:7.17999
[404]	validation-rmse:7.17862
[405]	validation-rmse:7.17886
[406]	validation-rmse:7.17858
[407]	validation-rmse:7.17803
[408]	validation-rmse:7.17814
[409]	validation-rmse:7.17697
[410]	validation-rmse:7.17668
[411]	validation-rmse:7.17642
[412]	validation-rmse:7.17622
[413]	validation-rmse:7.17450
[414]	validation-rmse:7.17321
[415]	validation-rmse:7.17233
[416]	validation-rmse:7.17204
[417]	validation-rmse:7.17234
[418]	validation-rmse:7.17272
[419]	validation-rmse:7.17089
[420]	validation-rmse:7.17064
[421]	validation-rmse:7.17001
[422]	validation-rmse:7.17019
[423]	validation-rmse:7.16941
[424]	validation-rmse:7.17008
[425]	validation-rmse:7.17000
[426]	validation-rmse:7.16935
[427]	validation-rmse:7.16935
[428]	validation-rmse:7.16838
[429]	validation-rmse:7.16838
[430]	validation-rmse:7.16782
[431]	validation-rmse:7.16766
[432]	validation-rmse:7.16731
[433]	validation-rmse:7.16703
[434]	validation-rmse:7.16692
[435]	validation-rmse:7.16606
[436]	validation-rmse:7.16599
[437]	validation-rmse:7.16460
[438]	validation-rmse:7.16415
[439]	validation-rmse:7.16472
[440]	validation-rmse:7.16377
[441]	validation-rmse:7.16323
[442]	validation-rmse:7.16218
[443]	validation-rmse:7.16239
[444]	validation-rmse:7.16187
[445]	validation-rmse:7.16095
[446]	validation-rmse:7.16144
[447]	validation-rmse:7.16073
[448]	validation-rmse:7.15942
[449]	validation-rmse:7.15857
[450]	validation-rmse:7.15794
[451]	validation-rmse:7.15735
[452]	validation-rmse:7.15617
[453]	validation-rmse:7.15572
[454]	validation-rmse:7.15458
[455]	validation-rmse:7.15473
[456]	validation-rmse:7.15392
[457]	validation-rmse:7.15231
[458]	validation-rmse:7.15030
[459]	validation-rmse:7.15047
[460]	validation-rmse:7.15053
[461]	validation-rmse:7.15002
[462]	validation-rmse:7.14965
[463]	validation-rmse:7.14983
[464]	validation-rmse:7.14952
[465]	validation-rmse:7.14900
[466]	validation-rmse:7.14857
[467]	validation-rmse:7.14759
[468]	validation-rmse:7.14758
[469]	validation-rmse:7.14725
[470]	validation-rmse:7.14741
[471]	validation-rmse:7.14635
[472]	validation-rmse:7.14697
[473]	validation-rmse:7.14564
[474]	validation-rmse:7.14422
[475]	validation-rmse:7.14470
[476]	validation-rmse:7.14429
[477]	validation-rmse:7.14399
[478]	validation-rmse:7.14398
[479]	validation-rmse:7.14359
[480]	validation-rmse:7.14388
[481]	validation-rmse:7.14314
[482]	validation-rmse:7.14287
[483]	validation-rmse:7.14228
[484]	validation-rmse:7.14201
[485]	validation-rmse:7.14218
[486]	validation-rmse:7.14169
[487]	validation-rmse:7.14051
[488]	validation-rmse:7.14005
[489]	validation-rmse:7.14011
[490]	validation-rmse:7.13960
[491]	validation-rmse:7.13896
[492]	validation-rmse:7.13946
[493]	validation-rmse:7.13978
[494]	validation-rmse:7.13937
[495]	validation-rmse:7.13890
[496]	validation-rmse:7.13903
[497]	validation-rmse:7.13822
[498]	validation-rmse:7.13768
[499]	validation-rmse:7.13665
[500]	validation-rmse:7.13675
[501]	validation-rmse:7.13628
[502]	validation-rmse:7.13601
[503]	validation-rmse:7.13516
[504]	validation-rmse:7.13445
[505]	validation-rmse:7.13211
[506]	validation-rmse:7.13235
[507]	validation-rmse:7.13202
[508]	validation-rmse:7.13075
[509]	validation-rmse:7.13016
[510]	validation-rmse:7.12971
[511]	validation-rmse:7.12921
[512]	validation-rmse:7.12891
[513]	validation-rmse:7.12966
[514]	validation-rmse:7.12939
[515]	validation-rmse:7.12873
[516]	validation-rmse:7.12849
[517]	validation-rmse:7.12829
[518]	validation-rmse:7.12786
[519]	validation-rmse:7.12764
[520]	validation-rmse:7.12756
[521]	validation-rmse:7.12760
[522]	validation-rmse:7.12685
[523]	validation-rmse:7.12672
[524]	validation-rmse:7.12693
[525]	validation-rmse:7.12623
[526]	validation-rmse:7.12639
[527]	validation-rmse:7.12630
[528]	validation-rmse:7.12535
[529]	validation-rmse:7.12498
[530]	validation-rmse:7.12402
[531]	validation-rmse:7.12394
[532]	validation-rmse:7.12365
[533]	validation-rmse:7.12367
[534]	validation-rmse:7.12311
[535]	validation-rmse:7.12317
[536]	validation-rmse:7.12300
[537]	validation-rmse:7.12293
[538]	validation-rmse:7.12192
[539]	validation-rmse:7.12231
[540]	validation-rmse:7.12150
[541]	validation-rmse:7.11978
[542]	validation-rmse:7.11982
[543]	validation-rmse:7.11924
[544]	validation-rmse:7.11683
[545]	validation-rmse:7.11695
[546]	validation-rmse:7.11706
[547]	validation-rmse:7.11277
[548]	validation-rmse:7.11187
[549]	validation-rmse:7.11154
[550]	validation-rmse:7.11175
[551]	validation-rmse:7.11134
[552]	validation-rmse:7.11146
[553]	validation-rmse:7.11162
[554]	validation-rmse:7.11160
[555]	validation-rmse:7.11085
[556]	validation-rmse:7.11042
[557]	validation-rmse:7.11036
[558]	validation-rmse:7.10962
[559]	validation-rmse:7.10881
[560]	validation-rmse:7.10881
[561]	validation-rmse:7.10883
[562]	validation-rmse:7.10784
[563]	validation-rmse:7.10740
[564]	validation-rmse:7.10793
[565]	validation-rmse:7.10820
[566]	validation-rmse:7.10738
[567]	validation-rmse:7.10674
[568]	validation-rmse:7.10720
[569]	validation-rmse:7.10627
[570]	validation-rmse:7.10613
[571]	validation-rmse:7.10594
[572]	validation-rmse:7.10510
[573]	validation-rmse:7.10526
[574]	validation-rmse:7.10432
[575]	validation-rmse:7.10377
[576]	validation-rmse:7.10301
[577]	validation-rmse:7.10325
[578]	validation-rmse:7.10288
[579]	validation-rmse:7.10298
[580]	validation-rmse:7.10233
[581]	validation-rmse:7.10250
[582]	validation-rmse:7.10248
[583]	validation-rmse:7.10276
[584]	validation-rmse:7.10278
[585]	validation-rmse:7.10183
[586]	validation-rmse:7.10231
[587]	validation-rmse:7.10155
[588]	validation-rmse:7.10091
[589]	validation-rmse:7.10040
[590]	validation-rmse:7.09988
[591]	validation-rmse:7.10059
[592]	validation-rmse:7.10060
[593]	validation-rmse:7.10009
[594]	validation-rmse:7.10003
[595]	validation-rmse:7.09984
[596]	validation-rmse:7.09993
[597]	validation-rmse:7.10035
[598]	validation-rmse:7.09955
[599]	validation-rmse:7.09914
[600]	validation-rmse:7.09942
[601]	validation-rmse:7.09898
[602]	validation-rmse:7.09839
[603]	validation-rmse:7.09837
[604]	validation-rmse:7.09781
[605]	validation-rmse:7.09759
[606]	validation-rmse:7.09727
[607]	validation-rmse:7.09760
[608]	validation-rmse:7.09788
[609]	validation-rmse:7.09710
[610]	validation-rmse:7.09545
[611]	validation-rmse:7.09435
[612]	validation-rmse:7.09376
[613]	validation-rmse:7.09376
[614]	validation-rmse:7.09403
[615]	validation-rmse:7.09482
[616]	validation-rmse:7.09440
[617]	validation-rmse:7.09388
[618]	validation-rmse:7.09291
[619]	validation-rmse:7.09304
[620]	validation-rmse:7.09267
[621]	validation-rmse:7.09270
[622]	validation-rmse:7.09301
[623]	validation-rmse:7.09287
[624]	validation-rmse:7.09222
[625]	validation-rmse:7.09129
[626]	validation-rmse:7.09127
[627]	validation-rmse:7.09099
[628]	validation-rmse:7.09058
[629]	validation-rmse:7.09061
[630]	validation-rmse:7.09003
[631]	validation-rmse:7.08933
[632]	validation-rmse:7.08955
[633]	validation-rmse:7.08979
[634]	validation-rmse:7.08981
[635]	validation-rmse:7.08991
[636]	validation-rmse:7.09048
[637]	validation-rmse:7.09033
[638]	validation-rmse:7.09083
[639]	validation-rmse:7.08974
[640]	validation-rmse:7.08981
[641]	validation-rmse:7.08920
[642]	validation-rmse:7.08897
[643]	validation-rmse:7.08845
[644]	validation-rmse:7.08846
[645]	validation-rmse:7.08803
[646]	validation-rmse:7.08805
[647]	validation-rmse:7.08741
[648]	validation-rmse:7.08751
[649]	validation-rmse:7.08766
[650]	validation-rmse:7.08793
[651]	validation-rmse:7.08762
[652]	validation-rmse:7.08771
[653]	validation-rmse:7.08723
[654]	validation-rmse:7.08774
[655]	validation-rmse:7.08776
[656]	validation-rmse:7.08755
[657]	validation-rmse:7.08769
[658]	validation-rmse:7.08666
[659]	validation-rmse:7.08621
[660]	validation-rmse:7.08580
[661]	validation-rmse:7.08544
[662]	validation-rmse:7.08537
[663]	validation-rmse:7.08467
[664]	validation-rmse:7.08446
[665]	validation-rmse:7.08476
[666]	validation-rmse:7.08476
[667]	validation-rmse:7.08427
[668]	validation-rmse:7.08470
[669]	validation-rmse:7.08433
[670]	validation-rmse:7.08478

[13:10:24] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[0]	validation-rmse:15.56412
[1]	validation-rmse:12.35793
[2]	validation-rmse:10.46014
[3]	validation-rmse:9.28149
[4]	validation-rmse:8.76168
[5]	validation-rmse:8.36536
[6]	validation-rmse:8.15429
[7]	validation-rmse:7.81831
[8]	validation-rmse:7.73791
[9]	validation-rmse:7.66115
[10]	validation-rmse:7.57095
[11]	validation-rmse:7.51639
[12]	validation-rmse:7.45603
[13]	validation-rmse:7.41762
[14]	validation-rmse:7.40203
[15]	validation-rmse:7.38568
[16]	validation-rmse:7.37293
[17]	validation-rmse:7.36543
[18]	validation-rmse:7.35739
[19]	validation-rmse:7.33989
[20]	validation-rmse:7.33054
[21]	validation-rmse:7.32542
[22]	validation-rmse:7.32157
[23]	validation-rmse:7.31855
[24]	validation-rmse:7.31897
[25]	validation-rmse:7.31130
[26]	validation-rmse:7.31039
[27]	validation-rmse:7.31012
[28]	validation-rmse:7.30913
[29]	validation-rmse:7.30791
[30]	validation-rmse:7.30584
[31]	validation-rmse:7.30621
[32]	validation-rmse:7.30623
[33]	validation-rmse:7.30592
[34]	validation-rmse:7.30337
[35]	validation-rmse:7.30234
[36]	validation-rmse:7.30438
[37]	validation-rmse:7.30266
[38]	validation-rmse:7.30208
[39]	validation-rmse:7.30131
[40]	validation-rmse:7.30061
[41]	validation-rmse:7.30061
[42]	validation-rmse:7.30061
[43]	validation-rmse:7.29849
[44]	validation-rmse:7.29880
[45]	validation-rmse:7.29856
[46]	validation-rmse:7.29890
[47]	validation-rmse:7.29739
[48]	validation-rmse:7.29730
[49]	validation-rmse:7.29550
[50]	validation-rmse:7.29296
[51]	validation-rmse:7.29192
[52]	validation-rmse:7.29192
[53]	validation-rmse:7.29217
[54]	validation-rmse:7.29035
[55]	validation-rmse:7.29019
[56]	validation-rmse:7.28987
[57]	validation-rmse:7.29011
[58]	validation-rmse:7.29090
[59]	validation-rmse:7.28850
[60]	validation-rmse:7.28759
[61]	validation-rmse:7.28752
[62]	validation-rmse:7.28563
[63]	validation-rmse:7.28684
[64]	validation-rmse:7.28755
[65]	validation-rmse:7.28572
[66]	validation-rmse:7.28342
[67]	validation-rmse:7.28289
[68]	validation-rmse:7.28218
[69]	validation-rmse:7.28215
[70]	validation-rmse:7.28237
[71]	validation-rmse:7.28147
[72]	validation-rmse:7.27967
[73]	validation-rmse:7.28149
[74]	validation-rmse:7.28100
[75]	validation-rmse:7.28027
[76]	validation-rmse:7.27957
[77]	validation-rmse:7.27857
[78]	validation-rmse:7.27840
[79]	validation-rmse:7.27886
[80]	validation-rmse:7.27867
[81]	validation-rmse:7.27798
[82]	validation-rmse:7.27743
[83]	validation-rmse:7.27627
[84]	validation-rmse:7.27673
[85]	validation-rmse:7.27679
[86]	validation-rmse:7.27582
[87]	validation-rmse:7.27633
[88]	validation-rmse:7.27443
[89]	validation-rmse:7.27402
[90]	validation-rmse:7.27448
[91]	validation-rmse:7.27421
[92]	validation-rmse:7.27367
[93]	validation-rmse:7.27341
[94]	validation-rmse:7.27361
[95]	validation-rmse:7.27411
[96]	validation-rmse:7.27351
[97]	validation-rmse:7.27336
[98]	validation-rmse:7.27257
[99]	validation-rmse:7.27153
[100]	validation-rmse:7.27060
[101]	validation-rmse:7.26894
[102]	validation-rmse:7.26805
[103]	validation-rmse:7.26803
[104]	validation-rmse:7.26748
[105]	validation-rmse:7.26731
[106]	validation-rmse:7.26881
[107]	validation-rmse:7.26766
[108]	validation-rmse:7.26595
[109]	validation-rmse:7.26470
[110]	validation-rmse:7.26408
[111]	validation-rmse:7.26289
[112]	validation-rmse:7.26299
[113]	validation-rmse:7.26184
[114]	validation-rmse:7.26104
[115]	validation-rmse:7.25925
[116]	validation-rmse:7.25960
[117]	validation-rmse:7.25877
[118]	validation-rmse:7.25869
[119]	validation-rmse:7.25757
[120]	validation-rmse:7.25619
[121]	validation-rmse:7.25553
[122]	validation-rmse:7.25544
[123]	validation-rmse:7.25453
[124]	validation-rmse:7.25405
[125]	validation-rmse:7.25280
[126]	validation-rmse:7.25200
[127]	validation-rmse:7.25185
[128]	validation-rmse:7.25158
[129]	validation-rmse:7.25103
[130]	validation-rmse:7.24929
[131]	validation-rmse:7.24895
[132]	validation-rmse:7.24975
[133]	validation-rmse:7.24884
[134]	validation-rmse:7.24952
[135]	validation-rmse:7.25008
[136]	validation-rmse:7.24920
[137]	validation-rmse:7.24894
[138]	validation-rmse:7.25017
[139]	validation-rmse:7.24946
[140]	validation-rmse:7.24903
[141]	validation-rmse:7.24776
[142]	validation-rmse:7.24692
[143]	validation-rmse:7.24789
[144]	validation-rmse:7.24868
[145]	validation-rmse:7.24665
[146]	validation-rmse:7.24619
[147]	validation-rmse:7.24608
[148]	validation-rmse:7.24504
[149]	validation-rmse:7.24449
[150]	validation-rmse:7.24445
[151]	validation-rmse:7.24449
[152]	validation-rmse:7.24535
[153]	validation-rmse:7.24415
[154]	validation-rmse:7.24323
[155]	validation-rmse:7.24357
[156]	validation-rmse:7.24430
[157]	validation-rmse:7.24450
[158]	validation-rmse:7.24341
[159]	validation-rmse:7.24194
[160]	validation-rmse:7.24265
[161]	validation-rmse:7.24229
[162]	validation-rmse:7.24264
[163]	validation-rmse:7.24202
[164]	validation-rmse:7.24136
[165]	validation-rmse:7.24041
[166]	validation-rmse:7.23987
[167]	validation-rmse:7.23970
[168]	validation-rmse:7.23916
[169]	validation-rmse:7.23874
[170]	validation-rmse:7.23994
[171]	validation-rmse:7.23981
[172]	validation-rmse:7.23914
[173]	validation-rmse:7.23836
[174]	validation-rmse:7.23807
[175]	validation-rmse:7.23757
[176]	validation-rmse:7.23763
[177]	validation-rmse:7.23788
[178]	validation-rmse:7.23686
[179]	validation-rmse:7.23423
[180]	validation-rmse:7.23417
[181]	validation-rmse:7.23367
[182]	validation-rmse:7.23261
[183]	validation-rmse:7.23223
[184]	validation-rmse:7.23178
[185]	validation-rmse:7.23283
[186]	validation-rmse:7.23281
[187]	validation-rmse:7.23168
[188]	validation-rmse:7.23168
[189]	validation-rmse:7.23171
[190]	validation-rmse:7.23184
[191]	validation-rmse:7.23159
[192]	validation-rmse:7.22986
[193]	validation-rmse:7.22880
[194]	validation-rmse:7.22629
[195]	validation-rmse:7.22539
[196]	validation-rmse:7.22545
[197]	validation-rmse:7.22560
[198]	validation-rmse:7.22601
[199]	validation-rmse:7.22537
[200]	validation-rmse:7.22443
[201]	validation-rmse:7.22340
[202]	validation-rmse:7.22350
[203]	validation-rmse:7.22253
[204]	validation-rmse:7.22150
[205]	validation-rmse:7.22161
[206]	validation-rmse:7.22141
[207]	validation-rmse:7.22168
[208]	validation-rmse:7.22196
[209]	validation-rmse:7.22150
[210]	validation-rmse:7.22023
[211]	validation-rmse:7.21951
[212]	validation-rmse:7.21954
[213]	validation-rmse:7.21948
[214]	validation-rmse:7.22009
[215]	validation-rmse:7.22109
[216]	validation-rmse:7.22081
[217]	validation-rmse:7.21972
[218]	validation-rmse:7.21849
[219]	validation-rmse:7.21867
[220]	validation-rmse:7.21775
[221]	validation-rmse:7.21647
[222]	validation-rmse:7.21724
[223]	validation-rmse:7.21629
[224]	validation-rmse:7.21608
[225]	validation-rmse:7.21546
[226]	validation-rmse:7.21475
[227]	validation-rmse:7.21443
[228]	validation-rmse:7.21435
[229]	validation-rmse:7.21445
[230]	validation-rmse:7.21471
[231]	validation-rmse:7.21479
[232]	validation-rmse:7.21487
[233]	validation-rmse:7.21442
[234]	validation-rmse:7.21337
[235]	validation-rmse:7.21299
[236]	validation-rmse:7.21348
[237]	validation-rmse:7.21381
[238]	validation-rmse:7.21375
[239]	validation-rmse:7.21443
[240]	validation-rmse:7.21333
[241]	validation-rmse:7.21186
[242]	validation-rmse:7.21226
[243]	validation-rmse:7.21264
[244]	validation-rmse:7.21296
[245]	validation-rmse:7.21166
[246]	validation-rmse:7.21256
[247]	validation-rmse:7.21136
[248]	validation-rmse:7.21069
[249]	validation-rmse:7.21100
[250]	validation-rmse:7.21104
[251]	validation-rmse:7.20987
[252]	validation-rmse:7.21025
[253]	validation-rmse:7.20918
[254]	validation-rmse:7.20866
[255]	validation-rmse:7.20880
[256]	validation-rmse:7.20868
[257]	validation-rmse:7.20845
[258]	validation-rmse:7.20875
[259]	validation-rmse:7.20821
[260]	validation-rmse:7.20840
[261]	validation-rmse:7.20834
[262]	validation-rmse:7.20629
[263]	validation-rmse:7.20680
[264]	validation-rmse:7.20696
[265]	validation-rmse:7.20600
[266]	validation-rmse:7.20547
[267]	validation-rmse:7.20584
[268]	validation-rmse:7.20481
[269]	validation-rmse:7.20452
[270]	validation-rmse:7.20369
[271]	validation-rmse:7.20360
[272]	validation-rmse:7.20325
[273]	validation-rmse:7.20229
[274]	validation-rmse:7.20192
[275]	validation-rmse:7.20167
[276]	validation-rmse:7.20041
[277]	validation-rmse:7.19965
[278]	validation-rmse:7.20111
[279]	validation-rmse:7.20093
[280]	validation-rmse:7.20024
[281]	validation-rmse:7.19981
[282]	validation-rmse:7.19965
[283]	validation-rmse:7.19950
[284]	validation-rmse:7.20032
[285]	validation-rmse:7.20013
[286]	validation-rmse:7.20032
[287]	validation-rmse:7.19998
[288]	validation-rmse:7.19963
[289]	validation-rmse:7.19913
[290]	validation-rmse:7.19875
[291]	validation-rmse:7.19957
[292]	validation-rmse:7.19923
[293]	validation-rmse:7.19882
[294]	validation-rmse:7.20024
[295]	validation-rmse:7.19905
[296]	validation-rmse:7.19921
[297]	validation-rmse:7.19826
[298]	validation-rmse:7.19812
[299]	validation-rmse:7.19844
[300]	validation-rmse:7.19899
[301]	validation-rmse:7.19843
[302]	validation-rmse:7.19830
[303]	validation-rmse:7.19901
[304]	validation-rmse:7.19840
[305]	validation-rmse:7.19775
[306]	validation-rmse:7.19651
[307]	validation-rmse:7.19684
[308]	validation-rmse:7.19669
[309]	validation-rmse:7.19674
[310]	validation-rmse:7.19649
[311]	validation-rmse:7.19507
[312]	validation-rmse:7.19578
[313]	validation-rmse:7.19616
[314]	validation-rmse:7.19563
[315]	validation-rmse:7.19452
[316]	validation-rmse:7.19459
[317]	validation-rmse:7.19441
[318]	validation-rmse:7.19448
[319]	validation-rmse:7.19435
[320]	validation-rmse:7.19401
[321]	validation-rmse:7.19430
[322]	validation-rmse:7.19421
[323]	validation-rmse:7.19412
[324]	validation-rmse:7.19301
[325]	validation-rmse:7.19257
[326]	validation-rmse:7.19301
[327]	validation-rmse:7.19261
[328]	validation-rmse:7.19197
[329]	validation-rmse:7.19308
[330]	validation-rmse:7.19327
[331]	validation-rmse:7.19272
[332]	validation-rmse:7.19219
[333]	validation-rmse:7.19262
[334]	validation-rmse:7.19113
[335]	validation-rmse:7.19138
[336]	validation-rmse:7.19165
[337]	validation-rmse:7.19114
[338]	validation-rmse:7.19140
[339]	validation-rmse:7.19004
[340]	validation-rmse:7.18974
[341]	validation-rmse:7.19031
[342]	validation-rmse:7.19005
[343]	validation-rmse:7.18913
[344]	validation-rmse:7.18907
[345]	validation-rmse:7.18968
[346]	validation-rmse:7.18992
[347]	validation-rmse:7.19081
[348]	validation-rmse:7.19049
[349]	validation-rmse:7.18954
[350]	validation-rmse:7.18937
[351]	validation-rmse:7.18933
[352]	validation-rmse:7.18938
[353]	validation-rmse:7.18963
[354]	validation-rmse:7.18958
[355]	validation-rmse:7.18888
[356]	validation-rmse:7.18870
[357]	validation-rmse:7.18891
[358]	validation-rmse:7.18787
[359]	validation-rmse:7.18750
[360]	validation-rmse:7.18681
[361]	validation-rmse:7.18800
[362]	validation-rmse:7.18730
[363]	validation-rmse:7.18709
[364]	validation-rmse:7.18752
[365]	validation-rmse:7.18669
[366]	validation-rmse:7.18705
[367]	validation-rmse:7.18744
[368]	validation-rmse:7.18749
[369]	validation-rmse:7.18722
[370]	validation-rmse:7.18637
[371]	validation-rmse:7.18631
[372]	validation-rmse:7.18701
[373]	validation-rmse:7.18672
[374]	validation-rmse:7.18538
[375]	validation-rmse:7.18558
[376]	validation-rmse:7.18597
[377]	validation-rmse:7.18574
[378]	validation-rmse:7.18507
[379]	validation-rmse:7.18559
[380]	validation-rmse:7.18625
[381]	validation-rmse:7.18490
[382]	validation-rmse:7.18555
[383]	validation-rmse:7.18503
[384]	validation-rmse:7.18461
[385]	validation-rmse:7.18448
[386]	validation-rmse:7.18507
[387]	validation-rmse:7.18406
[388]	validation-rmse:7.18296
[389]	validation-rmse:7.18381
[390]	validation-rmse:7.18262
[391]	validation-rmse:7.18248
[392]	validation-rmse:7.18264
[393]	validation-rmse:7.18266
[394]	validation-rmse:7.18288
[395]	validation-rmse:7.18340
[396]	validation-rmse:7.18300
[397]	validation-rmse:7.18346
[398]	validation-rmse:7.18468
[399]	validation-rmse:7.18348
[400]	validation-rmse:7.18318
[401]	validation-rmse:7.18275
[402]	validation-rmse:7.18224
[403]	validation-rmse:7.18251
[404]	validation-rmse:7.18220
[405]	validation-rmse:7.18209
[406]	validation-rmse:7.18226
[407]	validation-rmse:7.18167
[408]	validation-rmse:7.18152
[409]	validation-rmse:7.18206
[410]	validation-rmse:7.18092
[411]	validation-rmse:7.18057
[412]	validation-rmse:7.18062
[413]	validation-rmse:7.18048
[414]	validation-rmse:7.17990
[415]	validation-rmse:7.17887
[416]	validation-rmse:7.17805
[417]	validation-rmse:7.17875
[418]	validation-rmse:7.17920
[419]	validation-rmse:7.17869
[420]	validation-rmse:7.17742
[421]	validation-rmse:7.17842
[422]	validation-rmse:7.17829
[423]	validation-rmse:7.17818
[424]	validation-rmse:7.17752
[425]	validation-rmse:7.17772
[426]	validation-rmse:7.17763
[427]	validation-rmse:7.17747
[428]	validation-rmse:7.17757
[429]	validation-rmse:7.17741
[430]	validation-rmse:7.17739
[431]	validation-rmse:7.17755
[432]	validation-rmse:7.17777
[433]	validation-rmse:7.17717
[434]	validation-rmse:7.17623
[435]	validation-rmse:7.17651
[436]	validation-rmse:7.17601
[437]	validation-rmse:7.17650
[438]	validation-rmse:7.17687
[439]	validation-rmse:7.17647
[440]	validation-rmse:7.17686
[441]	validation-rmse:7.17720
[442]	validation-rmse:7.17665
[443]	validation-rmse:7.17645
[444]	validation-rmse:7.17571
[445]	validation-rmse:7.17591
[446]	validation-rmse:7.17633
[447]	validation-rmse:7.17584
[448]	validation-rmse:7.17626
[449]	validation-rmse:7.17652
[450]	validation-rmse:7.17636
[451]	validation-rmse:7.17644
[452]	validation-rmse:7.17654
[453]	validation-rmse:7.17654
[454]	validation-rmse:7.17625
[455]	validation-rmse:7.17686
[456]	validation-rmse:7.17642
[457]	validation-rmse:7.17655
[458]	validation-rmse:7.17529
[459]	validation-rmse:7.17553
[460]	validation-rmse:7.17557
[461]	validation-rmse:7.17522
[462]	validation-rmse:7.17547
[463]	validation-rmse:7.17518
[464]	validation-rmse:7.17483
[465]	validation-rmse:7.17494
[466]	validation-rmse:7.17450
[467]	validation-rmse:7.17457
[468]	validation-rmse:7.17459
[469]	validation-rmse:7.17355
[470]	validation-rmse:7.17326
[471]	validation-rmse:7.17355
[472]	validation-rmse:7.17254
[473]	validation-rmse:7.17257
[474]	validation-rmse:7.17211
[475]	validation-rmse:7.17240
[476]	validation-rmse:7.17248
[477]	validation-rmse:7.17331
[478]	validation-rmse:7.17358
[479]	validation-rmse:7.17321
[480]	validation-rmse:7.17360
[481]	validation-rmse:7.17350
[482]	validation-rmse:7.17364
[483]	validation-rmse:7.17382
[484]	validation-rmse:7.17401
[485]	validation-rmse:7.17448
[486]	validation-rmse:7.17345
[487]	validation-rmse:7.17426
[488]	validation-rmse:7.17462
[489]	validation-rmse:7.17371
[490]	validation-rmse:7.17364
[491]	validation-rmse:7.17365
[492]	validation-rmse:7.17414
[493]	validation-rmse:7.17406
[494]	validation-rmse:7.17402
[495]	validation-rmse:7.17455
[496]	validation-rmse:7.17472
[497]	validation-rmse:7.17391
[498]	validation-rmse:7.17333
[499]	validation-rmse:7.17351
[500]	validation-rmse:7.17361
[501]	validation-rmse:7.17350
[502]	validation-rmse:7.17323
[503]	validation-rmse:7.17334
[504]	validation-rmse:7.17358
[505]	validation-rmse:7.17304
[506]	validation-rmse:7.17349
[507]	validation-rmse:7.17271
[508]	validation-rmse:7.17303
[509]	validation-rmse:7.17304
[510]	validation-rmse:7.17329
[511]	validation-rmse:7.17258
[512]	validation-rmse:7.17281
[513]	validation-rmse:7.17287
[514]	validation-rmse:7.17249
[515]	validation-rmse:7.17204
[516]	validation-rmse:7.17137
[517]	validation-rmse:7.17117
[518]	validation-rmse:7.17195
[519]	validation-rmse:7.17245
[520]	validation-rmse:7.17250
[521]	validation-rmse:7.17135
[522]	validation-rmse:7.17148
[523]	validation-rmse:7.17149
[524]	validation-rmse:7.17140
[525]	validation-rmse:7.17139
[526]	validation-rmse:7.17079
[527]	validation-rmse:7.17093
[528]	validation-rmse:7.17140
[529]	validation-rmse:7.17144
[530]	validation-rmse:7.17181
[531]	validation-rmse:7.17123
[532]	validation-rmse:7.17113
[533]	validation-rmse:7.17083
[534]	validation-rmse:7.17059
[535]	validation-rmse:7.17093
[536]	validation-rmse:7.17067
[537]	validation-rmse:7.17090
[538]	validation-rmse:7.17150
[539]	validation-rmse:7.17186
[540]	validation-rmse:7.17240
[541]	validation-rmse:7.17156
[542]	validation-rmse:7.17164
[543]	validation-rmse:7.17170
[544]	validation-rmse:7.17192
[545]	validation-rmse:7.17142
[546]	validation-rmse:7.17141
[547]	validation-rmse:7.17066
[548]	validation-rmse:7.16982
[549]	validation-rmse:7.16968
[550]	validation-rmse:7.16954
[551]	validation-rmse:7.16916
[552]	validation-rmse:7.16970
[553]	validation-rmse:7.16988
[554]	validation-rmse:7.17013
[555]	validation-rmse:7.17045
[556]	validation-rmse:7.16956
[557]	validation-rmse:7.16952
[558]	validation-rmse:7.16903
[559]	validation-rmse:7.16864
[560]	validation-rmse:7.16902
[561]	validation-rmse:7.16997
[562]	validation-rmse:7.17039
[563]	validation-rmse:7.16959
[564]	validation-rmse:7.16968
[565]	validation-rmse:7.16975
[566]	validation-rmse:7.16976
[567]	validation-rmse:7.16930
[568]	validation-rmse:7.16909
[569]	validation-rmse:7.16981
[570]	validation-rmse:7.16976
[571]	validation-rmse:7.17003
[572]	validation-rmse:7.17017
[573]	validation-rmse:7.16938
[574]	validation-rmse:7.16923
[575]	validation-rmse:7.16945
[576]	validation-rmse:7.16846
[577]	validation-rmse:7.16940
[578]	validation-rmse:7.16976
[579]	validation-rmse:7.17050
[580]	validation-rmse:7.16964
[581]	validation-rmse:7.16978
[582]	validation-rmse:7.16935
[583]	validation-rmse:7.16948
[584]	validation-rmse:7.16966
[585]	validation-rmse:7.17022
[586]	validation-rmse:7.16987
[587]	validation-rmse:7.17009
[588]	validation-rmse:7.17013
[589]	validation-rmse:7.16947
[590]	validation-rmse:7.16940
[591]	validation-rmse:7.16913
[592]	validation-rmse:7.16822
[593]	validation-rmse:7.16801
[594]	validation-rmse:7.16707
[595]	validation-rmse:7.16741
[596]	validation-rmse:7.16778
[597]	validation-rmse:7.16692
[598]	validation-rmse:7.16728
[599]	validation-rmse:7.16736
[600]	validation-rmse:7.16781
[601]	validation-rmse:7.16792
[602]	validation-rmse:7.16833
[603]	validation-rmse:7.16759
[604]	validation-rmse:7.16750
[605]	validation-rmse:7.16778
[606]	validation-rmse:7.16737
[607]	validation-rmse:7.16702
[608]	validation-rmse:7.16731
[609]	validation-rmse:7.16700
[610]	validation-rmse:7.16744
[611]	validation-rmse:7.16708
[612]	validation-rmse:7.16616
[613]	validation-rmse:7.16618
[614]	validation-rmse:7.16617
[615]	validation-rmse:7.16688
[616]	validation-rmse:7.16688
[617]	validation-rmse:7.16693
[618]	validation-rmse:7.16664
[619]	validation-rmse:7.16670
[620]	validation-rmse:7.16660
[621]	validation-rmse:7.16675
[622]	validation-rmse:7.16653
[623]	validation-rmse:7.16728
[624]	validation-rmse:7.16737
[625]	validation-rmse:7.16753
[626]	validation-rmse:7.16760
[627]	validation-rmse:7.16775
[628]	validation-rmse:7.16747
[629]	validation-rmse:7.16733
[630]	validation-rmse:7.16685
[631]	validation-rmse:7.16661
[632]	validation-rmse:7.16648
[633]	validation-rmse:7.16682
[634]	validation-rmse:7.16635
[635]	validation-rmse:7.16559
[636]	validation-rmse:7.16494
[637]	validation-rmse:7.16536
[638]	validation-rmse:7.16460
[639]	validation-rmse:7.16477
[640]	validation-rmse:7.16464
[641]	validation-rmse:7.16458
[642]	validation-rmse:7.16548
[643]	validation-rmse:7.16513
[644]	validation-rmse:7.16568
[645]	validation-rmse:7.16564
[646]	validation-rmse:7.16578
[647]	validation-rmse:7.16621
[648]	validation-rmse:7.16616
[649]	validation-rmse:7.16677
[650]	validation-rmse:7.16644
[651]	validation-rmse:7.16645
[652]	validation-rmse:7.16626
[653]	validation-rmse:7.16638
[654]	validation-rmse:7.16601
[655]	validation-rmse:7.16653
[656]	validation-rmse:7.16647
[657]	validation-rmse:7.16592
[658]	validation-rmse:7.16640
[659]	validation-rmse:7.16684
[660]	validation-rmse:7.16675
[661]	validation-rmse:7.16692
[662]	validation-rmse:7.16665
[663]	validation-rmse:7.16670
[664]	validation-rmse:7.16672
[665]	validation-rmse:7.16670
[666]	validation-rmse:7.16754
[667]	validation-rmse:7.16691
[668]	validation-rmse:7.16680
[669]	validation-rmse:7.16700

[13:14:13] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[0]	validation-rmse:17.07324
[1]	validation-rmse:14.30469
[2]	validation-rmse:12.43555
[3]	validation-rmse:11.25809
[4]	validation-rmse:10.38463
[5]	validation-rmse:9.88533
[6]	validation-rmse:9.57101
[7]	validation-rmse:9.29420
[8]	validation-rmse:9.14369
[9]	validation-rmse:8.99487
[10]	validation-rmse:8.89520
[11]	validation-rmse:8.81087
[12]	validation-rmse:8.74929
[13]	validation-rmse:8.69705
[14]	validation-rmse:8.66439
[15]	validation-rmse:8.63054
[16]	validation-rmse:8.59693
[17]	validation-rmse:8.57936
[18]	validation-rmse:8.55888
[19]	validation-rmse:8.53872
[20]	validation-rmse:8.51999
[21]	validation-rmse:8.50588
[22]	validation-rmse:8.48582
[23]	validation-rmse:8.45561
[24]	validation-rmse:8.43664
[25]	validation-rmse:8.41878
[26]	validation-rmse:8.40193
[27]	validation-rmse:8.38616
[28]	validation-rmse:8.37077
[29]	validation-rmse:8.35563
[30]	validation-rmse:8.33973
[31]	validation-rmse:8.32488
[32]	validation-rmse:8.30154
[33]	validation-rmse:8.28447
[34]	validation-rmse:8.27194
[35]	validation-rmse:8.25992
[36]	validation-rmse:8.24951
[37]	validation-rmse:8.23744
[38]	validation-rmse:8.22851
[39]	validation-rmse:8.21401
[40]	validation-rmse:8.20075
[41]	validation-rmse:8.19162
[42]	validation-rmse:8.18226
[43]	validation-rmse:8.16892
[44]	validation-rmse:8.15386
[45]	validation-rmse:8.14297
[46]	validation-rmse:8.13299
[47]	validation-rmse:8.12316
[48]	validation-rmse:8.11437
[49]	validation-rmse:8.10767
[50]	validation-rmse:8.09622
[51]	validation-rmse:8.08839
[52]	validation-rmse:8.07944
[53]	validation-rmse:8.07231
[54]	validation-rmse:8.06518
[55]	validation-rmse:8.05436
[56]	validation-rmse:8.04827
[57]	validation-rmse:8.04016
[58]	validation-rmse:8.03302
[59]	validation-rmse:8.02640
[60]	validation-rmse:8.01974
[61]	validation-rmse:8.01187
[62]	validation-rmse:8.00708
[63]	validation-rmse:7.99986
[64]	validation-rmse:7.99434
[65]	validation-rmse:7.98736
[66]	validation-rmse:7.98350
[67]	validation-rmse:7.97939
[68]	validation-rmse:7.97363
[69]	validation-rmse:7.97060
[70]	validation-rmse:7.96654
[71]	validation-rmse:7.96290
[72]	validation-rmse:7.95858
[73]	validation-rmse:7.95312
[74]	validation-rmse:7.94968
[75]	validation-rmse:7.94111
[76]	validation-rmse:7.93751
[77]	validation-rmse:7.93376
[78]	validation-rmse:7.93114
[79]	validation-rmse:7.92858
[80]	validation-rmse:7.92104
[81]	validation-rmse:7.91785
[82]	validation-rmse:7.91422
[83]	validation-rmse:7.90845
[84]	validation-rmse:7.90671
[85]	validation-rmse:7.90257
[86]	validation-rmse:7.89814
[87]	validation-rmse:7.89202
[88]	validation-rmse:7.87653
[89]	validation-rmse:7.87124
[90]	validation-rmse:7.86524
[91]	validation-rmse:7.86268
[92]	validation-rmse:7.85878
[93]	validation-rmse:7.85392
[94]	validation-rmse:7.84663
[95]	validation-rmse:7.84149
[96]	validation-rmse:7.83452
[97]	validation-rmse:7.82850
[98]	validation-rmse:7.82475
[99]	validation-rmse:7.81979
[100]	validation-rmse:7.81435
[101]	validation-rmse:7.80593
[102]	validation-rmse:7.80065
[103]	validation-rmse:7.79686
[104]	validation-rmse:7.79227
[105]	validation-rmse:7.78531
[106]	validation-rmse:7.78089
[107]	validation-rmse:7.77705
[108]	validation-rmse:7.77130
[109]	validation-rmse:7.76561
[110]	validation-rmse:7.76188
[111]	validation-rmse:7.75677
[112]	validation-rmse:7.75116
[113]	validation-rmse:7.74652
[114]	validation-rmse:7.74387
[115]	validation-rmse:7.73951
[116]	validation-rmse:7.73731
[117]	validation-rmse:7.73439
[118]	validation-rmse:7.72990
[119]	validation-rmse:7.72036
[120]	validation-rmse:7.71695
[121]	validation-rmse:7.71445
[122]	validation-rmse:7.71321
[123]	validation-rmse:7.71208
[124]	validation-rmse:7.71008
[125]	validation-rmse:7.70904
[126]	validation-rmse:7.70674
[127]	validation-rmse:7.70570
[128]	validation-rmse:7.70492
[129]	validation-rmse:7.70181
[130]	validation-rmse:7.69785
[131]	validation-rmse:7.69237
[132]	validation-rmse:7.69104
[133]	validation-rmse:7.68505
[134]	validation-rmse:7.68264
[135]	validation-rmse:7.68008
[136]	validation-rmse:7.67427
[137]	validation-rmse:7.66837
[138]	validation-rmse:7.66201
[139]	validation-rmse:7.65951
[140]	validation-rmse:7.65319
[141]	validation-rmse:7.64399
[142]	validation-rmse:7.63809
[143]	validation-rmse:7.63050
[144]	validation-rmse:7.62250
[145]	validation-rmse:7.61879
[146]	validation-rmse:7.61453
[147]	validation-rmse:7.60993
[148]	validation-rmse:7.60463
[149]	validation-rmse:7.59687
[150]	validation-rmse:7.59022
[151]	validation-rmse:7.58483
[152]	validation-rmse:7.58099
[153]	validation-rmse:7.57666
[154]	validation-rmse:7.57086
[155]	validation-rmse:7.56793
[156]	validation-rmse:7.56344
[157]	validation-rmse:7.55983
[158]	validation-rmse:7.55633
[159]	validation-rmse:7.55234
[160]	validation-rmse:7.54957
[161]	validation-rmse:7.54708
[162]	validation-rmse:7.54188
[163]	validation-rmse:7.53942
[164]	validation-rmse:7.53696
[165]	validation-rmse:7.53607
[166]	validation-rmse:7.53286
[167]	validation-rmse:7.52826
[168]	validation-rmse:7.52645
[169]	validation-rmse:7.52383
[170]	validation-rmse:7.52041
[171]	validation-rmse:7.51966
[172]	validation-rmse:7.51634
[173]	validation-rmse:7.51374
[174]	validation-rmse:7.51111
[175]	validation-rmse:7.50576
[176]	validation-rmse:7.50303
[177]	validation-rmse:7.50104
[178]	validation-rmse:7.49610
[179]	validation-rmse:7.49393
[180]	validation-rmse:7.49241
[181]	validation-rmse:7.48741
[182]	validation-rmse:7.48496
[183]	validation-rmse:7.48180
[184]	validation-rmse:7.48016
[185]	validation-rmse:7.47728
[186]	validation-rmse:7.47559
[187]	validation-rmse:7.47345
[188]	validation-rmse:7.47161
[189]	validation-rmse:7.46738
[190]	validation-rmse:7.46504
[191]	validation-rmse:7.46302
[192]	validation-rmse:7.46112
[193]	validation-rmse:7.45969
[194]	validation-rmse:7.45670
[195]	validation-rmse:7.45694
[196]	validation-rmse:7.45598
[197]	validation-rmse:7.45291
[198]	validation-rmse:7.45100
[199]	validation-rmse:7.44982
[200]	validation-rmse:7.44804
[201]	validation-rmse:7.44761
[202]	validation-rmse:7.44686
[203]	validation-rmse:7.44541
[204]	validation-rmse:7.44458
[205]	validation-rmse:7.44222
[206]	validation-rmse:7.43951
[207]	validation-rmse:7.43637
[208]	validation-rmse:7.43421
[209]	validation-rmse:7.43245
[210]	validation-rmse:7.43081
[211]	validation-rmse:7.42680
[212]	validation-rmse:7.42467
[213]	validation-rmse:7.42413
[214]	validation-rmse:7.42104
[215]	validation-rmse:7.41861
[216]	validation-rmse:7.41714
[217]	validation-rmse:7.41678
[218]	validation-rmse:7.41643
[219]	validation-rmse:7.41370
[220]	validation-rmse:7.41327
[221]	validation-rmse:7.41191
[222]	validation-rmse:7.41158
[223]	validation-rmse:7.40835
[224]	validation-rmse:7.40656
[225]	validation-rmse:7.40252
[226]	validation-rmse:7.40237
[227]	validation-rmse:7.40040
[228]	validation-rmse:7.39806
[229]	validation-rmse:7.39450
[230]	validation-rmse:7.39303
[231]	validation-rmse:7.39150
[232]	validation-rmse:7.38944
[233]	validation-rmse:7.38803
[234]	validation-rmse:7.38609
[235]	validation-rmse:7.38449
[236]	validation-rmse:7.37911
[237]	validation-rmse:7.37714
[238]	validation-rmse:7.37534
[239]	validation-rmse:7.37141
[240]	validation-rmse:7.36946
[241]	validation-rmse:7.36688
[242]	validation-rmse:7.36484
[243]	validation-rmse:7.36335
[244]	validation-rmse:7.36259
[245]	validation-rmse:7.36003
[246]	validation-rmse:7.35788
[247]	validation-rmse:7.35660
[248]	validation-rmse:7.35451
[249]	validation-rmse:7.35319
[250]	validation-rmse:7.35204
[251]	validation-rmse:7.35130
[252]	validation-rmse:7.35038
[253]	validation-rmse:7.34817
[254]	validation-rmse:7.34556
[255]	validation-rmse:7.34329
[256]	validation-rmse:7.34170
[257]	validation-rmse:7.33781
[258]	validation-rmse:7.33709
[259]	validation-rmse:7.33639
[260]	validation-rmse:7.33638
[261]	validation-rmse:7.33492
[262]	validation-rmse:7.33496
[263]	validation-rmse:7.33260
[264]	validation-rmse:7.33142
[265]	validation-rmse:7.32932
[266]	validation-rmse:7.32712
[267]	validation-rmse:7.32328
[268]	validation-rmse:7.32216
[269]	validation-rmse:7.32041
[270]	validation-rmse:7.31981
[271]	validation-rmse:7.31908
[272]	validation-rmse:7.31691
[273]	validation-rmse:7.31552
[274]	validation-rmse:7.31491
[275]	validation-rmse:7.31391
[276]	validation-rmse:7.31265
[277]	validation-rmse:7.31121
[278]	validation-rmse:7.30969
[279]	validation-rmse:7.30715
[280]	validation-rmse:7.30568
[281]	validation-rmse:7.30151
[282]	validation-rmse:7.29968
[283]	validation-rmse:7.29885
[284]	validation-rmse:7.29758
[285]	validation-rmse:7.29511
[286]	validation-rmse:7.29341
[287]	validation-rmse:7.29094
[288]	validation-rmse:7.28936
[289]	validation-rmse:7.28849
[290]	validation-rmse:7.28392
[291]	validation-rmse:7.28115
[292]	validation-rmse:7.27970
[293]	validation-rmse:7.27657
[294]	validation-rmse:7.27259
[295]	validation-rmse:7.27091
[296]	validation-rmse:7.26722
[297]	validation-rmse:7.26628
[298]	validation-rmse:7.26413
[299]	validation-rmse:7.26357
[300]	validation-rmse:7.26104
[301]	validation-rmse:7.26076
[302]	validation-rmse:7.25996
[303]	validation-rmse:7.25734
[304]	validation-rmse:7.25631
[305]	validation-rmse:7.25557
[306]	validation-rmse:7.25437
[307]	validation-rmse:7.25390
[308]	validation-rmse:7.25152
[309]	validation-rmse:7.25095
[310]	validation-rmse:7.25046
[311]	validation-rmse:7.25006
[312]	validation-rmse:7.24902
[313]	validation-rmse:7.24778
[314]	validation-rmse:7.24770
[315]	validation-rmse:7.24342
[316]	validation-rmse:7.24279
[317]	validation-rmse:7.24246
[318]	validation-rmse:7.24177
[319]	validation-rmse:7.24166
[320]	validation-rmse:7.24132
[321]	validation-rmse:7.23964
[322]	validation-rmse:7.23917
[323]	validation-rmse:7.23765
[324]	validation-rmse:7.23813
[325]	validation-rmse:7.23774
[326]	validation-rmse:7.23760
[327]	validation-rmse:7.23675
[328]	validation-rmse:7.23641
[329]	validation-rmse:7.23557
[330]	validation-rmse:7.23499
[331]	validation-rmse:7.23410
[332]	validation-rmse:7.23360
[333]	validation-rmse:7.23227
[334]	validation-rmse:7.23177
[335]	validation-rmse:7.23150
[336]	validation-rmse:7.23091
[337]	validation-rmse:7.23001
[338]	validation-rmse:7.23016
[339]	validation-rmse:7.22988
[340]	validation-rmse:7.22973
[341]	validation-rmse:7.22949
[342]	validation-rmse:7.22858
[343]	validation-rmse:7.22671
[344]	validation-rmse:7.22545
[345]	validation-rmse:7.22505
[346]	validation-rmse:7.22472
[347]	validation-rmse:7.22360
[348]	validation-rmse:7.22243
[349]	validation-rmse:7.22136
[350]	validation-rmse:7.22031
[351]	validation-rmse:7.21961
[352]	validation-rmse:7.21911
[353]	validation-rmse:7.21801
[354]	validation-rmse:7.21769
[355]	validation-rmse:7.21786
[356]	validation-rmse:7.21685
[357]	validation-rmse:7.21609
[358]	validation-rmse:7.21486
[359]	validation-rmse:7.21401
[360]	validation-rmse:7.21321
[361]	validation-rmse:7.21241
[362]	validation-rmse:7.21146
[363]	validation-rmse:7.21028
[364]	validation-rmse:7.21087
[365]	validation-rmse:7.20949
[366]	validation-rmse:7.20901
[367]	validation-rmse:7.20832
[368]	validation-rmse:7.20768
[369]	validation-rmse:7.20659
[370]	validation-rmse:7.20515
[371]	validation-rmse:7.20452
[372]	validation-rmse:7.20370
[373]	validation-rmse:7.20317
[374]	validation-rmse:7.20244
[375]	validation-rmse:7.20145
[376]	validation-rmse:7.20107
[377]	validation-rmse:7.20032
[378]	validation-rmse:7.19832
[379]	validation-rmse:7.19744
[380]	validation-rmse:7.19643
[381]	validation-rmse:7.19609
[382]	validation-rmse:7.19538
[383]	validation-rmse:7.19525
[384]	validation-rmse:7.19490
[385]	validation-rmse:7.19476
[386]	validation-rmse:7.19492
[387]	validation-rmse:7.19419
[388]	validation-rmse:7.19389
[389]	validation-rmse:7.19321
[390]	validation-rmse:7.19259
[391]	validation-rmse:7.19196
[392]	validation-rmse:7.19149
[393]	validation-rmse:7.19035
[394]	validation-rmse:7.18970
[395]	validation-rmse:7.18904
[396]	validation-rmse:7.18839
[397]	validation-rmse:7.18767
[398]	validation-rmse:7.18762
[399]	validation-rmse:7.18668
[400]	validation-rmse:7.18613
[401]	validation-rmse:7.18544
[402]	validation-rmse:7.18520
[403]	validation-rmse:7.18429
[404]	validation-rmse:7.18468
[405]	validation-rmse:7.18475
[406]	validation-rmse:7.18339
[407]	validation-rmse:7.18266
[408]	validation-rmse:7.18153
[409]	validation-rmse:7.17981
[410]	validation-rmse:7.18010
[411]	validation-rmse:7.17998
[412]	validation-rmse:7.17915
[413]	validation-rmse:7.17845
[414]	validation-rmse:7.17771
[415]	validation-rmse:7.17602
[416]	validation-rmse:7.17554
[417]	validation-rmse:7.17514
[418]	validation-rmse:7.17354
[419]	validation-rmse:7.17221
[420]	validation-rmse:7.17224
[421]	validation-rmse:7.17121
[422]	validation-rmse:7.17015
[423]	validation-rmse:7.16972
[424]	validation-rmse:7.16862
[425]	validation-rmse:7.16851
[426]	validation-rmse:7.16803
[427]	validation-rmse:7.16707
[428]	validation-rmse:7.16683
[429]	validation-rmse:7.16612
[430]	validation-rmse:7.16537
[431]	validation-rmse:7.16413
[432]	validation-rmse:7.16353
[433]	validation-rmse:7.16261
[434]	validation-rmse:7.16268
[435]	validation-rmse:7.16190
[436]	validation-rmse:7.16187
[437]	validation-rmse:7.16182
[438]	validation-rmse:7.16139
[439]	validation-rmse:7.16107
[440]	validation-rmse:7.16071
[441]	validation-rmse:7.15981
[442]	validation-rmse:7.15898
[443]	validation-rmse:7.15843
[444]	validation-rmse:7.15841
[445]	validation-rmse:7.15820
[446]	validation-rmse:7.15504
[447]	validation-rmse:7.15383
[448]	validation-rmse:7.15250
[449]	validation-rmse:7.15285
[450]	validation-rmse:7.15219
[451]	validation-rmse:7.15171
[452]	validation-rmse:7.15148
[453]	validation-rmse:7.15117
[454]	validation-rmse:7.15068
[455]	validation-rmse:7.15037
[456]	validation-rmse:7.15029
[457]	validation-rmse:7.14986
[458]	validation-rmse:7.15016
[459]	validation-rmse:7.15023
[460]	validation-rmse:7.14971
[461]	validation-rmse:7.14897
[462]	validation-rmse:7.14854
[463]	validation-rmse:7.14796
[464]	validation-rmse:7.14773
[465]	validation-rmse:7.14746
[466]	validation-rmse:7.14714
[467]	validation-rmse:7.14616
[468]	validation-rmse:7.14622
[469]	validation-rmse:7.14604
[470]	validation-rmse:7.14537
[471]	validation-rmse:7.14494
[472]	validation-rmse:7.14476
[473]	validation-rmse:7.14410
[474]	validation-rmse:7.14390
[475]	validation-rmse:7.14375
[476]	validation-rmse:7.14366
[477]	validation-rmse:7.14334
[478]	validation-rmse:7.14314
[479]	validation-rmse:7.14294
[480]	validation-rmse:7.14241
[481]	validation-rmse:7.14141
[482]	validation-rmse:7.14132
[483]	validation-rmse:7.14074
[484]	validation-rmse:7.14062
[485]	validation-rmse:7.14021
[486]	validation-rmse:7.13983
[487]	validation-rmse:7.13971
[488]	validation-rmse:7.13924
[489]	validation-rmse:7.13880
[490]	validation-rmse:7.13921
[491]	validation-rmse:7.13950
[492]	validation-rmse:7.13830
[493]	validation-rmse:7.13777
[494]	validation-rmse:7.13724
[495]	validation-rmse:7.13715
[496]	validation-rmse:7.13640
[497]	validation-rmse:7.13652
[498]	validation-rmse:7.13613
[499]	validation-rmse:7.13580
[500]	validation-rmse:7.13545
[501]	validation-rmse:7.13597
[502]	validation-rmse:7.13554
[503]	validation-rmse:7.13339
[504]	validation-rmse:7.13306
[505]	validation-rmse:7.13236
[506]	validation-rmse:7.13175
[507]	validation-rmse:7.13108
[508]	validation-rmse:7.13148
[509]	validation-rmse:7.13036
[510]	validation-rmse:7.13019
[511]	validation-rmse:7.13037
[512]	validation-rmse:7.12964
[513]	validation-rmse:7.12989
[514]	validation-rmse:7.12934
[515]	validation-rmse:7.12957
[516]	validation-rmse:7.12902
[517]	validation-rmse:7.12806
[518]	validation-rmse:7.12688
[519]	validation-rmse:7.12683
[520]	validation-rmse:7.12685
[521]	validation-rmse:7.12678
[522]	validation-rmse:7.12650
[523]	validation-rmse:7.12630
[524]	validation-rmse:7.12652
[525]	validation-rmse:7.12647
[526]	validation-rmse:7.12585
[527]	validation-rmse:7.12557
[528]	validation-rmse:7.12502
[529]	validation-rmse:7.12473
[530]	validation-rmse:7.12415
[531]	validation-rmse:7.12388
[532]	validation-rmse:7.12354
[533]	validation-rmse:7.12386
[534]	validation-rmse:7.12253
[535]	validation-rmse:7.12255
[536]	validation-rmse:7.12217
[537]	validation-rmse:7.12219
[538]	validation-rmse:7.12128
[539]	validation-rmse:7.12133
[540]	validation-rmse:7.12119
[541]	validation-rmse:7.12068
[542]	validation-rmse:7.11983
[543]	validation-rmse:7.11946
[544]	validation-rmse:7.11923
[545]	validation-rmse:7.11914
[546]	validation-rmse:7.11854
[547]	validation-rmse:7.11796
[548]	validation-rmse:7.11754
[549]	validation-rmse:7.11816
[550]	validation-rmse:7.11756
[551]	validation-rmse:7.11696
[552]	validation-rmse:7.11684
[553]	validation-rmse:7.11660
[554]	validation-rmse:7.11654
[555]	validation-rmse:7.11649
[556]	validation-rmse:7.11632
[557]	validation-rmse:7.11489
[558]	validation-rmse:7.11464
[559]	validation-rmse:7.11405
[560]	validation-rmse:7.11420
[561]	validation-rmse:7.11352
[562]	validation-rmse:7.11359
[563]	validation-rmse:7.11267
[564]	validation-rmse:7.11258
[565]	validation-rmse:7.11228
[566]	validation-rmse:7.11217
[567]	validation-rmse:7.11183
[568]	validation-rmse:7.11121
[569]	validation-rmse:7.11052
[570]	validation-rmse:7.11079
[571]	validation-rmse:7.11108
[572]	validation-rmse:7.11144
[573]	validation-rmse:7.11111
[574]	validation-rmse:7.11111
[575]	validation-rmse:7.10968
[576]	validation-rmse:7.10929
[577]	validation-rmse:7.10883
[578]	validation-rmse:7.10845
[579]	validation-rmse:7.10846
[580]	validation-rmse:7.10797
[581]	validation-rmse:7.10812
[582]	validation-rmse:7.10755
[583]	validation-rmse:7.10728
[584]	validation-rmse:7.10794
[585]	validation-rmse:7.10748
[586]	validation-rmse:7.10751
[587]	validation-rmse:7.10719
[588]	validation-rmse:7.10683
[589]	validation-rmse:7.10615
[590]	validation-rmse:7.10641
[591]	validation-rmse:7.10575
[592]	validation-rmse:7.10540
[593]	validation-rmse:7.10482
[594]	validation-rmse:7.10494
[595]	validation-rmse:7.10426
[596]	validation-rmse:7.10476
[597]	validation-rmse:7.10480
[598]	validation-rmse:7.10448
[599]	validation-rmse:7.10465
[600]	validation-rmse:7.10462
[601]	validation-rmse:7.10436
[602]	validation-rmse:7.10340
[603]	validation-rmse:7.10335
[604]	validation-rmse:7.10343
[605]	validation-rmse:7.10317
[606]	validation-rmse:7.10257
[607]	validation-rmse:7.10123
[608]	validation-rmse:7.10095
[609]	validation-rmse:7.10079
[610]	validation-rmse:7.09951
[611]	validation-rmse:7.09887
[612]	validation-rmse:7.09921
[613]	validation-rmse:7.09902
[614]	validation-rmse:7.09915
[615]	validation-rmse:7.09873
[616]	validation-rmse:7.09803
[617]	validation-rmse:7.09794
[618]	validation-rmse:7.09760
[619]	validation-rmse:7.09725
[620]	validation-rmse:7.09692
[621]	validation-rmse:7.09664
[622]	validation-rmse:7.09648
[623]	validation-rmse:7.09632
[624]	validation-rmse:7.09584
[625]	validation-rmse:7.09613
[626]	validation-rmse:7.09533
[627]	validation-rmse:7.09492
[628]	validation-rmse:7.09410
[629]	validation-rmse:7.09390
[630]	validation-rmse:7.09358
[631]	validation-rmse:7.09341
[632]	validation-rmse:7.09283
[633]	validation-rmse:7.09228
[634]	validation-rmse:7.09207
[635]	validation-rmse:7.09227
[636]	validation-rmse:7.09177
[637]	validation-rmse:7.09184
[638]	validation-rmse:7.09165
[639]	validation-rmse:7.09110
[640]	validation-rmse:7.08718
[641]	validation-rmse:7.08682
[642]	validation-rmse:7.08613
[643]	validation-rmse:7.08618
[644]	validation-rmse:7.08574
[645]	validation-rmse:7.08543
[646]	validation-rmse:7.08497
[647]	validation-rmse:7.08502
[648]	validation-rmse:7.08515
[649]	validation-rmse:7.08487
[650]	validation-rmse:7.08443
[651]	validation-rmse:7.08431
[652]	validation-rmse:7.08410
[653]	validation-rmse:7.08390
[654]	validation-rmse:7.08407
[655]	validation-rmse:7.08393
[656]	validation-rmse:7.08338
[657]	validation-rmse:7.08276
[658]	validation-rmse:7.08242
[659]	validation-rmse:7.08144
[660]	validation-rmse:7.08046
[661]	validation-rmse:7.08061
[662]	validation-rmse:7.08019
[663]	validation-rmse:7.07987
[664]	validation-rmse:7.07975
[665]	validation-rmse:7.07948
[666]	validation-rmse:7.07922
[667]	validation-rmse:7.07912
[668]	validation-rmse:7.07867
[669]	validation-rmse:7.07836

[13:20:08] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:14.13383
[2]	validation-rmse:12.27419
[3]	validation-rmse:11.09984
[4]	validation-rmse:10.26401
[5]	validation-rmse:9.80171
[6]	validation-rmse:9.40992
[7]	validation-rmse:9.19884
[8]	validation-rmse:9.06848
[9]	validation-rmse:8.91756
[10]	validation-rmse:8.82512
[11]	validation-rmse:8.75665
[12]	validation-rmse:8.68858
[13]	validation-rmse:8.64590
[14]	validation-rmse:8.59214
[15]	validation-rmse:8.55589
[16]	validation-rmse:8.52829
[17]	validation-rmse:8.51035
[18]	validation-rmse:8.49295
[19]	validation-rmse:8.47497
[20]	validation-rmse:8.46214
[21]	validation-rmse:8.44243
[22]	validation-rmse:8.42096
[23]	validation-rmse:8.40920
[24]	validation-rmse:8.39760
[25]	validation-rmse:8.38827
[26]	validation-rmse:8.37497
[27]	validation-rmse:8.35895
[28]	validation-rmse:8.34542
[29]	validation-rmse:8.33502
[30]	validation-rmse:8.31818
[31]	validation-rmse:8.30582
[32]	validation-rmse:8.29264
[33]	validation-rmse:8.27757
[34]	validation-rmse:8.26446
[35]	validation-rmse:8.25172
[36]	validation-rmse:8.24318
[37]	validation-rmse:8.23291
[38]	validation-rmse:8.21549
[39]	validation-rmse:8.20127
[40]	validation-rmse:8.19684
[41]	validation-rmse:8.18652
[42]	validation-rmse:8.17783
[43]	validation-rmse:8.16784
[44]	validation-rmse:8.15684
[45]	validation-rmse:8.14799
[46]	validation-rmse:8.14102
[47]	validation-rmse:8.13468
[48]	validation-rmse:8.12487
[49]	validation-rmse:8.11910
[50]	validation-rmse:8.10946
[51]	validation-rmse:8.10240
[52]	validation-rmse:8.09510
[53]	validation-rmse:8.08787
[54]	validation-rmse:8.08006
[55]	validation-rmse:8.07310
[56]	validation-rmse:8.06713
[57]	validation-rmse:8.06394
[58]	validation-rmse:8.05854
[59]	validation-rmse:8.05225
[60]	validation-rmse:8.04551
[61]	validation-rmse:8.04167
[62]	validation-rmse:8.03445
[63]	validation-rmse:8.02932
[64]	validation-rmse:8.02645
[65]	validation-rmse:8.02201
[66]	validation-rmse:8.01811
[67]	validation-rmse:8.01017
[68]	validation-rmse:8.00596
[69]	validation-rmse:8.00095
[70]	validation-rmse:7.99677
[71]	validation-rmse:7.99237
[72]	validation-rmse:7.98939
[73]	validation-rmse:7.98662
[74]	validation-rmse:7.97933
[75]	validation-rmse:7.97280
[76]	validation-rmse:7.96859
[77]	validation-rmse:7.96155
[78]	validation-rmse:7.95729
[79]	validation-rmse:7.95236
[80]	validation-rmse:7.94576
[81]	validation-rmse:7.94183
[82]	validation-rmse:7.93867
[83]	validation-rmse:7.93453
[84]	validation-rmse:7.93286
[85]	validation-rmse:7.92787
[86]	validation-rmse:7.92188
[87]	validation-rmse:7.91910
[88]	validation-rmse:7.91337
[89]	validation-rmse:7.90846
[90]	validation-rmse:7.90445
[91]	validation-rmse:7.90035
[92]	validation-rmse:7.89634
[93]	validation-rmse:7.88815
[94]	validation-rmse:7.88290
[95]	validation-rmse:7.87384
[96]	validation-rmse:7.86639
[97]	validation-rmse:7.85957
[98]	validation-rmse:7.85642
[99]	validation-rmse:7.85321
[100]	validation-rmse:7.84940
[101]	validation-rmse:7.84343
[102]	validation-rmse:7.83930
[103]	validation-rmse:7.83454
[104]	validation-rmse:7.83287
[105]	validation-rmse:7.82653
[106]	validation-rmse:7.82225
[107]	validation-rmse:7.81789
[108]	validation-rmse:7.81325
[109]	validation-rmse:7.80930
[110]	validation-rmse:7.80632
[111]	validation-rmse:7.80213
[112]	validation-rmse:7.79869
[113]	validation-rmse:7.79448
[114]	validation-rmse:7.78967
[115]	validation-rmse:7.78636
[116]	validation-rmse:7.78061
[117]	validation-rmse:7.77507
[118]	validation-rmse:7.77158
[119]	validation-rmse:7.76861
[120]	validation-rmse:7.76218
[121]	validation-rmse:7.75972
[122]	validation-rmse:7.75584
[123]	validation-rmse:7.75248
[124]	validation-rmse:7.74992
[125]	validation-rmse:7.74626
[126]	validation-rmse:7.73978
[127]	validation-rmse:7.73716
[128]	validation-rmse:7.73021
[129]	validation-rmse:7.72705
[130]	validation-rmse:7.72334
[131]	validation-rmse:7.71942
[132]	validation-rmse:7.71702
[133]	validation-rmse:7.71509
[134]	validation-rmse:7.70420
[135]	validation-rmse:7.69948
[136]	validation-rmse:7.69210
[137]	validation-rmse:7.68858
[138]	validation-rmse:7.68332
[139]	validation-rmse:7.67851
[140]	validation-rmse:7.67436
[141]	validation-rmse:7.66822
[142]	validation-rmse:7.66156
[143]	validation-rmse:7.65957
[144]	validation-rmse:7.65495
[145]	validation-rmse:7.64922
[146]	validation-rmse:7.64481
[147]	validation-rmse:7.64064
[148]	validation-rmse:7.63442
[149]	validation-rmse:7.63048
[150]	validation-rmse:7.62428
[151]	validation-rmse:7.61958
[152]	validation-rmse:7.61183
[153]	validation-rmse:7.60812
[154]	validation-rmse:7.60389
[155]	validation-rmse:7.59992
[156]	validation-rmse:7.59639
[157]	validation-rmse:7.59056
[158]	validation-rmse:7.58689
[159]	validation-rmse:7.58315
[160]	validation-rmse:7.57845
[161]	validation-rmse:7.57361
[162]	validation-rmse:7.56878
[163]	validation-rmse:7.56673
[164]	validation-rmse:7.56429
[165]	validation-rmse:7.56140
[166]	validation-rmse:7.55926
[167]	validation-rmse:7.55686
[168]	validation-rmse:7.55500
[169]	validation-rmse:7.55327
[170]	validation-rmse:7.54975
[171]	validation-rmse:7.54819
[172]	validation-rmse:7.54713
[173]	validation-rmse:7.54522
[174]	validation-rmse:7.54175
[175]	validation-rmse:7.54092
[176]	validation-rmse:7.53981
[177]	validation-rmse:7.53759
[178]	validation-rmse:7.53761
[179]	validation-rmse:7.53456
[180]	validation-rmse:7.53129
[181]	validation-rmse:7.53049
[182]	validation-rmse:7.52439
[183]	validation-rmse:7.52251
[184]	validation-rmse:7.52068
[185]	validation-rmse:7.51886
[186]	validation-rmse:7.51768
[187]	validation-rmse:7.51651
[188]	validation-rmse:7.51361
[189]	validation-rmse:7.51206
[190]	validation-rmse:7.51082
[191]	validation-rmse:7.50910
[192]	validation-rmse:7.50791
[193]	validation-rmse:7.50709
[194]	validation-rmse:7.50588
[195]	validation-rmse:7.50485
[196]	validation-rmse:7.50292
[197]	validation-rmse:7.50117
[198]	validation-rmse:7.49918
[199]	validation-rmse:7.49669
[200]	validation-rmse:7.49560
[201]	validation-rmse:7.49444
[202]	validation-rmse:7.49245
[203]	validation-rmse:7.49090
[204]	validation-rmse:7.48917
[205]	validation-rmse:7.48787
[206]	validation-rmse:7.48742
[207]	validation-rmse:7.48605
[208]	validation-rmse:7.48178
[209]	validation-rmse:7.47988
[210]	validation-rmse:7.47849
[211]	validation-rmse:7.47754
[212]	validation-rmse:7.47680
[213]	validation-rmse:7.47495
[214]	validation-rmse:7.47340
[215]	validation-rmse:7.47259
[216]	validation-rmse:7.47147
[217]	validation-rmse:7.47042
[218]	validation-rmse:7.46658
[219]	validation-rmse:7.46571
[220]	validation-rmse:7.46458
[221]	validation-rmse:7.45967
[222]	validation-rmse:7.45866
[223]	validation-rmse:7.45801
[224]	validation-rmse:7.45658
[225]	validation-rmse:7.45438
[226]	validation-rmse:7.45236
[227]	validation-rmse:7.45025
[228]	validation-rmse:7.44666
[229]	validation-rmse:7.44425
[230]	validation-rmse:7.44136
[231]	validation-rmse:7.43975
[232]	validation-rmse:7.43907
[233]	validation-rmse:7.43722
[234]	validation-rmse:7.43351
[235]	validation-rmse:7.43259
[236]	validation-rmse:7.43214
[237]	validation-rmse:7.42915
[238]	validation-rmse:7.42640
[239]	validation-rmse:7.42522
[240]	validation-rmse:7.42276
[241]	validation-rmse:7.42088
[242]	validation-rmse:7.42003
[243]	validation-rmse:7.42060
[244]	validation-rmse:7.41893
[245]	validation-rmse:7.41701
[246]	validation-rmse:7.41643
[247]	validation-rmse:7.41604
[248]	validation-rmse:7.41434
[249]	validation-rmse:7.41346
[250]	validation-rmse:7.41236
[251]	validation-rmse:7.41102
[252]	validation-rmse:7.40720
[253]	validation-rmse:7.40486
[254]	validation-rmse:7.40011
[255]	validation-rmse:7.39347
[256]	validation-rmse:7.39369
[257]	validation-rmse:7.39263
[258]	validation-rmse:7.39112
[259]	validation-rmse:7.39048
[260]	validation-rmse:7.38993
[261]	validation-rmse:7.38925
[262]	validation-rmse:7.38938
[263]	validation-rmse:7.38906
[264]	validation-rmse:7.38541
[265]	validation-rmse:7.38402
[266]	validation-rmse:7.38384
[267]	validation-rmse:7.38232
[268]	validation-rmse:7.38200
[269]	validation-rmse:7.38073
[270]	validation-rmse:7.38017
[271]	validation-rmse:7.37998
[272]	validation-rmse:7.37818
[273]	validation-rmse:7.37723
[274]	validation-rmse:7.37512
[275]	validation-rmse:7.37319
[276]	validation-rmse:7.37314
[277]	validation-rmse:7.37093
[278]	validation-rmse:7.36963
[279]	validation-rmse:7.36643
[280]	validation-rmse:7.36475
[281]	validation-rmse:7.36381
[282]	validation-rmse:7.36244
[283]	validation-rmse:7.36104
[284]	validation-rmse:7.35774
[285]	validation-rmse:7.35591
[286]	validation-rmse:7.35389
[287]	validation-rmse:7.35290
[288]	validation-rmse:7.35267
[289]	validation-rmse:7.35086
[290]	validation-rmse:7.34880
[291]	validation-rmse:7.34789
[292]	validation-rmse:7.34698
[293]	validation-rmse:7.34619
[294]	validation-rmse:7.34606
[295]	validation-rmse:7.34157
[296]	validation-rmse:7.33981
[297]	validation-rmse:7.33901
[298]	validation-rmse:7.33795
[299]	validation-rmse:7.33707
[300]	validation-rmse:7.33669
[301]	validation-rmse:7.33557
[302]	validation-rmse:7.33524
[303]	validation-rmse:7.33441
[304]	validation-rmse:7.33334
[305]	validation-rmse:7.33166
[306]	validation-rmse:7.33059
[307]	validation-rmse:7.32967
[308]	validation-rmse:7.32908
[309]	validation-rmse:7.32804
[310]	validation-rmse:7.32831
[311]	validation-rmse:7.32663
[312]	validation-rmse:7.32573
[313]	validation-rmse:7.32471
[314]	validation-rmse:7.32328
[315]	validation-rmse:7.31964
[316]	validation-rmse:7.31954
[317]	validation-rmse:7.31890
[318]	validation-rmse:7.31810
[319]	validation-rmse:7.31596
[320]	validation-rmse:7.31447
[321]	validation-rmse:7.31317
[322]	validation-rmse:7.31280
[323]	validation-rmse:7.31195
[324]	validation-rmse:7.30948
[325]	validation-rmse:7.30942
[326]	validation-rmse:7.30893
[327]	validation-rmse:7.30885
[328]	validation-rmse:7.30769
[329]	validation-rmse:7.30789
[330]	validation-rmse:7.30756
[331]	validation-rmse:7.30544
[332]	validation-rmse:7.30568
[333]	validation-rmse:7.30488
[334]	validation-rmse:7.29932
[335]	validation-rmse:7.29768
[336]	validation-rmse:7.29506
[337]	validation-rmse:7.29270
[338]	validation-rmse:7.29233
[339]	validation-rmse:7.29073
[340]	validation-rmse:7.28982
[341]	validation-rmse:7.28835
[342]	validation-rmse:7.28632
[343]	validation-rmse:7.28350
[344]	validation-rmse:7.28354
[345]	validation-rmse:7.28238
[346]	validation-rmse:7.27978
[347]	validation-rmse:7.27776
[348]	validation-rmse:7.27588
[349]	validation-rmse:7.27466
[350]	validation-rmse:7.27139
[351]	validation-rmse:7.26981
[352]	validation-rmse:7.26667
[353]	validation-rmse:7.26577
[354]	validation-rmse:7.26259
[355]	validation-rmse:7.26144
[356]	validation-rmse:7.26139
[357]	validation-rmse:7.25874
[358]	validation-rmse:7.25636
[359]	validation-rmse:7.25548
[360]	validation-rmse:7.25335
[361]	validation-rmse:7.25289
[362]	validation-rmse:7.25119
[363]	validation-rmse:7.24724
[364]	validation-rmse:7.24658
[365]	validation-rmse:7.24558
[366]	validation-rmse:7.24505
[367]	validation-rmse:7.24338
[368]	validation-rmse:7.24222
[369]	validation-rmse:7.24205
[370]	validation-rmse:7.23960
[371]	validation-rmse:7.23981
[372]	validation-rmse:7.24002
[373]	validation-rmse:7.23784
[374]	validation-rmse:7.23729
[375]	validation-rmse:7.23631
[376]	validation-rmse:7.23618
[377]	validation-rmse:7.23673
[378]	validation-rmse:7.23636
[379]	validation-rmse:7.23517
[380]	validation-rmse:7.23429
[381]	validation-rmse:7.23402
[382]	validation-rmse:7.23162
[383]	validation-rmse:7.23123
[384]	validation-rmse:7.23041
[385]	validation-rmse:7.23000
[386]	validation-rmse:7.22959
[387]	validation-rmse:7.22919
[388]	validation-rmse:7.22846
[389]	validation-rmse:7.22807
[390]	validation-rmse:7.22756
[391]	validation-rmse:7.22615
[392]	validation-rmse:7.22587
[393]	validation-rmse:7.22626
[394]	validation-rmse:7.22557
[395]	validation-rmse:7.22443
[396]	validation-rmse:7.22453
[397]	validation-rmse:7.22459
[398]	validation-rmse:7.22372
[399]	validation-rmse:7.22309
[400]	validation-rmse:7.22211
[401]	validation-rmse:7.22250
[402]	validation-rmse:7.22271
[403]	validation-rmse:7.22195
[404]	validation-rmse:7.22130
[405]	validation-rmse:7.22090
[406]	validation-rmse:7.21911
[407]	validation-rmse:7.21775
[408]	validation-rmse:7.21746
[409]	validation-rmse:7.21697
[410]	validation-rmse:7.21629
[411]	validation-rmse:7.21609
[412]	validation-rmse:7.21482
[413]	validation-rmse:7.21412
[414]	validation-rmse:7.21352
[415]	validation-rmse:7.21344
[416]	validation-rmse:7.21315
[417]	validation-rmse:7.21206
[418]	validation-rmse:7.21143
[419]	validation-rmse:7.21059
[420]	validation-rmse:7.21060
[421]	validation-rmse:7.21051
[422]	validation-rmse:7.21036
[423]	validation-rmse:7.21042
[424]	validation-rmse:7.21009
[425]	validation-rmse:7.21000
[426]	validation-rmse:7.20985
[427]	validation-rmse:7.20939
[428]	validation-rmse:7.20910
[429]	validation-rmse:7.20859
[430]	validation-rmse:7.20800
[431]	validation-rmse:7.20691
[432]	validation-rmse:7.20598
[433]	validation-rmse:7.20568
[434]	validation-rmse:7.20495
[435]	validation-rmse:7.20480
[436]	validation-rmse:7.20461
[437]	validation-rmse:7.20409
[438]	validation-rmse:7.20221
[439]	validation-rmse:7.20217
[440]	validation-rmse:7.20199
[441]	validation-rmse:7.20183
[442]	validation-rmse:7.20161
[443]	validation-rmse:7.20135
[444]	validation-rmse:7.20114
[445]	validation-rmse:7.20061
[446]	validation-rmse:7.20051
[447]	validation-rmse:7.20023
[448]	validation-rmse:7.20051
[449]	validation-rmse:7.19990
[450]	validation-rmse:7.19843
[451]	validation-rmse:7.19803
[452]	validation-rmse:7.19796
[453]	validation-rmse:7.19657
[454]	validation-rmse:7.19536
[455]	validation-rmse:7.19441
[456]	validation-rmse:7.19387
[457]	validation-rmse:7.19377
[458]	validation-rmse:7.19364
[459]	validation-rmse:7.19180
[460]	validation-rmse:7.18992
[461]	validation-rmse:7.18970
[462]	validation-rmse:7.18947
[463]	validation-rmse:7.18854
[464]	validation-rmse:7.18750
[465]	validation-rmse:7.18714
[466]	validation-rmse:7.18657
[467]	validation-rmse:7.18658
[468]	validation-rmse:7.18587
[469]	validation-rmse:7.18553
[470]	validation-rmse:7.18430
[471]	validation-rmse:7.18362
[472]	validation-rmse:7.18343
[473]	validation-rmse:7.18245
[474]	validation-rmse:7.18191
[475]	validation-rmse:7.18165
[476]	validation-rmse:7.18095
[477]	validation-rmse:7.18055
[478]	validation-rmse:7.17959
[479]	validation-rmse:7.17930
[480]	validation-rmse:7.17841
[481]	validation-rmse:7.17723
[482]	validation-rmse:7.17698
[483]	validation-rmse:7.17701
[484]	validation-rmse:7.17661
[485]	validation-rmse:7.17674
[486]	validation-rmse:7.17685
[487]	validation-rmse:7.17566
[488]	validation-rmse:7.17440
[489]	validation-rmse:7.17427
[490]	validation-rmse:7.17402
[491]	validation-rmse:7.17356
[492]	validation-rmse:7.17360
[493]	validation-rmse:7.17208
[494]	validation-rmse:7.17215
[495]	validation-rmse:7.17161
[496]	validation-rmse:7.17144
[497]	validation-rmse:7.17169
[498]	validation-rmse:7.17102
[499]	validation-rmse:7.17038
[500]	validation-rmse:7.17026
[501]	validation-rmse:7.16997
[502]	validation-rmse:7.16947
[503]	validation-rmse:7.16914
[504]	validation-rmse:7.16923
[505]	validation-rmse:7.16896
[506]	validation-rmse:7.16888
[507]	validation-rmse:7.16837
[508]	validation-rmse:7.16755
[509]	validation-rmse:7.16719
[510]	validation-rmse:7.16629
[511]	validation-rmse:7.16264
[512]	validation-rmse:7.16214
[513]	validation-rmse:7.16140
[514]	validation-rmse:7.16110
[515]	validation-rmse:7.15929
[516]	validation-rmse:7.15943
[517]	validation-rmse:7.15941
[518]	validation-rmse:7.15936
[519]	validation-rmse:7.15837
[520]	validation-rmse:7.15834
[521]	validation-rmse:7.15830
[522]	validation-rmse:7.15901
[523]	validation-rmse:7.15834
[524]	validation-rmse:7.15795
[525]	validation-rmse:7.15737
[526]	validation-rmse:7.15698
[527]	validation-rmse:7.15686
[528]	validation-rmse:7.15685
[529]	validation-rmse:7.15681
[530]	validation-rmse:7.15702
[531]	validation-rmse:7.15648
[532]	validation-rmse:7.15628
[533]	validation-rmse:7.15572
[534]	validation-rmse:7.15569
[535]	validation-rmse:7.15580
[536]	validation-rmse:7.15511
[537]	validation-rmse:7.15465
[538]	validation-rmse:7.15451
[539]	validation-rmse:7.15339
[540]	validation-rmse:7.15309
[541]	validation-rmse:7.15257
[542]	validation-rmse:7.15327
[543]	validation-rmse:7.15279
[544]	validation-rmse:7.15223
[545]	validation-rmse:7.15174
[546]	validation-rmse:7.15070
[547]	validation-rmse:7.14997
[548]	validation-rmse:7.14981
[549]	validation-rmse:7.14892
[550]	validation-rmse:7.14850
[551]	validation-rmse:7.14790
[552]	validation-rmse:7.14846
[553]	validation-rmse:7.14848
[554]	validation-rmse:7.14804
[555]	validation-rmse:7.14833
[556]	validation-rmse:7.14809
[557]	validation-rmse:7.14746
[558]	validation-rmse:7.14660
[559]	validation-rmse:7.14572
[560]	validation-rmse:7.14558
[561]	validation-rmse:7.14525
[562]	validation-rmse:7.14447
[563]	validation-rmse:7.14478
[564]	validation-rmse:7.14441
[565]	validation-rmse:7.14447
[566]	validation-rmse:7.14372
[567]	validation-rmse:7.14371
[568]	validation-rmse:7.14360
[569]	validation-rmse:7.14200
[570]	validation-rmse:7.14199
[571]	validation-rmse:7.14119
[572]	validation-rmse:7.14087
[573]	validation-rmse:7.14154
[574]	validation-rmse:7.14070
[575]	validation-rmse:7.13965
[576]	validation-rmse:7.13960
[577]	validation-rmse:7.13938
[578]	validation-rmse:7.13895
[579]	validation-rmse:7.13811
[580]	validation-rmse:7.13844
[581]	validation-rmse:7.13861
[582]	validation-rmse:7.13826
[583]	validation-rmse:7.13820
[584]	validation-rmse:7.13797
[585]	validation-rmse:7.13654
[586]	validation-rmse:7.13586
[587]	validation-rmse:7.13629
[588]	validation-rmse:7.13621
[589]	validation-rmse:7.13621
[590]	validation-rmse:7.13556
[591]	validation-rmse:7.13512
[592]	validation-rmse:7.13500
[593]	validation-rmse:7.13476
[594]	validation-rmse:7.13450
[595]	validation-rmse:7.13409
[596]	validation-rmse:7.13401
[597]	validation-rmse:7.13402
[598]	validation-rmse:7.13375
[599]	validation-rmse:7.13304
[600]	validation-rmse:7.13276
[601]	validation-rmse:7.13263
[602]	validation-rmse:7.13228
[603]	validation-rmse:7.13188
[604]	validation-rmse:7.13117
[605]	validation-rmse:7.13111
[606]	validation-rmse:7.13100
[607]	validation-rmse:7.13113
[608]	validation-rmse:7.13111
[609]	validation-rmse:7.13028
[610]	validation-rmse:7.12992
[611]	validation-rmse:7.12893
[612]	validation-rmse:7.12853
[613]	validation-rmse:7.12828
[614]	validation-rmse:7.12877
[615]	validation-rmse:7.12843
[616]	validation-rmse:7.12815
[617]	validation-rmse:7.12820
[618]	validation-rmse:7.12754
[619]	validation-rmse:7.12677
[620]	validation-rmse:7.12655
[621]	validation-rmse:7.12592
[622]	validation-rmse:7.12597
[623]	validation-rmse:7.12558
[624]	validation-rmse:7.12510
[625]	validation-rmse:7.12534
[626]	validation-rmse:7.12508
[627]	validation-rmse:7.12477
[628]	validation-rmse:7.12394
[629]	validation-rmse:7.12412
[630]	validation-rmse:7.12386
[631]	validation-rmse:7.12345
[632]	validation-rmse:7.12355
[633]	validation-rmse:7.12306
[634]	validation-rmse:7.12284
[635]	validation-rmse:7.12269
[636]	validation-rmse:7.12201
[637]	validation-rmse:7.12197
[638]	validation-rmse:7.12088
[639]	validation-rmse:7.12008
[640]	validation-rmse:7.11937
[641]	validation-rmse:7.11871
[642]	validation-rmse:7.11934
[643]	validation-rmse:7.11939
[644]	validation-rmse:7.11931
[645]	validation-rmse:7.11924
[646]	validation-rmse:7.11860
[647]	validation-rmse:7.11859
[648]	validation-rmse:7.11835
[649]	validation-rmse:7.11668
[650]	validation-rmse:7.11605
[651]	validation-rmse:7.11609
[652]	validation-rmse:7.11652
[653]	validation-rmse:7.11642
[654]	validation-rmse:7.11645
[655]	validation-rmse:7.11527
[656]	validation-rmse:7.11520
[657]	validation-rmse:7.11516
[658]	validation-rmse:7.11519
[659]	validation-rmse:7.11487
[660]	validation-rmse:7.11440
[661]	validation-rmse:7.11470
[662]	validation-rmse:7.11479
[663]	validation-rmse:7.11494
[664]	validation-rmse:7.11453
[665]	validation-rmse:7.11460
[666]	validation-rmse:7.11434
[667]	validation-rmse:7.11343
[668]	validation-rmse:7.11297
[669]	validation-rmse:7.11216
[670]	validation-rmse:7.11210

[13:25:45] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:10.67846
[2]	validation-rmse:9.38477
[3]	validation-rmse:8.72600
[4]	validation-rmse:8.41332
[5]	validation-rmse:8.15719
[6]	validation-rmse:8.03015
[7]	validation-rmse:7.91389
[8]	validation-rmse:7.86383
[9]	validation-rmse:7.72256
[10]	validation-rmse:7.64385
[11]	validation-rmse:7.61515
[12]	validation-rmse:7.59222
[13]	validation-rmse:7.58390
[14]	validation-rmse:7.55281
[15]	validation-rmse:7.54667
[16]	validation-rmse:7.53215
[17]	validation-rmse:7.51444
[18]	validation-rmse:7.50921
[19]	validation-rmse:7.50838
[20]	validation-rmse:7.50610
[21]	validation-rmse:7.50209
[22]	validation-rmse:7.49976
[23]	validation-rmse:7.49727
[24]	validation-rmse:7.49506
[25]	validation-rmse:7.49135
[26]	validation-rmse:7.49013
[27]	validation-rmse:7.48979
[28]	validation-rmse:7.49011
[29]	validation-rmse:7.48799
[30]	validation-rmse:7.48548
[31]	validation-rmse:7.48480
[32]	validation-rmse:7.48072
[33]	validation-rmse:7.47834
[34]	validation-rmse:7.47828
[35]	validation-rmse:7.47562
[36]	validation-rmse:7.47444
[37]	validation-rmse:7.47207
[38]	validation-rmse:7.47183
[39]	validation-rmse:7.46921
[40]	validation-rmse:7.46829
[41]	validation-rmse:7.46647
[42]	validation-rmse:7.46585
[43]	validation-rmse:7.46466
[44]	validation-rmse:7.46128
[45]	validation-rmse:7.46021
[46]	validation-rmse:7.45940
[47]	validation-rmse:7.45612
[48]	validation-rmse:7.45482
[49]	validation-rmse:7.45323
[50]	validation-rmse:7.45073
[51]	validation-rmse:7.44964
[52]	validation-rmse:7.44878
[53]	validation-rmse:7.44701
[54]	validation-rmse:7.44648
[55]	validation-rmse:7.44576
[56]	validation-rmse:7.44529
[57]	validation-rmse:7.44382
[58]	validation-rmse:7.44251
[59]	validation-rmse:7.44392
[60]	validation-rmse:7.44245
[61]	validation-rmse:7.43991
[62]	validation-rmse:7.43800
[63]	validation-rmse:7.43657
[64]	validation-rmse:7.43809
[65]	validation-rmse:7.43539
[66]	validation-rmse:7.43463
[67]	validation-rmse:7.43331
[68]	validation-rmse:7.43263
[69]	validation-rmse:7.43214
[70]	validation-rmse:7.43063
[71]	validation-rmse:7.43162
[72]	validation-rmse:7.43023
[73]	validation-rmse:7.42954
[74]	validation-rmse:7.42853
[75]	validation-rmse:7.42615
[76]	validation-rmse:7.42555
[77]	validation-rmse:7.42352
[78]	validation-rmse:7.42406
[79]	validation-rmse:7.42213
[80]	validation-rmse:7.42234
[81]	validation-rmse:7.42007
[82]	validation-rmse:7.41951
[83]	validation-rmse:7.41771
[84]	validation-rmse:7.41814
[85]	validation-rmse:7.41603
[86]	validation-rmse:7.41528
[87]	validation-rmse:7.41295
[88]	validation-rmse:7.41106
[89]	validation-rmse:7.40933
[90]	validation-rmse:7.40973
[91]	validation-rmse:7.40774
[92]	validation-rmse:7.40704
[93]	validation-rmse:7.40670
[94]	validation-rmse:7.40506
[95]	validation-rmse:7.40523
[96]	validation-rmse:7.40493
[97]	validation-rmse:7.40403
[98]	validation-rmse:7.40258
[99]	validation-rmse:7.40042
[100]	validation-rmse:7.39984
[101]	validation-rmse:7.39969
[102]	validation-rmse:7.39756
[103]	validation-rmse:7.39722
[104]	validation-rmse:7.39684
[105]	validation-rmse:7.39602
[106]	validation-rmse:7.39483
[107]	validation-rmse:7.39497
[108]	validation-rmse:7.39419
[109]	validation-rmse:7.39205
[110]	validation-rmse:7.39160
[111]	validation-rmse:7.39190
[112]	validation-rmse:7.39130
[113]	validation-rmse:7.38974
[114]	validation-rmse:7.38993
[115]	validation-rmse:7.38950
[116]	validation-rmse:7.38963
[117]	validation-rmse:7.38939
[118]	validation-rmse:7.38764
[119]	validation-rmse:7.38598
[120]	validation-rmse:7.38554
[121]	validation-rmse:7.38257
[122]	validation-rmse:7.38144
[123]	validation-rmse:7.38141
[124]	validation-rmse:7.37909
[125]	validation-rmse:7.37861
[126]	validation-rmse:7.37981
[127]	validation-rmse:7.37843
[128]	validation-rmse:7.37669
[129]	validation-rmse:7.37639
[130]	validation-rmse:7.37598
[131]	validation-rmse:7.37395
[132]	validation-rmse:7.37179
[133]	validation-rmse:7.37236
[134]	validation-rmse:7.37143
[135]	validation-rmse:7.37035
[136]	validation-rmse:7.36886
[137]	validation-rmse:7.36969
[138]	validation-rmse:7.36841
[139]	validation-rmse:7.36743
[140]	validation-rmse:7.36699
[141]	validation-rmse:7.36599
[142]	validation-rmse:7.36429
[143]	validation-rmse:7.36475
[144]	validation-rmse:7.36413
[145]	validation-rmse:7.36181
[146]	validation-rmse:7.36106
[147]	validation-rmse:7.35992
[148]	validation-rmse:7.35934
[149]	validation-rmse:7.35893
[150]	validation-rmse:7.35840
[151]	validation-rmse:7.35562
[152]	validation-rmse:7.35486
[153]	validation-rmse:7.35302
[154]	validation-rmse:7.35216
[155]	validation-rmse:7.35273
[156]	validation-rmse:7.35204
[157]	validation-rmse:7.35050
[158]	validation-rmse:7.34868
[159]	validation-rmse:7.34877
[160]	validation-rmse:7.34714
[161]	validation-rmse:7.34715
[162]	validation-rmse:7.34652
[163]	validation-rmse:7.34584
[164]	validation-rmse:7.34382
[165]	validation-rmse:7.34301
[166]	validation-rmse:7.34175
[167]	validation-rmse:7.34124
[168]	validation-rmse:7.33852
[169]	validation-rmse:7.33783
[170]	validation-rmse:7.33713
[171]	validation-rmse:7.33726
[172]	validation-rmse:7.33799
[173]	validation-rmse:7.33866
[174]	validation-rmse:7.33779
[175]	validation-rmse:7.33702
[176]	validation-rmse:7.33660
[177]	validation-rmse:7.33567
[178]	validation-rmse:7.33410
[179]	validation-rmse:7.33320
[180]	validation-rmse:7.33291
[181]	validation-rmse:7.33295
[182]	validation-rmse:7.33297
[183]	validation-rmse:7.33252
[184]	validation-rmse:7.33200
[185]	validation-rmse:7.33218
[186]	validation-rmse:7.33150
[187]	validation-rmse:7.33052
[188]	validation-rmse:7.32924
[189]	validation-rmse:7.32872
[190]	validation-rmse:7.32846
[191]	validation-rmse:7.32992
[192]	validation-rmse:7.32904
[193]	validation-rmse:7.32931
[194]	validation-rmse:7.32741
[195]	validation-rmse:7.32717
[196]	validation-rmse:7.32721
[197]	validation-rmse:7.32713
[198]	validation-rmse:7.32606
[199]	validation-rmse:7.32698
[200]	validation-rmse:7.32529
[201]	validation-rmse:7.32397
[202]	validation-rmse:7.32193
[203]	validation-rmse:7.32172
[204]	validation-rmse:7.32126
[205]	validation-rmse:7.32196
[206]	validation-rmse:7.32048
[207]	validation-rmse:7.31983
[208]	validation-rmse:7.31953
[209]	validation-rmse:7.31806
[210]	validation-rmse:7.31729
[211]	validation-rmse:7.31698
[212]	validation-rmse:7.31682
[213]	validation-rmse:7.31652
[214]	validation-rmse:7.31582
[215]	validation-rmse:7.31530
[216]	validation-rmse:7.31532
[217]	validation-rmse:7.31400
[218]	validation-rmse:7.31175
[219]	validation-rmse:7.31142
[220]	validation-rmse:7.30959
[221]	validation-rmse:7.30987
[222]	validation-rmse:7.30984
[223]	validation-rmse:7.30928
[224]	validation-rmse:7.30680
[225]	validation-rmse:7.30577
[226]	validation-rmse:7.30495
[227]	validation-rmse:7.30395
[228]	validation-rmse:7.30234
[229]	validation-rmse:7.30184
[230]	validation-rmse:7.30066
[231]	validation-rmse:7.30047
[232]	validation-rmse:7.30135
[233]	validation-rmse:7.30093
[234]	validation-rmse:7.30013
[235]	validation-rmse:7.29889
[236]	validation-rmse:7.29742
[237]	validation-rmse:7.29709
[238]	validation-rmse:7.29567
[239]	validation-rmse:7.29609
[240]	validation-rmse:7.29595
[241]	validation-rmse:7.29409
[242]	validation-rmse:7.29333
[243]	validation-rmse:7.29272
[244]	validation-rmse:7.29358
[245]	validation-rmse:7.29462
[246]	validation-rmse:7.29335
[247]	validation-rmse:7.29261
[248]	validation-rmse:7.29405
[249]	validation-rmse:7.29355
[250]	validation-rmse:7.29253
[251]	validation-rmse:7.29211
[252]	validation-rmse:7.29164
[253]	validation-rmse:7.29150
[254]	validation-rmse:7.28903
[255]	validation-rmse:7.28836
[256]	validation-rmse:7.28590
[257]	validation-rmse:7.28529
[258]	validation-rmse:7.28363
[259]	validation-rmse:7.28517
[260]	validation-rmse:7.28434
[261]	validation-rmse:7.28428
[262]	validation-rmse:7.28362
[263]	validation-rmse:7.28399
[264]	validation-rmse:7.28321
[265]	validation-rmse:7.28336
[266]	validation-rmse:7.28244
[267]	validation-rmse:7.28168
[268]	validation-rmse:7.28251
[269]	validation-rmse:7.28131
[270]	validation-rmse:7.28163
[271]	validation-rmse:7.28136
[272]	validation-rmse:7.28078
[273]	validation-rmse:7.28015
[274]	validation-rmse:7.27895
[275]	validation-rmse:7.27922
[276]	validation-rmse:7.27849
[277]	validation-rmse:7.27927
[278]	validation-rmse:7.27897
[279]	validation-rmse:7.27806
[280]	validation-rmse:7.27808
[281]	validation-rmse:7.27720
[282]	validation-rmse:7.27794
[283]	validation-rmse:7.27612
[284]	validation-rmse:7.27551
[285]	validation-rmse:7.27462
[286]	validation-rmse:7.27383
[287]	validation-rmse:7.27288
[288]	validation-rmse:7.27302
[289]	validation-rmse:7.27201
[290]	validation-rmse:7.27241
[291]	validation-rmse:7.27187
[292]	validation-rmse:7.27114
[293]	validation-rmse:7.27122
[294]	validation-rmse:7.27034
[295]	validation-rmse:7.26965
[296]	validation-rmse:7.26979
[297]	validation-rmse:7.26917
[298]	validation-rmse:7.26981
[299]	validation-rmse:7.26995
[300]	validation-rmse:7.26900
[301]	validation-rmse:7.26836
[302]	validation-rmse:7.26675
[303]	validation-rmse:7.26651
[304]	validation-rmse:7.26471
[305]	validation-rmse:7.26504
[306]	validation-rmse:7.26424
[307]	validation-rmse:7.26360
[308]	validation-rmse:7.26301
[309]	validation-rmse:7.26315
[310]	validation-rmse:7.26283
[311]	validation-rmse:7.26319
[312]	validation-rmse:7.26217
[313]	validation-rmse:7.26243
[314]	validation-rmse:7.26273
[315]	validation-rmse:7.26338
[316]	validation-rmse:7.26216
[317]	validation-rmse:7.26216
[318]	validation-rmse:7.26292
[319]	validation-rmse:7.26191
[320]	validation-rmse:7.26227
[321]	validation-rmse:7.26171
[322]	validation-rmse:7.26130
[323]	validation-rmse:7.26086
[324]	validation-rmse:7.26010
[325]	validation-rmse:7.25945
[326]	validation-rmse:7.25889
[327]	validation-rmse:7.25844
[328]	validation-rmse:7.25877
[329]	validation-rmse:7.25951
[330]	validation-rmse:7.25961
[331]	validation-rmse:7.25853
[332]	validation-rmse:7.25892
[333]	validation-rmse:7.25780
[334]	validation-rmse:7.25765
[335]	validation-rmse:7.25616
[336]	validation-rmse:7.25519
[337]	validation-rmse:7.25540
[338]	validation-rmse:7.25484
[339]	validation-rmse:7.25492
[340]	validation-rmse:7.25457
[341]	validation-rmse:7.25364
[342]	validation-rmse:7.25363
[343]	validation-rmse:7.25380
[344]	validation-rmse:7.25363
[345]	validation-rmse:7.25295
[346]	validation-rmse:7.25213
[347]	validation-rmse:7.25191
[348]	validation-rmse:7.25276
[349]	validation-rmse:7.25250
[350]	validation-rmse:7.25234
[351]	validation-rmse:7.25121
[352]	validation-rmse:7.25048
[353]	validation-rmse:7.24946
[354]	validation-rmse:7.24830
[355]	validation-rmse:7.24728
[356]	validation-rmse:7.24701
[357]	validation-rmse:7.24838
[358]	validation-rmse:7.24787
[359]	validation-rmse:7.24851
[360]	validation-rmse:7.24811
[361]	validation-rmse:7.24826
[362]	validation-rmse:7.24773
[363]	validation-rmse:7.24828
[364]	validation-rmse:7.24849
[365]	validation-rmse:7.24741
[366]	validation-rmse:7.24629
[367]	validation-rmse:7.24669
[368]	validation-rmse:7.24585
[369]	validation-rmse:7.24544
[370]	validation-rmse:7.24523
[371]	validation-rmse:7.24486
[372]	validation-rmse:7.24501
[373]	validation-rmse:7.24570
[374]	validation-rmse:7.24427
[375]	validation-rmse:7.24407
[376]	validation-rmse:7.24357
[377]	validation-rmse:7.24368
[378]	validation-rmse:7.24355
[379]	validation-rmse:7.24281
[380]	validation-rmse:7.24264
[381]	validation-rmse:7.24233
[382]	validation-rmse:7.24172
[383]	validation-rmse:7.24116
[384]	validation-rmse:7.24045
[385]	validation-rmse:7.23982
[386]	validation-rmse:7.24056
[387]	validation-rmse:7.23963
[388]	validation-rmse:7.23858
[389]	validation-rmse:7.23846
[390]	validation-rmse:7.23800
[391]	validation-rmse:7.23845
[392]	validation-rmse:7.23779
[393]	validation-rmse:7.23761
[394]	validation-rmse:7.23730
[395]	validation-rmse:7.23683
[396]	validation-rmse:7.23629
[397]	validation-rmse:7.23605
[398]	validation-rmse:7.23544
[399]	validation-rmse:7.23515
[400]	validation-rmse:7.23437
[401]	validation-rmse:7.23412
[402]	validation-rmse:7.23411
[403]	validation-rmse:7.23386
[404]	validation-rmse:7.23286
[405]	validation-rmse:7.23115
[406]	validation-rmse:7.23078
[407]	validation-rmse:7.23098
[408]	validation-rmse:7.23074
[409]	validation-rmse:7.23090
[410]	validation-rmse:7.22999
[411]	validation-rmse:7.22995
[412]	validation-rmse:7.23002
[413]	validation-rmse:7.23001
[414]	validation-rmse:7.22903
[415]	validation-rmse:7.22854
[416]	validation-rmse:7.22942
[417]	validation-rmse:7.22973
[418]	validation-rmse:7.22837
[419]	validation-rmse:7.22806
[420]	validation-rmse:7.22815
[421]	validation-rmse:7.22808
[422]	validation-rmse:7.22782
[423]	validation-rmse:7.22792
[424]	validation-rmse:7.22792
[425]	validation-rmse:7.22698
[426]	validation-rmse:7.22634
[427]	validation-rmse:7.22582
[428]	validation-rmse:7.22516
[429]	validation-rmse:7.22491
[430]	validation-rmse:7.22447
[431]	validation-rmse:7.22375
[432]	validation-rmse:7.22374
[433]	validation-rmse:7.22425
[434]	validation-rmse:7.22394
[435]	validation-rmse:7.22322
[436]	validation-rmse:7.22358
[437]	validation-rmse:7.22297
[438]	validation-rmse:7.22399
[439]	validation-rmse:7.22331
[440]	validation-rmse:7.22321
[441]	validation-rmse:7.22258
[442]	validation-rmse:7.22226
[443]	validation-rmse:7.22248
[444]	validation-rmse:7.22194
[445]	validation-rmse:7.22246
[446]	validation-rmse:7.22226
[447]	validation-rmse:7.21949
[448]	validation-rmse:7.21865
[449]	validation-rmse:7.21901
[450]	validation-rmse:7.21890
[451]	validation-rmse:7.21801
[452]	validation-rmse:7.21930
[453]	validation-rmse:7.21943
[454]	validation-rmse:7.21923
[455]	validation-rmse:7.21883
[456]	validation-rmse:7.21796
[457]	validation-rmse:7.21736
[458]	validation-rmse:7.21747
[459]	validation-rmse:7.21769
[460]	validation-rmse:7.21742
[461]	validation-rmse:7.21790
[462]	validation-rmse:7.21787
[463]	validation-rmse:7.21770
[464]	validation-rmse:7.21622
[465]	validation-rmse:7.21640
[466]	validation-rmse:7.21642
[467]	validation-rmse:7.21679
[468]	validation-rmse:7.21555
[469]	validation-rmse:7.21515
[470]	validation-rmse:7.21562
[471]	validation-rmse:7.21530
[472]	validation-rmse:7.21381
[473]	validation-rmse:7.21370
[474]	validation-rmse:7.21302
[475]	validation-rmse:7.21309
[476]	validation-rmse:7.21258
[477]	validation-rmse:7.21169
[478]	validation-rmse:7.21249
[479]	validation-rmse:7.21165
[480]	validation-rmse:7.21107
[481]	validation-rmse:7.21058
[482]	validation-rmse:7.21039
[483]	validation-rmse:7.20937
[484]	validation-rmse:7.20960
[485]	validation-rmse:7.20967
[486]	validation-rmse:7.21054
[487]	validation-rmse:7.21001
[488]	validation-rmse:7.20922
[489]	validation-rmse:7.20944
[490]	validation-rmse:7.20959
[491]	validation-rmse:7.20992
[492]	validation-rmse:7.20852
[493]	validation-rmse:7.20807
[494]	validation-rmse:7.20731
[495]	validation-rmse:7.20842
[496]	validation-rmse:7.20816
[497]	validation-rmse:7.20842
[498]	validation-rmse:7.20801
[499]	validation-rmse:7.20716
[500]	validation-rmse:7.20733
[501]	validation-rmse:7.20706
[502]	validation-rmse:7.20672
[503]	validation-rmse:7.20756
[504]	validation-rmse:7.20776
[505]	validation-rmse:7.20820
[506]	validation-rmse:7.20827
[507]	validation-rmse:7.20818
[508]	validation-rmse:7.20846
[509]	validation-rmse:7.20801
[510]	validation-rmse:7.20829
[511]	validation-rmse:7.20790
[512]	validation-rmse:7.20816
[513]	validation-rmse:7.20827
[514]	validation-rmse:7.20744
[515]	validation-rmse:7.20635
[516]	validation-rmse:7.20524
[517]	validation-rmse:7.20560
[518]	validation-rmse:7.20522
[519]	validation-rmse:7.20519
[520]	validation-rmse:7.20636
[521]	validation-rmse:7.20652
[522]	validation-rmse:7.20637
[523]	validation-rmse:7.20657
[524]	validation-rmse:7.20518
[525]	validation-rmse:7.20458
[526]	validation-rmse:7.20405
[527]	validation-rmse:7.20294
[528]	validation-rmse:7.20285
[529]	validation-rmse:7.20339
[530]	validation-rmse:7.20234
[531]	validation-rmse:7.20214
[532]	validation-rmse:7.20221
[533]	validation-rmse:7.20195
[534]	validation-rmse:7.20285
[535]	validation-rmse:7.20203
[536]	validation-rmse:7.20161
[537]	validation-rmse:7.20121
[538]	validation-rmse:7.20076
[539]	validation-rmse:7.20045
[540]	validation-rmse:7.20081
[541]	validation-rmse:7.20089
[542]	validation-rmse:7.20103
[543]	validation-rmse:7.19990
[544]	validation-rmse:7.19967
[545]	validation-rmse:7.20052
[546]	validation-rmse:7.20062
[547]	validation-rmse:7.19928
[548]	validation-rmse:7.19841
[549]	validation-rmse:7.19837
[550]	validation-rmse:7.19782
[551]	validation-rmse:7.19794
[552]	validation-rmse:7.19763
[553]	validation-rmse:7.19774
[554]	validation-rmse:7.19701
[555]	validation-rmse:7.19769
[556]	validation-rmse:7.19766
[557]	validation-rmse:7.19687
[558]	validation-rmse:7.19617
[559]	validation-rmse:7.19574
[560]	validation-rmse:7.19572
[561]	validation-rmse:7.19517
[562]	validation-rmse:7.19542
[563]	validation-rmse:7.19602
[564]	validation-rmse:7.19623
[565]	validation-rmse:7.19546
[566]	validation-rmse:7.19581
[567]	validation-rmse:7.19557
[568]	validation-rmse:7.19573
[569]	validation-rmse:7.19515
[570]	validation-rmse:7.19527
[571]	validation-rmse:7.19524
[572]	validation-rmse:7.19493
[573]	validation-rmse:7.19488
[574]	validation-rmse:7.19514
[575]	validation-rmse:7.19517
[576]	validation-rmse:7.19493
[577]	validation-rmse:7.19437
[578]	validation-rmse:7.19501
[579]	validation-rmse:7.19555
[580]	validation-rmse:7.19471
[581]	validation-rmse:7.19514
[582]	validation-rmse:7.19487
[583]	validation-rmse:7.19543
[584]	validation-rmse:7.19455
[585]	validation-rmse:7.19429
[586]	validation-rmse:7.19458
[587]	validation-rmse:7.19414
[588]	validation-rmse:7.19404
[589]	validation-rmse:7.19365
[590]	validation-rmse:7.19245
[591]	validation-rmse:7.19242
[592]	validation-rmse:7.19278
[593]	validation-rmse:7.19242
[594]	validation-rmse:7.19250
[595]	validation-rmse:7.19258
[596]	validation-rmse:7.19262
[597]	validation-rmse:7.19182
[598]	validation-rmse:7.19238
[599]	validation-rmse:7.19200
[600]	validation-rmse:7.19098
[601]	validation-rmse:7.19032
[602]	validation-rmse:7.19061
[603]	validation-rmse:7.19013
[604]	validation-rmse:7.18996
[605]	validation-rmse:7.19057
[606]	validation-rmse:7.18982
[607]	validation-rmse:7.18979
[608]	validation-rmse:7.18902
[609]	validation-rmse:7.18961
[610]	validation-rmse:7.18877
[611]	validation-rmse:7.18830
[612]	validation-rmse:7.18899
[613]	validation-rmse:7.18902
[614]	validation-rmse:7.18894
[615]	validation-rmse:7.18859
[616]	validation-rmse:7.18895
[617]	validation-rmse:7.18885
[618]	validation-rmse:7.18918
[619]	validation-rmse:7.18814
[620]	validation-rmse:7.18789
[621]	validation-rmse:7.18716
[622]	validation-rmse:7.18756
[623]	validation-rmse:7.18737
[624]	validation-rmse:7.18725
[625]	validation-rmse:7.18773
[626]	validation-rmse:7.18821
[627]	validation-rmse:7.18818
[628]	validation-rmse:7.18702
[629]	validation-rmse:7.18680
[630]	validation-rmse:7.18635
[631]	validation-rmse:7.18541
[632]	validation-rmse:7.18635
[633]	validation-rmse:7.18559
[634]	validation-rmse:7.18490
[635]	validation-rmse:7.18507
[636]	validation-rmse:7.18447
[637]	validation-rmse:7.18465
[638]	validation-rmse:7.18416
[639]	validation-rmse:7.18360
[640]	validation-rmse:7.18352
[641]	validation-rmse:7.18286
[642]	validation-rmse:7.18293
[643]	validation-rmse:7.18292
[644]	validation-rmse:7.18299
[645]	validation-rmse:7.18298
[646]	validation-rmse:7.18306
[647]	validation-rmse:7.18309
[648]	validation-rmse:7.18380
[649]	validation-rmse:7.18425
[650]	validation-rmse:7.18435
[651]	validation-rmse:7.18323
[652]	validation-rmse:7.18366
[653]	validation-rmse:7.18291
[654]	validation-rmse:7.18232
[655]	validation-rmse:7.18291
[656]	validation-rmse:7.18286
[657]	validation-rmse:7.18268
[658]	validation-rmse:7.18250
[659]	validation-rmse:7.18275
[660]	validation-rmse:7.18179
[661]	validation-rmse:7.18157
[662]	validation-rmse:7.18172
[663]	validation-rmse:7.18193
[664]	validation-rmse:7.18242
[665]	validation-rmse:7.18141
[666]	validation-rmse:7.18181
[667]	validation-rmse:7.18171
[668]	validation-rmse:7.18230
[669]	validation-rmse:7.18157
[670]	validation-rmse:7.18145

[13:32:16] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[0]	validation-rmse:16.50244
[1]	validation-rmse:13.48708
[2]	validation-rmse:11.61338
[3]	validation-rmse:10.55482
[4]	validation-rmse:9.92460
[5]	validation-rmse:9.33907
[6]	validation-rmse:9.05697
[7]	validation-rmse:8.87894
[8]	validation-rmse:8.66211
[9]	validation-rmse:8.55851
[10]	validation-rmse:8.48647
[11]	validation-rmse:8.41973
[12]	validation-rmse:8.32801
[13]	validation-rmse:8.26656
[14]	validation-rmse:8.23754
[15]	validation-rmse:8.20115
[16]	validation-rmse:8.17783
[17]	validation-rmse:8.15577
[18]	validation-rmse:8.13704
[19]	validation-rmse:8.11939
[20]	validation-rmse:8.07354
[21]	validation-rmse:8.04479
[22]	validation-rmse:8.02977
[23]	validation-rmse:8.01949
[24]	validation-rmse:7.99565
[25]	validation-rmse:7.98651
[26]	validation-rmse:7.96304
[27]	validation-rmse:7.95412
[28]	validation-rmse:7.94806
[29]	validation-rmse:7.94036
[30]	validation-rmse:7.93499
[31]	validation-rmse:7.92969
[32]	validation-rmse:7.92511
[33]	validation-rmse:7.91912
[34]	validation-rmse:7.91193
[35]	validation-rmse:7.90756
[36]	validation-rmse:7.90333
[37]	validation-rmse:7.89323
[38]	validation-rmse:7.89186
[39]	validation-rmse:7.88708
[40]	validation-rmse:7.88315
[41]	validation-rmse:7.87907
[42]	validation-rmse:7.87673
[43]	validation-rmse:7.87300
[44]	validation-rmse:7.87024
[45]	validation-rmse:7.86539
[46]	validation-rmse:7.86191
[47]	validation-rmse:7.85820
[48]	validation-rmse:7.85502
[49]	validation-rmse:7.85110
[50]	validation-rmse:7.84824
[51]	validation-rmse:7.84491
[52]	validation-rmse:7.84217
[53]	validation-rmse:7.83996
[54]	validation-rmse:7.83861
[55]	validation-rmse:7.83310
[56]	validation-rmse:7.82983
[57]	validation-rmse:7.82561
[58]	validation-rmse:7.82414
[59]	validation-rmse:7.82285
[60]	validation-rmse:7.81943
[61]	validation-rmse:7.81689
[62]	validation-rmse:7.81311
[63]	validation-rmse:7.81086
[64]	validation-rmse:7.80896
[65]	validation-rmse:7.80738
[66]	validation-rmse:7.80505
[67]	validation-rmse:7.80366
[68]	validation-rmse:7.80225
[69]	validation-rmse:7.79996
[70]	validation-rmse:7.79669
[71]	validation-rmse:7.79665
[72]	validation-rmse:7.79460
[73]	validation-rmse:7.79123
[74]	validation-rmse:7.78824
[75]	validation-rmse:7.78593
[76]	validation-rmse:7.78449
[77]	validation-rmse:7.78277
[78]	validation-rmse:7.78077
[79]	validation-rmse:7.77958
[80]	validation-rmse:7.77743
[81]	validation-rmse:7.77401
[82]	validation-rmse:7.77190
[83]	validation-rmse:7.77029
[84]	validation-rmse:7.77038
[85]	validation-rmse:7.76574
[86]	validation-rmse:7.76293
[87]	validation-rmse:7.76021
[88]	validation-rmse:7.75983
[89]	validation-rmse:7.75822
[90]	validation-rmse:7.75632
[91]	validation-rmse:7.75441
[92]	validation-rmse:7.75227
[93]	validation-rmse:7.75054
[94]	validation-rmse:7.74798
[95]	validation-rmse:7.74550
[96]	validation-rmse:7.74482
[97]	validation-rmse:7.74409
[98]	validation-rmse:7.74253
[99]	validation-rmse:7.73846
[100]	validation-rmse:7.73637
[101]	validation-rmse:7.73448
[102]	validation-rmse:7.73207
[103]	validation-rmse:7.72956
[104]	validation-rmse:7.72779
[105]	validation-rmse:7.72704
[106]	validation-rmse:7.72505
[107]	validation-rmse:7.72425
[108]	validation-rmse:7.72175
[109]	validation-rmse:7.71989
[110]	validation-rmse:7.71806
[111]	validation-rmse:7.71578
[112]	validation-rmse:7.71440
[113]	validation-rmse:7.71292
[114]	validation-rmse:7.71127
[115]	validation-rmse:7.70988
[116]	validation-rmse:7.70787
[117]	validation-rmse:7.70670
[118]	validation-rmse:7.70511
[119]	validation-rmse:7.70359
[120]	validation-rmse:7.70159
[121]	validation-rmse:7.69943
[122]	validation-rmse:7.69727
[123]	validation-rmse:7.69613
[124]	validation-rmse:7.69467
[125]	validation-rmse:7.69308
[126]	validation-rmse:7.69115
[127]	validation-rmse:7.68924
[128]	validation-rmse:7.68809
[129]	validation-rmse:7.68644
[130]	validation-rmse:7.68474
[131]	validation-rmse:7.68414
[132]	validation-rmse:7.68275
[133]	validation-rmse:7.68151
[134]	validation-rmse:7.67928
[135]	validation-rmse:7.67784
[136]	validation-rmse:7.67577
[137]	validation-rmse:7.67457
[138]	validation-rmse:7.67397
[139]	validation-rmse:7.67262
[140]	validation-rmse:7.67112
[141]	validation-rmse:7.67013
[142]	validation-rmse:7.66890
[143]	validation-rmse:7.66740
[144]	validation-rmse:7.66421
[145]	validation-rmse:7.66175
[146]	validation-rmse:7.66069
[147]	validation-rmse:7.65757
[148]	validation-rmse:7.65569
[149]	validation-rmse:7.65483
[150]	validation-rmse:7.65386
[151]	validation-rmse:7.65343
[152]	validation-rmse:7.65295
[153]	validation-rmse:7.65256
[154]	validation-rmse:7.65222
[155]	validation-rmse:7.65141
[156]	validation-rmse:7.65183
[157]	validation-rmse:7.65005
[158]	validation-rmse:7.64874
[159]	validation-rmse:7.64810
[160]	validation-rmse:7.64694
[161]	validation-rmse:7.64574
[162]	validation-rmse:7.64215
[163]	validation-rmse:7.64125
[164]	validation-rmse:7.64031
[165]	validation-rmse:7.63995
[166]	validation-rmse:7.63852
[167]	validation-rmse:7.63855
[168]	validation-rmse:7.63770
[169]	validation-rmse:7.63626
[170]	validation-rmse:7.63543
[171]	validation-rmse:7.63439
[172]	validation-rmse:7.63334
[173]	validation-rmse:7.63250
[174]	validation-rmse:7.63126
[175]	validation-rmse:7.63063
[176]	validation-rmse:7.62999
[177]	validation-rmse:7.62928
[178]	validation-rmse:7.62773
[179]	validation-rmse:7.62642
[180]	validation-rmse:7.62587
[181]	validation-rmse:7.62527
[182]	validation-rmse:7.62400
[183]	validation-rmse:7.62423
[184]	validation-rmse:7.62252
[185]	validation-rmse:7.62197
[186]	validation-rmse:7.61962
[187]	validation-rmse:7.61828
[188]	validation-rmse:7.61822
[189]	validation-rmse:7.61633
[190]	validation-rmse:7.61555
[191]	validation-rmse:7.61344
[192]	validation-rmse:7.61277
[193]	validation-rmse:7.61256
[194]	validation-rmse:7.61160
[195]	validation-rmse:7.61130
[196]	validation-rmse:7.61011
[197]	validation-rmse:7.60987
[198]	validation-rmse:7.60780
[199]	validation-rmse:7.60692
[200]	validation-rmse:7.60551
[201]	validation-rmse:7.60443
[202]	validation-rmse:7.60367
[203]	validation-rmse:7.60310
[204]	validation-rmse:7.60134
[205]	validation-rmse:7.60040
[206]	validation-rmse:7.59953
[207]	validation-rmse:7.59832
[208]	validation-rmse:7.59770
[209]	validation-rmse:7.59693
[210]	validation-rmse:7.59625
[211]	validation-rmse:7.59580
[212]	validation-rmse:7.59512
[213]	validation-rmse:7.59281
[214]	validation-rmse:7.59173
[215]	validation-rmse:7.59005
[216]	validation-rmse:7.58869
[217]	validation-rmse:7.58554
[218]	validation-rmse:7.58419
[219]	validation-rmse:7.58231
[220]	validation-rmse:7.58192
[221]	validation-rmse:7.58114
[222]	validation-rmse:7.58096
[223]	validation-rmse:7.58015
[224]	validation-rmse:7.57746
[225]	validation-rmse:7.57777
[226]	validation-rmse:7.57746
[227]	validation-rmse:7.57665
[228]	validation-rmse:7.57573
[229]	validation-rmse:7.57436
[230]	validation-rmse:7.57282
[231]	validation-rmse:7.57192
[232]	validation-rmse:7.57107
[233]	validation-rmse:7.56883
[234]	validation-rmse:7.56795
[235]	validation-rmse:7.56758
[236]	validation-rmse:7.56717
[237]	validation-rmse:7.56728
[238]	validation-rmse:7.56647
[239]	validation-rmse:7.56475
[240]	validation-rmse:7.56387
[241]	validation-rmse:7.56263
[242]	validation-rmse:7.56091
[243]	validation-rmse:7.56093
[244]	validation-rmse:7.55998
[245]	validation-rmse:7.55924
[246]	validation-rmse:7.55758
[247]	validation-rmse:7.55635
[248]	validation-rmse:7.55509
[249]	validation-rmse:7.55376
[250]	validation-rmse:7.55356
[251]	validation-rmse:7.55292
[252]	validation-rmse:7.55282
[253]	validation-rmse:7.55142
[254]	validation-rmse:7.55058
[255]	validation-rmse:7.54995
[256]	validation-rmse:7.54945
[257]	validation-rmse:7.54927
[258]	validation-rmse:7.54791
[259]	validation-rmse:7.54579
[260]	validation-rmse:7.54502
[261]	validation-rmse:7.54357
[262]	validation-rmse:7.54267
[263]	validation-rmse:7.54348
[264]	validation-rmse:7.54215
[265]	validation-rmse:7.54078
[266]	validation-rmse:7.53985
[267]	validation-rmse:7.53895
[268]	validation-rmse:7.53889
[269]	validation-rmse:7.53715
[270]	validation-rmse:7.53583
[271]	validation-rmse:7.53514
[272]	validation-rmse:7.53567
[273]	validation-rmse:7.53390
[274]	validation-rmse:7.53354
[275]	validation-rmse:7.53226
[276]	validation-rmse:7.53016
[277]	validation-rmse:7.52993
[278]	validation-rmse:7.52861
[279]	validation-rmse:7.52722
[280]	validation-rmse:7.52760
[281]	validation-rmse:7.52611
[282]	validation-rmse:7.52532
[283]	validation-rmse:7.52467
[284]	validation-rmse:7.52247
[285]	validation-rmse:7.52124
[286]	validation-rmse:7.52106
[287]	validation-rmse:7.52047
[288]	validation-rmse:7.51895
[289]	validation-rmse:7.51775
[290]	validation-rmse:7.51709
[291]	validation-rmse:7.51661
[292]	validation-rmse:7.51597
[293]	validation-rmse:7.51551
[294]	validation-rmse:7.51472
[295]	validation-rmse:7.51372
[296]	validation-rmse:7.51276
[297]	validation-rmse:7.51080
[298]	validation-rmse:7.51030
[299]	validation-rmse:7.50884
[300]	validation-rmse:7.50854
[301]	validation-rmse:7.50740
[302]	validation-rmse:7.50656
[303]	validation-rmse:7.50434
[304]	validation-rmse:7.50431
[305]	validation-rmse:7.50374
[306]	validation-rmse:7.50352
[307]	validation-rmse:7.50256
[308]	validation-rmse:7.50182
[309]	validation-rmse:7.50044
[310]	validation-rmse:7.50017
[311]	validation-rmse:7.49955
[312]	validation-rmse:7.49896
[313]	validation-rmse:7.49870
[314]	validation-rmse:7.49857
[315]	validation-rmse:7.49797
[316]	validation-rmse:7.49682
[317]	validation-rmse:7.49683
[318]	validation-rmse:7.49655
[319]	validation-rmse:7.49539
[320]	validation-rmse:7.49506
[321]	validation-rmse:7.49512
[322]	validation-rmse:7.49435
[323]	validation-rmse:7.49416
[324]	validation-rmse:7.49444
[325]	validation-rmse:7.49393
[326]	validation-rmse:7.49280
[327]	validation-rmse:7.49210
[328]	validation-rmse:7.49213
[329]	validation-rmse:7.49092
[330]	validation-rmse:7.48909
[331]	validation-rmse:7.48844
[332]	validation-rmse:7.48728
[333]	validation-rmse:7.48700
[334]	validation-rmse:7.48608
[335]	validation-rmse:7.48483
[336]	validation-rmse:7.48400
[337]	validation-rmse:7.48283
[338]	validation-rmse:7.48271
[339]	validation-rmse:7.48029
[340]	validation-rmse:7.48001
[341]	validation-rmse:7.47811
[342]	validation-rmse:7.47774
[343]	validation-rmse:7.47660
[344]	validation-rmse:7.47552
[345]	validation-rmse:7.47427
[346]	validation-rmse:7.47369
[347]	validation-rmse:7.47379
[348]	validation-rmse:7.47250
[349]	validation-rmse:7.47189
[350]	validation-rmse:7.47138
[351]	validation-rmse:7.47134
[352]	validation-rmse:7.47028
[353]	validation-rmse:7.46976
[354]	validation-rmse:7.46906
[355]	validation-rmse:7.46841
[356]	validation-rmse:7.46728
[357]	validation-rmse:7.46748
[358]	validation-rmse:7.46643
[359]	validation-rmse:7.46605
[360]	validation-rmse:7.46580
[361]	validation-rmse:7.46537
[362]	validation-rmse:7.46557
[363]	validation-rmse:7.46510
[364]	validation-rmse:7.46417
[365]	validation-rmse:7.46325
[366]	validation-rmse:7.46236
[367]	validation-rmse:7.46194
[368]	validation-rmse:7.46130
[369]	validation-rmse:7.46139
[370]	validation-rmse:7.46140
[371]	validation-rmse:7.46085
[372]	validation-rmse:7.45998
[373]	validation-rmse:7.45999
[374]	validation-rmse:7.45853
[375]	validation-rmse:7.45814
[376]	validation-rmse:7.45707
[377]	validation-rmse:7.45661
[378]	validation-rmse:7.45528
[379]	validation-rmse:7.45404
[380]	validation-rmse:7.45424
[381]	validation-rmse:7.45318
[382]	validation-rmse:7.45327
[383]	validation-rmse:7.45265
[384]	validation-rmse:7.45231
[385]	validation-rmse:7.45235
[386]	validation-rmse:7.45155
[387]	validation-rmse:7.44951
[388]	validation-rmse:7.44911
[389]	validation-rmse:7.44850
[390]	validation-rmse:7.44842
[391]	validation-rmse:7.44772
[392]	validation-rmse:7.44822
[393]	validation-rmse:7.44759
[394]	validation-rmse:7.44652
[395]	validation-rmse:7.44611
[396]	validation-rmse:7.44513
[397]	validation-rmse:7.44499
[398]	validation-rmse:7.44454
[399]	validation-rmse:7.44416
[400]	validation-rmse:7.44329
[401]	validation-rmse:7.44163
[402]	validation-rmse:7.44087
[403]	validation-rmse:7.44013
[404]	validation-rmse:7.43888
[405]	validation-rmse:7.43700
[406]	validation-rmse:7.43668
[407]	validation-rmse:7.43606
[408]	validation-rmse:7.43593
[409]	validation-rmse:7.43558
[410]	validation-rmse:7.43495
[411]	validation-rmse:7.43457
[412]	validation-rmse:7.43366
[413]	validation-rmse:7.43335
[414]	validation-rmse:7.43297
[415]	validation-rmse:7.43244
[416]	validation-rmse:7.43153
[417]	validation-rmse:7.43182
[418]	validation-rmse:7.43048
[419]	validation-rmse:7.43008
[420]	validation-rmse:7.42912
[421]	validation-rmse:7.42856
[422]	validation-rmse:7.42788
[423]	validation-rmse:7.42588
[424]	validation-rmse:7.42610
[425]	validation-rmse:7.42508
[426]	validation-rmse:7.42531
[427]	validation-rmse:7.42390
[428]	validation-rmse:7.42345
[429]	validation-rmse:7.42341
[430]	validation-rmse:7.42298
[431]	validation-rmse:7.42328
[432]	validation-rmse:7.42228
[433]	validation-rmse:7.42198
[434]	validation-rmse:7.42206
[435]	validation-rmse:7.42079
[436]	validation-rmse:7.42015
[437]	validation-rmse:7.41954
[438]	validation-rmse:7.41874
[439]	validation-rmse:7.41835
[440]	validation-rmse:7.41762
[441]	validation-rmse:7.41773
[442]	validation-rmse:7.41691
[443]	validation-rmse:7.41702
[444]	validation-rmse:7.41691
[445]	validation-rmse:7.41485
[446]	validation-rmse:7.41451
[447]	validation-rmse:7.41366
[448]	validation-rmse:7.41312
[449]	validation-rmse:7.41273
[450]	validation-rmse:7.41204
[451]	validation-rmse:7.41220
[452]	validation-rmse:7.41171
[453]	validation-rmse:7.41089
[454]	validation-rmse:7.41022
[455]	validation-rmse:7.40935
[456]	validation-rmse:7.40849
[457]	validation-rmse:7.40794
[458]	validation-rmse:7.40754
[459]	validation-rmse:7.40742
[460]	validation-rmse:7.40759
[461]	validation-rmse:7.40713
[462]	validation-rmse:7.40603
[463]	validation-rmse:7.40545
[464]	validation-rmse:7.40452
[465]	validation-rmse:7.40365
[466]	validation-rmse:7.40317
[467]	validation-rmse:7.40277
[468]	validation-rmse:7.40313
[469]	validation-rmse:7.40172
[470]	validation-rmse:7.40139
[471]	validation-rmse:7.40094
[472]	validation-rmse:7.40004
[473]	validation-rmse:7.39920
[474]	validation-rmse:7.39878
[475]	validation-rmse:7.39852
[476]	validation-rmse:7.39790
[477]	validation-rmse:7.39745
[478]	validation-rmse:7.39728
[479]	validation-rmse:7.39730
[480]	validation-rmse:7.39704
[481]	validation-rmse:7.39610
[482]	validation-rmse:7.39590
[483]	validation-rmse:7.39582
[484]	validation-rmse:7.39567
[485]	validation-rmse:7.39558
[486]	validation-rmse:7.39491
[487]	validation-rmse:7.39531
[488]	validation-rmse:7.39474
[489]	validation-rmse:7.39399
[490]	validation-rmse:7.39327
[491]	validation-rmse:7.39291
[492]	validation-rmse:7.39257
[493]	validation-rmse:7.39212
[494]	validation-rmse:7.39136
[495]	validation-rmse:7.39116
[496]	validation-rmse:7.39015
[497]	validation-rmse:7.38985
[498]	validation-rmse:7.38937
[499]	validation-rmse:7.38853
[500]	validation-rmse:7.38841
[501]	validation-rmse:7.38837
[502]	validation-rmse:7.38766
[503]	validation-rmse:7.38714
[504]	validation-rmse:7.38692
[505]	validation-rmse:7.38658
[506]	validation-rmse:7.38660
[507]	validation-rmse:7.38619
[508]	validation-rmse:7.38522
[509]	validation-rmse:7.38446
[510]	validation-rmse:7.38408
[511]	validation-rmse:7.38340
[512]	validation-rmse:7.38284
[513]	validation-rmse:7.38222
[514]	validation-rmse:7.38241
[515]	validation-rmse:7.38146
[516]	validation-rmse:7.38074
[517]	validation-rmse:7.38006
[518]	validation-rmse:7.37957
[519]	validation-rmse:7.37956
[520]	validation-rmse:7.37915
[521]	validation-rmse:7.37876
[522]	validation-rmse:7.37863
[523]	validation-rmse:7.37873
[524]	validation-rmse:7.37806
[525]	validation-rmse:7.37829
[526]	validation-rmse:7.37714
[527]	validation-rmse:7.37653
[528]	validation-rmse:7.37615
[529]	validation-rmse:7.37549
[530]	validation-rmse:7.37485
[531]	validation-rmse:7.37425
[532]	validation-rmse:7.37457
[533]	validation-rmse:7.37367
[534]	validation-rmse:7.37342
[535]	validation-rmse:7.37317
[536]	validation-rmse:7.37277
[537]	validation-rmse:7.37214
[538]	validation-rmse:7.37216
[539]	validation-rmse:7.37160
[540]	validation-rmse:7.37107
[541]	validation-rmse:7.37071
[542]	validation-rmse:7.37040
[543]	validation-rmse:7.37019
[544]	validation-rmse:7.36933
[545]	validation-rmse:7.36869
[546]	validation-rmse:7.36874
[547]	validation-rmse:7.36797
[548]	validation-rmse:7.36780
[549]	validation-rmse:7.36748
[550]	validation-rmse:7.36723
[551]	validation-rmse:7.36686
[552]	validation-rmse:7.36633
[553]	validation-rmse:7.36559
[554]	validation-rmse:7.36487
[555]	validation-rmse:7.36449
[556]	validation-rmse:7.36434
[557]	validation-rmse:7.36441
[558]	validation-rmse:7.36430
[559]	validation-rmse:7.36262
[560]	validation-rmse:7.36202
[561]	validation-rmse:7.36206
[562]	validation-rmse:7.36139
[563]	validation-rmse:7.36116
[564]	validation-rmse:7.36075
[565]	validation-rmse:7.36021
[566]	validation-rmse:7.35975
[567]	validation-rmse:7.35965
[568]	validation-rmse:7.35892
[569]	validation-rmse:7.35895
[570]	validation-rmse:7.35878
[571]	validation-rmse:7.35833
[572]	validation-rmse:7.35830
[573]	validation-rmse:7.35805
[574]	validation-rmse:7.35768
[575]	validation-rmse:7.35724
[576]	validation-rmse:7.35693
[577]	validation-rmse:7.35628
[578]	validation-rmse:7.35639
[579]	validation-rmse:7.35626
[580]	validation-rmse:7.35561
[581]	validation-rmse:7.35481
[582]	validation-rmse:7.35401
[583]	validation-rmse:7.35365
[584]	validation-rmse:7.35269
[585]	validation-rmse:7.35277
[586]	validation-rmse:7.35237
[587]	validation-rmse:7.35209
[588]	validation-rmse:7.35169
[589]	validation-rmse:7.35093
[590]	validation-rmse:7.35032
[591]	validation-rmse:7.34927
[592]	validation-rmse:7.34871
[593]	validation-rmse:7.34832
[594]	validation-rmse:7.34791
[595]	validation-rmse:7.34821
[596]	validation-rmse:7.34825
[597]	validation-rmse:7.34815
[598]	validation-rmse:7.34778
[599]	validation-rmse:7.34681
[600]	validation-rmse:7.34651
[601]	validation-rmse:7.34564
[602]	validation-rmse:7.34540
[603]	validation-rmse:7.34550
[604]	validation-rmse:7.34502
[605]	validation-rmse:7.34439
[606]	validation-rmse:7.34349
[607]	validation-rmse:7.34343
[608]	validation-rmse:7.34244
[609]	validation-rmse:7.34244
[610]	validation-rmse:7.34194
[611]	validation-rmse:7.34129
[612]	validation-rmse:7.34040
[613]	validation-rmse:7.34047
[614]	validation-rmse:7.34017
[615]	validation-rmse:7.33975
[616]	validation-rmse:7.33967
[617]	validation-rmse:7.33924
[618]	validation-rmse:7.33895
[619]	validation-rmse:7.33836
[620]	validation-rmse:7.33779
[621]	validation-rmse:7.33717
[622]	validation-rmse:7.33749
[623]	validation-rmse:7.33663
[624]	validation-rmse:7.33588
[625]	validation-rmse:7.33575
[626]	validation-rmse:7.33503
[627]	validation-rmse:7.33436
[628]	validation-rmse:7.33429
[629]	validation-rmse:7.33441
[630]	validation-rmse:7.33362
[631]	validation-rmse:7.33290
[632]	validation-rmse:7.33212
[633]	validation-rmse:7.33120
[634]	validation-rmse:7.33142
[635]	validation-rmse:7.33106
[636]	validation-rmse:7.33064
[637]	validation-rmse:7.33032
[638]	validation-rmse:7.33056
[639]	validation-rmse:7.33028
[640]	validation-rmse:7.32883
[641]	validation-rmse:7.32834
[642]	validation-rmse:7.32775
[643]	validation-rmse:7.32741
[644]	validation-rmse:7.32604
[645]	validation-rmse:7.32577
[646]	validation-rmse:7.32533
[647]	validation-rmse:7.32560
[648]	validation-rmse:7.32579
[649]	validation-rmse:7.32516
[650]	validation-rmse:7.32477
[651]	validation-rmse:7.32403
[652]	validation-rmse:7.32307
[653]	validation-rmse:7.32255
[654]	validation-rmse:7.32208
[655]	validation-rmse:7.32236
[656]	validation-rmse:7.32183
[657]	validation-rmse:7.32085
[658]	validation-rmse:7.32036
[659]	validation-rmse:7.32003
[660]	validation-rmse:7.32026
[661]	validation-rmse:7.31960
[662]	validation-rmse:7.31980
[663]	validation-rmse:7.31941
[664]	validation-rmse:7.31881
[665]	validation-rmse:7.31903
[666]	validation-rmse:7.31891
[667]	validation-rmse:7.31795
[668]	validation-rmse:7.31796
[669]	validation-rmse:7.31736

[13:39:05] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[0]	validation-rmse:18.36989
[1]	validation-rmse:16.19231
[2]	validation-rmse:14.53964
[3]	validation-rmse:13.29184
[4]	validation-rmse:12.35262
[5]	validation-rmse:11.63005
[6]	validation-rmse:11.13880
[7]	validation-rmse:10.72352
[8]	validation-rmse:10.39299
[9]	validation-rmse:10.18981
[10]	validation-rmse:10.00316
[11]	validation-rmse:9.87872
[12]	validation-rmse:9.78177
[13]	validation-rmse:9.70859
[14]	validation-rmse:9.64643
[15]	validation-rmse:9.58769
[16]	validation-rmse:9.53376
[17]	validation-rmse:9.49438
[18]	validation-rmse:9.38674
[19]	validation-rmse:9.35550
[20]	validation-rmse:9.30028
[21]	validation-rmse:9.27667
[22]	validation-rmse:9.24950
[23]	validation-rmse:9.23527
[24]	validation-rmse:9.20766
[25]	validation-rmse:9.17601
[26]	validation-rmse:9.13103
[27]	validation-rmse:9.11939
[28]	validation-rmse:9.09421
[29]	validation-rmse:9.08283
[30]	validation-rmse:9.07172
[31]	validation-rmse:9.06031
[32]	validation-rmse:9.05162
[33]	validation-rmse:9.03991
[34]	validation-rmse:9.03392
[35]	validation-rmse:9.02314
[36]	validation-rmse:9.01179
[37]	validation-rmse:9.00086
[38]	validation-rmse:8.99782
[39]	validation-rmse:8.98935
[40]	validation-rmse:8.98469
[41]	validation-rmse:8.97786
[42]	validation-rmse:8.97072
[43]	validation-rmse:8.96402
[44]	validation-rmse:8.95842
[45]	validation-rmse:8.94734
[46]	validation-rmse:8.93733
[47]	validation-rmse:8.93083
[48]	validation-rmse:8.92075
[49]	validation-rmse:8.91159
[50]	validation-rmse:8.89904
[51]	validation-rmse:8.88583
[52]	validation-rmse:8.87329
[53]	validation-rmse:8.86248
[54]	validation-rmse:8.85146
[55]	validation-rmse:8.84546
[56]	validation-rmse:8.83834
[57]	validation-rmse:8.82895
[58]	validation-rmse:8.82375
[59]	validation-rmse:8.81614
[60]	validation-rmse:8.81147
[61]	validation-rmse:8.80546
[62]	validation-rmse:8.79831
[63]	validation-rmse:8.79037
[64]	validation-rmse:8.78349
[65]	validation-rmse:8.77553
[66]	validation-rmse:8.76951
[67]	validation-rmse:8.76343
[68]	validation-rmse:8.75691
[69]	validation-rmse:8.75236
[70]	validation-rmse:8.74829
[71]	validation-rmse:8.74031
[72]	validation-rmse:8.73194
[73]	validation-rmse:8.72591
[74]	validation-rmse:8.72044
[75]	validation-rmse:8.71012
[76]	validation-rmse:8.70374
[77]	validation-rmse:8.69876
[78]	validation-rmse:8.69383
[79]	validation-rmse:8.68835
[80]	validation-rmse:8.68303
[81]	validation-rmse:8.67784
[82]	validation-rmse:8.67099
[83]	validation-rmse:8.66587
[84]	validation-rmse:8.65836
[85]	validation-rmse:8.65288
[86]	validation-rmse:8.64621
[87]	validation-rmse:8.64135
[88]	validation-rmse:8.63648
[89]	validation-rmse:8.63154
[90]	validation-rmse:8.62522
[91]	validation-rmse:8.62110
[92]	validation-rmse:8.61612
[93]	validation-rmse:8.61243
[94]	validation-rmse:8.60297
[95]	validation-rmse:8.59869
[96]	validation-rmse:8.59190
[97]	validation-rmse:8.58821
[98]	validation-rmse:8.58320
[99]	validation-rmse:8.57939
[100]	validation-rmse:8.57419
[101]	validation-rmse:8.56958
[102]	validation-rmse:8.56431
[103]	validation-rmse:8.55969
[104]	validation-rmse:8.55586
[105]	validation-rmse:8.55211
[106]	validation-rmse:8.54771
[107]	validation-rmse:8.54354
[108]	validation-rmse:8.53997
[109]	validation-rmse:8.53569
[110]	validation-rmse:8.52879
[111]	validation-rmse:8.52504
[112]	validation-rmse:8.52257
[113]	validation-rmse:8.51973
[114]	validation-rmse:8.51576
[115]	validation-rmse:8.51283
[116]	validation-rmse:8.50667
[117]	validation-rmse:8.50413
[118]	validation-rmse:8.49897
[119]	validation-rmse:8.49643
[120]	validation-rmse:8.49236
[121]	validation-rmse:8.48905
[122]	validation-rmse:8.48440
[123]	validation-rmse:8.48114
[124]	validation-rmse:8.47875
[125]	validation-rmse:8.47397
[126]	validation-rmse:8.46894
[127]	validation-rmse:8.46560
[128]	validation-rmse:8.46225
[129]	validation-rmse:8.45606
[130]	validation-rmse:8.45141
[131]	validation-rmse:8.44808
[132]	validation-rmse:8.44362
[133]	validation-rmse:8.44138
[134]	validation-rmse:8.43894
[135]	validation-rmse:8.43611
[136]	validation-rmse:8.43109
[137]	validation-rmse:8.42711
[138]	validation-rmse:8.42332
[139]	validation-rmse:8.41954
[140]	validation-rmse:8.41752
[141]	validation-rmse:8.41379
[142]	validation-rmse:8.40893
[143]	validation-rmse:8.40392
[144]	validation-rmse:8.40080
[145]	validation-rmse:8.39777
[146]	validation-rmse:8.39488
[147]	validation-rmse:8.39103
[148]	validation-rmse:8.38741
[149]	validation-rmse:8.38424
[150]	validation-rmse:8.38144
[151]	validation-rmse:8.37862
[152]	validation-rmse:8.37430
[153]	validation-rmse:8.37149
[154]	validation-rmse:8.36723
[155]	validation-rmse:8.36298
[156]	validation-rmse:8.36035
[157]	validation-rmse:8.35729
[158]	validation-rmse:8.35480
[159]	validation-rmse:8.35276
[160]	validation-rmse:8.34986
[161]	validation-rmse:8.34677
[162]	validation-rmse:8.34461
[163]	validation-rmse:8.34184
[164]	validation-rmse:8.33728
[165]	validation-rmse:8.33438
[166]	validation-rmse:8.33087
[167]	validation-rmse:8.32898
[168]	validation-rmse:8.32664
[169]	validation-rmse:8.32348
[170]	validation-rmse:8.31901
[171]	validation-rmse:8.31712
[172]	validation-rmse:8.31313
[173]	validation-rmse:8.31005
[174]	validation-rmse:8.30779
[175]	validation-rmse:8.30605
[176]	validation-rmse:8.30313
[177]	validation-rmse:8.30201
[178]	validation-rmse:8.29994
[179]	validation-rmse:8.29792
[180]	validation-rmse:8.29529
[181]	validation-rmse:8.29373
[182]	validation-rmse:8.28997
[183]	validation-rmse:8.28810
[184]	validation-rmse:8.28419
[185]	validation-rmse:8.28094
[186]	validation-rmse:8.27824
[187]	validation-rmse:8.27613
[188]	validation-rmse:8.27335
[189]	validation-rmse:8.27130
[190]	validation-rmse:8.27000
[191]	validation-rmse:8.26727
[192]	validation-rmse:8.26582
[193]	validation-rmse:8.26407
[194]	validation-rmse:8.26153
[195]	validation-rmse:8.25965
[196]	validation-rmse:8.25819
[197]	validation-rmse:8.25511
[198]	validation-rmse:8.25402
[199]	validation-rmse:8.25201
[200]	validation-rmse:8.24969
[201]	validation-rmse:8.24814
[202]	validation-rmse:8.24755
[203]	validation-rmse:8.24627
[204]	validation-rmse:8.24481
[205]	validation-rmse:8.24297
[206]	validation-rmse:8.24144
[207]	validation-rmse:8.24068
[208]	validation-rmse:8.23901
[209]	validation-rmse:8.23739
[210]	validation-rmse:8.23551
[211]	validation-rmse:8.23418
[212]	validation-rmse:8.23244
[213]	validation-rmse:8.23096
[214]	validation-rmse:8.22944
[215]	validation-rmse:8.22762
[216]	validation-rmse:8.22592
[217]	validation-rmse:8.22524
[218]	validation-rmse:8.22421
[219]	validation-rmse:8.22198
[220]	validation-rmse:8.21608
[221]	validation-rmse:8.21441
[222]	validation-rmse:8.21190
[223]	validation-rmse:8.21129
[224]	validation-rmse:8.20993
[225]	validation-rmse:8.20888
[226]	validation-rmse:8.20747
[227]	validation-rmse:8.20625
[228]	validation-rmse:8.20384
[229]	validation-rmse:8.20182
[230]	validation-rmse:8.19905
[231]	validation-rmse:8.19719
[232]	validation-rmse:8.19564
[233]	validation-rmse:8.19361
[234]	validation-rmse:8.18986
[235]	validation-rmse:8.18803
[236]	validation-rmse:8.18587
[237]	validation-rmse:8.18312
[238]	validation-rmse:8.18091
[239]	validation-rmse:8.17756
[240]	validation-rmse:8.17378
[241]	validation-rmse:8.17175
[242]	validation-rmse:8.17015
[243]	validation-rmse:8.16730
[244]	validation-rmse:8.16521
[245]	validation-rmse:8.16187
[246]	validation-rmse:8.15937
[247]	validation-rmse:8.15600
[248]	validation-rmse:8.15231
[249]	validation-rmse:8.15035
[250]	validation-rmse:8.14613
[251]	validation-rmse:8.14129
[252]	validation-rmse:8.13801
[253]	validation-rmse:8.13461
[254]	validation-rmse:8.13224
[255]	validation-rmse:8.12852
[256]	validation-rmse:8.12554
[257]	validation-rmse:8.12197
[258]	validation-rmse:8.11898
[259]	validation-rmse:8.11586
[260]	validation-rmse:8.11436
[261]	validation-rmse:8.11177
[262]	validation-rmse:8.11058
[263]	validation-rmse:8.10739
[264]	validation-rmse:8.10630
[265]	validation-rmse:8.10490
[266]	validation-rmse:8.10170
[267]	validation-rmse:8.09840
[268]	validation-rmse:8.09578
[269]	validation-rmse:8.09456
[270]	validation-rmse:8.09242
[271]	validation-rmse:8.08909
[272]	validation-rmse:8.08810
[273]	validation-rmse:8.08588
[274]	validation-rmse:8.08429
[275]	validation-rmse:8.08167
[276]	validation-rmse:8.07978
[277]	validation-rmse:8.07869
[278]	validation-rmse:8.07689
[279]	validation-rmse:8.07443
[280]	validation-rmse:8.07362
[281]	validation-rmse:8.07196
[282]	validation-rmse:8.07107
[283]	validation-rmse:8.06929
[284]	validation-rmse:8.06741
[285]	validation-rmse:8.06616
[286]	validation-rmse:8.06481
[287]	validation-rmse:8.06392
[288]	validation-rmse:8.06234
[289]	validation-rmse:8.06030
[290]	validation-rmse:8.05880
[291]	validation-rmse:8.05758
[292]	validation-rmse:8.05469
[293]	validation-rmse:8.05213
[294]	validation-rmse:8.04928
[295]	validation-rmse:8.04767
[296]	validation-rmse:8.04600
[297]	validation-rmse:8.04540
[298]	validation-rmse:8.04378
[299]	validation-rmse:8.04087
[300]	validation-rmse:8.03892
[301]	validation-rmse:8.03695
[302]	validation-rmse:8.03543
[303]	validation-rmse:8.03407
[304]	validation-rmse:8.03370
[305]	validation-rmse:8.03213
[306]	validation-rmse:8.03009
[307]	validation-rmse:8.02761
[308]	validation-rmse:8.02656
[309]	validation-rmse:8.02504
[310]	validation-rmse:8.02378
[311]	validation-rmse:8.02272
[312]	validation-rmse:8.02162
[313]	validation-rmse:8.02032
[314]	validation-rmse:8.01838
[315]	validation-rmse:8.01807
[316]	validation-rmse:8.01750
[317]	validation-rmse:8.01495
[318]	validation-rmse:8.01356
[319]	validation-rmse:8.01081
[320]	validation-rmse:8.00956
[321]	validation-rmse:8.00868
[322]	validation-rmse:8.00694
[323]	validation-rmse:8.00551
[324]	validation-rmse:8.00469
[325]	validation-rmse:8.00323
[326]	validation-rmse:8.00241
[327]	validation-rmse:8.00093
[328]	validation-rmse:8.00018
[329]	validation-rmse:7.99867
[330]	validation-rmse:7.99809
[331]	validation-rmse:7.99755
[332]	validation-rmse:7.99670
[333]	validation-rmse:7.99655
[334]	validation-rmse:7.99516
[335]	validation-rmse:7.99443
[336]	validation-rmse:7.99309
[337]	validation-rmse:7.99243
[338]	validation-rmse:7.99167
[339]	validation-rmse:7.99084
[340]	validation-rmse:7.98941
[341]	validation-rmse:7.98905
[342]	validation-rmse:7.98826
[343]	validation-rmse:7.98669
[344]	validation-rmse:7.98609
[345]	validation-rmse:7.98457
[346]	validation-rmse:7.98206
[347]	validation-rmse:7.98147
[348]	validation-rmse:7.97936
[349]	validation-rmse:7.97768
[350]	validation-rmse:7.97557
[351]	validation-rmse:7.97374
[352]	validation-rmse:7.97201
[353]	validation-rmse:7.96794
[354]	validation-rmse:7.96598
[355]	validation-rmse:7.96396
[356]	validation-rmse:7.96191
[357]	validation-rmse:7.96074
[358]	validation-rmse:7.95934
[359]	validation-rmse:7.95688
[360]	validation-rmse:7.95465
[361]	validation-rmse:7.95260
[362]	validation-rmse:7.95073
[363]	validation-rmse:7.94806
[364]	validation-rmse:7.94608
[365]	validation-rmse:7.94284
[366]	validation-rmse:7.93927
[367]	validation-rmse:7.93678
[368]	validation-rmse:7.93486
[369]	validation-rmse:7.93312
[370]	validation-rmse:7.93191
[371]	validation-rmse:7.92975
[372]	validation-rmse:7.92696
[373]	validation-rmse:7.92398
[374]	validation-rmse:7.92256
[375]	validation-rmse:7.91996
[376]	validation-rmse:7.91786
[377]	validation-rmse:7.91500
[378]	validation-rmse:7.91330
[379]	validation-rmse:7.91188
[380]	validation-rmse:7.90929
[381]	validation-rmse:7.90608
[382]	validation-rmse:7.90267
[383]	validation-rmse:7.89985
[384]	validation-rmse:7.89804
[385]	validation-rmse:7.89604
[386]	validation-rmse:7.89419
[387]	validation-rmse:7.89146
[388]	validation-rmse:7.88776
[389]	validation-rmse:7.88587
[390]	validation-rmse:7.88280
[391]	validation-rmse:7.88128
[392]	validation-rmse:7.87756
[393]	validation-rmse:7.87473
[394]	validation-rmse:7.87229
[395]	validation-rmse:7.86939
[396]	validation-rmse:7.86720
[397]	validation-rmse:7.86429
[398]	validation-rmse:7.86235
[399]	validation-rmse:7.85948
[400]	validation-rmse:7.85729
[401]	validation-rmse:7.85633
[402]	validation-rmse:7.85317
[403]	validation-rmse:7.85085
[404]	validation-rmse:7.84912
[405]	validation-rmse:7.84658
[406]	validation-rmse:7.84491
[407]	validation-rmse:7.84238
[408]	validation-rmse:7.83944
[409]	validation-rmse:7.83815
[410]	validation-rmse:7.83642
[411]	validation-rmse:7.83562
[412]	validation-rmse:7.83431
[413]	validation-rmse:7.83264
[414]	validation-rmse:7.83169
[415]	validation-rmse:7.83097
[416]	validation-rmse:7.82853
[417]	validation-rmse:7.82792
[418]	validation-rmse:7.82650
[419]	validation-rmse:7.82585
[420]	validation-rmse:7.82431
[421]	validation-rmse:7.82324
[422]	validation-rmse:7.82160
[423]	validation-rmse:7.82042
[424]	validation-rmse:7.81867
[425]	validation-rmse:7.81776
[426]	validation-rmse:7.81776
[427]	validation-rmse:7.81728
[428]	validation-rmse:7.81683
[429]	validation-rmse:7.81569
[430]	validation-rmse:7.81485
[431]	validation-rmse:7.81337
[432]	validation-rmse:7.81285
[433]	validation-rmse:7.81235
[434]	validation-rmse:7.81192
[435]	validation-rmse:7.81191
[436]	validation-rmse:7.81088
[437]	validation-rmse:7.80989
[438]	validation-rmse:7.80913
[439]	validation-rmse:7.80842
[440]	validation-rmse:7.80832
[441]	validation-rmse:7.80756
[442]	validation-rmse:7.80722
[443]	validation-rmse:7.80559
[444]	validation-rmse:7.80358
[445]	validation-rmse:7.80328
[446]	validation-rmse:7.80271
[447]	validation-rmse:7.80209
[448]	validation-rmse:7.80135
[449]	validation-rmse:7.80106
[450]	validation-rmse:7.80043
[451]	validation-rmse:7.79885
[452]	validation-rmse:7.79845
[453]	validation-rmse:7.79796
[454]	validation-rmse:7.79730
[455]	validation-rmse:7.79622
[456]	validation-rmse:7.79615
[457]	validation-rmse:7.79570
[458]	validation-rmse:7.79471
[459]	validation-rmse:7.79340
[460]	validation-rmse:7.79301
[461]	validation-rmse:7.79275
[462]	validation-rmse:7.79174
[463]	validation-rmse:7.79076
[464]	validation-rmse:7.78995
[465]	validation-rmse:7.78935
[466]	validation-rmse:7.78849
[467]	validation-rmse:7.78782
[468]	validation-rmse:7.78713
[469]	validation-rmse:7.78656
[470]	validation-rmse:7.78608
[471]	validation-rmse:7.78506
[472]	validation-rmse:7.78354
[473]	validation-rmse:7.78284
[474]	validation-rmse:7.78236
[475]	validation-rmse:7.78099
[476]	validation-rmse:7.78037
[477]	validation-rmse:7.77951
[478]	validation-rmse:7.77877
[479]	validation-rmse:7.77812
[480]	validation-rmse:7.77746
[481]	validation-rmse:7.77672
[482]	validation-rmse:7.77670
[483]	validation-rmse:7.77610
[484]	validation-rmse:7.77528
[485]	validation-rmse:7.77494
[486]	validation-rmse:7.77375
[487]	validation-rmse:7.77388
[488]	validation-rmse:7.77274
[489]	validation-rmse:7.77112
[490]	validation-rmse:7.77103
[491]	validation-rmse:7.77008
[492]	validation-rmse:7.76965
[493]	validation-rmse:7.76915
[494]	validation-rmse:7.76807
[495]	validation-rmse:7.76792
[496]	validation-rmse:7.76733
[497]	validation-rmse:7.76615
[498]	validation-rmse:7.76582
[499]	validation-rmse:7.76529
[500]	validation-rmse:7.76486
[501]	validation-rmse:7.76442
[502]	validation-rmse:7.76409
[503]	validation-rmse:7.76382
[504]	validation-rmse:7.76362
[505]	validation-rmse:7.76315
[506]	validation-rmse:7.76285
[507]	validation-rmse:7.76273
[508]	validation-rmse:7.76184
[509]	validation-rmse:7.76128
[510]	validation-rmse:7.76091
[511]	validation-rmse:7.76035
[512]	validation-rmse:7.75976
[513]	validation-rmse:7.75934
[514]	validation-rmse:7.75929
[515]	validation-rmse:7.75846
[516]	validation-rmse:7.75775
[517]	validation-rmse:7.75765
[518]	validation-rmse:7.75759
[519]	validation-rmse:7.75573
[520]	validation-rmse:7.75565
[521]	validation-rmse:7.75475
[522]	validation-rmse:7.75399
[523]	validation-rmse:7.75391
[524]	validation-rmse:7.75317
[525]	validation-rmse:7.75251
[526]	validation-rmse:7.75170
[527]	validation-rmse:7.75119
[528]	validation-rmse:7.75046
[529]	validation-rmse:7.75016
[530]	validation-rmse:7.75016
[531]	validation-rmse:7.75001
[532]	validation-rmse:7.74944
[533]	validation-rmse:7.74832
[534]	validation-rmse:7.74814
[535]	validation-rmse:7.74739
[536]	validation-rmse:7.74611
[537]	validation-rmse:7.74395
[538]	validation-rmse:7.74374
[539]	validation-rmse:7.74361
[540]	validation-rmse:7.74374
[541]	validation-rmse:7.74334
[542]	validation-rmse:7.74248
[543]	validation-rmse:7.74161
[544]	validation-rmse:7.74064
[545]	validation-rmse:7.73867
[546]	validation-rmse:7.73672
[547]	validation-rmse:7.73609
[548]	validation-rmse:7.73517
[549]	validation-rmse:7.73375
[550]	validation-rmse:7.73293
[551]	validation-rmse:7.73161
[552]	validation-rmse:7.73092
[553]	validation-rmse:7.73012
[554]	validation-rmse:7.72944
[555]	validation-rmse:7.72957
[556]	validation-rmse:7.72762
[557]	validation-rmse:7.72669
[558]	validation-rmse:7.72553
[559]	validation-rmse:7.72490
[560]	validation-rmse:7.72439
[561]	validation-rmse:7.72286
[562]	validation-rmse:7.72199
[563]	validation-rmse:7.72113
[564]	validation-rmse:7.72046
[565]	validation-rmse:7.71873
[566]	validation-rmse:7.71761
[567]	validation-rmse:7.71735
[568]	validation-rmse:7.71650
[569]	validation-rmse:7.71504
[570]	validation-rmse:7.71413
[571]	validation-rmse:7.71254
[572]	validation-rmse:7.71203
[573]	validation-rmse:7.71133
[574]	validation-rmse:7.71065
[575]	validation-rmse:7.70964
[576]	validation-rmse:7.70806
[577]	validation-rmse:7.70694
[578]	validation-rmse:7.70597
[579]	validation-rmse:7.70555
[580]	validation-rmse:7.70451
[581]	validation-rmse:7.70401
[582]	validation-rmse:7.70230
[583]	validation-rmse:7.70215
[584]	validation-rmse:7.70140
[585]	validation-rmse:7.70064
[586]	validation-rmse:7.70001
[587]	validation-rmse:7.69964
[588]	validation-rmse:7.69894
[589]	validation-rmse:7.69810
[590]	validation-rmse:7.69768
[591]	validation-rmse:7.69780
[592]	validation-rmse:7.69782
[593]	validation-rmse:7.69738
[594]	validation-rmse:7.69640
[595]	validation-rmse:7.69525
[596]	validation-rmse:7.69406
[597]	validation-rmse:7.69328
[598]	validation-rmse:7.69243
[599]	validation-rmse:7.69153
[600]	validation-rmse:7.69057
[601]	validation-rmse:7.69014
[602]	validation-rmse:7.68891
[603]	validation-rmse:7.68826
[604]	validation-rmse:7.68783
[605]	validation-rmse:7.68701
[606]	validation-rmse:7.68638
[607]	validation-rmse:7.68584
[608]	validation-rmse:7.68506
[609]	validation-rmse:7.68430
[610]	validation-rmse:7.68349
[611]	validation-rmse:7.68273
[612]	validation-rmse:7.68232
[613]	validation-rmse:7.68171
[614]	validation-rmse:7.68113
[615]	validation-rmse:7.68108
[616]	validation-rmse:7.67990
[617]	validation-rmse:7.67902
[618]	validation-rmse:7.67869
[619]	validation-rmse:7.67786
[620]	validation-rmse:7.67742
[621]	validation-rmse:7.67604
[622]	validation-rmse:7.67558
[623]	validation-rmse:7.67524
[624]	validation-rmse:7.67540
[625]	validation-rmse:7.67263
[626]	validation-rmse:7.67216
[627]	validation-rmse:7.67107
[628]	validation-rmse:7.67046
[629]	validation-rmse:7.67007
[630]	validation-rmse:7.66977
[631]	validation-rmse:7.66903
[632]	validation-rmse:7.66701
[633]	validation-rmse:7.66657
[634]	validation-rmse:7.66585
[635]	validation-rmse:7.66550
[636]	validation-rmse:7.66519
[637]	validation-rmse:7.66481
[638]	validation-rmse:7.66467
[639]	validation-rmse:7.66420
[640]	validation-rmse:7.66375
[641]	validation-rmse:7.66307
[642]	validation-rmse:7.66170
[643]	validation-rmse:7.66117
[644]	validation-rmse:7.66092
[645]	validation-rmse:7.66085
[646]	validation-rmse:7.66067
[647]	validation-rmse:7.66050
[648]	validation-rmse:7.65942
[649]	validation-rmse:7.65884
[650]	validation-rmse:7.65830
[651]	validation-rmse:7.65805
[652]	validation-rmse:7.65714
[653]	validation-rmse:7.65716
[654]	validation-rmse:7.65626
[655]	validation-rmse:7.65599
[656]	validation-rmse:7.65430
[657]	validation-rmse:7.65395
[658]	validation-rmse:7.65345
[659]	validation-rmse:7.65249
[660]	validation-rmse:7.65241
[661]	validation-rmse:7.65230
[662]	validation-rmse:7.65087
[663]	validation-rmse:7.65054
[664]	validation-rmse:7.65008
[665]	validation-rmse:7.64997
[666]	validation-rmse:7.64856
[667]	validation-rmse:7.64835
[668]	validation-rmse:7.64806

[13:48:48] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[0]	validation-rmse:19.87681
[1]	validation-rmse:18.69618
[2]	validation-rmse:17.62843
[3]	validation-rmse:16.67227
[4]	validation-rmse:15.79335
[5]	validation-rmse:15.00759
[6]	validation-rmse:14.30610
[7]	validation-rmse:13.69580
[8]	validation-rmse:13.13308
[9]	validation-rmse:12.63210
[10]	validation-rmse:12.18654
[11]	validation-rmse:11.80790
[12]	validation-rmse:11.43710
[13]	validation-rmse:11.12914
[14]	validation-rmse:10.86399
[15]	validation-rmse:10.59468
[16]	validation-rmse:10.38642
[17]	validation-rmse:10.20246
[18]	validation-rmse:10.00614
[19]	validation-rmse:9.84527
[20]	validation-rmse:9.71878
[21]	validation-rmse:9.60729
[22]	validation-rmse:9.47843
[23]	validation-rmse:9.36428
[24]	validation-rmse:9.27675
[25]	validation-rmse:9.20710
[26]	validation-rmse:9.12193
[27]	validation-rmse:9.06307
[28]	validation-rmse:9.01254
[29]	validation-rmse:8.94466
[30]	validation-rmse:8.89675
[31]	validation-rmse:8.85102
[32]	validation-rmse:8.81743
[33]	validation-rmse:8.78188
[34]	validation-rmse:8.75136
[35]	validation-rmse:8.70481
[36]	validation-rmse:8.67303
[37]	validation-rmse:8.64618
[38]	validation-rmse:8.62059
[39]	validation-rmse:8.58982
[40]	validation-rmse:8.55852
[41]	validation-rmse:8.53604
[42]	validation-rmse:8.51406
[43]	validation-rmse:8.49035
[44]	validation-rmse:8.47159
[45]	validation-rmse:8.45437
[46]	validation-rmse:8.43644
[47]	validation-rmse:8.42464
[48]	validation-rmse:8.40933
[49]	validation-rmse:8.38784
[50]	validation-rmse:8.37567
[51]	validation-rmse:8.36326
[52]	validation-rmse:8.35355
[53]	validation-rmse:8.34377
[54]	validation-rmse:8.33317
[55]	validation-rmse:8.31873
[56]	validation-rmse:8.30891
[57]	validation-rmse:8.29900
[58]	validation-rmse:8.28954
[59]	validation-rmse:8.28170
[60]	validation-rmse:8.27380
[61]	validation-rmse:8.26787
[62]	validation-rmse:8.25679
[63]	validation-rmse:8.24573
[64]	validation-rmse:8.23531
[65]	validation-rmse:8.22529
[66]	validation-rmse:8.22005
[67]	validation-rmse:8.21331
[68]	validation-rmse:8.20858
[69]	validation-rmse:8.20341
[70]	validation-rmse:8.19691
[71]	validation-rmse:8.19230
[72]	validation-rmse:8.18768
[73]	validation-rmse:8.18374
[74]	validation-rmse:8.18001
[75]	validation-rmse:8.17710
[76]	validation-rmse:8.17099
[77]	validation-rmse:8.16496
[78]	validation-rmse:8.15825
[79]	validation-rmse:8.15429
[80]	validation-rmse:8.15037
[81]	validation-rmse:8.14658
[82]	validation-rmse:8.14187
[83]	validation-rmse:8.13925
[84]	validation-rmse:8.13572
[85]	validation-rmse:8.13119
[86]	validation-rmse:8.12915
[87]	validation-rmse:8.12326
[88]	validation-rmse:8.12081
[89]	validation-rmse:8.11864
[90]	validation-rmse:8.11605
[91]	validation-rmse:8.10981
[92]	validation-rmse:8.10759
[93]	validation-rmse:8.10481
[94]	validation-rmse:8.10219
[95]	validation-rmse:8.09838
[96]	validation-rmse:8.09564
[97]	validation-rmse:8.09316
[98]	validation-rmse:8.09022
[99]	validation-rmse:8.08809
[100]	validation-rmse:8.08508
[101]	validation-rmse:8.08106
[102]	validation-rmse:8.07749
[103]	validation-rmse:8.07415
[104]	validation-rmse:8.07172
[105]	validation-rmse:8.06927
[106]	validation-rmse:8.06400
[107]	validation-rmse:8.06195
[108]	validation-rmse:8.05920
[109]	validation-rmse:8.05514
[110]	validation-rmse:8.05155
[111]	validation-rmse:8.04895
[112]	validation-rmse:8.04630
[113]	validation-rmse:8.04349
[114]	validation-rmse:8.04198
[115]	validation-rmse:8.03945
[116]	validation-rmse:8.03741
[117]	validation-rmse:8.03314
[118]	validation-rmse:8.03098
[119]	validation-rmse:8.02921
[120]	validation-rmse:8.02643
[121]	validation-rmse:8.02354
[122]	validation-rmse:8.01962
[123]	validation-rmse:8.01740
[124]	validation-rmse:8.01303
[125]	validation-rmse:8.01118
[126]	validation-rmse:8.00950
[127]	validation-rmse:8.00654
[128]	validation-rmse:8.00400
[129]	validation-rmse:8.00023
[130]	validation-rmse:7.99758
[131]	validation-rmse:7.99614
[132]	validation-rmse:7.99305
[133]	validation-rmse:7.99074
[134]	validation-rmse:7.98907
[135]	validation-rmse:7.98540
[136]	validation-rmse:7.98305
[137]	validation-rmse:7.98059
[138]	validation-rmse:7.97817
[139]	validation-rmse:7.97590
[140]	validation-rmse:7.97346
[141]	validation-rmse:7.97090
[142]	validation-rmse:7.96839
[143]	validation-rmse:7.96535
[144]	validation-rmse:7.96284
[145]	validation-rmse:7.95918
[146]	validation-rmse:7.95709
[147]	validation-rmse:7.95483
[148]	validation-rmse:7.95260
[149]	validation-rmse:7.95072
[150]	validation-rmse:7.94830
[151]	validation-rmse:7.94661
[152]	validation-rmse:7.94468
[153]	validation-rmse:7.94354
[154]	validation-rmse:7.94154
[155]	validation-rmse:7.93859
[156]	validation-rmse:7.93546
[157]	validation-rmse:7.93303
[158]	validation-rmse:7.93058
[159]	validation-rmse:7.92888
[160]	validation-rmse:7.92702
[161]	validation-rmse:7.92526
[162]	validation-rmse:7.92393
[163]	validation-rmse:7.92203
[164]	validation-rmse:7.92008
[165]	validation-rmse:7.91772
[166]	validation-rmse:7.91603
[167]	validation-rmse:7.91413
[168]	validation-rmse:7.91258
[169]	validation-rmse:7.91059
[170]	validation-rmse:7.90869
[171]	validation-rmse:7.90716
[172]	validation-rmse:7.90498
[173]	validation-rmse:7.90266
[174]	validation-rmse:7.90003
[175]	validation-rmse:7.89709
[176]	validation-rmse:7.89532
[177]	validation-rmse:7.89339
[178]	validation-rmse:7.89200
[179]	validation-rmse:7.88924
[180]	validation-rmse:7.88777
[181]	validation-rmse:7.88616
[182]	validation-rmse:7.88357
[183]	validation-rmse:7.88213
[184]	validation-rmse:7.88066
[185]	validation-rmse:7.87868
[186]	validation-rmse:7.87657
[187]	validation-rmse:7.87458
[188]	validation-rmse:7.87232
[189]	validation-rmse:7.87060
[190]	validation-rmse:7.86872
[191]	validation-rmse:7.86688
[192]	validation-rmse:7.86584
[193]	validation-rmse:7.86289
[194]	validation-rmse:7.86032
[195]	validation-rmse:7.85828
[196]	validation-rmse:7.85522
[197]	validation-rmse:7.85435
[198]	validation-rmse:7.85216
[199]	validation-rmse:7.85070
[200]	validation-rmse:7.84946
[201]	validation-rmse:7.84773
[202]	validation-rmse:7.84617
[203]	validation-rmse:7.84456
[204]	validation-rmse:7.84308
[205]	validation-rmse:7.84135
[206]	validation-rmse:7.83908
[207]	validation-rmse:7.83762
[208]	validation-rmse:7.83595
[209]	validation-rmse:7.83448
[210]	validation-rmse:7.83273
[211]	validation-rmse:7.83097
[212]	validation-rmse:7.82917
[213]	validation-rmse:7.82807
[214]	validation-rmse:7.82668
[215]	validation-rmse:7.82588
[216]	validation-rmse:7.82455
[217]	validation-rmse:7.82301
[218]	validation-rmse:7.82145
[219]	validation-rmse:7.82054
[220]	validation-rmse:7.81893
[221]	validation-rmse:7.81786
[222]	validation-rmse:7.81595
[223]	validation-rmse:7.81439
[224]	validation-rmse:7.81324
[225]	validation-rmse:7.81096
[226]	validation-rmse:7.80884
[227]	validation-rmse:7.80775
[228]	validation-rmse:7.80651
[229]	validation-rmse:7.80505
[230]	validation-rmse:7.80414
[231]	validation-rmse:7.80310
[232]	validation-rmse:7.80222
[233]	validation-rmse:7.80098
[234]	validation-rmse:7.79965
[235]	validation-rmse:7.79873
[236]	validation-rmse:7.79778
[237]	validation-rmse:7.79671
[238]	validation-rmse:7.79551
[239]	validation-rmse:7.79428
[240]	validation-rmse:7.79319
[241]	validation-rmse:7.79192
[242]	validation-rmse:7.79080
[243]	validation-rmse:7.78921
[244]	validation-rmse:7.78779
[245]	validation-rmse:7.78677
[246]	validation-rmse:7.78545
[247]	validation-rmse:7.78374
[248]	validation-rmse:7.78272
[249]	validation-rmse:7.78169
[250]	validation-rmse:7.78061
[251]	validation-rmse:7.78017
[252]	validation-rmse:7.77899
[253]	validation-rmse:7.77800
[254]	validation-rmse:7.77754
[255]	validation-rmse:7.77586
[256]	validation-rmse:7.77374
[257]	validation-rmse:7.77263
[258]	validation-rmse:7.77170
[259]	validation-rmse:7.77051
[260]	validation-rmse:7.76886
[261]	validation-rmse:7.76756
[262]	validation-rmse:7.76678
[263]	validation-rmse:7.76543
[264]	validation-rmse:7.76385
[265]	validation-rmse:7.76292
[266]	validation-rmse:7.76126
[267]	validation-rmse:7.76011
[268]	validation-rmse:7.75936
[269]	validation-rmse:7.75811
[270]	validation-rmse:7.75675
[271]	validation-rmse:7.75594
[272]	validation-rmse:7.75504
[273]	validation-rmse:7.75359
[274]	validation-rmse:7.75283
[275]	validation-rmse:7.75130
[276]	validation-rmse:7.75045
[277]	validation-rmse:7.74949
[278]	validation-rmse:7.74811
[279]	validation-rmse:7.74742
[280]	validation-rmse:7.74668
[281]	validation-rmse:7.74578
[282]	validation-rmse:7.74515
[283]	validation-rmse:7.74437
[284]	validation-rmse:7.74224
[285]	validation-rmse:7.74101
[286]	validation-rmse:7.74019
[287]	validation-rmse:7.73912
[288]	validation-rmse:7.73826
[289]	validation-rmse:7.73730
[290]	validation-rmse:7.73697
[291]	validation-rmse:7.73610
[292]	validation-rmse:7.73511
[293]	validation-rmse:7.73424
[294]	validation-rmse:7.73340
[295]	validation-rmse:7.73269
[296]	validation-rmse:7.73228
[297]	validation-rmse:7.73145
[298]	validation-rmse:7.73054
[299]	validation-rmse:7.73025
[300]	validation-rmse:7.72943
[301]	validation-rmse:7.72863
[302]	validation-rmse:7.72783
[303]	validation-rmse:7.72704
[304]	validation-rmse:7.72628
[305]	validation-rmse:7.72571
[306]	validation-rmse:7.72502
[307]	validation-rmse:7.72389
[308]	validation-rmse:7.72288
[309]	validation-rmse:7.72244
[310]	validation-rmse:7.72157
[311]	validation-rmse:7.72064
[312]	validation-rmse:7.71980
[313]	validation-rmse:7.71897
[314]	validation-rmse:7.71760
[315]	validation-rmse:7.71488
[316]	validation-rmse:7.71401
[317]	validation-rmse:7.71299
[318]	validation-rmse:7.71153
[319]	validation-rmse:7.71080
[320]	validation-rmse:7.70980
[321]	validation-rmse:7.70901
[322]	validation-rmse:7.70824
[323]	validation-rmse:7.70783
[324]	validation-rmse:7.70695
[325]	validation-rmse:7.70629
[326]	validation-rmse:7.70574
[327]	validation-rmse:7.70502
[328]	validation-rmse:7.70447
[329]	validation-rmse:7.70424
[330]	validation-rmse:7.70380
[331]	validation-rmse:7.70282
[332]	validation-rmse:7.70177
[333]	validation-rmse:7.70159
[334]	validation-rmse:7.69975
[335]	validation-rmse:7.69917
[336]	validation-rmse:7.69869
[337]	validation-rmse:7.69860
[338]	validation-rmse:7.69794
[339]	validation-rmse:7.69753
[340]	validation-rmse:7.69714
[341]	validation-rmse:7.69679
[342]	validation-rmse:7.69627
[343]	validation-rmse:7.69491
[344]	validation-rmse:7.69420
[345]	validation-rmse:7.69371
[346]	validation-rmse:7.69274
[347]	validation-rmse:7.69216
[348]	validation-rmse:7.69161
[349]	validation-rmse:7.69108
[350]	validation-rmse:7.68987
[351]	validation-rmse:7.68694
[352]	validation-rmse:7.68529
[353]	validation-rmse:7.68469
[354]	validation-rmse:7.68398
[355]	validation-rmse:7.68263
[356]	validation-rmse:7.68079
[357]	validation-rmse:7.68021
[358]	validation-rmse:7.67913
[359]	validation-rmse:7.67731
[360]	validation-rmse:7.67662
[361]	validation-rmse:7.67563
[362]	validation-rmse:7.67487
[363]	validation-rmse:7.67432
[364]	validation-rmse:7.67335
[365]	validation-rmse:7.67229
[366]	validation-rmse:7.67139
[367]	validation-rmse:7.66909
[368]	validation-rmse:7.66826
[369]	validation-rmse:7.66736
[370]	validation-rmse:7.66619
[371]	validation-rmse:7.66563
[372]	validation-rmse:7.66365
[373]	validation-rmse:7.66310
[374]	validation-rmse:7.66071
[375]	validation-rmse:7.65997
[376]	validation-rmse:7.65908
[377]	validation-rmse:7.65688
[378]	validation-rmse:7.65530
[379]	validation-rmse:7.65448
[380]	validation-rmse:7.65336
[381]	validation-rmse:7.65212
[382]	validation-rmse:7.65101
[383]	validation-rmse:7.64906
[384]	validation-rmse:7.64796
[385]	validation-rmse:7.64623
[386]	validation-rmse:7.64582
[387]	validation-rmse:7.64534
[388]	validation-rmse:7.64330
[389]	validation-rmse:7.64224
[390]	validation-rmse:7.64115
[391]	validation-rmse:7.64040
[392]	validation-rmse:7.63917
[393]	validation-rmse:7.63802
[394]	validation-rmse:7.63743
[395]	validation-rmse:7.63626
[396]	validation-rmse:7.63521
[397]	validation-rmse:7.63444
[398]	validation-rmse:7.63250
[399]	validation-rmse:7.63179
[400]	validation-rmse:7.63122
[401]	validation-rmse:7.63010
[402]	validation-rmse:7.62887
[403]	validation-rmse:7.62785
[404]	validation-rmse:7.62687
[405]	validation-rmse:7.62572
[406]	validation-rmse:7.62437
[407]	validation-rmse:7.62332
[408]	validation-rmse:7.62196
[409]	validation-rmse:7.62115
[410]	validation-rmse:7.61963
[411]	validation-rmse:7.61847
[412]	validation-rmse:7.61733
[413]	validation-rmse:7.61622
[414]	validation-rmse:7.61466
[415]	validation-rmse:7.61402
[416]	validation-rmse:7.61305
[417]	validation-rmse:7.61227
[418]	validation-rmse:7.61149
[419]	validation-rmse:7.61064
[420]	validation-rmse:7.60910
[421]	validation-rmse:7.60822
[422]	validation-rmse:7.60747
[423]	validation-rmse:7.60648
[424]	validation-rmse:7.60573
[425]	validation-rmse:7.60472
[426]	validation-rmse:7.60334
[427]	validation-rmse:7.60219
[428]	validation-rmse:7.60159
[429]	validation-rmse:7.60064
[430]	validation-rmse:7.59965
[431]	validation-rmse:7.59883
[432]	validation-rmse:7.59732
[433]	validation-rmse:7.59632
[434]	validation-rmse:7.59529
[435]	validation-rmse:7.59452
[436]	validation-rmse:7.59383
[437]	validation-rmse:7.59281
[438]	validation-rmse:7.59160
[439]	validation-rmse:7.59040
[440]	validation-rmse:7.58947
[441]	validation-rmse:7.58830
[442]	validation-rmse:7.58638
[443]	validation-rmse:7.58581
[444]	validation-rmse:7.58477
[445]	validation-rmse:7.58394
[446]	validation-rmse:7.58271
[447]	validation-rmse:7.58176
[448]	validation-rmse:7.58092
[449]	validation-rmse:7.58026
[450]	validation-rmse:7.57927
[451]	validation-rmse:7.57842
[452]	validation-rmse:7.57709
[453]	validation-rmse:7.57603
[454]	validation-rmse:7.57502
[455]	validation-rmse:7.57421
[456]	validation-rmse:7.57342
[457]	validation-rmse:7.57265
[458]	validation-rmse:7.57125
[459]	validation-rmse:7.57064
[460]	validation-rmse:7.57001
[461]	validation-rmse:7.56886
[462]	validation-rmse:7.56802
[463]	validation-rmse:7.56733
[464]	validation-rmse:7.56614
[465]	validation-rmse:7.56559
[466]	validation-rmse:7.56527
[467]	validation-rmse:7.56461
[468]	validation-rmse:7.56374
[469]	validation-rmse:7.56300
[470]	validation-rmse:7.56211
[471]	validation-rmse:7.56166
[472]	validation-rmse:7.56083
[473]	validation-rmse:7.55989
[474]	validation-rmse:7.55933
[475]	validation-rmse:7.55842
[476]	validation-rmse:7.55739
[477]	validation-rmse:7.55590
[478]	validation-rmse:7.55524
[479]	validation-rmse:7.55471
[480]	validation-rmse:7.55261
[481]	validation-rmse:7.55190
[482]	validation-rmse:7.55162
[483]	validation-rmse:7.55075
[484]	validation-rmse:7.55050
[485]	validation-rmse:7.54944
[486]	validation-rmse:7.54862
[487]	validation-rmse:7.54761
[488]	validation-rmse:7.54527
[489]	validation-rmse:7.54371
[490]	validation-rmse:7.54296
[491]	validation-rmse:7.54274
[492]	validation-rmse:7.54216
[493]	validation-rmse:7.54166
[494]	validation-rmse:7.54093
[495]	validation-rmse:7.53978
[496]	validation-rmse:7.53921
[497]	validation-rmse:7.53877
[498]	validation-rmse:7.53689
[499]	validation-rmse:7.53627
[500]	validation-rmse:7.53606
[501]	validation-rmse:7.53557
[502]	validation-rmse:7.53388
[503]	validation-rmse:7.53352
[504]	validation-rmse:7.53133
[505]	validation-rmse:7.53107
[506]	validation-rmse:7.53063
[507]	validation-rmse:7.53026
[508]	validation-rmse:7.52950
[509]	validation-rmse:7.52908
[510]	validation-rmse:7.52853
[511]	validation-rmse:7.52758
[512]	validation-rmse:7.52726
[513]	validation-rmse:7.52670
[514]	validation-rmse:7.52552
[515]	validation-rmse:7.52464
[516]	validation-rmse:7.52429
[517]	validation-rmse:7.52378
[518]	validation-rmse:7.52294
[519]	validation-rmse:7.52149
[520]	validation-rmse:7.52098
[521]	validation-rmse:7.52043
[522]	validation-rmse:7.52011
[523]	validation-rmse:7.51961
[524]	validation-rmse:7.51882
[525]	validation-rmse:7.51845
[526]	validation-rmse:7.51810
[527]	validation-rmse:7.51747
[528]	validation-rmse:7.51654
[529]	validation-rmse:7.51596
[530]	validation-rmse:7.51547
[531]	validation-rmse:7.51495
[532]	validation-rmse:7.51445
[533]	validation-rmse:7.51215
[534]	validation-rmse:7.51121
[535]	validation-rmse:7.51098
[536]	validation-rmse:7.50947
[537]	validation-rmse:7.50805
[538]	validation-rmse:7.50775
[539]	validation-rmse:7.50726
[540]	validation-rmse:7.50627
[541]	validation-rmse:7.50430
[542]	validation-rmse:7.50344
[543]	validation-rmse:7.50249
[544]	validation-rmse:7.50197
[545]	validation-rmse:7.50139
[546]	validation-rmse:7.49975
[547]	validation-rmse:7.49908
[548]	validation-rmse:7.49702
[549]	validation-rmse:7.49635
[550]	validation-rmse:7.49534
[551]	validation-rmse:7.49453
[552]	validation-rmse:7.49407
[553]	validation-rmse:7.49294
[554]	validation-rmse:7.49191
[555]	validation-rmse:7.49158
[556]	validation-rmse:7.49065
[557]	validation-rmse:7.48998
[558]	validation-rmse:7.48906
[559]	validation-rmse:7.48734
[560]	validation-rmse:7.48602
[561]	validation-rmse:7.48483
[562]	validation-rmse:7.48279
[563]	validation-rmse:7.48098
[564]	validation-rmse:7.48023
[565]	validation-rmse:7.47959
[566]	validation-rmse:7.47818
[567]	validation-rmse:7.47708
[568]	validation-rmse:7.47633
[569]	validation-rmse:7.47484
[570]	validation-rmse:7.47394
[571]	validation-rmse:7.47254
[572]	validation-rmse:7.47026
[573]	validation-rmse:7.46923
[574]	validation-rmse:7.46788
[575]	validation-rmse:7.46640
[576]	validation-rmse:7.46454
[577]	validation-rmse:7.46305
[578]	validation-rmse:7.46215
[579]	validation-rmse:7.46085
[580]	validation-rmse:7.45905
[581]	validation-rmse:7.45728
[582]	validation-rmse:7.45602
[583]	validation-rmse:7.45451
[584]	validation-rmse:7.45285
[585]	validation-rmse:7.45183
[586]	validation-rmse:7.45122
[587]	validation-rmse:7.44964
[588]	validation-rmse:7.44760
[589]	validation-rmse:7.44576
[590]	validation-rmse:7.44389
[591]	validation-rmse:7.44229
[592]	validation-rmse:7.44107
[593]	validation-rmse:7.43905
[594]	validation-rmse:7.43800
[595]	validation-rmse:7.43638
[596]	validation-rmse:7.43558
[597]	validation-rmse:7.43475
[598]	validation-rmse:7.43313
[599]	validation-rmse:7.43240
[600]	validation-rmse:7.43021
[601]	validation-rmse:7.42883
[602]	validation-rmse:7.42814
[603]	validation-rmse:7.42710
[604]	validation-rmse:7.42552
[605]	validation-rmse:7.42411
[606]	validation-rmse:7.42321
[607]	validation-rmse:7.42278
[608]	validation-rmse:7.42150
[609]	validation-rmse:7.41942
[610]	validation-rmse:7.41887
[611]	validation-rmse:7.41832
[612]	validation-rmse:7.41721
[613]	validation-rmse:7.41686
[614]	validation-rmse:7.41557
[615]	validation-rmse:7.41467
[616]	validation-rmse:7.41292
[617]	validation-rmse:7.41254
[618]	validation-rmse:7.41179
[619]	validation-rmse:7.41127
[620]	validation-rmse:7.40969
[621]	validation-rmse:7.40841
[622]	validation-rmse:7.40692
[623]	validation-rmse:7.40624
[624]	validation-rmse:7.40532
[625]	validation-rmse:7.40441
[626]	validation-rmse:7.40321
[627]	validation-rmse:7.40231
[628]	validation-rmse:7.40174
[629]	validation-rmse:7.40033
[630]	validation-rmse:7.39963
[631]	validation-rmse:7.39831
[632]	validation-rmse:7.39786
[633]	validation-rmse:7.39754
[634]	validation-rmse:7.39673
[635]	validation-rmse:7.39568
[636]	validation-rmse:7.39446
[637]	validation-rmse:7.39343
[638]	validation-rmse:7.39219
[639]	validation-rmse:7.39185
[640]	validation-rmse:7.39135
[641]	validation-rmse:7.39034
[642]	validation-rmse:7.38951
[643]	validation-rmse:7.38851
[644]	validation-rmse:7.38760
[645]	validation-rmse:7.38716
[646]	validation-rmse:7.38637
[647]	validation-rmse:7.38592
[648]	validation-rmse:7.38504
[649]	validation-rmse:7.38469
[650]	validation-rmse:7.38447
[651]	validation-rmse:7.38400
[652]	validation-rmse:7.38299
[653]	validation-rmse:7.38217
[654]	validation-rmse:7.38160
[655]	validation-rmse:7.38146
[656]	validation-rmse:7.38137
[657]	validation-rmse:7.38079
[658]	validation-rmse:7.38036
[659]	validation-rmse:7.37958
[660]	validation-rmse:7.37913
[661]	validation-rmse:7.37884
[662]	validation-rmse:7.37828
[663]	validation-rmse:7.37779
[664]	validation-rmse:7.37748
[665]	validation-rmse:7.37711
[666]	validation-rmse:7.37655
[667]	validation-rmse:7.37628
[668]	validation-rmse:7.37579

[13:53:22] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:14.64659
[2]	validation-rmse:12.88729
[3]	validation-rmse:11.73887
[4]	validation-rmse:10.99952
[5]	validation-rmse:10.53792
[6]	validation-rmse:10.18595
[7]	validation-rmse:9.98014
[8]	validation-rmse:9.82432
[9]	validation-rmse:9.72494
[10]	validation-rmse:9.65149
[11]	validation-rmse:9.58866
[12]	validation-rmse:9.52390
[13]	validation-rmse:9.47147
[14]	validation-rmse:9.35442
[15]	validation-rmse:9.32413
[16]	validation-rmse:9.30290
[17]	validation-rmse:9.27976
[18]	validation-rmse:9.25692
[19]	validation-rmse:9.23936
[20]	validation-rmse:9.22236
[21]	validation-rmse:9.20928
[22]	validation-rmse:9.18705
[23]	validation-rmse:9.16846
[24]	validation-rmse:9.15346
[25]	validation-rmse:9.14109
[26]	validation-rmse:9.13508
[27]	validation-rmse:9.08190
[28]	validation-rmse:9.05101
[29]	validation-rmse:9.01903
[30]	validation-rmse:9.01105
[31]	validation-rmse:8.98716
[32]	validation-rmse:8.97554
[33]	validation-rmse:8.96143
[34]	validation-rmse:8.95313
[35]	validation-rmse:8.94395
[36]	validation-rmse:8.93289
[37]	validation-rmse:8.92167
[38]	validation-rmse:8.91107
[39]	validation-rmse:8.90138
[40]	validation-rmse:8.89466
[41]	validation-rmse:8.88487
[42]	validation-rmse:8.87680
[43]	validation-rmse:8.86735
[44]	validation-rmse:8.86036
[45]	validation-rmse:8.84979
[46]	validation-rmse:8.84389
[47]	validation-rmse:8.83301
[48]	validation-rmse:8.82433
[49]	validation-rmse:8.81433
[50]	validation-rmse:8.80268
[51]	validation-rmse:8.79149
[52]	validation-rmse:8.77989
[53]	validation-rmse:8.77003
[54]	validation-rmse:8.76110
[55]	validation-rmse:8.75293
[56]	validation-rmse:8.74244
[57]	validation-rmse:8.73432
[58]	validation-rmse:8.72742
[59]	validation-rmse:8.72183
[60]	validation-rmse:8.71319
[61]	validation-rmse:8.70641
[62]	validation-rmse:8.69953
[63]	validation-rmse:8.69328
[64]	validation-rmse:8.68537
[65]	validation-rmse:8.68033
[66]	validation-rmse:8.66967
[67]	validation-rmse:8.66290
[68]	validation-rmse:8.65433
[69]	validation-rmse:8.64688
[70]	validation-rmse:8.64214
[71]	validation-rmse:8.63647
[72]	validation-rmse:8.63206
[73]	validation-rmse:8.62481
[74]	validation-rmse:8.61968
[75]	validation-rmse:8.61544
[76]	validation-rmse:8.60821
[77]	validation-rmse:8.60259
[78]	validation-rmse:8.59825
[79]	validation-rmse:8.59357
[80]	validation-rmse:8.58782
[81]	validation-rmse:8.57756
[82]	validation-rmse:8.57303
[83]	validation-rmse:8.56946
[84]	validation-rmse:8.56412
[85]	validation-rmse:8.55285
[86]	validation-rmse:8.54659
[87]	validation-rmse:8.54205
[88]	validation-rmse:8.53713
[89]	validation-rmse:8.52907
[90]	validation-rmse:8.52419
[91]	validation-rmse:8.51877
[92]	validation-rmse:8.51687
[93]	validation-rmse:8.50888
[94]	validation-rmse:8.50504
[95]	validation-rmse:8.50062
[96]	validation-rmse:8.49317
[97]	validation-rmse:8.48497
[98]	validation-rmse:8.47954
[99]	validation-rmse:8.47540
[100]	validation-rmse:8.47066
[101]	validation-rmse:8.46548
[102]	validation-rmse:8.45965
[103]	validation-rmse:8.45464
[104]	validation-rmse:8.44806
[105]	validation-rmse:8.44304
[106]	validation-rmse:8.43745
[107]	validation-rmse:8.43218
[108]	validation-rmse:8.42718
[109]	validation-rmse:8.42251
[110]	validation-rmse:8.41794
[111]	validation-rmse:8.41331
[112]	validation-rmse:8.40913
[113]	validation-rmse:8.40660
[114]	validation-rmse:8.40226
[115]	validation-rmse:8.39763
[116]	validation-rmse:8.39350
[117]	validation-rmse:8.38867
[118]	validation-rmse:8.38391
[119]	validation-rmse:8.37990
[120]	validation-rmse:8.37566
[121]	validation-rmse:8.37266
[122]	validation-rmse:8.36916
[123]	validation-rmse:8.36559
[124]	validation-rmse:8.36094
[125]	validation-rmse:8.35809
[126]	validation-rmse:8.35586
[127]	validation-rmse:8.35276
[128]	validation-rmse:8.34922
[129]	validation-rmse:8.34676
[130]	validation-rmse:8.34488
[131]	validation-rmse:8.34119
[132]	validation-rmse:8.33914
[133]	validation-rmse:8.33733
[134]	validation-rmse:8.33401
[135]	validation-rmse:8.33232
[136]	validation-rmse:8.33014
[137]	validation-rmse:8.32745
[138]	validation-rmse:8.32511
[139]	validation-rmse:8.32383
[140]	validation-rmse:8.32211
[141]	validation-rmse:8.31790
[142]	validation-rmse:8.31567
[143]	validation-rmse:8.31160
[144]	validation-rmse:8.30798
[145]	validation-rmse:8.30621
[146]	validation-rmse:8.30420
[147]	validation-rmse:8.30146
[148]	validation-rmse:8.29798
[149]	validation-rmse:8.29270
[150]	validation-rmse:8.28897
[151]	validation-rmse:8.28603
[152]	validation-rmse:8.28187
[153]	validation-rmse:8.27871
[154]	validation-rmse:8.27572
[155]	validation-rmse:8.27266
[156]	validation-rmse:8.26700
[157]	validation-rmse:8.26214
[158]	validation-rmse:8.25842
[159]	validation-rmse:8.25201
[160]	validation-rmse:8.24665
[161]	validation-rmse:8.24380
[162]	validation-rmse:8.23764
[163]	validation-rmse:8.23144
[164]	validation-rmse:8.22593
[165]	validation-rmse:8.22045
[166]	validation-rmse:8.21489
[167]	validation-rmse:8.21016
[168]	validation-rmse:8.20605
[169]	validation-rmse:8.20212
[170]	validation-rmse:8.19729
[171]	validation-rmse:8.19342
[172]	validation-rmse:8.18903
[173]	validation-rmse:8.18584
[174]	validation-rmse:8.18267
[175]	validation-rmse:8.17921
[176]	validation-rmse:8.17454
[177]	validation-rmse:8.17133
[178]	validation-rmse:8.16791
[179]	validation-rmse:8.16316
[180]	validation-rmse:8.15998
[181]	validation-rmse:8.15686
[182]	validation-rmse:8.15491
[183]	validation-rmse:8.15118
[184]	validation-rmse:8.14971
[185]	validation-rmse:8.14788
[186]	validation-rmse:8.14263
[187]	validation-rmse:8.14149
[188]	validation-rmse:8.13941
[189]	validation-rmse:8.13686
[190]	validation-rmse:8.13463
[191]	validation-rmse:8.13357
[192]	validation-rmse:8.13034
[193]	validation-rmse:8.12718
[194]	validation-rmse:8.12215
[195]	validation-rmse:8.12038
[196]	validation-rmse:8.11829
[197]	validation-rmse:8.11611
[198]	validation-rmse:8.11339
[199]	validation-rmse:8.11230
[200]	validation-rmse:8.10988
[201]	validation-rmse:8.10806
[202]	validation-rmse:8.10618
[203]	validation-rmse:8.10304
[204]	validation-rmse:8.10255
[205]	validation-rmse:8.09896
[206]	validation-rmse:8.09657
[207]	validation-rmse:8.09448
[208]	validation-rmse:8.09197
[209]	validation-rmse:8.09104
[210]	validation-rmse:8.08799
[211]	validation-rmse:8.08539
[212]	validation-rmse:8.08418
[213]	validation-rmse:8.08056
[214]	validation-rmse:8.07710
[215]	validation-rmse:8.07413
[216]	validation-rmse:8.07165
[217]	validation-rmse:8.06847
[218]	validation-rmse:8.06666
[219]	validation-rmse:8.06426
[220]	validation-rmse:8.06221
[221]	validation-rmse:8.05523
[222]	validation-rmse:8.05227
[223]	validation-rmse:8.05049
[224]	validation-rmse:8.04609
[225]	validation-rmse:8.04337
[226]	validation-rmse:8.04168
[227]	validation-rmse:8.03942
[228]	validation-rmse:8.03575
[229]	validation-rmse:8.02955
[230]	validation-rmse:8.02405
[231]	validation-rmse:8.02028
[232]	validation-rmse:8.01700
[233]	validation-rmse:8.01350
[234]	validation-rmse:8.01011
[235]	validation-rmse:8.00576
[236]	validation-rmse:8.00468
[237]	validation-rmse:8.00026
[238]	validation-rmse:7.99579
[239]	validation-rmse:7.98850
[240]	validation-rmse:7.98657
[241]	validation-rmse:7.98264
[242]	validation-rmse:7.97939
[243]	validation-rmse:7.97705
[244]	validation-rmse:7.97240
[245]	validation-rmse:7.96949
[246]	validation-rmse:7.96287
[247]	validation-rmse:7.95928
[248]	validation-rmse:7.95619
[249]	validation-rmse:7.95211
[250]	validation-rmse:7.94906
[251]	validation-rmse:7.94722
[252]	validation-rmse:7.94302
[253]	validation-rmse:7.94025
[254]	validation-rmse:7.93922
[255]	validation-rmse:7.93647
[256]	validation-rmse:7.93277
[257]	validation-rmse:7.93005
[258]	validation-rmse:7.92798
[259]	validation-rmse:7.92392
[260]	validation-rmse:7.91816
[261]	validation-rmse:7.91494
[262]	validation-rmse:7.91218
[263]	validation-rmse:7.90863
[264]	validation-rmse:7.90687
[265]	validation-rmse:7.90437
[266]	validation-rmse:7.90124
[267]	validation-rmse:7.89774
[268]	validation-rmse:7.89442
[269]	validation-rmse:7.89068
[270]	validation-rmse:7.88693
[271]	validation-rmse:7.88451
[272]	validation-rmse:7.88066
[273]	validation-rmse:7.87817
[274]	validation-rmse:7.87431
[275]	validation-rmse:7.87192
[276]	validation-rmse:7.87103
[277]	validation-rmse:7.86928
[278]	validation-rmse:7.86730
[279]	validation-rmse:7.86514
[280]	validation-rmse:7.86341
[281]	validation-rmse:7.86041
[282]	validation-rmse:7.85876
[283]	validation-rmse:7.85639
[284]	validation-rmse:7.85555
[285]	validation-rmse:7.85355
[286]	validation-rmse:7.85224
[287]	validation-rmse:7.85095
[288]	validation-rmse:7.85001
[289]	validation-rmse:7.84591
[290]	validation-rmse:7.84491
[291]	validation-rmse:7.84439
[292]	validation-rmse:7.84368
[293]	validation-rmse:7.84277
[294]	validation-rmse:7.84058
[295]	validation-rmse:7.83926
[296]	validation-rmse:7.83651
[297]	validation-rmse:7.83556
[298]	validation-rmse:7.83488
[299]	validation-rmse:7.83288
[300]	validation-rmse:7.83137
[301]	validation-rmse:7.82995
[302]	validation-rmse:7.82792
[303]	validation-rmse:7.82641
[304]	validation-rmse:7.82527
[305]	validation-rmse:7.82279
[306]	validation-rmse:7.82174
[307]	validation-rmse:7.82026
[308]	validation-rmse:7.81787
[309]	validation-rmse:7.81678
[310]	validation-rmse:7.81552
[311]	validation-rmse:7.81436
[312]	validation-rmse:7.81244
[313]	validation-rmse:7.81178
[314]	validation-rmse:7.81017
[315]	validation-rmse:7.80904
[316]	validation-rmse:7.80766
[317]	validation-rmse:7.80614
[318]	validation-rmse:7.80477
[319]	validation-rmse:7.80361
[320]	validation-rmse:7.80189
[321]	validation-rmse:7.80121
[322]	validation-rmse:7.79945
[323]	validation-rmse:7.79944
[324]	validation-rmse:7.79795
[325]	validation-rmse:7.79610
[326]	validation-rmse:7.79459
[327]	validation-rmse:7.79408
[328]	validation-rmse:7.79299
[329]	validation-rmse:7.79199
[330]	validation-rmse:7.79118
[331]	validation-rmse:7.79042
[332]	validation-rmse:7.78963
[333]	validation-rmse:7.78905
[334]	validation-rmse:7.78810
[335]	validation-rmse:7.78743
[336]	validation-rmse:7.78581
[337]	validation-rmse:7.78559
[338]	validation-rmse:7.78494
[339]	validation-rmse:7.78351
[340]	validation-rmse:7.77980
[341]	validation-rmse:7.77907
[342]	validation-rmse:7.77724
[343]	validation-rmse:7.77599
[344]	validation-rmse:7.77392
[345]	validation-rmse:7.77252
[346]	validation-rmse:7.76801
[347]	validation-rmse:7.76667
[348]	validation-rmse:7.76430
[349]	validation-rmse:7.76223
[350]	validation-rmse:7.76056
[351]	validation-rmse:7.75861
[352]	validation-rmse:7.75719
[353]	validation-rmse:7.75623
[354]	validation-rmse:7.75566
[355]	validation-rmse:7.75499
[356]	validation-rmse:7.75411
[357]	validation-rmse:7.75276
[358]	validation-rmse:7.75093
[359]	validation-rmse:7.74927
[360]	validation-rmse:7.74759
[361]	validation-rmse:7.74562
[362]	validation-rmse:7.74443
[363]	validation-rmse:7.74323
[364]	validation-rmse:7.74128
[365]	validation-rmse:7.73971
[366]	validation-rmse:7.73759
[367]	validation-rmse:7.73598
[368]	validation-rmse:7.73619
[369]	validation-rmse:7.73559
[370]	validation-rmse:7.73154
[371]	validation-rmse:7.73067
[372]	validation-rmse:7.72906
[373]	validation-rmse:7.72755
[374]	validation-rmse:7.72565
[375]	validation-rmse:7.72446
[376]	validation-rmse:7.72372
[377]	validation-rmse:7.72193
[378]	validation-rmse:7.71864
[379]	validation-rmse:7.71749
[380]	validation-rmse:7.71603
[381]	validation-rmse:7.71597
[382]	validation-rmse:7.71491
[383]	validation-rmse:7.71450
[384]	validation-rmse:7.71290
[385]	validation-rmse:7.71252
[386]	validation-rmse:7.71154
[387]	validation-rmse:7.70954
[388]	validation-rmse:7.70908
[389]	validation-rmse:7.70836
[390]	validation-rmse:7.70751
[391]	validation-rmse:7.70701
[392]	validation-rmse:7.70625
[393]	validation-rmse:7.70568
[394]	validation-rmse:7.70419
[395]	validation-rmse:7.70343
[396]	validation-rmse:7.70147
[397]	validation-rmse:7.70066
[398]	validation-rmse:7.70029
[399]	validation-rmse:7.69961
[400]	validation-rmse:7.69906
[401]	validation-rmse:7.69870
[402]	validation-rmse:7.69795
[403]	validation-rmse:7.69570
[404]	validation-rmse:7.69508
[405]	validation-rmse:7.69509
[406]	validation-rmse:7.69405
[407]	validation-rmse:7.69274
[408]	validation-rmse:7.69141
[409]	validation-rmse:7.69079
[410]	validation-rmse:7.68943
[411]	validation-rmse:7.68827
[412]	validation-rmse:7.68758
[413]	validation-rmse:7.68752
[414]	validation-rmse:7.68591
[415]	validation-rmse:7.68433
[416]	validation-rmse:7.68369
[417]	validation-rmse:7.68271
[418]	validation-rmse:7.68107
[419]	validation-rmse:7.68115
[420]	validation-rmse:7.67967
[421]	validation-rmse:7.67772
[422]	validation-rmse:7.67700
[423]	validation-rmse:7.67559
[424]	validation-rmse:7.67510
[425]	validation-rmse:7.67452
[426]	validation-rmse:7.67427
[427]	validation-rmse:7.67356
[428]	validation-rmse:7.67250
[429]	validation-rmse:7.67046
[430]	validation-rmse:7.67077
[431]	validation-rmse:7.67061
[432]	validation-rmse:7.67016
[433]	validation-rmse:7.66966
[434]	validation-rmse:7.66915
[435]	validation-rmse:7.66870
[436]	validation-rmse:7.66826
[437]	validation-rmse:7.66767
[438]	validation-rmse:7.66692
[439]	validation-rmse:7.66554
[440]	validation-rmse:7.66510
[441]	validation-rmse:7.66393
[442]	validation-rmse:7.66289
[443]	validation-rmse:7.66177
[444]	validation-rmse:7.66070
[445]	validation-rmse:7.65819
[446]	validation-rmse:7.65721
[447]	validation-rmse:7.65642
[448]	validation-rmse:7.65601
[449]	validation-rmse:7.65505
[450]	validation-rmse:7.65434
[451]	validation-rmse:7.65429
[452]	validation-rmse:7.65353
[453]	validation-rmse:7.65214
[454]	validation-rmse:7.65144
[455]	validation-rmse:7.65178
[456]	validation-rmse:7.65107
[457]	validation-rmse:7.65052
[458]	validation-rmse:7.64992
[459]	validation-rmse:7.64911
[460]	validation-rmse:7.64791
[461]	validation-rmse:7.64704
[462]	validation-rmse:7.64581
[463]	validation-rmse:7.64522
[464]	validation-rmse:7.64366
[465]	validation-rmse:7.64196
[466]	validation-rmse:7.64062
[467]	validation-rmse:7.63978
[468]	validation-rmse:7.64007
[469]	validation-rmse:7.63927
[470]	validation-rmse:7.63843
[471]	validation-rmse:7.63794
[472]	validation-rmse:7.63736
[473]	validation-rmse:7.63685
[474]	validation-rmse:7.63474
[475]	validation-rmse:7.63422
[476]	validation-rmse:7.63241
[477]	validation-rmse:7.63119
[478]	validation-rmse:7.63043
[479]	validation-rmse:7.62994
[480]	validation-rmse:7.62836
[481]	validation-rmse:7.62678
[482]	validation-rmse:7.62610
[483]	validation-rmse:7.62565
[484]	validation-rmse:7.62536
[485]	validation-rmse:7.62438
[486]	validation-rmse:7.62249
[487]	validation-rmse:7.62181
[488]	validation-rmse:7.62003
[489]	validation-rmse:7.61915
[490]	validation-rmse:7.61916
[491]	validation-rmse:7.61819
[492]	validation-rmse:7.61821
[493]	validation-rmse:7.61720
[494]	validation-rmse:7.61628
[495]	validation-rmse:7.61554
[496]	validation-rmse:7.61460
[497]	validation-rmse:7.61396
[498]	validation-rmse:7.61402
[499]	validation-rmse:7.61332
[500]	validation-rmse:7.61280
[501]	validation-rmse:7.61151
[502]	validation-rmse:7.61077
[503]	validation-rmse:7.60991
[504]	validation-rmse:7.60966
[505]	validation-rmse:7.60977
[506]	validation-rmse:7.60970
[507]	validation-rmse:7.60975
[508]	validation-rmse:7.60863
[509]	validation-rmse:7.60833
[510]	validation-rmse:7.60790
[511]	validation-rmse:7.60640
[512]	validation-rmse:7.60554
[513]	validation-rmse:7.60290
[514]	validation-rmse:7.60270
[515]	validation-rmse:7.60229
[516]	validation-rmse:7.60128
[517]	validation-rmse:7.60095
[518]	validation-rmse:7.60037
[519]	validation-rmse:7.59953
[520]	validation-rmse:7.59869
[521]	validation-rmse:7.59833
[522]	validation-rmse:7.59821
[523]	validation-rmse:7.59761
[524]	validation-rmse:7.59712
[525]	validation-rmse:7.59642
[526]	validation-rmse:7.59582
[527]	validation-rmse:7.59470
[528]	validation-rmse:7.59305
[529]	validation-rmse:7.59147
[530]	validation-rmse:7.59056
[531]	validation-rmse:7.58847
[532]	validation-rmse:7.58757
[533]	validation-rmse:7.58712
[534]	validation-rmse:7.58613
[535]	validation-rmse:7.58438
[536]	validation-rmse:7.58265
[537]	validation-rmse:7.58101
[538]	validation-rmse:7.57995
[539]	validation-rmse:7.57889
[540]	validation-rmse:7.57835
[541]	validation-rmse:7.57615
[542]	validation-rmse:7.57451
[543]	validation-rmse:7.57326
[544]	validation-rmse:7.57246
[545]	validation-rmse:7.57178
[546]	validation-rmse:7.57045
[547]	validation-rmse:7.56952
[548]	validation-rmse:7.56777
[549]	validation-rmse:7.56692
[550]	validation-rmse:7.56626
[551]	validation-rmse:7.56555
[552]	validation-rmse:7.56548
[553]	validation-rmse:7.56392
[554]	validation-rmse:7.56376
[555]	validation-rmse:7.56287
[556]	validation-rmse:7.56167
[557]	validation-rmse:7.56048
[558]	validation-rmse:7.55987
[559]	validation-rmse:7.55937
[560]	validation-rmse:7.55779
[561]	validation-rmse:7.55734
[562]	validation-rmse:7.55682
[563]	validation-rmse:7.55613
[564]	validation-rmse:7.55594
[565]	validation-rmse:7.55502
[566]	validation-rmse:7.55508
[567]	validation-rmse:7.55415
[568]	validation-rmse:7.55351
[569]	validation-rmse:7.55288
[570]	validation-rmse:7.55229
[571]	validation-rmse:7.55194
[572]	validation-rmse:7.55043
[573]	validation-rmse:7.54840
[574]	validation-rmse:7.54805
[575]	validation-rmse:7.54760
[576]	validation-rmse:7.54726
[577]	validation-rmse:7.54583
[578]	validation-rmse:7.54571
[579]	validation-rmse:7.54516
[580]	validation-rmse:7.54456
[581]	validation-rmse:7.54434
[582]	validation-rmse:7.54320
[583]	validation-rmse:7.54316
[584]	validation-rmse:7.54260
[585]	validation-rmse:7.54240
[586]	validation-rmse:7.54132
[587]	validation-rmse:7.54080
[588]	validation-rmse:7.54016
[589]	validation-rmse:7.53952
[590]	validation-rmse:7.53888
[591]	validation-rmse:7.53818
[592]	validation-rmse:7.53755
[593]	validation-rmse:7.53688
[594]	validation-rmse:7.53690
[595]	validation-rmse:7.53643
[596]	validation-rmse:7.53488
[597]	validation-rmse:7.53399
[598]	validation-rmse:7.53302
[599]	validation-rmse:7.53233
[600]	validation-rmse:7.53195
[601]	validation-rmse:7.53170
[602]	validation-rmse:7.53120
[603]	validation-rmse:7.53087
[604]	validation-rmse:7.53083
[605]	validation-rmse:7.53001
[606]	validation-rmse:7.52959
[607]	validation-rmse:7.52920
[608]	validation-rmse:7.52891
[609]	validation-rmse:7.52855
[610]	validation-rmse:7.52781
[611]	validation-rmse:7.52776
[612]	validation-rmse:7.52587
[613]	validation-rmse:7.52558
[614]	validation-rmse:7.52535
[615]	validation-rmse:7.52447
[616]	validation-rmse:7.52425
[617]	validation-rmse:7.52402
[618]	validation-rmse:7.52391
[619]	validation-rmse:7.52380
[620]	validation-rmse:7.52296
[621]	validation-rmse:7.52211
[622]	validation-rmse:7.52138
[623]	validation-rmse:7.52120
[624]	validation-rmse:7.52064
[625]	validation-rmse:7.51994
[626]	validation-rmse:7.51843
[627]	validation-rmse:7.51853
[628]	validation-rmse:7.51758
[629]	validation-rmse:7.51609
[630]	validation-rmse:7.51485
[631]	validation-rmse:7.51298
[632]	validation-rmse:7.51294
[633]	validation-rmse:7.51224
[634]	validation-rmse:7.51218
[635]	validation-rmse:7.51142
[636]	validation-rmse:7.51052
[637]	validation-rmse:7.51045
[638]	validation-rmse:7.50912
[639]	validation-rmse:7.50856
[640]	validation-rmse:7.50828
[641]	validation-rmse:7.50823
[642]	validation-rmse:7.50688
[643]	validation-rmse:7.50645
[644]	validation-rmse:7.50614
[645]	validation-rmse:7.50618
[646]	validation-rmse:7.50498
[647]	validation-rmse:7.50435
[648]	validation-rmse:7.50410
[649]	validation-rmse:7.50406
[650]	validation-rmse:7.50381
[651]	validation-rmse:7.50307
[652]	validation-rmse:7.50190
[653]	validation-rmse:7.50062
[654]	validation-rmse:7.50094
[655]	validation-rmse:7.49989
[656]	validation-rmse:7.49954
[657]	validation-rmse:7.49978
[658]	validation-rmse:7.49945
[659]	validation-rmse:7.49904
[660]	validation-rmse:7.49822
[661]	validation-rmse:7.49673
[662]	validation-rmse:7.49594
[663]	validation-rmse:7.49555
[664]	validation-rmse:7.49487
[665]	validation-rmse:7.49409
[666]	validation-rmse:7.49465
[667]	validation-rmse:7.49463
[668]	validation-rmse:7.49395
[669]	validation-rmse:7.49384
[670]	validation-rmse:7.49372

[13:55:52] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[0]	validation-rmse:13.24266
[1]	validation-rmse:10.45889
[2]	validation-rmse:9.57758
[3]	validation-rmse:9.05235
[4]	validation-rmse:8.83081
[5]	validation-rmse:8.73309
[6]	validation-rmse:8.57889
[7]	validation-rmse:8.52378
[8]	validation-rmse:8.48277
[9]	validation-rmse:8.44458
[10]	validation-rmse:8.41822
[11]	validation-rmse:8.39441
[12]	validation-rmse:8.37086
[13]	validation-rmse:8.34890
[14]	validation-rmse:8.33375
[15]	validation-rmse:8.30538
[16]	validation-rmse:8.28742
[17]	validation-rmse:8.26902
[18]	validation-rmse:8.25600
[19]	validation-rmse:8.23632
[20]	validation-rmse:8.21313
[21]	validation-rmse:8.19588
[22]	validation-rmse:8.18451
[23]	validation-rmse:8.17060
[24]	validation-rmse:8.15238
[25]	validation-rmse:8.13799
[26]	validation-rmse:8.12728
[27]	validation-rmse:8.11554
[28]	validation-rmse:8.10962
[29]	validation-rmse:8.09081
[30]	validation-rmse:8.08071
[31]	validation-rmse:8.07079
[32]	validation-rmse:8.05897
[33]	validation-rmse:8.05119
[34]	validation-rmse:8.04424
[35]	validation-rmse:8.02919
[36]	validation-rmse:8.02326
[37]	validation-rmse:8.01372
[38]	validation-rmse:8.00536
[39]	validation-rmse:7.99026
[40]	validation-rmse:7.98696
[41]	validation-rmse:7.97239
[42]	validation-rmse:7.96556
[43]	validation-rmse:7.95637
[44]	validation-rmse:7.94842
[45]	validation-rmse:7.93972
[46]	validation-rmse:7.93497
[47]	validation-rmse:7.92889
[48]	validation-rmse:7.92185
[49]	validation-rmse:7.91604
[50]	validation-rmse:7.91160
[51]	validation-rmse:7.90219
[52]	validation-rmse:7.89865
[53]	validation-rmse:7.89496
[54]	validation-rmse:7.88831
[55]	validation-rmse:7.88714
[56]	validation-rmse:7.88184
[57]	validation-rmse:7.87801
[58]	validation-rmse:7.87166
[59]	validation-rmse:7.86679
[60]	validation-rmse:7.86377
[61]	validation-rmse:7.85691
[62]	validation-rmse:7.85154
[63]	validation-rmse:7.84440
[64]	validation-rmse:7.84148
[65]	validation-rmse:7.83660
[66]	validation-rmse:7.82733
[67]	validation-rmse:7.82067
[68]	validation-rmse:7.81589
[69]	validation-rmse:7.80874
[70]	validation-rmse:7.80280
[71]	validation-rmse:7.78947
[72]	validation-rmse:7.78242
[73]	validation-rmse:7.77599
[74]	validation-rmse:7.76786
[75]	validation-rmse:7.75646
[76]	validation-rmse:7.75475
[77]	validation-rmse:7.74906
[78]	validation-rmse:7.74447
[79]	validation-rmse:7.73858
[80]	validation-rmse:7.73564
[81]	validation-rmse:7.73059
[82]	validation-rmse:7.72864
[83]	validation-rmse:7.72685
[84]	validation-rmse:7.72277
[85]	validation-rmse:7.71927
[86]	validation-rmse:7.71710
[87]	validation-rmse:7.71584
[88]	validation-rmse:7.71086
[89]	validation-rmse:7.70612
[90]	validation-rmse:7.70366
[91]	validation-rmse:7.70089
[92]	validation-rmse:7.69620
[93]	validation-rmse:7.68507
[94]	validation-rmse:7.68553
[95]	validation-rmse:7.68195
[96]	validation-rmse:7.67831
[97]	validation-rmse:7.67160
[98]	validation-rmse:7.66713
[99]	validation-rmse:7.65582
[100]	validation-rmse:7.64942
[101]	validation-rmse:7.64395
[102]	validation-rmse:7.63632
[103]	validation-rmse:7.62966
[104]	validation-rmse:7.62353
[105]	validation-rmse:7.61888
[106]	validation-rmse:7.61830
[107]	validation-rmse:7.61110
[108]	validation-rmse:7.60770
[109]	validation-rmse:7.60500
[110]	validation-rmse:7.60169
[111]	validation-rmse:7.59638
[112]	validation-rmse:7.59602
[113]	validation-rmse:7.59197
[114]	validation-rmse:7.59211
[115]	validation-rmse:7.58826
[116]	validation-rmse:7.58651
[117]	validation-rmse:7.58338
[118]	validation-rmse:7.57913
[119]	validation-rmse:7.57669
[120]	validation-rmse:7.57305
[121]	validation-rmse:7.57258
[122]	validation-rmse:7.56908
[123]	validation-rmse:7.56858
[124]	validation-rmse:7.56643
[125]	validation-rmse:7.56316
[126]	validation-rmse:7.56124
[127]	validation-rmse:7.56071
[128]	validation-rmse:7.55749
[129]	validation-rmse:7.55582
[130]	validation-rmse:7.55069
[131]	validation-rmse:7.54814
[132]	validation-rmse:7.54564
[133]	validation-rmse:7.54463
[134]	validation-rmse:7.54363
[135]	validation-rmse:7.54076
[136]	validation-rmse:7.53734
[137]	validation-rmse:7.53638
[138]	validation-rmse:7.53603
[139]	validation-rmse:7.53268
[140]	validation-rmse:7.53141
[141]	validation-rmse:7.52934
[142]	validation-rmse:7.52787
[143]	validation-rmse:7.52613
[144]	validation-rmse:7.52224
[145]	validation-rmse:7.52039
[146]	validation-rmse:7.51847
[147]	validation-rmse:7.51746
[148]	validation-rmse:7.51009
[149]	validation-rmse:7.50701
[150]	validation-rmse:7.50183
[151]	validation-rmse:7.49830
[152]	validation-rmse:7.49600
[153]	validation-rmse:7.49302
[154]	validation-rmse:7.49047
[155]	validation-rmse:7.48869
[156]	validation-rmse:7.48609
[157]	validation-rmse:7.48300
[158]	validation-rmse:7.48161
[159]	validation-rmse:7.48045
[160]	validation-rmse:7.47765
[161]	validation-rmse:7.46879
[162]	validation-rmse:7.45817
[163]	validation-rmse:7.45724
[164]	validation-rmse:7.45354
[165]	validation-rmse:7.45288
[166]	validation-rmse:7.45082
[167]	validation-rmse:7.44780
[168]	validation-rmse:7.44512
[169]	validation-rmse:7.44364
[170]	validation-rmse:7.44347
[171]	validation-rmse:7.44011
[172]	validation-rmse:7.43856
[173]	validation-rmse:7.43821
[174]	validation-rmse:7.43665
[175]	validation-rmse:7.43708
[176]	validation-rmse:7.43596
[177]	validation-rmse:7.43249
[178]	validation-rmse:7.42933
[179]	validation-rmse:7.42599
[180]	validation-rmse:7.42355
[181]	validation-rmse:7.42342
[182]	validation-rmse:7.42146
[183]	validation-rmse:7.41933
[184]	validation-rmse:7.41579
[185]	validation-rmse:7.41527
[186]	validation-rmse:7.41402
[187]	validation-rmse:7.41238
[188]	validation-rmse:7.40724
[189]	validation-rmse:7.40577
[190]	validation-rmse:7.40631
[191]	validation-rmse:7.40361
[192]	validation-rmse:7.40215
[193]	validation-rmse:7.39992
[194]	validation-rmse:7.39809
[195]	validation-rmse:7.39481
[196]	validation-rmse:7.39185
[197]	validation-rmse:7.38928
[198]	validation-rmse:7.39017
[199]	validation-rmse:7.38863
[200]	validation-rmse:7.38622
[201]	validation-rmse:7.38640
[202]	validation-rmse:7.38600
[203]	validation-rmse:7.38502
[204]	validation-rmse:7.38213
[205]	validation-rmse:7.38119
[206]	validation-rmse:7.38007
[207]	validation-rmse:7.37865
[208]	validation-rmse:7.37675
[209]	validation-rmse:7.37595
[210]	validation-rmse:7.37583
[211]	validation-rmse:7.36884
[212]	validation-rmse:7.36736
[213]	validation-rmse:7.36444
[214]	validation-rmse:7.36560
[215]	validation-rmse:7.36420
[216]	validation-rmse:7.36121
[217]	validation-rmse:7.36085
[218]	validation-rmse:7.35902
[219]	validation-rmse:7.35759
[220]	validation-rmse:7.35569
[221]	validation-rmse:7.35283
[222]	validation-rmse:7.34978
[223]	validation-rmse:7.34960
[224]	validation-rmse:7.34775
[225]	validation-rmse:7.34589
[226]	validation-rmse:7.34453
[227]	validation-rmse:7.34280
[228]	validation-rmse:7.34082
[229]	validation-rmse:7.33985
[230]	validation-rmse:7.33810
[231]	validation-rmse:7.33674
[232]	validation-rmse:7.33510
[233]	validation-rmse:7.33452
[234]	validation-rmse:7.33407
[235]	validation-rmse:7.33356
[236]	validation-rmse:7.33235
[237]	validation-rmse:7.32982
[238]	validation-rmse:7.32864
[239]	validation-rmse:7.32719
[240]	validation-rmse:7.32695
[241]	validation-rmse:7.32610
[242]	validation-rmse:7.32269
[243]	validation-rmse:7.32212
[244]	validation-rmse:7.32153
[245]	validation-rmse:7.32106
[246]	validation-rmse:7.32053
[247]	validation-rmse:7.31939
[248]	validation-rmse:7.31930
[249]	validation-rmse:7.31750
[250]	validation-rmse:7.31780
[251]	validation-rmse:7.31638
[252]	validation-rmse:7.31501
[253]	validation-rmse:7.31379
[254]	validation-rmse:7.31019
[255]	validation-rmse:7.31027
[256]	validation-rmse:7.30920
[257]	validation-rmse:7.30825
[258]	validation-rmse:7.30755
[259]	validation-rmse:7.30605
[260]	validation-rmse:7.30444
[261]	validation-rmse:7.30462
[262]	validation-rmse:7.30395
[263]	validation-rmse:7.30015
[264]	validation-rmse:7.29964
[265]	validation-rmse:7.29998
[266]	validation-rmse:7.29857
[267]	validation-rmse:7.29800
[268]	validation-rmse:7.29740
[269]	validation-rmse:7.29752
[270]	validation-rmse:7.29129
[271]	validation-rmse:7.29081
[272]	validation-rmse:7.29046
[273]	validation-rmse:7.29069
[274]	validation-rmse:7.28814
[275]	validation-rmse:7.28914
[276]	validation-rmse:7.28769
[277]	validation-rmse:7.28672
[278]	validation-rmse:7.28505
[279]	validation-rmse:7.28484
[280]	validation-rmse:7.28214
[281]	validation-rmse:7.28221
[282]	validation-rmse:7.28085
[283]	validation-rmse:7.27858
[284]	validation-rmse:7.27581
[285]	validation-rmse:7.27417
[286]	validation-rmse:7.27155
[287]	validation-rmse:7.27173
[288]	validation-rmse:7.27147
[289]	validation-rmse:7.27187
[290]	validation-rmse:7.27173
[291]	validation-rmse:7.27132
[292]	validation-rmse:7.27151
[293]	validation-rmse:7.27092
[294]	validation-rmse:7.26935
[295]	validation-rmse:7.26829
[296]	validation-rmse:7.26441
[297]	validation-rmse:7.26379
[298]	validation-rmse:7.26316
[299]	validation-rmse:7.26207
[300]	validation-rmse:7.26041
[301]	validation-rmse:7.25823
[302]	validation-rmse:7.25656
[303]	validation-rmse:7.25613
[304]	validation-rmse:7.25456
[305]	validation-rmse:7.25370
[306]	validation-rmse:7.25384
[307]	validation-rmse:7.25395
[308]	validation-rmse:7.25459
[309]	validation-rmse:7.25507
[310]	validation-rmse:7.25359
[311]	validation-rmse:7.25238
[312]	validation-rmse:7.25163
[313]	validation-rmse:7.25244
[314]	validation-rmse:7.25038
[315]	validation-rmse:7.25014
[316]	validation-rmse:7.24978
[317]	validation-rmse:7.24770
[318]	validation-rmse:7.24769
[319]	validation-rmse:7.24724
[320]	validation-rmse:7.24582
[321]	validation-rmse:7.24542
[322]	validation-rmse:7.24418
[323]	validation-rmse:7.24419
[324]	validation-rmse:7.24434
[325]	validation-rmse:7.24387
[326]	validation-rmse:7.24303
[327]	validation-rmse:7.24306
[328]	validation-rmse:7.24071
[329]	validation-rmse:7.23886
[330]	validation-rmse:7.23667
[331]	validation-rmse:7.23762
[332]	validation-rmse:7.23762
[333]	validation-rmse:7.23650
[334]	validation-rmse:7.23567
[335]	validation-rmse:7.23510
[336]	validation-rmse:7.23555
[337]	validation-rmse:7.23417
[338]	validation-rmse:7.23378
[339]	validation-rmse:7.23299
[340]	validation-rmse:7.23173
[341]	validation-rmse:7.23109
[342]	validation-rmse:7.23122
[343]	validation-rmse:7.23064
[344]	validation-rmse:7.22868
[345]	validation-rmse:7.22707
[346]	validation-rmse:7.22740
[347]	validation-rmse:7.22622
[348]	validation-rmse:7.22510
[349]	validation-rmse:7.22374
[350]	validation-rmse:7.22433
[351]	validation-rmse:7.22321
[352]	validation-rmse:7.22210
[353]	validation-rmse:7.22178
[354]	validation-rmse:7.22311
[355]	validation-rmse:7.22014
[356]	validation-rmse:7.21881
[357]	validation-rmse:7.21853
[358]	validation-rmse:7.21614
[359]	validation-rmse:7.21590
[360]	validation-rmse:7.21562
[361]	validation-rmse:7.21437
[362]	validation-rmse:7.21387
[363]	validation-rmse:7.21395
[364]	validation-rmse:7.21214
[365]	validation-rmse:7.21066
[366]	validation-rmse:7.21017
[367]	validation-rmse:7.21025
[368]	validation-rmse:7.20915
[369]	validation-rmse:7.20806
[370]	validation-rmse:7.20701
[371]	validation-rmse:7.20518
[372]	validation-rmse:7.20519
[373]	validation-rmse:7.20478
[374]	validation-rmse:7.20417
[375]	validation-rmse:7.20387
[376]	validation-rmse:7.20461
[377]	validation-rmse:7.20403
[378]	validation-rmse:7.20279
[379]	validation-rmse:7.20244
[380]	validation-rmse:7.20282
[381]	validation-rmse:7.20143
[382]	validation-rmse:7.20006
[383]	validation-rmse:7.19907
[384]	validation-rmse:7.19926
[385]	validation-rmse:7.19845
[386]	validation-rmse:7.19784
[387]	validation-rmse:7.19770
[388]	validation-rmse:7.19786
[389]	validation-rmse:7.19730
[390]	validation-rmse:7.19631
[391]	validation-rmse:7.19585
[392]	validation-rmse:7.19485
[393]	validation-rmse:7.19523
[394]	validation-rmse:7.19467
[395]	validation-rmse:7.19508
[396]	validation-rmse:7.19428
[397]	validation-rmse:7.19461
[398]	validation-rmse:7.19451
[399]	validation-rmse:7.19462
[400]	validation-rmse:7.19299
[401]	validation-rmse:7.19241
[402]	validation-rmse:7.19154
[403]	validation-rmse:7.19136
[404]	validation-rmse:7.19096
[405]	validation-rmse:7.19031
[406]	validation-rmse:7.18960
[407]	validation-rmse:7.19025
[408]	validation-rmse:7.18862
[409]	validation-rmse:7.18787
[410]	validation-rmse:7.18742
[411]	validation-rmse:7.18682
[412]	validation-rmse:7.18572
[413]	validation-rmse:7.18432
[414]	validation-rmse:7.18354
[415]	validation-rmse:7.18350
[416]	validation-rmse:7.18107
[417]	validation-rmse:7.18102
[418]	validation-rmse:7.18055
[419]	validation-rmse:7.18022
[420]	validation-rmse:7.18061
[421]	validation-rmse:7.18022
[422]	validation-rmse:7.17908
[423]	validation-rmse:7.17927
[424]	validation-rmse:7.17894
[425]	validation-rmse:7.17822
[426]	validation-rmse:7.17729
[427]	validation-rmse:7.17677
[428]	validation-rmse:7.17680
[429]	validation-rmse:7.17655
[430]	validation-rmse:7.17595
[431]	validation-rmse:7.17475
[432]	validation-rmse:7.17392
[433]	validation-rmse:7.17351
[434]	validation-rmse:7.17274
[435]	validation-rmse:7.17258
[436]	validation-rmse:7.17262
[437]	validation-rmse:7.17266
[438]	validation-rmse:7.17280
[439]	validation-rmse:7.17209
[440]	validation-rmse:7.17041
[441]	validation-rmse:7.16940
[442]	validation-rmse:7.16854
[443]	validation-rmse:7.16843
[444]	validation-rmse:7.16874
[445]	validation-rmse:7.16878
[446]	validation-rmse:7.16772
[447]	validation-rmse:7.16742
[448]	validation-rmse:7.16779
[449]	validation-rmse:7.16597
[450]	validation-rmse:7.16567
[451]	validation-rmse:7.16494
[452]	validation-rmse:7.16413
[453]	validation-rmse:7.16418
[454]	validation-rmse:7.16358
[455]	validation-rmse:7.16485
[456]	validation-rmse:7.16390
[457]	validation-rmse:7.16373
[458]	validation-rmse:7.16330
[459]	validation-rmse:7.16242
[460]	validation-rmse:7.16171
[461]	validation-rmse:7.16133
[462]	validation-rmse:7.16120
[463]	validation-rmse:7.16061
[464]	validation-rmse:7.15980
[465]	validation-rmse:7.15985
[466]	validation-rmse:7.15889
[467]	validation-rmse:7.15897
[468]	validation-rmse:7.15861
[469]	validation-rmse:7.15806
[470]	validation-rmse:7.15784
[471]	validation-rmse:7.15705
[472]	validation-rmse:7.15769
[473]	validation-rmse:7.15797
[474]	validation-rmse:7.15741
[475]	validation-rmse:7.15649
[476]	validation-rmse:7.15603
[477]	validation-rmse:7.15471
[478]	validation-rmse:7.15476
[479]	validation-rmse:7.15484
[480]	validation-rmse:7.15418
[481]	validation-rmse:7.15432
[482]	validation-rmse:7.15292
[483]	validation-rmse:7.15255
[484]	validation-rmse:7.15239
[485]	validation-rmse:7.15255
[486]	validation-rmse:7.15245
[487]	validation-rmse:7.15240
[488]	validation-rmse:7.15196
[489]	validation-rmse:7.15195
[490]	validation-rmse:7.15200
[491]	validation-rmse:7.15211
[492]	validation-rmse:7.15259
[493]	validation-rmse:7.15196
[494]	validation-rmse:7.15048
[495]	validation-rmse:7.15085
[496]	validation-rmse:7.15036
[497]	validation-rmse:7.15023
[498]	validation-rmse:7.14939
[499]	validation-rmse:7.14859
[500]	validation-rmse:7.14814
[501]	validation-rmse:7.14720
[502]	validation-rmse:7.14705
[503]	validation-rmse:7.14622
[504]	validation-rmse:7.14653
[505]	validation-rmse:7.14610
[506]	validation-rmse:7.14582
[507]	validation-rmse:7.14542
[508]	validation-rmse:7.14417
[509]	validation-rmse:7.14353
[510]	validation-rmse:7.14168
[511]	validation-rmse:7.14238
[512]	validation-rmse:7.14229
[513]	validation-rmse:7.14265
[514]	validation-rmse:7.14191
[515]	validation-rmse:7.13962
[516]	validation-rmse:7.13897
[517]	validation-rmse:7.13886
[518]	validation-rmse:7.13912
[519]	validation-rmse:7.13858
[520]	validation-rmse:7.13770
[521]	validation-rmse:7.13782
[522]	validation-rmse:7.13764
[523]	validation-rmse:7.13839
[524]	validation-rmse:7.13670
[525]	validation-rmse:7.13661
[526]	validation-rmse:7.13560
[527]	validation-rmse:7.13670
[528]	validation-rmse:7.13641
[529]	validation-rmse:7.13446
[530]	validation-rmse:7.13472
[531]	validation-rmse:7.13432
[532]	validation-rmse:7.13381
[533]	validation-rmse:7.13416
[534]	validation-rmse:7.13349
[535]	validation-rmse:7.13261
[536]	validation-rmse:7.13280
[537]	validation-rmse:7.13196
[538]	validation-rmse:7.13166
[539]	validation-rmse:7.13161
[540]	validation-rmse:7.12979
[541]	validation-rmse:7.12913
[542]	validation-rmse:7.12872
[543]	validation-rmse:7.12955
[544]	validation-rmse:7.12891
[545]	validation-rmse:7.12897
[546]	validation-rmse:7.12815
[547]	validation-rmse:7.12822
[548]	validation-rmse:7.12781
[549]	validation-rmse:7.12862
[550]	validation-rmse:7.12815
[551]	validation-rmse:7.12829
[552]	validation-rmse:7.12809
[553]	validation-rmse:7.12780
[554]	validation-rmse:7.12704
[555]	validation-rmse:7.12656
[556]	validation-rmse:7.12619
[557]	validation-rmse:7.12645
[558]	validation-rmse:7.12601
[559]	validation-rmse:7.12578
[560]	validation-rmse:7.12583
[561]	validation-rmse:7.12531
[562]	validation-rmse:7.12514
[563]	validation-rmse:7.12475
[564]	validation-rmse:7.12521
[565]	validation-rmse:7.12427
[566]	validation-rmse:7.12402
[567]	validation-rmse:7.12359
[568]	validation-rmse:7.12441
[569]	validation-rmse:7.12343
[570]	validation-rmse:7.12329
[571]	validation-rmse:7.12321
[572]	validation-rmse:7.12293
[573]	validation-rmse:7.12302
[574]	validation-rmse:7.12364
[575]	validation-rmse:7.12321
[576]	validation-rmse:7.12239
[577]	validation-rmse:7.12081
[578]	validation-rmse:7.12031
[579]	validation-rmse:7.12053
[580]	validation-rmse:7.12036
[581]	validation-rmse:7.12001
[582]	validation-rmse:7.12024
[583]	validation-rmse:7.12062
[584]	validation-rmse:7.12144
[585]	validation-rmse:7.12025
[586]	validation-rmse:7.12087
[587]	validation-rmse:7.12047
[588]	validation-rmse:7.12029
[589]	validation-rmse:7.12010
[590]	validation-rmse:7.12004
[591]	validation-rmse:7.11943
[592]	validation-rmse:7.11972
[593]	validation-rmse:7.11816
[594]	validation-rmse:7.11810
[595]	validation-rmse:7.11830
[596]	validation-rmse:7.11748
[597]	validation-rmse:7.11666
[598]	validation-rmse:7.11690
[599]	validation-rmse:7.11713
[600]	validation-rmse:7.11732
[601]	validation-rmse:7.11738
[602]	validation-rmse:7.11771
[603]	validation-rmse:7.11699
[604]	validation-rmse:7.11617
[605]	validation-rmse:7.11641
[606]	validation-rmse:7.11513
[607]	validation-rmse:7.11393
[608]	validation-rmse:7.11423
[609]	validation-rmse:7.11507
[610]	validation-rmse:7.11498
[611]	validation-rmse:7.11509
[612]	validation-rmse:7.11390
[613]	validation-rmse:7.11401
[614]	validation-rmse:7.11437
[615]	validation-rmse:7.11419
[616]	validation-rmse:7.11291
[617]	validation-rmse:7.11225
[618]	validation-rmse:7.11286
[619]	validation-rmse:7.11230
[620]	validation-rmse:7.11243
[621]	validation-rmse:7.11191
[622]	validation-rmse:7.11188
[623]	validation-rmse:7.11186
[624]	validation-rmse:7.11171
[625]	validation-rmse:7.11142
[626]	validation-rmse:7.11168
[627]	validation-rmse:7.11192
[628]	validation-rmse:7.11024
[629]	validation-rmse:7.11008
[630]	validation-rmse:7.11010
[631]	validation-rmse:7.11089
[632]	validation-rmse:7.11115
[633]	validation-rmse:7.11084
[634]	validation-rmse:7.11037
[635]	validation-rmse:7.11046
[636]	validation-rmse:7.11041
[637]	validation-rmse:7.10939
[638]	validation-rmse:7.10984
[639]	validation-rmse:7.10924
[640]	validation-rmse:7.10835
[641]	validation-rmse:7.10854
[642]	validation-rmse:7.10872
[643]	validation-rmse:7.10832
[644]	validation-rmse:7.10846
[645]	validation-rmse:7.10810
[646]	validation-rmse:7.10899
[647]	validation-rmse:7.10865
[648]	validation-rmse:7.10802
[649]	validation-rmse:7.10716
[650]	validation-rmse:7.10732
[651]	validation-rmse:7.10640
[652]	validation-rmse:7.10560
[653]	validation-rmse:7.10580
[654]	validation-rmse:7.10664
[655]	validation-rmse:7.10644
[656]	validation-rmse:7.10683
[657]	validation-rmse:7.10537
[658]	validation-rmse:7.10503
[659]	validation-rmse:7.10515
[660]	validation-rmse:7.10546
[661]	validation-rmse:7.10559
[662]	validation-rmse:7.10542
[663]	validation-rmse:7.10554
[664]	validation-rmse:7.10492
[665]	validation-rmse:7.10439
[666]	validation-rmse:7.10469
[667]	validation-rmse:7.10454
[668]	validation-rmse:7.10462
[669]	validation-rmse:7.10441

[14:45:11] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[0]	validation-rmse:16.39524
[1]	validation-rmse:13.32928
[2]	validation-rmse:11.45895
[3]	validation-rmse:10.40762
[4]	validation-rmse:9.67412
[5]	validation-rmse:9.20083
[6]	validation-rmse:8.94511
[7]	validation-rmse:8.70624
[8]	validation-rmse:8.58956
[9]	validation-rmse:8.50313
[10]	validation-rmse:8.41234
[11]	validation-rmse:8.35418
[12]	validation-rmse:8.27993
[13]	validation-rmse:8.20130
[14]	validation-rmse:8.15555
[15]	validation-rmse:8.12256
[16]	validation-rmse:8.07160
[17]	validation-rmse:8.04911
[18]	validation-rmse:8.03285
[19]	validation-rmse:8.01409
[20]	validation-rmse:7.98654
[21]	validation-rmse:7.97309
[22]	validation-rmse:7.95925
[23]	validation-rmse:7.95289
[24]	validation-rmse:7.93986
[25]	validation-rmse:7.92714
[26]	validation-rmse:7.91760
[27]	validation-rmse:7.91385
[28]	validation-rmse:7.90931
[29]	validation-rmse:7.90283
[30]	validation-rmse:7.89915
[31]	validation-rmse:7.89699
[32]	validation-rmse:7.89355
[33]	validation-rmse:7.87990
[34]	validation-rmse:7.87717
[35]	validation-rmse:7.87253
[36]	validation-rmse:7.86930
[37]	validation-rmse:7.86721
[38]	validation-rmse:7.86326
[39]	validation-rmse:7.85863
[40]	validation-rmse:7.85620
[41]	validation-rmse:7.85306
[42]	validation-rmse:7.84778
[43]	validation-rmse:7.84408
[44]	validation-rmse:7.84139
[45]	validation-rmse:7.83885
[46]	validation-rmse:7.83557
[47]	validation-rmse:7.83178
[48]	validation-rmse:7.82939
[49]	validation-rmse:7.82539
[50]	validation-rmse:7.82318
[51]	validation-rmse:7.81909
[52]	validation-rmse:7.81752
[53]	validation-rmse:7.81598
[54]	validation-rmse:7.81368
[55]	validation-rmse:7.80892
[56]	validation-rmse:7.80667
[57]	validation-rmse:7.80348
[58]	validation-rmse:7.79965
[59]	validation-rmse:7.79803
[60]	validation-rmse:7.79620
[61]	validation-rmse:7.79462
[62]	validation-rmse:7.79206
[63]	validation-rmse:7.79014
[64]	validation-rmse:7.78704
[65]	validation-rmse:7.78532
[66]	validation-rmse:7.78148
[67]	validation-rmse:7.77921
[68]	validation-rmse:7.77685
[69]	validation-rmse:7.77506
[70]	validation-rmse:7.77237
[71]	validation-rmse:7.77005
[72]	validation-rmse:7.76736
[73]	validation-rmse:7.76357
[74]	validation-rmse:7.75998
[75]	validation-rmse:7.75608
[76]	validation-rmse:7.75456
[77]	validation-rmse:7.75080
[78]	validation-rmse:7.74772
[79]	validation-rmse:7.74406
[80]	validation-rmse:7.74189
[81]	validation-rmse:7.73983
[82]	validation-rmse:7.73781
[83]	validation-rmse:7.73527
[84]	validation-rmse:7.73291
[85]	validation-rmse:7.73120
[86]	validation-rmse:7.72987
[87]	validation-rmse:7.72827
[88]	validation-rmse:7.72613
[89]	validation-rmse:7.72342
[90]	validation-rmse:7.72103
[91]	validation-rmse:7.72033
[92]	validation-rmse:7.71850
[93]	validation-rmse:7.71706
[94]	validation-rmse:7.71446
[95]	validation-rmse:7.71230
[96]	validation-rmse:7.71002
[97]	validation-rmse:7.70767
[98]	validation-rmse:7.70505
[99]	validation-rmse:7.70478
[100]	validation-rmse:7.70256
[101]	validation-rmse:7.69862
[102]	validation-rmse:7.69690
[103]	validation-rmse:7.69315
[104]	validation-rmse:7.69077
[105]	validation-rmse:7.68868
[106]	validation-rmse:7.68791
[107]	validation-rmse:7.68632
[108]	validation-rmse:7.68503
[109]	validation-rmse:7.68461
[110]	validation-rmse:7.68374
[111]	validation-rmse:7.68282
[112]	validation-rmse:7.68014
[113]	validation-rmse:7.67870
[114]	validation-rmse:7.67778
[115]	validation-rmse:7.67637
[116]	validation-rmse:7.67580
[117]	validation-rmse:7.67414
[118]	validation-rmse:7.67213
[119]	validation-rmse:7.67078
[120]	validation-rmse:7.66990
[121]	validation-rmse:7.66800
[122]	validation-rmse:7.66687
[123]	validation-rmse:7.66529
[124]	validation-rmse:7.66483
[125]	validation-rmse:7.66421
[126]	validation-rmse:7.66330
[127]	validation-rmse:7.66301
[128]	validation-rmse:7.66328
[129]	validation-rmse:7.66202
[130]	validation-rmse:7.66096
[131]	validation-rmse:7.65991
[132]	validation-rmse:7.65663
[133]	validation-rmse:7.65574
[134]	validation-rmse:7.65461
[135]	validation-rmse:7.65246
[136]	validation-rmse:7.65078
[137]	validation-rmse:7.64895
[138]	validation-rmse:7.64734
[139]	validation-rmse:7.64692
[140]	validation-rmse:7.64519
[141]	validation-rmse:7.64263
[142]	validation-rmse:7.64113
[143]	validation-rmse:7.63971
[144]	validation-rmse:7.63945
[145]	validation-rmse:7.63880
[146]	validation-rmse:7.63817
[147]	validation-rmse:7.63752
[148]	validation-rmse:7.63641
[149]	validation-rmse:7.63479
[150]	validation-rmse:7.63413
[151]	validation-rmse:7.63357
[152]	validation-rmse:7.63253
[153]	validation-rmse:7.63052
[154]	validation-rmse:7.62962
[155]	validation-rmse:7.62938
[156]	validation-rmse:7.62812
[157]	validation-rmse:7.62817
[158]	validation-rmse:7.62656
[159]	validation-rmse:7.62574
[160]	validation-rmse:7.62522
[161]	validation-rmse:7.62177
[162]	validation-rmse:7.62030
[163]	validation-rmse:7.61915
[164]	validation-rmse:7.61877
[165]	validation-rmse:7.61745
[166]	validation-rmse:7.61598
[167]	validation-rmse:7.61506
[168]	validation-rmse:7.61324
[169]	validation-rmse:7.61222
[170]	validation-rmse:7.61044
[171]	validation-rmse:7.60855
[172]	validation-rmse:7.60739
[173]	validation-rmse:7.60407
[174]	validation-rmse:7.60359
[175]	validation-rmse:7.60224
[176]	validation-rmse:7.60043
[177]	validation-rmse:7.59867
[178]	validation-rmse:7.59921
[179]	validation-rmse:7.59783
[180]	validation-rmse:7.59606
[181]	validation-rmse:7.59481
[182]	validation-rmse:7.59328
[183]	validation-rmse:7.59121
[184]	validation-rmse:7.59018
[185]	validation-rmse:7.58928
[186]	validation-rmse:7.58776
[187]	validation-rmse:7.58658
[188]	validation-rmse:7.58526
[189]	validation-rmse:7.58348
[190]	validation-rmse:7.58209
[191]	validation-rmse:7.58076
[192]	validation-rmse:7.57979
[193]	validation-rmse:7.57812
[194]	validation-rmse:7.57599
[195]	validation-rmse:7.57504
[196]	validation-rmse:7.57413
[197]	validation-rmse:7.57374
[198]	validation-rmse:7.57357
[199]	validation-rmse:7.57204
[200]	validation-rmse:7.57142
[201]	validation-rmse:7.56971
[202]	validation-rmse:7.56847
[203]	validation-rmse:7.56778
[204]	validation-rmse:7.56655
[205]	validation-rmse:7.56485
[206]	validation-rmse:7.56397
[207]	validation-rmse:7.56372
[208]	validation-rmse:7.56238
[209]	validation-rmse:7.56208
[210]	validation-rmse:7.56093
[211]	validation-rmse:7.56027
[212]	validation-rmse:7.55912
[213]	validation-rmse:7.55745
[214]	validation-rmse:7.55663
[215]	validation-rmse:7.55538
[216]	validation-rmse:7.55526
[217]	validation-rmse:7.55333
[218]	validation-rmse:7.55327
[219]	validation-rmse:7.55264
[220]	validation-rmse:7.55132
[221]	validation-rmse:7.55025
[222]	validation-rmse:7.54997
[223]	validation-rmse:7.54890
[224]	validation-rmse:7.54809
[225]	validation-rmse:7.54750
[226]	validation-rmse:7.54668
[227]	validation-rmse:7.54470
[228]	validation-rmse:7.54468
[229]	validation-rmse:7.54402
[230]	validation-rmse:7.54284
[231]	validation-rmse:7.54228
[232]	validation-rmse:7.54170
[233]	validation-rmse:7.54120
[234]	validation-rmse:7.54013
[235]	validation-rmse:7.53936
[236]	validation-rmse:7.53679
[237]	validation-rmse:7.53615
[238]	validation-rmse:7.53575
[239]	validation-rmse:7.53519
[240]	validation-rmse:7.53510
[241]	validation-rmse:7.53401
[242]	validation-rmse:7.53305
[243]	validation-rmse:7.53314
[244]	validation-rmse:7.53241
[245]	validation-rmse:7.53069
[246]	validation-rmse:7.52847
[247]	validation-rmse:7.52821
[248]	validation-rmse:7.52685
[249]	validation-rmse:7.52665
[250]	validation-rmse:7.52599
[251]	validation-rmse:7.52519
[252]	validation-rmse:7.52517
[253]	validation-rmse:7.52514
[254]	validation-rmse:7.52393
[255]	validation-rmse:7.52246
[256]	validation-rmse:7.52120
[257]	validation-rmse:7.52017
[258]	validation-rmse:7.51992
[259]	validation-rmse:7.51974
[260]	validation-rmse:7.51807
[261]	validation-rmse:7.51746
[262]	validation-rmse:7.51665
[263]	validation-rmse:7.51451
[264]	validation-rmse:7.51408
[265]	validation-rmse:7.51336
[266]	validation-rmse:7.51250
[267]	validation-rmse:7.51199
[268]	validation-rmse:7.51195
[269]	validation-rmse:7.50967
[270]	validation-rmse:7.50868
[271]	validation-rmse:7.50772
[272]	validation-rmse:7.50612
[273]	validation-rmse:7.50432
[274]	validation-rmse:7.50371
[275]	validation-rmse:7.50333
[276]	validation-rmse:7.50162
[277]	validation-rmse:7.50139
[278]	validation-rmse:7.50060
[279]	validation-rmse:7.50020
[280]	validation-rmse:7.49971
[281]	validation-rmse:7.49972
[282]	validation-rmse:7.49910
[283]	validation-rmse:7.49802
[284]	validation-rmse:7.49774
[285]	validation-rmse:7.49677
[286]	validation-rmse:7.49564
[287]	validation-rmse:7.49454
[288]	validation-rmse:7.49290
[289]	validation-rmse:7.49046
[290]	validation-rmse:7.49045
[291]	validation-rmse:7.48954
[292]	validation-rmse:7.48875
[293]	validation-rmse:7.48828
[294]	validation-rmse:7.48765
[295]	validation-rmse:7.48342
[296]	validation-rmse:7.48267
[297]	validation-rmse:7.48137
[298]	validation-rmse:7.48012
[299]	validation-rmse:7.47882
[300]	validation-rmse:7.47744
[301]	validation-rmse:7.47710
[302]	validation-rmse:7.47636
[303]	validation-rmse:7.47434
[304]	validation-rmse:7.47329
[305]	validation-rmse:7.47284
[306]	validation-rmse:7.47019
[307]	validation-rmse:7.46917
[308]	validation-rmse:7.46838
[309]	validation-rmse:7.46755
[310]	validation-rmse:7.46628
[311]	validation-rmse:7.46484
[312]	validation-rmse:7.46433
[313]	validation-rmse:7.46361
[314]	validation-rmse:7.46327
[315]	validation-rmse:7.45982
[316]	validation-rmse:7.45932
[317]	validation-rmse:7.45879
[318]	validation-rmse:7.45758
[319]	validation-rmse:7.45737
[320]	validation-rmse:7.45669
[321]	validation-rmse:7.45502
[322]	validation-rmse:7.45379
[323]	validation-rmse:7.45256
[324]	validation-rmse:7.45222
[325]	validation-rmse:7.45133
[326]	validation-rmse:7.45039
[327]	validation-rmse:7.45009
[328]	validation-rmse:7.44948
[329]	validation-rmse:7.44998
[330]	validation-rmse:7.44864
[331]	validation-rmse:7.44879
[332]	validation-rmse:7.44833
[333]	validation-rmse:7.44871
[334]	validation-rmse:7.44900
[335]	validation-rmse:7.44847
[336]	validation-rmse:7.44715
[337]	validation-rmse:7.44536
[338]	validation-rmse:7.44472
[339]	validation-rmse:7.44451
[340]	validation-rmse:7.44411
[341]	validation-rmse:7.44334
[342]	validation-rmse:7.44345
[343]	validation-rmse:7.44321
[344]	validation-rmse:7.44273
[345]	validation-rmse:7.44237
[346]	validation-rmse:7.44189
[347]	validation-rmse:7.44089
[348]	validation-rmse:7.44042
[349]	validation-rmse:7.44057
[350]	validation-rmse:7.44080
[351]	validation-rmse:7.43967
[352]	validation-rmse:7.43792
[353]	validation-rmse:7.43833
[354]	validation-rmse:7.43716
[355]	validation-rmse:7.43662
[356]	validation-rmse:7.43506
[357]	validation-rmse:7.43449
[358]	validation-rmse:7.43334
[359]	validation-rmse:7.43254
[360]	validation-rmse:7.43216
[361]	validation-rmse:7.43041
[362]	validation-rmse:7.42866
[363]	validation-rmse:7.42838
[364]	validation-rmse:7.42805
[365]	validation-rmse:7.42714
[366]	validation-rmse:7.42658
[367]	validation-rmse:7.42616
[368]	validation-rmse:7.42520
[369]	validation-rmse:7.42508
[370]	validation-rmse:7.42407
[371]	validation-rmse:7.42323
[372]	validation-rmse:7.42256
[373]	validation-rmse:7.42248
[374]	validation-rmse:7.42140
[375]	validation-rmse:7.42038
[376]	validation-rmse:7.41910
[377]	validation-rmse:7.41749
[378]	validation-rmse:7.41706
[379]	validation-rmse:7.41661
[380]	validation-rmse:7.41607
[381]	validation-rmse:7.41549
[382]	validation-rmse:7.41481
[383]	validation-rmse:7.41505
[384]	validation-rmse:7.41478
[385]	validation-rmse:7.41337
[386]	validation-rmse:7.41254
[387]	validation-rmse:7.41116
[388]	validation-rmse:7.41093
[389]	validation-rmse:7.41046
[390]	validation-rmse:7.40941
[391]	validation-rmse:7.40835
[392]	validation-rmse:7.40819
[393]	validation-rmse:7.40750
[394]	validation-rmse:7.40676
[395]	validation-rmse:7.40559
[396]	validation-rmse:7.40486
[397]	validation-rmse:7.40437
[398]	validation-rmse:7.40382
[399]	validation-rmse:7.40395
[400]	validation-rmse:7.40326
[401]	validation-rmse:7.40271
[402]	validation-rmse:7.40231
[403]	validation-rmse:7.40203
[404]	validation-rmse:7.40128
[405]	validation-rmse:7.40060
[406]	validation-rmse:7.40016
[407]	validation-rmse:7.39979
[408]	validation-rmse:7.39966
[409]	validation-rmse:7.39952
[410]	validation-rmse:7.39895
[411]	validation-rmse:7.39871
[412]	validation-rmse:7.39837
[413]	validation-rmse:7.39786
[414]	validation-rmse:7.39794
[415]	validation-rmse:7.39675
[416]	validation-rmse:7.39589
[417]	validation-rmse:7.39526
[418]	validation-rmse:7.39465
[419]	validation-rmse:7.39424
[420]	validation-rmse:7.39349
[421]	validation-rmse:7.39227
[422]	validation-rmse:7.39086
[423]	validation-rmse:7.39060
[424]	validation-rmse:7.39093
[425]	validation-rmse:7.39077
[426]	validation-rmse:7.39098
[427]	validation-rmse:7.38989
[428]	validation-rmse:7.38962
[429]	validation-rmse:7.38983
[430]	validation-rmse:7.38940
[431]	validation-rmse:7.38877
[432]	validation-rmse:7.38794
[433]	validation-rmse:7.38735
[434]	validation-rmse:7.38784
[435]	validation-rmse:7.38794
[436]	validation-rmse:7.38806
[437]	validation-rmse:7.38756
[438]	validation-rmse:7.38622
[439]	validation-rmse:7.38524
[440]	validation-rmse:7.38461
[441]	validation-rmse:7.38399
[442]	validation-rmse:7.38268
[443]	validation-rmse:7.38240
[444]	validation-rmse:7.38193
[445]	validation-rmse:7.38180
[446]	validation-rmse:7.38048
[447]	validation-rmse:7.37855
[448]	validation-rmse:7.37785
[449]	validation-rmse:7.37773
[450]	validation-rmse:7.37686
[451]	validation-rmse:7.37553
[452]	validation-rmse:7.37555
[453]	validation-rmse:7.37496
[454]	validation-rmse:7.37508
[455]	validation-rmse:7.37361
[456]	validation-rmse:7.37282
[457]	validation-rmse:7.37312
[458]	validation-rmse:7.37240
[459]	validation-rmse:7.37182
[460]	validation-rmse:7.37180
[461]	validation-rmse:7.37126
[462]	validation-rmse:7.37060
[463]	validation-rmse:7.36909
[464]	validation-rmse:7.36880
[465]	validation-rmse:7.36835
[466]	validation-rmse:7.36827
[467]	validation-rmse:7.36735
[468]	validation-rmse:7.36716
[469]	validation-rmse:7.36613
[470]	validation-rmse:7.36641
[471]	validation-rmse:7.36523
[472]	validation-rmse:7.36463
[473]	validation-rmse:7.36446
[474]	validation-rmse:7.36330
[475]	validation-rmse:7.36293
[476]	validation-rmse:7.36270
[477]	validation-rmse:7.36170
[478]	validation-rmse:7.36131
[479]	validation-rmse:7.36151
[480]	validation-rmse:7.36122
[481]	validation-rmse:7.36053
[482]	validation-rmse:7.36006
[483]	validation-rmse:7.35941
[484]	validation-rmse:7.35820
[485]	validation-rmse:7.35729
[486]	validation-rmse:7.35712
[487]	validation-rmse:7.35724
[488]	validation-rmse:7.35694
[489]	validation-rmse:7.35686
[490]	validation-rmse:7.35578
[491]	validation-rmse:7.35570
[492]	validation-rmse:7.35437
[493]	validation-rmse:7.35367
[494]	validation-rmse:7.35322
[495]	validation-rmse:7.35294
[496]	validation-rmse:7.35303
[497]	validation-rmse:7.35296
[498]	validation-rmse:7.35291
[499]	validation-rmse:7.35219
[500]	validation-rmse:7.35169
[501]	validation-rmse:7.35106
[502]	validation-rmse:7.35123
[503]	validation-rmse:7.35053
[504]	validation-rmse:7.35002
[505]	validation-rmse:7.34952
[506]	validation-rmse:7.34868
[507]	validation-rmse:7.34718
[508]	validation-rmse:7.34602
[509]	validation-rmse:7.34568
[510]	validation-rmse:7.34535
[511]	validation-rmse:7.34532
[512]	validation-rmse:7.34506
[513]	validation-rmse:7.34473
[514]	validation-rmse:7.34223
[515]	validation-rmse:7.34197
[516]	validation-rmse:7.34176
[517]	validation-rmse:7.34072
[518]	validation-rmse:7.33945
[519]	validation-rmse:7.33940
[520]	validation-rmse:7.33844
[521]	validation-rmse:7.33845
[522]	validation-rmse:7.33791
[523]	validation-rmse:7.33793
[524]	validation-rmse:7.33668
[525]	validation-rmse:7.33581
[526]	validation-rmse:7.33529
[527]	validation-rmse:7.33501
[528]	validation-rmse:7.33470
[529]	validation-rmse:7.33404
[530]	validation-rmse:7.33284
[531]	validation-rmse:7.33261
[532]	validation-rmse:7.33193
[533]	validation-rmse:7.33172
[534]	validation-rmse:7.33141
[535]	validation-rmse:7.33124
[536]	validation-rmse:7.33127
[537]	validation-rmse:7.33131
[538]	validation-rmse:7.33118
[539]	validation-rmse:7.33106
[540]	validation-rmse:7.33123
[541]	validation-rmse:7.33073
[542]	validation-rmse:7.33070
[543]	validation-rmse:7.32960
[544]	validation-rmse:7.32812
[545]	validation-rmse:7.32756
[546]	validation-rmse:7.32650
[547]	validation-rmse:7.32643
[548]	validation-rmse:7.32551
[549]	validation-rmse:7.32478
[550]	validation-rmse:7.32422
[551]	validation-rmse:7.32430
[552]	validation-rmse:7.32438
[553]	validation-rmse:7.32410
[554]	validation-rmse:7.32422
[555]	validation-rmse:7.32369
[556]	validation-rmse:7.32343
[557]	validation-rmse:7.32264
[558]	validation-rmse:7.32272
[559]	validation-rmse:7.32198
[560]	validation-rmse:7.32158
[561]	validation-rmse:7.32158
[562]	validation-rmse:7.32107
[563]	validation-rmse:7.32079
[564]	validation-rmse:7.31977
[565]	validation-rmse:7.31932
[566]	validation-rmse:7.31846
[567]	validation-rmse:7.31878
[568]	validation-rmse:7.31870
[569]	validation-rmse:7.31815
[570]	validation-rmse:7.31720
[571]	validation-rmse:7.31704
[572]	validation-rmse:7.31715
[573]	validation-rmse:7.31685
[574]	validation-rmse:7.31616
[575]	validation-rmse:7.31496
[576]	validation-rmse:7.31501
[577]	validation-rmse:7.31507
[578]	validation-rmse:7.31439
[579]	validation-rmse:7.31398
[580]	validation-rmse:7.31296
[581]	validation-rmse:7.31254
[582]	validation-rmse:7.31211
[583]	validation-rmse:7.31044
[584]	validation-rmse:7.30976
[585]	validation-rmse:7.30869
[586]	validation-rmse:7.30861
[587]	validation-rmse:7.30804
[588]	validation-rmse:7.30738
[589]	validation-rmse:7.30700
[590]	validation-rmse:7.30691
[591]	validation-rmse:7.30601
[592]	validation-rmse:7.30599
[593]	validation-rmse:7.30561
[594]	validation-rmse:7.30576
[595]	validation-rmse:7.30587
[596]	validation-rmse:7.30490
[597]	validation-rmse:7.30424
[598]	validation-rmse:7.30395
[599]	validation-rmse:7.30328
[600]	validation-rmse:7.30282
[601]	validation-rmse:7.30274
[602]	validation-rmse:7.30308
[603]	validation-rmse:7.30276
[604]	validation-rmse:7.30099
[605]	validation-rmse:7.30003
[606]	validation-rmse:7.29951
[607]	validation-rmse:7.29991
[608]	validation-rmse:7.30030
[609]	validation-rmse:7.29986
[610]	validation-rmse:7.29932
[611]	validation-rmse:7.29788
[612]	validation-rmse:7.29745
[613]	validation-rmse:7.29767
[614]	validation-rmse:7.29768
[615]	validation-rmse:7.29733
[616]	validation-rmse:7.29731
[617]	validation-rmse:7.29582
[618]	validation-rmse:7.29532
[619]	validation-rmse:7.29536
[620]	validation-rmse:7.29435
[621]	validation-rmse:7.29381
[622]	validation-rmse:7.29321
[623]	validation-rmse:7.29247
[624]	validation-rmse:7.29258
[625]	validation-rmse:7.29191
[626]	validation-rmse:7.29084
[627]	validation-rmse:7.29067
[628]	validation-rmse:7.28978
[629]	validation-rmse:7.28963
[630]	validation-rmse:7.28936
[631]	validation-rmse:7.28886
[632]	validation-rmse:7.28920
[633]	validation-rmse:7.28896
[634]	validation-rmse:7.28870
[635]	validation-rmse:7.28874
[636]	validation-rmse:7.28898
[637]	validation-rmse:7.28917
[638]	validation-rmse:7.28833
[639]	validation-rmse:7.28788
[640]	validation-rmse:7.28762
[641]	validation-rmse:7.28808
[642]	validation-rmse:7.28739
[643]	validation-rmse:7.28719
[644]	validation-rmse:7.28444
[645]	validation-rmse:7.28365
[646]	validation-rmse:7.28360
[647]	validation-rmse:7.28342
[648]	validation-rmse:7.28352
[649]	validation-rmse:7.28342
[650]	validation-rmse:7.28319
[651]	validation-rmse:7.28251
[652]	validation-rmse:7.28179
[653]	validation-rmse:7.28153
[654]	validation-rmse:7.28118
[655]	validation-rmse:7.28064
[656]	validation-rmse:7.27990
[657]	validation-rmse:7.27986
[658]	validation-rmse:7.27949
[659]	validation-rmse:7.27855
[660]	validation-rmse:7.27848
[661]	validation-rmse:7.27814
[662]	validation-rmse:7.27814
[663]	validation-rmse:7.27758
[664]	validation-rmse:7.27743
[665]	validation-rmse:7.27727
[666]	validation-rmse:7.27753
[667]	validation-rmse:7.27751
[668]	validation-rmse:7.27726
[669]	validation-rmse:7.27640

[14:49:50] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:16.24052
[2]	validation-rmse:14.46409
[3]	validation-rmse:13.11495
[4]	validation-rmse:12.02679
[5]	validation-rmse:11.16842
[6]	validation-rmse:10.48422
[7]	validation-rmse:9.97982
[8]	validation-rmse:9.61201
[9]	validation-rmse:9.29899
[10]	validation-rmse:9.00766
[11]	validation-rmse:8.84729
[12]	validation-rmse:8.69529
[13]	validation-rmse:8.57710
[14]	validation-rmse:8.40108
[15]	validation-rmse:8.28947
[16]	validation-rmse:8.23681
[17]	validation-rmse:8.15763
[18]	validation-rmse:8.05507
[19]	validation-rmse:8.02579
[20]	validation-rmse:7.95161
[21]	validation-rmse:7.91229
[22]	validation-rmse:7.87133
[23]	validation-rmse:7.83302
[24]	validation-rmse:7.80591
[25]	validation-rmse:7.78251
[26]	validation-rmse:7.75670
[27]	validation-rmse:7.74630
[28]	validation-rmse:7.72089
[29]	validation-rmse:7.71171
[30]	validation-rmse:7.68782
[31]	validation-rmse:7.66709
[32]	validation-rmse:7.65131
[33]	validation-rmse:7.64687
[34]	validation-rmse:7.63264
[35]	validation-rmse:7.62459
[36]	validation-rmse:7.61880
[37]	validation-rmse:7.61383
[38]	validation-rmse:7.60576
[39]	validation-rmse:7.60044
[40]	validation-rmse:7.59430
[41]	validation-rmse:7.59073
[42]	validation-rmse:7.58597
[43]	validation-rmse:7.58342
[44]	validation-rmse:7.58256
[45]	validation-rmse:7.58085
[46]	validation-rmse:7.57593
[47]	validation-rmse:7.57581
[48]	validation-rmse:7.57491
[49]	validation-rmse:7.56994
[50]	validation-rmse:7.56842
[51]	validation-rmse:7.56836
[52]	validation-rmse:7.56573
[53]	validation-rmse:7.56569
[54]	validation-rmse:7.56453
[55]	validation-rmse:7.56351
[56]	validation-rmse:7.56124
[57]	validation-rmse:7.56026
[58]	validation-rmse:7.55994
[59]	validation-rmse:7.55992
[60]	validation-rmse:7.55972
[61]	validation-rmse:7.55936
[62]	validation-rmse:7.55815
[63]	validation-rmse:7.55869
[64]	validation-rmse:7.55835
[65]	validation-rmse:7.55768
[66]	validation-rmse:7.55746
[67]	validation-rmse:7.55758
[68]	validation-rmse:7.55764
[69]	validation-rmse:7.55730
[70]	validation-rmse:7.55630
[71]	validation-rmse:7.55627
[72]	validation-rmse:7.55622
[73]	validation-rmse:7.55634
[74]	validation-rmse:7.55527
[75]	validation-rmse:7.55501
[76]	validation-rmse:7.55507
[77]	validation-rmse:7.55492
[78]	validation-rmse:7.55451
[79]	validation-rmse:7.55402
[80]	validation-rmse:7.55383
[81]	validation-rmse:7.55406
[82]	validation-rmse:7.55373
[83]	validation-rmse:7.55360
[84]	validation-rmse:7.55339
[85]	validation-rmse:7.55345
[86]	validation-rmse:7.55343
[87]	validation-rmse:7.55314
[88]	validation-rmse:7.55309
[89]	validation-rmse:7.55314
[90]	validation-rmse:7.55282
[91]	validation-rmse:7.55280
[92]	validation-rmse:7.55236
[93]	validation-rmse:7.55228
[94]	validation-rmse:7.55236
[95]	validation-rmse:7.55216
[96]	validation-rmse:7.55212
[97]	validation-rmse:7.55212
[98]	validation-rmse:7.55227
[99]	validation-rmse:7.55232
[100]	validation-rmse:7.55237
[101]	validation-rmse:7.55247
[102]	validation-rmse:7.55226
[103]	validation-rmse:7.55221
[104]	validation-rmse:7.55220
[105]	validation-rmse:7.55220
[106]	validation-rmse:7.55207
[107]	validation-rmse:7.55210
[108]	validation-rmse:7.55213
[109]	validation-rmse:7.55221
[110]	validation-rmse:7.55211
[111]	validation-rmse:7.55206
[112]	validation-rmse:7.55203
[113]	validation-rmse:7.55201
[114]	validation-rmse:7.55197
[115]	validation-rmse:7.55191
[116]	validation-rmse:7.55195
[117]	validation-rmse:7.55196
[118]	validation-rmse:7.55178
[119]	validation-rmse:7.55166
[120]	validation-rmse:7.55164
[121]	validation-rmse:7.55158
[122]	validation-rmse:7.55153
[123]	validation-rmse:7.55148
[124]	validation-rmse:7.55148
[125]	validation-rmse:7.55141
[126]	validation-rmse:7.55141
[127]	validation-rmse:7.55142
[128]	validation-rmse:7.55134
[129]	validation-rmse:7.55126
[130]	validation-rmse:7.55120
[131]	validation-rmse:7.55120
[132]	validation-rmse:7.55108
[133]	validation-rmse:7.55108
[134]	validation-rmse:7.55105
[135]	validation-rmse:7.55100
[136]	validation-rmse:7.55089
[137]	validation-rmse:7.55091
[138]	validation-rmse:7.55089
[139]	validation-rmse:7.55084
[140]	validation-rmse:7.55081
[141]	validation-rmse:7.55082
[142]	validation-rmse:7.55073
[143]	validation-rmse:7.55071
[144]	validation-rmse:7.55071
[145]	validation-rmse:7.55064
[146]	validation-rmse:7.55061
[147]	validation-rmse:7.55056
[148]	validation-rmse:7.55049
[149]	validation-rmse:7.55042
[150]	validation-rmse:7.55039
[151]	validation-rmse:7.55035
[152]	validation-rmse:7.55032
[153]	validation-rmse:7.55031
[154]	validation-rmse:7.55028
[155]	validation-rmse:7.55026
[156]	validation-rmse:7.55022
[157]	validation-rmse:7.55021
[158]	validation-rmse:7.55022
[159]	validation-rmse:7.55021
[160]	validation-rmse:7.55015
[161]	validation-rmse:7.55017
[162]	validation-rmse:7.55013
[163]	validation-rmse:7.55010
[164]	validation-rmse:7.55010
[165]	validation-rmse:7.55009
[166]	validation-rmse:7.55005
[167]	validation-rmse:7.55001
[168]	validation-rmse:7.55000
[169]	validation-rmse:7.54999
[170]	validation-rmse:7.54997
[171]	validation-rmse:7.54994
[172]	validation-rmse:7.54992
[173]	validation-rmse:7.54989
[174]	validation-rmse:7.54988
[175]	validation-rmse:7.54987
[176]	validation-rmse:7.54983
[177]	validation-rmse:7.54984
[178]	validation-rmse:7.54982
[179]	validation-rmse:7.54983
[180]	validation-rmse:7.54983
[181]	validation-rmse:7.54983
[182]	validation-rmse:7.54982
[183]	validation-rmse:7.54980
[184]	validation-rmse:7.54980
[185]	validation-rmse:7.54977
[186]	validation-rmse:7.54977
[187]	validation-rmse:7.54977
[188]	validation-rmse:7.54977
[189]	validation-rmse:7.54974
[190]	validation-rmse:7.54974
[191]	validation-rmse:7.54974
[192]	validation-rmse:7.54973
[193]	validation-rmse:7.54973
[194]	validation-rmse:7.54972
[195]	validation-rmse:7.54971
[196]	validation-rmse:7.54971
[197]	validation-rmse:7.54971
[198]	validation-rmse:7.54969
[199]	validation-rmse:7.54969
[200]	validation-rmse:7.54967
[201]	validation-rmse:7.54966
[202]	validation-rmse:7.54965
[203]	validation-rmse:7.54965
[204]	validation-rmse:7.54965
[205]	validation-rmse:7.54965
[206]	validation-rmse:7.54964
[207]	validation-rmse:7.54963
[208]	validation-rmse:7.54962
[209]	validation-rmse:7.54962
[210]	validation-rmse:7.54961
[211]	validation-rmse:7.54961
[212]	validation-rmse:7.54960
[213]	validation-rmse:7.54960
[214]	validation-rmse:7.54960
[215]	validation-rmse:7.54959
[216]	validation-rmse:7.54959
[217]	validation-rmse:7.54959
[218]	validation-rmse:7.54959
[219]	validation-rmse:7.54959
[220]	validation-rmse:7.54959
[221]	validation-rmse:7.54959
[222]	validation-rmse:7.54958
[223]	validation-rmse:7.54957
[224]	validation-rmse:7.54957
[225]	validation-rmse:7.54957
[226]	validation-rmse:7.54958
[227]	validation-rmse:7.54958
[228]	validation-rmse:7.54957
[229]	validation-rmse:7.54957
[230]	validation-rmse:7.54957
[231]	validation-rmse:7.54957
[232]	validation-rmse:7.54956
[233]	validation-rmse:7.54955
[234]	validation-rmse:7.54954
[235]	validation-rmse:7.54954
[236]	validation-rmse:7.54954
[237]	validation-rmse:7.54954
[238]	validation-rmse:7.54954
[239]	validation-rmse:7.54954
[240]	validation-rmse:7.54954
[241]	validation-rmse:7.54954
[242]	validation-rmse:7.54954
[243]	validation-rmse:7.54954
[244]	validation-rmse:7.54953
[245]	validation-rmse:7.54953
[246]	validation-rmse:7.54953
[247]	validation-rmse:7.54953
[248]	validation-rmse:7.54952
[249]	validation-rmse:7.54952
[250]	validation-rmse:7.54952
[251]	validation-rmse:7.54952
[252]	validation-rmse:7.54952
[253]	validation-rmse:7.54952
[254]	validation-rmse:7.54952
[255]	validation-rmse:7.54952
[256]	validation-rmse:7.54952
[257]	validation-rmse:7.54952
[258]	validation-rmse:7.54952
[259]	validation-rmse:7.54952
[260]	validation-rmse:7.54953
[261]	validation-rmse:7.54953
[262]	validation-rmse:7.54953
[263]	validation-rmse:7.54952
[264]	validation-rmse:7.54952
[265]	validation-rmse:7.54953
[266]	validation-rmse:7.54952
[267]	validation-rmse:7.54952
[268]	validation-rmse:7.54952
[269]	validation-rmse:7.54952
[270]	validation-rmse:7.54952
[271]	validation-rmse:7.54952
[272]	validation-rmse:7.54952
[273]	validation-rmse:7.54952
[274]	validation-rmse:7.54952
[275]	validation-rmse:7.54952
[276]	validation-rmse:7.54952
[277]	validation-rmse:7.54952
[278]	validation-rmse:7.54952
[279]	validation-rmse:7.54952
[280]	validation-rmse:7.54952
[281]	validation-rmse:7.54952
[282]	validation-rmse:7.54952
[283]	validation-rmse:7.54952
[284]	validation-rmse:7.54952
[285]	validation-rmse:7.54952
[286]	validation-rmse:7.54952
[287]	validation-rmse:7.54952
[288]	validation-rmse:7.54952
[289]	validation-rmse:7.54952
[290]	validation-rmse:7.54952
[291]	validation-rmse:7.54952
[292]	validation-rmse:7.54952
[293]	validation-rmse:7.54952
[294]	validation-rmse:7.54952
[295]	validation-rmse:7.54952
[296]	validation-rmse:7.54952
[297]	validation-rmse:7.54952
[298]	validation-rmse:7.54953
[299]	validation-rmse:7.54953
[300]	validation-rmse:7.54952
[301]	validation-rmse:7.54953
[302]	validation-rmse:7.54953
[0]	validation-rmse:13.94056
 68%|██████▊   | 34/50 [3:01:37<2:47:58, 629.93s/trial, best loss: 7.015206479144177]

[14:51:33] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:11.13181
[2]	validation-rmse:10.07403
[3]	validation-rmse:9.59402
[4]	validation-rmse:9.40218
[5]	validation-rmse:9.27816
[6]	validation-rmse:9.18295
[7]	validation-rmse:9.12764
[8]	validation-rmse:9.05075
[9]	validation-rmse:8.97595
[10]	validation-rmse:8.89120
[11]	validation-rmse:8.85778
[12]	validation-rmse:8.82886
[13]	validation-rmse:8.79332
[14]	validation-rmse:8.78070
[15]	validation-rmse:8.76492
[16]	validation-rmse:8.73221
[17]	validation-rmse:8.70785
[18]	validation-rmse:8.68423
[19]	validation-rmse:8.67054
[20]	validation-rmse:8.65410
[21]	validation-rmse:8.63328
[22]	validation-rmse:8.61462
[23]	validation-rmse:8.60167
[24]	validation-rmse:8.58925
[25]	validation-rmse:8.57092
[26]	validation-rmse:8.55333
[27]	validation-rmse:8.54230
[28]	validation-rmse:8.52525
[29]	validation-rmse:8.50964
[30]	validation-rmse:8.49395
[31]	validation-rmse:8.47801
[32]	validation-rmse:8.46679
[33]	validation-rmse:8.45723
[34]	validation-rmse:8.44907
[35]	validation-rmse:8.44069
[36]	validation-rmse:8.43557
[37]	validation-rmse:8.42147
[38]	validation-rmse:8.41503
[39]	validation-rmse:8.40840
[40]	validation-rmse:8.39751
[41]	validation-rmse:8.38966
[42]	validation-rmse:8.38435
[43]	validation-rmse:8.37884
[44]	validation-rmse:8.37551
[45]	validation-rmse:8.36739
[46]	validation-rmse:8.36084
[47]	validation-rmse:8.35576
[48]	validation-rmse:8.34931
[49]	validation-rmse:8.34028
[50]	validation-rmse:8.33348
[51]	validation-rmse:8.32894
[52]	validation-rmse:8.32125
[53]	validation-rmse:8.31567
[54]	validation-rmse:8.31216
[55]	validation-rmse:8.30672
[56]	validation-rmse:8.30110
[57]	validation-rmse:8.29511
[58]	validation-rmse:8.28994
[59]	validation-rmse:8.28659
[60]	validation-rmse:8.28275
[61]	validation-rmse:8.27425
[62]	validation-rmse:8.27016
[63]	validation-rmse:8.26600
[64]	validation-rmse:8.25822
[65]	validation-rmse:8.25431
[66]	validation-rmse:8.24468
[67]	validation-rmse:8.23352
[68]	validation-rmse:8.22220
[69]	validation-rmse:8.21004
[70]	validation-rmse:8.19968
[71]	validation-rmse:8.19122
[72]	validation-rmse:8.18376
[73]	validation-rmse:8.17300
[74]	validation-rmse:8.16519
[75]	validation-rmse:8.16093
[76]	validation-rmse:8.15360
[77]	validation-rmse:8.14899
[78]	validation-rmse:8.14490
[79]	validation-rmse:8.14018
[80]	validation-rmse:8.13793
[81]	validation-rmse:8.13287
[82]	validation-rmse:8.12633
[83]	validation-rmse:8.12287
[84]	validation-rmse:8.11735
[85]	validation-rmse:8.11580
[86]	validation-rmse:8.10107
[87]	validation-rmse:8.09135
[88]	validation-rmse:8.07536
[89]	validation-rmse:8.06668
[90]	validation-rmse:8.05248
[91]	validation-rmse:8.04462
[92]	validation-rmse:8.03569
[93]	validation-rmse:8.03065
[94]	validation-rmse:8.02012
[95]	validation-rmse:8.01592
[96]	validation-rmse:8.00371
[97]	validation-rmse:7.99524
[98]	validation-rmse:7.98417
[99]	validation-rmse:7.97770
[100]	validation-rmse:7.97036
[101]	validation-rmse:7.96297
[102]	validation-rmse:7.95712
[103]	validation-rmse:7.95052
[104]	validation-rmse:7.93917
[105]	validation-rmse:7.93315
[106]	validation-rmse:7.92858
[107]	validation-rmse:7.92503
[108]	validation-rmse:7.91895
[109]	validation-rmse:7.91409
[110]	validation-rmse:7.90821
[111]	validation-rmse:7.90660
[112]	validation-rmse:7.90025
[113]	validation-rmse:7.89339
[114]	validation-rmse:7.88704
[115]	validation-rmse:7.88276
[116]	validation-rmse:7.87988
[117]	validation-rmse:7.87270
[118]	validation-rmse:7.86969
[119]	validation-rmse:7.86477
[120]	validation-rmse:7.85639
[121]	validation-rmse:7.85247
[122]	validation-rmse:7.84838
[123]	validation-rmse:7.84616
[124]	validation-rmse:7.84395
[125]	validation-rmse:7.84043
[126]	validation-rmse:7.83751
[127]	validation-rmse:7.83353
[128]	validation-rmse:7.82972
[129]	validation-rmse:7.82814
[130]	validation-rmse:7.82495
[131]	validation-rmse:7.82304
[132]	validation-rmse:7.82222
[133]	validation-rmse:7.81928
[134]	validation-rmse:7.81752
[135]	validation-rmse:7.81583
[136]	validation-rmse:7.81232
[137]	validation-rmse:7.81091
[138]	validation-rmse:7.80892
[139]	validation-rmse:7.80705
[140]	validation-rmse:7.80484
[141]	validation-rmse:7.80255
[142]	validation-rmse:7.80014
[143]	validation-rmse:7.79747
[144]	validation-rmse:7.79528
[145]	validation-rmse:7.78992
[146]	validation-rmse:7.78958
[147]	validation-rmse:7.78636
[148]	validation-rmse:7.78305
[149]	validation-rmse:7.78267
[150]	validation-rmse:7.78176
[151]	validation-rmse:7.77881
[152]	validation-rmse:7.77755
[153]	validation-rmse:7.77637
[154]	validation-rmse:7.77432
[155]	validation-rmse:7.76934
[156]	validation-rmse:7.76842
[157]	validation-rmse:7.76690
[158]	validation-rmse:7.76136
[159]	validation-rmse:7.76042
[160]	validation-rmse:7.75729
[161]	validation-rmse:7.75554
[162]	validation-rmse:7.75335
[163]	validation-rmse:7.75087
[164]	validation-rmse:7.74805
[165]	validation-rmse:7.74797
[166]	validation-rmse:7.74602
[167]	validation-rmse:7.74424
[168]	validation-rmse:7.74311
[169]	validation-rmse:7.74026
[170]	validation-rmse:7.73889
[171]	validation-rmse:7.73577
[172]	validation-rmse:7.73362
[173]	validation-rmse:7.73327
[174]	validation-rmse:7.73206
[175]	validation-rmse:7.72887
[176]	validation-rmse:7.72808
[177]	validation-rmse:7.72775
[178]	validation-rmse:7.72709
[179]	validation-rmse:7.72297
[180]	validation-rmse:7.71805
[181]	validation-rmse:7.71761
[182]	validation-rmse:7.71531
[183]	validation-rmse:7.71522
[184]	validation-rmse:7.71319
[185]	validation-rmse:7.71250
[186]	validation-rmse:7.71124
[187]	validation-rmse:7.70935
[188]	validation-rmse:7.70054
[189]	validation-rmse:7.69836
[190]	validation-rmse:7.69546
[191]	validation-rmse:7.69147
[192]	validation-rmse:7.68918
[193]	validation-rmse:7.68768
[194]	validation-rmse:7.68506
[195]	validation-rmse:7.68273
[196]	validation-rmse:7.67778
[197]	validation-rmse:7.67534
[198]	validation-rmse:7.67253
[199]	validation-rmse:7.67116
[200]	validation-rmse:7.66940
[201]	validation-rmse:7.66544
[202]	validation-rmse:7.66223
[203]	validation-rmse:7.65913
[204]	validation-rmse:7.65354
[205]	validation-rmse:7.65056
[206]	validation-rmse:7.64508
[207]	validation-rmse:7.64362
[208]	validation-rmse:7.63963
[209]	validation-rmse:7.63878
[210]	validation-rmse:7.63643
[211]	validation-rmse:7.63524
[212]	validation-rmse:7.63526
[213]	validation-rmse:7.63260
[214]	validation-rmse:7.63166
[215]	validation-rmse:7.63233
[216]	validation-rmse:7.63113
[217]	validation-rmse:7.62871
[218]	validation-rmse:7.62594
[219]	validation-rmse:7.62442
[220]	validation-rmse:7.62136
[221]	validation-rmse:7.62055
[222]	validation-rmse:7.61869
[223]	validation-rmse:7.61579
[224]	validation-rmse:7.61424
[225]	validation-rmse:7.61355
[226]	validation-rmse:7.61126
[227]	validation-rmse:7.60886
[228]	validation-rmse:7.60475
[229]	validation-rmse:7.60038
[230]	validation-rmse:7.59719
[231]	validation-rmse:7.59414
[232]	validation-rmse:7.58820
[233]	validation-rmse:7.58550
[234]	validation-rmse:7.58293
[235]	validation-rmse:7.58252
[236]	validation-rmse:7.57979
[237]	validation-rmse:7.57835
[238]	validation-rmse:7.57596
[239]	validation-rmse:7.57558
[240]	validation-rmse:7.57331
[241]	validation-rmse:7.57313
[242]	validation-rmse:7.57336
[243]	validation-rmse:7.57215
[244]	validation-rmse:7.57213
[245]	validation-rmse:7.57052
[246]	validation-rmse:7.56956
[247]	validation-rmse:7.56789
[248]	validation-rmse:7.56636
[249]	validation-rmse:7.56478
[250]	validation-rmse:7.56446
[251]	validation-rmse:7.56318
[252]	validation-rmse:7.56269
[253]	validation-rmse:7.56074
[254]	validation-rmse:7.56164
[255]	validation-rmse:7.56161
[256]	validation-rmse:7.56035
[257]	validation-rmse:7.55896
[258]	validation-rmse:7.55812
[259]	validation-rmse:7.55774
[260]	validation-rmse:7.55768
[261]	validation-rmse:7.55595
[262]	validation-rmse:7.55536
[263]	validation-rmse:7.55467
[264]	validation-rmse:7.55187
[265]	validation-rmse:7.55118
[266]	validation-rmse:7.55074
[267]	validation-rmse:7.54885
[268]	validation-rmse:7.54708
[269]	validation-rmse:7.54293
[270]	validation-rmse:7.54291
[271]	validation-rmse:7.54017
[272]	validation-rmse:7.53942
[273]	validation-rmse:7.53931
[274]	validation-rmse:7.53945
[275]	validation-rmse:7.53622
[276]	validation-rmse:7.53508
[277]	validation-rmse:7.53420
[278]	validation-rmse:7.53304
[279]	validation-rmse:7.53344
[280]	validation-rmse:7.53017
[281]	validation-rmse:7.52997
[282]	validation-rmse:7.53014
[283]	validation-rmse:7.52775
[284]	validation-rmse:7.52447
[285]	validation-rmse:7.52408
[286]	validation-rmse:7.52463
[287]	validation-rmse:7.52267
[288]	validation-rmse:7.52198
[289]	validation-rmse:7.52170
[290]	validation-rmse:7.52085
[291]	validation-rmse:7.52039
[292]	validation-rmse:7.52072
[293]	validation-rmse:7.51704
[294]	validation-rmse:7.51375
[295]	validation-rmse:7.51113
[296]	validation-rmse:7.51066
[297]	validation-rmse:7.51032
[298]	validation-rmse:7.50873
[299]	validation-rmse:7.50872
[300]	validation-rmse:7.50653
[301]	validation-rmse:7.50515
[302]	validation-rmse:7.50575
[303]	validation-rmse:7.50442
[304]	validation-rmse:7.50391
[305]	validation-rmse:7.50314
[306]	validation-rmse:7.50167
[307]	validation-rmse:7.50033
[308]	validation-rmse:7.49732
[309]	validation-rmse:7.49724
[310]	validation-rmse:7.49735
[311]	validation-rmse:7.49785
[312]	validation-rmse:7.49700
[313]	validation-rmse:7.49510
[314]	validation-rmse:7.49375
[315]	validation-rmse:7.49266
[316]	validation-rmse:7.49117
[317]	validation-rmse:7.48742
[318]	validation-rmse:7.48551
[319]	validation-rmse:7.48553
[320]	validation-rmse:7.48478
[321]	validation-rmse:7.48190
[322]	validation-rmse:7.47971
[323]	validation-rmse:7.47921
[324]	validation-rmse:7.47856
[325]	validation-rmse:7.47723
[326]	validation-rmse:7.47793
[327]	validation-rmse:7.47723
[328]	validation-rmse:7.47612
[329]	validation-rmse:7.47503
[330]	validation-rmse:7.47400
[331]	validation-rmse:7.47326
[332]	validation-rmse:7.47260
[333]	validation-rmse:7.47268
[334]	validation-rmse:7.47071
[335]	validation-rmse:7.46972
[336]	validation-rmse:7.46847
[337]	validation-rmse:7.46906
[338]	validation-rmse:7.46835
[339]	validation-rmse:7.46798
[340]	validation-rmse:7.46771
[341]	validation-rmse:7.46695
[342]	validation-rmse:7.46565
[343]	validation-rmse:7.46446
[344]	validation-rmse:7.46358
[345]	validation-rmse:7.46276
[346]	validation-rmse:7.46084
[347]	validation-rmse:7.46148
[348]	validation-rmse:7.45925
[349]	validation-rmse:7.45912
[350]	validation-rmse:7.45851
[351]	validation-rmse:7.45661
[352]	validation-rmse:7.45565
[353]	validation-rmse:7.45457
[354]	validation-rmse:7.45429
[355]	validation-rmse:7.45419
[356]	validation-rmse:7.45367
[357]	validation-rmse:7.45296
[358]	validation-rmse:7.45123
[359]	validation-rmse:7.45041
[360]	validation-rmse:7.44998
[361]	validation-rmse:7.44806
[362]	validation-rmse:7.44690
[363]	validation-rmse:7.44594
[364]	validation-rmse:7.44502
[365]	validation-rmse:7.44362
[366]	validation-rmse:7.44265
[367]	validation-rmse:7.44054
[368]	validation-rmse:7.43675
[369]	validation-rmse:7.43566
[370]	validation-rmse:7.43414
[371]	validation-rmse:7.43236
[372]	validation-rmse:7.43175
[373]	validation-rmse:7.42924
[374]	validation-rmse:7.42851
[375]	validation-rmse:7.42693
[376]	validation-rmse:7.42644
[377]	validation-rmse:7.42517
[378]	validation-rmse:7.42503
[379]	validation-rmse:7.42327
[380]	validation-rmse:7.42313
[381]	validation-rmse:7.42124
[382]	validation-rmse:7.42079
[383]	validation-rmse:7.42028
[384]	validation-rmse:7.41988
[385]	validation-rmse:7.41987
[386]	validation-rmse:7.41867
[387]	validation-rmse:7.41787
[388]	validation-rmse:7.41445
[389]	validation-rmse:7.41362
[390]	validation-rmse:7.41247
[391]	validation-rmse:7.41240
[392]	validation-rmse:7.41065
[393]	validation-rmse:7.40937
[394]	validation-rmse:7.40970
[395]	validation-rmse:7.40892
[396]	validation-rmse:7.40730
[397]	validation-rmse:7.40683
[398]	validation-rmse:7.40529
[399]	validation-rmse:7.40528
[400]	validation-rmse:7.40513
[401]	validation-rmse:7.40514
[402]	validation-rmse:7.40525
[403]	validation-rmse:7.40344
[404]	validation-rmse:7.40329
[405]	validation-rmse:7.40302
[406]	validation-rmse:7.40310
[407]	validation-rmse:7.40199
[408]	validation-rmse:7.40108
[409]	validation-rmse:7.40078
[410]	validation-rmse:7.39989
[411]	validation-rmse:7.39871
[412]	validation-rmse:7.39922
[413]	validation-rmse:7.39878
[414]	validation-rmse:7.39782
[415]	validation-rmse:7.39740
[416]	validation-rmse:7.39418
[417]	validation-rmse:7.39331
[418]	validation-rmse:7.39172
[419]	validation-rmse:7.39080
[420]	validation-rmse:7.39027
[421]	validation-rmse:7.38972
[422]	validation-rmse:7.38855
[423]	validation-rmse:7.38791
[424]	validation-rmse:7.38614
[425]	validation-rmse:7.38648
[426]	validation-rmse:7.38657
[427]	validation-rmse:7.38655
[428]	validation-rmse:7.38572
[429]	validation-rmse:7.38297
[430]	validation-rmse:7.38219
[431]	validation-rmse:7.38170
[432]	validation-rmse:7.38173
[433]	validation-rmse:7.38079
[434]	validation-rmse:7.38006
[435]	validation-rmse:7.37996
[436]	validation-rmse:7.38043
[437]	validation-rmse:7.38025
[438]	validation-rmse:7.37910
[439]	validation-rmse:7.37918
[440]	validation-rmse:7.37940
[441]	validation-rmse:7.37892
[442]	validation-rmse:7.37919
[443]	validation-rmse:7.37822
[444]	validation-rmse:7.37543
[445]	validation-rmse:7.37460
[446]	validation-rmse:7.37425
[447]	validation-rmse:7.37371
[448]	validation-rmse:7.37327
[449]	validation-rmse:7.37168
[450]	validation-rmse:7.37085
[451]	validation-rmse:7.37099
[452]	validation-rmse:7.37092
[453]	validation-rmse:7.37029
[454]	validation-rmse:7.36973
[455]	validation-rmse:7.36948
[456]	validation-rmse:7.36796
[457]	validation-rmse:7.36674
[458]	validation-rmse:7.36527
[459]	validation-rmse:7.36512
[460]	validation-rmse:7.36547
[461]	validation-rmse:7.36447
[462]	validation-rmse:7.36400
[463]	validation-rmse:7.36331
[464]	validation-rmse:7.36267
[465]	validation-rmse:7.36304
[466]	validation-rmse:7.36315
[467]	validation-rmse:7.36318
[468]	validation-rmse:7.36244
[469]	validation-rmse:7.36228
[470]	validation-rmse:7.36270
[471]	validation-rmse:7.36090
[472]	validation-rmse:7.36015
[473]	validation-rmse:7.35850
[474]	validation-rmse:7.35980
[475]	validation-rmse:7.35894
[476]	validation-rmse:7.35783
[477]	validation-rmse:7.35743
[478]	validation-rmse:7.35691
[479]	validation-rmse:7.35544
[480]	validation-rmse:7.35375
[481]	validation-rmse:7.35419
[482]	validation-rmse:7.35428
[483]	validation-rmse:7.35416
[484]	validation-rmse:7.35355
[485]	validation-rmse:7.35304
[486]	validation-rmse:7.35211
[487]	validation-rmse:7.35140
[488]	validation-rmse:7.35130
[489]	validation-rmse:7.35067
[490]	validation-rmse:7.34948
[491]	validation-rmse:7.34948
[492]	validation-rmse:7.34851
[493]	validation-rmse:7.34810
[494]	validation-rmse:7.34777
[495]	validation-rmse:7.34751
[496]	validation-rmse:7.34628
[497]	validation-rmse:7.34628
[498]	validation-rmse:7.34414
[499]	validation-rmse:7.34400
[500]	validation-rmse:7.34325
[501]	validation-rmse:7.34379
[502]	validation-rmse:7.34347
[503]	validation-rmse:7.34269
[504]	validation-rmse:7.34190
[505]	validation-rmse:7.34151
[506]	validation-rmse:7.34172
[507]	validation-rmse:7.34163
[508]	validation-rmse:7.34028
[509]	validation-rmse:7.34077
[510]	validation-rmse:7.34004
[511]	validation-rmse:7.33870
[512]	validation-rmse:7.33883
[513]	validation-rmse:7.33701
[514]	validation-rmse:7.33689
[515]	validation-rmse:7.33616
[516]	validation-rmse:7.33529
[517]	validation-rmse:7.33575
[518]	validation-rmse:7.33458
[519]	validation-rmse:7.33404
[520]	validation-rmse:7.33338
[521]	validation-rmse:7.33345
[522]	validation-rmse:7.33342
[523]	validation-rmse:7.33299
[524]	validation-rmse:7.33240
[525]	validation-rmse:7.33127
[526]	validation-rmse:7.33005
[527]	validation-rmse:7.32894
[528]	validation-rmse:7.32863
[529]	validation-rmse:7.32896
[530]	validation-rmse:7.32803
[531]	validation-rmse:7.32797
[532]	validation-rmse:7.32796
[533]	validation-rmse:7.32691
[534]	validation-rmse:7.32703
[535]	validation-rmse:7.32601
[536]	validation-rmse:7.32559
[537]	validation-rmse:7.32571
[538]	validation-rmse:7.32540
[539]	validation-rmse:7.32503
[540]	validation-rmse:7.32492
[541]	validation-rmse:7.32232
[542]	validation-rmse:7.32145
[543]	validation-rmse:7.32117
[544]	validation-rmse:7.31872
[545]	validation-rmse:7.31859
[546]	validation-rmse:7.31873
[547]	validation-rmse:7.31847
[548]	validation-rmse:7.31840
[549]	validation-rmse:7.31885
[550]	validation-rmse:7.31800
[551]	validation-rmse:7.31728
[552]	validation-rmse:7.31748
[553]	validation-rmse:7.31646
[554]	validation-rmse:7.31435
[555]	validation-rmse:7.31379
[556]	validation-rmse:7.31320
[557]	validation-rmse:7.31259
[558]	validation-rmse:7.31209
[559]	validation-rmse:7.31163
[560]	validation-rmse:7.31166
[561]	validation-rmse:7.31143
[562]	validation-rmse:7.31111
[563]	validation-rmse:7.31004
[564]	validation-rmse:7.30948
[565]	validation-rmse:7.30922
[566]	validation-rmse:7.30898
[567]	validation-rmse:7.30815
[568]	validation-rmse:7.30730
[569]	validation-rmse:7.30707
[570]	validation-rmse:7.30747
[571]	validation-rmse:7.30710
[572]	validation-rmse:7.30735
[573]	validation-rmse:7.30720
[574]	validation-rmse:7.30638
[575]	validation-rmse:7.30640
[576]	validation-rmse:7.30503
[577]	validation-rmse:7.30501
[578]	validation-rmse:7.30553
[579]	validation-rmse:7.30522
[580]	validation-rmse:7.30438
[581]	validation-rmse:7.30456
[582]	validation-rmse:7.30334
[583]	validation-rmse:7.30273
[584]	validation-rmse:7.30279
[585]	validation-rmse:7.30230
[586]	validation-rmse:7.30168
[587]	validation-rmse:7.30165
[588]	validation-rmse:7.30164
[589]	validation-rmse:7.30041
[590]	validation-rmse:7.30039
[591]	validation-rmse:7.30011
[592]	validation-rmse:7.29961
[593]	validation-rmse:7.29814
[594]	validation-rmse:7.29843
[595]	validation-rmse:7.29811
[596]	validation-rmse:7.29735
[597]	validation-rmse:7.29647
[598]	validation-rmse:7.29616
[599]	validation-rmse:7.29540
[600]	validation-rmse:7.29525
[601]	validation-rmse:7.29511
[602]	validation-rmse:7.29378
[603]	validation-rmse:7.29338
[604]	validation-rmse:7.29354
[605]	validation-rmse:7.29409
[606]	validation-rmse:7.29311
[607]	validation-rmse:7.29191
[608]	validation-rmse:7.29144
[609]	validation-rmse:7.29081
[610]	validation-rmse:7.28998
[611]	validation-rmse:7.28933
[612]	validation-rmse:7.28920
[613]	validation-rmse:7.28872
[614]	validation-rmse:7.28812
[615]	validation-rmse:7.28733
[616]	validation-rmse:7.28734
[617]	validation-rmse:7.28697
[618]	validation-rmse:7.28541
[619]	validation-rmse:7.28518
[620]	validation-rmse:7.28543
[621]	validation-rmse:7.28454
[622]	validation-rmse:7.28394
[623]	validation-rmse:7.28395
[624]	validation-rmse:7.28412
[625]	validation-rmse:7.28350
[626]	validation-rmse:7.28309
[627]	validation-rmse:7.28270
[628]	validation-rmse:7.28247
[629]	validation-rmse:7.28124
[630]	validation-rmse:7.28042
[631]	validation-rmse:7.28097
[632]	validation-rmse:7.28091
[633]	validation-rmse:7.27955
[634]	validation-rmse:7.27826
[635]	validation-rmse:7.27796
[636]	validation-rmse:7.27783
[637]	validation-rmse:7.27728
[638]	validation-rmse:7.27744
[639]	validation-rmse:7.27729
[640]	validation-rmse:7.27626
[641]	validation-rmse:7.27602
[642]	validation-rmse:7.27491
[643]	validation-rmse:7.27528
[644]	validation-rmse:7.27476
[645]	validation-rmse:7.27162
[646]	validation-rmse:7.27105
[647]	validation-rmse:7.27095
[648]	validation-rmse:7.27024
[649]	validation-rmse:7.27022
[650]	validation-rmse:7.27074
[651]	validation-rmse:7.27051
[652]	validation-rmse:7.27029
[653]	validation-rmse:7.26930
[654]	validation-rmse:7.26850
[655]	validation-rmse:7.26796
[656]	validation-rmse:7.26794
[657]	validation-rmse:7.26706
[658]	validation-rmse:7.26704
[659]	validation-rmse:7.26598
[660]	validation-rmse:7.26616
[661]	validation-rmse:7.26598
[662]	validation-rmse:7.26546
[663]	validation-rmse:7.26494
[664]	validation-rmse:7.26426
[665]	validation-rmse:7.26392
[666]	validation-rmse:7.26302
[667]	validation-rmse:7.26298
[668]	validation-rmse:7.26195
[669]	validation-rmse:7.26143
[670]	validation-rmse:7.26165

[14:55:36] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:9.73604
[2]	validation-rmse:9.41045
[3]	validation-rmse:9.22769
[4]	validation-rmse:9.01731
[5]	validation-rmse:8.93680
[6]	validation-rmse:8.84471
[7]	validation-rmse:8.74882
[8]	validation-rmse:8.71050
[9]	validation-rmse:8.68043
[10]	validation-rmse:8.65527
[11]	validation-rmse:8.61726
[12]	validation-rmse:8.59576
[13]	validation-rmse:8.58695
[14]	validation-rmse:8.57790
[15]	validation-rmse:8.57418
[16]	validation-rmse:8.56204
[17]	validation-rmse:8.54951
[18]	validation-rmse:8.53619
[19]	validation-rmse:8.52678
[20]	validation-rmse:8.51072
[21]	validation-rmse:8.49402
[22]	validation-rmse:8.47880
[23]	validation-rmse:8.46771
[24]	validation-rmse:8.45000
[25]	validation-rmse:8.42896
[26]	validation-rmse:8.40807
[27]	validation-rmse:8.39332
[28]	validation-rmse:8.38325
[29]	validation-rmse:8.36682
[30]	validation-rmse:8.35578
[31]	validation-rmse:8.34751
[32]	validation-rmse:8.33536
[33]	validation-rmse:8.32287
[34]	validation-rmse:8.31747
[35]	validation-rmse:8.31047
[36]	validation-rmse:8.30676
[37]	validation-rmse:8.29766
[38]	validation-rmse:8.29722
[39]	validation-rmse:8.29565
[40]	validation-rmse:8.28851
[41]	validation-rmse:8.28405
[42]	validation-rmse:8.28122
[43]	validation-rmse:8.27399
[44]	validation-rmse:8.26667
[45]	validation-rmse:8.26286
[46]	validation-rmse:8.25596
[47]	validation-rmse:8.25252
[48]	validation-rmse:8.24971
[49]	validation-rmse:8.24699
[50]	validation-rmse:8.24191
[51]	validation-rmse:8.23572
[52]	validation-rmse:8.22951
[53]	validation-rmse:8.22182
[54]	validation-rmse:8.22026
[55]	validation-rmse:8.21768
[56]	validation-rmse:8.21143
[57]	validation-rmse:8.20293
[58]	validation-rmse:8.19493
[59]	validation-rmse:8.18666
[60]	validation-rmse:8.18100
[61]	validation-rmse:8.17413
[62]	validation-rmse:8.17457
[63]	validation-rmse:8.16501
[64]	validation-rmse:8.15682
[65]	validation-rmse:8.15265
[66]	validation-rmse:8.14799
[67]	validation-rmse:8.14523
[68]	validation-rmse:8.13882
[69]	validation-rmse:8.13332
[70]	validation-rmse:8.12782
[71]	validation-rmse:8.12155
[72]	validation-rmse:8.12048
[73]	validation-rmse:8.11711
[74]	validation-rmse:8.11359
[75]	validation-rmse:8.11081
[76]	validation-rmse:8.10227
[77]	validation-rmse:8.10057
[78]	validation-rmse:8.09447
[79]	validation-rmse:8.09060
[80]	validation-rmse:8.08994
[81]	validation-rmse:8.08807
[82]	validation-rmse:8.08771
[83]	validation-rmse:8.08303
[84]	validation-rmse:8.08065
[85]	validation-rmse:8.07560
[86]	validation-rmse:8.07250
[87]	validation-rmse:8.06957
[88]	validation-rmse:8.06671
[89]	validation-rmse:8.06619
[90]	validation-rmse:8.06480
[91]	validation-rmse:8.06402
[92]	validation-rmse:8.06141
[93]	validation-rmse:8.05586
[94]	validation-rmse:8.05287
[95]	validation-rmse:8.04798
[96]	validation-rmse:8.03901
[97]	validation-rmse:8.03233
[98]	validation-rmse:8.02103
[99]	validation-rmse:8.01563
[100]	validation-rmse:8.01021
[101]	validation-rmse:8.00506
[102]	validation-rmse:7.99872
[103]	validation-rmse:7.99579
[104]	validation-rmse:7.99158
[105]	validation-rmse:7.99121
[106]	validation-rmse:7.98706
[107]	validation-rmse:7.98466
[108]	validation-rmse:7.97763
[109]	validation-rmse:7.97665
[110]	validation-rmse:7.97416
[111]	validation-rmse:7.97188
[112]	validation-rmse:7.96974
[113]	validation-rmse:7.96634
[114]	validation-rmse:7.96226
[115]	validation-rmse:7.96209
[116]	validation-rmse:7.95887
[117]	validation-rmse:7.95683
[118]	validation-rmse:7.95550
[119]	validation-rmse:7.95043
[120]	validation-rmse:7.94551
[121]	validation-rmse:7.93973
[122]	validation-rmse:7.93679
[123]	validation-rmse:7.93017
[124]	validation-rmse:7.92564
[125]	validation-rmse:7.92068
[126]	validation-rmse:7.91149
[127]	validation-rmse:7.90748
[128]	validation-rmse:7.90265
[129]	validation-rmse:7.89753
[130]	validation-rmse:7.89185
[131]	validation-rmse:7.88784
[132]	validation-rmse:7.88395
[133]	validation-rmse:7.87908
[134]	validation-rmse:7.87781
[135]	validation-rmse:7.87390
[136]	validation-rmse:7.87214
[137]	validation-rmse:7.87216
[138]	validation-rmse:7.86942
[139]	validation-rmse:7.86798
[140]	validation-rmse:7.86241
[141]	validation-rmse:7.86310
[142]	validation-rmse:7.85944
[143]	validation-rmse:7.85892
[144]	validation-rmse:7.85796
[145]	validation-rmse:7.85490
[146]	validation-rmse:7.85401
[147]	validation-rmse:7.85026
[148]	validation-rmse:7.84830
[149]	validation-rmse:7.84737
[150]	validation-rmse:7.84699
[151]	validation-rmse:7.84440
[152]	validation-rmse:7.84127
[153]	validation-rmse:7.84020
[154]	validation-rmse:7.83867
[155]	validation-rmse:7.83777
[156]	validation-rmse:7.83625
[157]	validation-rmse:7.83630
[158]	validation-rmse:7.83487
[159]	validation-rmse:7.83027
[160]	validation-rmse:7.82909
[161]	validation-rmse:7.82755
[162]	validation-rmse:7.82668
[163]	validation-rmse:7.82510
[164]	validation-rmse:7.82392
[165]	validation-rmse:7.82320
[166]	validation-rmse:7.82031
[167]	validation-rmse:7.81672
[168]	validation-rmse:7.81701
[169]	validation-rmse:7.81763
[170]	validation-rmse:7.81582
[171]	validation-rmse:7.81310
[172]	validation-rmse:7.80922
[173]	validation-rmse:7.80848
[174]	validation-rmse:7.80682
[175]	validation-rmse:7.80489
[176]	validation-rmse:7.80208
[177]	validation-rmse:7.80262
[178]	validation-rmse:7.80130
[179]	validation-rmse:7.79918
[180]	validation-rmse:7.79533
[181]	validation-rmse:7.79059
[182]	validation-rmse:7.78980
[183]	validation-rmse:7.78899
[184]	validation-rmse:7.78899
[185]	validation-rmse:7.78724
[186]	validation-rmse:7.78730
[187]	validation-rmse:7.78642
[188]	validation-rmse:7.78598
[189]	validation-rmse:7.77946
[190]	validation-rmse:7.77918
[191]	validation-rmse:7.77166
[192]	validation-rmse:7.76897
[193]	validation-rmse:7.76534
[194]	validation-rmse:7.76182
[195]	validation-rmse:7.75946
[196]	validation-rmse:7.75749
[197]	validation-rmse:7.75501
[198]	validation-rmse:7.75287
[199]	validation-rmse:7.75167
[200]	validation-rmse:7.75027
[201]	validation-rmse:7.75012
[202]	validation-rmse:7.74570
[203]	validation-rmse:7.74386
[204]	validation-rmse:7.73916
[205]	validation-rmse:7.73801
[206]	validation-rmse:7.73688
[207]	validation-rmse:7.73270
[208]	validation-rmse:7.72981
[209]	validation-rmse:7.72790
[210]	validation-rmse:7.72713
[211]	validation-rmse:7.72452
[212]	validation-rmse:7.72165
[213]	validation-rmse:7.72072
[214]	validation-rmse:7.72035
[215]	validation-rmse:7.71753
[216]	validation-rmse:7.71776
[217]	validation-rmse:7.71710
[218]	validation-rmse:7.71562
[219]	validation-rmse:7.71375
[220]	validation-rmse:7.71215
[221]	validation-rmse:7.71190
[222]	validation-rmse:7.71129
[223]	validation-rmse:7.71097
[224]	validation-rmse:7.70954
[225]	validation-rmse:7.70782
[226]	validation-rmse:7.70634
[227]	validation-rmse:7.70506
[228]	validation-rmse:7.70263
[229]	validation-rmse:7.70184
[230]	validation-rmse:7.69928
[231]	validation-rmse:7.69765
[232]	validation-rmse:7.69458
[233]	validation-rmse:7.69477
[234]	validation-rmse:7.69287
[235]	validation-rmse:7.69290
[236]	validation-rmse:7.69243
[237]	validation-rmse:7.68879
[238]	validation-rmse:7.68795
[239]	validation-rmse:7.68659
[240]	validation-rmse:7.68553
[241]	validation-rmse:7.68382
[242]	validation-rmse:7.68356
[243]	validation-rmse:7.68326
[244]	validation-rmse:7.68382
[245]	validation-rmse:7.68265
[246]	validation-rmse:7.68094
[247]	validation-rmse:7.67720
[248]	validation-rmse:7.67622
[249]	validation-rmse:7.67533
[250]	validation-rmse:7.67468
[251]	validation-rmse:7.67284
[252]	validation-rmse:7.67357
[253]	validation-rmse:7.67307
[254]	validation-rmse:7.67403
[255]	validation-rmse:7.66990
[256]	validation-rmse:7.66909
[257]	validation-rmse:7.66796
[258]	validation-rmse:7.66784
[259]	validation-rmse:7.66700
[260]	validation-rmse:7.66607
[261]	validation-rmse:7.66584
[262]	validation-rmse:7.66532
[263]	validation-rmse:7.66381
[264]	validation-rmse:7.66378
[265]	validation-rmse:7.66260
[266]	validation-rmse:7.66056
[267]	validation-rmse:7.65969
[268]	validation-rmse:7.65570
[269]	validation-rmse:7.65440
[270]	validation-rmse:7.65446
[271]	validation-rmse:7.65305
[272]	validation-rmse:7.65348
[273]	validation-rmse:7.65342
[274]	validation-rmse:7.65186
[275]	validation-rmse:7.65068
[276]	validation-rmse:7.64994
[277]	validation-rmse:7.64893
[278]	validation-rmse:7.64891
[279]	validation-rmse:7.64716
[280]	validation-rmse:7.64759
[281]	validation-rmse:7.64748
[282]	validation-rmse:7.64789
[283]	validation-rmse:7.64595
[284]	validation-rmse:7.64313
[285]	validation-rmse:7.64248
[286]	validation-rmse:7.64122
[287]	validation-rmse:7.64004
[288]	validation-rmse:7.63872
[289]	validation-rmse:7.63704
[290]	validation-rmse:7.63532
[291]	validation-rmse:7.63528
[292]	validation-rmse:7.63348
[293]	validation-rmse:7.63069
[294]	validation-rmse:7.63129
[295]	validation-rmse:7.62934
[296]	validation-rmse:7.62784
[297]	validation-rmse:7.62636
[298]	validation-rmse:7.62378
[299]	validation-rmse:7.62276
[300]	validation-rmse:7.62199
[301]	validation-rmse:7.61808
[302]	validation-rmse:7.61638
[303]	validation-rmse:7.61600
[304]	validation-rmse:7.61471
[305]	validation-rmse:7.61146
[306]	validation-rmse:7.61232
[307]	validation-rmse:7.61251
[308]	validation-rmse:7.61125
[309]	validation-rmse:7.60979
[310]	validation-rmse:7.60957
[311]	validation-rmse:7.60793
[312]	validation-rmse:7.60761
[313]	validation-rmse:7.60662
[314]	validation-rmse:7.60588
[315]	validation-rmse:7.60501
[316]	validation-rmse:7.60489
[317]	validation-rmse:7.60518
[318]	validation-rmse:7.60418
[319]	validation-rmse:7.60306
[320]	validation-rmse:7.60184
[321]	validation-rmse:7.59671
[322]	validation-rmse:7.59741
[323]	validation-rmse:7.59814
[324]	validation-rmse:7.59585
[325]	validation-rmse:7.59611
[326]	validation-rmse:7.59329
[327]	validation-rmse:7.59344
[328]	validation-rmse:7.59230
[329]	validation-rmse:7.59078
[330]	validation-rmse:7.59008
[331]	validation-rmse:7.58937
[332]	validation-rmse:7.58770
[333]	validation-rmse:7.58844
[334]	validation-rmse:7.58689
[335]	validation-rmse:7.58530
[336]	validation-rmse:7.58478
[337]	validation-rmse:7.58494
[338]	validation-rmse:7.58298
[339]	validation-rmse:7.58215
[340]	validation-rmse:7.58098
[341]	validation-rmse:7.57971
[342]	validation-rmse:7.57976
[343]	validation-rmse:7.57889
[344]	validation-rmse:7.57894
[345]	validation-rmse:7.57619
[346]	validation-rmse:7.57714
[347]	validation-rmse:7.57682
[348]	validation-rmse:7.57534
[349]	validation-rmse:7.57388
[350]	validation-rmse:7.57321
[351]	validation-rmse:7.57123
[352]	validation-rmse:7.57129
[353]	validation-rmse:7.56969
[354]	validation-rmse:7.57049
[355]	validation-rmse:7.56949
[356]	validation-rmse:7.56582
[357]	validation-rmse:7.56615
[358]	validation-rmse:7.56554
[359]	validation-rmse:7.56548
[360]	validation-rmse:7.56447
[361]	validation-rmse:7.56242
[362]	validation-rmse:7.56234
[363]	validation-rmse:7.56300
[364]	validation-rmse:7.56153
[365]	validation-rmse:7.56110
[366]	validation-rmse:7.55984
[367]	validation-rmse:7.55724
[368]	validation-rmse:7.55585
[369]	validation-rmse:7.55307
[370]	validation-rmse:7.55308
[371]	validation-rmse:7.55355
[372]	validation-rmse:7.55285
[373]	validation-rmse:7.55264
[374]	validation-rmse:7.55177
[375]	validation-rmse:7.54902
[376]	validation-rmse:7.54834
[377]	validation-rmse:7.54645
[378]	validation-rmse:7.54440
[379]	validation-rmse:7.54523
[380]	validation-rmse:7.54457
[381]	validation-rmse:7.54434
[382]	validation-rmse:7.54091
[383]	validation-rmse:7.54097
[384]	validation-rmse:7.53911
[385]	validation-rmse:7.53983
[386]	validation-rmse:7.53859
[387]	validation-rmse:7.53677
[388]	validation-rmse:7.53700
[389]	validation-rmse:7.53863
[390]	validation-rmse:7.53588
[391]	validation-rmse:7.53431
[392]	validation-rmse:7.53320
[393]	validation-rmse:7.53333
[394]	validation-rmse:7.53176
[395]	validation-rmse:7.53160
[396]	validation-rmse:7.52939
[397]	validation-rmse:7.52985
[398]	validation-rmse:7.52838
[399]	validation-rmse:7.52874
[400]	validation-rmse:7.52718
[401]	validation-rmse:7.52678
[402]	validation-rmse:7.52561
[403]	validation-rmse:7.52438
[404]	validation-rmse:7.52285
[405]	validation-rmse:7.52046
[406]	validation-rmse:7.52000
[407]	validation-rmse:7.51870
[408]	validation-rmse:7.51852
[409]	validation-rmse:7.51919
[410]	validation-rmse:7.51980
[411]	validation-rmse:7.51797
[412]	validation-rmse:7.51741
[413]	validation-rmse:7.51729
[414]	validation-rmse:7.51606
[415]	validation-rmse:7.51607
[416]	validation-rmse:7.51467
[417]	validation-rmse:7.51451
[418]	validation-rmse:7.51401
[419]	validation-rmse:7.51342
[420]	validation-rmse:7.51266
[421]	validation-rmse:7.51187
[422]	validation-rmse:7.51118
[423]	validation-rmse:7.51215
[424]	validation-rmse:7.50977
[425]	validation-rmse:7.50814
[426]	validation-rmse:7.50563
[427]	validation-rmse:7.50558
[428]	validation-rmse:7.50473
[429]	validation-rmse:7.50569
[430]	validation-rmse:7.50411
[431]	validation-rmse:7.50319
[432]	validation-rmse:7.50189
[433]	validation-rmse:7.50192
[434]	validation-rmse:7.50324
[435]	validation-rmse:7.50249
[436]	validation-rmse:7.50223
[437]	validation-rmse:7.50164
[438]	validation-rmse:7.50045
[439]	validation-rmse:7.49793
[440]	validation-rmse:7.49499
[441]	validation-rmse:7.49518
[442]	validation-rmse:7.49287
[443]	validation-rmse:7.49163
[444]	validation-rmse:7.49134
[445]	validation-rmse:7.49127
[446]	validation-rmse:7.49070
[447]	validation-rmse:7.48997
[448]	validation-rmse:7.48933
[449]	validation-rmse:7.48840
[450]	validation-rmse:7.48711
[451]	validation-rmse:7.48764
[452]	validation-rmse:7.48645
[453]	validation-rmse:7.48665
[454]	validation-rmse:7.48655
[455]	validation-rmse:7.48574
[456]	validation-rmse:7.48605
[457]	validation-rmse:7.48430
[458]	validation-rmse:7.48239
[459]	validation-rmse:7.48213
[460]	validation-rmse:7.48145
[461]	validation-rmse:7.48115
[462]	validation-rmse:7.48023
[463]	validation-rmse:7.48054
[464]	validation-rmse:7.47877
[465]	validation-rmse:7.47986
[466]	validation-rmse:7.47932
[467]	validation-rmse:7.47919
[468]	validation-rmse:7.47920
[469]	validation-rmse:7.47966
[470]	validation-rmse:7.47991
[471]	validation-rmse:7.47848
[472]	validation-rmse:7.47636
[473]	validation-rmse:7.47634
[474]	validation-rmse:7.47498
[475]	validation-rmse:7.47633
[476]	validation-rmse:7.47530
[477]	validation-rmse:7.47385
[478]	validation-rmse:7.47260
[479]	validation-rmse:7.47294
[480]	validation-rmse:7.47143
[481]	validation-rmse:7.47005
[482]	validation-rmse:7.47145
[483]	validation-rmse:7.47155
[484]	validation-rmse:7.46923
[485]	validation-rmse:7.47028
[486]	validation-rmse:7.46861
[487]	validation-rmse:7.46632
[488]	validation-rmse:7.46624
[489]	validation-rmse:7.46613
[490]	validation-rmse:7.46606
[491]	validation-rmse:7.46683
[492]	validation-rmse:7.46616
[493]	validation-rmse:7.46572
[494]	validation-rmse:7.46557
[495]	validation-rmse:7.46327
[496]	validation-rmse:7.46108
[497]	validation-rmse:7.46053
[498]	validation-rmse:7.46023
[499]	validation-rmse:7.45910
[500]	validation-rmse:7.45816
[501]	validation-rmse:7.45821
[502]	validation-rmse:7.45757
[503]	validation-rmse:7.45780
[504]	validation-rmse:7.45772
[505]	validation-rmse:7.45671
[506]	validation-rmse:7.45688
[507]	validation-rmse:7.45532
[508]	validation-rmse:7.45452
[509]	validation-rmse:7.45396
[510]	validation-rmse:7.45174
[511]	validation-rmse:7.45189
[512]	validation-rmse:7.45096
[513]	validation-rmse:7.45131
[514]	validation-rmse:7.45198
[515]	validation-rmse:7.45211
[516]	validation-rmse:7.45238
[517]	validation-rmse:7.45057
[518]	validation-rmse:7.45015
[519]	validation-rmse:7.44874
[520]	validation-rmse:7.44868
[521]	validation-rmse:7.44786
[522]	validation-rmse:7.44706
[523]	validation-rmse:7.44614
[524]	validation-rmse:7.44552
[525]	validation-rmse:7.44391
[526]	validation-rmse:7.44435
[527]	validation-rmse:7.44344
[528]	validation-rmse:7.44440
[529]	validation-rmse:7.44354
[530]	validation-rmse:7.44324
[531]	validation-rmse:7.44408
[532]	validation-rmse:7.44276
[533]	validation-rmse:7.44188
[534]	validation-rmse:7.44096
[535]	validation-rmse:7.44024
[536]	validation-rmse:7.43925
[537]	validation-rmse:7.43846
[538]	validation-rmse:7.43766
[539]	validation-rmse:7.43699
[540]	validation-rmse:7.43721
[541]	validation-rmse:7.43682
[542]	validation-rmse:7.43710
[543]	validation-rmse:7.43662
[544]	validation-rmse:7.43610
[545]	validation-rmse:7.43610
[546]	validation-rmse:7.43432
[547]	validation-rmse:7.43373
[548]	validation-rmse:7.43321
[549]	validation-rmse:7.43275
[550]	validation-rmse:7.43310
[551]	validation-rmse:7.43177
[552]	validation-rmse:7.43119
[553]	validation-rmse:7.43241
[554]	validation-rmse:7.43055
[555]	validation-rmse:7.43087
[556]	validation-rmse:7.42915
[557]	validation-rmse:7.42886
[558]	validation-rmse:7.42803
[559]	validation-rmse:7.42741
[560]	validation-rmse:7.42651
[561]	validation-rmse:7.42613
[562]	validation-rmse:7.42679
[563]	validation-rmse:7.42703
[564]	validation-rmse:7.42513
[565]	validation-rmse:7.42524
[566]	validation-rmse:7.42519
[567]	validation-rmse:7.42495
[568]	validation-rmse:7.42542
[569]	validation-rmse:7.42519
[570]	validation-rmse:7.42334
[571]	validation-rmse:7.42261
[572]	validation-rmse:7.42289
[573]	validation-rmse:7.42235
[574]	validation-rmse:7.42182
[575]	validation-rmse:7.42139
[576]	validation-rmse:7.42091
[577]	validation-rmse:7.42137
[578]	validation-rmse:7.42049
[579]	validation-rmse:7.42046
[580]	validation-rmse:7.42077
[581]	validation-rmse:7.41891
[582]	validation-rmse:7.41934
[583]	validation-rmse:7.41902
[584]	validation-rmse:7.41898
[585]	validation-rmse:7.41847
[586]	validation-rmse:7.41880
[587]	validation-rmse:7.41796
[588]	validation-rmse:7.41778
[589]	validation-rmse:7.41713
[590]	validation-rmse:7.41618
[591]	validation-rmse:7.41583
[592]	validation-rmse:7.41486
[593]	validation-rmse:7.41421
[594]	validation-rmse:7.41426
[595]	validation-rmse:7.41301
[596]	validation-rmse:7.41287
[597]	validation-rmse:7.41244
[598]	validation-rmse:7.41212
[599]	validation-rmse:7.41103
[600]	validation-rmse:7.41008
[601]	validation-rmse:7.41109
[602]	validation-rmse:7.41062
[603]	validation-rmse:7.41010
[604]	validation-rmse:7.40843
[605]	validation-rmse:7.40918
[606]	validation-rmse:7.40912
[607]	validation-rmse:7.40786
[608]	validation-rmse:7.40634
[609]	validation-rmse:7.40677
[610]	validation-rmse:7.40625
[611]	validation-rmse:7.40487
[612]	validation-rmse:7.40500
[613]	validation-rmse:7.40521
[614]	validation-rmse:7.40354
[615]	validation-rmse:7.40324
[616]	validation-rmse:7.40317
[617]	validation-rmse:7.40422
[618]	validation-rmse:7.40446
[619]	validation-rmse:7.40485
[620]	validation-rmse:7.40301
[621]	validation-rmse:7.40183
[622]	validation-rmse:7.40054
[623]	validation-rmse:7.40096
[624]	validation-rmse:7.40108
[625]	validation-rmse:7.40102
[626]	validation-rmse:7.39999
[627]	validation-rmse:7.39856
[628]	validation-rmse:7.39823
[629]	validation-rmse:7.39778
[630]	validation-rmse:7.39797
[631]	validation-rmse:7.39823
[632]	validation-rmse:7.39822
[633]	validation-rmse:7.39815
[634]	validation-rmse:7.39768
[635]	validation-rmse:7.39712
[636]	validation-rmse:7.39724
[637]	validation-rmse:7.39819
[638]	validation-rmse:7.39815
[639]	validation-rmse:7.39595
[640]	validation-rmse:7.39600
[641]	validation-rmse:7.39425
[642]	validation-rmse:7.39504
[643]	validation-rmse:7.39508
[644]	validation-rmse:7.39379
[645]	validation-rmse:7.39280
[646]	validation-rmse:7.39236
[647]	validation-rmse:7.39277
[648]	validation-rmse:7.39229
[649]	validation-rmse:7.39183
[650]	validation-rmse:7.39183
[651]	validation-rmse:7.39226
[652]	validation-rmse:7.39230
[653]	validation-rmse:7.39159
[654]	validation-rmse:7.39060
[655]	validation-rmse:7.39134
[656]	validation-rmse:7.38984
[657]	validation-rmse:7.39014
[658]	validation-rmse:7.39029
[659]	validation-rmse:7.38830
[660]	validation-rmse:7.38844
[661]	validation-rmse:7.38800
[662]	validation-rmse:7.38800
[663]	validation-rmse:7.38714
[664]	validation-rmse:7.38723
[665]	validation-rmse:7.38804
[666]	validation-rmse:7.38786
[667]	validation-rmse:7.38676
[668]	validation-rmse:7.38599
[669]	validation-rmse:7.38619
[670]	validation-rmse:7.38568

[14:58:39] WARNING: /Users/runner/work/xgboost/xgboost/python-package/build/temp.macosx-10.9-x86_64-3.7/xgboost/src/objective/regression_obj.cu:203: reg:linear is now deprecated in favor of reg:squarederror.

[1]	validation-rmse:15.19340
[2]	validation-rmse:13.37153
[3]	validation-rmse:12.03899
[4]	validation-rmse:11.12741
[5]	validation-rmse:10.39076
[6]	validation-rmse:9.93061
[7]	validation-rmse:9.61451
[8]	validation-rmse:9.29423
[9]	validation-rmse:9.12308
[10]	validation-rmse:8.99164
[11]	validation-rmse:8.86711
[12]	validation-rmse:8.78561
[13]	validation-rmse:8.70947
[14]	validation-rmse:8.63088
[15]	validation-rmse:8.56030
[16]	validation-rmse:8.52380
[17]	validation-rmse:8.47966
[18]	validation-rmse:8.42440
[19]	validation-rmse:8.39199
[20]	validation-rmse:8.36456
[21]	validation-rmse:8.34066
[22]	validation-rmse:8.32306
[23]	validation-rmse:8.30154
[24]	validation-rmse:8.28659
[25]	validation-rmse:8.27408
[26]	validation-rmse:8.24939
[27]	validation-rmse:8.23983
[28]	validation-rmse:8.22685
[29]	validation-rmse:8.21545
[30]	validation-rmse:8.19739
[31]	validation-rmse:8.19009
[32]	validation-rmse:8.18030
[33]	validation-rmse:8.17207
[34]	validation-rmse:8.16288
[35]	validation-rmse:8.15882
[36]	validation-rmse:8.14985
[37]	validation-rmse:8.13978
[38]	validation-rmse:8.12965
[39]	validation-rmse:8.12514
[40]	validation-rmse:8.11529
[41]	validation-rmse:8.10927
[42]	validation-rmse:8.10319
[43]	validation-rmse:8.09692
[44]	validation-rmse:8.08919
[45]	validation-rmse:8.08392
[46]	validation-rmse:8.07793
[47]	validation-rmse:8.07396
[48]	validation-rmse:8.06693
[49]	validation-rmse:8.05505
[50]	validation-rmse:8.04718
[51]	validation-rmse:8.04222
[52]	validation-rmse:8.03657
[53]	validation-rmse:8.03006
[54]	validation-rmse:8.02489
[55]	validation-rmse:8.01690
[56]	validation-rmse:8.01169
[57]	validation-rmse:8.00563
[58]	validation-rmse:8.00211
[59]	validation-rmse:7.99560
[60]	validation-rmse:7.99051
[61]	validation-rmse:7.98521
[62]	validation-rmse:7.97983
[63]	validation-rmse:7.97413
[64]	validation-rmse:7.96935
[65]	validation-rmse:7.96389
[66]	validation-rmse:7.96234
[67]	validation-rmse:7.95817
[68]	validation-rmse:7.95195
[69]	validation-rmse:7.94617
[70]	validation-rmse:7.94046
[71]	validation-rmse:7.93668
[72]	validation-rmse:7.93238
[73]	validation-rmse:7.92699
[74]	validation-rmse:7.92263
[75]	validation-rmse:7.91999
[76]	validation-rmse:7.91596
[77]	validation-rmse:7.91435
[78]	validation-rmse:7.90971
[79]	validation-rmse:7.90554
[80]	validation-rmse:7.90236
[81]	validation-rmse:7.89860
[82]	validation-rmse:7.89564
[83]	validation-rmse:7.89168
[84]	validation-rmse:7.88845
[85]	validation-rmse:7.88429
[86]	validation-rmse:7.88167
[87]	validation-rmse:7.87759
[88]	validation-rmse:7.87359
[89]	validation-rmse:7.87126
[90]	validation-rmse:7.86784
[91]	validation-rmse:7.86390
[92]	validation-rmse:7.86008
[93]	validation-rmse:7.85677
[94]	validation-rmse:7.85400
[95]	validation-rmse:7.85061
[96]	validation-rmse:7.84792
[97]	validation-rmse:7.84419
[98]	validation-rmse:7.84208
[99]	validation-rmse:7.83439
[100]	validation-rmse:7.83216
[101]	validation-rmse:7.82938
[102]	validation-rmse:7.82725
[103]	validation-rmse:7.82447
[104]	validation-rmse:7.82284
[105]	validation-rmse:7.82085
[106]	validation-rmse:7.81779
[107]	validation-rmse:7.81589
[108]	validation-rmse:7.81278
[109]	validation-rmse:7.80846
[110]	validation-rmse:7.80629
[111]	validation-rmse:7.80385
[112]	validation-rmse:7.80200
[113]	validation-rmse:7.79994
[114]	validation-rmse:7.79821
[115]	validation-rmse:7.79690
[116]	validation-rmse:7.79500
[117]	validation-rmse:7.79289
[118]	validation-rmse:7.79173
[119]	validation-rmse:7.78854
[120]	validation-rmse:7.78641
[121]	validation-rmse:7.78519
[122]	validation-rmse:7.78403
[123]	validation-rmse:7.78345
[124]	validation-rmse:7.78159
[125]	validation-rmse:7.78007
[126]	validation-rmse:7.77846
[127]	validation-rmse:7.77564
[128]	validation-rmse:7.77251
[129]	validation-rmse:7.77132
[130]	validation-rmse:7.76965
[131]	validation-rmse:7.76811
[132]	validation-rmse:7.76619
[133]	validation-rmse:7.76372
[134]	validation-rmse:7.76234
[135]	validation-rmse:7.76036
[136]	validation-rmse:7.75934
[137]	validation-rmse:7.75568
[138]	validation-rmse:7.75051
[139]	validation-rmse:7.74999
[140]	validation-rmse:7.74640
[141]	validation-rmse:7.74400
[142]	validation-rmse:7.74210
[143]	validation-rmse:7.74099
[144]	validation-rmse:7.73667
[145]	validation-rmse:7.73334
[146]	validation-rmse:7.72921
[147]	validation-rmse:7.72640
[148]	validation-rmse:7.72328
[149]	validation-rmse:7.72086
[150]	validation-rmse:7.71831
[151]	validation-rmse:7.71594
[152]	validation-rmse:7.71385
[153]	validation-rmse:7.71176
[154]	validation-rmse:7.70861
[155]	validation-rmse:7.70520
[156]	validation-rmse:7.70158
[157]	validation-rmse:7.70001
[158]	validation-rmse:7.69717
[159]	validation-rmse:7.69551
[160]	validation-rmse:7.69351
[161]	validation-rmse:7.69014
[162]	validation-rmse:7.68764
[163]	validation-rmse:7.68531
[164]	validation-rmse:7.68361
[165]	validation-rmse:7.68226
[166]	validation-rmse:7.67994
[167]	validation-rmse:7.67808
[168]	validation-rmse:7.67668
[169]	validation-rmse:7.67448
[170]	validation-rmse:7.67224
[171]	validation-rmse:7.66870
[172]	validation-rmse:7.66684
[173]	validation-rmse:7.66507
[174]	validation-rmse:7.66431
[175]	validation-rmse:7.66321
[176]	validation-rmse:7.66192
[177]	validation-rmse:7.66050
[178]	validation-rmse:7.65759
[179]	validation-rmse:7.65610
[180]	validation-rmse:7.65459
[181]	validation-rmse:7.65169
[182]	validation-rmse:7.64929
[183]	validation-rmse:7.64836
[184]	validation-rmse:7.64621
[185]	validation-rmse:7.64516
[186]	validation-rmse:7.64344
[187]	validation-rmse:7.64245
[188]	validation-rmse:7.64126
[189]	validation-rmse:7.64004
[190]	validation-rmse:7.63882
[191]	validation-rmse:7.63822
[192]	validation-rmse:7.63705
[193]	validation-rmse:7.63475
[194]	validation-rmse:7.63314
[195]	validation-rmse:7.63253
[196]	validation-rmse:7.63191
[197]	validation-rmse:7.63085
[198]	validation-rmse:7.62999
[199]	validation-rmse:7.62498
[200]	validation-rmse:7.62359
[201]	validation-rmse:7.62073
[202]	validation-rmse:7.61923
[203]	validation-rmse:7.61793
[204]	validation-rmse:7.61454
[205]	validation-rmse:7.61179
[206]	validation-rmse:7.60879
[207]	validation-rmse:7.60665
[208]	validation-rmse:7.60367
[209]	validation-rmse:7.60082
[210]	validation-rmse:7.59818
[211]	validation-rmse:7.59464
[212]	validation-rmse:7.59319
[213]	validation-rmse:7.58812
[214]	validation-rmse:7.58418
[215]	validation-rmse:7.58253
[216]	validation-rmse:7.57951
[217]	validation-rmse:7.57536
[218]	validation-rmse:7.57160
[219]	validation-rmse:7.56723
[220]	validation-rmse:7.56314
[221]	validation-rmse:7.56020
[222]	validation-rmse:7.55507
[223]	validation-rmse:7.55136
[224]	validation-rmse:7.54633
[225]	validation-rmse:7.54385
[226]	validation-rmse:7.54074
[227]	validation-rmse:7.53855
[228]	validation-rmse:7.53621
[229]	validation-rmse:7.53295
[230]	validation-rmse:7.52916
[231]	validation-rmse:7.52511
[232]	validation-rmse:7.52215
[233]	validation-rmse:7.52110
[234]	validation-rmse:7.51874
[235]	validation-rmse:7.51754
[236]	validation-rmse:7.51550
[237]	validation-rmse:7.51268
[238]	validation-rmse:7.51160
[239]	validation-rmse:7.50899
[240]	validation-rmse:7.50634
[241]	validation-rmse:7.50299
[242]	validation-rmse:7.50194
[243]	validation-rmse:7.50092
[244]	validation-rmse:7.49970
[245]	validation-rmse:7.49807
[246]	validation-rmse:7.49702
[247]	validation-rmse:7.49558
[248]	validation-rmse:7.49375
[249]	validation-rmse:7.49234
[250]	validation-rmse:7.48944
[251]	validation-rmse:7.48807
[252]	validation-rmse:7.48764
[253]	validation-rmse:7.48656
[254]	validation-rmse:7.48565
[255]	validation-rmse:7.48493
[256]	validation-rmse:7.48385
[257]	validation-rmse:7.48254
[258]	validation-rmse:7.48183
[259]	validation-rmse:7.48154
[260]	validation-rmse:7.48041
[261]	validation-rmse:7.47960
[262]	validation-rmse:7.47773
[263]	validation-rmse:7.47560
[264]	validation-rmse:7.47457
[265]	validation-rmse:7.47453
[266]	validation-rmse:7.47356
[267]	validation-rmse:7.47267
[268]	validation-rmse:7.47039
[269]	validation-rmse:7.47033
[270]	validation-rmse:7.46983
[271]	validation-rmse:7.46865
[272]	validation-rmse:7.46817
[273]	validation-rmse:7.46775
[274]	validation-rmse:7.46736
[275]	validation-rmse:7.46551
[276]	validation-rmse:7.46452
[277]	validation-rmse:7.46396
[278]	validation-rmse:7.46293
[279]	validation-rmse:7.46189
[280]	validation-rmse:7.46094
[281]	validation-rmse:7.46022
[282]	validation-rmse:7.45950
[283]	validation-rmse:7.45924
[284]	validation-rmse:7.45831
[285]	validation-rmse:7.45764
[286]	validation-rmse:7.45672
[287]	validation-rmse:7.45563
[288]	validation-rmse:7.45460
[289]	validation-rmse:7.45382
[290]	validation-rmse:7.45318
[291]	validation-rmse:7.45311
[292]	validation-rmse:7.45231
[293]	validation-rmse:7.45201
[294]	validation-rmse:7.45070
[295]	validation-rmse:7.44992
[296]	validation-rmse:7.44919
[297]	validation-rmse:7.44711
[298]	validation-rmse:7.44592
[299]	validation-rmse:7.44337
[300]	validation-rmse:7.44312
[301]	validation-rmse:7.44124
[302]	validation-rmse:7.43977
[303]	validation-rmse:7.43861
[304]	validation-rmse:7.43750
[305]	validation-rmse:7.43602
[306]	validation-rmse:7.43468
[307]	validation-rmse:7.43465
[308]	validation-rmse:7.43344
[309]	validation-rmse:7.43230
[310]	validation-rmse:7.43142
[311]	validation-rmse:7.43155
[312]	validation-rmse:7.43103
[313]	validation-rmse:7.43041
[314]	validation-rmse:7.42907
[315]	validation-rmse:7.42830
[316]	validation-rmse:7.42738
[317]	validation-rmse:7.42657
[318]	validation-rmse:7.42530
[319]	validation-rmse:7.42410
[320]	validation-rmse:7.42295
[321]	validation-rmse:7.42207
[322]	validation-rmse:7.42179
[323]	validation-rmse:7.42109
[324]	validation-rmse:7.41958
[325]	validation-rmse:7.41892
[326]	validation-rmse:7.41793
[327]	validation-rmse:7.41719
[328]	validation-rmse:7.41618
[329]	validation-rmse:7.41556
[330]	validation-rmse:7.41484
[331]	validation-rmse:7.41406
[332]	validation-rmse:7.41408
[333]	validation-rmse:7.41362
[334]	validation-rmse:7.41370
[335]	validation-rmse:7.41177
[336]	validation-rmse:7.41117
[337]	validation-rmse:7.41089
[338]	validation-rmse:7.41014
[339]	validation-rmse:7.40981
[340]	validation-rmse:7.40940
[341]	validation-rmse:7.40830
[342]	validation-rmse:7.40733
[343]	validation-rmse:7.40663
[344]	validation-rmse:7.40640
[345]	validation-rmse:7.40540
[346]	validation-rmse:7.40352
[347]	validation-rmse:7.40290
[348]	validation-rmse:7.40251
[349]	validation-rmse:7.40213
[350]	validation-rmse:7.40145
[351]	validation-rmse:7.40160
[352]	validation-rmse:7.39995
[353]	validation-rmse:7.39934
[354]	validation-rmse:7.39848
[355]	validation-rmse:7.39845
[356]	validation-rmse:7.39762
[357]	validation-rmse:7.39769
[358]	validation-rmse:7.39628
[359]	validation-rmse:7.39476
[360]	validation-rmse:7.39412
[361]	validation-rmse:7.39309
[362]	validation-rmse:7.39187
[363]	validation-rmse:7.39133
[364]	validation-rmse:7.39048
[365]	validation-rmse:7.39012
[366]	validation-rmse:7.39021
[367]	validation-rmse:7.38929
[368]	validation-rmse:7.38784
[369]	validation-rmse:7.38734
[370]	validation-rmse:7.38533
[371]	validation-rmse:7.38489
[372]	validation-rmse:7.38391
[373]	validation-rmse:7.38414
[374]	validation-rmse:7.38402
[375]	validation-rmse:7.38340
[376]	validation-rmse:7.38197
[377]	validation-rmse:7.38053
[378]	validation-rmse:7.37940
[379]	validation-rmse:7.37922
[380]	validation-rmse:7.37775
[381]	validation-rmse:7.37695
[382]	validation-rmse:7.37608
[383]	validation-rmse:7.37450
[384]	validation-rmse:7.37365
[385]	validation-rmse:7.37305
[386]	validation-rmse:7.37234
[387]	validation-rmse:7.37068
[388]	validation-rmse:7.36987
[389]	validation-rmse:7.36958
[390]	validation-rmse:7.36916
[391]	validation-rmse:7.36808
[392]	validation-rmse:7.36753
[393]	validation-rmse:7.36683
[394]	validation-rmse:7.36607
[395]	validation-rmse:7.36538
[396]	validation-rmse:7.36431
[397]	validation-rmse:7.36214
[398]	validation-rmse:7.36094
[399]	validation-rmse:7.35987
[400]	validation-rmse:7.35889
[401]	validation-rmse:7.35842
[402]	validation-rmse:7.35789
[403]	validation-rmse:7.35648
[404]	validation-rmse:7.35520
[405]	validation-rmse:7.35406
[406]	validation-rmse:7.35373
[407]	validation-rmse:7.35260
[408]	validation-rmse:7.35153
[409]	validation-rmse:7.35045
[410]	validation-rmse:7.34938
[411]	validation-rmse:7.34949
[412]	validation-rmse:7.34910
[413]	validation-rmse:7.34784
[414]	validation-rmse:7.34631
[415]	validation-rmse:7.34527
[416]	validation-rmse:7.34389
[417]	validation-rmse:7.34333
[418]	validation-rmse:7.34330
[419]	validation-rmse:7.34310
[420]	validation-rmse:7.34269
[421]	validation-rmse:7.34254
[422]	validation-rmse:7.34195
[423]	validation-rmse:7.33847
[424]	validation-rmse:7.33770
[425]	validation-rmse:7.33745
[426]	validation-rmse:7.33654
[427]	validation-rmse:7.33465
[428]	validation-rmse:7.33202
[429]	validation-rmse:7.33208
[430]	validation-rmse:7.33184
[431]	validation-rmse:7.33131
[432]	validation-rmse:7.33083
[433]	validation-rmse:7.33080
[434]	validation-rmse:7.33055
[435]	validation-rmse:7.32919
[436]	validation-rmse:7.32847
[437]	validation-rmse:7.32746
[438]	validation-rmse:7.32772
[439]	validation-rmse:7.32688
[440]	validation-rmse:7.32644
[441]	validation-rmse:7.32610
[442]	validation-rmse:7.32536
[443]	validation-rmse:7.32428
[444]	validation-rmse:7.32382
[445]	validation-rmse:7.32313
[446]	validation-rmse:7.32319
[447]	validation-rmse:7.32294
[448]	validation-rmse:7.32255
[449]	validation-rmse:7.32265
[450]	validation-rmse:7.32205
[451]	validation-rmse:7.32184
[452]	validation-rmse:7.32081
[453]	validation-rmse:7.32041
[454]	validation-rmse:7.32018
[455]	validation-rmse:7.31926
[456]	validation-rmse:7.31906
[457]	validation-rmse:7.31892
[458]	validation-rmse:7.31746
[459]	validation-rmse:7.31663
[460]	validation-rmse:7.31528
[461]	validation-rmse:7.31367
[462]	validation-rmse:7.31366
[463]	validation-rmse:7.31310
[464]	validation-rmse:7.31259
[465]	validation-rmse:7.31169
[466]	validation-rmse:7.31168
[467]	validation-rmse:7.31149
[468]	validation-rmse:7.31115
[469]	validation-rmse:7.31026
[470]	validation-rmse:7.30902
[471]	validation-rmse:7.30897
[472]	validation-rmse:7.30859
[473]	validation-rmse:7.30837
[474]	validation-rmse:7.30786
[475]	validation-rmse:7.30798
[476]	validation-rmse:7.30742
[477]	validation-rmse:7.30712
[478]	validation-rmse:7.30622
[479]	validation-rmse:7.30574
[480]	validation-rmse:7.30548
[481]	validation-rmse:7.30485
[482]	validation-rmse:7.30413
[483]	validation-rmse:7.30372
[484]	validation-rmse:7.30356
[485]	validation-rmse:7.30271
[486]	validation-rmse:7.30243
[487]	validation-rmse:7.30204
[488]	validation-rmse:7.30087
[489]	validation-rmse:7.30052
[490]	validation-rmse:7.30065
[491]	validation-rmse:7.29978
[492]	validation-rmse:7.29906
[493]	validation-rmse:7.29861
[494]	validation-rmse:7.29785
[495]	validation-rmse:7.29692
[496]	validation-rmse:7.29587
[497]	validation-rmse:7.29539
[498]	validation-rmse:7.29359
[499]	validation-rmse:7.29377
[500]	validation-rmse:7.29409
[501]	validation-rmse:7.29376
[502]	validation-rmse:7.29347
[503]	validation-rmse:7.29291
[504]	validation-rmse:7.29297
[505]	validation-rmse:7.29206
[506]	validation-rmse:7.29170
[507]	validation-rmse:7.29115
[508]	validation-rmse:7.29108
[509]	validation-rmse:7.29068
[510]	validation-rmse:7.28965
[511]	validation-rmse:7.28875
[512]	validation-rmse:7.28796
[513]	validation-rmse:7.28726
[514]	validation-rmse:7.28710
[515]	validation-rmse:7.28680
[516]	validation-rmse:7.28597
[517]	validation-rmse:7.28627
[518]	validation-rmse:7.28606
[519]	validation-rmse:7.28554
[520]	validation-rmse:7.28561
[521]	validation-rmse:7.28530
[522]	validation-rmse:7.28466
[523]	validation-rmse:7.28373
[524]	validation-rmse:7.28360
[525]	validation-rmse:7.28353
[526]	validation-rmse:7.28356
[527]	validation-rmse:7.28342
[528]	validation-rmse:7.28261
[529]	validation-rmse:7.28173
[530]	validation-rmse:7.28199
[531]	validation-rmse:7.28243
[532]	validation-rmse:7.28131
[533]	validation-rmse:7.28088
[534]	validation-rmse:7.27998
[535]	validation-rmse:7.27947
[536]	validation-rmse:7.27880
[537]	validation-rmse:7.27849
[538]	validation-rmse:7.27817
[539]	validation-rmse:7.27794
[540]	validation-rmse:7.27780
[541]	validation-rmse:7.27708
[542]	validation-rmse:7.27632
[543]	validation-rmse:7.27359
[544]	validation-rmse:7.27277
[545]	validation-rmse:7.27197
[546]	validation-rmse:7.27167
[547]	validation-rmse:7.27167
[548]	validation-rmse:7.27140
[549]	validation-rmse:7.27116
[550]	validation-rmse:7.27118
[551]	validation-rmse:7.27086
[552]	validation-rmse:7.27065
[553]	validation-rmse:7.27021
[554]	validation-rmse:7.26914
[555]	validation-rmse:7.26911
[556]	validation-rmse:7.26937
[557]	validation-rmse:7.26947
[558]	validation-rmse:7.26972
[559]	validation-rmse:7.26971
[560]	validation-rmse:7.26912
[561]	validation-rmse:7.26853
[562]	validation-rmse:7.26889
[563]	validation-rmse:7.26813
[564]	validation-rmse:7.26761
[565]	validation-rmse:7.26721
[566]	validation-rmse:7.26667
[567]	validation-rmse:7.26673
[568]	validation-rmse:7.26607
[569]	validation-rmse:7.26572
[570]	validation-rmse:7.26457
[571]	validation-rmse:7.26468
[572]	validation-rmse:7.26445
[573]	validation-rmse:7.26457
[574]	validation-rmse:7.26402
[575]	validation-rmse:7.26390
[576]	validation-rmse:7.26336
[577]	validation-rmse:7.26228
[578]	validation-rmse:7.26124
[579]	validation-rmse:7.26080
[580]	validation-rmse:7.26077
[581]	validation-rmse:7.26084
[582]	validation-rmse:7.26071
[583]	validation-rmse:7.25973
[584]	validation-rmse:7.25939
[585]	validation-rmse:7.25876
[586]	validation-rmse:7.25775
[587]	validation-rmse:7.25531
[588]	validation-rmse:7.25510
[589]	validation-rmse:7.25396
[590]	validation-rmse:7.25373
[591]	validation-rmse:7.25310
[592]	validation-rmse:7.25148
[593]	validation-rmse:7.25063
[594]	validation-rmse:7.24989
[595]	validation-rmse:7.25002
[596]	validation-rmse:7.24960
[597]	validation-rmse:7.24931
[598]	validation-rmse:7.24806
[599]	validation-rmse:7.24727
[600]	validation-rmse:7.24660
[601]	validation-rmse:7.24524
[602]	validation-rmse:7.24459
[603]	validation-rmse:7.24420
[604]	validation-rmse:7.24396
[605]	validation-rmse:7.24179
[606]	validation-rmse:7.23969
[607]	validation-rmse:7.23876
[608]	validation-rmse:7.23853
[609]	validation-rmse:7.23691
[610]	validation-rmse:7.23559
[611]	validation-rmse:7.23472
[612]	validation-rmse:7.23431
[613]	validation-rmse:7.23305
[614]	validation-rmse:7.23241
[615]	validation-rmse:7.23148
[616]	validation-rmse:7.22995
[617]	validation-rmse:7.22855
[618]	validation-rmse:7.22802
[619]	validation-rmse:7.22809
[620]	validation-rmse:7.22634
[621]	validation-rmse:7.22549
[622]	validation-rmse:7.22397
[623]	validation-rmse:7.22277
[624]	validation-rmse:7.22241
[625]	validation-rmse:7.22166
[626]	validation-rmse:7.22108
[627]	validation-rmse:7.22030
[628]	validation-rmse:7.22043
[629]	validation-rmse:7.21954
[630]	validation-rmse:7.21920
[631]	validation-rmse:7.21801
[632]	validation-rmse:7.21790
[633]	validation-rmse:7.21669
[634]	validation-rmse:7.21620
[635]	validation-rmse:7.21607
[636]	validation-rmse:7.21595
[637]	validation-rmse:7.21489
[638]	validation-rmse:7.21467
[639]	validation-rmse:7.21396
[640]	validation-rmse:7.21418
[641]	validation-rmse:7.21339
[642]	validation-rmse:7.21366
[643]	validation-rmse:7.21340
[644]	validation-rmse:7.21203
[645]	validation-rmse:7.21163
[646]	validation-rmse:7.21160
[647]	validation-rmse:7.21096
[648]	validation-rmse:7.20999
[649]	validation-rmse:7.20961
[650]	validation-rmse:7.20889
[651]	validation-rmse:7.20873
[652]	validation-rmse:7.20817
[653]	validation-rmse:7.20756
[654]	validation-rmse:7.20736
[655]	validation-rmse:7.20781
[656]	validation-rmse:7.20720
[657]	validation-rmse:7.20781
[658]	validation-rmse:7.20755
[659]	validation-rmse:7.20693
[660]	validation-rmse:7.20672
[661]	validation-rmse:7.20616
[662]	validation-rmse:7.20561
[663]	validation-rmse:7.20542
[664]	validation-rmse:7.20488
[665]	validation-rmse:7.20504
[666]	validation-rmse:7.20440
[667]	validation-rmse:7.20408
[668]	validation-rmse:7.20308
[669]	validation-rmse:7.20285
[670]	validation-rmse:7.20279

In [ ]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor
from sklearn.svm import LinearSVR

mlflow.sklearn.autolog()

for model_class in (RandomForestRegressor, GradientBoostingRegressor, ExtraTreesRegressor, LinearSVR):

    with mlflow.start_run():

        mlflow.log_param("train-data-path", "./data/green_tripdata_2021-01.csv")
        mlflow.log_param("valid-data-path", "./data/green_tripdata_2021-02.csv")
        mlflow.log_artifact("models/preprocessor.b", artifact_path="preprocessor")

        mlmodel = model_class()
        mlmodel.fit(X_train, y_train)

        y_pred = mlmodel.predict(X_val)
        rmse = mean_squared_error(y_val, y_pred, squared=False)
        mlflow.log_metric("rmse", rmse)